### ISSUE TITLE
Can't add a new font

### ISSUE THREAD

**Issue by Rekengappy** [xulihang/ImageTrans-docs#100]
Good afternoon, I ran into a problem. I can't "Read from PS" a new font. Maybe I'm doing something wrong. But in any case, several questions arose:

1. Do you plan to add the function of importing directly TTF files to the program?
2. Is it possible to somehow quickly export the file in psd format to continue working with it in Photoshop?
3. In case I just do not understand the instructions for reading the font from the PS: can you record a short video tutorial on this topic?

**Comment by xulihang** [comment]
You can learn about PS interaction here: <https://imagetrans.readthedocs.io/en/latest/interoperation.html#psd>.

1. This should be possible as I found that some fonts newly installed in the system do not appear in the font list.
2. There are two versions of Photoshop scripts: au3 and javascript. If you have installed Photoshop correctly and use Windows, you can generate PSD directly. If not, you may have to use `addLayers.jsx` script.
3. The font name in Photoshop is special so we need to get it from PS. You can input the font name directly if you know the name like `ArialMT`. Or you have to get it using scripts by following the guide here: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#id24

**Comment by xulihang** [comment]
As requested, I've recorded a video showing the process of reading font name from photoshop.

https://user-images.githubusercontent.com/5462205/141479458-efd31045-5979-4e28-84b9-5e70c3c8ff68.mp4

**Comment by Rekengappy** [comment]
Thanks, I managed to find out the name of the font, but not import it into the project. 
Maybe it's all about the versions of Windows? 
Apparently, you are not using Windows 10, as I am

**Comment by xulihang** [comment]
This should not be related to the system. I am using Windows 10 and Photoshop CS3. I've tested Photoshop 2018, 2019 as well. How did you install Photoshop? If you've installed it correctly, the program should be able to interact with it through the COM interface.

**Comment by xulihang** [comment]
Importing TTF files is added in v1.5.0.
