### ISSUE TITLE
v1.5.0 Update

### ISSUE THREAD

**Issue by ShadowXRS** [xulihang/ImageTrans-docs#105]
Where can I download the latest version (v1.5.0) ?

**Comment by xulihang** [comment]
It has been discussed here: https://github.com/xulihang/ImageTrans-docs/issues/74

**Comment by ShadowXRS** [comment]
Can you tell me where can I get the onedrive link? after I purchased ImageTrans (August 2021), my gmail only contains order information and there is no onedrive link, can you help me?

**Comment by xulihang** [comment]
Please send an email to [admin@basiccat.org](mailto:admin@basiccat.org). I will send you the link.
