### ISSUE TITLE
Addtional Plugins on a Linux System

### ISSUE THREAD

**Issue by Desmo5574** [xulihang/ImageTrans-docs#107]
I've been looking over the plugins in the git repo and was wondering how to install and use these since they aren't in jar format?

**Comment by xulihang** [comment]
You can download the jars here: https://github.com/xulihang/ImageTrans_plugins/releases/tag/plugins

You can also compile them to jars by yourself using B4J (windows app).

**Comment by Desmo5574** [comment]
Aww man, sorry Xu, if I would have looked around a little more I would have found my answer. 
I was looking at them individually and taking a look at the code. 
I tried installing B4J via wine development. It installs but won't run...I'm going to have to tinker around with it to find out what's going on in order to get it to run properly. 
Thanks again!!
