### ISSUE TITLE
Better machine translator

### ISSUE THREAD

**Issue by mspykerez** [xulihang/ImageTrans-docs#108]
Can you add support for this translation model that is currently being trained and is already giving the best japanese to english results out there https://www.reddit.com/r/visualnovels/comments/qnsgd2/from_sugoi_translator_developer_today_i_will_send/

It's free and can work offline. I think it would be a great addition to ImageTrans software because the only thing it's lacking right now is quality automatic translations.

**Comment by xulihang** [comment]
Okay. I've made a plugin for it: https://github.com/xulihang/ImageTrans_plugins/tree/master/sugoiMT

Usage:

1. Start the server.
  
  ```
  Sugoi-Japanese-Translator-V3.0\backendServer\Program-Backend\Sugoi-Translator-Offline\offlineTranslation\activateOfflineTranslationServer.bat
  ```

2. Put the plugin in the plugins folder and enable it in Preferences.
  
  [sugoiMT_plugin.zip](https://github.com/xulihang/ImageTrans-docs/files/7631125/sugoiMT_plugin.zip)
  
  ![image](https://user-images.githubusercontent.com/5462205/144177803-a1033c94-788a-4366-9673-97edaf003239.png)

**Comment by mspykerez** [comment]
Thx! Looks good.

Any plans to provide a free trial of the software or make a 'lite' or something version where the user can fill it up with their own OCR and translation models for offline use?
So like making it somewhat free if we use our own custom OCR and Translation engines or ones that are already available out there for free.

I get that we need to pay if we wish to harvest the power of online services but I think it would be great if we also got the chance to use our own local machine with our own models thus eliminating the cost and dependence on a online server.

I think ImageTrans can become a great tool for batch translating and whatnot but I don't think many people know about it and the ones who know just stop at the gate when they realize they can't even try it without paying.

You are on your own right to do what you see best.
And again, my thanks.

**Comment by xulihang** [comment]
A trial version will not be provided as it will add extra cost whether it is user support or maintenance. Since users have to purchase it to use it, I think they will try to read the documentations and watch videos before buying it. If the users don't have the patience, they may not be able to handle ImageTrans as well.

ImageTrans is a productivity tool which can saves hundreds of hours translating images. The current price is pretty low compared to tools like Trados. Its value lies in not just the online services.

**Comment by jacknion** [comment]
怎么下载Sugoi-Japanese-Translator-V3.0 ？ 网上好像没有地址。

**Comment by xulihang** [comment]
这是位越南老哥开发的，下载地址在他的youtube视频简介里：https://www.youtube.com/watch?v=r8xFzVbmo7k

**Comment by jacknion** [comment]
好的，十分感谢。

**Comment by xulihang** [comment]
> How can I download this is this .bat file is present inside the ImageTrans Folder to run it , and will it only work for Japanese or Others languages like Chinese all Versions Simple, Traditional etc

This is a third-party tool. Please check out its website: https://blog.sugoitoolkit.com/

**Comment by CoolGenius-123** [comment]
> > How can I download this is this .bat file is present inside the ImageTrans Folder to run it , and will it only work for Japanese or Others languages like Chinese all Versions Simple, Traditional etc
> 
> This is a third-party tool. Please check out its website: https://blog.sugoitoolkit.com/

Could you try creating translation using offline translation ( like using ollama and using LLM in it) it works offline https://ollama.com/

**Comment by xulihang** [comment]
> > > How can I download this is this .bat file is present inside the ImageTrans Folder to run it , and will it only work for Japanese or Others languages like Chinese all Versions Simple, Traditional etc
> > 
> > 
> > This is a third-party tool. Please check out its website: https://blog.sugoitoolkit.com/
> 
> Could you try creating translation using offline translation ( like using ollama and using LLM in it) it works offline https://ollama.com/

This is compatible with ChatGPT's API: https://ollama.com/blog/openai-compatibility

You can use the ChatGPT plugin to use it.
