### ISSUE TITLE
I don't know how to use tesseract.

### ISSUE THREAD

**Issue by minsawook** [xulihang/ImageTrans-docs#109]
After installing tesseract, I succeeded in executing it in cmd, but in image trans, it's non-responsive.
Is the tesseract path setting wrong in image trans?

https://user-images.githubusercontent.com/92355477/144171233-86dd3a11-7ac8-469f-8e8d-843591fa6301.mp4

![2](https://user-images.githubusercontent.com/92355477/144171276-503f1abf-c297-483d-9778-ad2809c3fa7f.JPG)
![1](https://user-images.githubusercontent.com/92355477/144171278-55f5a395-45bd-4d00-bc48-290b66b29a66.JPG)

![캡처](https://user-images.githubusercontent.com/92355477/144171283-143bd647-3bd8-4f52-84f5-dc0e5a9e2816.JPG)

**Comment by xulihang** [comment]
Tesseract supports full-page text localization of printed documents but it cannot detect text areas in comics.

In this case, you need to create text boxes then use Tesseract to OCR these boxes individually.

**Comment by minsawook** [comment]
Thanks to you, the problem has been solved. I would like to express my gratitude to you.
