### ISSUE TITLE
[Suggestion] OCR comparison

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#11]
It would be great to have a way to compare different OCR results, similar to how "Translation assist" works, as I've seen certain OCR engines being able to handle cases others can't, but not being as good overall (example: baidu_accurate is better than ABBYY overall, but ABBYY can OCR certain characters that baidu_accurate can't)

**Comment by xulihang** [comment]
This is a good idea. I have thought about this but haven't done anything yet.

**Comment by xulihang** [comment]
As the accuracy of OCR has become good enough, it is not needed to compare OCR results now.
