### ISSUE TITLE
ScreenReader's annoying behavior

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#110]
Every time the capture is taken, ScreenReader's window reappears in the middle of the screen instead of where it was placed, often on top of the other bubbles you want to ocr next. As a result, you have to constantly move it out of the way. It would be cool if this behavior could be disabled.

**Comment by Kamikadashi** [comment]
Thanks! This will be available in the next update, right?

**Comment by xulihang** [comment]
Yes. I can send you the updated files by email so that you can use it now.

**Comment by xulihang** [comment]
This is added in v1.5.1
