### ISSUE TITLE
User filter are not applied when translating using eztrans.

### ISSUE THREAD

**Issue by minsawook** [xulihang/ImageTrans-docs#111]
I'm using the eztrans you made well. However, it was found that the quality of translation was very poor because the filter, one of the functions of eztrans's ehnd, was not applied.
When translating into a program called anemone created by another user, the quality of translation is good because the filter is processed. Can you solve this problem? Please.

anemone : https://github.com/sokcuri/anemone     
![캡처](https://user-images.githubusercontent.com/92355477/144273790-40e900bb-c7c4-4131-b14c-1246d8fabd8e.JPG)

Run as anemone.
![ANE1](https://user-images.githubusercontent.com/92355477/144276426-643cba0a-fc1d-40d9-9fbb-1a56b08f8a40.png)

![2](https://user-images.githubusercontent.com/92355477/144273800-275924a5-b1e7-43c1-8e27-8768fb7a772d.JPG)
[ehnd+filter.zip](https://github.com/xulihang/ImageTrans-docs/files/7635675/ehnd%2Bfilter.zip)

**Comment by xulihang** [comment]
I just go through the project. I think anemone is a helper. We don't need it. The filter should be set up in eztrans XP.

But since I don't know Korean, you have to figure out how to do this by yourself.

**Comment by minsawook** [comment]
I was able to solve the problem myself. But thank you for answering.
