### ISSUE TITLE
Request for romaji translation

### ISSUE THREAD

**Issue by yogi19911** [xulihang/ImageTrans-docs#112]
as we talked about in the email about my unique request 😊  , I request support for romaji translation

**Comment by xulihang** [comment]
Okay, I've created a [transliteration plugin](https://github.com/xulihang/ImageTrans_plugins/tree/master/transliterationMT) for this.

![image](https://user-images.githubusercontent.com/5462205/144709651-72c1ee86-951a-4b00-a728-5eef46eb30e6.png)

Two engines are integrated: [Jakaroma](https://github.com/nicolas-raoul/jakaroma/) and [Microsoft Azure](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-transliterate).

Let's try to transliterate this sentence: `先生!ココ!ココ!オレの隣が… `

Jakaroma:

```
Sensei !Koko !Koko !Ore No Tonari Ga …
```

Microsfot Azure (supports other languages as well):

```
sensei ! coco ! coco ! ore no tonari ga ...
```

## How to use

1. Download the plugin

[Link](https://github.com/xulihang/ImageTrans_plugins/releases/download/plugins/transliterationMTPlugin.zip)

2. Unzip the file and put all the files in the plugins folder

3. Enable it in the Preferences

**Comment by xulihang** [comment]
Please note that Azure requires an API key.

**Comment by xulihang** [comment]
You can select which engine to use in the Preferences.

![image](https://user-images.githubusercontent.com/5462205/144739320-a05299b3-8610-4905-85c8-bfdb08b2dba7.png)

The sourceScript key is ont needed by Azure.

**Comment by xulihang** [comment]
v2.3.0 added an embedded web browser which can use an external web page to analyse Japanese. Romanji translation is also possible using it: https://github.com/xulihang/ImageTrans-docs/issues/483
