### ISSUE TITLE
Output JPGs sometimes have added white border

### ISSUE THREAD

**Issue by OrangeFarmHorse** [xulihang/ImageTrans-docs#115]
Hi,
I've run into the issue that some images of a project get "padded" with a white border on one side of the image for (to me) no discernible reason. 
I added a short clip of one such image in the actual project folder and then the out-folder. The image dimensions differ from 1600x1200 for the original and 1600x1226 for the output. I guess the extra 26 pixels are are the white border on the bottom edge.

https://user-images.githubusercontent.com/43349390/146673655-66436b8e-2f33-4e27-bc5b-08264d8a96e8.mp4

**Comment by xulihang** [comment]
I cannot replicate this problem. Could you send me the image so that I can have a test?

**Comment by OrangeFarmHorse** [comment]
With pleasure!

[001.zip](https://github.com/xulihang/ImageTrans-docs/files/7747593/001.zip)

**Comment by xulihang** [comment]
Please check if there are boxes outside of the image. I think this is the reason.

![image](https://user-images.githubusercontent.com/5462205/146856718-49a94c3a-e151-40d6-9dbb-055665e5dd1e.png)

**Comment by OrangeFarmHorse** [comment]
You are pretty much a genius at remote troubleshooting!
I did not see that before.. maybe because it only appears during the TypeSetting-mode.
Solved!

https://user-images.githubusercontent.com/43349390/147139905-7d970725-e038-4f33-add5-0f581d9eea0c.mp4
