### ISSUE TITLE
merging ocr text from multiple textboxes

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#118]
MTL can perform better with context, so it would be useful if textboxes could be merged in the order of their selection, at least on a page-by-page basis.

**Comment by xulihang** [comment]
It is true, and I have thought about this before. But where to save the translation is a problem.

Here is my thought:

If two balloons belong to one sentence, then it is possible to string them together, like text boxes in Microsoft Word. But this is a bit complex, I haven't done anything about this.

The other way is to export the text to a file and use machine translation to translate the whole file. This has been talked about before: https://github.com/xulihang/ImageTrans-docs/issues/15#issuecomment-810834036

**Comment by Kamikadashi** [comment]
I've tried this, but unfortunately it doesn't quite accomplish the goal, as all the text is scattered around and this ruins the context. That's why I specified "in order of their selection" earlier.

**Comment by xulihang** [comment]
The order can be adjusted, though it may not be very intuitive:
![image](https://user-images.githubusercontent.com/5462205/147411046-734fa8f4-499f-4e33-8e07-c36401921408.png)

If translating a text file, [BasicCAT](https://www.basiccat.org/) can be useful as it can merge and split segments easily.

**Comment by Kamikadashi** [comment]
OK, thanks! It's very slow though, as you have to do a lot of clicking for each individual line. I hope there would be a better implementation in the future, if that's possible. Clicking the lines in the menu in the order you want them sorted, or something like that.

**Comment by Kamikadashi** [comment]
> It is true, and I have thought about this before. But where to save the translation is a problem.
e.g. the merged text could be saved in the first selected or in a newly generated textbox

**Comment by xulihang** [comment]
I just created a deepl plugin: https://github.com/xulihang/ImageTrans-docs/issues/15#issuecomment-1023885174

I try to join text of different boxes into one before translating it, like this:

```
先生はそれをお前に教えたい
だから先生が温泉に行ってる間天文部を頼む
```

This seems to produce more coherent results.

Enable batch translation:
![004-batch](https://user-images.githubusercontent.com/5462205/151490295-0f6222d5-dd18-48fc-9c9c-9a9ed5641df5.jpg)


Translate one by one:
![004](https://user-images.githubusercontent.com/5462205/151490305-81255f3e-22d2-4e32-bded-aded0812ff91.jpg)

**Comment by Kamikadashi** [comment]
Cool! Could this work with sugoi as well?

**Comment by xulihang** [comment]
It just combines all the text together, so Sugoi can work as wel. It's just that I haven't add batch translation to the plugin.

**Comment by hentaitaku** [comment]
Really like to see the batch translation to sugoi and deepl have then more context and can make a better translation.

**Comment by xulihang** [comment]
Whether Batch translation is default can be configured in the Preferences.

**Comment by xulihang** [comment]
Whether Batch translation is default can be configured in the Preferences.

**Comment by xulihang** [comment]
I've added a context menu item to show the translation of the combined text of selected text areas:

![image](https://user-images.githubusercontent.com/5462205/152645857-f6f0e695-0f33-4340-9d9e-a86ce1f96d4b.png)
