### ISSUE TITLE
I don't know how to install and use ImageTransOCR and mangaTranslatorOCR.

### ISSUE THREAD

**Issue by awwdx** [xulihang/ImageTrans-docs#119]
I don't know how to install and use ImageTransOCR and mangaTranslatorOCR.

**Comment by xulihang** [comment]
ImageTrans_OCR is abandoned. mangaTranslatorOCR is based on an old version of <https://github.com/zyddnys/manga-image-translator>.

The installation is not easy.

**Comment by awwdx** [comment]
Should I follow this link?   https://github.com/zyddnys/manga-image-translator
Or
Should I follow this link? https://github.com/xulihang/manga-image-translator

**Comment by xulihang** [comment]
Use the latter

**Comment by awwdx** [comment]
If I do 3. Run the server: python server.py 
An error occurs.
Traceback (most recent call last):
  File "D:\eclipse\TT\ImageTrans\manga-image-translator-main\server.py", line 6, in <module>
    from bottle import route, run, template, request, static_file
ModuleNotFoundError: No module named 'bottle'
an
![KakaoTalk_20211227_142941130](https://user-images.githubusercontent.com/96706748/147437700-041d9b3b-af28-437f-9d3b-43dc8a6b02e8.png)
What should I write in this space?

**Comment by xulihang** [comment]
The default URL is http://127.0.0.1:8080/ocr.

If you don't set this, the default one will be used.
