### ISSUE TITLE
[Suggestion] Quick text area delete

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#12]
An option to bind deleting a text area to a button (DEL perhaps?) would be useful since it's pretty common for some garbage text areas to be leftover.

**Comment by xulihang** [comment]
This suggestion was also given here: https://github.com/xulihang/ImageTrans-docs/issues/7.

I will try to add a shortcut for this.

**Comment by lugia19** [comment]
Whoops, I missed it. Closing.

**Comment by xulihang** [comment]
Added in v1.5.2.
