### ISSUE TITLE
Found this Offline Balloon Detection Model and Best OCR?

### ISSUE THREAD

**Issue by hentaitaku** [xulihang/ImageTrans-docs#120]
Hi have found this Offline Balloon Detection Model is really good will find all Balloons.
https://github.com/madeyoga/detect-manga-dialogue

And what is the best Online OCR for Japanese Manga?
Offline is Abbyy and WinRT good but get ! and ... wrong.

**Comment by xulihang** [comment]
You can try google drive ocr.

**Comment by hentaitaku** [comment]
Yes google drive ocr is good can i add a api so i dont need to use your backend server?
Is google drive ocr the best or is there a paid service that is better.

**Comment by xulihang** [comment]
Google OCR uses the paid Google vision API.

Sogou is the best but it is not available for non-Chinese users.

**Comment by hentaitaku** [comment]
Many Thanks

One last question is there a usage limit by google drive ocr in imagetrans.

**Comment by xulihang** [comment]
Currently, no. You can use your own API key to use Google Drive OCR. Check out this: https://github.com/xulihang/ImageTrans-docs/issues/91

**Comment by hentaitaku** [comment]
Like todo that but your first download link is down in that post.

**Comment by hentaitaku** [comment]
Ok i download the server file for Google Drive OCR and add the cert file and add the url with port from my server in the Google Drive OCR plugin. Is that right.

**Comment by xulihang** [comment]
The command-line version is needed to get the token. You can use the cli version first.

**Comment by xulihang** [comment]
About the detection model, have you used it in ImageTrans?

I just tested it. The result is okay for manga, though the boundaries are not very accurate.

The model.json I adapted:

```
{
	"isDarkNet":true,
	"swapRB":true,
	"crop":false,
	"mean":[0,0,0],
	"scalefactor":"1/255",
	"width":512,
	"height":512
}
```

**Comment by hentaitaku** [comment]
I have used this and use expand area.

{
	"isDarkNet":true,
	"swapRB":false,
	"crop":false,
	"mean":[0,0,0],
	"scalefactor":"1/255",
	"width":416,
	"height":416
}

For what is swapRB.

**Comment by hentaitaku** [comment]
swapRB false gives better results and i use 416 because the cfg file is 416 to.
