### ISSUE TITLE
Rounded mask background

### ISSUE THREAD

**Issue by hentaitaku** [xulihang/ImageTrans-docs#123]
Hi please add the rounded mask background to imagetrans.

**Comment by xulihang** [comment]
I have added this as a project setting:

![image](https://user-images.githubusercontent.com/5462205/149664521-0d19dd7b-2240-4af1-b625-85f759775d37.png)

![image](https://user-images.githubusercontent.com/5462205/149664857-038b2424-f3bc-4b0b-a382-fe1095c2467b.png)
