### ISSUE TITLE
Import OCR Text after Extract Text Areas into Pictures

### ISSUE THREAD

**Issue by hentaitaku** [xulihang/ImageTrans-docs#124]
Hi i like to use "Batch > Extract Text Areas into Pictures" and then OCR the Pictures with Abbyy because it is faster that why.
How can i Import the text made txt files with the same file name is the Pictures.
Or how can i Import the text think there is a why because you made a Export.

**Comment by hentaitaku** [comment]
When there is no import think easy todo where a plugin for ImgExport and one for ImgTxtImport.

**Comment by xulihang** [comment]
There is not a way to import OCRed text in txt files, yet. I have to add such a function.

**Comment by hentaitaku** [comment]
Why then in Batch > Extract Text Areas into Pictures is it not to OCR the images ImageTrans need some why to add the made text then. Like to use Abbyy that why because in Abbyy is the batch soooo much faster. Your tool need a why to OCR more than one area at a time like making 5 OCR at the same time to speed it up.

**Comment by xulihang** [comment]
I've added this in v1.5.3.

Text areas can be exported to images:

```
image-1.jpg
image-2.jpg
```
It can import text from txt files with the same filename:

```
image-1.txt
image-2.txt
```

About how to create these txt files, third-party OCR tools like ABBYY can be used ([FineCMD](https://stackoverflow.com/questions/16385443/abbyy-finereader-exe-looking-for-cmd-commands-to-use-in-other-programms)).
