### ISSUE TITLE
In windows environment, there is no response when opening the software

### ISSUE THREAD

**Issue by stanleyQQ** [xulihang/ImageTrans-docs#126]
In windows environment, there is no response when opening the software

**Comment by xulihang** [comment]
How did you install ImageTrans? It seems that the Java environment is missing. It is better to download the full package from onedrive.

**Comment by stanleyQQ** [comment]
I installed the installation package sent to me by email after purchase, and the latest version of Java. Is there anything else I need to install?

**Comment by stanleyQQ** [comment]
I installed the installation package sent to me by email after purchase, and the latest version of Java. Is there anything else I need to install?

**Comment by xulihang** [comment]
ImageTrans needs JavaFX so the latest version of Java may not work as it does not have JavaFX. In the [docs](https://imagetrans.readthedocs.io/en/latest/), I recommend using [the full version of Liberica JDK 8](https://bell-sw.com/pages/downloads/).
