### ISSUE TITLE
Image Pre-processing in ImageTrans

### ISSUE THREAD

**Issue by hentaitaku** [xulihang/ImageTrans-docs#127]
Hi is ImageTrans Pre-processing ocr images before ocr?

Like making ocr image to 300dpi and so on.

Like to know is there a why to run a python script before ImageTrans ocr the image.
Will be great to have a why for Pre-processing the image.

What i see is that when i press ocr on a plugin, is the saved image just 96dpi my original image was over 300dpi.
Best when your tool saved the dpi from the original image to max 300dpi.

Dont know how you handle dpi with tesseract.

**Comment by xulihang** [comment]
There are several preprocessing:
It crops the text area.
It removes Japanese furigana.
It can remove background.
It can convert vertical Japanese to horizontal
It can extract lines for tesseract to read
As for DPI, I think the image resolutiom matters. DPI is just a meta info. If the width or height is smaller than 50, ImageTrans will scale it up.

**Comment by xulihang** [comment]
There is not mechanism to use python for preprocessing. I need to add a new plugin type for this.

**Comment by hentaitaku** [comment]
Hi i think dpi matters tired before a image with height 1800px and DPI 366 the OCR was really good then made the image 2X with waifu2x DPI was then 72 and OCR made many more errors.

**Comment by hentaitaku** [comment]
And why are you saving the ocr image in jpeg where png not better?

I train right now a new bubble model let you know how it is when its done.

**Comment by xulihang** [comment]
Okay. I will try out different dpi and file format.

Related issues: https://github.com/tesseract-ocr/tesseract/issues/1702

**Comment by xulihang** [comment]
After some experiments, I think DPI and file formats do not affect the result very much, although a better benchmark should be made for comparison. Maybe after the import OCRed text from exported text areas is done, you can do your own preprocessing in this way

Some test images:.

![test](https://user-images.githubusercontent.com/5462205/147871535-55e4ae89-1084-4dc5-9a98-dafd5724c9e2.jpg)

![2](https://user-images.githubusercontent.com/5462205/147871542-fcb67cb2-d957-4386-afcf-3854ec75e8d0.jpg)

**Comment by xulihang** [comment]
I've found a way to set the DPI of images to 300, but the result is not good for tesseract, so I will not add this fow now.

https://www.b4x.com/android/forum/threads/save-images-in-300-dpi.137269/

**Comment by hentaitaku** [comment]
Have tired some stuff to and found out that when i use a image that has 1280x1820 and a dpi over 300 is the ocr better.
But when i save the same image in 1280x1820 with 96dpi is the ocr not so good.

**I like to have this feature:**

Save the image like now but when you add to imageTrans Settings the path to your ImageMagick covert exe you get a 300dpi ocr image.
You need to get the 300dpi Image as source and not a 72dpi some tools do that wrong, there get 72dpi and save it to 300dpi.
Think is not hard to add just a if exist and a else and a exec for the cli.

You can do it with this cli command:

`convert -density 300 -units PixelsPerInch IMAGE_IN -density 300 -colorspace sRGB -sampling-factor 4:2:2 -quality 100 -strip -interlace none -format jpg IMAGE_OUT`

First density is for the input image and second density for the output this will not change the resolution just the dpi.


Hope you can add that why a pre-processing script to.
Add in imageTrans Settings a box where the user can add a command for a cli that will run after the image is saved.
When the box is empty will it skip the exec.

Something like this `"/path/python.exe /path/your-script.py"`

> And one more think i train with darknet a bubble speech model right now and found out that darknetV4 works but the new Scaled YOLO v4 not works. There are many new for csp mish swish p5 https://github.com/AlexeyAB/darknet and the mAP is better so when you have time hope you can add it. What i know is the cfg use now activation=logistic before was it activation=linear when i use linear in the model.cfg is it working but buggy get wrong sizes think because i trained with logistic.

**Comment by xulihang** [comment]
Which OCR software do you use?

If using tesseract, it has an option to specify the DPI. DPI is just a meta data. If the resolution is the same, the image pixels should be the same. By specifying the DPI 300, it may provide the same result.

**Comment by hentaitaku** [comment]
Will use tesseract i think WinRT and Abbyy are good to.

No when resolution is same but dpi is 300 in meta is it bigger is just shown at that resolution.

**Comment by hentaitaku** [comment]
Is like 96dpi 1pixel and 300dpi have like 4pxels in 1 pixel so ocr gets better.

**Comment by xulihang** [comment]
DPI is a conpect for printing and scanning. The tools say it is better to use at least 300 DPI to scan documents but I think it won't affect too much if we adjust the DPI of already scanned images.

**Comment by hentaitaku** [comment]
You are right dpi is for the scan 72dpi will work to when resolution is ok.
But a pre-processing like i said where user can make his own script is a good think.

Remove noise, rescale and so on can then be done.
Tesseract  hates noise so better remove it.

> Add in imageTrans Settings a box where the user can add a command for a cli that will run after the image is saved.
> When the box is empty will it skip the exec.
> 
> Something like this "/path/python.exe /path/your-script.py"
> 
> Think this will help you a exec for b4j https://www.b4x.com/android/forum/threads/jshell-library.34661/#content

**Comment by xulihang** [comment]
It is now possible to use the pure-text images manager for customized image preprocessing:

https://github.com/xulihang/ImageTrans-docs/issues/199
