### ISSUE TITLE
Please add Support for Scaled YOLO v4:

### ISSUE THREAD

**Issue by hentaitaku** [xulihang/ImageTrans-docs#129]
Hi can you add support für Scaled YOLO v4.

https://github.com/AlexeyAB/darknet

Like to train my bubble model with yolov4-csp-swish.cfg or yolov4-csp.cfg there make a good mAP.

**Comment by xulihang** [comment]
ImageTrans uses OpenCV's DNN module for object detection. You can try to run it with the code here: https://github.com/xulihang/ObjectDetector

**Comment by hentaitaku** [comment]
When i read it right is support added in opencv 4.5.4 but better use 4.5.5.
How can i use the new 4.5.5?
Think your code need some updates to.

Read here for more.
https://github.com/opencv/opencv/issues/18975

**Comment by hentaitaku** [comment]
Ok is working now have downloaded the 4.5.5 and placed the opencv_java455 as opencv_java453 in imageTrans.

**Comment by xulihang** [comment]
The bundled OpenCV is updated to 4.5.5 in ImageTrans v1.5.3
