### ISSUE TITLE
[Bug?] Weird undo behavior with resizing/moving text areas

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#13]
When dealing with resizing/moving text areas, undo behaves in a somewhat weird way. It seems to undo them one "step" at a time, instead of all at once. Moving/resizing the text area back to what it was before the mouse button was first pressed would be more consistent with the usual behavior of similar features in other programs.

**Comment by xulihang** [comment]
The undo/redo is not perfect. It is managed with [Undo Manager](https://www.b4x.com/android/forum/threads/b4x-class-undomanager.73019/#content). I implemented this by manually add the save status code to needed places.

I will try to do this correctly.

**Comment by lugia19** [comment]
I didn't know this project used b4j, neat to see it being used in the wild. Perhaps it would be possible to save the state only when the user clicks on the text area, rather than at every step? I'm sure you know of a way to fix this either way.

**Comment by lugia19** [comment]
Does this apply to any changes or just the dragging? Either way, should be fixed.

**Comment by xulihang** [comment]
Any changes. But I haven't found any other operations which happen consecutively within 1 second.
