### ISSUE TITLE
How to use Sickzil-Machine.

### ISSUE THREAD

**Issue by awwdx** [xulihang/ImageTrans-docs#130]
I finished installing Sickzil-Machine and ran the server.
But I don't know how to use Sickzil-Machine in the image trans program.

**Comment by xulihang** [comment]
It can be used in mask editor and text remover.

![image](https://user-images.githubusercontent.com/5462205/148042253-d3325c08-bee0-4620-bc20-1bf12b528e3c.png)

![image](https://user-images.githubusercontent.com/5462205/148042437-ce1dd85a-5c51-4964-87bb-b509dc9b298e.png)

![image](https://user-images.githubusercontent.com/5462205/148042522-a1114bb0-a936-4fbe-848d-6b364718c556.png)

**Comment by xulihang** [comment]
Example:

![image](https://user-images.githubusercontent.com/5462205/148043215-07aae3a9-2607-49b1-bce1-c00e303f642f.png)
