### ISSUE TITLE
Auto Correct

### ISSUE THREAD

**Issue by perobruh** [xulihang/ImageTrans-docs#133]
is there a way to make auto correct automaticly correct translated text?

**Comment by perobruh** [comment]
https://user-images.githubusercontent.com/97352942/148896112-edb24288-5152-4a4d-95b1-aadbcce67494.mp4

**Comment by perobruh** [comment]
here's a video, if you don't understand what i'm talking about

i have to manually type Saya to be auto corrected to aku

https://user-images.githubusercontent.com/97352942/148896377-f0e5c449-168c-4596-a39e-0f3607d9a6eb.mp4

**Comment by perobruh** [comment]
here's a video, if you don't understand what i'm talking about

i have to manually type Saya to be auto corrected to ak

Uploading bandicam 2022-01-11 14-06-27-247.mp4…

**Comment by perobruh** [comment]
here's a video, if you don't understand what i'm talking about

i have to manually type Saya to be auto corrected to aku

https://user-images.githubusercontent.com/97352942/148896706-98c997b0-ccb5-4581-a570-ccdf787cdbb6.mp4

**Comment by xulihang** [comment]
Okay. I will add an option to enable AutoCorrect for machine translation.
![image](https://user-images.githubusercontent.com/5462205/148934339-49cdbed8-c683-4274-9e1d-2f35de04f98e.png)

**Comment by xulihang** [comment]
Please note that It will replace all the matched text. It is case-sensitive.

https://user-images.githubusercontent.com/5462205/148937727-3d423414-8374-4f7f-afbc-912ce5fa31ce.mp4

**Comment by perobruh** [comment]
> Okay. I will add an option to enable AutoCorrect for machine translation. ![image](https://user-images.githubusercontent.com/5462205/148934339-49cdbed8-c683-4274-9e1d-2f35de04f98e.png)

where is this button placed?

**Comment by xulihang** [comment]
In the project's settings. Please wait for a new release.

**Comment by perobruh** [comment]
thank you

**Comment by xulihang** [comment]
Added in v1.5.3
