### ISSUE TITLE
Made a Balloon Modul with Darknet

### ISSUE THREAD

**Issue by hentaitaku** [xulihang/ImageTrans-docs#135]
Hi made a darknet balloon modul please try it.
Is working best with japanese manga have trained it with more then 2500 manga, h-manga and doujin pages.

[Download from GDrive](https://drive.google.com/file/d/1S6PZmI4laRKKS5YOiLtbD_MzIg8E5lqa/view?usp=sharing)

Working right now on a tesseract modul for vertical japanese text.
Train it with 59 fonts used in Manga.

When will you bring out new ImageTrans Release?

**Comment by xulihang** [comment]
This works great for manga. 

I will release a new version with OpenCV 4.5.5 in a few days,

**Comment by xulihang** [comment]
Some irregular balloons cannot be accurately detected. The heuristic method is more accurate in detecting these balloons, while it fails if the background is too complex.

![image](https://user-images.githubusercontent.com/5462205/149665162-457c7f9a-d96d-4e10-bfb6-c7ea09d1f6d3.png)

**Comment by hentaitaku** [comment]
Can you give me the full manga page so i can test it, try to fix it then.

**Comment by xulihang** [comment]
This is from Detective Conan.

![1](https://user-images.githubusercontent.com/5462205/149665855-9e61b376-bc56-4f94-a81f-f1f3f4674c21.jpg)

**Comment by Kamikadashi** [comment]
the model also sometimes has problems detecting fairly standard balloons like here (﻿こうなったら力ずく one gets ignored)
![0009](https://user-images.githubusercontent.com/90068423/149768327-8f16e1d0-e00d-4670-97c6-9b4f83132e87.jpg)

**Comment by hentaitaku** [comment]
Its because i have not trained to many manga what volume is that.

**Comment by Kamikadashi** [comment]
tate no yuusha vol 16, but that's just one example, I highly doubt the model doesn't have similar problems in different volumes of other manga

**Comment by hentaitaku** [comment]
I can fix that is the bubble had many round but not trained for that bubble art. Have trained most with h-manga and doujin. Just 800 pages trained for manga.

**Comment by Kamikadashi** [comment]
おｋ, hope it works out!

**Comment by hentaitaku** [comment]
xulihang: I train module for for the irregular balloons right now.

Kamikadashi: By me is the page and all others from v16 not leaving balloons, all are found.
Did you update ImageTrans to 1.5.3 and set balloon detection to offline in settings.

What i see if a image is too big like 6000px heigh can balloon modul get wrong results.

**Comment by hentaitaku** [comment]
Here is v2 with the fix for irregular balloons.

https://drive.google.com/file/d/1lfquXkO40p6mVVzm1ebXA1CGcCNCveg2/view?usp=sharing

**Comment by Kamikadashi** [comment]
tested the new version and it seems to work surprisingly well! I do wonder though, if there's a way to batch 'expand areas' for all pages after balloon detection(@xulihang), as the model sometimes puts borders so close it cuts off parts of the kanji (to an extent seems to be page size dependent)

**Comment by xulihang** [comment]
Use custom workflow:

![image](https://user-images.githubusercontent.com/5462205/150449735-886ddecf-a2b6-49eb-9f34-804e4d07f9f7.png)

Since 1.5.3, it is also possible to expand areas after balloon detection (check project settings):

![image](https://user-images.githubusercontent.com/5462205/150450043-cea076e3-f70d-48a1-994d-ff9b7acab49f.png)

**Comment by Kamikadashi** [comment]
@hentaitaku an example of a pretty complex case where the model ignores all handwritten text
![545](https://user-images.githubusercontent.com/90068423/153307250-baf1d5b5-e723-47d0-b428-e034ee2ee8d6.png)

**Comment by hentaitaku** [comment]
Hi is just model is not trained for that text art need more data like this so i can train it.

**Comment by Kamikadashi** [comment]
Does the size of training images matter a lot? [This ](https://twitter.com/hashtag/%E5%AD%90%E8%82%B2%E3%81%A6%E6%BC%AB%E7%94%BB?src=hashtag_click) hashtag seems to have quite a lot of pages with handwritten text both inside and outside of bubbles.

**Comment by 1439707509** [comment]
我想给这个项目用，可以吗？

https://github.com/zyddnys/manga-image-translator

**Comment by CoolGenius-123** [comment]
Where Should I put this downloaded model to use it in balloon detection?

**Comment by xulihang** [comment]
> Where Should I put this downloaded model to use it in balloon detection?

Please read before you post questions: https://github.com/xulihang/ImageTrans-docs/issues/135#issuecomment-1014761409
