### ISSUE TITLE
Balloon Detection Feature Request

### ISSUE THREAD

**Issue by hentaitaku** [xulihang/ImageTrans-docs#137]
Hi can you add a function to Balloon Detection Offline.

I have made a five test and found out that you get best results when the image it use is not to big best 1170px height.
So can you resample the image to 1170px height before you use opencv dnn and calculate the results up to the image height used in ImageTrans.

It is the darknet network that works best on smaller images.

**Comment by xulihang** [comment]
The model should resize it to like 512x512 before inference. I wonder if this is necessary.

```java
Mat blob = Dnn.blobFromImage(img, scalefactor, new Size(inpWidth,inpHeight), mean, swapRB, crop);
```

**Comment by hentaitaku** [comment]
No it will not resize the image the 512x512 is the network size the model use. The images used where 1170px height and darknet resized them in training to 512x512. Now it use the 512x512 to find balloons, when the image is to big will it not work because balloon is bigger then trained for and small wrong balloons not trained for will be found.

You can see it good on this 2 pages one in 1170px and other in 6000px.

https://drive.google.com/file/d/12puHrjhrvjp59iWA8FRnuTvZJ2wZ2NRm/view?usp=sharing
https://drive.google.com/file/d/1o0QS699LU5EfSSM1LAKgbwQjsM-mt1Yi/view?usp=sharing

**Comment by hentaitaku** [comment]
You need to edit your code like this hope made no error.
```
import org.opencv.imgcodecs.Imgcodecs;

//Create a 4D blob from a frame.
Mat blob = Dnn.blobFromImage(img, scalefactor, new Size(inpWidth,inpHeight), mean, swapRB, crop);
```
import org.opencv.imgproc.Imgproc;
import org.opencv.imgcodecs.Imgcodecs;

//Create a 4D blob from a frame.
Mat reimage = new Mat();
Imgproc.resize(img, reimage, new Size(inpWidth, inpHeight));
Mat blob = Dnn.blobFromImage(reimage, scalefactor, new Size(inpWidth,inpHeight), mean, swapRB, crop);

**Comment by xulihang** [comment]
I see. Your image has a very high resolution. The resize operation will reduce the image quality, and that quality is better for detection.

**Comment by hentaitaku** [comment]
Has todo with the image size not the quality, i save the images in quality 100.
This is how darknet works.

**Comment by xulihang** [comment]
The option is added in v1.5.4.
