### ISSUE TITLE
[Suggestion] manga_ocr

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#140]
I've been testing this new offline ocr and it seems to produce extremely accurate results. 
https://github.com/kha-white/manga_ocr
Moreover, it already can detect text in any image from the clipboard as well as automatically copy the text (and it's not windows only). So basically the plugin would have to copy the balloon to the clipboard and paste the results. It can also ocr images from a specified folder, so the yomikaku extension almost works, except that it doesn't paste the result from the clipboard back into ImageTrans.
I think together with hentaitaku's Darknet model this can be the free, offline, accurate and easy to install to go option for any platform.

**Comment by hentaitaku** [comment]
Cool thanks for the info i will try it with my new image processing i have made with python.

That is a code i made to edit images for ocr (ImageTrans 'batch > extract text area into pictures').
Right now it deskew, removes furigana as good as it can, removes background and makes image better for ocr.
Have not test it to much but works great on the test images.

`You need installed in python: cv2, scipy, numpy, tkinter and pytesseract`

https://drive.google.com/file/d/1w3lUIpDjICtL5K4myuyUO5k1Qf67yqIx/view?usp=sharing

**Comment by Kamikadashi** [comment]
this ocr can handle skewed text, ignores furigana and doesn't mind complex background/borders around symbols out of the box, so I'm not sure preprocessing will improve the result. But thanks for the link, I'll try it out!

**Comment by xulihang** [comment]
This end-to-end transformer solution is fast and accurate. Probably the best manga OCR that I've used.

I've made a plugin for it:

How to install:

1. Put the plugin in the plugins folder: [manga-ocr-plugin.zip](https://github.com/xulihang/ImageTrans-docs/files/7919869/manga-ocr-plugin.zip)
2. Run the OCR server:

```
python server_manga_ocr.py
```
[server_manga_ocr.zip](https://github.com/xulihang/ImageTrans-docs/files/7919874/server_manga_ocr.zip)

Source: <https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR>

**Comment by xulihang** [comment]
> Cool thanks for the info i will try it with my new image processing i have made with python.

I have been thinking about using edge detection and SWT to remove background as well, since tesseract and my way of furigana removing work the best on a clean background.

But now that there is manga-ocr, I think it is not necessary to dive into the preprocessing stuff anymore.

**Comment by Kamikadashi** [comment]
> 2. Run the OCR server:
> python server_manga_ocr.py

Had to install 'bottle' and 'paste' for it to run, but seems to work now.
