### ISSUE TITLE
Preferences -> General Chinese script on English language setting in v1.5.3

### ISSUE THREAD

**Issue by OrangeFarmHorse** [xulihang/ImageTrans-docs#141]
Probably not a huge issue, but in version 1.5.3, the General tab in the preferences has some Chinese text fields even on the English language setting:

![image](https://user-images.githubusercontent.com/43349390/150636302-6de5f79b-e2f6-4f38-9e5c-dcfd40909b9f.png)

**Comment by xulihang** [comment]
I see. I updated the UI to make it scrollable if there is not enough screen space,  and I forgot to localize it. I will update the files.

**Comment by xulihang** [comment]
Fixed in v1.5.4.
