### ISSUE TITLE
ScreenReader's usability

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#145]
It would help if 'capture' and 'get image' buttons had hotkeys (could speed up the process significantly).
Having an option to automatically copy the results to clipboard would be great as well.

**Comment by xulihang** [comment]
Okay. I've added an option to enable clipboard monitor. It will check if the clipboard has new images every 0.5 second. 

As for shortcuts, a hook has to be used to add a system-level shortcuts. I will not add such a function for now.

https://user-images.githubusercontent.com/5462205/151692692-62d12285-ba41-4877-aca7-5d97ec8139ac.mp4

**Comment by Kamikadashi** [comment]
Tnx! Can it copy the OCR results to the clipboard as well? (as a togglable option)

**Comment by xulihang** [comment]
What is the use of copying the OCR result to the clipboard?

**Comment by Kamikadashi** [comment]
Integration with parsers to quickly look up words in the dictionary (in addition to the MTL screen reader already provides)

**Comment by xulihang** [comment]
Now, the clipboard monitor will set the clipboard empty after acquiring the image. I will set the content of the clipboard to the OCR result instead.

**Comment by xulihang** [comment]
Added in v1.5.5.
