### ISSUE TITLE
[Suggestion] DeepL machine translation support

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#15]
The title essentially says it all - I've found DeepL (https://www.deepl.com/translator) to be the best machine translator overall, and it would be great to have support for it within the program.

**Comment by xulihang** [comment]
Making a machine translation plugin is simple (See [googleMT](https://github.com/xulihang/ImageTrans_plugins/tree/master/googleMT)). 

But since DeepL does not provide subscription services in China, I haven't found a way to use it.

**Comment by lugia19** [comment]
Are the plugins also written using B4J? If that's the case, I'll try my hand at creating a deepL plugin.

**Comment by xulihang** [comment]
Yes.  I used B4J and [ABPlugin](https://www.b4x.com/android/forum/threads/abplugin-live-plugin-library-for-your-apps.67395/). You can find more examples here: <https://github.com/xulihang/BasicCAT/tree/master/plugins>

**Comment by HeLan8** [comment]
I've been wanting this as well because DeepL is definitely the best machine translator. But I have found a way how you can translate every text area in your project with DeepL and insert it back into the program in less than 5 minutes.

First export a document for translation as docx in ImageTrans. Then open the docx document with LibreOffice. Save the document as a Microsoft Word XML (.docx) document. Translate this document with DeepL into your language. After you get the translated document open both the original docx document and the translated document in LibreOffice. Copy the entire translated text and paste it next to the raw text in the original document. Save the document again as Microsoft Word XML (.docx). Import this translation into ImageTrans and you'll have every text area translated by DeepL in less than 5 minutes.

**Comment by HeLan8** [comment]
The DeepL Windows App has an option to insert the translation back into ImageTrans, so maybe there can be something done with this.

**Comment by xulihang** [comment]
I bought a deepl account from an agency and I am able to create a deepl plugin.

Here is the plugin ([code](https://github.com/xulihang/ImageTrans_plugins/tree/master/deeplMT)):

[deepl.zip](https://github.com/xulihang/ImageTrans-docs/files/7955765/deepl.zip)

Usage:

1. Put the unzipped files into the plugins folder of ImageTrans
2. Get your authentication key from deepl and fill it in ImageTrans's preferences settings.
3. Enable it in the MT preferences.

**Comment by Caravanr54545** [comment]
> I've been wanting this as well because DeepL is definitely the best machine translator. But I have found a way how you can translate every text area in your project with DeepL and insert it back into the program in less than 5 minutes.
> 
> First export a document for translation as docx in ImageTrans. Then open the docx document with LibreOffice. Save the document as a Microsoft Word XML (.docx) document. Translate this document with DeepL into your language. After you get the translated document open both the original docx document and the translated document in LibreOffice. Copy the entire translated text and paste it next to the raw text in the original document. Save the document again as Microsoft Word XML (.docx). Import this translation into ImageTrans and you'll have every text area translated by DeepL in less than 5 minutes.
> 
> Edit: I had an old version of LibreOffice and the new/current version doesn't have Microsoft Word XML (.docx). But apparantly it's enough to just save it normally. If you translate the exported docx document with DeepL without saving it in LibreOffice first, then the translated document will be corrupted and unusable.



Man thanks, but  i try make this 3-4 hours,  not work....

The imported text,  is replaced by a number....

Maybe this problem?:  I want save as docx, but "This document contains formatting or content that cannot be saved in the currently selected "Word 2007-365" file format." 

"Use the default ODF file format to make sure the document is saved correctly."

And try "„Office Open XML world (Transitional), but still the problem. 

The deepl api  does not cost much, but i want only month arround 1-2 comics translation.  So therefore want free method.

**Comment by Caravanr54545** [comment]
Now try this:

Export doc for translation /docx/ and make this file import translation , but the imported text, is replaced by a number.
But the files not edit, so the import translation function not work?

**Comment by xulihang** [comment]
The workflow above is for users using LibreOffice.

You can simply do the following to use the deepl's free file translation:

1. File->Export>Document for translation and choose docx as the output format 
2. Use deepl to translate the file
3. Copy the translation in the translated file from deepl and paste the translation in the previously exported file
4. Use ImageTrans to import the translation

**Comment by xulihang** [comment]
New deepl plugin which does not require an api key: https://github.com/xulihang/ImageTrans_plugins/tree/master/deeplfreeMT

**Comment by Megablader** [comment]
The deeplfree works for a little bit, About 5-6 translations then it gives an error. You then have to restart imagetrans for it to start working again.

**Comment by xulihang** [comment]
What is the error? I haven't encountered any error.
