### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MelThatcher** [xulihang/ImageTrans-docs#150]
How to fix java.io not found error

![error](https://user-images.githubusercontent.com/8630139/152581939-ca0c9127-bc4d-45ea-8296-43a2a0ad7ddf.JPG)
?
![error](https://user-images.githubusercontent.com/8630139/152582024-7eeda718-1050-4630-8350-320f19b7cb34.JPG)

**Comment by xulihang** [comment]
Do not put ImageTrans in the `Program File` folder. There will be permission problem, Put it in other places like `D:\ImageTrans`

**Comment by MelThatcher** [comment]
solved
