### ISSUE TITLE
OCR error

### ISSUE THREAD

**Issue by MelThatcher** [xulihang/ImageTrans-docs#151]
Getting java.ioFilenotfoundeaxception error when OCRing.
Help me out!!!

This message box is not letting me paste or upload a screen clip of the error message.

Mel Thatcher

**Comment by xulihang** [comment]
Have you solved this issue: https://github.com/xulihang/ImageTrans-docs/issues/150

**Comment by MelThatcher** [comment]
#150 Solved
#151 Still having issues.  Moved files to c:/ImageTrans as you suggested.  Works better but getting java.lang.illegalArgumentException error.  So still need help
![java lang illegalArgumentException](https://user-images.githubusercontent.com/8630139/152628564-92d78ad5-69e8-4f45-8022-ba5685de296f.JPG)
.

**Comment by xulihang** [comment]
You may have wrongly created text areas. Clear existing text areas, create a new text area and try again.

**Comment by xulihang** [comment]
You can copy the error message instead of posting a screenshot.

**Comment by MelThatcher** [comment]
Recreated text areas.

Now I am getting the following error:  

error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.main$ResumableSub_BoxesListView_SelectedIndexChanged.resume(main.java:3024)
	at org.xulihang.imagetrans.main._boxeslistview_selectedindexchanged(main.java:2982)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by xulihang** [comment]
How.did.this error happen? I can't tell the reason from the message.

**Comment by MelThatcher** [comment]
I can't replicate the error.
I finally have OCRd text but when I save it the text is removed!  How can I fix this?
Also how can I get APIs for Baidu and Youdao/

    On Saturday, February 5, 2022, 04:10:21 PM MST, Lihang Xu ***@***.***> wrote:  
 
 


How.did.this error happen? I can't tell the reason from the message.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MelThatcher** [comment]
Recreated the error.  It appears after I creat a text box> click the box > Edit > OCR all text areas.


    On Saturday, February 5, 2022, 05:13:18 PM MST, Mel Thatcher ***@***.***> wrote:  
 
  I can't replicate the error.
I finally have OCRd text but when I save it the text is removed!  How can I fix this?
Also how can I get APIs for Baidu and Youdao/

    On Saturday, February 5, 2022, 04:10:21 PM MST, Lihang Xu ***@***.***> wrote:  
 
 


How.did.this error happen? I can't tell the reason from the message.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulihang** [comment]
I can't reproduce the problem. Do not do any operation when the OCR is running.

**Comment by xulihang** [comment]
Baidu and Youdao are only open for apply for Chinese. You can apply for Google instead.

**Comment by MelThatcher** [comment]
I am OCRing Chinese texts. So far Convertio.co does the most accurate OCR scan.  Youdao is usually better than Baidu for translation.  Both of them are better than Google Translate.
    On Saturday, February 5, 2022, 07:44:27 PM MST, Lihang Xu ***@***.***> wrote:  
 
 


Baidu and Youdao are only open for apply for Chinese. You can apply for Google instead.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MelThatcher** [comment]
Can you tell me how to stop removal of the text when I save a file?
    On Saturday, February 5, 2022, 05:13:18 PM MST, Mel Thatcher ***@***.***> wrote:  
 
  I can't replicate the error.
I finally have OCRd text but when I save it the text is removed!  How can I fix this?
Also how can I get APIs for Baidu and Youdao/

    On Saturday, February 5, 2022, 04:10:21 PM MST, Lihang Xu ***@***.***> wrote:  
 
 


How.did.this error happen? I can't tell the reason from the message.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulihang** [comment]
The ocr result is removed or the translation is removed? I think this is because you haven't saved the result or you didn't select a text area.

**Comment by xulihang** [comment]
Baidu OCR and Baidu machine translation are available by default. It's just the default version has usage limits like 500 times per day for baidu accurate version.

**Comment by MelThatcher** [comment]
OCR results.

I have not been able do a translation even though I have ticked translate after OCR box

**Comment by xulihang** [comment]
Try to use an offline OCR like WinRT. The OCR result may be replaced with an empty result due to network delay.

**Comment by xulihang** [comment]
If you use `OCR all text areas`, it will not translate. It will translate after you clicked the OCR button.

**Comment by MelThatcher** [comment]
Imagetrans is not saving now.  Just spins.

**Comment by xulihang** [comment]
Please do not use the issue like a live chat. Try to follow the [documentation](https://imagetrans.readthedocs.io/en/latest/) to use ImageTrans first.

**Comment by MelThatcher** [comment]
Documentation is inadequate.

**Comment by MelThatcher** [comment]
Thanks for your help.  I will see what I can do on my own.  I am not a developer.
