### ISSUE TITLE
功能疑问

### ISSUE THREAD

**Issue by Smile8848** [xulihang/ImageTrans-docs#152]
软件支持sugoi但没有提供安装包，希望提供一下下载地址。自动更正功能可不可以支持非当前项目，能否添加复制单个区域ocr出的原文的按钮。

**Comment by xulihang** [comment]
Sugoi是第三方软件，我只提供插件，下载还是从源地址下吧，这是日英翻译软件，我以为中国用户不需要这个。

全局自动更正我可以加一个导入导出设置的功能。

复制OCR结果，不知道什么场景需要这个功能，OCR后其实文本是自动复制进剪贴板的。

**Comment by Smile8848** [comment]
大部分机译出来会很奇怪，所以希望能用sugoi机译之后再机译？
因为大部分机译需要key 所以需要能复制ocr原文进网页翻译
自动更正我所想的是那种继承之前添加过的数据

**Comment by xulihang** [comment]
用网页翻译其实我写过一个插件，但好久没更新了，这些机译网站经常变化，有些还做了反自动化：https://www.basiccat.org/zh/new-plugin-machine-translation-via-web/

复制原文直接点中编辑区CTRL+A全选复制不也挺快的

**Comment by Smile8848** [comment]
步骤要多一步挺麻烦的 我觉得能直接从这 选择需要的词条然后直接复制更方便![](https://b2.kuibu.net/file/imgdisk/imgs/2022/02/c89c0a661f4602cb.png)

**Comment by xulihang** [comment]
好的，我给右键菜单加个复制文本的项目

**Comment by Smile8848** [comment]
感谢，看了下网页翻译插件 使用起来有有点专业性强，感觉还是utool中的翻译插件方便点，另外朗读器能支持调节下语速吗？感觉默认语速有点快。麻烦了

**Comment by Smile8848** [comment]
另外朗读器点所有图片朗读但首张图片没有内容和区域时会报错。。

**Comment by Kamikadashi** [comment]
> 好的，我给右键菜单加个复制文本的项目
It would be quicker if 'CONTROL+C' worked in a text area list, but I'm not sure it's possible to implement this.

**Comment by xulihang** [comment]
语音朗读的语速调整已经加在1.6.1版里了
