### ISSUE TITLE
[Suggestion] Panel detection in custom workflow 

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#153]
Would be great if `Custom workflow` gave some indication it does what it's supposed to when detecting panels as well as to have the ability to abort operation.

**Comment by xulihang** [comment]
Okay. I forgot to show the progress dialog for panel detection.

I might also add a progress bar in the custom workflow form and keep the form open.

**Comment by xulihang** [comment]
I just added the progress dialog for batch panel detection in v1.6.1.
