### ISSUE TITLE
♡无法显示？

### ISSUE THREAD

**Issue by Smile8848** [xulihang/ImageTrans-docs#154]
♡在软件中无法正常显示？？
![](https://b2.kuibu.net/file/imgdisk/imgs/2022/02/0bdaff8d3e9f24ac.png)

**Comment by xulihang** [comment]
♡ ♥ 💓 💔这些emoji，JavaFX是支持的。

![image](https://user-images.githubusercontent.com/5462205/153144492-ddd44f78-b27c-4681-94bf-8a64ec6f92b9.png)

OCR一般识别不出来爱心吧

**Comment by Smile8848** [comment]
> 

我是直接复制到译文的 也是在文本框里无法正常显示

**Comment by Smile8848** [comment]
![](https://b2.kuibu.net/file/imgdisk/imgs/2022/02/d46f4eb8999581db.png)
这是直接复制ocr原文到网页翻译的结果 
![](https://b2.kuibu.net/file/imgdisk/imgs/2022/02/c03d1bcbd1ba805c.png)
这是软件中的

**Comment by xulihang** [comment]
把文本粘过来，我测试下

**Comment by Smile8848** [comment]
今夜は一緒に寝よっか♡

**Comment by Smile8848** [comment]
我发出来也是可以正常显示，但在软件中无法正常显示。

**Comment by xulihang** [comment]
你用的什么java版本，更新到最新的看看吧：https://bell-sw.com/pages/downloads/

**Comment by xulihang** [comment]
![image](https://user-images.githubusercontent.com/5462205/153153987-46cfb63c-8d2f-4a7d-bfa9-6ba315114d87.png)

**Comment by Smile8848** [comment]
看了下 我没有安装过java 安装下看看。

**Comment by Smile8848** [comment]
软件中貌似带了个java环境是版本太低了吗？

**Comment by Smile8848** [comment]
已经将软件中的java环境替换依旧不显示

**Comment by xulihang** [comment]
系统是Windows 10吗。

还可以试试修改字体，在项目设置里。

**Comment by Smile8848** [comment]
系统环境LTSC 2021
项目设置中设置了字体会自动还原成system

**Comment by Smile8848** [comment]
![](https://b2.kuibu.net/file/imgdisk/imgs/2022/02/401341d2fbd5119c.png)

**Comment by xulihang** [comment]
设置后点应用，然后重新打开下项目

**Comment by Smile8848** [comment]
> 设置后点应用，然后重新打开下项目

这是应用后重新打开的效果 另外兼容输入助手中直接显示为方框

**Comment by Smile8848** [comment]
![](https://b2.kuibu.net/file/imgdisk/imgs/2022/02/2251a8c1592be484.png)

**Comment by Smile8848** [comment]
[![HG61vF.png](https://s4.ax1x.com/2022/02/09/HG61vF.png)](https://imgtu.com/i/HG61vF)
命令行中显示是？

**Comment by xulihang** [comment]
Arial不支持汉字，Arial Unicode才行。

**Comment by Smile8848** [comment]
在兼容输入助手中是正常的，软件界面显示不支持

**Comment by Smile8848** [comment]
[![HGcCZ9.png](https://s4.ax1x.com/2022/02/09/HGcCZ9.png)](https://imgtu.com/i/HGcCZ9)

**Comment by xulihang** [comment]
换个jre11试试看，不行我也没什么办法了

**Comment by Smile8848** [comment]
依旧如此:(
