### ISSUE TITLE
can't get the chrome extension up and running

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#155]
I was interested in trying the chrome extension but couldn't make it work. 
I successfully installed the extension via developer mode, placed 'ImageTrans_wsServer.jar' into the imagetrans folder, and ran the server in imagetrans itself.
Whenever I point the mouse onto the image I want to translate, click ctrl+shift+f, tab, enter its answer is 'Bad result. Is ImageTrans running correctly?'
Am I doing something wrong?

**Comment by xulihang** [comment]
Could you give a the link to test?

Possible reasons:

1. ImageTrans cannot download the image.
2. ImageTrans fails to translate the image.
3. Some steps are wrong.
