### ISSUE TITLE
[Enhancement] Option to Rotate TextBox Individually For Text Detection and TypeSetting

### ISSUE THREAD

**Issue by addak** [xulihang/ImageTrans-docs#157]
In the TypeSetting Mode, The only way currently to rotate textboxes is to do it via Project -> Settings -> Font Style. This is rather inconvenient when one wants to rotate only some textboxes manually. Read the docs : https://imagetrans.readthedocs.io/en/latest/tools.html but found nothing that allows me to rotate the textboxes individually.

**Comment by xulihang** [comment]
Check out this post I've made illustrating how to rotate an individual text box: https://www.proz.com/forum/cat_tools_technical_help/348742-a_tool_to_translate_images-page2.html#2898190, though the current way is not very convenient.

**Comment by xulihang** [comment]
The docs actually mentions this as well: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#id24

But the rotation cannot be used for OCR.

**Comment by addak** [comment]
> Check out this post I've made illustrating how to rotate an individual text box: https://www.proz.com/forum/cat_tools_technical_help/348742-a_tool_to_translate_images-page2.html#2898190, though the current way is not very convenient.

Yeah, this one link made it quite clear, just what I was looking for! While this would solve the issue, would it be possible to implement it the way we move textboxes? Like when you hover at one of the vertex, ↻ would appear.

**Comment by xulihang** [comment]
Rotation of the text box for both source and translated mode is added in v1.6.1.

You can now drag the mouse around the corners of the text area to rotate it. The image will also be rotated before OCR to improve recognition.

Here is a demo video:

https://user-images.githubusercontent.com/5462205/155844634-080953d6-09f5-4260-b3dd-55cce916c7ed.mp4

**Comment by jacknion** [comment]
新的1.6.1版里面，文字选择功能无法使用。 鼠标放在四个角可以出现那个旋转图标，但按下鼠标后，不会让图片旋转，会画一个新的黑框。

**Comment by xulihang** [comment]
麻烦录个屏，功能是正常的，有问题一般是操作问题

**Comment by xulihang** [comment]
噢，我知道了。不要选中快速滑动建框。这两个操作有冲突。

用默认的工具栏模式：

![image](https://user-images.githubusercontent.com/5462205/159408242-54a388f9-9fdb-4fd3-b863-30675b0960a2.png)

**Comment by jacknion** [comment]
是的。 感谢！
