### ISSUE TITLE
Offline balloon detection - Instructions

### ISSUE THREAD

**Issue by aravindnc** [xulihang/ImageTrans-docs#161]
Can you provide some walkthrough or instructions to setup offline balloon detection.

Also instructions to run,
[text-image-classifier](https://github.com/xulihang/text-image-classifier)
[ImageTrans_SceneText_Detection](https://github.com/xulihang/ImageTrans_SceneText_Detection)

**Comment by xulihang** [comment]
I've attached a balloon detection model in the mail. You can follow the readme file in it.

About the latter two, they are not needed in most cases.

**Comment by xulihang** [comment]
You can also find relevant issues here: https://github.com/xulihang/ImageTrans-docs/issues?q=balloon

**Comment by aravindnc** [comment]
Sorry just found the readme file. Works perfectly.
