### ISSUE TITLE
Google Translate via API

### ISSUE THREAD

**Issue by aravindnc** [xulihang/ImageTrans-docs#162]
I've added google api in preferences.

The google OCR is working correctly, but google text translation is not showing up. Its always blank. Does it need any other setup.

![image](https://user-images.githubusercontent.com/495110/154803643-8922711d-13c5-48d2-9239-4f425cf1c4d1.png)

**Comment by xulihang** [comment]
You need to enable machine translation in Google Cloud.

**Comment by aravindnc** [comment]
I have cloud translation enabled in GCP. Machine Translation is only a part of it I assume.

**Comment by aravindnc** [comment]
@xulihang Would be good if you can help on this. As this is the only thing taking most of my time.

**Comment by xulihang** [comment]
Google MT works in ImageTrans. Please check Google's docs and setup the cloud translation API: https://cloud.google.com/translate/docs/setup

**Comment by aravindnc** [comment]
Its already enabled for that Api Key. Should we configure anything other than Key in the api preferences screen in the app.

**Comment by xulihang** [comment]
Only the language codes are modifiable:

![image](https://user-images.githubusercontent.com/5462205/154875369-85113e33-e8a7-4dfb-8c53-655fbaf2439b.png)

**Comment by xulihang** [comment]
If google does not give an output, it may be because it does not support the language or the language codes are wrong.

**Comment by aravindnc** [comment]
Yes it seems my language is not supported.
