### ISSUE TITLE
选择框的问题 可以 旋转或者倾斜 或者自由框选吗？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#167]
![image](https://user-images.githubusercontent.com/30548000/155551852-17ea7d8d-5125-4836-8dd5-92b6733b6512.png)
![image](https://user-images.githubusercontent.com/30548000/155551889-e8b0e5ae-1437-41b9-865a-9ec07f36178e.png)

平时都没问题 遇到这种 不规则的  横着不是横着 竖着不是竖着的时候
正方形 长方形的框选就很别扭 能增加个 选项框的 旋转或者
![image](https://user-images.githubusercontent.com/30548000/155552060-c485e803-7948-495f-a5f6-280365b1bf9c.png)
 像截图软件的这种自由 选择的功能么

**Comment by xulihang** [comment]
旋转功能我已经做好了，周末发新版吧。旋转的文字ocr前也会做矫正

**Comment by jacknion** [comment]
能否添加多目录选择的功能？
现在只能一次翻译一个目录。

**Comment by xulihang** [comment]
不要问和issue不相关的问题。可以把多个目录放一个目录里。

**Comment by jacknion** [comment]
好的，感谢！

**Comment by lhj5426** [comment]
> 旋转功能我已经做好了，周末发新版吧。旋转的文字ocr前也会做矫正

期待 哈哈

**Comment by xulihang** [comment]
旋转功能加在1.6.1里了，选中一个文本框后可以拖动四个角进行旋转，操作视频可以看这条评论：https://github.com/xulihang/ImageTrans-docs/issues/157#issuecomment-1052121718
