### ISSUE TITLE
系统内存用光

### ISSUE THREAD

**Issue by jacknion** [xulihang/ImageTrans-docs#168]
<img width="465" alt="截屏2022-02-27 下午1 28 52" src="https://user-images.githubusercontent.com/100390443/155869746-ed6b4594-a907-42b7-882d-98ce83262ae3.png">

当批处理翻译一个大的目录时，在气泡识别时，内存会快速上涨。
然后到了一定阶段，内存没有了，imagetrans 的进度条就会假死不动。
有时在ocr时，也会卡死不动。

**Comment by xulihang** [comment]
应该是图片比较大，不要用在线的气泡识别和全图ocr，改成离线版气泡识别，按文字区域ocr。

**Comment by xulihang** [comment]
气泡识别使用的神经网络，模型加载会耗费点内存，后续计算主要占用CPU，内存占用应该不会上升太多的

**Comment by jacknion** [comment]
重新安装了一下，问题暂时解决了。 似乎是之前用的32位版，现在换成了64位版。

**Comment by jacknion** [comment]
![WechatIMG140](https://user-images.githubusercontent.com/100390443/155888900-f50e93a4-a750-48a5-aab4-9d6dcc328c42.jpeg)

但现在在ocr的时候，总是出现这个错误。虽然不影响运行，但也想问一下，是否需要修复？

**Comment by xulihang** [comment]
应该是这个OCR API没设置，软件会用默认的设置，不影响的

**Comment by jacknion** [comment]
<img width="1076" alt="截屏2022-03-01 上午8 24 20" src="https://user-images.githubusercontent.com/100390443/156095782-df36bb0a-d3f7-4677-863f-b820f194061a.png">
<img width="873" alt="截屏2022-03-01 上午7 46 00" src="https://user-images.githubusercontent.com/100390443/156095909-26a8d33b-3c52-4c38-8b53-3e91bfa243c0.png">

还是多次出现这个假死的问题。 手头没有代码，没法具体定位这个问题的错误。 还请帮忙分析一下，可能是哪里的错误？

谢谢

**Comment by xulihang** [comment]
用的什么OCR？不要勾选竖排转横排和去除振假名，这两个操作在复杂背景下效果不好，需要额外优化。

**Comment by jacknion** [comment]
manga-ocr。
好的，我再测试一下

**Comment by jacknion** [comment]
不勾选竖排转横排和去除振假名，这个问题再也没有出现。
