### ISSUE TITLE
为什么OCR的时候一直在写剪切板？ 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#169]
![2022-03-03-19 14 54](https://user-images.githubusercontent.com/30548000/156554218-43bb06d2-2d08-42e1-bb9a-c8d5d2cf3634.png)
 OCR的时候疯狂的写剪切板 我这剪切板是带声音提醒的 这咔咔咔 我就很疑惑为什么OCR的时候会走剪切板呀？

**Comment by lhj5426** [comment]
忘记说了 用的是离线的 manga-ocr

**Comment by xulihang** [comment]
方便一些用户获取文本后做查词等后续操作，现在没有关闭这个的设置

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/156555096-9d0c1a76-d49b-4b09-9f82-351096c47962.png)
  s顺带还有一个问题 安装的字体 这个不会记录  
  
  每次新建项目还的重新安装字体

**Comment by lhj5426** [comment]
> 方便一些用户获取文本后做查词等后续操作，现在没有关闭这个的设置

噢 是有这么个操作 在一个一个或者一页 一页的确实挺方便 但是直接整本 十几页 几十页的时候 就多余了 有点
希望后续可以增加开关 

还有 你回复的页太快了我就去截个图的功夫

**Comment by lhj5426** [comment]
> 方便一些用户获取文本后做查词等后续操作，现在没有关闭这个的设置
这个字体 每次安装完 新建项目的时候 都要重新安装一次 要怎么办呀

**Comment by xulihang** [comment]
如果装系统里，它不会列出来吗？我这里这个功能主要是为了字体装在系统里还是不显示的情况。

可以做一个模板，之后通过另存为新建项目

**Comment by lhj5426** [comment]
> 如果装系统里，它不会列出来吗？我这里这个功能主要是为了字体装在系统里还是不显示的情况。
> 
> 可以做一个模板，之后通过另存为新建项目

不会列出来 很多字体不会显示出来  好像只会显示等宽字体 非等宽的不显示

**Comment by lhj5426** [comment]
> 如果装系统里，它不会列出来吗？我这里这个功能主要是为了字体装在系统里还是不显示的情况。
> 
> 可以做一个模板，之后通过另存为新建项目

值得一试 我去试试  也是个解决方法

**Comment by lhj5426** [comment]
[新兰圆-B.zip](https://github.com/xulihang/ImageTrans-docs/files/8177457/-B.zip)
我发个字体 开发者你可以试试

**Comment by xulihang** [comment]
装系统里是列不出来，暂时没想到解决方法，我调用的是编程语言默认提供的接口。

**Comment by lhj5426** [comment]
> 装系统里是列不出来，暂时没想到解决方法，我调用的是编程语言默认提供的接口。

  现在用华康方圆W7+粗体看着也挺舒服的  哈哈

**Comment by jacknion** [comment]
建议添加 关闭按钮。 剪贴板总是被占用，会让日常其他工作变得很困难。

**Comment by xulihang** [comment]
> 日常其他工作

日常其它工作有必要和使用ImageTrans同时进行的吗

**Comment by lhj5426** [comment]
> > 日常其他工作
> 
> 日常其它工作有必要和使用ImageTrans同时进行的吗

其实我想吐槽一下 ocr是最花时间的 在OCR的时候难道不可以做其他事情么 其他事情不是工作才要用到剪切板啊比如我下载资源 然后资源有密码 这时候后台在OCR 我得复制密码啊 你看这不就抢剪切板了 我这只是举一个简单的例子 你能会说密码你不会手动打么 那我就没话说了 哈哈

**Comment by xulihang** [comment]
1.7.4加了一个关闭写剪贴板的偏好设置

**Comment by lhj5426** [comment]
> 1.7.4加了一个关闭写剪贴板的偏好设置

好的这就起床更新

**Comment by lhj5426** [comment]
> 1.7.4加了一个关闭写剪贴板的偏好设置

![image](https://user-images.githubusercontent.com/30548000/180635232-08fd58d8-1cf1-467d-bce3-abeb4f6676a3.png)
看到了不过有个问题 这个功能是根据用户实际情况开关的 可不可以移动到 外侧这样方便一键点击开关
还有我刚才更想的时候打开文件目录
![image](https://user-images.githubusercontent.com/30548000/180635289-a5b3a612-8092-47f1-8281-cdab19462b77.png)
呜哇 这 文件目录太乱了 可不可以把这些识别时候的文字啊图片切片啊放一个单独路径或者  软件根目录下一个单独文件夹 这不更新不打开主目录 一打开吓一跳啊

**Comment by lhj5426** [comment]
> 1.7.4加了一个关闭写剪贴板的偏好设置

再有一个就是一直的问题 
![image](https://user-images.githubusercontent.com/30548000/180635378-6b628176-72ba-498e-b4fa-a97fe291214b.png)
每次更新覆盖 填写的API 都会被清理。。。。 可以不要清理么 每次更新都要重新设置一遍。。。

**Comment by xulihang** [comment]
>识别时候的文字啊图片切片 

多出来的图片应该是tesseract ocr后没及时删除的，之后我给它优化下吧

> 更新覆盖

可以保留之前的preferences.conf文件

> 移动到 外侧这样方便一键点击开关

有什么情况需要频繁切换是否写剪贴板吗

**Comment by lhj5426** [comment]
> > 识别时候的文字啊图片切片
> 
> 多出来的图片应该是tesseract ocr后没及时删除的，之后我给它优化下吧
> 
> > 更新覆盖
> 
> 可以保留之前的preferences.conf文件
> 
> > 移动到 外侧这样方便一键点击开关
> 
> 有什么情况需要频繁切换是否写剪贴板吗

举个例子
我是看本子用 先是自动识别气泡 然后自动ocr  这话批量OCR的情况下是不需要写剪切板的
然后呢OCR完是机器翻译和手工润色时间 这步骤的时候就会发现OCR识别不准确的问题
不准确呢就要重新识别 识别之后是需要写到剪切板的方便隔壁的划词翻译浏览器扩展快捷键取词翻译的
所以人工润色的时候 修正OCR错误 重新换源OCR的时候 这种单个独立OCR是又需要写剪切板的
所以提出了希望把这个常用开关放在软件界面上的想法

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/180635943-85eee0c7-b973-4a2b-8942-fb58fe2f5d7e.png)
就是这样 所以在未来的版本希望可以把这个功能移动出来 而不是雪藏在设置里每次去设置里开开关关

**Comment by lhj5426** [comment]
其实很多常用共都可以考虑放在软件界面上而不是二级 三级菜单
比如  我用了几个月常用的有
![image](https://user-images.githubusercontent.com/30548000/180636053-7ff118b3-3d9c-428d-9580-b0a559efa130.png)
![image](https://user-images.githubusercontent.com/30548000/180636058-09c09a7e-f261-41fa-baa3-3af114e68713.png)
![image](https://user-images.githubusercontent.com/30548000/180636063-db949d1b-e42a-4550-8620-2693aeb2b8b3.png)
![image](https://user-images.githubusercontent.com/30548000/180636074-be987468-98fa-4d3f-9b08-acd8d37f968c.png)
这种常用的都可以放到外面而不是二级 三级菜单里
软件是为了 方便用户使用的 这方面请考虑一下 开发者 老哥

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/180636159-1f393a0c-ecdd-40b4-974d-5e20e77b6990.png)
这横着空出来一排留着干啥啊
选择和字体这个可以考虑并到一起
每次选择完气泡之后想修改字体 字体修改完之后又要修改对齐都要来回切换 好麻烦的

**Comment by lhj5426** [comment]
软件本身的操作就完全无法离开鼠标你挪出来 方便用户使用 岂不美哉 总比一级一级的去找方便
咱不是PS 功能并没那么多挪出来也完全不会影响什么 只会更加便捷和使用 希望老哥能考虑到用户的操作体验
的繁琐性 重复性 在未来提供更便捷的操作  感谢老哥周末在更新软件

**Comment by lhj5426** [comment]
长时间使用真的很累 总要去一级一级菜单找 虽然我用录制鼠标动作  实现了 伪一键操作
但是 不是所有用户都会 且 怎么也不如原生的好吧  哈哈 我连续用了3个月
长时间使用 目前体验真的很将将巴巴

**Comment by xulihang** [comment]
不是所有用户的屏幕都这么大的，小屏幕会放不下添加的按钮。我看可以新增一个快速操作工具栏，用于执行常用的子菜单的操作

其它关于使用性的问题还是发个新issue吧

**Comment by lhj5426** [comment]
> 不是所有用户的屏幕都这么大的，小屏幕会放不下添加的按钮。我看可以新增一个快速操作工具栏，用于执行常用的子菜单的操作
> 
> 其它关于使用性的问题还是发个新issue吧

0 0我截图都是标配1920X1080P的屏幕分辨率
![A5](https://user-images.githubusercontent.com/30548000/180637303-1e59028a-3b65-4c22-82ed-c36192c66ccd.gif)
哈哈 这个 可以有 左侧这个每次切换都会变化
那可以增加一个空的 这个工具条然后 可以各种自定义 也是极好好 然后当然可以自定义满咿整条屏幕1920 的宽度哈哈
好的 再有问题发新的issue
