### ISSUE TITLE
重新翻译

### ISSUE THREAD

**Issue by jacknion** [xulihang/ImageTrans-docs#170]
批量翻译完成 一种语言后，选择其他语言翻译，发现无法覆盖之前翻译的内容，必须一个个手动清除掉之前的翻译才可以。

能否添加全部清除之前翻译的批处理功能？ 这样可以再次翻译。

谢谢！

**Comment by xulihang** [comment]
可以用查找与替换，启用正则表达式，替换所有译文为空白。

![image](https://user-images.githubusercontent.com/5462205/156681481-68d831bf-3b47-4d60-b4d0-65b1d927ee8a.png)

**Comment by xulihang** [comment]
或者OCR结束后，先不要翻译，把项目另存为一份

**Comment by jacknion** [comment]
好的，解决了。

翻译输出的目录名out，能否加上不同语言的前缀或者后缀？例如：zh_cn_out
这样多种翻译可以区分。

谢谢

**Comment by xulihang** [comment]
输出路径的定制化，新版本加吧

**Comment by jacknion** [comment]
好的，感谢。

**Comment by jacknion** [comment]
在做正则替换的时候，如果翻译文字太多，会提示：
java.lang.OutOfMemoryError: GC overhead limit exceeded。

然后就卡死了。

**Comment by xulihang** [comment]
应该是因为要列出结果，所以内存超了。先改用文本编辑器操作吧。

用Notepad++打开项目文件，然后搜索替换。

搜索`"target": ".*?"`

替换为`"target": ""`。

然后重新打开项目。

![image](https://user-images.githubusercontent.com/5462205/156953634-0f952edf-e0d6-4ebe-947a-41742a9d5c6a.png)

**Comment by jacknion** [comment]
好的，感谢🙏

**Comment by xulihang** [comment]
1.6.2的输出文件夹名可以在项目设置里设置了
