### ISSUE TITLE
能不能给完成增加一个提示音？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#171]
软件最耗时间的自动部分就是ocr 有时候OCR 一次上百张的画师集 这样电脑在OCR的时候 人可以去做别的事情

举个例子 
VideoSubFinderWXW.exe 视频字幕提取工具
硬字幕提取工具8.0_x64
[漫画OCR完成.zip](https://github.com/xulihang/ImageTrans-docs/files/8195366/OCR.zip)

这种工具都提供了提取完成的提示音 而且可以自己更改
希望老哥的漫画软件也能提供这种提示音 OCR时间长 人可以离开电脑去做别的事情比如在客厅打老头环
等OCR结束之后 电脑音响播放 个提示音 然后人在回来继续做剩下的工作
提示音我已经帮你做好了  希望可以支持是完成提示音

**Comment by lhj5426** [comment]
压缩包里的提示音是 .wav格式的

**Comment by xulihang** [comment]
除了OCR还有哪里要加吗，我考虑只给自定义工作流加这个提示

**Comment by lhj5426** [comment]
> 除了OCR还有哪里要加吗，我考虑只给自定义工作流加这个提示

别的 好像都挺快 就ocr 最慢 翻译什么的几分钟就完事了 oCR 从十几分钟到按小时都有 所以我个人感觉是只有OCR需要
再看看其他用户的反馈？

**Comment by xulihang** [comment]
v1.6.2的自定义工作流可以播放完成提示音了
