### ISSUE TITLE
遇到这么个问题 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#172]
![image](https://user-images.githubusercontent.com/30548000/156991009-31bd811f-6a53-45c6-9f2c-5024c78bb823.png)

开发者老哥 你看啊 机器翻译的时候 超时了 就会显示ERROR
那么问题是什么呢?
问题就是 如图 翻译超时或者频繁翻译被API限制了 会显示ERROR
如果 在这个时候 选用其他翻译重新翻译
并不会 重新填写新选择的翻译引擎 的机翻文本 还是会显示error 
然后 呢 还没有 删除 全部译文这个选项
这就导致 目前这个状况  几十页 全部都是ERROR占用在译文区域
我只能手动一个一个去译文框里手动删除 ERROR保存
 然后 才能选择新的翻译引起 进行机器翻译 
 这样才能被新的机器翻译文本回填
 需要一个 一键删除ERROR译文的 功能

**Comment by lhj5426** [comment]
现在 有的只有删除  译文区域 而没有单独的删除 译文文本

**Comment by xulihang** [comment]
批量清除译文的方法见这里：https://github.com/xulihang/ImageTrans-docs/issues/170

哪个机器翻译引擎的错误？批处理请求时间间隔设长点吧。

还有就是程序会记住之前的机器翻译结果，如果记住了错误文本，得重新启动下程序。

**Comment by lhj5426** [comment]
> 批量清除译文的方法见这里：#170
> 
> 哪个_机器翻译_引擎的错误？批处理请求时间间隔设长点吧。
> 
> 还有就是程序会记住之前的_机器翻译_结果，如果记住了错误文本，得重新启动下程序。

彩云报错

**Comment by lhj5426** [comment]
> 批量清除译文的方法见这里：#170
> 
> 哪个_机器翻译_引擎的错误？批处理请求时间间隔设长点吧。
> 
> 还有就是程序会记住之前的_机器翻译_结果，如果记住了错误文本，得重新启动下程序。

colorfulclouds 我填写了自己的API 但是翻译软件上 就会翻译
![image](https://user-images.githubusercontent.com/30548000/156998853-3e477175-96e7-47d7-9636-1183919f5b5a.png)

 然而我在其他的翻译可以用彩云API的 软件上 我的API没问题的 没有被限制 可以用的
![image](https://user-images.githubusercontent.com/30548000/156998999-0be50f2d-3007-4307-9330-2607251e138b.png)

**Comment by xulihang** [comment]
应该是语言代码问题，用zh，不要用zh_cn

**Comment by lhj5426** [comment]
> 应该是语言代码问题，用zh，不要用zh_cn

这个是创建项目的时候选择的 我已经创建好了的项目可以改嘛 在哪里改?

**Comment by xulihang** [comment]
在项目设置里改

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/156999390-4b7992a7-2b45-45af-85a2-7612750a73b1.png)
呃 找到了   话说 能吧OCR结束提示音  安排上嘛

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/156999555-31ce841b-da3a-49bd-8a52-3b65154d4d86.png)
确实  改了 就翻译了
