### ISSUE TITLE
为什么 倾斜的文字都反向显示呢? 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#175]
![image](https://user-images.githubusercontent.com/30548000/157240492-1db501ce-5284-4f19-ba93-6380daac439d.png)
如图  倾斜 的文字全部都乱序甚至反向显示了  这是为什么呢? 
在做1400页的同人志 感觉这两天遇到了好多问题哈哈 
我很抱歉 开发者老哥

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/157240834-056526cd-d94b-4240-bfff-5cb70e1babc0.png)
 开不开精确涂抹 都是反向 的

**Comment by xulihang** [comment]
不是因为倾斜，是这些文字本来是横排的，你默认设的竖排。新建一个横排样式指定给这些区域

**Comment by lhj5426** [comment]
> 不是因为倾斜，是这些文字本来是横排的，你默认设的竖排。新建一个横排样式指定给这些区域

哦  原来是这样 谢谢 麻烦你了
