### ISSUE TITLE
这部分真的很粗糙哈哈 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#176]
![image](https://user-images.githubusercontent.com/30548000/157599850-481c5838-6ed5-48c9-8d1a-465a0ce11f71.png)
这部分太粗糙了  软件上的95%的这种数字框 全都不能手动输入数字 也不能滚轮滚动数字 只能点击上下剪头 太粗糙了
可以改一下吗 我开始以为是不支持小键盘区 结果换到大键盘区 也不支持
这种输入框不能输入 很伤 而且更伤的是鼠标左键 点击起来超级麻烦 而且效率底下

**Comment by lhj5426** [comment]
嗯方向键可以 但是手要离开 鼠标 或者另一只手离开快捷键 还是不方便最好是可以手动输入

**Comment by xulihang** [comment]
这个之前有讨论过： https://github.com/xulihang/ImageTrans-docs/issues/32

手动输入的话就是要再按一下回车才生效，然后启用手动输入后方向键就不能用了。

**Comment by lhj5426** [comment]
> 这个之前有讨论过： #32
> 
> 手动输入的话就是要再按一下回车才生效，然后启用手动输入后方向键就不能用了。

太糟糕了 我试着 输入 但是 敲回车的前提是 有文字被输入并且变化 现在输入文字并没有变化 这就导致敲回车也不会键入虚空下输入的数字啊

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/157642925-a8fccdb3-2121-4c8b-9a7a-75dd0e2d5cd7.mp4

我上传了 个视频 是我操作不对吗

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/157649393-ed13a7dc-fa42-412f-b62c-d5abcacf8e2a.mp4

**Comment by xulihang** [comment]
字体设置没启用手动输入功能，别试了。我说的是启用的话输完需要手动回车生效，类似显示比例那个spinner的效果。显示比例百分比这个我加了滚轮调整，别的spinner我都没加

**Comment by xulihang** [comment]
字体设置这个可以改成现在显示比例spinner的效果

**Comment by xulihang** [comment]
字体大小直接输入加载v1.6.2了
