### ISSUE TITLE
如何在使用Sickzil-Machine插件时gpu运算

### ISSUE THREAD

**Issue by 799190761** [xulihang/ImageTrans-docs#178]
我看Sickzil-Machine是支持gpu的，但是再imagetrans中默认是cpu运算，太慢，怎么切换到gpu？

**Comment by xulihang** [comment]
我没研究过在gpu上跑，没打包gpu版的。代码在这里：https://github.com/xulihang/SickZil-Machine，可能需要安装gpu版的tensorflow，然后运行server.py

**Comment by xulihang** [comment]
v1.6.5设置sickzil-machine为默认方法时，只会处理文字区域图像而不是全图，在cpu上跑速度也还行了
