### ISSUE TITLE
Feature Req: MangaInpainting

### ISSUE THREAD

**Issue by xVoldx** [xulihang/ImageTrans-docs#179]
is it possible to add [MangaInpainting](https://github.com/msxie92/MangaInpainting)
repo : https://github.com/msxie92/MangaInpainting

![image](https://user-images.githubusercontent.com/62064902/158222784-728a110f-2ca0-4a26-a5cd-06e59038e672.png)

**Comment by xulihang** [comment]
It is possible. We just need to add an HTTP interface so that we can use [external inpaint plugin](https://github.com/xulihang/ImageTrans_plugins/tree/master/ExternalInpaint) to use it. 

But it is not easy to install it and it may take a lot of time to process.

**Comment by xVoldx** [comment]
Thanks allot for your response :)
