### ISSUE TITLE
[Bug] Missing font in select font menu

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#18]
I have the Augie font installed, but it's not showing up in the font list. If I edit the project file manually to add it as a font, it works fine, despite also not showing up in the "text edit" mode.

**Comment by xulihang** [comment]
> manually to add it as a font

So the program can use this font but cannot list it in the font list. Could you share this font? I'll try to fix this.

**Comment by lugia19** [comment]
Here it is.
[augie.zip](https://github.com/xulihang/ImageTrans-docs/files/6214936/augie.zip)

**Comment by xulihang** [comment]
I can find this font in the list, though it is listed in the bottom.

![image](https://user-images.githubusercontent.com/5462205/112741415-4340b280-8fb8-11eb-980f-a872c2f18120.png)

**Comment by lugia19** [comment]
Huh. I'll check that out, I don't think I checked the bottom of the list.

-------- Original Message --------

**Comment by jps1226** [comment]
I'm also missing the Anime Ace font despite it being installed on my PC. I'm also unable to make it work by manually editing...

**Comment by xulihang** [comment]
I tried anime ace before. It should be able to work. Try restarting ImageTrans.

**Comment by xulihang** [comment]
I've added manual font importing in v1.5.0. This should solve the missing font problem.

![image](https://user-images.githubusercontent.com/5462205/141674932-bfa2fd73-a41e-41b3-8264-207264cf9a19.png)
