### ISSUE TITLE
NOT PURCHASED ?

### ISSUE THREAD

**Issue by xVoldx** [xulihang/ImageTrans-docs#182]
![image](https://user-images.githubusercontent.com/62064902/160848374-76f10d63-6b94-46bf-8e3a-e8a7dd3c87e7.png)

i double checked the Order Reference
and email

![image](https://user-images.githubusercontent.com/62064902/160848979-d1a0deb0-24ca-4bae-9890-9306b5bd44c3.png)

I'm using NL server

**Comment by xVoldx** [comment]
a new error appear 
![image](https://user-images.githubusercontent.com/62064902/160849295-247aca83-1727-4235-b69b-1cbb961b0d7d.png)

**Comment by xulihang** [comment]
Which version are you using? Free updates are within 6 months. If you use a newer version, you may encounter such a message as well.

**Comment by xulihang** [comment]
Other reasons:

The CN server is closed, so you need to choose the NL server.

If you have problems connecting the server, check out the Internet connection.

There is chance that it is related to ipv6. You can use the `ImageTrans-ipv4.bat` to open the program.

**Comment by xulihang** [comment]
If you need to use a new version, repurchase is needed. Of course, you can still use the last version within 6 months since your previous purchase.
