### ISSUE TITLE
pixels after removing text

### ISSUE THREAD

**Issue by annistarkk** [xulihang/ImageTrans-docs#183]
hello. When I have big picture (multiple panels combined in one picture, size is like 800x4000 and more), removed text leaves pixels on the picture. here's the example
![20220403_060631](https://user-images.githubusercontent.com/102887108/161408283-ee766d59-5612-446e-bf5c-e2a4f58427b3.jpg)
![20220403_060626](https://user-images.githubusercontent.com/102887108/161408285-a3ba474e-77d9-4b29-8c99-f66f87adefea.jpg)
How to avoid this? Pictures aren't pixelated or bad quality themselves

**Comment by annistarkk** [comment]
Just checked and it also happens on normal, simple panels (not combined)

**Comment by xulihang** [comment]
Try to increase the dilation kernel size in project settings.

![image](https://user-images.githubusercontent.com/5462205/161409415-d758f5bc-ab11-4594-828d-c763acd8ac2d.png)

You can learn more about text removal here:

https://www.basiccat.org/details-about-image-text-removal-using-imagetrans/

**Comment by annistarkk** [comment]
omg thank you it's better now.
I have another question. I have output quality set on 100 but even though width is 800px on every picture, output file is often decreased in size (560px,600px,640px...), How can I stop this so every picture is saved in the same size?

**Comment by xulihang** [comment]
You need to set the percentage to 100%, or the image will be scaled.

**Comment by annistarkk** [comment]
I have it set on 100% and I have "scale too large images to speed up processing" turned off

**Comment by xulihang** [comment]
Not quality. The display percentage.
![image](https://user-images.githubusercontent.com/5462205/161409799-1d4e92a9-b79b-499d-a524-028228ecee90.png)

**Comment by annistarkk** [comment]
okay thank you, have a wonderful day
