### ISSUE TITLE
能不能增加一下快捷键 或者 工具栏扩展一下？ 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#184]
现在 用起来真好难受 你看不用户都逼成什么样了
![image](https://user-images.githubusercontent.com/30548000/161815861-d87fa3b2-8cd8-43ae-834c-ef54172f70f3.png)
这里这一排空白闲着干啥啊 把下拉菜单里常用功能挪出来啊
 现在为了一键 操作 都是用工具录制各种动作 实在不想用快捷键
 又用了一个鼠标手势制作了一个 一键快捷菜单
 这些功能本来应该是软件自己自身提供的 ！ 求大量快捷键 最好快捷键可以自定义 还有 工具栏扩展一下啊 那么多空白地方浪费啊

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/161816233-2043c893-de69-40bb-8c9b-c468aed538e8.png)
这工具栏后边都空着 把常用功能都从下拉选单中挪出来啊

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/161816553-62477d1d-930f-4a38-b164-83d7bc2213f9.png)
同样是鼠标点击 直接把按钮放在明面上 可比这种一层一层的找可强太多了  
![image](https://user-images.githubusercontent.com/30548000/161816706-15fe6337-b4e7-4a4d-a381-259ec59c74e0.png)

现在这样一点不舒服 也不效率

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/161819953-8d1d8744-c471-4901-965e-4752cc8b870e.png)
 这种反选置信度 等操作 明明快捷键就完事了 二级菜单 太麻烦了 呜呜呜 跪求开发者哥哥 增加下快捷键

**Comment by xulihang** [comment]
启发式方法是适用于所有类型的图片的，如果只是翻译日漫，可以用网盘里的日漫气泡检测。

反转文字置信度可以选中所有需要操作的区域后再操作。可以按Ctrl后单击以多选，或者切换工具栏到多选模式。

**Comment by lhj5426** [comment]
> 启发式方法是适用于所有类型的图片的，如果只是翻译日漫，可以用网盘里的日漫气泡检测。
> 
> 反转文字置信度可以选中所有需要操作的区域后再操作。可以按Ctrl后单击以多选，或者切换工具栏到多选模式。

我喜欢看的都是全彩的画师集 气泡识别并不能很好的完美识别 所以 每次每页需要操作的非常多 识别并不准确只能说是辅助 主要还是手动操作 所以 必须要用快捷键  考虑考虑 把快捷键都安排上吧
软件现在比较稳定 快捷键这个可以考虑加上了

**Comment by xulihang** [comment]
那我加个自定义功能键吧，F1-F12可以对应菜单的某个操作

**Comment by lhj5426** [comment]
> 那我加个自定义功能键吧，F1-F12可以对应菜单的某个操作

那就牛逼了 这个功能
  还有个问题  文本替换 能不能空 = 删除
![image](https://user-images.githubusercontent.com/30548000/162027384-1d2ddc52-930f-4eb9-9354-112e9c1a82f5.png)
现在 文本替换 是 如果只填写替换前 而替换后空着
会默认删除整个替换条件
而不是替换前填写 替换后 空不填写 = 默认删除替换前的字符

**Comment by xulihang** [comment]
v1.6.5添加了一个反转文字置信度的快捷键ctrl-shift-c

**Comment by lhj5426** [comment]
> v1.6.5添加了一个反转文字置信度的快捷键ctrl-shift-c

感谢 期待后续跟新的更多快捷键操作 和其他的优化 打磨

**Comment by xulihang** [comment]
v1.8.4的偏好设置里新增了快捷键，可以自定义菜单项目的快捷键
![image](https://user-images.githubusercontent.com/5462205/204080939-730c6dd5-73a8-47db-b270-ff01b84e06d7.png)

**Comment by lhj5426** [comment]
> v1.8.4的偏好设置里新增了快捷键，可以自定义菜单项目的快捷键
> 
> ![image](https://user-images.githubusercontent.com/5462205/204080939-730c6dd5-73a8-47db-b270-ff01b84e06d7.png)
> 
> 

好耶憋了个大招，感谢这就更新去～感谢

**Comment by lhj5426** [comment]
> v1.8.4的偏好设置里新增了快捷键，可以自定义菜单项目的快捷键 ![image](https://user-images.githubusercontent.com/5462205/204080939-730c6dd5-73a8-47db-b270-ff01b84e06d7.png)

尊敬的开发者老哥感谢您憋出的这个快捷键大招
但是还差一点点
![image](https://user-images.githubusercontent.com/30548000/204135494-f60b1a23-ac4c-45b1-b725-cb6352703217.png)
就是这个 字体设置里的启用本地字体样式这个
在正常的使用中难免会出现误操作 比如 已经设置了样式 但是经过一些操作  手动操作之后 样式就变成本地样式了
再想修改别的样式 或者什么操作的时候 就只能 字体设置 取消勾选 启用本地字体样式 这个 操作
如果能给这个高配操作也配置一个 快捷键 就真的舒坦了 
还有 可以预留出来10个 字体样式快捷键插槽
![image](https://user-images.githubusercontent.com/30548000/204135683-5af0b2b6-eca2-4390-9056-052f94464e16.png)
或者 字体样式本身也可以支持自定义快捷键 就不需要每页去设置 里选择样式 而是直接通过快捷键快速设置了
希望您能思量一下 这边的快捷键 配置 感谢

**Comment by lhj5426** [comment]
研究用了一下这个功能是真的牛逼
![image](https://user-images.githubusercontent.com/30548000/207499800-bdb92e8f-eaef-4614-a9f2-44763fc6e4f6.png)

就是前提麻烦点
楼上提出的操作逻辑是 一边制作一边设置新页面角色对话字体颜色
这个功能是 我需要先把漫画里所有的角色的对话颜色先设置出来然后 自动跑一边
这样85%的识别成功率
 是该说牛逼呢还是说省事呢 反正比我楼上说的那个 好用很多
