### ISSUE TITLE
字体设置问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#185]
如图 
![image](https://user-images.githubusercontent.com/30548000/162788104-94b5fad1-492f-45a0-823a-94ef52b14ed6.png)
就是在 图片界面多选 或者 在文字栏这边多选 然后设置字体
不管你选择多少个 设置生效的只有最后一个
这是问题1
问题2 
我用的是本地字体
![image](https://user-images.githubusercontent.com/30548000/162788349-cf52bef5-93fe-45e1-9702-d21e24fc3dd5.png)
每选择一个对话框设置字体
![image](https://user-images.githubusercontent.com/30548000/162788460-823dfeca-8157-44e5-bc00-480c3d5db8a0.png)
就要弹出来一个 对话框然后 选中 启用本地字体
不应该是实时性的么 选择一个设置好的字体实时性就设置了么
不需要每次都点 这个字体设置吧
![image](https://user-images.githubusercontent.com/30548000/162788754-068384d8-204d-4dc3-a18b-816986d2d5e0.png)
整的现在所有功能都要录制鼠标动作才能一键完成
要不一页对话就要弹出N次设置窗口
![image](https://user-images.githubusercontent.com/30548000/162788913-b19b6311-6a62-4829-adec-350ce6f980ee.png)

**Comment by lhj5426** [comment]
还有这个生成掩码
![image](https://user-images.githubusercontent.com/30548000/162790549-5de2603b-ce82-4459-a2b7-1341348785c1.png)
![image](https://user-images.githubusercontent.com/30548000/162790608-d1472a5b-9a61-4917-9b94-12b4a743ac81.png)
打开就直接全屏呗 为什么还要额外的去点一下呢= =理解不了 现在这些全都是用键盘鼠标宏录制动作 一键完成这些多余的操作的

**Comment by lhj5426** [comment]
还有这个半透明 默认就打上勾呗... 本来半透明 在擦出文字的时候就要用到 默认还没启动= =呜呜 难受死了

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/162791074-05890cfc-7ca8-45ea-8032-7a4ed8017331.png)
这 半透明本来很好用的功能 默认为什么不启用呢

**Comment by lhj5426** [comment]
开发者老哥这个工具很不错 让我这种LPS实现了漫画和 同人志的阅读自由
但是越使用越发现 软件的一些操作很多余 不够便利 便捷 希望 开发者能重视下
软件目前很稳定 这种毛刺稍微修理一下吧 让软件用起来更便捷方便

**Comment by lhj5426** [comment]
疫情在家没事干 正好吧 想看的同人志漫画都看了

**Comment by xulihang** [comment]
你这一下子提了太多问题了。一个issue应该只对应一个问题。

1. 字体多选设置这个目前的方法是用多选工具栏里的统一字体。
![image](https://user-images.githubusercontent.com/5462205/162860287-a1b9f459-8f3f-450a-be8e-15f253d81eef.png)
2. 字体样式选择后就行了。但目前还没做选择后立即更新效果，得重新选择下查看翻译。
3. 竖排目前字号太大会存在显示不全的问题，这个还有待更新

**Comment by lhj5426** [comment]
> 你这一下子提了太多问题了。一个issue应该只对应一个问题。
> 
> 1. 字体多选设置这个目前的方法是用多选工具栏里的统一字体。
>    ![image](https://user-images.githubusercontent.com/5462205/162860287-a1b9f459-8f3f-450a-be8e-15f253d81eef.png)
> 2. 字体样式选择后就行了。但目前还没做选择后立即更新效果，得重新选择下查看翻译。
> 3. 竖排目前字号太大会存在显示不全的问题，这个还有待更新

噢那我非常抱歉 
我是绝对既然一个人发言就在一共帖子理集中了 
行 我去试试 多选工具栏。。。

**Comment by lhj5426** [comment]
**字体样式选择后就行了。但目前还没做选择后立即更新效果，得重新选择下查看翻译**。 原来是这样  
我还**纳闷**呢不应该选择之后就设置么 为什么还要点一下设置字体呢
原来首先不是实时生效 第二个是 那个字体设置不是必须要点的
看来还得研究怎么用

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/162883479-030a5773-39a8-4f76-bade-51c41e3887a6.mp4

这个问题是比较严重的  
您看视频 用多选工具选择了3个女主的对话框 然后去设置字体
之后最后选中的一个字体被更改了 其他的2个并没有 

而 如果用统一 字体的话
这样多一步骤就很麻烦
需要先单选一个设置字体

https://user-images.githubusercontent.com/30548000/162883925-19736c6b-db3e-4aef-addd-e55b93547345.mp4


然后再多选 再选择已经被设置字体的对话 再批量设置字体 
太繁琐了


可以 多选 设置字体 之后 所有选择的文字 都被一次性更改么

**Comment by xulihang** [comment]
字体样式的多选设置添加进v1.6.4了

**Comment by lhj5426** [comment]
> 字体样式的多选设置添加进v1.6.4了

可以相对轻松的修改气泡文字了 哈哈谢谢 这就去更新体验一下
