### ISSUE TITLE
标点符号的显示问题 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#186]
![image](https://user-images.githubusercontent.com/30548000/163022847-76279e3a-a27f-49dc-9c25-85810eaae934.png)
对不起 开发者老哥我问题比较多
![image](https://user-images.githubusercontent.com/30548000/163022994-b94be294-669a-4e52-ac8a-02da7c08e881.png)
给您土下座 谢罪了 
那个如图 标点符号的问题 这个要怎么解决呀
标点符号 不在字体中间
而且有些气泡里是!? 或者?!  !!这样2个符号显示
而在咱的软件了 2个符号这种符号是分成2行显示的 图上剪头标注出来了 请问下这种问题怎么解决?

**Comment by xulihang** [comment]
可以用下面这两个双叹号和叹号问号标点：
‼
⁉

字母，非叹号和问号我设置的是右对齐，但不同字体的表现不太一致，像字母用等宽字体才能对齐，这个还有待改进。

**Comment by lhj5426** [comment]
> 可以用下面这两个双叹号和叹号问号标点： ‼ ⁉
> 
> 字母，非叹号和问号我设置的是右对齐，但不同字体的表现不太一致，像字母用等宽字体才能对齐，这个还有待改进。

感谢老哥 期待您后续的改进和优化 因为就像看漫画 而不想 也不会 PS 所以 麻烦您了 感谢

**Comment by xulihang** [comment]
数字字母的对齐显示在v1.6.4里改进了

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/163719945-f928053a-c2e9-4624-a525-f11983cdb2f9.png)
漂亮 ！ 感谢老哥 就是 快捷键方面 还请 加油哈哈
