### ISSUE TITLE
ChineseOCR Plugin

### ISSUE THREAD

**Issue by mdm508** [xulihang/ImageTrans-docs#187]
I am trying to figure out how to use the ChineseOCR plugin addon. I am wondering if I can use it to more accurately OCR chinese comics. If so how can install the plugin?

**Comment by xulihang** [comment]
1. Download ChineseOCR here: https://github.com/xulihang/ImageTrans_plugins/releases/download/plugins/ChineseOCR.zip
2. Download and put the plugin in the plugins folder.

[ChineseOCR_plugins.zip](https://github.com/xulihang/ImageTrans-docs/files/8486222/ChineseOCR_plugins.zip)

The Chinese OCR is based on this https://github.com/DayBreak-u/chineseocr_lite. It can works offline and fast, but may not be more accurate than online OCR services like baidu.

**Comment by mdm508** [comment]
got it working thanks.
