### ISSUE TITLE
增加火山翻译

### ISSUE THREAD

**Issue by Smile8848** [xulihang/ImageTrans-docs#189]

**Comment by xulihang** [comment]
代码已经写好了：https://github.com/xulihang/ImageTrans_plugins

就是火山翻译sdk的依赖包比较多，打包后有十几兆，我看看怎么精简一下

**Comment by xulihang** [comment]
插件用法：

1. 解压插件到plugins目录

[volcanoMT_plugins.zip](https://github.com/xulihang/ImageTrans-docs/files/8595585/volcanoMT_plugins.zip)

2. 下载火山翻译命令行工具到软件目录

<https://github.com/xulihang/ImageTrans_plugins/releases/download/plugins/volcmt.jar>

3. 在偏好设置里设置密钥并启用


效果一般吧

![image](https://user-images.githubusercontent.com/5462205/166089000-8e2b3b98-3824-482b-b903-4e0f12f95bff.png)
