### ISSUE TITLE
[建议]增加一个快速朗读按钮

### ISSUE THREAD

**Issue by Smile8848** [xulihang/ImageTrans-docs#191]
类似于这样，因为总是要切出朗读器然后点朗读实在是麻烦
[![LRex2V.png](https://s1.ax1x.com/2022/04/22/LRex2V.png)](https://imgtu.com/i/LRex2V)

**Comment by xulihang** [comment]
那我加一个按钮在文本编辑框下方吧
![image](https://user-images.githubusercontent.com/5462205/164910135-04ee3d7b-9010-4536-a006-d23332ea838b.png)

因为目前TTS是用的系统自带TTS，第一次用需要先选择下用哪个语言和发音人，之后可以在项目设置里修改。

**Comment by lhj5426** [comment]
原来有这种功能吗 我还特意去找了个 AI语音合成 
https://github.com/VOICEVOX/voicevox  吐血

**Comment by Smile8848** [comment]
> 原来有这种功能吗 我还特意去找了个 AI语音合成 https://github.com/VOICEVOX/voicevox 吐血

我去 居然有第三方的合成 搞得我为了用这个重装了系统，，精简版系统阉割了tts

**Comment by xulihang** [comment]
微软有在线神经网络TTS，在浏览器里能用，还没集成进ImageTrans，但导出项目为网页后是可以读的。

在线阅读器：https://blog.xulihang.me/Comics-Viewer/viewer.html?uniquename=silverpolish

**Comment by Smile8848** [comment]
> 我的服务器功能一直都工作不了 显示已断开

**Comment by Smile8848** [comment]
> 微软有在线神经网络TTS，在浏览器里能用，还没集成进ImageTrans，但导出项目为网页后是可以读的。
> 
> 在线阅读器：https://blog.xulihang.me/Comics-Viewer/viewer.html?uniquename=silverpolish

服务器
2022-04-24 11:00:52.316:INFO::JavaFX Application Thread: Logging initialized @11362ms to org.eclipse.jetty.util.log.StdErrLog
WebSocket Closed: Connection refused: no further information

**Comment by xulihang** [comment]
把这个下下来放在根目录：

https://github.com/xulihang/ImageTrans_wsServer/releases/download/builds/ImageTrans_wsServer.jar

新版可以自动下载：

![image](https://user-images.githubusercontent.com/5462205/164954245-f057ea55-62bc-46b3-9e4e-2db0ab47cecb.png)

**Comment by Smile8848** [comment]
> 把这个下下来放在根目录：
> 
> https://github.com/xulihang/ImageTrans_wsServer/releases/download/builds/ImageTrans_wsServer.jar
> 
> 新版可以自动下载：
> 
> ![image](https://user-images.githubusercontent.com/5462205/164954245-f057ea55-62bc-46b3-9e4e-2db0ab47cecb.png)

需要手动运行吗，我使用没有效果...

**Comment by Smile8848** [comment]
> 把这个下下来放在根目录：
> 
> https://github.com/xulihang/ImageTrans_wsServer/releases/download/builds/ImageTrans_wsServer.jar
> 
> 新版可以自动下载：
> 
> ![image](https://user-images.githubusercontent.com/5462205/164954245-f057ea55-62bc-46b3-9e4e-2db0ab47cecb.png)

他起作用了 感谢。

**Comment by xulihang** [comment]
v1.6.5加入这个功能了
