### ISSUE TITLE
静默翻译助手是怎么使用的呢

### ISSUE THREAD

**Issue by Smile8848** [xulihang/ImageTrans-docs#193]
似乎每次打开都需要重新配置设置 而且输出位置为什么是在
C:\Users\Smile\Desktop\ImageTrans\temp
怎么修改默认的ocr呢

**Comment by xulihang** [comment]
OCR我懒得做单独的设置，是沿用的程序主界面的OCR设置。

静默翻译器是为了命令行调用设计的，输出路径可以通过命令行设，在程序里运行默认是temp目录。

静默翻译助手是便于在图形界面中使用静默翻译器简化操作，参数都保存在静默翻译器右侧的文本框，可以保存一份下次调用。

![image](https://user-images.githubusercontent.com/5462205/164966422-146b7c9a-07fd-40e1-9e28-e9c0e446dad6.png)

**Comment by Smile8848** [comment]
> OCR我懒得做单独的设置，是沿用的程序主界面的OCR设置。
> 
> 静默翻译器是为了命令行调用设计的，输出路径可以通过命令行设，在程序里运行默认是temp目录。
> 
> 静默翻译助手是便于在图形界面中使用静默翻译器简化操作，参数都保存在静默翻译器右侧的文本框，可以保存一份下次调用。
> 
> ![image](https://user-images.githubusercontent.com/5462205/164966422-146b7c9a-07fd-40e1-9e28-e9c0e446dad6.png)

感觉不是很好用的样子，为什么自定义的工作流里的文字识别ocr它缺字 或者ocr不出来东西（用的manga-ocr）

**Comment by Smile8848** [comment]
[![L5SjOJ.png](https://s1.ax1x.com/2022/04/24/L5SjOJ.png)](https://imgtu.com/i/L5SjOJ)

**Comment by Smile8848** [comment]
[![L5pe0A.png](https://s1.ax1x.com/2022/04/24/L5pe0A.png)](https://imgtu.com/i/L5pe0A)

**Comment by xulihang** [comment]
显示比例调大点再试试吧

**Comment by Smile8848** [comment]
> 显示比例调大点再试试吧

 可以了 我去 他是从软件里比例里截图来ocr的吗

**Comment by xulihang** [comment]
ocr是根据当前文本框控件位置算的，静默翻译则是根据保存的像素值
