### ISSUE TITLE
全彩关于文字颜色的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#194]
![b7919c41a529d0e632aa3396a3829677(CUnet)(noise_scale)(Level0)(x3 000000)](https://user-images.githubusercontent.com/30548000/166394516-72ce92a8-a62b-4e38-b180-a34e513d1c19.png)
先下跪谢罪
然后发问题
尊敬的开发者老哥 
这次遇到了这种问题
![image](https://user-images.githubusercontent.com/30548000/166394545-13fffd35-580d-45d5-a5bc-b9bcdf473eb0.png)
 原图
![image](https://user-images.githubusercontent.com/30548000/166394668-2780558b-d0ce-4294-a5ce-5ff0670dcb30.png)
就是原图 气泡有部分是**彩色**的就如图这个**心形图案**
然后嵌字之后 **并不能**对『**一个起泡里**的【**部分文字**】进行**改色**』
这么样的问题
如果完全不上色看上去有点不和谐
如果全上色也有点不和谐 
可以对文字编辑进行一下优化么 让一个气泡里选中的部分文字进行改色
就类似这样的 一个气泡里可以设置颜色字体全都不同

![image](https://user-images.githubusercontent.com/30548000/166395755-c16e8974-2b68-4132-ba13-3f3ffb368690.png)

**Comment by xulihang** [comment]
行内富文本编辑，目前横排支持行内加粗和斜体，竖排什么都不支持，也不能所见即所得地编辑。

要添加的话我考虑用bbcode这样的代码支持富文本，用法比如：嗯…… [textcolor=red]♥[/textcolor]

**Comment by lhj5426** [comment]
> 行内富文本编辑，目前横排支持行内加粗和斜体，竖排什么都不支持，也不能所见即所得地编辑。
> 
> 要添加的话我考虑用bbcode这样的代码支持富文本，用法比如：嗯…… [textcolor=red]♥[/textcolor]

(⊙０⊙)哇 看起来不错 期待 富文本的功能  还得 学习 怎么用 哈哈

**Comment by lhj5426** [comment]
> 行内富文本编辑，目前横排支持行内加粗和斜体，竖排什么都不支持，也不能所见即所得地编辑。
> 
> 要添加的话我考虑用bbcode这样的代码支持富文本，用法比如：嗯…… [textcolor=red]♥[/textcolor]

哈哈发这个 issues 的时候这个漫画刚出 现在 漫画都出到第二部了 过去了7个月 
![image](https://user-images.githubusercontent.com/30548000/212251703-23146443-6917-473f-b60d-583955d22cd3.png)

![image](https://user-images.githubusercontent.com/30548000/212251166-e01b5eb4-7389-4bc5-b2cc-cb9f1e67dad8.png)
 这个功能还没有实装上 哈哈 那个 弱弱的问一下 尊敬的开发者老哥
 这个功能什么时候可以开发呀

**Comment by xulihang** [comment]
基于BBCode的富文本编辑功能已经做好了，估计1.9.0发吧。相关代码：https://github.com/xulihang/BBCodeRichText

![image](https://user-images.githubusercontent.com/5462205/218299262-d560a343-a9e9-4c59-bbcd-946d5800188d.png)

**Comment by xulihang** [comment]
添加在v1.9.0了。

用法：

1. 在项目设置里启用富文本
2. 用bbcode标记需要添加样式的文本。目前支持加粗、斜体（汉字一般不支持）和颜色

   ```
   [b]粗体[/b]
   [i]斜体[/i]
   [color=#ff0000]红色[/color]
   ```

   可以嵌套使用，例如：
   ```
   [b][color=#ff0000]红色粗体[/color][/b]
   ```

**Comment by lhj5426** [comment]
> 添加在v1.9.0了。
> 
> 用法：
> 
> 1. 在项目设置里启用富文本
> 2. 用bbcode标记需要添加样式的文本。目前支持加粗、斜体（汉字一般不支持）和颜色（16进制表示的RGB颜色）
>    ```
>    [b]粗体[/b]
>    [i]斜体[/i]
>    [color=#ff0000]红色[/color]
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    可以嵌套使用，例如：
>    ```
>    [b][color=#ff0000]红色粗体[/color][/b]
>    ```

我草  我草 [23开年 重量级更新  
![image](https://user-images.githubusercontent.com/30548000/218317972-8a1667bc-f05e-418f-88b6-953f6ba3179e.png)

时隔8个月 （づ￣3￣）づ╭❤～   爱你哦 开发者老哥

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/218318045-4d65315d-ecbf-412d-8a58-8b71d5f5ad9d.png)
然后是不是可以打磨一下  在 文字编辑 选单 弄个 选择插入？ 
这样会不会更加便捷点 比如 划词选中文字之后 设置延时 或者 加粗 ？

**Comment by lhj5426** [comment]
就可以实现Ps 这种效果了
还有字体大小也可以加一个把？

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/218318599-547e5919-734a-4402-9e78-6d7b85492d83.mp4

现在文字编辑这边还不支持富文本 要是支持富文本是不是可以实现这种效果呢

虽然现在手动可以编辑 
但是有时候还是听麻烦的

https://user-images.githubusercontent.com/30548000/218318631-4dde2202-52a7-400a-a09d-bf961eff061f.mp4

字体 的大小调解 也请 无比 在后续的更新 安排上 这次更新真是 对嵌字的重量级功能更新

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/218319484-2c27a850-cac7-4042-bf68-9bc933bb5b97.mp4
虽然可以设置一键输入代码 但是颜色还得额外开一个 rgb 调色工具
所以请您 务必考虑一下可否 在
![image](https://user-images.githubusercontent.com/30548000/218319529-3724b6cd-cd78-4fc3-85a0-ede47c9788ce.png)

这些地方？ 增加 富文本设置

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/218320289-082afc4d-eec8-4e83-85af-7d230f2ff9ca.mp4

都是代码操作 但是有个 可以 快速的可视化设置还是挺方便的 那视频字幕制作软件
aegisub 来举个例子 输出的都是代码 但是有可视化界面
所谓恳请 务必考虑一下 后续更新 安排上 感谢

**Comment by xulihang** [comment]
编辑功能会加上的，我还没想好怎么做比较合适。字体大小的话，用于竖排会破坏文字的整齐性，所以我没加这个

**Comment by lhj5426** [comment]
> 编辑功能会加上的，我还没想好怎么做比较合适。字体大小的话，用于竖排会破坏文字的整齐性，所以我没加这个

慢慢打磨   辛苦开发者老哥了  字体大小这方面也是

**Comment by xulihang** [comment]
富文本编辑器加在v1.9.3了。具体见此：https://github.com/xulihang/ImageTrans-docs/issues/390
