### ISSUE TITLE
项目设置里的文字区域检测下面的可选操作添加后，似乎没什么效果

### ISSUE THREAD

**Issue by kimolate2** [xulihang/ImageTrans-docs#196]
![image](https://user-images.githubusercontent.com/13870033/167652244-d652ae35-4f1e-4112-bbf3-95c411c8230c.png)
项目设置里的文字区域检测下面的可选操作添加后，似乎没什么效果；不知道这里是不是指OCR识别文字后进行的后续操作，还是我理解错了

**Comment by kimolate2** [comment]
好的明白了，另外想问下普通的ocr文字识别后，我想使用下过滤（水平投影...)，但是批处理里面没有这个选项，想问下有什么方法可以实现

**Comment by xulihang** [comment]
目前只能编辑-文字区域操作里手动执行。这个操作是实验性的，实际用处不大

**Comment by kimolate2** [comment]
因为我正好翻译一张这样的图片（使用过滤（水平投影...)后，一些不必要的图标被排除了）时有不错的效果，所以希望可以实现一下，或者通过参数或配置文件也行
![image](https://user-images.githubusercontent.com/13870033/167758357-015e2526-263a-4321-93f8-a3bc87d56bf8.png)

**Comment by xulihang** [comment]
可以在文字区域检测设置里只保留过滤操作，然后用批处理里的启发式文字检测

**Comment by kimolate2** [comment]
启发式文字检测效果不太好，基本识别不到文字区域；可能是这种图片类型不适合，只能用普通的文字识别方式，批处理使用启发式也是一样，效果不好
![image](https://user-images.githubusercontent.com/13870033/167762062-2e941b45-5211-4705-a566-664962a5bfba.png)
左边是自动识别文字，右边是启发式
![image](https://user-images.githubusercontent.com/13870033/167761988-475d60ed-9c5c-43d0-b330-3cf23218cf6d.png)

**Comment by xulihang** [comment]
黑底白字需要在文字区域检测的设置里勾选反转颜色

**Comment by xulihang** [comment]
> 可以在文字区域检测设置里只保留过滤操作，然后用批处理里的启发式文字检测

这个操作不可行，我忘记这个不能用于处理现有文字区域了

**Comment by kimolate2** [comment]
> 黑底白字需要在文字区域检测的设置里勾选反转颜色

这样效果也不行，我试了好像自动识别文字就是比启发式更准确；所以希望就是在自动识别文字的基础上，可以再使用过滤（水平投影...)这个选项，不知道是不是可以在批处理里面添加一下这个选项，或者暂时有什么参数可以直接使用的呢？

**Comment by xulihang** [comment]
现在没有批处理支持调用这个操作。发张原图来吧，我看看是不是有这个必要

**Comment by kimolate2** [comment]
> 现在没有批处理支持调用这个操作。发张原图来吧，我看看是不是有这个必要
我用的是baidu_accurate，下面是图片
![losslesscut_screenshot](https://user-images.githubusercontent.com/13870033/167837353-375c0c95-1544-4474-a389-20daf2a2606e.jpg)

**Comment by xulihang** [comment]
这是软件界面的截图，是要翻译软件的使用手册里的图吗

**Comment by kimolate2** [comment]
是的，是一些软件操作界面

**Comment by xulihang** [comment]
这张图的文字间还有图标，需要很多手动调整，自动翻译的效果不会很好的，过滤操作没必要添加
![image](https://user-images.githubusercontent.com/5462205/167852472-986755e4-af31-49ad-a389-01a4696e9990.png)

![image](https://user-images.githubusercontent.com/5462205/167852743-8369e329-596f-4a3e-b65a-0ff2d32d93a7.png)

**Comment by xulihang** [comment]
要自动话我建议申请一个腾讯文字识别，识别出来的区域和文字贴合度比较好

**Comment by kimolate2** [comment]
好的，了解了，我去试试
