### ISSUE TITLE
是否有办法在图像OCR识别前对图像进行二值化处理

### ISSUE THREAD

**Issue by zl70971** [xulihang/ImageTrans-docs#199]
Manga-ocr似乎对无气泡的彩色背景，识别精准度较差，请问有没有办法对图像进行预处理后再进行识别

**Comment by xulihang** [comment]
有图吗？我感觉不是背景的关系，是它对长段文字的识别效果不好

**Comment by zl70971** [comment]
![image](https://user-images.githubusercontent.com/96489537/167993012-8d84110b-f495-4170-8858-594665384976.png)
似乎确实是因为长段文字的缘故，缩小选框后效果好了很多

**Comment by xulihang** [comment]
可以换google_drive_ocr或者其它ocr。

如果能去除背景，这些文字用tesseract应该也能识别，但目前没有这个选项。

**Comment by zl70971** [comment]
一般这种cg原作者都会提供纯背景的差分 类似这样
![213_0101](https://user-images.githubusercontent.com/96489537/168075760-f64e907f-162a-4f7a-99a1-b56f8c04083e.jpg)
感觉还是很大的一个需求，而且这还会大大方便嵌字。请问您有兴趣做一个在有纯背景图的基础上对cg图进行去除背景预处理的功能吗？

**Comment by xulihang** [comment]
有测试图吗，有原图的话去背景应该很容易的

**Comment by zl70971** [comment]
[测试图.zip](https://github.com/xulihang/ImageTrans-docs/files/8681139/default.zip)
找了几组测试图

**Comment by xulihang** [comment]
试了下能去除背景，用tesseract也能识别，就是有些汉字会识别错误

![image](https://user-images.githubusercontent.com/5462205/168263271-6a145add-9ad4-4d60-a90f-a967ec6c238a.png)

![thresh1](https://user-images.githubusercontent.com/5462205/168263295-32aedddb-7857-468b-ae28-05f11b8d81ac.jpg)

![thresh1](https://user-images.githubusercontent.com/5462205/168263315-32dffea6-108c-46e5-9007-72e84e1d1fe0.jpg)

**Comment by zl70971** [comment]
这个效果确实很好了

**Comment by zl70971** [comment]
有机会在下个版本中看到吗？或者有没有单独开发的小插件啥的。
如果能直接回填到背景中，就更好了 看到之间有一位朋友深受文字抹除的折磨，如果可以直接回填到背景中，就不再担心很多cg图的文字抹除的问题了

**Comment by xulihang** [comment]
怎么集成进去还需要设计一下，下一版添加吧

**Comment by xulihang** [comment]
我试了下百度、WinRT和Google drive都能识别这种背景的文字，它们用的自然场景文字识别方法，本身是能处理复杂背景的，二值化预处理功能我不打算加了，但还是会提供设置无文字原图的功能，这样这种CG图集就不用再去抹除文字了。

**Comment by lhj5426** [comment]
> 我试了下百度、WinRT和Google drive都能识别这种背景的文字，它们用的自然场景文字识别方法，本身是能处理复杂背景的，二值化预处理功能我不打算加了，但还是会提供设置无文字原图的功能，这样这种CG_图集_就不用再去抹除文字了。

好耶 以后做画师CG可以省事了 话说 无气泡的文字 框选可以支持吗

**Comment by lhj5426** [comment]
![0005](https://user-images.githubusercontent.com/30548000/168477313-a9478857-de59-4eb0-a6e8-c49b2d2c6c8c.jpg)
这样的一个气泡都没有
![0062](https://user-images.githubusercontent.com/30548000/168477340-052e1bcb-9cf6-4ae8-a3dc-f1ef8bb47b38.jpg)
![0149](https://user-images.githubusercontent.com/30548000/168477364-396ba017-4c6b-4d7a-8eed-4fc68728d325.jpg)

**Comment by lhj5426** [comment]
> 我试了下百度、WinRT和Google drive都能识别这种背景的文字，它们用的自然场景文字识别方法，本身是能处理复杂背景的，二值化预处理功能我不打算加了，但还是会提供设置无文字原图的功能，这样这种CG_图集_就不用再去抹除文字了。

winrt 是怎么用的也需要申请API吗 我昨天刚做完系统21H2遇到了BUG
现在用的
![image](https://user-images.githubusercontent.com/30548000/168477433-6b237481-fdf4-4812-b1c4-6bf680308ce7.png)
支持winrt吗

**Comment by xulihang** [comment]
无气泡的需要用OCR服务提供的位置信息，WinRT、有道、百度OCR应该都可以。离线的话这个应该最好：https://github.com/zyddnys/manga-image-translator，但本地跑比较慢

**Comment by xulihang** [comment]
WinRT就是Windows 10自带OCR，系统语言里安装日语后就能用了

**Comment by lhj5426** [comment]
> WinRT就是Windows 10自带OCR，系统语言里安装日语后就能用了

![image](https://user-images.githubusercontent.com/30548000/168477587-46b5a2e8-fc8b-496c-bcef-70f94b0fa688.png)
是这样an'z安装吗

**Comment by xulihang** [comment]
是的

**Comment by lhj5426** [comment]
> 是的

![image](https://user-images.githubusercontent.com/30548000/168477875-e930b173-697f-4965-8b52-f433db48c369.png)
这应该是没安装sha上 还是系统不支持？

**Comment by lhj5426** [comment]
> 无气泡的需要用OCR服务提供的位置信息，WinRT、有道、百度OCR应该都可以。离线的话这个应该最好：https://github.com/zyddnys/manga-image-translator ，但本地跑比较慢

然后 如果用百度 和有道的话
![image](https://user-images.githubusercontent.com/30548000/168477942-9e78aa62-3459-4528-8098-20560731b085.png)
![image](https://user-images.githubusercontent.com/30548000/168477953-45a52cab-a237-44f8-bcc4-dcb2a14935f4.png)
这里应该要选哪个操作才会自动框选？ 识别竖排无气泡文字

**Comment by xulihang** [comment]
光学字符识别是没装吗？

可以试试下载这个压缩包，解压到`C:\Windows\OCR`：
[ja-jp.zip](https://github.com/xulihang/ImageTrans-docs/files/8695169/ja-jp.zip)

自动识别文字是用OCR服务进行文字定位和识别的。

**Comment by lhj5426** [comment]
> 光学字符识别是没装吗？
> 
> 可以试试下载这个压缩包，_解压_到`C:\Windows\OCR`： ja-jp.zip
> 
> 自动识别文字是用OCR服务进行文字定位和识别的。

![image](https://user-images.githubusercontent.com/30548000/168478176-b54094b0-d97e-458c-98ef-59b24ed1de43.png)
哈哈哈哈 效果可以说是没有哈哈WINRT

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/168478242-7436a807-7a83-4606-926c-a39b03af8767.png)
哈哈 会了 原来点自动识别 百度就自己去识别了 会了 哈哈比离线的win 好很多

**Comment by lhj5426** [comment]
不错 这本600页的CG从去年就躺在我的硬盘里 即使买了这个软件半年也因为没有气泡手动框选太累 一直搁置
现在知道怎么识别无气泡了 搞起 哈哈 谢谢老哥 等老哥的下一版 设置无文字原图的功能 我就开始弄这本

**Comment by lhj5426** [comment]
> 光学字符识别是没装吗？
> 
> 可以试试下载这个压缩包，_解压_到`C:\Windows\OCR`： ja-jp.zip
> 
> 自动识别文字是用OCR服务进行文字定位和识别的。

![image](https://user-images.githubusercontent.com/30548000/168478614-9ebdac58-6b08-4478-a5bd-95e51be4c5e5.png)
这个是WINRT识别的有时候也很准确就是这个字和字直接全是空格顺便提供一个去文字间空格的功能吧 谢谢

**Comment by xulihang** [comment]
可以用查找与替换功能，或者勾选去除空格后点一下上下合并。因为去除空格勾选上后，在OCR单个区域和合并区域时会去除空格，这里可以这样用

**Comment by lhj5426** [comment]
> 可以用查找与替换功能，或者勾选去除空格后点一下上下合并。因为去除空格勾选上后，在OCR单个区域和合并区域时会去除空格，这里可以这样用。
> 
> 全图OCR现在勾选去除空格时不会删空格，这个我给它加上吧

嗯   查找和替换 
自定更正 我之前提到过一个 问题 您可能忽略了
![image](https://user-images.githubusercontent.com/30548000/168478960-c2be70fe-fde0-4d4f-8c69-902bfbaba64e.png)
就是自动更正的功能
现在的自动 更正前 写 更正后不写 可以默认为去掉么
举个例子
更正前写 1 更正后空着不写 = 去掉1
现在呢更正前写1 更正后如果空着 默认= 这个更正不生效
![Uploading image.png…]()

有时候只是想去掉一些标点  用查找替换的话 很多标点 很麻烦的

**Comment by lhj5426** [comment]
> 可以用查找与替换功能，或者勾选去除空格后点一下上下合并。因为去除空格勾选上后，在OCR单个区域和合并区域时会去除空格，这里可以这样用。
> 
> 全图OCR现在勾选去除空格时不会删空格，这个我给它加上吧

嗯   查找和替换 
自定更正 我之前提到过一个 问题 您可能忽略了
![image](https://user-images.githubusercontent.com/30548000/168478960-c2be70fe-fde0-4d4f-8c69-902bfbaba64e.png)
就是自动更正的功能
现在的自动 更正前 写 更正后不写 可以默认为去掉么
举个例子
更正前写 1 更正后空着不写 = 去掉1
现在呢更正前写1 更正后如果空着 默认= 这个更正不生效
![Uploading image.png…]()

有时候只是想去掉一些标点  用查找替换的话 很多标点 很麻烦的

**Comment by xulihang** [comment]
好的，那允许替换后的内容是空，然后可以设定规则用于ocr，机器翻译还是输入的文本

**Comment by lhj5426** [comment]
> 好的，那允许替换后的内容是空，然后可以设定规则用于ocr，_机器翻译_还是输入的文本

替换OCR完的原文内的就行  应该是输入文本？

**Comment by lhj5426** [comment]
> 好的，那允许替换后的内容是空，然后可以设定规则用于ocr，_机器翻译_还是输入的文本

对下一个版本期待嗷嗷的哈哈 辛苦了

**Comment by zl70971** [comment]
作者你好 如果有条件支持背景去除的话 还是希望能加入以下
因为今天在测试了百度ocr服务后感觉位置识别还是经常出问题，最重要的是会识别到一些错误的位置，比如语气词。
删除这些框和调整原先没有识别位置的框都需要额外花费时间，如果去除背景后，这些问题带来的困扰都将大大减少。
谢谢你了！

**Comment by xulihang** [comment]
功能已经做好了，讲下目前的用法吧：

通过菜单进入无文字原图和纯文字图管理器，点击图片可以查看和设置该图片的无文字图和纯文字图。设置无文字图支持多选后操作，纯文字图的生成支持批处理和参数调整。

![image](https://user-images.githubusercontent.com/5462205/169655014-6d595aae-4397-4cd8-926a-60938db6ab3f.png)

![image](https://user-images.githubusercontent.com/5462205/169655036-629b136b-8cdc-4e12-bf3a-9a9ce6fbc043.png)

原图和纯文字图的存储路径如下图：

![image](https://user-images.githubusercontent.com/5462205/169655143-b0d828d3-9357-4b9c-aace-236ffc7452db.png)

**Comment by xulihang** [comment]
添加在v1.7.0了

**Comment by lhj5426** [comment]
> 功能已经做好了，讲下目前的用法吧：
> 
> 通过菜单进入无文字原图和纯文字图管理器，点击图片可以查看和设置该图片的无文字图和纯文字图。设置无文字图支持多选后操作，纯文字图的生成支持批处理和参数调整。
> 
> ![image](https://user-images.githubusercontent.com/5462205/169655014-6d595aae-4397-4cd8-926a-60938db6ab3f.png)
> 
> ![image](https://user-images.githubusercontent.com/5462205/169655036-629b136b-8cdc-4e12-bf3a-9a9ce6fbc043.png)
> 
> 原图和纯文字图的存储路径如下图：
> 
> ![image](https://user-images.githubusercontent.com/5462205/169655143-b0d828d3-9357-4b9c-aace-236ffc7452db.png)
> 
> 具体用途：
> 
> OCR和启发式文字检测会自动选用纯文字图
> 
> 查看翻译时会自动使用无文字原图

这就下载更新找个图体验体验

**Comment by lhj5426** [comment]
> 功能已经做好了，讲下目前的用法吧：
> 
> 通过菜单进入无文字原图和纯文字图管理器，点击图片可以查看和设置该图片的无文字图和纯文字图。设置无文字图支持多选后操作，纯文字图的生成支持批处理和参数调整。
> 
> ![image](https://user-images.githubusercontent.com/5462205/169655014-6d595aae-4397-4cd8-926a-60938db6ab3f.png)
> 
> ![image](https://user-images.githubusercontent.com/5462205/169655036-629b136b-8cdc-4e12-bf3a-9a9ce6fbc043.png)
> 
> 原图和纯文字图的存储路径如下图：
> 
> ![image](https://user-images.githubusercontent.com/5462205/169655143-b0d828d3-9357-4b9c-aace-236ffc7452db.png)
> 
> 具体用途：
> 
> OCR和启发式文字检测会自动选用纯文字图
> 
> 查看翻译时会自动使用无文字原图

![image](https://user-images.githubusercontent.com/30548000/169694041-330381f8-d135-4ae4-9233-b11c40eb29e1.png)
![image](https://user-images.githubusercontent.com/30548000/169694054-cb90a9da-b91b-46ca-a9aa-fb08396bf10d.png)
是我没有理解怎么用吗？

**Comment by xulihang** [comment]
这张原图没有阴影，和有文字的图差别比较大

**Comment by lhj5426** [comment]
> 这张原图没有阴影，和有文字的图差别比较大

明白了 谢谢     研究出配合无背景图的用法 也不错

**Comment by xulihang** [comment]
我更新了下mangaocr的插件，如果是单行长条文字，会把文字拆分成几段进行识别，这样基本就都能识别出来了。

更新版插件：https://github.com/xulihang/ImageTrans-docs/files/10887754/manga-ocr-plugin.zip

**Comment by lhj5426** [comment]
> 我更新了下mangaocr的插件，如果是单行长条文字，会把文字拆分成几段进行识别，这样基本就都能识别出来了。
> 
> 更新版插件：https://github.com/xulihang/ImageTrans-docs/files/10887754/manga-ocr-plugin.zip
> 
> 具体说明见readme：https://github.com/xulihang/ImageTrans_plugins/blob/master/mangaOCR/readme.md

老哥 我没看懂

下载 将模型文件 [到文件夹中： detect.ckpt ](https://github.com/zyddnys/manga-image-translator/releases/download/beta-0.2.1/detect.ckpt), [ocr.ckpt ](https://github.com/zyddnys/manga-image-translator/releases/download/beta-0.2.1/ocr.ckpt), [修复.ckpt](https://github.com/zyddnys/manga-image-translator/releases/download/beta-0.2.1/inpainting.ckpt)
通过运行启动服务器 run.bat.
到哪个文件夹 运行哪个服务器？ run？？

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/222898439-0e971855-07c6-464b-ae84-a42a692bdfb1.mp4

太爱你了 牛逼  开发者老哥 这次妥妥的识别上了

**Comment by xulihang** [comment]
中文说明在百度网盘里

**Comment by lhj5426** [comment]
> _中文_说明在百度网盘里

囧没去百度云看 直接 github 搞定了  非常感谢 现在大概率看漫画可以不挑了 以前只能看气泡 现在纯文字的也没事了

**Comment by xulihang** [comment]
manga translator的去除文字还不太行，需要出个新版本支持默认以全图为单位处理图片

**Comment by lhj5426** [comment]
> _中文_说明在百度网盘里

主要是最近 一系列的下载百度云的工具脚本都挂了 就拒绝使用百度云了

**Comment by lhj5426** [comment]
> manga translator的去除文字还不太行，需要出个新版本支持默认以全图为单位处理图片

嗯 期待未来的新版本

**Comment by lhj5426** [comment]
> manga translator的去除文字还不太行，需要出个新版本支持默认以全图为单位处理图片

![image](https://user-images.githubusercontent.com/30548000/222900587-3a9922d5-75ca-431c-859d-dce1c5ff64af.png)
我按照 https://github.com/xulihang/ImageTrans_plugins
这个照猫画虎 修改了 端口之后 不好使了呢？？ 必须8080 吗？

**Comment by xulihang** [comment]
偏好设置设错了，mangaTranslator，不是mangaocr。

**Comment by lhj5426** [comment]
> 建议改mangaocr的端口，mangaTranslator不用改

嗯 谢谢 了解了 主要是 我电脑上 随时都开一堆东西  而且我听说很多软件都用8080 这个端口所以想说 给它避开 避免出现一些奇奇怪怪的问题。。。

**Comment by lhj5426** [comment]
> 建议改mangaocr的端口，mangaTranslator不用改

老哥 我想问一下今天这个 插进更新只会 可以识别竖排
![image](https://user-images.githubusercontent.com/30548000/222907731-f365d53a-38da-42b4-aa27-750883eff297.png)
然后识别完zhi之后我想通过 工作流 来自动合并相邻很紧的框选组成一个大框
但是我无论选横排 还是竖排 都没有任何的合并迹象
这个合并是在什么情况下 才可以合并？

**Comment by xulihang** [comment]
把这个检测分隔关闭
![image](https://user-images.githubusercontent.com/5462205/222908007-e0b68bdc-1a6a-4f5d-8704-78d901f3c3a8.png)

**Comment by lhj5426** [comment]
> 把这个检测分隔关闭 ![image](https://user-images.githubusercontent.com/5462205/222908007-e0b68bdc-1a6a-4f5d-8704-78d901f3c3a8.png)

好的 我试试看

**Comment by lhj5426** [comment]
非常感谢 这就对了嘛 自动合并相邻的选区成一个大框

**Comment by xulihang** [comment]
@zl70971 测试图的CG叫什么名字？我想看一下

**Comment by lhj5426** [comment]
> @zl70971 测试图的CG叫什么名字？我想看一下

[Sage (りゅんぬ)] 交尾奉納!誘惑の天狐ちゃん!?～限界じゃあ!もう種付は堪忍しろぉ!～
https://exhentai.org/g/1548047/2a64844a5b/
这个 测试图是这个 CG
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/925ef159-1060-4e27-a426-6c24e11eb262)

**Comment by xulihang** [comment]
好的，这个开头的场景描写还挺好的
