### ISSUE TITLE
气泡检测能调整检测出来的文字框的大小吗

### ISSUE THREAD

**Issue by tiger2012010** [xulihang/ImageTrans-docs#200]
我现在使用的是离线的气泡检测，总是感觉检测出来的效果都是贴着文字边的，如下：
<img width="129" alt="Snipaste_2022-05-12_11-47-33" src="https://user-images.githubusercontent.com/95688933/167988237-cc4d7f71-e0d1-472f-a141-a016315b438b.png">
<img width="53" alt="Snipaste_2022-05-12_11-48-12" src="https://user-images.githubusercontent.com/95688933/167988243-3f91a14c-129e-4de4-8d6d-0a37a6a4e8d6.png">

有没有什么办法能让这个框默认的就大一点，类似掩膜大小那样的设置？

**Comment by xulihang** [comment]
可以在项目设置里把拓展区域像素设大一点

![image](https://user-images.githubusercontent.com/5462205/167990418-306adf95-6d08-4929-9f0f-406706c03ac7.png)

**Comment by tiger2012010** [comment]
> 可以在项目设置里把拓展区域像素设大一点
> 
> ![image](https://user-images.githubusercontent.com/5462205/167990418-306adf95-6d08-4929-9f0f-406706c03ac7.png)

好的，我测试一下效果
