### ISSUE TITLE
Sickzil-Machine方法无法设置

### ISSUE THREAD

**Issue by tiger2012010** [xulihang/ImageTrans-docs#201]
我在[https://github.com/xulihang/ImageTrans_plugins](https://github.com/xulihang/ImageTrans_plugins)页面下载了所需的插件和文件，同时成功运行如下：
<img width="854" alt="Snipaste_2022-05-12_12-12-30" src="https://user-images.githubusercontent.com/95688933/167990879-4692ba72-1e0b-45dc-9110-ce16e66e5dab.png">

但是在应用里，我没有找到设置里的选项有变化，请问是哪里操作不对吗？
<img width="187" alt="Snipaste_2022-05-12_12-12-04" src="https://user-images.githubusercontent.com/95688933/167990885-276d9c44-e5ed-4d4f-b28d-adfc32d3d81f.png">
<img width="243" alt="Snipaste_2022-05-12_12-04-42" src="https://user-images.githubusercontent.com/95688933/167990937-fe109890-131e-419f-9ec6-a386522afcf0.png">

**Comment by xulihang** [comment]
重启下软件看看

**Comment by xulihang** [comment]
噢，应该是掩膜生成的插件没有放进去，那个ExternalMaskGen

**Comment by tiger2012010** [comment]
> 噢，应该是掩膜生成的插件没有放进去，那个ExternalMaskGen

我重启了一下电脑还是不行
那个截图下面就是ExternalMaskGen吧

**Comment by xulihang** [comment]
有解压后放到plugins目录吗？用ImageTrans.bat启动软件，把输出复制过来看看

**Comment by tiger2012010** [comment]
> 有解压后放到plugins目录吗？用ImageTrans.bat启动软件，把输出复制过来看看

在的，截图目录就是plugins，请问那个输出复制是什么？图片的输出吗？

**Comment by tiger2012010** [comment]
> 有解压后放到plugins目录吗？用ImageTrans.bat启动软件，把输出复制过来看看

你好，我重新下载了一遍插件覆盖了一次，现在就成功了，不知道之前是什么原因，但现在ok了
