### ISSUE TITLE
Pdf导入后出现这种情况应该如何处置

### ISSUE THREAD

**Issue by zl70971** [xulihang/ImageTrans-docs#202]
![image](https://user-images.githubusercontent.com/96489537/168444160-3b942306-58cb-47b7-93d6-4500deee86ae.png)
如何让这些识别框合并在一起进行ocr和翻译

**Comment by xulihang** [comment]
这个PDF的字是不是可以复制的？ImageTrans会提取可复制文字的。合并的话就是上下合并再左右合并，如果点按钮没反应，应该是分辨率比较高，需要在项目设置里把生长高度和宽度设大一点

**Comment by zl70971** [comment]
这个问题解决了 谢谢你~
