### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by NinjaAquaKin** [xulihang/ImageTrans-docs#205]
1：导出的图像比原图分辨率低怎么办
2：翻译的时候怎么让标点符号居中显示啊，省略号句号之类的，还有就是向下指的破折号能打出来吗

**Comment by NinjaAquaKin** [comment]
问题1
我在65％情况下排好的版调回100％时排版自己就乱了，框的大小自己会变有的字被挤到外面，这个什么情况

**Comment by xulihang** [comment]
用的什么版本？后来的版本有修复这个问题，相关issue：https://github.com/xulihang/ImageTrans-docs/issues/94 https://github.com/xulihang/ImageTrans-docs/issues/122

**Comment by xulihang** [comment]
更新的价格要低一点，购买页面：https://mianbaoduo.com/o/bread/YpmUmJps

**Comment by NinjaAquaKin** [comment]
我上一次买是去年6月，刚才在你那个链接又转了50，下的1.6.5版本，怎么登录的时候还是显示我未购买啊
订单号和去年的是一样的么，也没收到新邮件
还是说我的登陆的时候没有选对？

**Comment by NinjaAquaKin** [comment]
我付款的时候用的邮箱和去年买的时候是一个邮箱

**Comment by NinjaAquaKin** [comment]
嗯嗯没事了已经解决了

**Comment by NinjaAquaKin** [comment]
问题1
我在65％情况下排好的版调回100％时排版自己就乱了，框的大小自己会变有的字被挤到外面，这个什么情况


这个我安装了最新版以后还是会出现这个问题怎么办？

**Comment by xulihang** [comment]
能发个项目来我测试下吗

**Comment by NinjaAquaKin** [comment]
这个问题有时候放大会出现有时候不会出现
我再使用一段时间看看情况吧

可以直接在这里再问一个问题么
我项目里加载的是分辨率很高的图片 翻译出来的文字在排版模式下拉到最大只能到100，再往上需要点字体手动调，这个是没办法直接拉到更大么？

**Comment by xulihang** [comment]
自动字体大小的最大值和最小值可以在项目设置里调整

**Comment by NinjaAquaKin** [comment]
好的谢谢

另外抱歉我没找到更新说明
请问现在排版模式 查看翻译什么的还是没有快捷键吗？

**Comment by xulihang** [comment]
目前还没有，组件的快捷键怎么设比较好，我还没研究过

**Comment by NinjaAquaKin** [comment]
问题1
我在65％情况下排好的版调回100％时排版自己就乱了，框的大小自己会变有的字被挤到外面，这个什么情况

这个我安装了最新版以后还是会出现这个问题怎么办？


关于这个我自己测试了下大概发现问题出在哪了
就排版模式下想要拉大字体的时候有时候排版框会拉的比字体实际所占空间大一点或者大很多
这时候切换图片显示大小 比如60到100％，字体就是自动挤到新一行去
这算正常现象么

**Comment by xulihang** [comment]
可能是自动调整字体大小有点偏差。手动调整下字号（这样会启用本地样式）后再切换应该就没问题了

**Comment by xulihang** [comment]
v1.7.1添加了查看翻译和排版模式的快捷键

**Comment by NinjaAquaKin** [comment]
我再购买50那个服务的时候只要保证填写邮箱跟之前一样就行了么？

**Comment by NinjaAquaKin** [comment]
请问我购买更新的50之后，最新版的软件去哪里获取
