### ISSUE TITLE
导出翻译后再导回就显示错误，xlf格式的

### ISSUE THREAD

**Issue by kimolate2** [xulihang/ImageTrans-docs#207]
![image](https://user-images.githubusercontent.com/13870033/169224477-c2ed63b2-c69f-46d9-9693-177e34c998d0.png)
我的图片比较多，导出翻译后就算没有做任何更改，再导回也会报错。但是如果是少数几张就没问题，麻烦看下是什么问题或能否修复一下

**Comment by xulihang** [comment]
应该是xliff解析出错了，能发一个完整的文件过来吗？

xliff用的比较少，测的不多，你打算用什么工具去翻译？

**Comment by xulihang** [comment]
应该是有的图片没有文本，导致解析错误了，需要在新版里修复一下

**Comment by kimolate2** [comment]
> 应该是有的图片没有文本，导致解析错误了，需要在新版里修复一下

https://wwp.lanzouy.com/ipvYU053jjah 这是导出的文件，里面一个是源文件，一个是翻译后的

**Comment by kimolate2** [comment]
以后能支持txt格式的导回翻译吗，因为导出是支持txt格式的

**Comment by xulihang** [comment]
可以，txt有个问题就是会把换行转义为\n

**Comment by xulihang** [comment]
xlf导入问题在1.7.0中修复了，从txt导回翻译也添加了
