### ISSUE TITLE
怎么把字体背景颜色设置透明啊

### ISSUE THREAD

**Issue by kimolate2** [xulihang/ImageTrans-docs#208]
不想用自动修复背景图，但是直接使用翻译会出现字体背景，所以想问下如何设置透明背景色，让翻译直接覆盖到原图上

**Comment by xulihang** [comment]
需要在右边取消勾选建立覆盖图层，但目前没有批量设置的方法

![image](https://user-images.githubusercontent.com/5462205/169631178-4780d581-de93-414b-bb56-e3e208e36796.png)

**Comment by xulihang** [comment]
然后还需要使用非精确模式

**Comment by kimolate2** [comment]
那字体背景不能设置透明吗

**Comment by xulihang** [comment]
背景保存的是RGB值，不是RGBA，不能设置透明的

**Comment by kimolate2** [comment]
> 背景保存的是RGB值，不是RGBA，不能设置透明的

这个没办法通过改什么配置文件实现吗？

**Comment by xulihang** [comment]
噢，是可以的。先设置一个字体样式，然后用文本编辑器打开项目文件，把那条字体样式的bgColor改为transparent。

```
"fontStyles": [
            {
                "capital": false,
                "b4jfont": "System",
                "line-height": 1.25,
                "bold": false,
                "vertical-center": false,
                "fontname": "ArialMT",
                "italic": false,
                "bgcolor": "transparent",
                "size": 6,
                "name": "透明背景",
                "fontcolor": "0,0,0",
                "alignment": 0,
                "wrap": true,
                "direction": 0
            }
        ],
```

**Comment by kimolate2** [comment]
> 噢，是可以的。先设置一个字体样式，然后用文本编辑器打开项目文件，把那条字体样式的bgColor改为transparent。
> 
> ```
> "fontStyles": [
>             {
>                 "capital": false,
>                 "b4jfont": "System",
>                 "line-height": 1.25,
>                 "bold": false,
>                 "vertical-center": false,
>                 "fontname": "ArialMT",
>                 "italic": false,
>                 "bgcolor": "transparent",
>                 "size": 6,
>                 "name": "透明背景",
>                 "fontcolor": "0,0,0",
>                 "alignment": 0,
>                 "wrap": true,
>                 "direction": 0
>             }
>         ],
> ```

好的，感谢

**Comment by xulihang** [comment]
v1.7.0可以在界面里设置透明了

![image](https://user-images.githubusercontent.com/5462205/169679468-5fc3ac87-34cc-4a49-b215-1ab612b572a9.png)
