### ISSUE TITLE
可以自动记住项目的窗口状态吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#209]
![image](https://user-images.githubusercontent.com/30548000/169702615-885e11a1-2e3b-4c7e-a09f-c4b9f558b020.png)
经常报错
报错就要重开 每次重开都要去设置这些很烦啊
可以让软件自己记住项目的窗口状态吗

**Comment by xulihang** [comment]
主界面、掩膜编辑器都有需要保留的设置，这个我看看怎么实现吧

**Comment by xulihang** [comment]
加在v2.6.0了
