### ISSUE TITLE
[Bug/Improvement] Centering behavior of text is a bit janky

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#21]
Basically, if there's text within a textbox that wraps to the next line, and the text is centered, it can look a bit janky. As far as I can tell, this is due to the spaces within the text. Would it be possible to improve/fix this? It's pretty annoying since it means you need to manually fix it every time.

I've attached a screenshot showing the difference.
![textcentering](https://user-images.githubusercontent.com/21088033/112697230-0de47980-8e7f-11eb-8249-145f90d99063.png)

**Comment by xulihang** [comment]
I can't see the difference. Could you highlight it?

**Comment by lugia19** [comment]
I tried to highlight it by drawing a line in the middle of the text box - the text in the first one shifts to the left and right.
Another way to notice it is that "close" in the first example is touching the border, where in the second one it's slightly further away. 

The difference seems to be due to trailing spaces being counted in the width calculation.

![textcentering2](https://user-images.githubusercontent.com/21088033/112706251-fe732980-8e9a-11eb-8653-970ff5c27f92.png)

**Comment by xulihang** [comment]
I see. This looks annoying, but if the border is gone, the difference of the two versions is in the left position. 
As far as I know, letterers using Photoshop will use Point Text and manually cut text into lines which is time-consuming. I think ImageTrans's text wrapping makes the lettering easier. The text rendering is done using the TextFlow control in JavaFX. It may not be easy to control its behavior like removing the trailing space if it follows a line break.

**Comment by lugia19** [comment]
I see. Yes, that does sound complex to control. I think it's fine like this, might be useful to put it as a note somewhere on the documentation perhaps.

**Comment by xulihang** [comment]
This problem is finally solved in ImageTrans 3.0.0. Check out this issue: https://github.com/xulihang/ImageTrans-docs/issues/482
