### ISSUE TITLE
查看翻译的一个BUG

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#211]
如视频所示
未勾选查看翻译的情况下显示的是已勾选翻译的状态

再点击勾选 翻译之后 会出现重叠的现象 好像卡住一样了
只能通过关闭项目重开才能hui'fu恢复

https://user-images.githubusercontent.com/30548000/169722086-42cf07bc-6d29-4cba-b255-5c15645735c2.mp4

**Comment by lhj5426** [comment]
录的视频刚好12M超过了 GitHub限制的10M 压成了H265小了 但是发到GITHUB上成帕金森了？
[bandicam 2022-05-23 07-54-41-007.zip](https://github.com/xulihang/ImageTrans-docs/files/8750505/bandicam.2022-05-23.07-54-41-007.zip)
打包一个没压缩的没帕金森的 开发者老哥下载预览吧

**Comment by xulihang** [comment]
查看翻译时生成去文字图出错，或者比较慢， 切换图片时会有这个问题，我看看怎么修复下

**Comment by xulihang** [comment]
v1.7.1添加了一个右键刷新功能，可以重置当前画面

**Comment by lhj5426** [comment]
> v1.7.1添加了一个右键刷新功能，可以重置当前画面

看到了 下次出错的时候 我试试 谢谢

**Comment by lhj5426** [comment]
这个问题应该早就解决了忘记关闭了
