### ISSUE TITLE
关于字体设置和大小的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#212]
这个字体设置是部不是有问题？

https://user-images.githubusercontent.com/30548000/170073445-5d963cb3-73b7-42cf-bba9-6353096a4b58.mp4

问题1
项目设置里设置了字体的大小数值
然后在漫画里选中文字设置字体样式 字体大小不会跟着改变 如果不跟着样式里的字体大小改变那样式里的字体大小是干什么的呢？ 

问题2

https://user-images.githubusercontent.com/30548000/170073593-83d7b127-6b6a-4612-bda7-8c70a74ee618.mp4

**薛定谔的的启用本地字体**
项目设置里设置了字体
然后选中文字设置字体样式 有时候 不生效 需要去界面的字体设置里勾选 **启用本地字体样式**
有时候明明没勾选**启用本地字体样式**
也不生效反而需要去手动勾选字体样式
![image](https://user-images.githubusercontent.com/30548000/170074051-8055df90-67d2-42a7-8d36-c815854040b4.png)

最近一直在用咱的软件做本子 （爱发电）
嵌字的时候 调整字体 大小 和样式 就浪费了很多时间
可以修正这2个问题么
还有设置完字体之后可以不可以**不要取消气泡的选中状态** 有时候需要 修正其他的 还得重新去选择一次气泡框选 然后再回来设置字体

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/170083218-2b7fda0f-87b7-40ae-92d2-905e9a9756ed.mp4

本来是应该这样一键设置样式的的

**Comment by zl70971** [comment]
补充一个情况，全选文本框后，选中字体描边，似乎不能使全部字体都变成描边样式，只能一个一个改
不知是否有办法优化

**Comment by xulihang** [comment]
字体样式的优先级是这样的：

本地样式>全局样式

而文字大小是这样的：

本地样式>自动调整文字大小>全局样式


手动修改了字体大小后就启用了本地样式，不再受全局样式和自动调整文字大小的影响。

**Comment by xulihang** [comment]
@zl70971 可以设一个带描边的全局字体样式，这样所有文本框就都有描边了

**Comment by lhj5426** [comment]
> 字体样式的优先级是这样的：
> 
> 本地样式>全局样式
> 
> 而文字大小是这样的：
> 
> 本地样式>自动调整文字大小>全局样式
> 
> 手动修改了字体大小后就启用了本地样式，不再受全局样式和自动调整文字大小的影响。

？？？？？？这不科学
哈哈  本地和全局 全局不就是默认字体设置里的一个么 那个也没变化啊 都是相同字号

**Comment by lhj5426** [comment]
> > 字体样式的优先级是这样的：
> > 本地样式>全局样式
> > 而文字大小是这样的：
> > 本地样式>自动调整文字大小>全局样式
> > 手动修改了字体大小后就启用了本地样式，不再受全局样式和自动调整文字大小的影响。
> 
> ？？？？？？这不科学 哈哈 本地和全局 全局不就是默认字体设置里的一个么 那个也没变化啊 都是相同字号 字体样式应该大于全局 只要修改了样式 字体大小就跟着样式走 无论是手动调整过 比如我字号100 字体样式里是30 我对这个100的实用字体样式之后 就跟着样式走直接变成30号 这样才对吧 哈哈 现在这样设置完自由样式还得手动调整字体大小 而且就是默认的字体大小 再切换一页新页面的时候 查看翻译的字体大小是根据OCR框生生成的 按现在的逻辑就是每一个气泡里的文字套完样式之后都要手动修改字体大小

**Comment by xulihang** [comment]
可以把自动调整文字大小关了，这样全局样式的字体大小就有用了，如果需要调字号，就手动调整下，调整的区域就启用了本地样式

**Comment by lhj5426** [comment]
现在这个逻辑反倒是用起来麻烦  
现在的操作是
1.我想修改对话气泡字体样式颜色先一键设置发现设置不生效
2.再一键去关闭本地样式
3.然后再一键设置气字体样式颜色
4.然后再设置字体大小
有时候呐
是先设置字体大小
然后
1.我想修改对话气泡字体样式颜色先一键设置发现设置不生效
2.再一键去关闭本地样式
3.然后再一键设置气字体样式颜色
本来应该
1就完事的操作  不需要出现2 3 4步骤了

**Comment by lhj5426** [comment]
> 可以把自动调整文字大小关了，这样全局样式的字体大小就有用了，如果需要调字号，就手动调整下，调整的区域就启用了本地样式

这个可以关嘛 再哪里设置呀

**Comment by xulihang** [comment]
项目设置里

**Comment by lhj5426** [comment]
> 可以把自动调整文字大小关了，这样全局样式的字体大小就有用了，如果需要调字号，就手动调整下，调整的区域就启用了本地样式

![image](https://user-images.githubusercontent.com/30548000/170169634-18d3c692-4e86-4304-bb56-226c9a6c360d.png)
是说的这个xuan'x选项嘛  我试试

**Comment by lhj5426** [comment]
> 项目设置里

话说 应该再增加一个是否启用本地样式 还是 麻烦
还有设置完 之后 不要 **取消当前的选中文字**

**Comment by lhj5426** [comment]
老哥你要是长时间的用就会发现真的很不方便 哈哈 希望优化下

**Comment by xulihang** [comment]
> 不要 取消当前的选中文字

修改了下，会保留选择状态了

https://user-images.githubusercontent.com/5462205/170180511-ea477d6f-032e-4371-ad50-8e95212de6ff.mp4

**Comment by lhj5426** [comment]
> > 不要 取消当前的选_中文_字
> 
> 修改了下，会保留选择状态了
> 
>  ice_video_20220525-123507._mp4_

虽然保留了但是绿色框选不见了 也行吧 哈哈  不过最好还是把绿色的框选留下 这个是从视觉角度出发
操作的时候知道当前操作的是哪个 或者哪些 比较直观 
感谢老哥

**Comment by xulihang** [comment]
绿色边框的选中状态加上了，其实就一行代码的事情，之前一直没加上。

https://user-images.githubusercontent.com/5462205/170195046-d94e33d7-8bc7-4cf0-bca9-dc7c15eb566a.mp4

**Comment by lhj5426** [comment]
> 绿色边框的选中状态加上了，其实就一行代码的事情，之前一直没加上。
> 
>  ice_video_20220525-142813._mp4_

6666 就是这样  视觉上直观了 方便操作

**Comment by xulihang** [comment]
上面的修改添加进v1.7.1了
