### ISSUE TITLE
识别气泡的问题与更新建议

### ISSUE THREAD

**Issue by xiaoaotuman2** [xulihang/ImageTrans-docs#213]
您好，今天在使用IMAGETRANS的时候发现自动识别气泡无法使用了，更新了版本也没用，不知道是哪里设置错误了，想问一下如何修复这个问题。

另外有几个关于版本更新的建议希望可以采纳（或者我没找到设置的方法？）
第一：缩放比例每次打开都是100%，可否自定义为每次打开都是某一比例，使用起来更方便些
第二：之后能不能加入批量检查拼写和自动排版的功能
第三：菜单和工具区是否可以加入自定义功能，隐藏不必要的命令且可以自己定义快捷键
第四：字体在有预设后导入PSD时字号等设置都无效，可否修复这一问题
第五：批处理时可否自选OCR的API，目前都是固定的
第六：美漫中一些粗体字斜体字能否标记

**Comment by xulihang** [comment]
> 自定义为每次打开都是某一比例

这个需求类似这个：https://github.com/xulihang/ImageTrans-docs/issues/209 还没开始做

> 之后能不能加入批量检查拼写和自动排版的功能

所有条目的拼写检查可以做。自动排版是要做到什么程度，现在不就能自动排版吗

> 菜单和工具区是否可以加入自定义功能，隐藏不必要的命令且可以自己定义快捷键

自定义功能是什么功能？隐藏目前技术上修改起来比较麻烦。自定义快捷键这个issue提过，目前还没做。https://github.com/xulihang/ImageTrans-docs/issues/184

**Comment by xulihang** [comment]
> 字体在有预设后导入PSD时字号等设置都无效

新版本Photoshop新建文本框的字体设置无效的修正方法见这个issue：https://github.com/xulihang/ImageTrans-docs/issues/57 需要修改下脚本

> 批处理时可否自选OCR的API，目前都是固定的

OCR是可以选的，只是它沿用的主界面的OCR设置，没有在新窗口提供单独的选项设置

> 美漫中一些粗体字斜体字能否标记

具体是什么意思？OCR能检测粗体斜体还是排版的时候添加粗体斜体设置。设置粗体是可以的，在项目设置里启用富文本，然后用`**加粗文本**`这样的方法进行标记。但斜体是不支持的，汉字本身是没有斜体的，软件目前不支持伪斜体

**Comment by lhj5426** [comment]
> 您好，今天在使用IMAGETRANS的时候发现自动识别气泡无法使用了，更新了版本也没用，不知道是哪里设置错误了，想问一下如何修复这个问题。
> 
> 另外有几个关于版本更新的建议希望可以采纳（或者我没找到设置的方法？） 第一：缩放比例每次打开都是100%，可否自定义为每次打开都是某一比例，使用起来更方便些 第二：之后能不能加入批量检查拼写和自动排版的功能 第三：菜单和工具区是否可以加入自定义功能，隐藏不必要的命令且可以自己定义快捷键 第四：字体在有预设后导入PSD时字号等设置都无效，可否修复这一问题 第五：批处理时可否自选OCR的API，目前都是固定的 第六：美漫中一些粗体字斜体字能否标记

目前没有自定义快捷键我是用 鼠标宏来实现的 用的是 Key Manager 1.15
这个软件所有常用功能都录制一个宏然后一个按键映射 极大的提高了效率
在作者没有添加快捷键的前提下 建议用这个折中的方法

**Comment by xiaoaotuman2** [comment]
好的，感谢解答
