### ISSUE TITLE
关于自动更正的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#214]
![image](https://user-images.githubusercontent.com/30548000/170619274-4477f0d0-4003-480d-97fb-b2ca115842ce.png)

https://user-images.githubusercontent.com/30548000/170619546-0ac935d5-880e-4e4d-96d8-0d7661e7b280.mp4

gan'x感谢老哥添加了自动更正的替换功能
但是这个替换功能有个小瑕疵
就是我在 自动 更正里设置了空格 替换为 无（=删除）并用于OCR
然后如视频上那样 自动更正的替换空格功能 只实际在 手动点击 **识别按钮**的的情况下
而 编辑 - **自动识别文字**
批处理-**自动识别所有图片文字**
您看能不能给这2个功能也把自动 更正的替换功能 给安排了 
非常感谢您

**Comment by lhj5426** [comment]
这个自动识别文字应该也算OCR的一种吧？？
我是这么理解的....哈哈哈

**Comment by xulihang** [comment]
> 自动识别文字= 自动框选+OCR

是这样，定位加识别。

目前自动更正或者勾选去除空格是只能作用于单个框的OCR，全图自动识别文字还没加上这个操作。可以勾选去除空格后执行一下合并操作，也能去除空格。

**Comment by lhj5426** [comment]
> > 自动识别文字= 自动框选+OCR
> 
> 是这样，定位加识别。
> 
> 目前自动更正或者勾选去除空格是只能作用于单个框的OCR，全图自动识别文字还没加上这个操作。可以勾选去除空格后执行一下合并操作，也能去除空格。

学会了 哈哈  谢谢

**Comment by xulihang** [comment]
全图自动识别文字的自动更正在2.5.2里也加上了
