### ISSUE TITLE
Add lama inpainting

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#216]
The [lama](https://github.com/saic-mdal/lama) inpainting works great on comics as well. The [lama-cleaner](https://github.com/Sanster/lama-cleaner) project provides a server version which we can use to create a plugin.

Telea (ImageTrans's default):

![image](https://user-images.githubusercontent.com/5462205/170866503-d0769dea-0ace-4c01-8924-e70d50d46848.png)

Lama:

![image](https://user-images.githubusercontent.com/5462205/170866554-e2ab34a8-07a9-4bb6-9432-4d3cab7011a7.png)

**Comment by xulihang** [comment]
Here is the plugin: https://github.com/xulihang/ImageTrans_plugins/tree/master/LamaInpaint

**Comment by xulihang** [comment]
Plugin files:
[lama_inpainting_plugin.zip](https://github.com/xulihang/ImageTrans-docs/files/8793286/lama_inpainting_plugin.zip)

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/170895393-27cdef11-8cc6-473b-bd1c-2010e245b717.png)
新的修复 哈哈是这样用吧？

**Comment by xulihang** [comment]
You can use ExternalMaskGen to use manga translator to accurately generate the mask.

You can edit the mask using the mask editor.

**Comment by CoolGenius-123** [comment]
> You can use ExternalMaskGen to use manga translator to accurately generate the mask.
> 
> You can edit the mask using the mask editor.

Will ExternalMaskGen will be able to remove the text from complex background

**Comment by xulihang** [comment]
Just try it with Japanese manga.
