### ISSUE TITLE
去除文字能优化下吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#219]
端午安康 老哥 昨天做本子的时候
![image](https://user-images.githubusercontent.com/30548000/171971150-4f5c2bcc-b877-4980-98b7-f9915fc825e4.png)
![image](https://user-images.githubusercontent.com/30548000/171971155-e3079ad1-9957-4221-a2d3-e2937d0bc3e3.png)
![image](https://user-images.githubusercontent.com/30548000/171971162-5a387d8d-d2cc-45f0-9df5-c7c8f49e0b6c.png)
![image](https://user-images.githubusercontent.com/30548000/171971165-3223d796-16f3-4fba-8cfa-01be2112e503.png)
![image](https://user-images.githubusercontent.com/30548000/171971169-0d0e1e5c-715d-43f6-86c2-973ab8691a58.png)
![image](https://user-images.githubusercontent.com/30548000/171971174-315aadeb-524c-4471-b58c-ac7b7ebd8eae.png)
这个样子边框都被破坏看了
还有
![image](https://user-images.githubusercontent.com/30548000/171971206-49a6f646-76dc-44e2-9db7-afaf9b23f6ad.png)
我试了各种修复方式 我发现这个 修复方式没有启动成功过
请问这个修复方式怎么用
然后 这个是 隔壁软件的修复 
![image](https://user-images.githubusercontent.com/30548000/171971354-e96cce84-86b4-431d-9125-051d5f1eec61.png)
![image](https://user-images.githubusercontent.com/30548000/171971366-9fdae08c-32cc-4d88-bde6-b83cf380de5a.png)

未来可以优化下这部分么

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/171971663-5a5e07bc-6755-4105-a864-288a4fdfac55.mp4

还有未来有没有可能增加 这个 自由涂抹
还有大小调节 现在在文字修复里只有一个基础的正方形框选 
在掩码里虽然有 线条涂抹但是 不能调节大小

**Comment by xulihang** [comment]
1. 超框字的处理

图像修复算法需要能重绘边框，默认的telea是不行的，可以改用lama inpaint。有个在线demo可以测效果：https://cleanup.pictures/

2. 非超框字的处理

用telea算法的话，文字框的范围不要碰到边框，避免掩膜覆盖到边框。

3. patchmatch修复方法

我是用cygwin编译出inpainting.exe这个可执行文件的，可能在你系统上不能用，不嫌麻烦可以自行编译：https://github.com/xulihang/Inpainting。

4. 更方便的文字掩膜和文字去除

这个需要重构，需要花一定时间。

**Comment by lhj5426** [comment]
上次更新的喇叭修图插件直接就吧这个请求里的问题解决了 感谢
