### ISSUE TITLE
[BUG] PSD generating text with true/false before it.

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#22]
For whatever reason the generated PSDs have nonsense text - see the attached example of the original page and the resulting PSD.
They just have true/false before the actual text.
![PSD bug](https://user-images.githubusercontent.com/21088033/112701372-58b6bf00-8e88-11eb-8edc-2a17a22e8ac2.png)

**Comment by xulihang** [comment]
Please use the JavaScript version in here: <https://github.com/xulihang/ImageTrans_PhotoshopScripts>

The attached AutoIt3 scripts are not updated.

**Comment by lugia19** [comment]
Using the js script does fix the issue with the content of the text, however a new bug happens.
Every text box has a text size of 0, and a paragraph height of 0.01.

I had a look at out.txt and it appears to be correct? Here's an example of a line:
`1868	1610	178	152	Chapter 83.pdf-001.jpg	255,255,255	NotALayer	26.0	1.25	WildWordsRoman	0,0,0	1.0	2.0	false	false	false	false	null	null	null	I’m in the\nmiddle of\nerasing the \nblackboard…\n
`
Yet the corresponding text box has the issue I described above (see screenshot)
![textsizebug](https://user-images.githubusercontent.com/21088033/112706942-89562300-8e9f-11eb-9cef-acda9f25ccb7.png)

**Comment by xulihang** [comment]
Which version of Photoshop are you using? I tested it from Adobe Photoshop CS3 to 2019.

Since the JavaScript is open source, you can fix this by yourself. I'll fix the autoitv3 version in the next version.

**Comment by lugia19** [comment]
I was using version 2019, I fixed it by changing the lines setting the size and leading like this, here's an example for the text size:
`textLayer.textItem.size = pfontsize` -> `textLayer.textItem.size = new UnitValue(pfontsize,"px")`

**Comment by lugia19** [comment]
Well, now I'm running into a different bug where the text's position is wrong.
The values in the script and the actual values in photoshop are different as well, which is weird.

Note: I didn't edit the top-left textbox, it was already correct.
![PositionBug](https://user-images.githubusercontent.com/21088033/112722011-fc42b680-8efe-11eb-8f72-550a68797969.png)

**Comment by lugia19** [comment]
After investigating the issue more throughly, it seems like the offset text is entirely due to the difference between the script's X/Y values and the actual X/Y values in photoshop, since the % script (which is the % difference between the script's X value and the manually corrected X value) is very small (except for one outlier).
![Data](https://user-images.githubusercontent.com/21088033/112722453-8f7ceb80-8f01-11eb-8263-273d44e9109d.png)

**Comment by xulihang** [comment]
Based on my experience, this may be because the image has a high resolution (>72dpi).

**Comment by xulihang** [comment]
But I just tested a 300DPI image, the result is correct.

**Comment by lugia19** [comment]
Weird. What photoshop version are you using? 
Also, this may be a font-related issue again. I'm using WildWords.

**Comment by xulihang** [comment]
I use CS3 on my laptop's hard drive and 2018 on a portable hard drive.

**Comment by xulihang** [comment]
I tested a Chinese image. I can get the exact PSD as ImageTrans's

![image](https://user-images.githubusercontent.com/5462205/112723830-7ac54580-8f4b-11eb-99b7-e0881e680b08.png)

![image](https://user-images.githubusercontent.com/5462205/112723846-857fda80-8f4b-11eb-80c1-ea7a6d143c22.png)

**Comment by lugia19** [comment]
Must be an issue with my photoshop version then, I'll try a different one.

**Comment by lugia19** [comment]
Yeah at this point I'm clueless. Same exact bug using CS3. I've attached the project+images as well (It's in three files due to the 10MB limit) just in case it's an issue with this specific project.
[Anjou1.zip](https://github.com/xulihang/ImageTrans-docs/files/6215904/Anjou1.zip)
[Anjou3.zip](https://github.com/xulihang/ImageTrans-docs/files/6215905/Anjou3.zip)
[Anjou2.zip](https://github.com/xulihang/ImageTrans-docs/files/6215906/Anjou2.zip)


![wtf](https://user-images.githubusercontent.com/21088033/112725650-37e67c00-8f11-11eb-879e-78e42d6f01c0.png)

**Comment by xulihang** [comment]
I tested the images and I got the correct output. Maybe you can try to create a new project from scratch using the latest ImageTrans.

![image](https://user-images.githubusercontent.com/5462205/112739959-644ed680-8fab-11eb-9c60-8289c32e7caf.png)

**Comment by lugia19** [comment]
Must just be the specific project file then. I'll keep this open until I can test it with a new project and the new version.

**Comment by lugia19** [comment]
I ran into the same issue even with a new project, but I managed to fix it by editing the script, here's my version.
[addLayers - fix.zip](https://github.com/xulihang/ImageTrans-docs/files/6344872/addLayers.-.fix.zip)
