### ISSUE TITLE
填入自己的百度文字识别 API密钥后，使用自动识别文字报错

### ISSUE THREAD

**Issue by ualpumpkin** [xulihang/ImageTrans-docs#220]
error: java.lang.RuntimeException: Object should first be initialized (List).
StackTrace: java.lang.RuntimeException: Object should first be initialized (List).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.List.getSize(List.java:117)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2431)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
我申请了百度文字识别和百度机器翻译 
在api设置的地方
我将百度翻译的id和密钥填入了baiduMT 
将百度ocr的API Key和Secret key填入baidu 但是还有一个balloon_detection url我不知道应该填什么就没有填
然后ocr识别时有如上报错
请问我应该怎么解决？

**Comment by xulihang** [comment]
![image](https://user-images.githubusercontent.com/5462205/171992639-807a2b8c-e7dd-43d3-aee5-7ae2f8ac65e3.png)

**Comment by xulihang** [comment]
申请API后还要开通对应的服务，有开通文字识别吗？

**Comment by ualpumpkin** [comment]
是的 百度应用里面开通了文字识别

**Comment by ualpumpkin** [comment]
百度建立应用应该是默认开通文字识别

**Comment by xulihang** [comment]
用ImageTrans.bat启动软件，看下输出日志里有什么提示吧

**Comment by ualpumpkin** [comment]
D:\Imagetrans\ImageTrans>jre\bin\java -jar -Xmx2048M ImageTrans.jar
Device locale: zh
Found 730 strings.
(ArrayList) []
Loading jar finished
Initializing plugin abbyycloudOCR
Loading jar finished
Initializing plugin cloudtranslationMT
Loading jar finished
Initializing plugin clovaOCR
Loading jar finished
Initializing plugin colorfulcloudsMT
Loading jar finished
Initializing plugin deeplfreeMT
Loading jar finished
Initializing plugin deeplMT
Loading jar finished
Initializing plugin easyocrOCR
Loading jar finished
Initializing plugin google_driveOCR
Loading jar finished
Initializing plugin googleMT
Loading jar finished
Initializing plugin googleOCR
Loading jar finished
Initializing plugin niutransMT
Loading jar finished
Initializing plugin opusMT
Loading jar finished
Initializing plugin paddleocrOCR
Loading jar finished
Initializing plugin papagoMT
Loading jar finished
Initializing plugin tencentOCR
Loading jar finished
Initializing plugin webMT
Loading jar finished
Initializing plugin WinRTOCR
plugins have changed!
(ArrayList) [abbyycloudOCR, cloudtranslationMT, clovaOCR, colorfulcloudsMT, deeplfreeMT, deeplMT, easyocrOCR, google_driveOCR, googleMT, googleOCR, niutransMT, opusMT, paddleocrOCR, papagoMT, tencentOCR, webMT, WinRTOCR]
loading ocr plugins
(NullPointerException) java.lang.NullPointerException
(NullPointerException) java.lang.NullPointerException
Error: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "tesseract" (in directory "."): CreateProcess error=2, 系统找不到指定的文件。)
run(Map) Not initialized
run(Map) Not initialized
run(Map) Not initialized
run(Map) Not initialized
run(Map) Not initialized
run(Map) Not initialized
run(Map) Not initialized
winRT
(ArrayList) [abbyycloud, clova, easyocr, google_drive, google, paddleocr, tencent, WinRT]
新建项目
(NullPointerException) java.lang.NullPointerException
(NullPointerException) java.lang.NullPointerException
英语
eng
null
null
英语
eng
图片文件夹
(ArrayList) [00000003.jpg, 00000004.jpg, 00000005.jpg, 00000006.jpg, 00000007.jpg, 00000008.jpg, 00000009.jpg]
null
null
英语
ENG
日语
JAP
1654335102706
0
2592000
1654335103334
1652632136038
{"direction":0,"words_result":[{"probability":{"average":0.991019249,"min":0.9536740184,"variance":0.0001672260696},"words":"あ、アイスーつください！"},{"probability":{"average":0.9644048214,"min":0.7941651344,"variance":0.004386561923},"words":"こ、こんにちは！"}],"words_result_num":2,"log_id":1533018654226462686}
(ArrayList) [あ、アイスーつください!, こ、こんにちは!]
あ、アイスーつください!
こ、こんにちは!
自动识别文字
1654335108785
1652632136038
2592000
1654335108837
1652632141541
{"error_code":18,"error_msg":"Open api qps request limit reached"}
baidu
(RuntimeException) java.lang.RuntimeException: Object should first be initialized (List).
(List) Not initialized
这样的

**Comment by xulihang** [comment]
应该是请求太频繁了，超过了限制，OCR的间隔需要设大一点

**Comment by ualpumpkin** [comment]
好的 谢谢 我再试一下
对了 再请问一下 感觉自己申请的OCR识别精度还是差了一些 有什么改进的方法吗？

**Comment by xulihang** [comment]
我看了下含定位信息的请求限制（QPS）是每秒2次

**Comment by xulihang** [comment]
要识别什么文字？

baidu_accurate已经是高精确版了，如果是特别的字体，baidu_network会好一点

**Comment by ualpumpkin** [comment]
用来识别漫画 我申请的百度api是普通版的 那我再申请一个高精度版的试试

**Comment by longij** [comment]
> 用来识别漫画 我申请的百度api是普通版的 那我再申请一个高精度版的试试

请问申请api需要付费吗

**Comment by xulihang** [comment]
> 请问申请api需要付费吗
 申请不用，有免费额度，超过额度需要付费使用
