### ISSUE TITLE
怎么调整字距啊，只找到了行距

### ISSUE THREAD

**Issue by NinjaAquaKin** [xulihang/ImageTrans-docs#224]

**Comment by xulihang** [comment]
这个还没提供设置接口，目前默认值是5像素

**Comment by NinjaAquaKin** [comment]
再顺便问一下偶尔会有那种对话框里多了块污渍，就一小块灰黑的，什么原因导致的啊

**Comment by xulihang** [comment]
发张图在新的issue吧

**Comment by yahoozhu** [comment]
![Snipaste_2022-09-10_19-15-56](https://user-images.githubusercontent.com/24186777/189507569-80d547fb-33cc-476d-b610-abd927cdfee7.jpg)
![Snipaste_2022-09-10_19-16-32](https://user-images.githubusercontent.com/24186777/189507573-275f6245-10de-45e8-ac31-463a2104cd96.jpg)

不能调字距真的难受，CG大图对话框太小了，字看着就小，想调字号但是字数多了再调就到框外了蛮丑的

**Comment by xulihang** [comment]
竖排引擎我自己实现的，我加个字距（kerning）调整吧。之前不加主要是横排用的自带引擎，字距不能调

**Comment by xulihang** [comment]
![image](https://user-images.githubusercontent.com/5462205/189509329-a4e3cc58-c0cf-4b90-b98b-913582b278ee.png)

字距设置添加在字体样式里了

**Comment by xulihang** [comment]
添加在v1.7.8了
