### ISSUE TITLE
污渍问题

### ISSUE THREAD

**Issue by NinjaAquaKin** [xulihang/ImageTrans-docs#225]
https://img.chkaja.com/00c327bf2d406bfe.png
们 下面

https://img.chkaja.com/47221a58fe69562c.png
下  下面那一块

https://img.chkaja.com/f153c173473c964e.png
好  下面

 随便找了三处

**Comment by xulihang** [comment]
原图是什么样的，可能是文字比较淡，和背景的区分不够。

可以试试这两个操作：

1. 在项目设置里把掩膜膨胀大小设大一点

![image](https://user-images.githubusercontent.com/5462205/174997764-137b3bd8-98a7-45d1-b883-b9e68e79c541.png)


2. 在项目设置里把二值化阈值调为200
![image](https://user-images.githubusercontent.com/5462205/174997566-c9632523-99f8-4883-8f03-8ecca21c498d.png)

**Comment by NinjaAquaKin** [comment]
好的我试试
谢谢解答
