### ISSUE TITLE
截图快捷键

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#237]
呃 半年之期已到 已经重新在面包多续费了 感谢老哥让我实现了漫画自由看
现在有个问题
就是 
![image](https://user-images.githubusercontent.com/30548000/178144312-65348245-1061-4a55-b5ab-e8b09540096b.png)
有的时候比较懒 还有有的图就几张图 几个气泡没必要大动干戈下载下来看
直接屏幕读取器就行了 
![image](https://user-images.githubusercontent.com/30548000/178144354-1bca5301-1f83-4ce5-acff-fbb47986b79a.png)
但是 这个没有快捷键啊 能不能给屏幕读取器这个截图的快捷键安排上  
![image](https://user-images.githubusercontent.com/30548000/178144394-8cfa23ba-fe69-4b5e-840d-7e0214b3b6ab.png)
虽然吧我 有其他的OCR工具 但是有个额度问题 离线OCR的话就随便了  
manga-ocr 和 微软自身的系统OCR 完全足够应对的 实在不行我才用在线oCR 毕竟一一个月只有1000次 哈哈
希望老哥后续的版本可以把这个 屏幕读取器的 快捷键安排上

**Comment by xulihang** [comment]
可以勾选监听剪贴板，然后使用Windows自带的Win+SHIFT+S快捷键截屏。软件会自动检测剪贴板内新增的图像


参见之前的issue：https://github.com/xulihang/ImageTrans-docs/issues/145

**Comment by lhj5426** [comment]
> 可以勾选监听剪贴板，然后使用Windows自带的WIN+SHIFT+S快捷键截屏。软件会自动检测剪贴板内新增的图像
> 
> 参见之前的issue：#145

占用剪切板很麻烦的 这个我试过了 才说的 还是独立快捷键方便 比如我上1分钟在看图 下一分钟在另外一个显示器复制了一段文本 他也咔一下 不太方便  因为我监听的不只是剪切板还有软件 来调用翻译

**Comment by xulihang** [comment]
系统级别的快捷键要用hooks，要研究一下

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/178148241-c7e48ba8-4d62-4170-9e68-2a8e066f055a.png)

**Comment by lhj5426** [comment]
> 系统级别的快捷键要用hooks，要研究一下

哈哈抽空研究一下吧 开发者老哥

**Comment by xulihang** [comment]
你这个第三方剪贴板软件能不能检测剪贴板内容是图片还是文本吗？

还有目前所有OCR操作都是写剪贴板的，不也触发了你设的划词翻译了吗

**Comment by lhj5426** [comment]
> 你这个第三方剪贴板软件能不能检测剪贴板内容是图片还是文本吗？
> 
> 还有目前所有OCR操作都是写剪贴板的，不也触发了你设的划词翻译了吗

要有那么智能就真谢天谢地了没有啊  他只会识别什么呢 从什么软件传递过来的文字
或者剪切板里保护了什么文字  链接 可以用正则 但是不支持识别类型 文字还是图图片 还是文件 
它是只要你通过设置的软件产生了剪切板的变动 就会自动执行后续操作

**Comment by lhj5426** [comment]
> 你这个第三方剪贴板软件能不能检测剪贴板内容是图片还是文本吗？
> 
> 还有目前所有OCR操作都是写剪贴板的，不也触发了你设的划词翻译了吗

我设置是只有这个进程这个窗口才会触发这个操作 要是随便oCR都触发那多乱啊 屏幕上一直蹦窗口玩
还有回到上一个关于OCR疯狂写剪切板的那个议题上 我嫌烦OCR都关了只有最后完成的时候用软件自带的声音提醒完成OCR全部操作

**Comment by xulihang** [comment]
全局快捷键加在v2.8.2里了。默认关闭，需要在偏好设置里开启

**Comment by lhj5426** [comment]
噢噢噢噢噢~~~终于来来啦 感谢 太感谢了 ！！！！！！！！！！！！！！！！！！ 
零星的  变体集图 就可以不用下载了！！！！！！！！！
