### ISSUE TITLE
Can't read arabic language

### ISSUE THREAD

**Issue by beba4434** [xulihang/ImageTrans-docs#238]
Hello
After I installed the app, it works perfectly except the Arabic language.
The app can't read the Arabic text correct. Instead it shows a weird text.
![image](https://user-images.githubusercontent.com/99797214/178291339-d756fc07-42be-4205-86fd-1740067e5c79.png)

**Comment by xulihang** [comment]
I don't have this problem on my Windows 10 device.

![image](https://user-images.githubusercontent.com/5462205/178416152-f8c3ba28-252e-47fd-a3b4-4cd6fac0254d.png)

You can set up the font in the project settings:

![image](https://user-images.githubusercontent.com/5462205/178416302-237aee76-21ce-4a75-abcf-ecdf4df09060.png)

Besides, Arabic is right-aligned. If you need such a style, I can add a setting for this.
