### ISSUE TITLE
最近时不时弹错

### ISSUE THREAD

**Issue by googril** [xulihang/ImageTrans-docs#239]
error: java.lang.ArrayIndexOutOfBoundsException
StackTrace: java.lang.ArrayIndexOutOfBoundsException
![image](https://user-images.githubusercontent.com/25705390/179151478-4034a388-33a1-4230-859f-bab79e89e12f.png)，主要在识别出问题，用网页插件，设置百度识别不了，换了ocrspace就能正常识别，又可以了，不时抽风，要在百度云重新设置
![image](https://user-images.githubusercontent.com/25705390/179153530-69787435-dd0e-4f52-aa45-8a8e16fe0d94.png)

**Comment by xulihang** [comment]
具体执行什么操作时出现的？

**Comment by xulihang** [comment]
这个问题我估计是百度翻译的问题，可以换个tencent腾讯翻译看看。

翻译日漫的话可以用百度网盘里提供的气泡检测模型和manga-ocr，参见这篇博客：
https://www.basiccat.org/zh/best-practice-manga-ocr-and-translation/
