### ISSUE TITLE
百度OCR求助

### ISSUE THREAD

**Issue by awasky123456** [xulihang/ImageTrans-docs#240]
你好，大佬。我昨天刚买了你的软件，不知道为什么百度OCR老是报错，3个都是。你能帮我一下吗？
![image](https://user-images.githubusercontent.com/109777026/180352930-bf6029da-d62c-4a02-9d30-b8bc06b6a0b0.png)

**Comment by xulihang** [comment]
能发张原图过来吗，我测试一下

**Comment by xulihang** [comment]
我看了下，是每日使用额度超标了。可以申请一个自己的百度OCR API密钥。

**Comment by awasky123456** [comment]
好的，谢谢，请问一下每日使用额度是多少？

**Comment by xulihang** [comment]
带位置的和精确版每天500次，不带位置的50000次，所有用户共享。
