### ISSUE TITLE
那个lama inpainting插件安装了没有效果

### ISSUE THREAD

**Issue by Liboaea** [xulihang/ImageTrans-docs#243]
![Snipaste_2022-07-29_20-20-31](https://user-images.githubusercontent.com/87652382/181757801-19ce4dd7-4622-4cc2-8faa-d7ceb77b0510.png)
只显示"POST /inpaint HTTP/1.1" 400 -就没了

**Comment by xulihang** [comment]
我是用的0.12.0版。

可以装个0.12.0的再试试。

```
pip uninstall lama-cleaner
pip install lama-cleaner==0.12.0

```

**Comment by Liboaea** [comment]
可以，用0.12.0就正常了
