### ISSUE TITLE
Space Between Lines

### ISSUE THREAD

**Issue by LostDevM** [xulihang/ImageTrans-docs#244]
I wonder if there is any way to edit the space between lines.
I'm looking for something like css line-height property but couldn't find that property in the app

**Comment by xulihang** [comment]
There is line space setting for the text flow: https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextFlow.html#setLineSpacing-double- But I haven't exposed it in ImageTrans settings. If you need it, I can add this in a new version.

**Comment by LostDevM** [comment]
That would be great as some manga series would benefit a lot from it

**Comment by xulihang** [comment]
All right, I have enabled the line spacing setting for horizontal text.

https://user-images.githubusercontent.com/5462205/184475038-491df89f-15b1-44ac-8da7-cb005956bb71.mp4

**Comment by xulihang** [comment]
Added in v1.7.5.
