### ISSUE TITLE
关于软件启动时候默认OCR的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#245]
是这个样子的
![image](https://user-images.githubusercontent.com/30548000/185032215-f42ae579-8896-4936-826f-bed3c09ced50.png)
软件打开默认ocr是这个样子滴
而我实际上需要用的是
![image](https://user-images.githubusercontent.com/30548000/185032281-f18f83d9-62e3-4b1f-ba8e-86cb355c9536.png)
这个ocr 
想问一下
如何把这个OCR设置成软件启动的默认OCR
然后吧 我开始自作聪明的以为是 根据文件名排序的
我把这个ImageTrans/plugins 
mangaOCRPlugin.jar
mangaOCRPlugin.xml
改名成00然后发现 不仅没有排序成功
插件也从 软件的选项里消失了
改名回去软件又重新出现了
所以想问下 这个默认OCR是基于什么排序的 可以不可以自定义排序的 把我常用的OCR设置第一顺位

**Comment by lhj5426** [comment]
哎呀 好几次忘记设置OCR白白浪费了不少时间

**Comment by xulihang** [comment]
好的，我加个记忆功能吧，记住上次项目使用的OCR和语言

**Comment by lhj5426** [comment]
> 好的，我加个记忆功能吧，记住上次项目使用的OCR和语言

好耶  好耶   那就很棒了 本来现在就是按照老哥之前说的做一个模版每次复制那个模版
等老哥更新那个功能之后 再重新做一个新模版

**Comment by xulihang** [comment]
更新在1.7.6了

**Comment by lhj5426** [comment]
> 更新在1.7.6了

漂亮 这就去更新下模版以后再也不会因为 忘记选择OCR引擎而且傻傻的浪费时间了哈哈 辛苦！
