### ISSUE TITLE
文字描边 白边检测

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#247]
![image](https://user-images.githubusercontent.com/30548000/185864093-138137b9-3c71-479b-86eb-cf4a1e795ee1.png)

![image](https://user-images.githubusercontent.com/30548000/185864265-3b9643cc-f329-4bf2-8f7f-4494974ac966.png)
![02](https://user-images.githubusercontent.com/30548000/185865631-40b9c192-c17c-4eb2-ba6b-b681dd428b5d.png)
这种全彩  带字体白边的 
全都会把白边漏掉 希望后续的版本可以优化下 放一张图 以供 测试 
![image](https://user-images.githubusercontent.com/30548000/185866365-73600ac1-5d7d-4518-8c44-3512f7adc632.png)

不手动调整的话 膨胀开到100也不会覆盖 哈哈

**Comment by xulihang** [comment]
膨胀大小调大是有效果的。没效果可能是你已经保存了mask掩膜图像，它就不会重新生成了。

这种带描边，背景透明的文字，目前的默认方法还需要改进。涉及算法，需要一些时间实验。

之前的issue其实也提到过用manga-image-translator和sickzil-machine的掩膜生成功能，就是这两个处理起来比较慢

**Comment by lhj5426** [comment]
> 膨胀大小调大是有效果的。没效果可能是你已经保存了mask掩膜图像，它就不会重新生成了。
> 
> 这种带描边，背景透明的文字，目前的默认方法还需要改进。涉及算法，需要一些时间实验。
> 
> 之前的issue其实也提到过用manga-image-translator和sickzil-machine的掩膜生成功能，就是这两个处理起来比较慢

嗯  
我现在用 PhotoStudioIPS11 的修这种气泡 然后用
原名.原后缀.-original.jpg
直接改名放到 文件夹里 直接就替换成修的图了
不通过项目-管理无文字源图和纯文字图  
这也是个临时解决办法  因为现在怎么都跑不出去要手动涂抹修正 就换了个软件 哈哈
多个软件联动  一个修 一个嵌

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/185964525-eff58414-6dbc-45ad-b3ae-f4ca367f9d18.mp4

https://user-images.githubusercontent.com/30548000/185964551-2b78cc5d-ad29-4f66-a49b-7f247a7dc8c5.mp4

这样还快点

**Comment by lhj5426** [comment]
不过这个真的是很随机
![image](https://user-images.githubusercontent.com/30548000/185977455-b9352dea-eaad-4a1e-8ae6-594a56dac1b3.png)
这就没问题 哈哈  然后楼上发的那个图的的那种就是在气泡里 白边也全漏掉了
