### ISSUE TITLE
点击删除图片报错

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#249]
![image](https://user-images.githubusercontent.com/26926749/185933941-0d47e081-f706-42cb-b815-91c883c573c7.png)

![image](https://user-images.githubusercontent.com/26926749/185933681-75fbcce7-0cf7-45c3-8a54-50717fc02b12.png)

**Comment by xulihang** [comment]
因为没有图片了，所以报错。看下下方的列表。
![image](https://user-images.githubusercontent.com/5462205/185934482-4e98e8c4-2c98-4f56-98e8-5b1d4fe744dd.png)

最后一张图片从列表删除后，图片还会显示着，但其实已经删掉了。
