### ISSUE TITLE
离线版气泡说放置不对

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#250]
![image](https://user-images.githubusercontent.com/26926749/185935457-2d436e58-b882-42de-a70a-afc25459c5d6.png)
![image](https://user-images.githubusercontent.com/26926749/185935512-a636c783-5712-4807-88f5-45dc8b419c13.png)
所需文件夹已经放在了ImageTrans的里面

**Comment by xulihang** [comment]
从百度网盘下的吗？

![image](https://user-images.githubusercontent.com/5462205/185936447-f1ae5f64-eedf-4ca4-af3f-2486f53d53b0.png)


不要有文件夹，直接把model.weights这些文件放在根目录。

**Comment by xulihang** [comment]
文档里的说明：https://imagetrans.readthedocs.io/zh_CN/latest/settings.html#balloon-detection

**Comment by xulihang** [comment]
路径不要有中文
