### ISSUE TITLE
百度ocr的参数填哪几个啊

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#251]
![image](https://user-images.githubusercontent.com/26926749/186683000-90d92dbb-0d49-4216-8c7f-6094a7b27b2e.png)
![image](https://user-images.githubusercontent.com/26926749/186683058-9844ff62-45a8-450e-b94a-48d48f023b54.png)
软件里只有两个参数

**Comment by xulihang** [comment]
截图是百度翻译API（baiduMT）吧，文字识别需要的参数是apikey和secretkey

**Comment by hyominli** [comment]
> 

![image](https://user-images.githubusercontent.com/26926749/187742067-578de453-cae2-4a29-9bc7-0055eaa6d281.png)
但是这里写的是appid

**Comment by hyominli** [comment]
> 截图是百度翻译API（baiduMT）吧，文字识别需要的参数是apikey和secretkey

![image](https://user-images.githubusercontent.com/26926749/187742333-1a1ec77c-93ff-4f1c-827a-3de219b1f5b1.png)
但是这里写的是appid啊

**Comment by xulihang** [comment]
用的什么版本？旧版是这样的，后来更新了

**Comment by hyominli** [comment]
> 用的什么版本？旧版是这样的，后来更新了

![image](https://user-images.githubusercontent.com/26926749/187815186-616afae2-673b-4f0b-9d19-7da0ce4cf5ab.png)
这个版本，在哪里更新呀

**Comment by hyominli** [comment]
> 用的什么版本？旧版是这样的，后来更新了

![image](https://user-images.githubusercontent.com/26926749/187816540-6fa56ada-532d-4023-bb85-cfe15a836de4.png)
更新了还是appid

**Comment by xulihang** [comment]
新版应该是这样的

![image](https://user-images.githubusercontent.com/5462205/187817513-4e184069-dc1d-400c-8089-79ab44ddd86c.png)

百度网盘里下新版，1.7.6是比较新的了
