### ISSUE TITLE
I buy ImageTrans personal use

### ISSUE THREAD

**Issue by keba12** [xulihang/ImageTrans-docs#252]
Hello i buy ImageTrans personal use but when i come to open the program imageTrans
exe they did not work and it show me that " this program required java runtime environment 1.8
please help me how to solve this problem.

**Comment by xulihang** [comment]
You are using the cross-platform version. You need to install Java and OpenCV according to the docs: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html

Or you can simply use the full version on onedrive.
