### ISSUE TITLE
from where can i download the full version? 

### ISSUE THREAD

**Issue by keba12** [xulihang/ImageTrans-docs#254]
Hello from where can i download the full version?

**Comment by xulihang** [comment]
Check the emails sent to you or the readme file on FastSpring.

**Comment by keba12** [comment]
thanks the program is open but the program does not open png photo how can i run photo on it?

**Comment by xulihang** [comment]
Check out the docs: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#id10

**Comment by keba12** [comment]
yep thanks but there is still a proplem with getting text area confidence proplrm name is error report how can i fux it?

**Comment by keba12** [comment]
yup the proplem is solved but when i click on get text area confidence it does not work you can see the proplem in the photo.

**Comment by keba12** [comment]
![Uploading IMG_20220826_211353.jpg…]()

**Comment by xulihang** [comment]
I can't see the image. Try to put it in a simple path like D:\ImageTran

**Comment by keba12** [comment]
![Uploading IMG_20220826_211353.jpg…]()

**Comment by keba12** [comment]
https://ibb.co/n66k4mF

**Comment by keba12** [comment]
this is the link of the photo

**Comment by xulihang** [comment]
Put it in a path without special characters like Chinese, Arabia and French.

**Comment by keba12** [comment]
I don't understand. Can you explain to me more?

**Comment by keba12** [comment]
the proplem when i click on "Text area operations." it does not work and show me error report

**Comment by keba12** [comment]
Also when i click " one-click tranzleation" it show that there an error report.

**Comment by xulihang** [comment]
The reason of the getting text area confidence error is that the program's path has special characters.

If you encounter other problems, you can copy and paste the error here.

**Comment by keba12** [comment]
how can i solve the problem?

**Comment by xulihang** [comment]
What is your current path of ImageTrans? Move it to a simple path like `D:\ImageTrans`.

**Comment by keba12** [comment]
my manga in English and i want to tranzleat it to Arabic is the proplem because of the language?

**Comment by xulihang** [comment]
Not related to the manga's language.

**Comment by keba12** [comment]
my image Trans is in c folder 3 inside folder 3

**Comment by keba12** [comment]
oh thanks very much the proplem is solved.
