### ISSUE TITLE
It's been a while since I used it, so the ocr of the manga-image-translator-main is not working.

### ISSUE THREAD

**Issue by awwdx** [xulihang/ImageTrans-docs#255]
It's been a while since I used it, so the ocr of the manga-image-translator-main is not working.
The ability to get the position of a letter moves well, but does not ocr the letter.
![캡처](https://user-images.githubusercontent.com/96706748/186909893-b7e3aad7-f305-4252-a10c-024f3e798334.JPG)

**Comment by xulihang** [comment]
You have to select the detector+recognizer combination.

**Comment by awwdx** [comment]
thx bro
