### ISSUE TITLE
字体样式的小瑕疵

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#256]
https://user-images.githubusercontent.com/30548000/187164449-cdf69330-abf9-49e4-a68f-985afae709f1.mp4

 1字体样式在选择选中的样式上上进行任何调整
点击确定确定不会被保留必须 新建一个？！！
2字体大小调整  不能用退格键删除 不能用方向键上下调整（所有软件潜移默化的基本默认操作方向键上下调整数值） 不能手动输入大小（那里不是个输入框么？？另备注 软件90% 带有可调整数字的输入框都是假的不能手动输入 另外举个例子 工作流里的 翻译 时间设置）
3左侧字体样式栏选中的样式上 经常弹不出 上移 下移动 总是会弹出 从项目打开   （显示上移 下移动 删除 是概率问题？）
4左侧字体样式栏选中一个样式不能快速排序（鼠标拖动排序或者选中的时候按PAGEUP PAGEDN上下移动）
5左侧字体样式栏不能用del 快速删除 
需要打磨一下

**Comment by xulihang** [comment]
必须新建这个问题软件一开始就存在，我有时也忘记添加，一直懒得改。我看看怎么改下吧

右键菜单是这样的，你点在文字上弹出上移下移，点在空白处是从项目导入

**Comment by lhj5426** [comment]
> 必须新建这个问题软件一开始就存在，我有时也忘记添加，一直懒得改。我看看怎么改下吧
> 
> 右键菜单是这样的，你点在文字上弹出上移下移，点在空白处是从项目导入

不 选中样式 右键是经常是弹出从项目导入 概率性才会弹出上下移动 而不是正常理想中的 空白地方才弹出 从样式导入
我演示的这个项目创建的样式还是少的 有的项目 7 8 个样式 新进一个 想做默认移动到最顶上 麻烦死 很难受   

这次主要的矛盾点在于不方便设置默认  如果能方便设置默认 除了大一点  再原有样式上修改不保存
这个问题之外 其他的都是可以忍受的 

或者 把右键弹出菜单修好 然后增加一个 设置为默认样式 这样 就是再最后创建新项目也可以直接设置为默认而不需要一层一层移动

**Comment by xulihang** [comment]
![image](https://user-images.githubusercontent.com/5462205/189509367-635b94d9-72ce-4e3f-a2f6-bcd6561b1b52.png)

添加了一个修改选中样式的按钮
右键菜单添加一个将样式移至顶端的项目

**Comment by xulihang** [comment]
上述修改添加在v1.7.8了
