### ISSUE TITLE
希望图片比例及字体样式可以增加多个固定勾选框

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#257]
图片大小比例和字体样式换的比较频繁，希望主页面增加多个勾选框直接勾选切换设置好的参数

**Comment by lhj5426** [comment]
跟我提的这个有点类似
https://github.com/xulihang/ImageTrans-docs/issues/209
我希望每次自动记住 哈哈

**Comment by xulihang** [comment]
可以先设置几个全局字体样式，指定给所需区域。

勾选框这个具体怎么做没理解。

**Comment by yahoozhu** [comment]
> 可以先设置几个全局字体样式，指定给所需区域。
> 
> 勾选框这个具体怎么做没理解。

因为需要频繁切换到100%的原图处理局部细节，以及切到30%左右的样子看全局效果，所以希望可以有多个图片比例快速切换这样，并且可以记住这个勾选，而不是每次打开都是100%大图

**Comment by lhj5426** [comment]
> > 可以先设置几个全局字体样式，指定给所需区域。
> > 勾选框这个具体怎么做没理解。
> 
> 因为需要频繁切换到100%的原图处理局部细节，以及切到30%左右的样子看全局效果，所以希望可以有多个图片比例快速切换这样，并且可以记住这个勾选，而不是每次打开都是100%大图

临时的解决办法录制鼠标宏
https://github.com/xulihang/ImageTrans-docs/issues/215

**Comment by lhj5426** [comment]
> > 可以先设置几个全局字体样式，指定给所需区域。
> > 勾选框这个具体怎么做没理解。
> 
> 因为需要频繁切换到100%的原图处理局部细节，以及切到30%左右的样子看全局效果，所以希望可以有多个图片比例快速切换这样，并且可以记住这个勾选，而不是每次打开都是100%大图


https://user-images.githubusercontent.com/30548000/187629773-12bd8330-6a09-426d-8643-d2a25593e447.mp4

在开发者没有 添加上之前 键盘鼠标宏是最方便的解决方法

**Comment by xulihang** [comment]
只是显示比例的话，可以像福昕阅读器这样，搞一个spinner加进度条
![image](https://user-images.githubusercontent.com/5462205/188276973-262e0083-f16a-4986-ba56-981479130431.png)
