### ISSUE TITLE
自定义字体样式不能应用

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#259]
![Snipaste_2022-08-31_07-37-29](https://user-images.githubusercontent.com/24186777/187562042-a45df3ce-638c-401c-a4b1-58c406990cf5.jpg)

如图，有效，但是只有一半有效，另外两句怎么调都没变化，重启还是怎么样都没用

**Comment by xulihang** [comment]
点右侧字体设置，看看有没有本地样式，它的优先级高于全局样式

**Comment by yahoozhu** [comment]
雀实

**Comment by yahoozhu** [comment]
> 点右侧字体设置，看看有没有本地样式，它的优先级高于全局样式，

还是有点问题，选中对话框之后，只要先在左上栏里更改了字体大小，就自动勾选了本地样式，如果选中对话框后先选择了指定样式，则不会勾选本地样式，但是这个指定样式的字体大小好像并不能赋值过来，还是要去手动改
