### ISSUE TITLE
谷歌drive识别报这个错

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#260]
java.net.SocketException: Software caused connection abort: recv failed

Server Error

**Comment by xulihang** [comment]
我服务器的7天token已经过期了，需要我手动更新下

**Comment by hyominli** [comment]
> 我服务器的7天token已经过期了，需要我手动更新下

需要

**Comment by xulihang** [comment]
目前因为我的Google Cloud应用没有发布，被谷歌限制7天有效期。搞起来比较麻烦的。你有自己的Google Cloud账号的话也可以自己配置：https://github.com/xulihang/ImageTrans-docs/issues/91#issuecomment-950313389

**Comment by xulihang** [comment]
我更新了下，目前到下周日是可以用的
