### ISSUE TITLE
准星！？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#261]
https://user-images.githubusercontent.com/30548000/188074611-9f97899b-c5f0-4985-a716-4e89c62cf134.mp4

接触 的软件多了 我发现老哥 咱的涂抹没有准星啊
想精细化操作因为没有准星 我找了个 带1像素 准星的 放大镜 来当 准星 辅助进行精细化操作
然后发现 1是没有准星 2是没有准星的准星还有偏移 
![IKS~1~E%M(C2X9PSZ9G(~PX](https://user-images.githubusercontent.com/30548000/188074828-f6d1ba6b-ecd0-4fb4-85ac-4f17675dfc12.jpg)
我不太 会表达这个 您能理解吗

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/188075682-4a652691-6cc2-46c4-845f-9cb7eb67aa73.png)

其他工具的涂抹都有个准星 这个准星好像是标配？
![image](https://user-images.githubusercontent.com/30548000/188075860-94cd309c-df17-4eeb-89e0-e02f1ed98333.png)
![image](https://user-images.githubusercontent.com/30548000/188075915-14c35dcb-f36f-4e3d-8e6a-d2809f247659.png)
![image](https://user-images.githubusercontent.com/30548000/188076025-4fed059c-89f6-460a-b212-5ca405b1f4d4.png)
希望后续的开发中咱们也能来 个准星  这个应该是叫准星吧？？

**Comment by lhj5426** [comment]
而且还会偏移
![image](https://user-images.githubusercontent.com/30548000/188076466-cc4a056a-1438-4100-91c7-96687ee64932.png)

**Comment by lhj5426** [comment]
事情是这样发生的
因为我主攻的是全彩漫画
![image](https://user-images.githubusercontent.com/30548000/188077946-9d3ef424-1b45-43b0-86ee-a6bef1437da9.png)
这种默认出框的情况很多 会导致气泡很别扭 就想修正一下
修正的时候就发现 
![image](https://user-images.githubusercontent.com/30548000/188078337-13962081-50f3-4407-ae89-6e4f072eb716.png)
就用 最小的 涂抹 想修正这种气泡出来的或者贴边 的犄角旮旯
就要吗 多一块要么少一块 精细化操作很男 然后 我发现了是缺少准星造成的 在网上找了个带有1个像素点的准星放大镜 然后配合 最小尺寸的涂抹 才完成了这种精细化操作 因为 现在的没有准星的准星 太大了 而且没准星 不知道 起笔的位置

**Comment by xulihang** [comment]
我用的开发平台的这个canvas画板不是很好定制，也没有按圆形清除画布的API，画笔目前是不能太精细地操作

**Comment by xulihang** [comment]
不过十字光标的准星和避免偏移准星，实现应该不难

**Comment by lhj5426** [comment]
不偏移 也可以 配合放大镜 我一样可以的
一点点打磨 总会越来月好用的 最近QQ群里也有被安利到的
也有开始自己做漫画的了

**Comment by xulihang** [comment]
我把自定义光标改成矩形了，添加掩膜还是去除掩膜都用矩形，这样没有偏移问题。在macOS上光标大小就是实际操作大小，但Windows的光标大小可能是固定的，暂时不能解决。

https://user-images.githubusercontent.com/5462205/189486197-cdb6f68f-13bb-406b-b440-aa6f2a2c05ce.mp4

**Comment by xulihang** [comment]
上述修改添加在v1.7.8了

**Comment by lhj5426** [comment]
> 我把自定义光标改成矩形了，添加掩膜还是去除掩膜都用矩形，这样没有偏移问题。在macOS上光标大小就是实际操作大小，但Windows的光标大小可能是固定的，暂时不能解决。
> 
>  default._mp4_

哈哈所以说现在这个滑块调整大小在win 上实际上是无效的了啦

**Comment by xulihang** [comment]
效果是有的，改变实际操作大小，但光标显示的大小没变。

**Comment by lhj5426** [comment]
> 效果是有的，改变实际操作大小，但光标显示的大小没变。

![image](https://user-images.githubusercontent.com/30548000/189514228-469bedc2-a01a-43c5-9723-1aa3b9c2bb03.png)
哈哈这样做的话 更需要 "准星了" 大小不变 没有准星 更难对准了 一点点来吧 一步一个 脚印
辛苦老哥大中秋的还在更新 感谢

**Comment by xulihang** [comment]
把滑条调到中间位置，这样实际操作大小和显示大小一致，操作起来会方便一点。因为显示的区域和实际操作区域一直，我不考虑添加准星了。光标图像大小这个问题我在开发论坛有发帖，应该会在后续版本改进：https://www.b4x.com/android/forum/threads/imagecursors-display-size-does-not-change-on-windows.142837/#post-905143

**Comment by lhj5426** [comment]
> 把滑条调到中间位置，这样实际操作大小和显示大小一致，操作起来会方便一点。因为显示的区域和实际操作区域一致，我不考虑添加准星了。光标图像大小这个问题我在开发论坛有发帖，应该会在后续版本改进：https://www.b4x.com/android/forum/threads/imagecursors-display-size-does-not-change-on-windows.142837/#post-905143


https://user-images.githubusercontent.com/30548000/189620965-c775442a-7c0a-4224-9dff-7310800b62ab.mp4


那 现在既然大小没关系 默认能给它固定到 光标 方块大小么
现在想要设置成默认光标方块大小需要好些操作
而且以前1.78版之前因为滑块是可以调节大小的 所以只需要设置点击就可以 一个按钮点击一次是启动涂抹比再点一次是关闭涂抹笔
现在因为增加了 一个 设置滑块大小的键盘操作
我需要再额外射找一个按钮来关闭涂抹笔 
老哥现在可以给它 这个方块默认激活就是方块自身大小么 这样  还是可以只用一个按钮来激活和关闭涂抹笔

**Comment by xulihang** [comment]
好的，我把默认值设成32了。

**Comment by xulihang** [comment]
> 默认值设成32
> 消除模式的颜色我改成绿色吧

这两条加在v1.7.10里了

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/190888527-e3bbda68-f517-49df-bd4c-f0ab7d96effc.png)
![image](https://user-images.githubusercontent.com/30548000/190888533-c4dcf308-4c7c-4d52-a63c-d09e51c481b0.png)
比心 爱你噢  这非常的直观了哈哈
