### ISSUE TITLE
Manga-OCR not working

### ISSUE THREAD

**Issue by ahmedsaady28** [xulihang/ImageTrans-docs#263]
i downloaded the manga-ocr package for windows and started the server and added the plugin but there are 2 problems now :

1 - Manga-OCR "run.bat" won't run offline

2 - even in online mode with the server up whenever i try using manga-ocr as the OCR  and choose "detect text area and recognize text" it just does nothing with the correct language chosen too.

**Comment by xulihang** [comment]
1. You have to keep the windows open. It works offline on your local machine as a server.
2. It only recognizes text. So "detect text area and recognize text" does not work. You have to detect the text areas first.

**Comment by xulihang** [comment]
You can use this balloon detection model along with manga-ocr: https://github.com/xulihang/ImageTrans-docs/issues/135
