### ISSUE TITLE
can i tranzleat manga offline? 

### ISSUE THREAD

**Issue by keba12** [xulihang/ImageTrans-docs#264]
hello can i tranzleat the manga automatically without network like offline?

**Comment by xulihang** [comment]
You need to use offline OCR and machine translation engines like mangaOCR and OPUS-CAT.

**Comment by xulihang** [comment]
The OPUS-CAT has an English-Arabic model, though the quality may not be very good.

![image](https://user-images.githubusercontent.com/5462205/188850324-c68f922e-a8ad-46cb-80f5-800b178327a7.png)

**Comment by keba12** [comment]
no i just want to open the program without network and to make it Verification just one time and select the choice Heuristic offline and make " get Text area" also offline.

**Comment by xulihang** [comment]
After verification, you can use it offline.
