### ISSUE TITLE
设置的字体通用大小和自定义样式完全没用

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#265]
![Snipaste_2022-09-08_08-04-17](https://user-images.githubusercontent.com/24186777/189005868-b0d46620-d677-42db-a802-56757d1a4ced.jpg)

图像是900x1200的，通用设置了最小16最大26，也设置了自定义字体大小18，但是完全没用，自动生成的都是26 29的

**Comment by xulihang** [comment]
你希望字体大小是多少？

文档里对设置的优先级有说明：https://imagetrans.readthedocs.io/zh_CN/latest/gettingstarted.html#id24

**Comment by lhj5426** [comment]
之前在QQ群里就有人遇到这个问题 他就是没关闭自动调整字体 导致怎么弄字体都不统一

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/189068349-ce1675ed-5434-4996-924a-bbf676a149cf.mp4

**Comment by yahoozhu** [comment]
雀实是没关的原因
