### ISSUE TITLE
178 打开旧版项目直接报错....

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#269]
![image](https://user-images.githubusercontent.com/30548000/189513806-4beb8c3a-a0db-43ef-a8eb-957f8b1ee1a9.png)
[00088.zip](https://github.com/xulihang/ImageTrans-docs/files/9541826/00088.zip)
 附上一个报错的项目

**Comment by xulihang** [comment]
不是软件版本问题。你这个项目文件用什么软件打开过吗？尾部有其它数据了

**Comment by lhj5426** [comment]
> 不是软件版本问题。你这个项目文件用什么软件打开过吗？尾部有其它数据了

好像没有吧 ？反正也更新了 我重新做个新的 【项目模版】吧 不是软件的问题那就
