### ISSUE TITLE
Hover information for the current image

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#27]
I'm talking about the place between "previous" and "next" where you can click in the middle to choose a different picture. The problem is when the name for the jpg image too long is like this "xxxxxxxxxxxxxxxxx057" then you can't see what your current page number is without searching for it. It would be nice if I hover with the mouse over the area between "previous" and "next" that I could get the full name of the current image.

**Comment by xulihang** [comment]
Okay. I will add a tooltip.

![image](https://user-images.githubusercontent.com/5462205/113108542-ab50fc00-9237-11eb-932e-7e517d8e2e66.png)

**Comment by xulihang** [comment]
Added in v1.3.5 Update
