### ISSUE TITLE
使用网页插件翻译时软件一直报错

### ISSUE THREAD

**Issue by ftyswqqqq** [xulihang/ImageTrans-docs#270]
![a0bbb53796afcf6befbc1e0e42ac6773](https://user-images.githubusercontent.com/113300137/189535763-9173d179-3b58-42fb-90fb-3f151e133ab7.png)
出现在任何网站上

**Comment by xulihang** [comment]
给的信息太少，不能重现这个问题。我测这个网站是没问题的：https://ac.qq.com/ComicView/index/id/547921/cid/1

**Comment by xulihang** [comment]
可以先不用网页插件，单独处理一张图片，看看是不是也有这个问题。
