### ISSUE TITLE
竖排文字引擎对不同字体的兼容问题

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#271]
[方正黑体简体](https://www.zijia.com.cn/131.html)字体显示完整，标点位置正确：
![image](https://user-images.githubusercontent.com/5462205/189561878-9c9db0a9-8d80-462b-a3f2-e57d79ebebc3.png)

[思源黑体CN](https://www.zijia.com.cn/1000120.html)，最上方的文字顶端存在被切除一部分的问题：
![image](https://user-images.githubusercontent.com/5462205/189560021-8a3ff6c7-b7dc-49c4-a191-c422cc5762aa.png)

[思源黑体SC](https://www.zijia.com.cn/1000127.html)则没有这个问题：

![image](https://user-images.githubusercontent.com/5462205/189561923-e7252497-0eed-4c75-97de-5edf3bf07c8d.png)

微软雅黑，标点位置不对：
![image](https://user-images.githubusercontent.com/5462205/189562149-afc45906-e40f-42b6-9ff6-42ae38835e67.png)

![image](https://user-images.githubusercontent.com/5462205/189560071-298e3f5d-1fe6-46ec-9f17-b71931cf74c6.png)

不同系统的表现也会不一样，比如macOS上则没有上边缘被裁剪的问题

**Comment by xulihang** [comment]
横排时字体的省略号如果是居下的，竖排时旋转后会靠左，比如微软雅黑。如果原来是居中的，旋转后一般也是居中的，比如方正简体黑体。这个问题暂时没想到如何解决。

**Comment by xulihang** [comment]
标点符号的偏移在v1.7.9有一定改善，能根据固定宽度选择合适的起点位置

**Comment by lhj5426** [comment]
搭个issues车
[新建文件夹 (2).zip](https://github.com/xulihang/ImageTrans-docs/files/9562283/2.zip)
这两个字体的这个叹号要是能帮忙修一下就太感谢了 这个叹号 ｛❗｝
![image](https://user-images.githubusercontent.com/30548000/190049154-2b394dd0-8d7e-4c08-bd1d-c1b135173056.png)
如果是普通叹号shift+1的叹号的话根本就看不到哈哈
![image](https://user-images.githubusercontent.com/30548000/190049336-85a553f8-663a-4193-83f2-26b3208a8515.png)
还有~~~ 这个波浪号在竖排也能让它自己竖过来的话
![image](https://user-images.githubusercontent.com/30548000/190049536-37bf3964-da19-4ce7-948e-10c0a7537da7.png)

**Comment by xulihang** [comment]
> ~~~ 这个波浪号在竖排也能让它自己竖过来的话

1.7.9应该是能旋转~的

**Comment by xulihang** [comment]
> 这个叹号 ｛❗｝居中一点

目前哪些符号要居中我都是写死的，我再提供一个设置功能吧，能自定义哪些字符要旋转、居中这样的

**Comment by xulihang** [comment]
自定义符号功能加在v1.7.10里了
![image](https://user-images.githubusercontent.com/5462205/190885259-195fc64b-c7f7-48ff-b792-b32f73d732f7.png)

**Comment by lhj5426** [comment]
> 自定义符号功能加在v1.7.10里了 ![image](https://user-images.githubusercontent.com/5462205/190885259-195fc64b-c7f7-48ff-b792-b32f73d732f7.png)

我去 我去 我了个去 跳过1.7.9了哈哈 谢谢 老哥 这就更新体验

**Comment by lhj5426** [comment]
> 自定义符号功能加在v1.7.10里了 ![image](https://user-images.githubusercontent.com/5462205/190885259-195fc64b-c7f7-48ff-b792-b32f73d732f7.png)

![image](https://user-images.githubusercontent.com/30548000/190888771-74f919e7-afad-45db-b020-ccfa67345315.png)
太棒了！
