### ISSUE TITLE
术语管理

### ISSUE THREAD

**Issue by yougnut** [xulihang/ImageTrans-docs#272]
想请教术语管理如何开启、修改，目前程式内只看到添加的按键
![image](https://user-images.githubusercontent.com/67062125/189916845-b1e6a067-612d-4854-bc86-c7e045cd2008.png)

**Comment by yougnut** [comment]
了解，感谢。
请问是存放在哪个文件裡呢?

**Comment by xulihang** [comment]
扩展名itp的项目文件
