### ISSUE TITLE
“上/下一页”的按钮太贴近界面边缘了，能不能调一下

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#273]
![Snipaste_2022-09-13_22-07-58](https://user-images.githubusercontent.com/24186777/189925314-e2474c7d-fb77-4c8e-9e34-7be7645882b9.jpg)

太贴近边缘了，特别容易点到任务栏上弹出窗口

笔记本上上下翻页的快捷键也没反应

**Comment by xulihang** [comment]
可以把分辨率调低一点。快捷键翻页的话需要同时按住Ctrl键

**Comment by xulihang** [comment]
快捷键应该是没问题的，看看笔记本是不是需要把小键盘关闭

![image](https://user-images.githubusercontent.com/5462205/190315401-a9484422-6251-4eb5-818e-232dfa5fe259.png)

**Comment by yahoozhu** [comment]
没有小键盘的笔记本啦
