### ISSUE TITLE
Privacy Policy?

### ISSUE THREAD

**Issue by wfey12** [xulihang/ImageTrans-docs#275]
Hi, I would like to know the privacy policy of this app. I can't find it anywhere nor was it stated in the documentation. 

Clarification about the privacy policy would be appreciated.

1. Do you collect any data from us?

2. Do you share or resell data such as user email or other information to 3rd party?

I am looking forward to your response. Thanks

**Comment by xulihang** [comment]
No. It does not collect any data.
