### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by wfey12** [xulihang/ImageTrans-docs#276]
Hi, is the download link in Your Order not working?
![link1](https://user-images.githubusercontent.com/69673565/190544621-bad1e79b-cb1f-42e0-8efa-a44df9570258.jpg)
![link2](https://user-images.githubusercontent.com/69673565/190544635-4feabd46-b8f0-4b07-acd2-438e9db2a159.jpg)

**Comment by xulihang** [comment]
When did you make the order? The files may have expired in 7 days. You can use the links in the email sent to you.
