### ISSUE TITLE
掩膜区域都全涂红了，边边角角还是消不掉

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#278]
![Snipaste_2022-09-18_14-31-53](https://user-images.githubusercontent.com/24186777/190889064-9a7d372a-4bad-4029-b2ea-8a2a0685734a.jpg)

这还是我加了30个像素的描边遮了点，气泡覆盖整个对话框了

**Comment by xulihang** [comment]
新版我改成以文字框为单位去除文字，如果掩膜超出了文本框的范围，是不起效果的

**Comment by xulihang** [comment]
不调文本框范围的话，可以用编辑-编辑去除文字图操作，这个是以全图为单位处理的
