### ISSUE TITLE
导出文本报错

### ISSUE THREAD

**Issue by lvlvbubu** [xulihang/ImageTrans-docs#279]
![RIOZ3Q9_5E% KZ)N~{1AEN0](https://user-images.githubusercontent.com/34003162/190904652-8db00c02-180e-44cf-9f47-26658944db02.png)

**Comment by xulihang** [comment]
这是v1.7.8引入字间距设置带来的问题，我会发个新版本修复这个问题

**Comment by xulihang** [comment]
v1.7.11修复了这个问题
