### ISSUE TITLE
OCR batch skips areas with null result

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#28]
It does make sense that ocr batch will skip all text areas that have already been ocred, but it does so as well for every area that has gotten a null result which is a big problem if you use ocr with a daily limit. The only way right now for that to not happen is to use only offline ocr all the time so that you don't get a null result to begin with.

**Comment by HeLan8** [comment]
This seems to be only an issue with baidu ocr, the other ocr engines don't give me a null result when they don't work or when the limit is reached

**Comment by xulihang** [comment]
You can use `Search and Replace` to remove null. 

The correct handling of wrong OCR results is not unified. Only Baidu will give a null result.

**Comment by HeLan8** [comment]
Right, it works. I should probably go through every single option of this program to see what's possible.
