### ISSUE TITLE
Instructions & Policy

### ISSUE THREAD

**Issue by jjangyi** [xulihang/ImageTrans-docs#280]
Hello, I'm interested in buying this but the lack of instructional videos on how to set up the machine translations and OCR puts me off. Is there any plan to make a video on those process? Also, where can I read the privacy policy of the software?

**Comment by xulihang** [comment]
There are some OCR and machine translations available out of the box. 

You can configure your own API Keys and set up local offline services of your choice. Check out the docs for more: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html

About privacy policy, I haven't put up a page. It does not collect any data.
