### ISSUE TITLE
图片过大时无法生成掩膜

### ISSUE THREAD

**Issue by nortrom-neverafk** [xulihang/ImageTrans-docs#281]
如题，生成文字掩膜软件直接卡死，等待无反应，只能任务管理器强制关闭 
![image](https://user-images.githubusercontent.com/51827569/191052512-175ad777-5cea-4c5c-a34f-c10eb3b6c741.png)

奇怪的是，如果点击“批处理”里面的生成所有的图片掩膜和去文字图片，功能可以正常实现，文件夹里面也生成了
![image](https://user-images.githubusercontent.com/51827569/191053268-6acb3e3e-8949-4c18-abf3-9265c9bfa349.png)

但是单个图片仍然无法编辑文字掩膜；
却可以点击文字区域里面的修改掩膜和无文字图实现编辑文字掩膜
![image](https://user-images.githubusercontent.com/51827569/191054109-13383868-f80d-4df9-ae74-f3bd7ad3f841.png)

经过测试，发现图像过大（5000×7000以上）时必然会出现这种情况，这可能是某种bug，建议修改

**Comment by xulihang** [comment]
掩膜编辑器还需要把图像绘制到canvas上，图片过大时会比较慢。图像过大时，默认会把长边缩放到8000像素。

相关issue：https://github.com/xulihang/ImageTrans-docs/issues/266

**Comment by xulihang** [comment]
我测了张5000x7000的图没问题，检查下是不是用的64位版

**Comment by nortrom-neverafk** [comment]
我用的的确是64位版本的，测试了还是不行，需要改用32位版本吗？

> 我测了张5000x7000的图没问题，检查下是不是用的64位版

**Comment by nortrom-neverafk** [comment]
32位版本好像还是不行
![image](https://user-images.githubusercontent.com/51827569/191256126-5c113c19-692a-484c-8bc0-c211af6ad5fc.png)

**Comment by xulihang** [comment]
64位应该比32位性能好一点。把图片发我下吧，我测一下

**Comment by nortrom-neverafk** [comment]
![2](https://user-images.githubusercontent.com/51827569/191257419-1c1be868-328d-41ba-8ff9-551977db1578.jpg)

**Comment by xulihang** [comment]
我在五代i5 2Ghz，8GB内存的笔记本上处理没问题。

可以用命令行打开软件，把java虚拟机的内存设大一点。

```
jre\bin\java -jar -Xmx2048M ImageTrans.jar 
```

**Comment by nortrom-neverafk** [comment]
![image](https://user-images.githubusercontent.com/51827569/191275964-1ae9a452-1cf0-459f-99a0-7a7331af7ab1.png)
![image](https://user-images.githubusercontent.com/51827569/191276410-45332ac3-bfe1-40a2-b40c-6dabb0fe4f17.png)
空指针异常，感觉有点迷
但“批处理”里面的生成所有的图片掩膜和去文字图片的功能是可用的，文字区域里面也是可以生成掩膜，就是不能对单张图片生成掩膜。
应该其他人都没这个问题，可能我电脑运气不好吧，不过也不怎么影响使用。

**Comment by xulihang** [comment]
可能是上游软件的问题，可以换个liberica jdk 11试试。不行那就先用编辑文字区域的掩膜吧

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/191325282-326966d3-3331-4523-b768-527c3eb5a3c2.png)
我这边 刚试过 没事
还有 教 你个技巧
最近我也开始配用PS修图配合漫画软嵌字件一起用了
是这样的
用的
自己修改的图片后缀加  .jpg-original.jpg 就可以替换掉自动生成的图了
例子#0033.jpg-original.jpg  10.png-original.jpg
-original.jpg
原名.原后缀-original.jpg
软件生成的去字图片
原名.原后缀-text-removed.jpg
软件默认修图是加上-text-removed.jpg 的
想省事或者软件涂抹有瑕疵 处理不好需要用PS修图 修完之后保存同名 然后软件激活 **查看翻译**可以看到效果
但是用-text-removed.jpg 这个不能再用软件去涂抹修改 如果用软件涂抹会被重新生成的-text-removed.jpg 覆盖替换到
然后就是第二种方法
还有一种方法是-original.jpg 这个你怎么用软件修图都不会被覆盖 不过用PS修完也没必要再用软件修了
就是直跳过软件修图直接拿原图去ps修图
修完之后直接按 原名.原后缀-original.jpg 放入文件夹

比如0001.png
按照 原名.原后缀-original.jpg
就是0001.png-original.jpg

这样保存 然后激活软件 查看翻译可以看到 刚导入图片的效果 
这样也不需要完全依赖 软件的修图功能 
不过说到PS 软件导出PSD是一次性导出全部. 这个就很伤 因为我做的基本上都是上百页的漫画 我就用过一次导出PSD 电脑不太好导出了小1个小时 太麻烦了  之后就反向操作研究出这种 用作图软件修图然后反向用漫画软件嵌字的方法

**Comment by lhj5426** [comment]
> 举个例子你像这种 图 ![image](https://user-images.githubusercontent.com/30548000/191329176-227b9d99-f0f3-4e29-89e9-f6fc327e31be.png) 软件修完多少会破坏图片而 ps就很好 本来我 不会PS 后来稍微学了点 诶嘿 ![image](https://user-images.githubusercontent.com/30548000/191329490-a37082d1-b585-468e-8599-03093e875241.png)
> 
> > ![image](https://user-images.githubusercontent.com/30548000/191329369-91d6c2ab-9868-4393-b97b-16539440fa7e.png) 然后这样 改名放到目录里就行了 暂时你可以先 用 这个小技巧来用PS对图片处理 先用来过渡一下 等 下个版本 或者之后的版本里 开发者修复了这个问题之后 再接着用软件涂抹修改
> > ====================================================
> > 牛，老哥牛，在这里先感谢老哥和作者。
> > 不过用ps去扣字修图的话，应该会更花时间吧，我以前接触过ps，感觉需要很大耐心。
> > 我用这个软件汉化的话，都是选漫画或者同人志。因为修改漫画对白字体效果很好，而cg图大多因为没有对话框，修完多少会破坏图片，正如你所说。
> > 所以就算要汉化cg图，应该也要有那种textless的无字版本，你给出的例子应该也是这种吧？对于没有无字版本的cg图，就算是用ps慢慢改工作量也很大吧？
> > 不过，你说的通过加后缀-original.jpg的这种方法感觉确实很实用，特别是翻译cg图方面给了我很大启发。我想我以后会试试你这种方法，来汉化cg。
> > 我看老哥在这上面挺活跃的，前几天也细读了你发的提升操作效率的技巧，虽然keymanager现在我还不怎么会用，现在还在摸索。
> > 最后，我后面会通过你说的通过加后缀的方法来试试汉化cg，如果有不懂的再来问问老哥。

有的是用无文字图  替换就行 这是-original.jpg 管理无文字图和原图的初衷 不过我举例子的这部没有 提供 竖排文字原图    都PS一点点弄的
你看同人志 我这本也在e站开坑了 生肉地址里提供 这个竖排对话的无字图 .........
