### ISSUE TITLE
关于文字选中批量移动的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#285]
![image](https://user-images.githubusercontent.com/30548000/191689205-0e44139c-ebc4-44fc-bd9c-3e4f740f0765.png)
是这样的我想移动 没有被方括号包住的文字 和 方括号持平
但是当我操作的时候我发现

https://user-images.githubusercontent.com/30548000/191690119-f9700877-b235-4f3a-b4fa-da8b4097bdfa.mp4

欸？？？ 明明选中 了3个 但是 通过快捷键操作只能移动 最后选择上的一个？？？
而鼠标操作却可以 移动全部被选上的文本块？？？？
不知兄台何意如此啊？后续版本可以增加用快捷键批量对选中的文本框进行移动操作么 谢谢
或者是 我的操作 不对？

**Comment by xulihang** [comment]
我看了下代码，只操作单个文本框，我改成操作所有文本框吧

**Comment by lhj5426** [comment]
> 我看了下代码，只操作单个文本框，我改成操作所有文本框吧

土下座 感谢

**Comment by xulihang** [comment]
变动应用在v1.8.0了

**Comment by lhj5426** [comment]
> 变动应用在v1.8.0了

感谢 这样我就可以挑战一下 纯文字无气泡的漫画了 有时间的话
