### ISSUE TITLE
批量导出图片的bug

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#286]
![image](https://user-images.githubusercontent.com/30548000/191724788-cad29c94-bb65-4e04-9f38-c07d17c99f97.png)
触发bug的图片是 有两种分辨率 分别是  2400x1800 和 2400x2400
![image](https://user-images.githubusercontent.com/30548000/191725062-115e534f-7c83-4774-a541-c3532767b300.png)
然后 润色完 用 
![image](https://user-images.githubusercontent.com/30548000/191725301-1d891a06-5f68-442a-a20a-44b396becb4e.png)
这个 生成成品图 就出现了 第一张图的 bug 效果
单独用 
![image](https://user-images.githubusercontent.com/30548000/191725798-6312b642-e06e-4a42-8df1-080b855f4b09.png)
不会出现这个bug

**Comment by xulihang** [comment]
这个复现的概率比较低，不清楚原因，你再操作一次还会有这个问题吗？

**Comment by lhj5426** [comment]
> 这个复现的概率比较低，不清楚原因，你再操作一次还会有这个问题吗？

没有复现出来 之后我把软件关了重启之后 没复现 哈哈 好神奇这个bug 叠图
