### ISSUE TITLE
editable psd files issue

### ISSUE THREAD

**Issue by molyzoo** [xulihang/ImageTrans-docs#287]
Hi
i'm unable to export the work into '**_editable psd files_**';
depending of the various settings in ImageTrans i got an error either in line 3195, 3208 or 3238 of the addLayers.exe
Do you know how to fix it?
(addLayers.jsx is already updated to the latest version)

**Comment by xulihang** [comment]
The exe version may not work on your computer. You need to use the js version which is `addLayers.jsx`. Open Photoshop, in its File menu, go to script and select `addLayers.jsx`. Then, select the image's folder to generate PSDs using the exported data.
