### ISSUE TITLE
pt文件怎样才能导入Image Trans

### ISSUE THREAD

**Issue by MisterQX** [xulihang/ImageTrans-docs#289]
请问我用yolo5训练出来的[best.pt](http://best.pt/)文件怎样才能导入Image Trans呢？

**Comment by xulihang** [comment]
ImageTrans用的OpenCV的dnn来实现的目标检测（[代码](https://github.com/xulihang/ObjectDetector/blob/main/src/org/xulihang/ObjectDetector.java)），应该需要把pt转换成onnx来使用

**Comment by MisterQX** [comment]
> ImageTrans用的OpenCV的dnn来实现的目标检测（[代码](https://github.com/xulihang/ObjectDetector/blob/main/src/org/xulihang/ObjectDetector.java)），应该需要把pt转换成onnx来使用

我试着把pt文件转换成onnx文件了，放进目录中似乎不行
![image](https://user-images.githubusercontent.com/51272049/192097431-2234bff6-fa1c-4d7a-93f2-079bb3e1bf42.png)

**Comment by xulihang** [comment]
还需要一个model.json配置文件，类似这样的：

```json
{
	"isDarkNet":false,
	"swapRB":true,
	"crop":false,
	"mean":[127.5,127.5,127.5],
	"scalefactor":"1/127.5",
	"width":320,
	"height":320,
	"model":"model.pb",
	"modelcfg":"model.pbtxt"
}
```

**Comment by MisterQX** [comment]
> 还需要一个model.json配置文件，类似这样的：
> 
> ```json
> {
> 	"isDarkNet":false,
> 	"swapRB":true,
> 	"crop":false,
> 	"mean":[127.5,127.5,127.5],
> 	"scalefactor":"1/127.5",
> 	"width":320,
> 	"height":320,
> 	"model":"model.pb",
> 	"modelcfg":"model.pbtxt"
> }
> ```

我刚刚试了放进一个json配置文件，但是似乎还是不行，还是弹出模型未正确放置，不好意思，我不太懂如何配置这个配置文件，是直接放入我转换的.onnx文件和这个.json配置文件就行了吗？

**Comment by xulihang** [comment]
配置文件有做什么修改吗？它会根据这个配置文件里的模型路径加载文件，如果没加载成功就会提示未正确放置。

**Comment by MisterQX** [comment]
![image](https://user-images.githubusercontent.com/51272049/192100796-6910e618-b451-4a7e-b715-11b0cf29985d.png)
我尝试修改了一下，我没有cfg文件

**Comment by xulihang** [comment]
darknet应该要设为false

**Comment by MisterQX** [comment]
> 暗网应该设为false

还是不行

**Comment by xulihang** [comment]
不行可以启动一个python的http服务，提供和这里一样的接口：https://github.com/xulihang/ImageTrans_SceneText_Detection/blob/75995ab8e755ce8ce83ad83729f31d9b5795ad02/server_EAST.py#L160 之后用自然场景文字检测操作调用

**Comment by MisterQX** [comment]
> 

不好意思，我不懂怎么启动http服务

**Comment by MisterQX** [comment]
> 不能用启动一个python的http服务，提供和这里一样的接口：https://github.com/xulihang/ImageTrans_SceneText_Detection/blob/75995ab8e755ce8ce83ad83729f31d9b5795ad02/server_EAST.py#L160之后场景自然文字检测调用
> 
> ![图片](https://user-images.githubusercontent.com/5462205/192101216-32229c97-5b8a-4d26-a305-0cd1946289e4.png)

是这样吗
![image](https://user-images.githubusercontent.com/51272049/192101651-f4cc0935-bad9-4e02-9751-58df6ab43794.png)
![image](https://user-images.githubusercontent.com/51272049/192101659-b5e9caf3-6fb6-4d70-95c8-478860330ce5.png)

**Comment by xulihang** [comment]
需要`pip install bottle` 安装依赖。然后修改下代码，改成调用yolov5去识别。

**Comment by MisterQX** [comment]
> 需要`pip install bottle` 安装依赖。然后修改下代码，改成调用yolov5去识别。

改这里吗？
![image](https://user-images.githubusercontent.com/51272049/192102200-1445c533-463c-49b8-ac08-834feb7c50e7.png)

**Comment by MisterQX** [comment]
> 不行可以启动一个python的http服务，提供和这里一样的接口：https://github.com/xulihang/ImageTrans_SceneText_Detection/blob/75995ab8e755ce8ce83ad83729f31d9b5795ad02/server_EAST.py#L160 之后用自然场景文字检测操作调用
> 
> ![image](https://user-images.githubusercontent.com/5462205/192101216-32229c97-5b8a-4d26-a305-0cd1946289e4.png)

![image](https://user-images.githubusercontent.com/51272049/192108838-50704532-cd08-44f3-a301-c88025da8ba9.png)
是这样吗？

**Comment by MisterQX** [comment]
> 需要安装。然后修改下代码，改成调用yolov5`pip install bottle`去识别。

其他的我大概懂了，就是这个修改成调用yolov5实在搞不懂，是要直接调用权重还是要调用detect.py呢？

**Comment by MisterQX** [comment]
> 需要安装。然后修改下代码，改成调用yolov5`pip install bottle`去识别。
我没有学过python，请问如何修改这个代码呢？

**Comment by xulihang** [comment]
我看你能训练模型还以为你会python。没学就学下或者找别人改吧
