### ISSUE TITLE
can you add translate program 'eztrans'?

### ISSUE THREAD

**Issue by bravehon** [xulihang/ImageTrans-docs#29]
I use VNR [It's japanese adult game translate supporter]
when I use eztrans translation quality is high

[eztrans]
http://www.mediafire.com/file/roroiechqkz6319/ezTrans_XP_no_Install.7z/file

[VNR eztrans file]
https://blog.naver.com/bravehon/222308125156

**Comment by xulihang** [comment]
I will try to write a plugin. 

There are some projects I can reference:
https://github.com/HelloKS/ezTransWeb/blob/master/eztrans.py

**Comment by bravehon** [comment]
> I will try to write a plugin.
> 
> There are some projects I can reference:
> https://github.com/HelloKS/ezTransWeb/blob/master/eztrans.py

thank you!

**Comment by xulihang** [comment]
How to use:

1. Download eztrans and Ehnd. Put Ehnd with eztrans. (https://blog.naver.com/waltherp38/221062272423)
2. Download Python 3 x86: https://www.python.org/ftp/python/3.6.6/python-3.6.6-embed-win32.zip. Unzip it and put the files with eztrans.
3. Download eztrans's ImageTrans plugin files and put them into ImageTrans's plugins folder. 
[eztrans.zip](https://github.com/xulihang/ImageTrans-docs/files/6304225/eztrans.zip)
4. Download this file, unzip it and put it in the parent folder of eztrans.
[ezTrans.zip](https://github.com/xulihang/ImageTrans-docs/files/6304216/ezTrans.zip)
5. Double click `run.bat` to start the eztrans server.
5. Enable eztrans in ImageTrans.

**Comment by xulihang** [comment]
![image](https://user-images.githubusercontent.com/5462205/114564826-44a1f880-9ca3-11eb-99ba-457450ab22ba.png)

**Comment by bravehon** [comment]
![1](https://user-images.githubusercontent.com/79227082/114632334-78a80880-9cf9-11eb-89bb-770bf36f0141.jpg)

thank you! it's work!

**Comment by bravehon** [comment]
thank you so much 
I was surprised to work so fast
You are Genius!
