### ISSUE TITLE
手动添加的文本框可以设置默认大小和形状吗？

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#290]
![Snipaste_2022-09-25_11-36-15](https://user-images.githubusercontent.com/24186777/192127163-2234a0f0-e790-4fda-9bf8-c370e07f1033.jpg)

默认的总是这个大小的横排长方形框，大部分要手动添加气泡的都是单个拟声词，想调成默认正方形或竖直方框

**Comment by xulihang** [comment]
我加个项目设置吧，可以修改默认的尺寸

**Comment by xulihang** [comment]
添加在v1.8.0里了
