### ISSUE TITLE
关于ImageTrans_SceneText_Detection的问题

### ISSUE THREAD

**Issue by MisterQX** [xulihang/ImageTrans-docs#291]
请问www里的文件导入哪里呢
https://github.com/xulihang/ImageTrans_SceneText_Detection/tree/75995ab8e755ce8ce83ad83729f31d9b5795ad02/www
我把
![image](https://user-images.githubusercontent.com/51272049/192155019-2c75aef3-894a-4a74-9f6c-41925179f205.png)
![image](https://user-images.githubusercontent.com/51272049/192155027-56b4c421-8a15-4cf3-b87d-14123aeb11d7.png)
都运行了
![image](https://user-images.githubusercontent.com/51272049/192155059-91bc94ea-18fc-4eea-82bf-2a70328a089d.png)
但检测还是没反应
![image](https://user-images.githubusercontent.com/51272049/192155096-9b11a7d9-037b-4dba-b59f-15a559a0d7f5.png)

**Comment by xulihang** [comment]
这个我好久没测了，`server_CRAFT_original.py`这个应该是能用的

**Comment by xulihang** [comment]
它需要下载模型，可能要花一点时间才能启动

**Comment by MisterQX** [comment]
要从[kera](https://github.com/faustomorales/keras-ocr)这里下好keras-ocr的包吗，我刚才uninstall了就这样了
![image](https://user-images.githubusercontent.com/51272049/192197426-0fb59f66-5ab4-4a49-95fb-67728fd7ee3b.png)

**Comment by xulihang** [comment]
要装一下：

```
pip install keras-ocr
```

自然场景文字检测这个目前不是很实用，建议结合具体需求确定要不要用这个

**Comment by MisterQX** [comment]
> 要装一下：
> 
> ```
> pip install keras-ocr
> ```
> 
> 目前这个场景检测文字不是很实用，建议结合这个具体需​​求确定不要用

昨天用了启发式发现有些黑色底色的气泡好像识别不是很好

**Comment by MisterQX** [comment]
![image](https://user-images.githubusercontent.com/51272049/192198833-c595aa4d-b013-4ecc-81a7-8cface4b5ad4.png)

**Comment by xulihang** [comment]
日漫可以用这个：https://github.com/xulihang/ImageTrans-docs/issues/135

**Comment by MisterQX** [comment]
> 日漫可以用这个：#135

假如我先用这个，然后再用启发式，文字框会叠在一起吗？

**Comment by xulihang** [comment]
不会，如果和原来的文本框有重叠就不添加
