### ISSUE TITLE
字体安装到C盘了项目设置里都没有？在word文档里都可以选择了

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#292]
已经在C盘安装过了，但是项目设置里都没有，要重新安装，在word里都可以找到已安装的字体了

**Comment by lhj5426** [comment]
有没有一种可能 字体是可以独立安装的 跟安装到系统没关系
![image](https://user-images.githubusercontent.com/30548000/192375963-02f79ddf-4cd7-4402-99c3-05b4dd48ce6e.png)

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/192378589-06a0ff1a-0aef-4a93-bc27-021e5e003954.png)

然后如果一本漫画图片量大 怕软件崩溃 可以分成N个项目
每次完成一个项目分支的时候 开下一个项目 字体通过 右键导入上一个项目的字体就可以接着用了
![image](https://user-images.githubusercontent.com/30548000/192378703-df8e329a-13b4-4d00-9fd8-05594d200c11.png)

**Comment by lhj5426** [comment]
你像 项目里的自动更正 
![image](https://user-images.githubusercontent.com/30548000/192379692-f69497de-86f3-4ade-9384-40268ae39537.png)
![image](https://user-images.githubusercontent.com/30548000/192379737-4b677153-63b3-4d23-a063-e8e95d558cb3.png)
竖排设置
术语 都是跟着每一个项目文件走的 不是软件自身记录
所以创建一个 该设置都设置的项目模板 每次复制 这个模板来进行
是最省事的要不然 每次创建一个新的项目就要设置一次

**Comment by xulihang** [comment]
我用JavaFX的字体列出功能是存在无法列出部分安装在系统的字体的问题，所以我在字体项目设置里加了一个手动添加字体的功能
