### ISSUE TITLE
汉化日漫图流程

### ISSUE THREAD

**Issue by adaidaia123** [xulihang/ImageTrans-docs#294]
![afc77c0d358a7ea922d04b0c8e84c41](https://user-images.githubusercontent.com/114478767/192488075-31a010a3-1ed6-4923-acc0-6502aa0dc53c.jpg)

**Comment by xulihang** [comment]
流程并不是唯一的，可以有多种流程。我这里大致讲一个较合适的流程。

1. 文字检测

   使用https://github.com/xulihang/ImageTrans-docs/issues/135 提供的离线气泡检测模型识别气泡，并在项目设置里适当调整`拓展区域像素`，让气泡完整包含文字。这个气泡检测模型能识别背景复杂和黑底白字的气泡。

2. 识别文字

    使用OCR引擎识别文字。这张图片比较简单，没有复杂背景和振假名，可以直接用tesseract识别。manga-ocr的精度更高，并能识别复杂背景的文字以及自动去除振假名，但需要自行下载使用。或者也可以用百度、google等在线OCR。

3. 机器翻译

   挑选任一合适机器翻译引擎即可。

4. 查看翻译的图片与排版

   点左下角的查看翻译，可以查看翻译好的图片。这时再勾选排版模式可以进行排版。

更多见文档吧：https://imagetrans.readthedocs.io/zh_CN/latest/gettingstarted.html

**Comment by xulihang** [comment]
更多博客：
https://blog.xulihang.me/design-a-good-raw-Japanese-manga-reader/
https://www.basiccat.org/zh/best-practice-manga-ocr-and-translation/

**Comment by xulihang** [comment]
视频教程：

https://search.bilibili.com/all?keyword=ImageTrans
