### ISSUE TITLE
Tesseract OCR integration not working

### ISSUE THREAD

**Issue by cjmccjmccjmc** [xulihang/ImageTrans-docs#3]
HI,
 I'm having an issue with using Tesseract as the OCR engine.   I've successfully used ocrspace but when I use tesseract no translation has occurred.

It could be the external Tesseract setup, is there additional debug logging that I can enable?

To reproduce:

1. Open a file with a file.
2. Run Project/Detect Text Areas (heuristics)
3. Click 'OCR' button
4. If using ocrspace: 'OCR.. ' appears stays while processing and some text appears
5. if using tesseract: 'OCR.. '  flashes up and not text appears.

**Comment by xulihang** [comment]
Hi,

Have you installed tesseract? You can install it following its instruction: https://tesseract-ocr.github.io/tessdoc/Installation.html#windows .

If tesseract.exe's path is set in the system's environment, then it should work. If not, you need to mannualy specify tesseract.exe's path in preference.

In addition, you need to install language data to support extra languages.

**Comment by cjmccjmccjmc** [comment]
I opened a command prompt and added in tesseract to PATH and had ran it.  Successful processing, no issue.

BTW using Tesseract v4.x.x
