### ISSUE TITLE
怎么竖排字符居中的设置好像没用呢

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#301]
![Snipaste_2022-10-04_12-59-32](https://user-images.githubusercontent.com/24186777/193738817-915d4849-4a2d-4b62-97fe-49a669b43aed.jpg)
![Snipaste_2022-10-04_13-02-35](https://user-images.githubusercontent.com/24186777/193738829-43367c69-8034-4503-a324-b8f5e1fbecb3.jpg)

**Comment by xulihang** [comment]
这是什么字体？

**Comment by xulihang** [comment]
上下两张图有啥区别吗？

**Comment by yahoozhu** [comment]
前面上下两图符号居中不一样啊，下面这些都试了都没有一个能全部居中的，，我之前一直用的汉仪正圆是可以完全居中的，现在省略号“…”变得不能居中了，好奇怪
![Snipaste_2022-10-04_14-09-00](https://user-images.githubusercontent.com/24186777/193747688-67be2271-8ee1-4d4e-b596-adf2fc2b1a05.jpg)
![Snipaste_2022-10-04_14-09-29](https://user-images.githubusercontent.com/24186777/193747697-a1d1ce34-06d1-4638-8077-467af4f8c7cd.jpg)
![Snipaste_2022-10-04_14-10-59](https://user-images.githubusercontent.com/24186777/193747704-ccada99f-3810-46cc-b8f5-779ceaffb23f.jpg)
![Snipaste_2022-10-04_14-12-42](https://user-images.githubusercontent.com/24186777/193747716-c351752e-5afb-4445-adda-b291ba0057f1.jpg)

**Comment by xulihang** [comment]
不同字体的兼容会有问题，尽量用没问题的字体吧：https://github.com/xulihang/ImageTrans-docs/issues/271

或者像针对兰米叹号和问号不居中，可以改用❗和❓，把它们设为居中字符。

**Comment by yahoozhu** [comment]
见鬼，好乱啊，用你上面给的符号后，！和？都居中了，但是本来可以正常居中的省略号又变得靠右了，新建了个项目重新搞了一遍，省略号重新居中了，！和？重新添加设置也不能居中了，真的无语，不过下载了个方正黑体现在是全部能居中了，先用这个了

**Comment by swswlg** [comment]
> 不同字体的兼容会有问题，尽量用没问题的字体吧：#271
> 
> 或者像针对兰米叹号和问号不居中，可以改用❗和❓，把它们设为居中字符。

能加一个四面居中的逗号么？
![屏幕截图 2024-09-13 004016](https://github.com/user-attachments/assets/0952c7d5-65ab-4420-aaf8-375a18879fbe)

**Comment by xulihang** [comment]
可以用3.10.0加的offsetx和offsety设置偏移量。

![image](https://github.com/user-attachments/assets/9e08085b-60a0-4ff6-bca3-5c18b7bf14ac)
