### ISSUE TITLE
可以选择是否读取子文件夹嘛

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#304]
![image](https://user-images.githubusercontent.com/30548000/194702058-547ddab6-c536-4eac-b925-5714fb179062.png)
![image](https://user-images.githubusercontent.com/30548000/194702088-25518706-46a2-427f-b140-75fc76426c94.png)
现在默认是直接读取子文件夹 
因为有些原因必须会出现子文件夹
所以未来可以设置是否读取子文件夹嘛 感谢

**Comment by xulihang** [comment]
好的，我加个项目设置吧

**Comment by lhj5426** [comment]
> 好的，我加个项目设置吧

![image](https://user-images.githubusercontent.com/30548000/194703582-ea1032aa-43a7-4987-9195-577e0bfbf16a.png)
如果要加 尊敬的老哥这个应该是加到偏好设置里才对吧 全局的

**Comment by xulihang** [comment]
我偏向于项目设置

**Comment by xulihang** [comment]
加在v1.8.2里了

**Comment by lhj5426** [comment]
> 加在v1.8.2里了

收到 这就去更新 辛苦
