### ISSUE TITLE
run.bat闪退

### ISSUE THREAD

**Issue by wlgh111** [xulihang/ImageTrans-docs#305]
您好，运行run.bat闪退，显示的错误是“valueerror:check-hostname requires server-hostname”,请问该怎么办？

**Comment by xulihang** [comment]
照这里操作应该是可以的：https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR

**Comment by lhj5426** [comment]
> 您好，运行run.bat闪退，显示的错误是“valueerror:check-hostname requires server-hostname”,请问该怎么办？

这个闪退一般是网络问题 可以这也解决 这个解决方法其实网盘里就有 
------------------------------------------------
运行run.bat，或者run.exe 不要关闭弹出的窗口。 
等待出现127.0.0.1 

如果出现闪退，请按住Shift后右键，点“在此处打开Powershell窗口”，之后在出现的窗口里输入.\run.bat再按回车以运行，便于查看错误。

错误原因可能是需要翻墙或者模型下载错误。这时可以尝试文件夹里提供的模型缓存文件transformers文件夹，


复制到你的用户目录的.cache\huggingface\transformers文件夹里

（例如C:\Users\ziiyue\.cache\huggingface\transformers）。但注意这一方法可能会在模型更新后失效。

-----------------------------------------------
然后也说了 网络问题 网络问题怎么解决呢 以下
用小猫 cfw 举例子

![image](https://user-images.githubusercontent.com/30548000/195857550-02f321fd-3fda-43cf-ad57-a63bf18d1e15.png)
Python.exe 默认是不走代理的 小猫需要这也设置开启 真全局代理 
才会 在第一次运行的时候 正确下载模型
下载完成只会 就不会再闪退了
不过如果网络不好 直接用网盘里的方法也是一样的

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/195862839-1cd412bd-58e0-478b-a678-e29b11afa37d.png)
网盘里的补充文件里有说明 
一般就是网络问题 小猫开全局一般就解决了 我自己和 TG群里的小伙伴都是因为网络问题导致的闪退
![image](https://user-images.githubusercontent.com/30548000/195863073-41a57e18-ede0-4d8f-a35e-cfded2a0eefb.png)
