### ISSUE TITLE
导出PSD报错 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#307]
![image](https://user-images.githubusercontent.com/30548000/195976497-8f33e199-5949-416b-8306-09458f62845e.png)
![image](https://user-images.githubusercontent.com/30548000/195976512-d262d2d0-2b93-4742-a9a9-ced739704a24.png)
用的这个版本导出的 到PS就直接报错了 ~~
然后我用的PS版本
![image](https://user-images.githubusercontent.com/30548000/195976593-46aab765-a16f-4787-853e-0d057f4ccf67.png)
问题出在哪里呢
是完全按照视频上的勾选的
![image](https://user-images.githubusercontent.com/30548000/195976646-a7a43217-0950-40eb-8fa3-0b9268021e3f.png)
以前用过 好使 今天用就报错了

**Comment by lhj5426** [comment]
啊没事了 看到了 脚本更新了

**Comment by xulihang** [comment]
不勾选仅导出，用addLayers.exe会报错吗？可能是PS不是正常安装的问题，无法调用COM。这时候得用addLayers.jsx。

**Comment by lhj5426** [comment]
> 不勾选仅导出，用addLayers.exe会报错吗？可能是PS不是正常安装的问题，无法调用COM。这时候得用addLayers.jsx。
![image](https://user-images.githubusercontent.com/30548000/196023672-5cdd3a8b-bb7a-4cd7-be79-f984831043dd.png)
![image](https://user-images.githubusercontent.com/30548000/196023677-7282d344-8e66-4a06-8063-3188c415427d.png)
试了下这个 也是一样 不过无所谓了 手动启动脚本 也没什么 只要能导出就 是\(^o^)/~好的 
如果能修一下？ 顺便添加一个但张导出PSD  因为有时候只有只有几张图需要PS去做特效或者处理，结果呢只能等全部都导出只会才能去处理那需要的一张或者几张 单张导出psd的话可以按需处理 比较灵活 
希望开发者老哥 可以权衡一下 是否 能够考虑考虑在未来加入 单张导出psd的功能
![image](https://user-images.githubusercontent.com/30548000/196023773-3eca5239-6a37-44a1-b0b7-2e43485e767f.png)
