### ISSUE TITLE
I have a problem installing the program

### ISSUE THREAD

**Issue by Jack-0009** [xulihang/ImageTrans-docs#308]
When I run the program to install it it doesn't open anything (it doesn't work)
What is the solution to this problem?

![image](https://user-images.githubusercontent.com/79697535/196276899-d436d915-d8b8-439a-b641-c02b49d733e5.png)

**Comment by xulihang** [comment]
You are using the cross-platform version which requires installing of jre and opencv. For convenience, you can use the full package on onedrive.

**Comment by Jack-0009** [comment]
Where can I get the full version?

**Comment by xulihang** [comment]
Check out the emails you received.

**Comment by Jack-0009** [comment]
I have another problem, I can't extract the text and translate it

![image](https://user-images.githubusercontent.com/79697535/196507730-1906ac6d-aa9b-40a7-bc82-e8833be9a021.png)

**Comment by Jack-0009** [comment]
Text extraction is not accurate and this error also appeared
And Google Translate does not work with most of the services


![image](https://user-images.githubusercontent.com/79697535/196517424-e2baeb8d-2b0d-4da0-847e-ddcb41d3caf2.png)

**Comment by xulihang** [comment]
Not all OCR and machine translation engines are available. Some require extra installation and some require applying for an API key. 

You can check out the docs first to see which OCR engines are available by default: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#ocr

About PSD, also check out the docs: https://imagetrans.readthedocs.io/en/latest/interoperation.html#psd

**Comment by Jack-0009** [comment]
I am using the full version, do I need to install these add-ons? 

Also some API keys need money and others are hard to get. Is there a free way to get them?

**Comment by xulihang** [comment]
You need to install tesseract if you need to use it. It also applies for mangaOCR, etc. 

There is no free way to get them. DeepL is free with a hack though.
