### ISSUE TITLE
字体大小无法更改

### ISSUE THREAD

**Issue by Kannagis** [xulihang/ImageTrans-docs#309]
在项目-设置-字体样式-设置字体那里调了字体大小后，按了确认出去应用没字体大小还是那样，回去看设置字体那里又变回了默认的15大小

**Comment by xulihang** [comment]
字体大小的设置可以先看下文档：https://imagetrans.readthedocs.io/zh_CN/latest/gettingstarted.html#id25

**Comment by Kannagis** [comment]
> 

好吧 是自动调整字体的问题 感谢回复
