### ISSUE TITLE
Error related to machine translation comes repeatedly

### ISSUE THREAD

**Issue by KillerXSF** [xulihang/ImageTrans-docs#31]
error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at anywheresoftware.b4a.keywords.Common.WaitFor(Common.java:1054)
	at org.xulihang.imagetrans.mt$ResumableSub_getMT.resume(mt.java:646)
	at org.xulihang.imagetrans.mt._getmt(mt.java:511)
	at org.xulihang.imagetrans.main$ResumableSub_showTM.resume(main.java:16121)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xulihang** [comment]
I need more details. What is the MT you choose? It may need your own API keys.

And how did this happen (exact steps)?

**Comment by KillerXSF** [comment]
I used ocrspace. The mentioned error pops up when i select a box to move. I close the pop up and move the box but for the next box the pops up again.

**Comment by KillerXSF** [comment]
Others - baidu, azure, google. They either show null or don't detect the text to translate. Ocrspace is the only one which works but translation is bad.

**Comment by xulihang** [comment]
OCRSPACE is not a machine translation service. You can see from the log that the problem is related to machine translation.

Tencent, Baidu, Niutrans and Google are the machine translation services that are usable without manual setup of API keys.

**Comment by xulihang** [comment]
You need to apply your own API keys if you want to use OCRs like Google. I've written about this in [FAQ](https://www.basiccat.org/imagetrans/faq/).

Baidu OCR should be able to work. I don't see why it can't work. Maybe your internet is restricted.

**Comment by xulihang** [comment]
If the Translation Assist Tab is switched to, the program will automatically call machine translation:
![image](https://user-images.githubusercontent.com/5462205/115148196-105a7d80-a091-11eb-8001-e75207d83146.png)

Go to preferences to set which MT to use:

![image](https://user-images.githubusercontent.com/5462205/115148250-4b5cb100-a091-11eb-80c5-402ad5bff15e.png)

**Comment by KillerXSF** [comment]
Where should I confirm from which machine translator was used?

**Comment by KillerXSF** [comment]
I disable microsoft machine translator from preferences. It solved the issue.

**Comment by xulihang** [comment]
See the notes in the translation candidate list:
![image](https://user-images.githubusercontent.com/5462205/115148325-a0002c00-a091-11eb-99f4-5b6dfff9934d.png)

**Comment by KillerXSF** [comment]
> You need to apply your own API keys if you want to use OCRs like Google. I've written about this in [FAQ](https://www.basiccat.org/imagetrans/faq/).
> 
> Baidu OCR should be able to work. I don't see why it can't work. Maybe your internet is restricted.

When baidu is enabled, the same error pops up. I have installed baidu and allowed access to internet. So internet restrictions shouldn't be the cause.

**Comment by xulihang** [comment]
There are two Baidu machine translation and Baidu OCR. They are different. It's strange that enabling Baidu MT will cause such a problem.

**Comment by KillerXSF** [comment]
![IMG_20210418_193719.jpg](https://user-images.githubusercontent.com/82061496/115148498-81903580-a07d-11eb-9b2b-f1f3e7a920a0.jpg)
These all are enabled when i get the error.

**Comment by xulihang** [comment]
Do not enable Google. This requires your personal API keys.

**Comment by KillerXSF** [comment]
On disabling baidu, no error is found.
I translating vertical traditional chinese to english. Which one would be best among these?

**Comment by xulihang** [comment]
Could you give me a sample image?

I think Baidu OCR is the best. But some steps may have to be done to make it to give the best result.

Like detect the text areas first and then OCR these areas separately. 

If the text's reading order is right-to-left, you have to set this in the project settings.

**Comment by xulihang** [comment]
Some offline Chinese OCRs have good result, like [ChineseOCR-lite](https://github.com/DayBreak-u/chineseocr_lite) and [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR). But they are not included by default.

**Comment by KillerXSF** [comment]
Baidu is not working even after i did everything as you said. Tencent,
niutrans give somewhat correct translation.

**Comment by xulihang** [comment]
Have you changed the default API settings? If so, you can unzip ImageTrans to restore its default settings.

![image](https://user-images.githubusercontent.com/5462205/115149242-caec7f00-a095-11eb-9e74-4712eca85a9a.png)

**Comment by xulihang** [comment]
Please note that ImageTrans is a computer-aided translation tool. If you know nothing about Chinese, it may be difficult for you to read these images relying solely on the raw OCR and machine translation results.

**Comment by KillerXSF** [comment]
Yes i understand that. I will do as you said. Thank you!
