### ISSUE TITLE
Cannot start a new project 

### ISSUE THREAD

**Issue by Error-rr** [xulihang/ImageTrans-docs#310]
Need some assistance, was able to create a new project after extracting for the first time. But now when I try I'm prompted with this error. Could someone help me resolve this? Thanks
![Error](https://user-images.githubusercontent.com/116232827/196827071-e3bfd5c0-f5a8-449f-b11c-9204e1698a3a.PNG)

**Comment by Error-rr** [comment]
I get the same error when trying to open files as well.

**Comment by xulihang** [comment]
I haven't encounterted this and cannot tell the reason.

**Comment by Error-rr** [comment]
Any way to resolve this or am I stuck with this error?

**Comment by xulihang** [comment]
Are you writing to network shares?

**Comment by Error-rr** [comment]
Was intended for personal use, also I apologies in advance cause this all new to me.

**Comment by Error-rr** [comment]
Figured it could be cause of Jave being outdated, so updated it. Downloaded a previous version to see if it fixes it, unfortunately prompts the same error. So, yeah currently it is unusable.

**Comment by xulihang** [comment]
It seems related to your environment. You can install a virtual machine and use ImageTrans in it.

**Comment by Error-rr** [comment]
Damn, is that the only way? Don't even know to set up a virtual machine.

**Comment by Error-rr** [comment]
Ok seems to be working again when launched within a Virtual Machine, any chance to get it running without that?

**Comment by xulihang** [comment]
I cannot figure out the reason since I cannot replicate the problem.

**Comment by Error-rr** [comment]
Ok did a system reset, the issue seems to have resolved. You can close this thread. Before you do is it possible to share these files elsewhere? Won't let me download them from baidu.

https://pan.baidu.com/s/1gJZyuntLetZEpFWI8XqkXA#list/path=%2F

**Comment by xulihang** [comment]
Files on baidu can be found on onedrive and github (check out the docs for links).
