### ISSUE TITLE
希望在排版模式下点击气泡内的文字时，可以让边框隐藏透明

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#314]
![2022-10-29_13-30-22](https://user-images.githubusercontent.com/24186777/198815607-73a2a990-7802-49bd-8502-39bd869ce063.jpg)
![2022-10-29_13-30-36](https://user-images.githubusercontent.com/24186777/198815608-48c63943-5fbd-410b-b224-616f63a8ae42.jpg)

因为边框的存在，很容易引起视错觉，感觉像是居中了，需要把排版模式取消才能看出来还是差了那么一点，有点难受
在字少框小的情况下，会容易看不出来是不是居中了
而在字多框挤的情况下，又容易发生能看出来没居中，但是不容易调整的情况，因为很容易把排版打乱
这样单个截图出来可能觉得明明很容易分辨，但实际内容多了做起来很容易看错的，20页的漫画会出现挺多这样的情况
希望可以做成点击气泡中间字体的时候可以隐藏边框进行拖动，点到边框线的时候才会调整边框

**Comment by xulihang** [comment]
改成这样吧，拖拽的时候隐藏边框

https://user-images.githubusercontent.com/5462205/198823245-fedb81d8-0223-4851-9c55-6692e328f9be.mp4

**Comment by xulihang** [comment]
这个行为应用在1.8.2了

**Comment by yahoozhu** [comment]
强啊
