### ISSUE TITLE
Clear target text deletes source and target text

### ISSUE THREAD

**Issue by crystalli999** [xulihang/ImageTrans-docs#317]
Hi, 
For clear text, under both 'text area operations' and 'current text area' deletes both source and target text for me no matter the option I select. I want to be able to just mass delete all the translated text.

**Comment by xulihang** [comment]
Related issue: https://github.com/xulihang/ImageTrans-docs/issues/170

You can use "Find and replace" to delete all translated text.

**Comment by xulihang** [comment]
I just tested "Clear text". It works fine.
