### ISSUE TITLE
mangaocr不能在win7运行？

### ISSUE THREAD

**Issue by floweraki** [xulihang/ImageTrans-docs#318]
mangaocr不能在win7运行？

**Comment by xulihang** [comment]
我没在win7上跑过，但应该是能用的

**Comment by floweraki** [comment]
搜了一下原因是说python3.9不支持win7，能用低版本打包一下程序吗

**Comment by xulihang** [comment]
下一个Python3.8，按照这里的步骤自己装一下吧：https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR

**Comment by xulihang** [comment]
打包的话，我有时间再打包一个

**Comment by xulihang** [comment]
已经重新打包了，体积也小了不少
