### ISSUE TITLE
[Suggestion] Input text size directly

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#32]
It would be nice if you could input the text size directly with numbers rather than needing to click the up/down arrows.
Applies to pretty much anywhere text size is specified.

**Comment by xulihang** [comment]
Okay. There is a problem that inputing the text size directly will not trigger the value changed event. Users have to click the arrows to save the result.

**Comment by lugia19** [comment]
I see. Is it a textField? It should have a FocusChanged event in that case. That could be an option.

**Comment by xulihang** [comment]
The [doc](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Spinner.html) says users have to enter to commit the edit.

> A Spinner has a TextField child component that is responsible for displaying and potentially changing the current value of the Spinner, which is called the editor. By default the Spinner is non-editable, but input can be accepted if the editable property is set to true. The Spinner editor stays in sync with the value factory by listening for changes to the value property of the value factory. If the user has changed the value displayed in the editor it is possible for the Spinner value to differ from that of the editor. To make sure the model has the same value as the editor, the user must commit the edit using the Enter key.

**Comment by lugia19** [comment]
Well, being able to commit the input with an enter is already an improvement.

I wonder if it would be possible to expose the textfield's focuschanged event and then edit the spinner's value to match when the focus is changed. I guess that also depends on what b4j/javaFX library is used.

**Comment by xulihang** [comment]
I found that we can use the keyboard's arrow keys to quickly adjust values. But if it is set as editable, this will not work.

**Comment by xulihang** [comment]
Enabled in v1.6.2.
