### ISSUE TITLE
Disabling Alt Gr / Disabling shortcuts 

### ISSUE THREAD

**Issue by Pawel-Lapinski** [xulihang/ImageTrans-docs#323]
Hello,

First of all - congrats for great stuff, helps me a lot with translation of comics.
Is there any way to disable shortcuts which are activated after pressing Alt Gr? The thing is that I traslate into Polish and when I edit my translation, I have to use Alt Gr with several letters to insert Polish letters (for example Alt Gr + z to obtain "ż"). Unfortunately, whenever I try to do it by pressing Alt Gr, it enables the top bar menu and kicks me off the text editing window.
In other software I'd just change this couple of shortcust in settings, but here I can't find any place to do that.
Any hints how to handle that situation?
Thx in advance.

**Comment by xulihang** [comment]
What is an Alt Gr key? My keyboard does not seem to have this key and there are no shortcuts registered with it in ImageTrans. It is the program's default behavior to trigger the functions of the menu by pressing ALT.

I can still use Chinese input method with the editing window by pressing ALT. I am not familiar with a Polish input method. Maybe you can use another input method.

**Comment by xulihang** [comment]
Could you record the screen so that I can see what happens?

**Comment by xulihang** [comment]
Maybe I can add an event filter to the menubar to disable the alt gr key event using the code here: https://github.com/sshahine/JFoenix/issues/854

**Comment by Pawel-Lapinski** [comment]
By [Alt Gr] I mean the left Alt button, next to the Space: https://en.wikipedia.org/wiki/AltGr_key
On the first JPG you can see me working on a text segment. On the second I've just pressed [Alt Gr + Z] and all the text is gone. 
It happens only with two combinations: [Alt Gr + Z] and [Alt Gr + A], with other letters there's no problem at all using Alt combination.
![Image_trans_1](https://user-images.githubusercontent.com/118264515/201932721-0b3e7d0c-cdfd-4713-a6d8-6f6c10016766.jpg)[Image_trans_2](https://user-images.githubusercontent.com/118264515/201932716-7ae7213a-9309-48b1-aff0-464af859c0a2.jpg)
![Image_trans_1](https://user-images.githubusercontent.com/118264515/201932721-0b3e7d0c-cdfd-4713-a6d8-6f6c10016766.jpg)

From my perspective the best way to bypass that would be indeed to disable entirely triggering the functions of the menu with ALT, I'd much appreciated such help!

**Comment by xulihang** [comment]
Does ALT Gr + Z trigger the "undo" shortcut (Ctrl+Alt+Z)? That explains why the selected textbox is no longer selected.

**Comment by xulihang** [comment]
If you only need to input the special letters, you can also use the AutoCorrect feature. You can set a special text in the project settings like "z#" and its replacement like "ż". After you input "z#", it will be replaced with "ż".

**Comment by Pawel-Lapinski** [comment]
Yeah, it seems it triggered Undo.
And the [Alt Gr + A] changes the already OCR-ed segemtn into some positioning details, like in this screenshot:
![image](https://user-images.githubusercontent.com/118264515/201943538-c457fd72-c787-438a-8bd2-fb936b5d56ab.png)
what shortcut would that be?

**Comment by Pawel-Lapinski** [comment]
I currently bypass the problem by using "float window" for typing translation - when it's in float mode it doesn't trigger the above-mentioned shortcuts with Alt Gr. But then again - when in float, I can't use the shortcuts for "Previous/Next Area" (Ctr+] / Ctr + [ ), which is pretty usefull.

**Comment by xulihang** [comment]
Here is the Ctrl+Alt+A shortcut which clears the text:

![image](https://user-images.githubusercontent.com/5462205/201950854-fb438a05-1b07-4a5a-bcea-5f223fe865c8.png)

**Comment by xulihang** [comment]
I will add a setting to customize the shortcuts. I had plans about this. It's just I haven't figured out how to do this.

**Comment by Pawel-Lapinski** [comment]
That would be really cool, thx a lot.

**Comment by xulihang** [comment]
I've added a shortcut preference setting in v1.8.4. You can disable or modify the shortcuts for menu items.


![image](https://user-images.githubusercontent.com/5462205/204080856-dc43ae0e-8549-46ff-8228-eeab8f60f759.png)
