### ISSUE TITLE
这是什么神奇的现象

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#334]
https://user-images.githubusercontent.com/30548000/208232998-e3fc5dc7-6010-4d95-9237-7bbcbf0ce87a.mp4

 漫画 打出来 直接变成 小X？
  我感觉是因为那个自动更正造成的？
  
![image](https://user-images.githubusercontent.com/30548000/208233030-16d7578b-8eee-4880-93da-7d5f997b95ff.png)
这个不是在预处理的是才运行的吗？？？在输入框手动输入也？？？这是bug吗

**Comment by lhj5426** [comment]
或者说是逻辑问题？

**Comment by xulihang** [comment]
是这样设计的，键入时也会替换。类似于Word的自动更正功能。

![image](https://user-images.githubusercontent.com/5462205/208234667-c2f8b231-abaa-44db-91ae-ac78c2db38d7.png)

**Comment by lhj5426** [comment]
> 是这样设计的，键入时也会替换。类似于Word的自动更正功能。
> 
> ![image](https://user-images.githubusercontent.com/5462205/208234667-c2f8b231-abaa-44db-91ae-ac78c2db38d7.png)

哦 好吧 了解了 突然想到 既然我已经 用预翻译机翻完了 那我删掉 自动更正也没有任何问题 这样就可以正常输入了
不算毛病  主要是 这些人体奇怪部位的词 在各种机器翻译里能翻译成各种奇怪的词 我为了少修正的操作
全部都丢到 自动替换里了 结果触发了这种神奇的效果  哈哈 谢谢解答

**Comment by xulihang** [comment]
那我加个选项吧，是否输入时也替换

**Comment by lhj5426** [comment]
哈哈那太行了 感谢 掐指一算 软件购入买快一年了从当初 感觉教了智商税找你退款
到现在 已经离不开了
时间过的真快 感谢老哥开发的软件 实现了懒得学日语的我的acg里C 的漫画的自由
带带啦啦 在网上发了50多部 7000页 哈哈 真的太棒了

**Comment by xulihang** [comment]
是否键入时替换的选项加在v1.8.5了

**Comment by lhj5426** [comment]
收到 这就去更新
