### ISSUE TITLE
Text does not appear correctly when generating PSD file

### ISSUE THREAD

**Issue by MrSvard** [xulihang/ImageTrans-docs#335]
The problem i have is that when i generate a PSD, the text appears with incorrect sizing. If i manually decrease the font size inside photoshop to something very small like 1, i then start to see the entire text., although at that point it's to small to read anyway.

How can i avoid this issue?

**Comment by MrSvard** [comment]
After having read through and tried what was suggested in those posts it didn't solve the problem. I did some additional experimenting. By saving the image at a lower dpi of 72, the sizing of the text appear more in line with how it should look like, even though it's still off. I've also tested with various images, most of which were at a dpi of 300 or above, it seems that the higher the dpi, the more inaccurate the sizing of the font becomes.

I'm currently downloading photoshop cc 2018 to see if that fixes the problem.

**Comment by MrSvard** [comment]
Got the exact same problem in the 2018 version of photoshop

**Comment by xulihang** [comment]
Could you send the images and the project file so that I can have a test?

**Comment by MrSvard** [comment]
Sure thing, I've attached 2 projects, one were I managed to get correct text sizing and the other where it's still not functioning. They have different image-sets. Since this is potentially a problem with the images themselves, hopefully you can tell what the crucial difference is between these images that makes one set work while the other will not. (also masked out any NSFW parts of these images:))
[Project Correct Text size.zip](https://github.com/xulihang/ImageTrans-docs/files/10270161/Project.Correct.Text.size.zip)
[Project Wrong Text size.zip](https://github.com/xulihang/ImageTrans-docs/files/10270163/Project.Wrong.Text.size.zip)

**Comment by xulihang** [comment]
Using Photoshop CS3 or CS6 and the [addLayers.jsx](https://github.com/xulihang/ImageTrans_PhotoshopScripts/blob/master/addLayers.jsx), I can get the correct text size.
![image](https://user-images.githubusercontent.com/5462205/208919681-3913a6ee-6ff1-45b1-88aa-15d44e4b5c9b.png)

**Comment by xulihang** [comment]
I forgot to update the scripts in ImageTrans. Please use the latest version here: https://github.com/xulihang/ImageTrans_PhotoshopScripts.

**Comment by MrSvard** [comment]
Interesting, I'm using the creative cloud version of photoshop (2022), maybe there is a difference between them? I'll get back to you when I've tested with CS6.

Cheers
