### ISSUE TITLE
mangaOCR option not available

### ISSUE THREAD

**Issue by JacksApps** [xulihang/ImageTrans-docs#337]
Hello, I cannot find the option to use mangaOCR.
I've downloaded the zip link you provided https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR and put the folder in the plugins folder.
Run the mangaOCR bat but don't see any option for manga OCR.

I have bought the software this week

![image](https://user-images.githubusercontent.com/32218643/209311623-176d879b-6d2f-4dc7-82e8-915b1945a1c6.png)

**Comment by xulihang** [comment]
Make sure that you've done the fourth step and restarted ImageTrans.

> Unzip the [plugin files](https://github.com/xulihang/ImageTrans-docs/files/7919869/manga-ocr-plugin.zip) in ImageTrans's plugins folder
