### ISSUE TITLE
Help me I can't download things on Baidu

### ISSUE THREAD

**Issue by sumipesumi** [xulihang/ImageTrans-docs#34]
![Capture](https://user-images.githubusercontent.com/83235429/116119719-5054dc80-a6f1-11eb-82c3-08162933cb76.JPG)

**Comment by xulihang** [comment]
You provide an inconsistent screenshot. 
You ask about Baidu but in the screenshot, you are using Google OCR.
I've included the API key of Baidu by default. You don't need to set it up.
But Google OCR requires your own API key.
