### ISSUE TITLE
文件已经可以自动读取了，谢谢，可是出现了新的问题，自动导入的文字没有像image trans里排好的顺序一样，载PS里是全部横排的

### ISSUE THREAD

**Issue by Steamfunheero** [xulihang/ImageTrans-docs#340]
![1](https://user-images.githubusercontent.com/121746506/210164429-8354509b-45b9-4921-b140-e6ca89baed36.png)
![2](https://user-images.githubusercontent.com/121746506/210164433-b0026551-92db-4f76-a906-7f666c3c705a.png)
![3](https://user-images.githubusercontent.com/121746506/210164434-d87f6a2d-c70e-4a61-a50a-d932b5831207.png)
![4](https://user-images.githubusercontent.com/121746506/210164435-af5d0041-576d-46f7-a666-d862d7db32a4.png)
![5](https://user-images.githubusercontent.com/121746506/210164436-de50c9d0-30a4-4eea-b74f-52d188640d7e.png)

**Comment by xulihang** [comment]
导出时不要用选点文字。横排导出时不会添加换行信息，如果用点文字需要自己换行。

**Comment by Steamfunheero** [comment]
![c1762bac20e985b9a3821f4f425e605](https://user-images.githubusercontent.com/121746506/210165289-995158a4-9e3d-429c-b282-1e54f2839189.png)
这次是没有勾选点文字后的，请问这是不是PS的设置有关

**Comment by Steamfunheero** [comment]
自动导入后第一界面是这样的
![05fcacf4fb4f188f1827764d2131ae7](https://user-images.githubusercontent.com/121746506/210165335-c15ab539-a9a6-4e55-a3a3-1f609a3348ef.png)
![1af2b76993ceb803a16aa0f0215a5da](https://user-images.githubusercontent.com/121746506/210165336-463b07ce-cc9b-4fc8-83ba-6698e2566fe9.png)
之前那些图片是我在更改字号后得到的

**Comment by Steamfunheero** [comment]
上图指的是“制服”那个看起来没有文字那个区域

**Comment by Steamfunheero** [comment]
![68714ab407aaa163fa04bbdb1a6d13a](https://user-images.githubusercontent.com/121746506/210165403-a38af104-fa35-485f-b2d0-d6b875b1e858.png)
这是在image trans 上的设置

**Comment by xulihang** [comment]
Photoshop的字体名字可能没有设置正确，需要按照视频里新建一个文本框再用readFont那个脚本查看一下。

关于字体大小，你的Photoshop是什么版本的？我用Photoshop CS6， 2018是没有问题的
