### ISSUE TITLE
Check discussions, I posted a fix for webp files

### ISSUE THREAD

**Issue by crownaintanoob** [xulihang/ImageTrans-docs#343]
**I posted a fix for the webp files in Discussions**
https://github.com/xulihang/ImageTrans-docs/discussions/342

**Comment by xulihang** [comment]
Nice workground. ImageTrans has the ability to convert webp to jpeg. It's just that it is only checking the extension. I will improve this by checking the real format using methods like this one: http://jubin.tech/articles/2018/12/05/Detect-image-format-using-java.html

**Comment by crownaintanoob** [comment]
> Nice workground. ImageTrans has the ability to convert webp to jpeg. It's just that it is only checking the extension. I will improve this by checking the real format using methods like this one: http://jubin.tech/articles/2018/12/05/Detect-image-format-using-java.html

Alright!
