### ISSUE TITLE
I can't load tesseract-ocr files

### ISSUE THREAD

**Issue by Drozaza101** [xulihang/ImageTrans-docs#344]
I can't load the tesseract-ocr file, and do you know where I can find the language data file?

**Comment by Drozaza101** [comment]
To be honest, I don't know how to add another language.

**Comment by Drozaza101** [comment]
You mean this? https://pan.baidu.com/s/1gJZyuntLetZEpFWI8XqkXA#list/path=%2F

i tried i can't apply Baidu.

**Comment by xulihang** [comment]
The link above: https://github.com/UB-Mannheim/tesseract/wiki#tesseract-installer-for-windows

**Comment by Drozaza101** [comment]
It didn't work. Am I doing something wrong?

![1](https://user-images.githubusercontent.com/121895152/210832927-8b22688f-7e51-4e9b-b988-4920fed2663e.png)
![2](https://user-images.githubusercontent.com/121895152/210832942-709c1717-a7cc-4502-b38e-34679e53d0fa.png)
![3](https://user-images.githubusercontent.com/121895152/210832941-8e94a02d-f96e-4861-aaf1-41d838f73ce1.png)
![4](https://user-images.githubusercontent.com/121895152/210832935-80504223-7f90-4220-88e9-59f3950170e2.png)
![5](https://user-images.githubusercontent.com/121895152/210832934-3a379d72-c133-40ae-ac6f-d65ea0593a96.png)

**Comment by xulihang** [comment]
The project's language pair setting is mainly used by machine translation services while every OCR has its own language selection.

Tesseract's languages list  is defined in `lang.conf`. You can modify it to add other language models like the following:

```diff
+ Arabic
+ ara
英语
eng
简体中文
chi_sim
简体中文_竖
chi_sim_vert
繁体中文
chi_tra
日语
jpn
日语_竖
jpn_vert
韩语
kor
法语
fra
西班牙语
spa
葡萄牙语
por
俄语
rus
意大利语
ita
德语
deu
阿拉伯语
ara
藏语
bod
自动检测
auto
```

**Comment by Drozaza101** [comment]
i have tried it Unfortunately, I thought I must have done something wrong.


![Screenshot 2023-01-06 175535](https://user-images.githubusercontent.com/121895152/211062259-9535d6dc-c913-4ce1-83b6-80d8eeaa2914.png)

![Screenshot 2023-01-06 175801](https://user-images.githubusercontent.com/121895152/211062591-98351ecd-9aa8-42de-be65-f22bbbb46585.png)

I wrote it down in langcodes.txt


![Screenshot 2023-01-06 181513](https://user-images.githubusercontent.com/121895152/211063269-69bdaf6a-56e7-4da4-a7da-750c5b9fb4a0.png)


![Screenshot 2023-01-06 175900](https://user-images.githubusercontent.com/121895152/211062714-a9084e9b-8796-4ef0-8a9c-e3c538520b08.png)

![Screenshot 2023-01-06 175923](https://user-images.githubusercontent.com/121895152/211062747-0dfcfd35-972a-420a-b139-0a2deefdb45e.png)
![Screenshot 2023-01-06 180255](https://user-images.githubusercontent.com/121895152/211062790-69514ae1-5bca-40ff-81af-544356df35b7.png)

![Screenshot 2023-01-06 180418](https://user-images.githubusercontent.com/121895152/211062910-ac708251-602b-438f-80b7-362de92d5548.png)

**Comment by xulihang** [comment]
What do you want to achieve? If you need to translate English comics to Thai, you don't need to use the Thai OCR model. The correct project language code of Thai is th.

**Comment by Drozaza101** [comment]
Can you tell me in detail? What do I have to do? I have tried what I think is correct but it doesn't work.

**Comment by xulihang** [comment]
What image do you need to translate? You can send an example here.

**Comment by Drozaza101** [comment]
It's Manhwa
![p2](https://user-images.githubusercontent.com/121895152/211153261-b676d115-c3c6-4d69-9646-745544658c43.jpg)

**Comment by xulihang** [comment]
Then you don't need to modify `lang.conf` to use the Thai tesseract OCR model.

You just need to set the language pair in project settings to en->th. Then select an OCR engine like baidu with its language as English for recognizing the text.
![image](https://user-images.githubusercontent.com/5462205/211153575-9ec566af-2b22-4af8-9dc4-92d3f9650b34.png)

![image](https://user-images.githubusercontent.com/5462205/211153567-898c53b5-62d5-494b-9ae8-8cda7ea701a1.png)

**Comment by Drozaza101** [comment]
Do I need to delete what I wrote in lang.conf?

**Comment by Drozaza101** [comment]
I can do it
thank you
