### ISSUE TITLE
185 如何恢复到184这种 样子

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#346]
https://user-images.githubusercontent.com/30548000/212306783-e4601eb0-0367-475e-a40c-5866277906f9.mp4

这是在搞什么。。。。  文本框原来覆盖在图片上 不会因为拖拉而 消失
185 刚续完费用上 一用 嗯 不对 嗯 确实不对
开发者老哥185 如何恢复184的。。。 原来这种文本框 在图片之上 而不会因为拖拉 而消失？

**Comment by lhj5426** [comment]
我在更新里也没看到提到这项变化啊？
![image](https://user-images.githubusercontent.com/30548000/212307363-3a5d70e5-d57a-48d6-8421-b1c38371c50c.png)

**Comment by lhj5426** [comment]
这个变化是处于什么考量呢？

**Comment by xulihang** [comment]
见这个issue：https://github.com/xulihang/ImageTrans-docs/issues/314

**Comment by lhj5426** [comment]
> 见这个issue：[#314.visited_data{display: block}首次: 29 10月, 2022 | 下午7:37:15最后:  29 10月, 2022 | 下午7:37:15 次数: 1](https://github.com/xulihang/ImageTrans-docs/issues/314)

这个我发现了 拖动文字的时候 框没了方便定位 但是 跟这个。。拖动 编辑区域拓展图片 有什么关联？

**Comment by xulihang** [comment]
噢，我没看视频，以为拖动是拖动文本框。视频里有什么问题吗，我没看出来

**Comment by lhj5426** [comment]
> 噢，我没看_视频_，以为拖动是拖动文本框。_视频_里有什么问题吗，我没看出来

拓展编辑区域 图片被扩展了  如果扩大编辑区域 图片被压缩了 184 编辑区域是建立在图片之上的 无论怎么拖拽编辑区域 图片不会被压缩

**Comment by xulihang** [comment]
相关代码没有改动，1.8.4和1.8.5的表现应该是一样的

**Comment by lhj5426** [comment]
就好像变成2个箱子   |图片|编辑区域| 拖动中间往左图片被推走 拖动中间往右 编辑区域被推走  
那是BUG ？

**Comment by xulihang** [comment]
应该是第二张图横向的滚动条不在最左边的关系

**Comment by lhj5426** [comment]
> 应该是第二张图横向的滚动条不在最左边的关系


https://user-images.githubusercontent.com/30548000/212310364-46cc45c4-8246-4546-bfe0-75a0a1fa7c97.mp4

还得是开发者老哥您 一眼就看出问题所在 还真是 滚动条在左边的时候 是正常的 横向滚动条到右边的话就变成推箱子了
