### ISSUE TITLE
Width (0) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by crownaintanoob** [xulihang/ImageTrans-docs#347]
**I get this error when translating a webp image using the server:**
_(IllegalArgumentException) java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
run(Map) Not initialized_

![image](https://user-images.githubusercontent.com/70343800/212523595-65d29456-9d5b-487d-830b-78510c9b21d8.png)

**Comment by xulihang** [comment]
Could you post the URL so that I can have a test?

**Comment by crownaintanoob** [comment]
> Could you post the URL so that I can have a test?

https://s1.baozimh.com/scomic/xianwudizun-erciyuandongman/0/340-l31b/1.jpg

**Comment by xulihang** [comment]
Which version are you using? I don't have a problem using v1.8.5.

**Comment by xulihang** [comment]
The image uses JPEG, If you are using your way of converting webp images, it may go wrong. Use v1.8.5 which can handle both webp and jpeg files,
