### ISSUE TITLE
批处理问题

### ISSUE THREAD

**Issue by kikonoy** [xulihang/ImageTrans-docs#350]
在每一次的批处理一键翻译完漫画后软件都会未响应，翻译下一个文件又要重新打开

**Comment by xulihang** [comment]
一键翻译是翻译项目的所有图片吗？没碰到过不响应的问题，把项目和图片发我测一下吧

**Comment by HuangJune** [comment]
比方说我导入一个漫画的文件夹，这个大文件夹里又包含了漫画的章节数这种小文件夹，这时候一键翻译这几百张图片导出后软件就未响应了。但是如果只翻译某一章节数这种小文件夹里的十几张图片就没有问题。

**Comment by xulihang** [comment]
那我测这个要花很多时间啊，因为一键翻译涉及的步骤太多了。未响应是哪个阶段未响应的，是机器翻译好后 生成成品图阶段吗？可以执行批处理里的生成所有图片的成品图，看看会不会未响应。我估计是抹除文字这个阶段耗费了比较多的资源

**Comment by xulihang** [comment]
图片很多时可以用自定义工作流，分布执行操作，保证每个操作没问题。

**Comment by HuangJune** [comment]
生成所有图片的成品图还有所有图片的掩膜和去文字图这两个都没有问题，未响应的阶段出在机器翻译好后，生成完了成品图的阶段。

**Comment by HuangJune** [comment]
并且在我未勾选”精确抹除文字‘’这个选项，操作完后一样出现了未响应。其实这个也不影响我的使用，强迫症看不惯罢了。

**Comment by xulihang** [comment]
等我有空了看看能不能重现这个问题

**Comment by yogimator** [comment]
> 等我有空了看看能不能重现这个问题

对于100张图片的批处理 能不能先处理50个  第二次再处理后50个？  目前的批处理似乎每次都是从第一次开始

**Comment by xulihang** [comment]
> > 等我有空了看看能不能重现这个问题
> 
> 对于100张图片的批处理 能不能先处理50个 第二次再处理后50个？ 目前的批处理似乎每次都是从第一次开始

https://github.com/xulihang/ImageTrans-docs/issues/59#issuecomment-860326856

可以使用已翻译图片管理器，标记为已翻译的处理时就跳过
