### ISSUE TITLE
百度翻译api问题

### ISSUE THREAD

**Issue by HuangJune** [xulihang/ImageTrans-docs#351]
为什么我填写了自己的百度翻译的api，并且使用字符数也未达到我的每月上限，翻译到一定字数后再使用百度的机器翻译就报错了

**Comment by xulihang** [comment]
个人版每月5万字数，并且限制一秒一次请求，注意翻译时时间间隔的设置

**Comment by xulihang** [comment]
还有一种可能是百度没提供很好的批量句子翻译功能，我是通过按句子拼接段落的方式一次请求翻译多个文字区域，可能得到的翻译和原文没对应好。可以在偏好设置里把这个关了，改成按文字区域进行翻译。

目前支持一个请求翻译多个句子的只有百度和彩云小译，后者这个功能更完善一点。

**Comment by HuangJune** [comment]
好的谢谢
