### ISSUE TITLE
How to update our ImageTrans version ?

### ISSUE THREAD

**Issue by crownaintanoob** [xulihang/ImageTrans-docs#353]
**How do we update ImageTrans to the latest version ?**

**Comment by xulihang** [comment]
You can find the latest version in the onedrive link. Then you can overwrite the existing one. If you need to keep the preferences, keep the Preferences.conf.

**Comment by crownaintanoob** [comment]
> You can find the latest version in the onedrive link. Then you can overwrite the existing one. If you need to keep the preferences, keep the `Preferences.conf`.

Thanks, the manhua website works when using the latest version of ImageTrans
