### ISSUE TITLE
大大，问一下，输出图片的压图有点严重，把输出图片的质量拉到100了还是没用

### ISSUE THREAD

**Issue by zjl1938685954** [xulihang/ImageTrans-docs#356]
原图基本上都是2mb到3mb左右，但输出图片只有几百K
可以通过什么方法解决？

**Comment by xulihang** [comment]
显示比例是100%了吗？目前输出图像其实是对当前内容的截图。如果需要高质量文件，可以导出为PSD。

**Comment by zjl1938685954** [comment]
大大，导出psd后，我在输出文件夹只找到了out. txt和params.txt，并没有找到用于ps的psd文件，psd文件去哪找？



---原始邮件---
发件人: "Lihang ***@***.***&gt;
发送时间: 2023年1月29日(周日) 下午4:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xulihang/ImageTrans-docs] 大大，问一下，输出图片的压图有点严重，把输出图片的质量拉到100了还是没用 (Issue #356)




 
显示比例是100%了吗？目前输出图像其实是对当前内容的截图。如果需要高质量文件，可以导出为PSD。

**Comment by zjl1938685954** [comment]
大佬，我又回去了看了imagetrans的快速入门，发现我电脑少了ps，装上了，问题解决了



---原始邮件---
发件人: "Lihang ***@***.***&gt;
发送时间: 2023年1月29日(周日) 下午4:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xulihang/ImageTrans-docs] 大大，问一下，输出图片的压图有点严重，把输出图片的质量拉到100了还是没用 (Issue #356)




 
显示比例是100%了吗？目前输出图像其实是对当前内容的截图。如果需要高质量文件，可以导出为PSD。
