### ISSUE TITLE
错误: 缺少 JavaFX 运行时组件, 需要使用该组件来运行此应用程序

### ISSUE THREAD

**Issue by linkstree** [xulihang/ImageTrans-docs#36]
java -jar ImageTrans.jar 这个命令报错

**Comment by linkstree** [comment]
我是付费用户,麻烦尽快解决

**Comment by xulihang** [comment]
需要下载完整版：https://github.com/bell-sw/Liberica/releases/download/8u275%2B1/bellsoft-jdk8u275+1-windows-amd64-full.msi

**Comment by xulihang** [comment]
我建议下载网盘里的完整版，已经打包了OpenCV和JRE了

**Comment by linkstree** [comment]
搞定
