### ISSUE TITLE
能否批量删除翻译，或者让所有翻译的原文对应的译文进行配对。

### ISSUE THREAD

**Issue by sophiet97** [xulihang/ImageTrans-docs#363]
现在重新进行翻译会覆盖不了之前的翻译，也无法删除所有翻译。
还有就是能否指定某个原文单词翻译成指定的译文单词？然后批量重新翻译更改过的气泡？

最后是正则能否支持环视？

**Comment by xulihang** [comment]
>删除所有翻译

可以看这个issue：https://github.com/xulihang/ImageTrans-docs/issues/170

> 指定某个原文单词翻译成指定的译文单词

这个可以试着在机器翻译前把单词替换成译文，不知道效果好不好，好的话可以加一个自动更正设置。

> 正则能否支持环视

这个要实现什么效果，我没怎么用过

**Comment by lhj5426** [comment]
其实只要知道原词机翻后是什么 直接替换就行了
![image](https://user-images.githubusercontent.com/30548000/219785573-1ebdd766-0321-4c28-87b1-4ab571c93b34.png)

**Comment by lhj5426** [comment]
还有可以把原词 先用自动更正变成一个 不会被机器翻译识别并且翻译的词
然后再 用机器翻译替换成你 你要的词
虽然有点绕但是可以实现

**Comment by lhj5426** [comment]
不过确实如 动图所示那样
每次必须删除 原文 重新OCR 
或者删除译文重新翻译才能看到效果
要是可以 直接点重新ocr 就自动重新OCR 并替换
和重新机器翻译 不需要删除原文也会重新跑一遍 翻译并替换
体验上能更好一点
