### ISSUE TITLE
如何批量关闭 √启动本地样式

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#364]
事情是这个样子的
我在用软件的最新版 重置 1年前用软件初期版本制作的漫画
然后因为1年前 我刚接触软件 没有很了解 倒是 当时制作漫画字幕的时候 没有勾选掉 左边的 自动调整字体大小
而且当时字体也是用过拖拽调整而不是用过 字号调整的
![image](https://user-images.githubusercontent.com/30548000/220250795-790bfd1f-de66-42c3-969e-438392d30474.png)

导致现在 要重置的漫画 的每一个气泡 都是 被够的选了  √启动本地样式
这个选项 如图  这个被勾选了之后 无论在下方的 字体框里选择何种字体样式 都不会改版 本样式
因为 一本漫画 300 页 当时制作的时候每一页的气泡都是 在没有关闭  自动调整字体大小 的情况下拖拽调整的
导致300页漫画 的所有气泡全部被  √启动本地样式  
一个一个气泡取消勾选 简直 是噩梦 虽然可以用宏 来自动执行多步骤 一键取消 本地样式
但是也是要每个气泡按一次 所以想发帖 问一下开发者老哥 设计的时候 有没有设计 一键 批量取消
本地样式的功能 
![image](https://user-images.githubusercontent.com/30548000/220251333-2e3fc0ff-8656-4e6b-8053-6d3c111eca7a.png)
因为 我在软件里 好像没有找到相关的操作

**Comment by lhj5426** [comment]
> 可以用notepad++之类工具直接把本地样式的数据删除。
> 
> 正则表达式：
> 
> ```
> "localStyle.*?},
> ```
> 
> 截图：
> 
> ![image](https://user-images.githubusercontent.com/5462205/220260781-a2d1c83f-6c57-4d57-9bee-6be43f2d1cd3.png)

哦 就是直接打开
![image](https://user-images.githubusercontent.com/30548000/220263706-618e20b6-e15b-4e2b-991e-66e8a219c6c0.png)
这个项目文件修改然后保存吗

**Comment by lhj5426** [comment]
我先备份一下文件然后试试  感谢

**Comment by xulihang** [comment]
对的

**Comment by lhj5426** [comment]
非常感谢 太好用了 记笔记上
