### ISSUE TITLE
如何从ps读取字体？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#365]
https://user-images.githubusercontent.com/30548000/221058170-82f5f463-c583-4bca-9cc9-aed690e4e4e5.mp4

按照 操作说明 好像 无法获取到字体 
我的PS版本
![image](https://user-images.githubusercontent.com/30548000/221058328-5d01b436-6e7e-4b87-a09b-f3db73284fc7.png)
系统 
![image](https://user-images.githubusercontent.com/30548000/221058359-9e8b9c34-9a0f-4e83-83fe-5a6e0c23ec77.png)
是哪里设置错了吗？

**Comment by lhj5426** [comment]
因为如果不导入字体的话
就算我用的字体里ps有 通过PSD导入完 默认全部都是这个字体
![image](https://user-images.githubusercontent.com/30548000/221059191-2fc73a25-4b1f-4bb0-ab50-b0e006060719.png)

而且不是软件里设置的字体
我就在想 是不是因为没有从ps 导入字体才导致导出的PSD 导入PS 里字体全都是这个

**Comment by lhj5426** [comment]
而我实际上用的字体是这个
![image](https://user-images.githubusercontent.com/30548000/221059434-237dcf93-0c4f-4191-9d44-293072ae349e.png)
![image](https://user-images.githubusercontent.com/30548000/221059576-a3618d35-51ec-4484-831a-066418c49c20.png)

**Comment by xulihang** [comment]
换Photoshop CS3试一下readFont.jsx这个脚本

**Comment by lhj5426** [comment]
> 换Photoshop CS3试一下readFont.jsx这个脚本

我去下一个 ps CS3 是200几
![image](https://user-images.githubusercontent.com/30548000/221070646-f2c2b33a-6b6c-499d-a1c3-6705b8493982.png)
我电脑上现在装的是2022 2023

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/221072819-84c61a00-5fca-44fa-863e-316f87863b16.mp4

现在是这样

**Comment by xulihang** [comment]
只保留需要的那个字体的文本框，把获得的字体名复制到字体名称那栏。

另外如果有本地样式，需要单独更新一下。

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/221074128-c8ca91cb-510b-468e-b6a0-76c99bceaf51.mp4

是这样操作吗

**Comment by xulihang** [comment]
PS字体名设置后还需要单独设置在软件里显示的字体。从PS读取那个按钮需要正确安装Photoshop并注册com，不然没有效果。

**Comment by lhj5426** [comment]
> PS字体名设置后还需要单独设置在软件里显示的字体。从PS读取那个按钮需要正确安装Photoshop并注册com，不然没有效果。

我下载的PS 就是直接一个安装包
![image](https://user-images.githubusercontent.com/30548000/221100691-1e452cfc-7da1-42ea-b749-758f4efd7497.png)
 我也不知道算不算正确安装
 
![image](https://user-images.githubusercontent.com/30548000/221100854-6a1d1724-95dc-4b0c-b793-187b12762d8a.png)
反正在卸载程序可以正确显示出来 但是 COM 要怎么注册呢

**Comment by xulihang** [comment]
安装正版Photoshop一般能正确注册com。非正版的处理方法我也不是很清楚、

**Comment by lhj5426** [comment]
我是不是搞错了

我遇到的问题是 

软件里设置的字体 通过psd 导出到PS里 ps 的文字图层里所用的字体 不是 软件里设置的字体样式

这个跟读取PS 字体好像是相反的 应该是PS 读取 软件里的字体？

**Comment by xulihang** [comment]
从PS读取的字体名是PS专用的，软件里显示的字体怎么设都不影响导出的字体

**Comment by lhj5426** [comment]
> 从PS读取的字体名是PS专用的，软件里显示的字体怎么设都不影响导出的字体

所以说  【导出的PSD的文件】里的【字体】 就只能是默认的？

就算我成功的 从PS 里读取了 【字体】  然后 【导出PSD】  用PS 打开【PSD】 里的【字体】 还是【默认】的 ？

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/221121970-bb81e00f-8cd8-4def-8aa3-883bea44711a.png)
我觉得我应该把问题重新描述一下
是这样的 如图 
1 是软件里的字体
2是导出的pSD
3 PS打开PSD 之后文字块 显示的字体
我的问题是 如何让 导出的PSD 用ps打开时候  文字块 是 和软件里是相同的字体
这样就只需要调整位置 不需要再 挨个文字块 调整字体了

我绝对我是不是进入了一个误区 没有走出来

所以我重新描述了一下我的问题 对不起耽误您的时间了

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/221138771-eb23a62f-93de-4b80-b416-b583967f24c4.png)
首选对不起
其次非常感谢~~！！！！
