### ISSUE TITLE
Output to a PDF file

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#366]
Using [PDFBOX](https://pdfbox.apache.org/), we can create a PDF file with images. It cannot embed text layers, but the commercial SDKs are too expensive.

**Comment by lhj5426** [comment]
加油 现在的方法是 


先导出PSD 的 out.txt 
然后用 任意的 文本工具打开 我是用的
EmEditor 
然后输入 要单页提取 

https://user-images.githubusercontent.com/30548000/221355948-d52699d9-3f64-40ff-9cd9-13803d414a21.mp4

的 页面图片名
 然后全选复制 新建文档 改名 out.txt  保存 用ps 打开 就只针对某一页生成到psd文件了
 
 虽然麻烦 但是也不是不能生成 单页PSD

**Comment by lhj5426** [comment]
等等  ....不对  乌龙了... 我重新读了下标题 是....PDF 不是...PSD。。。。(#`O′) 好囧

**Comment by xulihang** [comment]
选择生成导出哪些图片的数据用于生成PSD，是应该加一个设置

**Comment by xulihang** [comment]
Added in v1.9.3. I found that Apache PDFBOX can add text lines, but it is not easy to wrap the text. So I just embed the images.
