### ISSUE TITLE
只支持漫画里面文案修改吗？支持宣传报这类文案修改吗，比如下面链接

### ISSUE THREAD

**Issue by 865240856** [xulihang/ImageTrans-docs#368]
![301677495811_ pic](https://user-images.githubusercontent.com/13608032/221547336-60c5a888-6223-44ea-83d0-23b2d2a6f7f3.jpg)

**Comment by xulihang** [comment]
可以的，比如这个视频里演示的：【ImageTrans漫画翻译教程——文字区域检测与译文回填-哔哩哔哩】 https://b23.tv/ivIeTty



徐力航 Tony Xu
邮箱/Mail： ***@***.***
电话/Phone：+86 18861822336
博客/Blog：blog.xulihang.me






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月27日 19:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [xulihang/ImageTrans-docs] 只支持漫画里面文案修改吗？支持宣传报这类文案修改吗，比如下面链接 (Issue #368) |

**Comment by xulihang** [comment]
可以的，比如这个视频里演示的：【ImageTrans漫画翻译教程——文字区域检测与译文回填-哔哩哔哩】 https://b23.tv/ivIeTty
