### ISSUE TITLE
个人版和企业版有啥功能区别吗

### ISSUE THREAD

**Issue by 865240856** [xulihang/ImageTrans-docs#369]

**Comment by xulihang** [comment]
你要是用于商业目的，需要购买企业版。另外企业版可以在50台设备上运行而个人版只有3台。

**Comment by 865240856** [comment]
> 你要是用于商业目的，需要购买企业版。另外企业版可以在50台设备上运行而个人版只有3台。

可以试用一下吗

**Comment by xulihang** [comment]
试用版是不提供的，可以把要翻的图片发过来我试一下

**Comment by lhj5426** [comment]
想了解功能的话 
我之前做了一个 我自己认为 
也是我自己常用的 软件一些功能的教程
可以看一下
https://e-hentai.org/g/2466821/3480ab0e09/

**Comment by adogandtina** [comment]
xulihang
有購買 ImageTrans 但開啟程式 輸入訂單號碼 以及郵箱號碼卻顯示未購買
怎麼解決?

**Comment by xulihang** [comment]
@adogandtina 不要询问无关的问题。产品购买问题可以发邮件到admin@basiccat.org

**Comment by adogandtina** [comment]
@xulihang 
之前有發郵件(用Gmail)
可是卻顯示郵件被封鎖
不得已才來這邊問
不好意思占用版面
550 Mail content denied
出错原因：该邮件内容涉嫌大量群发，并且被多数用户投诉为垃圾邮件。
对于具有群发性质的邮件，如果出现用户普遍表示反感或集中投诉的情况，腾讯邮箱将禁止类似此邮件内容继续发送。
改善建议：如果您是此群发邮件的管理员，请停止群发对用户造成骚扰的广告及推广类邮件。
如果您是个人邮箱用户，请向您的电子邮件提供商报告此情况。
