### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by animanl00ver** [xulihang/ImageTrans-docs#37]
I need help with step by step instruction to install imagetran i purchase the program and tried to floow the steps but i dont knnow what im doing. wrong  
i have a mac os big sur 11.3v 
would appreciate the help i dont know wat im doing.

**Comment by xulihang** [comment]
Download the dmg file and drag ImageTrans to the application folder.

If it says the app is damaged, you could try this command in terminal:

```
sudo xattr -rd com.apple.quarantine /Applications/ImageTrans.app
```

**Comment by animanl00ver** [comment]
how do i use this command where do i find the terminal?

**Comment by animanl00ver** [comment]
How do I do that?

**Comment by xulihang** [comment]
Please google  `mac terminal`

**Comment by animanl00ver** [comment]
I was able to install image trans but the chrome extension is not working im following the steps and noting is happening

**Comment by xulihang** [comment]
Get familiar with ImageTrans first then try the extension. Make sure you've done the steps in https://github.com/xulihang/ImageTrans_chrome_extension.

**Comment by animanl00ver** [comment]
I did follow the steps, what to you mean when you say download  ImageTrans_wsServer.ja <https://github.com/xulihang/ImageTrans_wsServer/releases/download/builds/ImageTrans_wsServer.jar>r and put it with ImageTrans I downloaded it but what do you mean by put it with imagetrans

> Download ImageTrans_wsServer.jar <https://github.com/xulihang/ImageTrans_wsServer/releases/download/builds/ImageTrans_wsServer.jar> and put it with ImageTrans.
>

**Comment by xulihang** [comment]
I see. For mac, you have to put the jar under this path: `/Application/ImageTrans.app/Contents/Java`

**Comment by xulihang** [comment]
Run this command in Terminal:

```
open /Applications/ImageTrans.app/Contents/Java
```

This will open the folder with Finder. Then, you can copy the jar to the folder.

**Comment by animanl00ver** [comment]
I was able to copy it to the folder. and followed the extension steps but i still get this error
Failed to connect to ImageTrans server

**Comment by animanl00ver** [comment]
where do i find repository that i need to download and install the extension through More Tools->Extensions->Load unpacked

**Comment by xulihang** [comment]
Make sure you've connected ImageTrans to the server:

![image](https://user-images.githubusercontent.com/5462205/116767503-12461880-aa63-11eb-9bed-3c8b46dc22a3.png)

**Comment by xulihang** [comment]
>  find repository

The link is the repo. But you don't need to do this now if you've installed it through Chrome App Store.

**Comment by animanl00ver** [comment]
yes i did that  but its still not working does the program work with any website

**Comment by xulihang** [comment]
Restart the browser and try again.

It works with any website. Basically, it downloads the image you hover your mouse on and runs the translation.

**Comment by animanl00ver** [comment]
so restarted the browser and press translate but it shows like its doing something because the blue ball appears but noting happend to the website

**Comment by xulihang** [comment]
Switch to ImageTrans. See if the image is downloaded, OCRed and translated.

**Comment by xulihang** [comment]
You can try this comic to see if it works: https://ac.qq.com/ComicView/index/id/547921/cid/1

**Comment by animanl00ver** [comment]
It loaded it to the image trans but it didn’t translate anything the bubbles were empty and it did the same for the website I try replicating it in another website and it just show the blue ball and noting happen this is the website https://newtoki95.com/webtoon/12575534?toon=BL%2FGL
<img width="1022" alt="Screen Shot 2021-05-01 at 5 41 06 PM" src="https://user-images.githubusercontent.com/83406722/116795643-805eff80-aaa4-11eb-82ac-f11e7e451e29.png">

**Comment by xulihang** [comment]
For the Chinese comic, you have to choose a proper OCR engine and language first.

**Comment by xulihang** [comment]
Here is how I translate the webtoon:

https://user-images.githubusercontent.com/5462205/116799303-ba72e480-ab2a-11eb-923d-fda81e0d480d.mp4

**Comment by xulihang** [comment]
Steps:

1. Set up a suitable grow width for the heuristic text detection
2. Adjust the view percent to 100%
3. Choose Baidu as the OCR engine and Korean as the language
4. Start the server. Choose Baidu as the machine translation engine.
5. In Chrome, translate the image.

**Comment by animanl00ver** [comment]
i did the same thing and im still getting the same issue 



https://user-images.githubusercontent.com/83406722/116800543-19efd680-aad0-11eb-9d61-0c764343638e.mov

**Comment by animanl00ver** [comment]
i tried it again and made sure i was connected and it just showed the blue ball and thats it 



https://user-images.githubusercontent.com/83406722/116800882-e6627b80-aad2-11eb-81f7-2efd834aeb90.mov

**Comment by xulihang** [comment]
Do not close the server window. This will kill the server. Also use shortcut to call the pop up. Or the extension may not be able to find the image which should be under the mouse.

**Comment by xulihang** [comment]
I clearly write this in the guide:

>In Chrome, move the mouse over the picture which needs to be translated. Press CTRL+SHIFT+F （CTRL+SHIFT+V on mac） to call the popup and press TAB to alter the buttons. Press Enter to run the desired action like translating the image or getting the image's src.

**Comment by xulihang** [comment]
Shutdown the server if you've started before. Do not open two server windows.

**Comment by animanl00ver** [comment]
its started translating but Im getting translating error 
<img width="1045" alt="Screen Shot 2021-05-02 at 7 42 06 AM" src="https://user-images.githubusercontent.com/83406722/116811938-00737c80-ab1a-11eb-96b9-c80b8f070373.png">

**Comment by animanl00ver** [comment]
<img width="774" alt="Screen Shot 2021-05-02 at 7 45 57 AM" src="https://user-images.githubusercontent.com/83406722/116812024-77107a00-ab1a-11eb-9ecc-9e3979d098b4.png">

**Comment by xulihang** [comment]
Baidu may have problems with multiple sentences in one textbox. Use other machine translation engines like tencent

**Comment by animanl00ver** [comment]
when changing the translation do you also change in the server

**Comment by animanl00ver** [comment]
do they have to match

**Comment by xulihang** [comment]
What do you mean `also change in the server`?

**Comment by animanl00ver** [comment]
the translation machine 
<img width="674" alt="Screen Shot 2021-05-03 at 11 04 15 AM" src="https://user-images.githubusercontent.com/83406722/116894166-c2508880-abff-11eb-939b-8f02b5bfb9e4.png">

**Comment by animanl00ver** [comment]
do they need to match because some translations tools aren't available

**Comment by xulihang** [comment]
One is the ocr engine and the other is the machine translation engine. The two do not have to match each other.

**Comment by animanl00ver** [comment]
if possible can you explain the difference so i can understand how the program work

**Comment by animanl00ver** [comment]
the program is working but it misses some bubbles, is there a way that i can fix that

**Comment by xulihang** [comment]
Please open a new issue for further problems.
