### ISSUE TITLE
使用chrome插件的时候显示Failed to connect to ImageTrans server

### ISSUE THREAD

**Issue by OniNezuko** [xulihang/ImageTrans-docs#371]
正如题目所说，我正确下载并且开启了本地服务器，在腾讯动漫中翻译也显示这个内容

**Comment by xulihang** [comment]
按F12打开控制台，看看有报什么错误

**Comment by xulihang** [comment]
另外可以访问<http://127.0.0.1:51042/translator>，看看有没有正确启动。也可以在这个页面上传图片进行翻译。
