### ISSUE TITLE
百度的API接口 对接是不是有问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#372]
![image](https://user-images.githubusercontent.com/30548000/222954658-5c4b6af9-43de-4294-bdbc-f03e970457e3.png)
如图 我pandaOCR 和IT 用的是相同的 百度API KEY 
相同的图片 相同的API 在panda上就可以正常识别 在您的IT 软件上就要么是空要么返回 null
轻微这个是什么问题呢
因为 昨天的插件 可以看竖排的漫画了 然后 我现在看的这本  离线ocr 准确率低到让人发指
所以想用在线的 而在线的 今天一用就出现了这种情况

**Comment by xulihang** [comment]
填错了，balloon_detection_url这个是百度easydl的接口地址，可以不填。需要填上面两个。

还有离线ocr，如果你说的是mangaocr，它默认识别长条文字效果是不好的。所以我昨天更新了插件，把长的单行文字拆分成几部分给它识别，效果就可以了，用的时候选long text (mangaocr)。但必须先按单行识别，不能合并后再识别。

**Comment by lhj5426** [comment]
> 填错了，balloon_detection_url这个是百度easydl的接口地址，可以不填。需要填上面两个。
> 
> 还有离线ocr，如果你说的是mangaocr，它默认识别长条文字效果是不好的。所以我昨天更新了插件，把长的单行文字拆分成几部分给它识别，效果就可以了，用的时候选long text (mangaocr)。但必须先按单行识别，不能合并后再识别。

好尴尬呀因为百度注册的时候 是给了这3个参数

所以我以为都填写呢 因为刚好3个 哈哈 

嗯  不过我昨天都合并完了哈哈 没事 在线我也都有自己的aPI 就是不识别 原谅填错了 谢谢 我去改正一下

**Comment by lhj5426** [comment]
好了识别上了  这TM填写的时候就没走脑子 非常感谢

**Comment by lhj5426** [comment]
> 填错了，balloon_detection_url这个是百度easydl的接口地址，可以不填。需要填上面两个。
> 
> 还有离线ocr，如果你说的是mangaocr，它默认识别长条文字效果是不好的。所以我昨天更新了插件，把长的单行文字拆分成几部分给它识别，效果就可以了，用的时候选long text (mangaocr)。但必须先按单行识别，不能合并后再识别。

对了还有一个问题 现在是识别了 但是有的识别出来是乱码 而用panda 在相同的api key 下就能识别是不是没有高精度的接口？
![image](https://user-images.githubusercontent.com/30548000/222956038-df6d5c45-c035-464a-a638-c693837be75e.png)
![image](https://user-images.githubusercontent.com/30548000/222956064-b3aa85be-2e55-4094-b6ed-f8ef8c36fd81.png)
这3个我都试 了都会乱码

**Comment by lhj5426** [comment]
语言是这样设置的
![image](https://user-images.githubusercontent.com/30548000/222956181-e9a8fe53-3570-4925-b01d-332ed1ed6ac3.png)

**Comment by xulihang** [comment]
baidu_accurate就是高精度版。accurate的话，语言可以调为自动检测。

还有点识别后看看软件目录下的image.jpg是什么样的，这个是上传到百度服务器的文件。

**Comment by lhj5426** [comment]
> image

![image](https://user-images.githubusercontent.com/30548000/222956561-d2fca859-510c-4a25-ab0a-68a748f4bfce.png)
软件目录下的这个文件 就是这样的

**Comment by lhj5426** [comment]
> baidu_accurate就是高精度版。accurate的话，语言可以调为自动检测。
> 
> 还有点识别后看看软件目录下的image.jpg是什么样的，这个是上传到百度服务器的文件。

问题是 有的可以识别 有的不可以识别 不可以识别就是乱码 返回瞎识别的结果
然后相同的API的 截图识别软件 就可以正常识别

**Comment by xulihang** [comment]
这个图和给pandaocr的不一样，要窄一点。可能百度识别出来就是这样的，太窄了会识别错误

**Comment by lhj5426** [comment]
> 这个图和给pandaocr的不一样，要窄一点。可能百度识别出来就是这样的，太窄了会识别错误

原来如此 还真是这个样子呢
![image](https://user-images.githubusercontent.com/30548000/222956943-5eec3f21-f0a0-4868-a089-0828dd19634b.png)
哈哈 我知道了 非常感谢老哥 解惑

**Comment by lhj5426** [comment]
下次遇到这种情况我就修改下文字框的范围再识别  或者批量 设置文字框扩展大一些
