### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by NUCKLER1** [xulihang/ImageTrans-docs#373]
![image](https://user-images.githubusercontent.com/127129709/223167000-752fdd55-7030-4fdb-8a5b-54afc5609f56.png)
NO ME DEJ TRADUCIR EN TODO EL PROYECTO

**Comment by xulihang** [comment]
The built-in API key for Baidu has exceeded its monthly usage. Try to use another machine translation like cloudtranslation and deeplfree.
