### ISSUE TITLE
能否接入GPT翻呢？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#375]
尊敬的开发者老哥 现在已经开放apil接入GPT了 咱们是不是也可以接入一下呀
用gpt 翻译 好像也可以  不知道有没有可行性
![image](https://user-images.githubusercontent.com/30548000/223333858-63d55ccc-4d85-4b6b-a70b-a7c3bb605db4.png)

**Comment by xulihang** [comment]
我看下做个插件

**Comment by xulihang** [comment]
插件做好了，可以填入自己的API密钥试一下。需要翻墙。

[chatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11040416/chatGPT.zip)

![image](https://user-images.githubusercontent.com/5462205/226919071-72b2627f-6eef-4cd1-84ea-5890ddcb995e.png)

**Comment by lhj5426** [comment]
> 插件做好了，可以填入自己的API密钥试一下。需要翻墙。
> 
> [chatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11040416/chatGPT.zip)
> 
> ![image](https://user-images.githubusercontent.com/5462205/226919071-72b2627f-6eef-4cd1-84ea-5890ddcb995e.png)

好的 其他都有就差您的插件 我去试试

**Comment by xulihang** [comment]
软件重启了吗？

然后我又更新了下插件，修了个语言代码的问题，麻烦再下一次。

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/226924830-1e6307a2-8c87-42d5-9f79-2aff1c96be9d.png)
![image](https://user-images.githubusercontent.com/30548000/226924892-911095fd-bd46-40e0-905f-6c6dfedc88a7.png)
API里也没有

**Comment by lhj5426** [comment]
我的版本是最新的192呀 我去看了没更新版本呀不应该是版本问题？

**Comment by lhj5426** [comment]
> 我用旧版开发工具重新编译了一份，再试一下吧。刚才帖子的附件更新了。

error: java.lang.NullPointerException
StackTrace: java.lang.NullPointerException
	at org.xulihang.imagetrans.httputils2service._hc_responseerror(httputils2service.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$3.run(BA.java:247)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
这个报错是什么意思呢？

**Comment by lhj5426** [comment]
配置了相同的API 浏览器翻译插件就可以工作
![image](https://user-images.githubusercontent.com/30548000/226930276-823be76f-b3e3-4581-8f86-af3291de6ba0.png)

**Comment by xulihang** [comment]
再切换一个文本框去翻译看看，然后看看命令行有什么输出，我试了下1.9.2配这个插件是可以用的

**Comment by xulihang** [comment]
还有同一个key放在不同应用多次请求也有可能会被限制

**Comment by lhj5426** [comment]
> 再切换一个文本框去翻译看看，然后看看命令行有什么输出，我试了下1.9.2配这个插件是可以用的

![image](https://user-images.githubusercontent.com/30548000/226931424-4677b6eb-fbd4-462b-b9d7-50ec178b6468.png)
代理设置了全局 然后 API 
设置了 没接过

**Comment by lhj5426** [comment]
> 再切换一个文本框去翻译看看，然后看看命令行有什么输出，我试了下1.9.2配这个插件是可以用的

命令行 在哪里看？？ 这个软件

**Comment by lhj5426** [comment]
我觉得 现在好像是也是这个问题
https://github.com/Bin-Huang/chatbox/issues/13
软件没有被代理上

**Comment by lhj5426** [comment]
刚才代理是这边 所以无法使用  
![image](https://user-images.githubusercontent.com/30548000/226938169-14c7ccc4-dd86-4222-8d59-cf07c9a27562.png)

**Comment by lhj5426** [comment]
话说老哥可以增加这个功能吗
![image](https://user-images.githubusercontent.com/30548000/226938554-eceaecb3-cd33-46cd-bc84-88d4e1d8ab6d.png)
![image](https://user-images.githubusercontent.com/30548000/226938686-b130c1a4-a330-40b4-9eb9-f7de070ed560.png)
变成可以自定义的

**Comment by lhj5426** [comment]
现在您内置的命令 翻译 会有奇怪的东西出现 
![image](https://user-images.githubusercontent.com/30548000/226942503-478c25b0-b1d3-4d35-9bd7-12dd54f35490.png)
![image](https://user-images.githubusercontent.com/30548000/226942850-211cf236-4181-4594-ad90-df0e18d647fb.png)

**Comment by lhj5426** [comment]
太开心了 都忘记说了  感谢开发者老哥更新GPT翻译插件！！！
另外 期待后续的更新迭代

**Comment by xulihang** [comment]
我把zh这样的语言代码转换成Chinese这样的英文了，应该可以正常使用了：
https://github.com/xulihang/ImageTrans_plugins/commit/d3f1842c21f5dafc591be14e7040ccc7df87275a

**Comment by lhj5426** [comment]
> 我把zh这样的语言代码转换成Chinese这样的英文了，应该可以正常使用了： [xulihang/ImageTrans_plugins@d3f1842](https://github.com/xulihang/ImageTrans_plugins/commit/d3f1842c21f5dafc591be14e7040ccc7df87275a)

我需要重新 下载吗 还是在那个帖子里下嘛？ 还是下次更新？
点击这个链接是跳转到了代码

**Comment by xulihang** [comment]
之前帖子的附件更新过了

**Comment by lhj5426** [comment]
> 我把zh这样的_语言_代码转换成_Chinese_这样的英文了，应该可以正常使用了： [xulihang/ImageTrans_plugins@d3f1842](https://github.com/xulihang/ImageTrans_plugins/commit/d3f1842c21f5dafc591be14e7040ccc7df87275a)

还是会有乱入
![image](https://user-images.githubusercontent.com/30548000/227870627-ef1eb490-6d6f-4013-9e8d-6a404331c50f.png)

**Comment by lhj5426** [comment]
乱入 很正常 因为它要解释 这个话是什么意思 怎么来的
但是我觉得乱入也应该是全中文

**Comment by xulihang** [comment]
加了一个诱导话语的设置。

默认的设置是`Translate the following into {langcode}: {source}`，软件会把`{langcode}`替换为目标语言，`{source}`替换为要翻译的内容。

可以改成截图里这样的用中文聊天并指定翻译为中文，这样返回的提示也会是中文的。

![image](https://user-images.githubusercontent.com/5462205/229261940-871f52e4-eb05-4922-bf00-36348f229d95.png)

新的插件：
[chatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11128278/chatGPT.zip)

**Comment by lhj5426** [comment]
> 加了一个诱导话语的设置。
> 
> 默认的设置是`Translate the following into {langcode}: {_source_}`，软件会把`{langcode}`替换为目标_语言_，`{_source_}`替换为要翻译的内容。
> 
> 可以改成截图里这样的用_中文_聊天并指定翻译为_中文_，这样返回的提示也会是_中文_的。
> 
> ![image](https://user-images.githubusercontent.com/5462205/229261940-871f52e4-eb05-4922-bf00-36348f229d95.png)
> 
> 新的插件： [chatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11128278/chatGPT.zip)

好的 我去试试

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/229268713-bf3d26aa-3b4f-4449-ab62-b2d5d05052e7.png)
哈哈 非常感谢开发者老哥 这次 没毛病

**Comment by lhj5426** [comment]
然后回到是上一个 
https://github.com/xulihang/ImageTrans-docs/issues/384
这里是可以 把每一页的 对话单独导出TXT
那么我在想可不可在批量翻译的时候 直接把一整页的 对话喂给 GPT
这样 一整页的对话 GPT会联系上下文 可能更准确一点？
然后手动选择框的时候 才是 一句一句喂

**Comment by xulihang** [comment]
ImageTrans只负责导出数据，数据怎么被处理就不管了。这个需要专门写个工具

**Comment by lhj5426** [comment]
> ImageTrans只负责导出数据，数据怎么被处理就不管了。这个需要专门写个工具

好吧那就不在这个issues 范畴了 再次感谢 您今天更新的GPT插件 本issues 完结
