### ISSUE TITLE
关于框选合并文本方向的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#376]
https://user-images.githubusercontent.com/30548000/223362205-57300610-5df6-4b75-a3bf-1e77ef9a8cb4.mp4

https://user-images.githubusercontent.com/30548000/223362222-50ab177e-4780-4b0d-8872-3fe3f17e504a.mp4

尊敬的老哥 如 视频所示那样 文本合并的方向好像搞反了 别的语言 咱不清楚
至少日文语言 合并的方向 应该是 从 右边到左边合并 
合并完之后 原先左边框的文字应该在原右边框文字之后才对 而不是现在这样 在前边

**Comment by xulihang** [comment]
这里的合并逻辑没有考虑阅读顺序，是按文本框当前顺序来的。可以先排序一下，然后再合并

**Comment by lhj5426** [comment]
> 这里的合并逻辑没有考虑阅读顺序，是按文本框当前顺序来的。可以先排序一下，然后再合并

排顺序 是要怎么个操作 ？目前的软件可以做到吗

**Comment by xulihang** [comment]
用文本框列表下方的排序按钮或者自定义工作流

**Comment by lhj5426** [comment]
> 用文本框列表下方的排序按钮或者自定义工作流

我稍微研究了一下这里
![image](https://user-images.githubusercontent.com/30548000/223378432-31186888-8ce2-45ca-bfac-77d94ad88fe0.png)
这里可以排序但是有个问题 这个 这个 文字框旁边的 合并 的2个按钮不好使？
只有 最顶上的 合并按钮好使？
这2个按钮是什么时候生效的？

**Comment by xulihang** [comment]
看这个视频：https://www.bilibili.com/video/BV1t7411L7u1/

**Comment by lhj5426** [comment]
> 看这个视频：https://www.bilibili.com/video/BV1t7411L7u1/

看完了 我这种不适用这个功能 也不是我想的那种功能  我还得在F2里合并  现在不是按阅读顺序 后续更新可以改成阅读顺序合并吗  手动排序也是个挺大的工作量哈哈

**Comment by lhj5426** [comment]
> 你点排序那个按钮，是按阅读顺序的

喔 原来

> 你点排序那个按钮，是按阅读顺序的

喔~还真是诶
那我就好像明白了 直接工作流里加一个就行了呗
![image](https://user-images.githubusercontent.com/30548000/223388350-60cefb2e-ba67-4267-8211-3258934b88a5.png)
