### ISSUE TITLE
这是什么情况 关于多选 框选的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#377]
https://user-images.githubusercontent.com/30548000/223677521-19faad57-893c-458b-97dc-bac11238d7c1.mp4

就是您看
我先操作的是把 一个文字框的颜色设置成了粉色
然后切换到多选么模式 我想要把所有文字进行对其
但是 当我 操作框选的时候 神奇的事情发生了
所有框选的颜色 全变成 最右边的白色

这个功能 在 什么地方可以关闭呢
气泡 就不说了
这种竖排的文字 基本上这个 文字对其功能是标配 对于纯竖排文字来说 只要一页大于2句对话
就都要使用这个功能
而这个全部框选后 文字全部变色的操作 会变相的增加修改文字颜色的工作量
明明已经修改完了颜色 然后就因为框选了一下 之前的 劳动就付诸东流了。。。

请问老哥 这个功能怎么关闭

**Comment by xulihang** [comment]
是个bug。之前这个[issue](https://github.com/xulihang/ImageTrans-docs/issues/185)增加了字体样式应用于所有选中文本框的功能。这里多选时会触发这个操作。下个版本修正吧

**Comment by lhj5426** [comment]
> 是个bug。之前这个[issue](https://github.com/xulihang/ImageTrans-docs/issues/185)增加了字体样式应用于所有选中文本框的功能。这里多选时会触发这个操作。下个版本修正吧

哦 我还以为是为了方便设置统一字体颜色 的设定。。。

**Comment by xulihang** [comment]
v1.9.3修复了这个问题
