### ISSUE TITLE
想询问下术语 和翻译记忆的正确用法

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#379]
https://user-images.githubusercontent.com/30548000/224320487-3c3f5e97-c5cc-4aec-a684-d4a86a346b1e.mp4

https://user-images.githubusercontent.com/30548000/224320513-165a8978-1790-411c-9719-9284cbea0a7c.mp4

开发者老哥 这个功能一直没用明白

![image](https://user-images.githubusercontent.com/30548000/224320649-af1ab53c-e69b-4244-80c1-558e08685375.png)
在一个项目里 只要有一股 对话 假设是123 然后翻译结果是你好
在该项目里所有 的123 都可以通过辅助翻译 快速点击 替换
这个很好用
但是添加到术语之后 就不好用了

术语这个功能我是这么理解的

就是添加之后 在 机器翻译的时候自动替换 原文为 术语里 写入的词 而不是用机器翻译替换原文

但是实际上好像并不是  我觉得我的理解是不是错了

然后还有 
![image](https://user-images.githubusercontent.com/30548000/224321053-6a5d44ce-f717-4348-b863-3254e6039dab.png)
这个翻译记忆 开启之后

![image](https://user-images.githubusercontent.com/30548000/224321189-88412d50-fced-405a-90ca-ba474cb02394.png)

这里显示不可用 是我术语 哪里设置错了吗

为什么要问这个问题呢
因为我发现 我在做漫画字幕的时候 大部分实际 是在做重复的不能再重复的劳动 就是输入拟声词
所以这个术语如果可以用的话 我在想我是不是可以把这些 完全一样的词全部在
机翻的过程中自动用术语替换掉？

比如这个双语翻译软件 的这种 术语管理
![image](https://user-images.githubusercontent.com/30548000/224321863-9883c97a-f2cc-45a0-a8f5-56f52ce6bfea.png)
就是如我理解的那样 在初次机翻的时候 会自动把原文 替换成术语库了 翻译 而忽略 机器翻译的结果

所以请教您一下 请您教我一下 这个软件的术语 和 翻译记忆如何使用

这个软件用了一年我居然没搞明白这个功能 或者说忽略了这个功能 在此感谢

**Comment by xulihang** [comment]
这两个功能目前比较简单，预翻译的翻译记忆匹配我没做。可以先用BasicCAT翻译ImageTrans的项目文件。BasicCAT的计算机辅助翻译功能要强大的多。

**Comment by lhj5426** [comment]
> 这两个功能目前比较简单，预翻译的翻译记忆匹配我没做。可以先用BasicCAT翻译ImageTrans的项目文件。BasicCAT的计算机辅助翻译功能要强大的多。
原来是这样
那个
![image](https://user-images.githubusercontent.com/30548000/224330138-7d6c3e17-3002-4258-a307-7295e4a00a57.png)
就是说 先通过ImageTrans 导出成文本形式 喂给BasicCAT 然后 翻译完再导出 再导入  ImageTrans

**Comment by lhj5426** [comment]
> 这两个功能目前比较简单，预翻译的翻译记忆匹配我没做。可以先用BasicCAT翻译ImageTrans的项目文件。BasicCAT的计算机辅助翻译功能要强大的多。

导入之后 乱码 无论是utf8 还是UTF8-BOM 都是乱码
 
![image](https://user-images.githubusercontent.com/30548000/224333677-a708a42d-38aa-4a57-a790-42555abecf04.png)

**Comment by xulihang** [comment]
推荐的方法：

1. 导出成xliff文件，可以用BasicCAT、memoQ、Trados、Transmate等软件翻译。参考这个[issue](https://github.com/xulihang/ImageTrans-docs/issues/207)
2. 使用BasicCAT的ImageTrans翻译插件，可以直接处理ImageTrans的项目文件。见https://github.com/xulihang/ImageTrans-docs/issues/380

**Comment by lhj5426** [comment]
> 推荐的方法：
> 
> 1. 导出成xliff文件，可以用BasicCAT、memoQ、Trados、Transmate等软件翻译。参考这个[issue](https://github.com/xulihang/ImageTrans-docs/issues/207)
> 2. 使用BasicCAT的ImageTrans翻译插件，可以直接处理ImageTrans的项目文件。见[BasicCAT plugin to translate ImageTrans projects #380](https://github.com/xulihang/ImageTrans-docs/issues/380)

按照了插进 直接能打开 项目文件了 可 为什么还是乱码 哭了

**Comment by lhj5426** [comment]
> 推荐的方法：
> 
> 1. 导出成xliff文件，可以用BasicCAT、memoQ、Trados、Transmate等软件翻译。参考这个[issue](https://github.com/xulihang/ImageTrans-docs/issues/207)
> 2. 使用BasicCAT的ImageTrans翻译插件，可以直接处理ImageTrans的项目文件。见[BasicCAT plugin to translate ImageTrans projects #380](https://github.com/xulihang/ImageTrans-docs/issues/380)

导出 这个格式的  导入是空

![image](https://user-images.githubusercontent.com/30548000/224341232-99f863ec-0846-4469-915e-39eae697a32d.png)

**Comment by lhj5426** [comment]
> 项目文件你有用别的编辑器编辑过吗，默认是utf8编码应该是没问题的。 导出为xliff，不是xlsx。

我确定以及肯定我没有编辑过 使用的项目文件

**Comment by lhj5426** [comment]
[000119-400.zip](https://github.com/xulihang/ImageTrans-docs/files/10942939/000119-400.zip)
我上传个项目文件 您试试 我这里打开就是乱码 换了狠多项目文件都是一个问题

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/224342297-a264743f-194f-4d10-8aef-0a118de8070d.png)
导出为XIIFF 我没有看到这选项？

**Comment by xulihang** [comment]
点供翻译的文档，然后扩展名选xliff。

**Comment by lhj5426** [comment]
> 点供翻译的文档，然后扩展名选xliff。

![image](https://user-images.githubusercontent.com/30548000/224342941-a1d04d24-7dab-4d8a-b706-a585f0e14940.png)
也是乱码

**Comment by xulihang** [comment]
我试了下没什么问题，看看项目的字体设置，换一个字体看看。
![image](https://user-images.githubusercontent.com/5462205/224342930-d1591acc-e314-47a3-a065-3145854703b1.png)

**Comment by xulihang** [comment]
噢，我知道了，项目路径不要有中文。

**Comment by xulihang** [comment]
分别设置原文和译文字体了吗

**Comment by lhj5426** [comment]
> 分别设置原文和译文字体了吗
我了去 原来 字体是分原文和译文的啊 
设置完了 好使了
![image](https://user-images.githubusercontent.com/30548000/224344916-22191e63-fdef-4539-af4b-1edc23ffdfae.png)
主要软件没中文看着有点 不太想看 非常感谢

**Comment by lhj5426** [comment]
先这么凑合用吧
期待有一天 老哥可以把 BasicCAT 的术语功能移植到  ImageTrans 这样就不需要2个软件来回折腾了

**Comment by lhj5426** [comment]
然后导出的 xlf 在导入BasicCAT 之后 翻译的文本显示不全

https://user-images.githubusercontent.com/30548000/224345999-476fd927-659e-4434-b8b8-879f0a3ec129.mp4
直接度项目文件可以的

**Comment by xulihang** [comment]
xliff会自动分句，可能使得翻译无法保留

**Comment by xulihang** [comment]
分句功能是可以在设置里关掉的

**Comment by lhj5426** [comment]
> xliff会自动分句，可能使得翻译无法保留


https://user-images.githubusercontent.com/30548000/224348648-f41aa57d-34ee-4587-baff-fc02512de125.mp4

看来是我想多了哈哈 我以为这边编辑保存 这边打开就可以看到结果

**Comment by xulihang** [comment]
把basiccat安装目录下的jre换成imagetrans的再试试看

**Comment by lhj5426** [comment]
> 

Error:Could not create the Java Virtual Machine.Error:A fatal exception has occurred.Program will exit.
![image](https://user-images.githubusercontent.com/30548000/224354672-cb1dc55b-949a-496a-a0f2-0294e5ecd286.png)
替换之后 只能重装软件了

**Comment by xulihang** [comment]
问题结束。BasicCAT的问题发到BasicCAT的仓库里。

**Comment by xulihang** [comment]
v1.9.5的预翻译功能更新了下，可以用翻译记忆进行完全匹配。需要原文完全相同才能填充对应的翻译。

**Comment by lhj5426** [comment]
> v1.9.5的预翻译功能更新了下，可以用翻译记忆进行完全匹配。需要原文完全相同才能填充对应的翻译。

辛苦老哥了    这就去更新看看

**Comment by lhj5426** [comment]
> v1.9.5的预翻译功能更新了下，可以用翻译记忆进行完全匹配。需要原文完全相同才能填充对应的翻译。

开发者老哥 这个翻译记忆 是一个独立的文件吗 还是保存在 项目里？

**Comment by xulihang** [comment]
其实就是存在项目文件里的原文和译文

**Comment by lhj5426** [comment]
> 其实就是存在项目文件里的原文和译文

哈哈 那也就是说 这记忆 是只针对当前漫画的 

比如如 当前漫画 金刚狼 是项目A1
然后又换了另外一个漫画 蝙蝠侠 是项目B1
这个B1 是读取不了A1里的 
是应该这么理解的吧

**Comment by lhj5426** [comment]
> 其实就是存在项目文件里的原文和译文

其实我还在想 如果是 一个独立的记忆文件
我是不是可以把之前所有润色过 上百本漫画的 结果 全部导入到这个
记忆文件里  哈哈 然后翻译的时候 自动读取 匹配提取

**Comment by xulihang** [comment]
是的，要使用其它项目的翻译记忆现在还是得用BasicCAT

**Comment by lhj5426** [comment]
> 是的，要使用其它项目的翻译记忆现在还是得用BasicCAT

好的 知道了 谢谢

**Comment by lhj5426** [comment]
> 是的，要使用其它项目的翻译记忆现在还是得用BasicCAT

嗯知道了  谢谢
您看我这个想法 用法对不对
那现在这个记忆是不是可以这样用比如 创建了一个项目A1 然后这个 项目里有500页
然后呢 我先翻了 100页 比如 EN EN  AA 这种 重复比较多的
我是不可以 直接在预翻译里那个用这个完全匹配翻译记忆
自动把剩下400页相同的 EN EN  AA 这种 重复比较多的 一次搞定？

**Comment by xulihang** [comment]
是这样的，不过原文一定要完全相同

**Comment by lhj5426** [comment]
> 是这样的，不过原文一定要完全相同

嗯那肯定 毕竟 长篇里相同的拟声词太多了 谢谢 明确用法就可以相对的减少输入的功夫了 
非常感谢51还在更新
