### ISSUE TITLE
[Suggestion] Apply first/default font style to text area

### ISSUE THREAD

**Issue by lugia19** [xulihang/ImageTrans-docs#38]
For whatever reason text areas have no listed font style once they've been added. It would be nice if it could be set to the topmost/default font style.
![a](https://user-images.githubusercontent.com/21088033/116611874-255bca00-a937-11eb-8302-bfb6501fb301.png)

**Comment by xulihang** [comment]
The top fontstyle is the default style. If the textbox has no style specified or local style, the default one will be used.

Only after you specify a font style will the combo box display the style's name.

**Comment by lugia19** [comment]
Yeah, that's what I figured that's what was happening. I was just wondering if the combo box couldn't have the default style selected
