### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#390]
ImageTrans now uses BBCode to set inline styles (rich text). To make it easy to use, I've made a rich text editor for it.

Check out the video for details:

https://user-images.githubusercontent.com/5462205/229330205-74691d91-f6cc-4851-94b7-bf5e88d6c190.mp4

**Comment by xulihang** [comment]
Added in v1.9.3.

**Comment by lhj5426** [comment]
> 加入v1。9.3.

![image](https://user-images.githubusercontent.com/30548000/229348645-a9495f4e-1240-4916-b8ea-f1c9eeb8785c.png)
太有意思了 非常感谢！
