### ISSUE TITLE
Issues installing ImageTrans on windows

### ISSUE THREAD

**Issue by zidemizar** [xulihang/ImageTrans-docs#392]
I have downloaded the application from the provided link and the additional applications such as the CV dll and jre, launching either the .exe or jar does nothing, no applications are open in task manager. What am I missing?

**Comment by xulihang** [comment]
You need [OpenCV 4.5.5](https://github.com/xulihang/ImageTrans-docs/releases/download/opencv/Windows.x64.opencv_java455.zip) and [the full version of Liberica JRE](https://github.com/bell-sw/Liberica/releases/download/11.0.18%2B10/bellsoft-jre11.0.18+10-windows-amd64-full.msi).

You can also use the full version on onedrive which already has the two packaged.

**Comment by zidemizar** [comment]
Where can I find the link for the one drive version?

**Comment by xulihang** [comment]
In the readme file or the emails sent to you.
