### ISSUE TITLE
能否在右键里增加去除译文位置信息 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#393]
https://user-images.githubusercontent.com/30548000/232788265-bc77f5b2-3cd1-4c6b-b85c-c131d809ea64.mp4

请看视频

如视频所示这样这种翻译结果呼拉长对话框
就是修改完文字
对话框还是要重置一下 但是
因为右键里没有这个 功能
每次都要去设置里找 有点不太方便
您看看 是不是可以直接在右键里增加一个？
这样点击右键操作 一气呵成
现在这样选择 然后 去顶部找 有点割裂感
虽然可以用快捷键 
但是这种还是喜欢视觉操作比较舒服 
请开发者老哥 您评估下这个功能
然后最好呢放在一级 或者二级菜单了 不要进3级 不好找
![image](https://user-images.githubusercontent.com/30548000/232789365-9c409861-2d9f-4cc5-afaf-c3f296f5e995.png)

以前呢 这种操作 并不频繁
以前是 可能宏出问题了或者马虎了把文字设置的很大数值
才会需要重置一下 译文位置信息
但是 现在用了 GPT之后会有点频繁 所以请您评估一下

**Comment by xulihang** [comment]
这里需求还有一点是去除选中的区域的译文位置信息，用菜单是去除全部的，我看看怎么给它加上吧

**Comment by lhj5426** [comment]
> 这里需求还有一点是去除选中的区域的译文位置信息，用菜单是去除全部的，我看看怎么给它加上吧

对 您说的 是去除选字幕块的译文位置信息

**Comment by xulihang** [comment]
加在v1.9.5里了
