### ISSUE TITLE
deepl

### ISSUE THREAD

**Issue by oxi82** [xulihang/ImageTrans-docs#399]
Hello, deepl does not work.

**Comment by oxi82** [comment]
![Capture d’écran 2023-05-02 200545](https://user-images.githubusercontent.com/13768562/235748748-45cc24c6-9088-4f20-b84f-bc9aba7c4bc7.png)

**Comment by xulihang** [comment]
Have you filled in your API key? You can get your key here: https://www.deepl.com/en/pro-api

Since I am from China, I cannot have an account to test.

**Comment by xulihang** [comment]
You can also use deeplfree which does not require an API key.

**Comment by oxi82** [comment]
I hadn't seen the deeplfree version, thank you very much.
