### ISSUE TITLE
新问题

### ISSUE THREAD

**Issue by 1010919601zzz** [xulihang/ImageTrans-docs#4]
![image](https://user-images.githubusercontent.com/32429737/105149344-67a68b80-5b3e-11eb-9137-72d90be7d989.png)

这个问题怎么解决呢？

在切换翻译语言对之后

**Comment by xulihang** [comment]
下面的错误信息没有全部显示出来。我觉得应该是有一个文本框超框了，文本框不要超出图片

**Comment by a509973930** [comment]
![1](https://user-images.githubusercontent.com/84120154/118092556-d6b23380-b3fe-11eb-9588-cd82422678b1.png)
![2](https://user-images.githubusercontent.com/84120154/118092620-e9c50380-b3fe-11eb-9b24-994b5f562489.png)
![3](https://user-images.githubusercontent.com/84120154/118092699-04977800-b3ff-11eb-9a02-501f253d9ee3.png)
![4](https://user-images.githubusercontent.com/84120154/118092713-082aff00-b3ff-11eb-980b-0bfb5db75245.png)

**Comment by xulihang** [comment]
这个谷歌机器翻译是需要自己申请API密钥的。

googlewithapikey是不需要的。
