### ISSUE TITLE
baidu_netwrok引擎无法使用麻烦尽快看一下

### ISSUE THREAD

**Issue by linkstree** [xulihang/ImageTrans-docs#40]
![image](https://user-images.githubusercontent.com/18115991/116666428-9b961600-a9a3-11eb-8ed2-e78a48a74288.png)

**Comment by linkstree** [comment]
你好作者，我是付费用户，你是不是考虑开个微信群呀，太多需要改进的地方了，而且需要售后技术支持

**Comment by xulihang** [comment]
百度网络图片版每天只能请求500次，你可以自己去百度申请一个付费账号，就没这个问题了

**Comment by xulihang** [comment]
这里申请：https://ai.baidu.com/tech/ocr_others/webimage

**Comment by linkstree** [comment]
申请成功之后要配置什么嘛？

**Comment by xulihang** [comment]
需要填写的是API Key和Secret Key

**Comment by linkstree** [comment]
ok
