### ISSUE TITLE
可以兼容A API2D吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#401]
https://www.bilibili.com/video/BV1Ds4y177W6/?vd_source=0e5320b70a2cffd76ff2f2b234f7367c
是这样的 现在 GPT免费API 被限制成了 1分钟3条 3条 3条 3条 啊
而 IT 这个软件预翻译 是一个气泡一个气泡的发送这就导致了  一个关键的问题 翻译的会很慢 一页都要跑好久
但是 看了这个视频 这个 视频说只要有 代理地址的填写 和 API 填写就可以用 他们的服务
价格不贵 而且 至少1分钟有60条的速率 比 OP官方的免费版1分钟就3条 要强很多呀
600句话的 漫画也就10来分钟就完事了

老哥可以考虑一下吗？

**Comment by xulihang** [comment]
现在插件这个URL是写死的：`https://api.openai.com/v1/chat/completions`

我给它改成可以配置吧，这样看它的说明，把URL替换下应该就能用了

**Comment by lhj5426** [comment]
> 现在插件这个URL是写死的：`https://api.openai.com/v1/chat/completions`
> 
> 我给它改成可以配置吧，这样看它的说明，把URL替换下应该就能用了

看视频里说 好像是  只要能配置代理地址 和K 就能用的样子

**Comment by xulihang** [comment]
我把插件更新了一下，需要设置API2D的API地址和Forward Key。

![image](https://user-images.githubusercontent.com/5462205/236669171-c3005521-518f-4889-835c-c36155884fae.png)


[ChatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11414424/ChatGPT.zip)

**Comment by lhj5426** [comment]
> 

测试可用

https://user-images.githubusercontent.com/30548000/236673756-af0c5c0e-7602-4223-87aa-33b4cde45237.mp4

感谢
