### ISSUE TITLE
这是bug吗 删除译文无效

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#402]
https://user-images.githubusercontent.com/30548000/236514163-b77ec4f1-a798-40f4-9523-008c0a4cf95e.mp4

之前问您的时候我特意截图保留的 就怕忘记了
![image](https://user-images.githubusercontent.com/30548000/236514328-be9a7410-c3af-4642-aaea-0bff74997213.png)
这次按照这个截图的方法  软件上 提示说 删除了  但是 实际上译文还在  
这是bug吗？
还有 这个 译文 是通过 DOC 导入进来的 我OCR完就直接导出DOC 去喂 Claude 然后 翻译完 导入 
然后 想要测试不同GPT 以及竞品Claude 引擎 想清空译文  再导出个 纯日文的 DOC 就发现清空不了 
用之前的方法删译文删不掉  如视频所示
用的版本
![image](https://user-images.githubusercontent.com/30548000/236515816-213f6088-3a15-440b-92bb-063a138ae7d2.png)

**Comment by xulihang** [comment]
我试了下没问题，可以把项目文件发过来我再试一下。

**Comment by lhj5426** [comment]
> 我试了下没问题，可以把项目文件发过来我再试一下。
[000127.zip](https://github.com/xulihang/ImageTrans-docs/files/11411336/000127.zip)
这个项目文件 我这里 就是无法清空

**Comment by xulihang** [comment]
我看了下是多行文本的匹配有问题，从docx导入的文本末尾有个换行符导致替换时匹配失败了，新版本修复吧

**Comment by lhj5426** [comment]
> 我看了下是多行文本的匹配有问题，从docx导入的文本末尾有个换行符导致替换时匹配失败了，新版本修复吧

嗯 麻烦 感谢 了

**Comment by xulihang** [comment]
v1.9.6修复了

**Comment by lhj5426** [comment]
> v1.9.6修复了

感谢  试过了 妥妥的 可以删除了 DOC导入后的原文
