### ISSUE TITLE
导入导出文本可以增加JSON格式吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#404]
我使用过GIT上各种 翻译文本的工具

都是 按行 按句来翻译
这2个工具可以 批量翻译
不是拿着一行 翻译 1可以用免费的 GPT 2付费API 这样消耗也小一点

https://github.com/XHXJ/json-GPT-translator

https://github.com/NEKOparapa/AiNiee-chatgpt

现在还得额外跑一下 PY 来转换成json
![image](https://user-images.githubusercontent.com/30548000/236667425-5ced4137-571a-4c8b-b217-12f36dc9faf3.png)
所以说 能直接 导出就导出 json 格式的 然后导入也可以导入JSON格式的
 然后跑完还得用代码
 
![image](https://user-images.githubusercontent.com/30548000/236667479-6bba6b74-a2b3-4723-84e8-62f107a62d04.png)
再转换成TXT 成
![image](https://user-images.githubusercontent.com/30548000/236667562-a8617346-3c37-4850-a156-14f744ea2f82.png)
这个格式 就很麻烦  所以 请开发者老哥 考虑下 后续的版本增加直接JSON导入导出吧 

顺带一说 这代码页GPT 写的 我不懂代码

**Comment by xulihang** [comment]
ImageTrans的项目就是JSON格式的，不过这些工具不能直接用，我看了下这些工具只支持mtool导出的JSON，不是一个通用标准，不打算兼容。建议这些工具支持XLIFF格式，这个是一个标准格式

**Comment by lhj5426** [comment]
> ImageTrans的项目就是JSON格式的，不过这些工具不能直接用，我看了下这些工具只支持mtool导出的JSON，不是一个通用标准，不打算兼容。建议这些工具支持XLIFF格式，这个是一个标准格式

知道啦

**Comment by xulihang** [comment]
我看了下这个工具的批量功能需要自定义一个诱导内容，去翻译一个JSON格式的内容以实现批量翻译，我考虑给现在的ChatGPT插件加一个批量翻译话术设置

**Comment by lhj5426** [comment]
> 我看了下这个工具的批量功能需要自定义一个诱导内容，去翻译一个JSON格式的内容以实现批量翻译，我考虑给现在的ChatGPT插件加一个批量翻译话术设置

那这个可以 主要就是现在 的IT的GPT用来润色可以  但是用来 预翻译 批量的是 一个气泡一个气泡的 
就很慢而且 1个气泡=一句问答 免费的API 只有1分钟3次 也就是翻译 3个气泡 要有1分钟休息时间
我刚才用转成JSON 的方式用这些工具翻译 22页漫画 120个气泡 只用了不到5分钟就跑出来了

**Comment by xulihang** [comment]
我更新了下ChatGPT的插件，改成以图为单位进行批量翻译

[ChatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11523811/ChatGPT.zip)

**Comment by lhj5426** [comment]
> 我更新了下ChatGPT的插件，改成默认以图为单位进行批量翻译
> 
> [ChatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11523811/ChatGPT.zip)

好的 我去试试

**Comment by xulihang** [comment]
我试了下会把两个句子翻译成一个句子，我再优化下提示语。批量翻译的提示语需要修改偏好设置里batch_prompt这个参数

**Comment by xulihang** [comment]
更新了下，这个版本相对稳定一点：

[ChatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11524026/ChatGPT.zip)

**Comment by lhj5426** [comment]
> 更新了下，这个版本相对稳定一点：
> 
> [ChatGPT.zip](https://github.com/xulihang/ImageTrans-docs/files/11524026/ChatGPT.zip)

![2023-05-21-18 03 46](https://github.com/xulihang/ImageTrans-docs/assets/30548000/71586eed-6bcc-4803-ab0b-6e9d78815311)
 正在用新的 插件翻译这个1100页的超大型漫画 
 跑完看看效果

**Comment by lhj5426** [comment]
别的不说着比一句句翻译跑 起来快多了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8d403fa2-b611-4995-81be-deeda49b7556)
