### ISSUE TITLE
安装完字体在选择字体中没出现

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#405]
好怪耶。。不是这样安装的吗？  
![WeChat 截圖_20230508171459](https://user-images.githubusercontent.com/49093867/236785967-77c9e94e-d29f-4d2b-b4ba-a258314cc7e1.png)
![WeChat 截圖_20230508171447](https://user-images.githubusercontent.com/49093867/236786007-bc491add-237a-498d-95b2-f7f35a9f15db.png)

**Comment by xulihang** [comment]
新安装的字体不是排在末尾，是按照字母排序的。然后显示的字体名称是英文，需要到列表中找一下

**Comment by haofan170** [comment]
sokka,解决啦 多谢大佬
