### ISSUE TITLE
去字以后掩模的地方变黑了，没有被虚化？

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#407]
有的时候纯白有的时候纯黑，这个是为什么呢？
![237474408-bc875c1b-3797-4f26-b1f1-c8e8e8974709](https://github.com/xulihang/ImageTrans-docs/assets/49093867/ddb5f149-53b9-431a-9b7d-826ceb70f252)

**Comment by haofan170** [comment]
嗯，出现个新问题了（）
![WeChat 截圖_20230511235754](https://github.com/xulihang/ImageTrans-docs/assets/49093867/b6cf2509-eef9-480f-ab05-baec66948d43)
点击 patchmatch修复以后，掩模的地方直接变上面这样了（）一点没去字，是按照BLOG的掩膜膨胀大小设置为10以后再去patchmatch的，就变上图了。。纳闷

**Comment by xulihang** [comment]
Patchmatch是我在自己电脑上编译的，可能在你电脑上用不了，我一直没解决这个问题。它的源代码在这里：https://github.com/xulihang/Inpainting

**Comment by xulihang** [comment]
还有一个叫lama inpaint的工具，效果也还可以：https://github.com/xulihang/ImageTrans-docs/issues/216

**Comment by haofan170** [comment]
好捏，我研究下，现在用manga translate那个来去字效果也还行 谢谢大佬啦
