### ISSUE TITLE
关于右键里新增的清除译文位置？ 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#408]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/83e8f24c-6edc-4a2e-9013-bb23ca6c7628

老哥  这个 不是只清理 译文的位置 而是 把整个气泡给清空了 原文 译文 全部都没了位置 是复位了
但是文字全没了 和 在菜单里的 清除译文位置信息 不一样 菜单里的这个 是会保留译文和原文的
这个在右键里新增的 把原文 和译文也个情况了 是只需要清理位置信息 而不需要 清理气泡里的所有文字信息呀

**Comment by xulihang** [comment]
这个功能只会重置译文位置信息，不会清除文本的。文本消失可能是之前没有保存。

**Comment by lhj5426** [comment]
> 我看了下，你开了自动保存。这个会有影响，是个bug

呃 这个 偏好设置里的自动保存600 默认就是勾着的没动过

**Comment by xulihang** [comment]
是右边大写a那个按钮

**Comment by lhj5426** [comment]
> 是右边大写a那个按钮

那个 不点 我容易忘记 所以 每次打开项目之后 会用宏一键打开 并且调整右侧栏目的位置
打开这个这样 润完一个气泡就可以直接去弄下一个了 不需要手动在点保存了
很方便 等下个版本 修复BUG了  辛苦了

**Comment by xulihang** [comment]
v1.9.7修复了

**Comment by lhj5426** [comment]
> v1.9.7修复了

好快…回到家就更新

**Comment by lhj5426** [comment]
感谢 好用了 不再删除文字了 修好咯！！
