### ISSUE TITLE
OCR translate doesn't work.

### ISSUE THREAD

**Issue by orcavia** [xulihang/ImageTrans-docs#409]
i tried to use OCR button for translating the selected text area but nothing happen

![tmp](https://github.com/xulihang/ImageTrans-docs/assets/68916685/8cfa58f0-0d05-4a69-8e9c-02a771bab2f7)

**Comment by xulihang** [comment]
You have to install tesseract with the language data of Japanese if you need to use it: https://github.com/UB-Mannheim/tesseract/wiki

I'd recommend using mangaOCR which has a better accuracy: https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR
