### ISSUE TITLE
已经OCR识别过的词条再次用其他引擎识别，还要一个个的点识别按钮

### ISSUE THREAD

**Issue by linkstree** [xulihang/ImageTrans-docs#41]
![image](https://user-images.githubusercontent.com/18115991/116684365-8cba5e00-a9b9-11eb-94e4-3e4d2fe93e73.png)

**Comment by linkstree** [comment]
启发式方法也并不完美，所以我都是先用启发式方法或者某个OCR引擎先进行框选，然后再根据效果对部分文字框选再进行OCR

**Comment by xulihang** [comment]
明白了，主要是已经做好了框选，不适合直接全部删除。我打算加强下搜索与替换功能，可以根据OCR引擎名字对结果进行筛选

**Comment by xulihang** [comment]
腾讯OCR和搜狗OCR效果也不错，可能比百度好，你可以再试一下这两个。不过都是要自己申请API密钥的

**Comment by xulihang** [comment]
1.3.6版添加了一个去除所选文字框的原文和译文的功能，之后可以用批量OCR和机器翻译翻译没有文字的区域
