### ISSUE TITLE
Use Inset Rect for Mask

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#413]
For text with complex background, it is not easy to accurately generate the text mask.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/f549e82f-886d-4b29-bc78-79ca55a3d819)

Actually, in most cases which have complex background, an inset rect is enough.

Mask:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/8baf6818-2a1f-4e72-a585-f2006b56081e)

Text removed using Sickzil Machine:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/ba16e314-c454-492f-b5bd-ddc1b9a0d0a7)

I've created the [InsetRectMaskGen](https://github.com/xulihang/ImageTrans_plugins/tree/master/InsetRectMaskGen) mask generator plugin to do this.

**Comment by xulihang** [comment]
The plugin has been added in v1.9.8.

**Comment by lhj5426** [comment]
> 对于背景复杂的文本，准确生成文本掩码并不容易。
> 
> ![image](https://user-images.githubusercontent.com/5462205/239737286-f549e82f-886d-4b29-bc78-79ca55a3d819.jpg)
> 
> 实际上，在大多数有复杂背景的情况下，插入 rect 就足够了。
> 
> 面具:
> 
> ![image](https://user-images.githubusercontent.com/5462205/239737659-8baf6818-2a1f-4e72-a585-f2006b56081e.png)
> 
> 使用 Lama Inaint 删除文字:
> 
> ![image](https://user-images.githubusercontent.com/5462205/239738293-d7a7fa5d-8db5-49c8-9a34-00fdaf8de5fd.png)
> 
> 我已经创建了 InsetRectMaskGen 掩码生成器插件来实现这一点。

是的 之后会用文字遮丑所以这样就很不错了 如果再想做精点的话直接ps内容识别填充 了 
不过这就需要开发者老哥 后期迭代更新 单页导出PSD文件了

**Comment by xulihang** [comment]
Similar mask generation methods are added: OCR and balloon detection
