### ISSUE TITLE
How to use DEEPL FREE?

### ISSUE THREAD

**Issue by dnr111222** [xulihang/ImageTrans-docs#415]
I'm not sure how to use deepl free, I'd appreciate it if you could elaborate.
Currently, when I try to use it, it doesn't translate.

**Comment by xulihang** [comment]
It works fine translating Japanese to Chinese. If it does not work, maybe your language pair is not supported.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/7fc4dee2-fc6d-4b14-b19d-d3cd5274c9f2)

**Comment by dnr111222** [comment]
When I test in Chinese, I don't get any translation results. 
The deeplfree plugin documentation has a docker address, do I need to do anything else to use deeplfree?

**Comment by dnr111222** [comment]
I set it to zh, not zh-Cn, and it worked fine. I guess they don't support Korean. That's a shame, thank you.

**Comment by xulihang** [comment]
Papago and eztrans may have a better result translating Japanese to Korean.
