### ISSUE TITLE
Validator Problem

### ISSUE THREAD

**Issue by YukiHimeTempest** [xulihang/ImageTrans-docs#418]
I was using the program in the old version. When I tried to upgrade, it didn't accept my information. The old version accepts it though. 
![image](https://github.com/xulihang/ImageTrans-docs/assets/79001588/093b5754-8dd5-47ac-a097-43f48c239fef)
![image](https://github.com/xulihang/ImageTrans-docs/assets/79001588/b1a1ebb9-06fb-4fc7-9658-c609cf9476cd)

**Comment by xulihang** [comment]
You need to purchase ImageTrans again to use versions released 6 months after your previous purchase.
