### ISSUE TITLE
Google OCR

### ISSUE THREAD

**Issue by YukiHimeTempest** [xulihang/ImageTrans-docs#419]
How i use Google OCR? I add API Key but not working ocr.
![image](https://github.com/xulihang/ImageTrans-docs/assets/79001588/5e3439fe-88dd-41c5-9d3d-8a6565a54acd)

I click th OCR button but it doesn't work
![image](https://github.com/xulihang/ImageTrans-docs/assets/79001588/903373bc-2369-4dcb-b822-dde3612154f6)

**Comment by YukiHimeTempest** [comment]
version 1.6.5

**Comment by xulihang** [comment]
Try to follow guides like this: https://easyscreenocr.com/how-to-load-google-api-in-easyscreenocr-for-mac-lifetime-version/

**Comment by YukiHimeTempest** [comment]
i did it this way too

**Comment by YukiHimeTempest** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/79001588/12321b13-cb8d-426a-b69d-bca15f865dcc)
![image](https://github.com/xulihang/ImageTrans-docs/assets/79001588/e2611651-aab6-4722-bbc7-840aebc49133)

**Comment by xulihang** [comment]
Use `ImageTrans.bat` to open ImageTrans and you can see the output of the program to find out the reason. Which country are you in? The OCR service is blocked in China.

**Comment by YukiHimeTempest** [comment]
Turkey.

**Comment by YukiHimeTempest** [comment]
I solved the problem thanks to ImageTrans.bat. Thanks for help.
