### ISSUE TITLE
文字区批量删除功能缺失

### ISSUE THREAD

**Issue by linkstree** [xulihang/ImageTrans-docs#42]
![image](https://user-images.githubusercontent.com/18115991/116690616-4f0e0300-a9c2-11eb-9e0b-989b6fc08063.png)

**Comment by linkstree** [comment]
![image](https://user-images.githubusercontent.com/18115991/116685801-99d84c80-a9bb-11eb-9f68-3c24f2b40417.png)
麻烦下一个版本加上这些功能

**Comment by xulihang** [comment]
好的，多选删除和针对选中文字区域的重新OCR和翻译，我会添加上去的

**Comment by linkstree** [comment]
![image](https://user-images.githubusercontent.com/18115991/116691474-84ffb700-a9c3-11eb-96a2-2b60faaa4cb3.png)

**Comment by xulihang** [comment]
目前需要点击辅助翻译，然后从机器翻译列表中选择一个进行填充

**Comment by xulihang** [comment]
1.3.6版添加了一个快速填入机器翻译的按钮

**Comment by xulihang** [comment]
v1.5.2多选文字区域后可以按Delete键删除了
