### ISSUE TITLE
请问斜着的一行字怎么识别啊

### ISSUE THREAD

**Issue by NinjaAquaKin** [xulihang/ImageTrans-docs#422]
建的识别框只能先建竖着的  文本斜的话有的字体就识别不上了

**Comment by xulihang** [comment]
可以旋转文本框的，把鼠标移动四个顶点的位置时会出现旋转手势

**Comment by NinjaAquaKin** [comment]
我建好框旋转之后点击识别 识别不到文字

**Comment by xulihang** [comment]
文字是什么样的。有旋转信息的区域OCR前会被纠正，还是识别不出可能就是所选的OCR不能识别了

**Comment by NinjaAquaKin** [comment]
对着斜着的一行文字建框——旋转框——点击识别——能识别出文字，但是原文无法消抹掉，查看翻译时中文直接覆盖上去了

**Comment by xulihang** [comment]
不旋转的情况下的框应该需要完全包含文字

**Comment by NinjaAquaKin** [comment]
试了一下完全包含 还是消除不掉原文
即便使用正常框识别到 原文也还是无法消除

**Comment by xulihang** [comment]
默认的文字掩膜生成方法是针对气泡内文字优化的，不能去除的话需要自己编辑文字掩膜
