### ISSUE TITLE
ChatGPT有漏翻译的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#423]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/0d35947a-bc56-426e-aa10-95d919ce41ff)
尊敬的开发者老哥 如图 
最近发现批量直接跑预翻译GPT 经常会这样原文返回  是怎么个情况呢
不对 我的描述错了 
是根本就没翻译到
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1175e3ba-d814-42d5-8fa3-014bc5a74593)
应该是 经常丢翻译 丢三落四 1 2百页 会有个 十几页 几十页 会丢掉

**Comment by lhj5426** [comment]
如果手动翻译的话 
又会变成这样
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d6e382a0-96d9-4c5a-91d2-4a6af908e895)
 提示词里也写了不要返回中文以外的语言 。。。

**Comment by xulihang** [comment]
你有改过提示词吗？用的API2D还是ChatGPT的服务，漏掉可能是请求失败了。还有目前的提示词还是无法杜绝两个气泡被翻译成一个的问题，有时译文顺序会有问题。

**Comment by lhj5426** [comment]
> 你有改过提示词吗？用的API_2D_还是ChatGPT的服务？漏掉可能是请求失败了。还有目前的提示词还是无法杜绝两个气泡被翻译成一个的问题，有时译文顺序会有问题。

修改和没修改 目前都有这个 漏的问题 就是一整页 就没翻译

合并翻译 和漏翻译是2个概念
合并翻译至少是翻译成中文了 而漏翻译是整个页面就被划过去了没翻译 基本上是翻译几页十几页就会有这种问题
修改过提示词之后 不会再全日文了 

我用的是120刀的账号 
就是 现在比较流行的号贩子那里的 10块钱120刀额度的账号 专门用来跑翻译的账号 我也是从翻译游戏的群友那知道的

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ea2b4b6d-131f-4ca7-975a-99491d9e0884)


我现在的提示词是这样  虽然丢页漏翻 无法解决 但是 手动翻的时候 不会再像 楼上我发的图那个会全变成英文了
而是翻译成中文

请帮我把JSON格式的文本翻译成{langcode},并且按照JSON格式原样返回,请不要将不同的键值混在一起返回.同时在翻译的过程中请忽略对内容的解释,不需要对所翻译的内容作出解释.除了对原文的翻译之外的内容一概不需要,在此基础上禁止返回除了简体中文以外的任何一种其他语言,也不要拒绝翻译,同时再在这个基础之上每句话里的标点符号都请按照原文的标点返回,如果发送的JSON里出现无意义或者无效的内容时请按照原文返回,最后如果可以适当的对文本进行一下润色就更好了.这是需要请你帮忙翻译的JSON字符串: {source} 

译文顺序到是小事 临时吃口机翻快餐 不碍事 要像润色 问题也不大

就是 漏页  比较讨厌  顺序错位比起 漏页丢页来说 都不叫事  了？ 个人感觉

**Comment by lhj5426** [comment]
请求失败这个是常事 就是网页聊天
跟他说话 或者写代码的时候
它也会突然卡壳 然后中断重新写或者继续写
这个 是不是可以考虑增加一个 重试机制？
如果说错了您就当我胡诌 多担待
因为毕竟我只是用户 不懂软件的运行机制

**Comment by xulihang** [comment]
看日志的话用ImageTrans.bat打开软件可以看到日志

**Comment by sera1991** [comment]
> 请求失败这个是常事 就是网页聊天 跟他说话 或者写代码的时候 它也会突然卡壳 然后中断重新写或者继续写 这个 是不是可以考虑增加一个 重试机制？ 因为GPT和传统的翻译还是很不一样 传统的翻译 发一句翻译一句 没有延迟 GPT 说白了 它会思考 这个思考 就有返回时间 一问一答 目前 插件只有一个进度批量进度条 和 一个延迟 来查看 还有和GPT沟通 ![image](https://user-images.githubusercontent.com/30548000/242950492-741d2dc7-d90b-4010-a931-ab257c40dc44.png)
> 
> 是不是可以增加一个 可以查看到 软件怎么样的在和GPT进行沟通？比如增加日志功能？ 因为现在 就是只知道它 漏了 但是运行过程中它是怎么漏的 不知道 是因为443了 还是就漏了 不知道
> 
> 如果说错了您就当我胡诌 多担待 因为毕竟用户 不懂软件的运行机制

老哥现在解决了吗，我不知道算不算漏翻，用gpt3.5预翻译有些图会原文返回ocr结果
<img width="1201" alt="屏幕截图 2023-06-27 012417" src="https://github.com/xulihang/ImageTrans-docs/assets/30473573/03600cca-b066-4319-8bb8-901e497f7964">
而且就算把译文清除再翻译还是会原文拷贝到翻译栏中
不过奇怪的是gpt-4能正常翻译（就是成本有点高）。。。

**Comment by hakureikiri** [comment]
> 请求失败这个是常事 就是网页聊天 跟他说话 或者写代码的时候 它也会突然卡壳 然后中断重新写或者继续写 这个 是不是可以考虑增加一个 重试机制？ 因为GPT和传统的翻译还是很不一样 传统的翻译 发一句翻译一句 没有延迟 GPT 说白了 它会思考 这个思考 就有返回时间 一问一答 目前 插件只有一个进度批量进度条 和 一个延迟 来查看 还有和GPT沟通 ![image](https://user-images.githubusercontent.com/30548000/242950492-741d2dc7-d90b-4010-a931-ab257c40dc44.png)
> 
> 是不是可以增加一个 可以查看到 软件怎么样的在和GPT进行沟通？比如增加日志功能？ 因为现在 就是只知道它 漏了 但是运行过程中它是怎么漏的 不知道 是因为443了 还是就漏了 不知道
> 
> 如果说错了您就当我胡诌 多担待 因为毕竟用户 不懂软件的运行机制

问问120刀10元的GPT哪里买的

**Comment by lhj5426** [comment]
> > 请求失败这个是常事 就是网页聊天 跟他说话 或者写代码的时候 它也会突然卡壳 然后中断重新写或者继续写 这个 是不是可以考虑增加一个 重试机制？ 因为GPT和传统的翻译还是很不一样 传统的翻译 发一句翻译一句 没有延迟 GPT 说白了 它会思考 这个思考 就有返回时间 一问一答 目前 插件只有一个进度批量进度条 和 一个延迟 来查看 还有和GPT沟通 ![image](https://user-images.githubusercontent.com/30548000/242950492-741d2dc7-d90b-4010-a931-ab257c40dc44.png)
> 
> > 
> 
> > 是不是可以增加一个 可以查看到 软件怎么样的在和GPT进行沟通？比如增加日志功能？ 因为现在 就是只知道它 漏了 但是运行过程中它是怎么漏的 不知道 是因为443了 还是就漏了 不知道
> 
> > 
> 
> > 如果说错了您就当我胡诌 多担待 因为毕竟用户 不懂软件的运行机制
> 
> 
> 
> 问问120刀10元的GPT哪里买的

过了这村没那店 已经成为历史了…前2个月的事情了

**Comment by lhj5426** [comment]
解决办法 OCR后 排序 排序后导出 供翻译的TXT 直接那TXT去喂 就不会 楼翻译了
