### ISSUE TITLE
偏好设置怎么导出

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#424]
偏好设置怎么导出。每次更完软件，之前的设置就没了...还有译文字体放大缩小能添加个快捷键功能吗（只看到图像比例有放大缩小快捷键），然后希望快捷键可以支持绑定鼠标侧键。。

**Comment by xulihang** [comment]
更新时保留原来的preferences.conf文件可以保留偏好设置。

**Comment by xulihang** [comment]
鼠标侧键我没用过，我鼠标也没有侧键，不知道怎么设这个

**Comment by xulihang** [comment]
译文字体放大缩小我可以加一个菜单项目，具体用哪个快捷键你自己在偏好设置里指定吧。

或者像现在百分比调节一样，鼠标放在上面，可以滚动滚轮调节

**Comment by lhj5426** [comment]
> 偏好设置怎么导出。每次更完软件，之前的设置就没了...还有译文字体放大缩小能添加个快捷键功能吗（只看到图像比例有放大缩小快捷键），然后希望快捷键可以支持绑定鼠标侧键。。

建议看下这个 https://github.com/xulihang/ImageTrans-docs/issues/215
可以一定程度弥补
