### ISSUE TITLE
Two improvement requests

### ISSUE THREAD

**Issue by dnr111222** [xulihang/ImageTrans-docs#425]
1. When detecting font color, the color of the border is detected, not the color of the font.

![image](https://github.com/xulihang/ImageTrans-docs/assets/42793507/8dd9dc8f-81e4-4a87-868d-2d41ea8505bb)
For example, in this image, white is detected when detecting the font color

Is there any way to fix this?

If there's no way around it, 

https://github.com/zyddnys/manga-image-translator/releases/tag/beta-0.3
This is the address of the manga-image-translator git release, and manga-image-translator is very good at detecting font colors and border colors.
The font color detection model used here is 
https://manga-colorization-v2-generator.zip
manga-colorization-v2-net_rgb.pth
I'm wondering how it can't be applied to imagetrans?

Secondly, it would be nice to have the ability to merge characters horizontally and vertically in a batch.

**Comment by xulihang** [comment]
About font color detection, I have to improve the algorithm. The easy way would be using `manga-image-translator` of course. It's just I don't have much time to adapt it for ImageTrans. If they provide an HTTP interface for font detection by default, I don't need to do anything.

You can merge characters horizontally and vertically in a batch. Check out custom workflow.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/698c00aa-d0f3-4a82-8f3b-d8e3516ed1a5)

**Comment by dnr111222** [comment]
Basically, how do you use the HTTP interface for font detection?

When I select merge areas in a custom workflow and hit okay, the HOW TO MERGE BOXES? that you see in the picture doesn't pop up, is there something I need to do differently?

**Comment by xulihang** [comment]
If manga-image-translator has an HTTP interface for font color detection, I can directly send the image of the text area to detect the color. But there is not. I have to edit its code to add such an interface.

Click the label of boxes merging and you can configure it.

**Comment by xulihang** [comment]
If you encounter the problem of lines not being merged, you can check out the FAQ: https://www.basiccat.org/imagetrans/faq/

**Comment by dnr111222** [comment]
It seems to be difficult to use manga-image-translator. 
I would appreciate it if you could improve the algorithm for the font color detection you mentioned above when you have time.

**Comment by xulihang** [comment]
About text color detection, it is now possible to use manga-image-translator to detect the color.

Check out this: https://github.com/xulihang/ImageTrans-docs/issues/478
