### ISSUE TITLE
关于富文本字体设置大小与项目设置里字体样式之间的关系

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#427]
尊敬的开发者老哥你好
我在刚才制作漫画字幕的过程中发现了一个问题
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/050b713c-2b54-41ff-87f2-50d908d1f692)
如图
如您所看到的的
我的字幕启用了 项目里的样式
并且启用了富文本  对文字的颜色 和大小分比设置了富文本 
但是 在实际的效果里 只有富文本的颜色 被赋予了上去
而且设置的富文本大小字体并没有被赋予上去
之前在
https…//github.com/xulihang/ImageTrans-docs/issues/390
这个刚更新的时候我 用我是随便创建了一个新的项目 这个项目并没有有在项目设置里资源样式里设置
任何的字体样式 所以可以像这样可大可小随意调节
但是今天我在做漫画字幕的时候 实战的时候发现 如果项目里的字体样式有设置
在启用富文本 则 只有部分富文本生效 面前 实战使用的 更改字体 更改字体大小 更改字体颜色
只有字体颜色的富文本生效了
所以我想知道一下 这个富文本与 项目设置里的字体样式的关系

**Comment by lhj5426** [comment]
我的这一系列操作是
建立在
我以为 以项目里的字体样式为基本的基础上
可以进行富文本的加工
而实际上应该也是这样
但真正实操之后发现 好像不然
要说 我的理解不对但是颜色被赋予了呀
要说的 但其他的又没有生效
所以我很迷糊

**Comment by xulihang** [comment]
竖排引擎目前是不支持富文本的字体大小设置的，切换成横排可以看到效果。像你图里这种可以设成横排，但因为是竖着拉长的，实际显示效果可以和竖排一样。

**Comment by lhj5426** [comment]
> 竖排引擎目前是不支持富文本的字体大小设置的，切换成横排可以看到效果。像你图里这种可以设成横排，但因为是竖着拉长的，实际显示效果可以和竖排一样。

搜嘎 原来是这么回事 谢谢 非常感谢
