### ISSUE TITLE
Export JPG quality

### ISSUE THREAD

**Issue by ByRoT91** [xulihang/ImageTrans-docs#429]
Hy!

Your program is amazing! But i have a question:
If I export a random image to JPG, in the out folder the JPG files quality is very low than the original ones.
Can I export to JPG with the original quality of the picture?
And another question: can i translate in the program with DeepL to hungarian? (english to hungarian) It's not the most important for me, because with the OCR, it's very easy copy-paste method to DeepL website to translate to hungarian.

Thank you your answer! :)

**Comment by xulihang** [comment]
You have to set the display percentage to 100% before exporting to JPEG. Otherwise, it will be scaled.

You can use DeepL for English to Hungarian. Try DeepLFree or DeepL with your own API key.

**Comment by ByRoT91** [comment]
Thanks, when I set the display percentage to 100%, before export JPG, the quality is same like the original one in the out folder, so thanks a lot! 

But how can I translate to hungarian? In the machine translation,, I select in checkbox only the DeepL and DeeplFree.
But where is the setting, I can translate from ENG to HUN?
Thanks!

**Comment by xulihang** [comment]
When creating a new project, set the language-pair with the ISO-639 Code: en and hu.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/26c9fcdf-6073-4a53-8eea-03bc80cd5b7c)

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/39408a9a-4352-437d-ae7f-dfdee8e290c7)

**Comment by ByRoT91** [comment]
Thanks, It work. This program is amazing, and I can install my fonts too that I usually use for the translations.
No need any program for the comic translations anymore. This program contains all of what I need.
Thanks again for you work, you are the best!
