### ISSUE TITLE
can you add papago OCR??

### ISSUE THREAD

**Issue by bravehon** [xulihang/ImageTrans-docs#43]
https://developers.naver.com/apps/#/myapps/kbne68t22o2oxse4X86F/overview

when I use papago translate
I found papago OCR can you add ??

**Comment by xulihang** [comment]
I think it is the same as clove ocr.

**Comment by bravehon** [comment]
> I think it is the same as clova ocr.

can you add? because papago OCR is free but clova is not free

**Comment by xulihang** [comment]
I checked again. It is not OCR.

![无标题](https://user-images.githubusercontent.com/5462205/116953068-e32be300-acbe-11eb-9064-e2424a8d7cd4.png)

**Comment by bravehon** [comment]
> I checked again. It is not OCR.
> 
> ![无标题](https://user-images.githubusercontent.com/5462205/116953068-e32be300-acbe-11eb-9064-e2424a8d7cd4.png)

okay I see..
