### ISSUE TITLE
可以给GPT插件增加自定义模型的功能吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#430]
举个例子
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4fd9b281-6b8e-40b6-89c7-b62ca099082c)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7f5efad0-4a4a-4cd2-822a-838776bcbc6f)
这样 用户直接手动修改就可以使用该API 里的任意模型了 
https://platform.openai.com/docs/models/how-we-use-your-data
还请开发者老哥 考虑一下 

假如用户有钱的话还可以就修改下直接用gpt4 
而像这样更新 切换 模型的话 只需要 修改下 模型就行了 
不需要等待开发者的更新

**Comment by xulihang** [comment]
加一个配置很容易的，我明天加一下

**Comment by lhj5426** [comment]
> 加一个配置很容易的，我明天加一下

非常的感谢
这样只要OPENAI那边的API主要地址不变
每次出新模型 用户自己修改下 模型编号就可以用了

**Comment by xulihang** [comment]
更新文件：
[ChatGPTPlugin.zip](https://github.com/xulihang/ImageTrans-docs/files/11752741/ChatGPTPlugin.zip)



代码变动：
https://github.com/xulihang/ImageTrans_plugins/commit/52fc3d00e60badb6f55c0209c44ed4d8bfc7fa88

**Comment by lhj5426** [comment]
> 更新文件： [ChatGPTPlugin.zip](https://github.com/xulihang/ImageTrans-docs/files/11752741/ChatGPTPlugin.zip)
> 
> 代码变动： [xulihang/ImageTrans_plugins@52fc3d0](https://github.com/xulihang/ImageTrans_plugins/commit/52fc3d00e60badb6f55c0209c44ed4d8bfc7fa88)

好快 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/897ef0f7-71fe-4bdf-9073-7b302ec842c7)
这样应该就可以直接用最新的0613了 感谢

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4ca44c83-82cb-4509-9bd2-e9d6f6051cb5)
换上新插件跑图速度嗖嗖的

**Comment by xulihang** [comment]
搜不到这个错误`PARAM FROM TO Q EMPTY`

**Comment by lhj5426** [comment]
> 搜不到这个错误`PARAM FROM TO Q EMPTY`

好神奇的错误 下次遇到再反馈吧  估计这个跟
https://github.com/xulihang/ImageTrans-docs/issues/423
是一个问题 所以 这个  就关闭了 我下次遇到了去那个423里反馈
