### ISSUE TITLE
Unknown host exception

### ISSUE THREAD

**Issue by ByRoT91** [xulihang/ImageTrans-docs#431]
Hy!

I have a question. When I try start the program on my company computer (in the company, on company network) it gave me a message at the verification. Can I fix this? Or can I skip the verification? I Don't want share the program, I buy it, but i can translate comics in my jobtime, and this program is the best.

Thanks!
![1](https://github.com/xulihang/ImageTrans-docs/assets/104424475/ae54e454-85b6-49f1-b7dc-ead1c4531e35)

**Comment by xulihang** [comment]
There may be some firewall blocking the Internet connection. I have met such a problem at Airbus.

Even if I remove the verification, you still cannot access services like DeepL. You have to use offline machine translation engines like Opus-CAT. But if you just need to translate manually, it works okay.

**Comment by ByRoT91** [comment]
Thanks your answers, but I don't risk that IT look after this anyway.
But I can translate with this way: in home, I running the ImageTrans, and do OCR and text removed pages. I put to a pendrive the text removed pages, and the OCR translated texts, and editing with portable photoshop. :)
