### ISSUE TITLE
ME DICE ACCESO DENEGADO

### ISSUE THREAD

**Issue by NUCKLER1** [xulihang/ImageTrans-docs#433]
AL INGRESAR AMI PROGRAMA  ME MARCA Y ERRO Y DICE ACCESO DENEGADO ME PODRIAN APOYAR CON ESO NOSE PORQUE SERA 
error: java.io.FileNotFoundException: C:\account (Acceso denegado)
![Captura de pantalla 2023-06-16 164732](https://github.com/xulihang/ImageTrans-docs/assets/127129709/c1d0a7dd-6068-4835-a1d9-334e31be9225)

**Comment by xulihang** [comment]
Do not put ImageTrans at C:\. There will be a permission problem that it cannot write files to it.
