### ISSUE TITLE
导出PSD后用PS打开没有修复图片，而是直接用白色图层覆盖

### ISSUE THREAD

**Issue by chengfa2333** [xulihang/ImageTrans-docs#434]
![1686997626122](https://github.com/xulihang/ImageTrans-docs/assets/61651149/aed6a8d1-4fd3-4f7c-8227-b25aa25fcd3d)

**Comment by chengfa2333** [comment]
导出时已选择精确模式

**Comment by xulihang** [comment]
怎么操作的，用的addLayers.jsx这个脚本吗？导出的out.txt和params.txt发我看一下

**Comment by chengfa2333** [comment]
[out.txt](https://github.com/xulihang/ImageTrans-docs/files/11778740/out.txt)
[params.txt](https://github.com/xulihang/ImageTrans-docs/files/11778742/params.txt)

**Comment by chengfa2333** [comment]
我是翻译完成后，点击文件-生成可编辑PSD文件。PS用的是最新的2023版。

**Comment by xulihang** [comment]
那是直接用的au3脚本，这个我好久没测试了，要测一下。

可以用addLayers.jsx去创建PSD，这个JavaScript的版本是最新的。

**Comment by xulihang** [comment]
我看了下params.txt里第二个数字是0，这个表示非精确模式，所以会用白色图层覆盖。你确定选中添加覆盖图层和精确模式了吗

**Comment by chengfa2333** [comment]
![1687004531387](https://github.com/xulihang/ImageTrans-docs/assets/61651149/5962cb4e-ba3d-4999-a845-4501e4727ca2)

**Comment by chengfa2333** [comment]
这样直接导出自动打开PS

**Comment by chengfa2333** [comment]
ok了，用addLayers.jsx构建就成功了
