### ISSUE TITLE
How to fix This.

### ISSUE THREAD

**Issue by WavaDev** [xulihang/ImageTrans-docs#435]
![image](https://github.com/xulihang/ImageTrans-docs/assets/127393002/60e83a0d-2cb1-4d99-aa3f-81452deda371)

After Exported:
![image](https://github.com/xulihang/ImageTrans-docs/assets/127393002/b5b79a17-1035-421c-a403-90c8d839dfbf)
 
How to fix that?

**Comment by xulihang** [comment]
ImageTrans exports what you see. Do not check the typesetting checkbox.

**Comment by WavaDev** [comment]
I know that, but it is the font is the problem.

**Comment by WavaDev** [comment]
After the export the font is trash

**Comment by xulihang** [comment]
It seems a very long image. Please upload the project along with the image for me to have a test.
