### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#436]
华康字体标点会往左偏，有办法能让标点居中吗。。
然后华文细黑字体加粗和倾斜都没反应。。

**Comment by xulihang** [comment]
竖排引擎对不同字体的兼容不好，可以见这个issue：https://github.com/xulihang/ImageTrans-docs/issues/271

不支持粗体和斜体是因为这个字体本身不支持粗体和斜体，只能通过算法来实现仿斜体和仿粗体，这个竖排目前不支持。

**Comment by xulihang** [comment]
可以导出结果为PSD，用Photoshop做进一步处理

**Comment by sera1991** [comment]
刚安装了方正黑体，安装完后字体设置有这字体，但工作区的更改字体那没有显示。

**Comment by xulihang** [comment]
这是一个不足的地方，需要重新打开一次项目。
