### ISSUE TITLE
机翻问题

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#438]
用chatgpt机翻有些能正常翻译成中文，但有些会把ocr出的日文都填进翻译框里（整张图）。
还有怎么重新翻译（或清空当前图的翻译)...我用批量翻译会自动跳过错误的那块，只能手动一个个点右边的翻译。。

**Comment by xulihang** [comment]
ChatGPT的批量翻译用的batch_prompt可以自己调整一下，我也试了好久才调出目前的prompt，但可能还是会有问题。

重新翻译的话需要先去除译文，可以全选后在右键菜单里选择清除译文
