### ISSUE TITLE
是否可以增加【导出的txt可直接用于labelplus嵌字】的功能

### ISSUE THREAD

**Issue by Pulaimarii** [xulihang/ImageTrans-docs#439]
labelplus所需的txt格式需包含页码，标号，以及xy轴上的位置
以及希望chatgpt翻译的功能可以越做越好

**Comment by Pulaimarii** [comment]
感谢！如果您不准备集成进ImageTrans的话在哪里可以知道您有没有发布转换工具呢🙏🏻

**Comment by xulihang** [comment]
转换工具我会写成一个网页，写好了会在这里回复

**Comment by xulihang** [comment]
网页写好了，可以用它实现ImageTrans和LabelPlus项目的互相转换：https://www.basiccat.org/tools/image-translation-project-manager/

注意LabelPlus使用百分比保存坐标，所以处理时还需要选择图片文件以提供宽高信息。LabelPlus不支持子文件夹，所以ImageTrans的项目也不能有子文件夹。

**Comment by xulihang** [comment]
@noodlefighter FYI

**Comment by noodlefighter** [comment]
是想用起LabelPlus的Photoshop导入脚本吧，Good Job

**Comment by Pulaimarii** [comment]
您好，抱歉打扰，不知道是不是我操作有误，使用ImageTrans的几种导出文件后，导出的LabelPlus文件均为空白
我选择的是文件-导出-Tab分割的TXT文件，并上传至网页的“选择项目文件”一栏
同时也选择了全部图片上传至“选择图片文件”一栏
导出格式选择了“LabelPlus”
但是出来的文件只包含
1,0
-
框内
框外
-
Default Comment
You can edit me

没有其他任何翻译文字或原文文字
后面尝试了ImageTrans导出其他格式，重新上传至“选择项目文件”，生成的结果依然同上
是应该选择其他的导出吗？

**Comment by xulihang** [comment]
不是ImageTrans导出的文件，是ImageTrans的项目文件，扩展名是itp。

**Comment by Pulaimarii** [comment]
已经成功了！非常感谢！

**Comment by lhj5426** [comment]
这个网页功能牛掰啊

**Comment by chencxt** [comment]
请问@xulihang 大哥可以帮忙写个python版本的吗？用网页没法在没网的地方使用啊

**Comment by xulihang** [comment]
https://[raw.githubusercontent.com/xulihang/BasicCAT-website/master/tools/image-translation-project-manager/index.html](https://raw.githubusercontent.com/xulihang/BasicCAT-website/master/tools/image-translation-project-manager/index.html) 网页下载到本地就可以离线用了

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/547b8b16-76ad-4f06-866f-202f3dbf5191)
厉害
