### ISSUE TITLE
我使用的這個字體豎排的時候（，。、）這幾個標點不顯示是怎麼回事？

### ISSUE THREAD

**Issue by kamikoshi-sorawo** [xulihang/ImageTrans-docs#44]

**Comment by kamikoshi-sorawo** [comment]
就是这个字體[DFLiHei-Md.zip](https://github.com/xulihang/ImageTrans-docs/files/6417086/DFLiHei-Md.zip)

**Comment by kamikoshi-sorawo** [comment]
[DFLiHei-Md.zip](https://github.com/xulihang/ImageTrans-docs/files/6417174/DFLiHei-Md.zip)

**Comment by kamikoshi-sorawo** [comment]
就是這個字體
[DFLiHei-Md.zip](https://github.com/xulihang/ImageTrans-docs/files/6417177/DFLiHei-Md.zip)

**Comment by xulihang** [comment]
竖排引擎是我自己实现的，目前是存在一些问题：

1. 文字不能自动调整大小
2. 标点符号的处理不是很完善，比如不同的字体表现不一致

你给的字体：
![image](https://user-images.githubusercontent.com/5462205/116955066-1cb31d00-acc4-11eb-812c-d47dfbc04a1b.png)

黑体：
![image](https://user-images.githubusercontent.com/5462205/116955263-9fd47300-acc4-11eb-8385-2585a402511b.png)

**Comment by kamikoshi-sorawo** [comment]
ok 我明白了

**Comment by xulihang** [comment]
v1.6.2对竖排引擎做了优化，标点应该都能显示了

![image](https://user-images.githubusercontent.com/5462205/160263710-d2826b74-7240-40cb-852d-ae15e2d4a35c.png)
