### ISSUE TITLE
图像修复设置

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#440]
图像修复方式怎样在生成掩膜那改，有些图用sickzil-machine的比较好，而有些用二值化比较好，但每次都得去设置里改图像修复方式。

我看https://github.com/xulihang/ImageTrans-docs/issues/192这个议题中出现了单独的图像修复选项框，这是咋调出来的？

还有就是PatchMatch图像修复为啥没用（日文完全没遮盖），是要和sickzil-machine一样装插件吗。

**Comment by xulihang** [comment]
PatchMatch的二进制文件是在我电脑上用Cygwin编译的，可能在你的系统环境用不了，需要自己重新编译一下（比较复杂）。

默认的掩膜生成方式和图像修复方式可以在项目设置里设置。

**Comment by sera1991** [comment]
https://user-images.githubusercontent.com/30548000/164956820-38afae50-d7dd-4fe0-b54a-98fc9f7b7163.png
最上面的框该怎么调出来

**Comment by xulihang** [comment]
这个是去除文字器，在编辑菜单里有

**Comment by lhj5426** [comment]
其实我觉得遇到难处理的图 用 .jpg-original 这种方式是最好 因为可以用其他的工具配合
举个例子
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b3d93bda-b6ee-43d2-b2d1-ef245d52794e)
就那这个图来说 这个图 网上的资源是没有提供无文字图
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/fe36fccc-c54d-4f18-873b-5598c4c6a66f)
而这是自己修的无文字图
两个文件夹的文件名
0002.jpg
0002.jpg-original.jpg
只要用这种改名的方法 可以不局限限于只用 ImageTrans
来修图 你可以用pS 甚至各种AI修图工具
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/f3f1beb6-a3ba-4cfb-be9d-19ebc7afe31e)
比如我最近找到的在用 一款不错的修图工具

用这种方法 非常轻松方便的就可以处理  ImageTrans 自身功能 无法处理完美的图 或者处理起来不理想的图
要善用 -original 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4a9db733-5d85-44fa-ae69-763e0a86e136)
这个功能

**Comment by sera1991** [comment]
还有个问题是为什么有些手动框选生成掩膜图会存放在软件根目录，我明明已经设置好文件路径了。。

**Comment by lhj5426** [comment]
> 还有个问题是为什么有些手动框选生成掩膜图会存放在软件根目录，我明明已经设置好文件路径了。。

我用了2年一直是存在文件相同目录的  其实眼不见为净
而且放在同级目录也方便对比
或者看着烦 可以这样 

https://github.com/xulihang/ImageTrans-docs/assets/30548000/6d36859f-9c9b-4fe9-8bf1-42340c6e4201

隐藏起来
如果想方便删除 直接筛选 就可以 了
在根目录下 没啥毛病
