### ISSUE TITLE
根目录总是多出很多文件

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#441]
![QQ图片20230625002321](https://github.com/xulihang/ImageTrans-docs/assets/30473573/1a38227f-f562-4e01-b2ae-7c55e3d06426)
用了tesseract-ocr就成这样了，多了好多文件，有时候生成掩膜和单独ocr图片也会生成在根目录，有办法设置在别的地方吗。

**Comment by xulihang** [comment]
tesseract-ocr的临时文件我是写了删除操作的，但可能没写好。

其它ocr和掩膜的图片我默认写在根目录，用的固定的几个文件名，目前没有修改设置
