### ISSUE TITLE
Request: Add A Backround Color of the Font.

### ISSUE THREAD

**Issue by WavaDev** [xulihang/ImageTrans-docs#443]
Can you add so you have a color in the backround of the font, so it can have the text everywhere on image.
Like This:
![image](https://github.com/xulihang/ImageTrans-docs/assets/127393002/47c7e23e-6ca5-478d-8af0-5f56afc1d76f)

**Comment by xulihang** [comment]
This is called stroke or shadow. You can set it in the font style settings.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/50973f67-ca4a-465a-86de-854185594d0b)

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/1f7d3933-ef91-462f-a1fb-9be165f5e4de)
