### ISSUE TITLE
怎么批量修改字体样式

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#444]
怎么批量修改字体样式，在设置里改了字体但只有一部分变了，还有很多依然是之前的字体。
看了下没改变的字体，都是启用了本地字体样式（好像是因为我单独调整过那些字体大小就自动启用了）。
所以能批量改变这些启用本地字体样式的字体吗，我试了下框选改字体但只能改变一个文本框的，怎么样能把框选的字体都改变。。

**Comment by xulihang** [comment]
点工具栏左侧的第二个按钮，切换到多选模式，选择多个框后点上方的统一字体按钮可以统一所选的框的样式为某个框的样式
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/112553fd-86ed-49c7-9ce9-aa91a0fb26f5)

**Comment by xulihang** [comment]
如果要批量删除本地样式，可以参考这个issue：https://github.com/xulihang/ImageTrans-docs/issues/364
