### ISSUE TITLE
排序问题

### ISSUE THREAD

**Issue by whyiskey** [xulihang/ImageTrans-docs#445]
开发者大大你好，因为启发式文本检索无法找到全部的文字所以需要手动拉框，但是新拉的框序号是排在最后的，因为有翻译组的文字对照要求需要对提取的文字排序，所有造成了一些麻烦，首先排序功能有问题，长条漫中各个文本框无法通过排序按键自动排序，会出现要么是1239456或者1234956这种情况，有没有按照h值（高度）排序的功能啊。谢谢啦

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/096e8c22-88ad-4615-b7f4-a2b57200d533)
有个功能j叫分镜 设置完分镜在排序能好点

**Comment by whyiskey** [comment]
> ![image](https://user-images.githubusercontent.com/30548000/249237291-096e8c22-88ad-4615-b7f4-a2b57200d533.png) 有个功能j叫分镜 设置完分镜在排序能好点 可以先试一试
> 
> 还有 可以用离线气泡识别 或者 manga-image-translatorrun 插件识别 自动识别完之后再排序也能好点 都在 网盘文件里 ![image](https://user-images.githubusercontent.com/30548000/249239892-59680f75-d034-4fd7-b4c9-487f9c5b24ab.png)

是这样的，漫画是一镜到底的所以分镜检测失败好像，希望能出个自义定排序功能，或者起码能手动输入序号不用鼠标从底部一下一下点上来hh

**Comment by xulihang** [comment]
目前只有按到坐标原点的距离一种排序方式，可以有这两个优化方式：

1. 加一个排序的设置选项，增加按纵坐标排序的方法
2. 输入序号来快速设定某个文字区域的顺序

**Comment by whyiskey** [comment]
> 目前只有按到坐标原点的距离一种排序方式，可以有这两个优化方式：
> 
> 1. 加一个排序的设置选项，增加按纵坐标排序的方法
> 2. 输入序号来快速设定某个文字区域的顺序

赞美！！！👍

**Comment by xulihang** [comment]
2.0.0关于排序的改动：

1. 切换到排序工具后，双击文字区域，可以手动输入序号。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/f11370e9-200a-4765-9083-9cb2b441f824)

2. 项目设置里增加了排序依据的设置，可以根据纵坐标排序：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/6f6b6a22-f128-47c4-a5c3-a3c2d02a2b61)
