### ISSUE TITLE
重嵌问题

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#446]
想问下这软件能进行重嵌吗。
（比如几年前的汉化作品，出了更高质量的图源，想把这些汉化的文字嵌入到高质量的图源上。）
有方法或者思路实现吗（想过ocr，但竖排的汉字不太容易识别，而且还要解决排序问题）
只是问问，没有的话就继续用ps重嵌了。。

**Comment by xulihang** [comment]
这个有用户提过的，我之前这样回复的：
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/947fd9da-5e03-4b84-89cf-974792ed09df)


https://www.bilibili.com/video/BV1Uo4y1Z7Wo/

**Comment by sera1991** [comment]
试着做了下，确实可以！
但有个问题，除了复制粘贴外，怎么把左侧ocr到的原文都填入右侧的译文栏内。因为虽然点“查看翻译”能正常显示中文，但对左侧文本进行修改不会反馈到图片的文本框里，得复制到右边译文栏才能修改
![QQ图片20230628144326](https://github.com/xulihang/ImageTrans-docs/assets/30473573/0503d657-ca14-4894-9f9a-67f3c0626649)
而且单击文本框会变成空白（先点右边填了译文的文本框，再点右边没填译文的文本框就会变成空白）
![QQ图片20230628144355](https://github.com/xulihang/ImageTrans-docs/assets/30473573/6f69b7c2-7143-42d8-8945-5f7e24101ec7)
有办法能解决吗。。

——————————
还有问题是manga-ocr和ocrspace只能用日文才能较准确地识别繁体字，简体字几乎识别不了。
如果用繁简识别会按从左至右从上至下的方式ocr（文本乱序）
所以想问下有没有能按日文ocr方式竖排识别中文的ocr，或者有什么设置能改成竖排识别吗。

**Comment by lhj5426** [comment]
我去年做过重嵌字 用了 在线的 百度 有道 OCR 发现对繁体识别真的不行
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/e3412277-18c1-478b-8a5d-6b7de5ec56d7)

**Comment by xulihang** [comment]
需要在项目设置里设置一下从右到左阅读，这样合并区域时会按从右到左的顺序操作。
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/72a27f90-bd1d-437b-b232-b3881d7251e8)

我试了下有道OCR的效果还可以。网易的漫威无限就是从世图出版的美漫提取翻译后重新嵌字的

**Comment by xulihang** [comment]
如果要把原文填入译文，可以这样操作：

导出-供翻译的文档，保存为docx文件。

编辑docx文件，把原文复制到译文列。
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/6c7ac347-1f14-448a-95d3-8ec37b0bec35)

然后在ImageTrans里导回翻译就行了

**Comment by sera1991** [comment]
> 我去年做过重嵌字 我是白黑白的重嵌到全彩上 用了 在线的 百度 有道 OCR 发现对繁体识别真的不行 ![image](https://user-images.githubusercontent.com/30548000/249435856-e3412277-18c1-478b-8a5d-6b7de5ec56d7.png)

繁体的话用日文ocr勉强可以对付（日文汉字和繁体基本相同），但简体识别就

> 需要在项目设置里设置一下从右到左阅读，这样合并区域时会按从右到左的顺序操作。 ![image](https://user-images.githubusercontent.com/5462205/249451578-72a27f90-bd1d-437b-b232-b3881d7251e8.png)
> 
> 我试了下有道OCR的效果还可以。网易的漫威无限就是从世图出版的美漫提取翻译后重新嵌字的

像这种竖排从右至左阅读的中文就没办法ocr了。。我把从右至左阅读打开了，但还是按横排识别中文。
![QQ图片20230628210947](https://github.com/xulihang/ImageTrans-docs/assets/30473573/885b7793-9379-4150-ab91-42cd55631a45)

**Comment by sera1991** [comment]
还有想问下软件自带的ocrspace的key是免费的吗，我在想要不要自己申请key。

**Comment by xulihang** [comment]
OCRSpace其实就是Windows10自带OCR，ImageTrans里叫WinRT。

你这里的文字都在气泡里，可以开启竖排转横排，就能识别了：
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/0ed2a5e5-cd8d-4699-abd2-f3b91edca976)

**Comment by xulihang** [comment]
是第一张图的选项。可以把框调得贴合文本一点，换不同的ocr识别一下

**Comment by sera1991** [comment]
> 是第一张图的选项。可以把框调得贴合文本一点，换不同的ocr识别一下

贴合后识别率倒是高了些，但还需要手动修改结果。。
不过比起用ps重嵌倒是方便许多。
说起来古籍的阅读顺序和日漫的差不多。。如果有支持古籍的ocr的话就能满足需求了。
