### ISSUE TITLE
识别期间双眼皮的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#447]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a990f375-4936-410e-ace0-92540aca9d62)
是这样的开发者老哥 

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/07b15f1d-2154-4db1-bff2-b532d936eacd)
这 自动识别所有气泡 对气泡识别的好 但是 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/036e25d0-3506-4e6d-8009-86eb9305adfe)
这种纯竖排文字无力 
然后 manga-image-translatorrun
 自然场景检测  对 这种 识别的还可以 
 但是 他会捎带手的 识别气泡
 然后它识别气泡的时候 会戴上大量的无意义文字
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b429b275-1f6f-4b35-9553-fcebbb7e6576)
一本漫画数百页 每页都有大量的无意义的文字被
 manga-image-translatorrun
 识别 在OCR之前就要手动去 删 很麻烦
 就是用所谓的置信度检测也不行
 所以 我想了办法是
 用 1 气泡识别 先 把气泡识别出来
 然后再用 2自然场景检测 来 单独检测 非气泡文字
 然后问题 就来  是出现了双眼皮
 所以能不能在批量识别的时候增加一个选项 或者设置
 假如入 图片有被气泡识别 就跳过这张图片 去识别下一张 
 这样就 杜绝了双眼皮的问题 先气泡识别完 然后 跑 manga-image-translatorrun 它发现 图片 已经被识别过了就自动跳过跳过跳过
 发现 纯文字图 没有被识别 就开始识别  这样的话就 不会出现双眼皮的情况了
要是只用 manga-image-translatorrun  识别 在 气泡页面 会产生大佬的无意义 框选 置信度检测不行 只能人工处理
几百也 少说也的半个小时 去删这些东西 

 而且OCR的话 双眼皮了OCR也会识别2遍  所以 必须清理干净
要是可以 实现 被识别就跳过 2个识别方式配合使用可以节省大量的删除 无意义 识别的时间

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/72d07371-a351-4619-8cc1-aadd7bec0c1d)
扫置信度的话 同样 也会带来大量的 重置置信度的问题

**Comment by lhj5426** [comment]
然后 双眼皮的问题可以通过
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/dfe113c4-e115-4b7b-b116-bfc450e21bda)

但最主要的问题是  manga-image-translatorrun 二次识别会产生大量的 无意义识别 这个 问题
双眼皮 只是附带的问题

**Comment by xulihang** [comment]
二次识别照理会判断图片里是不是有重叠的内容，重叠就不会添加上去的。

如果想跳过处理的话，可以用这个管理翻译的图片的功能，选中的图片会被认为已经翻译过了，处理时会被跳过。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/27556abe-4d28-4fc5-8a75-c48c1cf2bade)

要去除内部文字区域，也可以用这个功能，但我没做成支持操作所有图片的：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/38d6835f-3b5e-4b8a-ae3e-192f0de29a73)

**Comment by xulihang** [comment]
噢，你是想自动判断有没有识别出区域，识别出的图片就跳过，这个目前没这样的设定

**Comment by lhj5426** [comment]
> 二次识别照理会判断图片里是不是有重叠的内容，重叠就不会添加上去的。
> 
> 如果想跳过处理的话，可以用这个管理翻译的图片的功能，选中的图片会被认为已经翻译过了，处理时会被跳过。
> 
> ![image](https://user-images.githubusercontent.com/5462205/249453443-27556abe-4d28-4fc5-8a75-c48c1cf2bade.png)
> 
> 要去除内部文字区域，也可以用这个功能，但我没做成支持操作所有图片的：
> 
> ![image](https://user-images.githubusercontent.com/5462205/249455153-38d6835f-3b5e-4b8a-ae3e-192f0de29a73.png)

按理来说 应该是 会自动跳过 我也是这么认为的
因为OCR 或者 预翻译的时候 如果中断了 再重新运行 是会一张图检测如果检测到已经被OCR或者被翻译就会跳过的
所以我 想当然的以为 是不框选阶段也可以 但是 实际上实践之后 并不能所以有了这个帖子
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/161635aa-d9e0-448d-a0d8-592c4acf6778)
图片管理这个 不太可能 没有图 我也不知道哪张 是那张只能 软件和 资源管理器来回切换
其实这个也不是很好操作 嘿嘿

**Comment by lhj5426** [comment]
> 噢，你是想自动判断有没有识别出区域，识别出的图片就跳过，这个目前没这样的设定

是的  就是先 跑 气泡识别 跑完气泡识别 在跑 插件的识别 如果 扫到图片已经被识别框选过 就跳过

**Comment by xulihang** [comment]
发张图片给我吧，我看看怎么会有重叠的问题。

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/249468742-8e4ed719-c86a-430c-a86d-26757f3abb88.jpeg)

**Comment by xulihang** [comment]
2.0.0做了下面的改动：

1. 之前新检测到的区域如果比原有区域大，不会被滤除。2.0.0改成滤除。
2. 已翻译图片管理器里可以便捷选择有文字区域图片、有原文图片或者有译文图片。选中的图片在批处理时会被跳过。
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/b7444508-809a-4f6e-8918-eed115021048)

**Comment by lhj5426** [comment]
哦奈瑟  哈哈  这就去更新体验一下

**Comment by lhj5426** [comment]
2.0引入了一个更严重的问题 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2eddac09-34c6-4085-80aa-08d3343cd3cb)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/77493055-5154-46d4-986e-20f7db88657f)
之前1。9几的时候
这种图人物的身上不会被识别 更不会被这么夸张的是被框选
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/10b9e4ad-f1c2-4393-8878-c6d9d7e3abad)

**Comment by xulihang** [comment]
这个是启发式文字识别吧，这个本来就是这样的。

**Comment by lhj5426** [comment]
> 这个是启发式文字检测吧，这个本来就是这样的。

不是 单图的时候调用了 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c2529e24-ee38-4b1f-96c9-134706b60f12)

批量的时候没有调用 现在
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/589e3732-a68e-4698-b435-1b7b7e0af13f)

**Comment by lhj5426** [comment]
之前批量的时候 也是会调用这个的 ？ 发问题时候的截图 检测就没这么多方块

**Comment by lhj5426** [comment]
先自然场景 和启发式 在批量里 几乎是一个功能 不会调用外部插件

**Comment by xulihang** [comment]
我用manga-translator做自然场景文字检测，只有文字区域是被识别的。用项目-批处理的自动定位所有图片的文字（自然场景检测）
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/9001e6b8-2ba4-4118-a23f-f24962031f63)

**Comment by lhj5426** [comment]
> -批处理的自动定位所有图片的文字

我就用的这个功能呀 之前是这样的  今天更新完之后 就变成检测出一堆方块了 等我去重新安装一下插件

**Comment by lhj5426** [comment]
> 我用manga-translator做自然场景文字检测，只有文字区域是被识别的。用项目-批处理的自动定位所有图片的文字（自然场景检测） ![image](https://user-images.githubusercontent.com/5462205/250337134-9001e6b8-2ba4-4118-a23f-f24962031f63.png)

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a1df5345-d301-4a06-92ce-1450745b1523)
那我这是为啥呢？ 插件重新安装重新下了 用的 项目 批量 里的自然检测
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1615006a-e32d-47e2-8cbf-a3840d6e4a03)
就出来这么多方块呢

**Comment by xulihang** [comment]
项目文件发给我看一下

**Comment by lhj5426** [comment]
> 项目文件发给我看一下

不好意思 老哥 是我的锅  我不知道为什么勾选么了翻转颜色导致了 一堆方块
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/04f79f22-587f-40d8-a68f-5b7fae3e7c53)
删了之后好了
还有老哥 能不能想想办法让扫码置信度的时候 可以更准确的判断下 这个 非文字区域？

**Comment by xulihang** [comment]
这个需要自己重新训练一个模型。

1. 保留图片中置信度低的区域

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/53f38cb9-2eee-4041-8959-8f1289b741c1)

2. 导出用于训练的文字区域图像和非文字区域图像

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/11f6d945-66e1-4726-b809-0e263eabbf33)

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/91a81629-b7ee-4605-bcbb-413150f62285)

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/493028d5-c45e-4862-abcb-be2dfe42ef3a)

3. 用tensorflow的[make_image_classifier](https://github.com/tensorflow/hub/tree/1d2684eeec673f0c1be108309650ce282574782d/tensorflow_hub/tools/make_image_classifier)训练一个模型，保存为frozen_graph.pb，替换ImageTrans里的模型。这一步需要自己跑脚本和配环境，目前没有一个傻瓜式的操作工具。

**Comment by lhj5426** [comment]
> 这个需要自己重新训练一个模型。
> 
> 1. 保留图片中置信度低的区域
> 
> ![image](https://user-images.githubusercontent.com/5462205/250338779-53f38cb9-2eee-4041-8959-8f1289b741c1.png)
> 
> 2. 导出用于训练的文字区域图像和非文字区域图像
> 
> ![image](https://user-images.githubusercontent.com/5462205/250338902-11f6d945-66e1-4726-b809-0e263eabbf33.png)
> 
> ![image](https://user-images.githubusercontent.com/5462205/250338909-91a81629-b7ee-4605-bcbb-413150f62285.png)
> 
> ![image](https://user-images.githubusercontent.com/5462205/250338918-493028d5-c45e-4862-abcb-be2dfe42ef3a.png)
> 
> 3. 用tensorflow的[make_image_classifier](https://github.com/tensorflow/hub/tree/1d2684eeec673f0c1be108309650ce282574782d/tensorflow_hub/tools/make_image_classifier)训练一个模型，保存为frozen_graph.pb，替换ImageTrans里的模型。这一步需要自己跑脚本和配环境，目前没有一个傻瓜式的操作工具。

好恨自己不懂啊 哈哈  谢谢  我还是手动把 看不懂代码哈哈哈 虽然有GPT 但是跨界还是挺麻烦的
而且gtp也很智障经常问东说西 或者 就复读机
