### ISSUE TITLE
竖排设置里的关于 竖排方括号替换应该要怎么操作

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#449]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/650551e4-a9c6-4ab4-8167-eaa2f54df6af)
我久违的制作全部文字无气泡的漫画字幕
打算做的美观一点 打上方括号方便排版
刚好前段时间更新了这个功能
今天按照 括号的格式去改了
但是没有成功？ 是为什么呢
我 哪里该错了？
{
  "（":"︵",
  "）":"︶",
  "『":"﹃",
  "』":"﹄",
  "「":"﹁",
  "」":"﹂",
}
请教教我 感谢 老哥
我都是复制括号 然后替换成方括号符号应该没有使用错？

**Comment by xulihang** [comment]
最后
最后这条多了个逗号，解析失败了。

```diff
{
"（":"︵",
"）":"︶",
"『":"﹃",
"』":"﹄",
"「":"﹁",
- "」":"﹂",
+ "」":"﹂"
}
```

**Comment by xulihang** [comment]
我再加个验证功能吧

**Comment by lhj5426** [comment]
> 我再加个验证功能吧

嗯 感谢

**Comment by xulihang** [comment]
加了个验证按钮，如果JSON格式有误，会提示哪个位置不对。
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/9b81874c-8b4a-4456-b035-5a63426627ff)
