### ISSUE TITLE
导出excel的时候不包含译文信息

### ISSUE THREAD

**Issue by linkstree** [xulihang/ImageTrans-docs#45]
你的WIKI上面写的可以导出译文信息但是导出之后没看到译文信息
![image](https://user-images.githubusercontent.com/18115991/116977880-a0bcd300-accb-11eb-97ad-b2c42f4549d0.png)
![image](https://user-images.githubusercontent.com/18115991/116977980-c5b14600-accb-11eb-9be5-65b11e764a95.png)

**Comment by xulihang** [comment]
这个功能最初是用来导出原文，给翻译项目经理分发给译员用的，所以没考虑译文。选择生成PSD也会生成上图这样的表格，可以选择是否用译文替代原文。
按目录导出有设计译文的表头，我看了下代码，发现漏加了译文一栏，我补上了。

**Comment by xulihang** [comment]
1.3.7导出的数据有译文了
