### ISSUE TITLE
2.0版 无框选气泡的时候不显示图片

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#453]
因为我做的漫画都不是什么能上大雅之堂的 所以 为了避免尴尬我打了马赛克

是这样的开发者老哥  我现在在用2.0 继续制作 昨天没有制作完的漫画
在 遇到如视频这样的图片时候  图本身无任何文字 也不需要进行翻译 没有 一个文本框的时候

https://github.com/xulihang/ImageTrans-docs/assets/30548000/7fbd9431-e12c-4e44-a3b1-953afdf0c2d4

 切换到查看翻译 整个图片就不显示了 
 但是 在昨天还在使用的198版本

https://github.com/xulihang/ImageTrans-docs/assets/30548000/7836deb0-86fb-4d63-aba2-6c8ddcb657bd

就不存在这个问题 同样的一页 没有任何气泡框选 
在点击 查看翻译的时候 会正确显示出 0108.jpg-original.jpg 这个图
这个问题可能会影响到 导出的时候 缺页的问题
所以 想问下这个是 bug吗？

**Comment by xulihang** [comment]
重新下一份，这个问题我后来修了

**Comment by xulihang** [comment]
查看翻译时，如果有文本框，会在原图上覆盖一层无文字图。新版我为了提升大图的显示性能，会把无文字图后面的原图隐藏。我后来又更新了下文件，没有文本框时点查看翻译不隐藏原图

**Comment by lhj5426** [comment]
> 查看翻译时，如果有文本框，会在原图上覆盖一层无文字图。新版我为了提升大图的显示性能，会把无文字图后面的原图隐藏。我后来又更新了下文件，没有文本框时点查看翻译不隐藏原图

ooo   嗯 好的我 去网盘瞅瞅 重新下一个

**Comment by lhj5426** [comment]
可能我下的太早了 哈哈  所以遇上了 这个版本 十分感谢  

> 查看翻译时，如果有文本框，会在原图上覆盖一层无文字图。新版我为了提升大图的显示性能，会把无文字图后面的原图隐藏。我后来又更新了下文件，没有文本框时点查看翻译不隐藏原图

可能我下的太早了 哈哈  所以遇上了 这个版本 十分感谢
