### ISSUE TITLE
使用过程遇到的一些小问题

### ISSUE THREAD

**Issue by whyiskey** [xulihang/ImageTrans-docs#455]
开发者大大你好，我在实际使用的时候遇到了一些问题或许可以优化一下下
    1 首先是删除文本框，使用快捷键（组合键加delete那个）会随机连带删掉周围的文本框，操作的时候可以看到未被选中的框也会被连累，这个怎么说有的时候挺方便的，可以一下去除很多无用框，但也会伤及无辜需要手动拉（撤销操作也是恢复多个）。而右键，选择删除则没有这个问题
    2 其次是跳转问题，我看到双击右下角的列表可以快速跳转到图片具体位置，但是反过来双击图片的文本框却不行。这一点用起来还是有些难受的，35000长度的图要上上下下的拉。（如果能够和快捷键-上一个区域Ctrl+Open Bracket联动就更好了）
    3 还有就是导出翻译doc文档,可以看到表格消失了，这个问题不是每次都会出现，有些项目没有问题
![图片](https://github.com/xulihang/ImageTrans-docs/assets/135958188/6a803b87-0f21-4268-91f9-634f7b8dcac4)
![图片](https://github.com/xulihang/ImageTrans-docs/assets/135958188/21924841-1ab6-4bd4-971e-e592421dc9de)
![图片](https://github.com/xulihang/ImageTrans-docs/assets/135958188/419e8370-cc7f-439e-be47-f657e14ded91)
谢谢拉，很好用的软件

**Comment by xulihang** [comment]
1. 删除直接按Delete键就行了。我才发现还绑定了一个Ctrl+Delete的菜单，你用这个会导致触发两次删除。新版我会把这个快捷键删了。
2. 在列表选中文字区域时，也跳转到图片对应的位置。如果文字区域不可见时，我给它跳转一下吧
3. 能发个重现问题的项目我测一下吗

**Comment by xulihang** [comment]
我用WPS打开导出的docx是没问题的，可能高版本的Word有一点兼容问题

**Comment by whyiskey** [comment]
okk明白了，工具太新反而不美hh

**Comment by xulihang** [comment]
2.1.0修复了删除快捷键的冲突问题，并添加了跳转功能，需要点击文字区域列表右边的F按钮来启用。

https://github.com/xulihang/ImageTrans-docs/assets/5462205/579febba-cfb8-4e54-83b6-cd44302e089c

**Comment by whyiskey** [comment]
> 2.1.0修复了删除快捷键的冲突问题，并添加了跳转功能，需要点击文字区域列表右边的F按钮来启用。
> ice_video_20230709-133646.mp4

nice!
