### ISSUE TITLE
Failed to connect to ImageTrans server

### ISSUE THREAD

**Issue by NNNnot** [xulihang/ImageTrans-docs#457]
已经按教程设置好了，但也使用插件点击翻译就出现未连接服务器，但软件上的服务器显示已连接

**Comment by xulihang** [comment]
照[这里](https://github.com/xulihang/ImageTrans_chrome_extension)说明的，访问https://local.basiccat.org:51043/translator看看服务器有没有运行

**Comment by NNNnot** [comment]
> 照[这里](https://github.com/xulihang/ImageTrans_chrome_extension)说明的，访问https://local.basiccat.org:51043/translator看看服务器有没有运行

访问不了，[ImageTrans_wsServer.jar]也已经下载了替换了原先那个，其余步骤和教程是一样的

**Comment by xulihang** [comment]
用的百度网盘里提供的完整版吗

**Comment by xulihang** [comment]
还有先不要用翻墙软件

**Comment by xulihang** [comment]
目前是只能翻译鼠标下方的单张图片。
