### ISSUE TITLE
关于文字的调整边框的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#458]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/273395bb-7e3a-472e-b11c-a10d76d9f30e

https://github.com/xulihang/ImageTrans-docs/assets/30548000/09d1ace5-0ef2-43e2-af46-ff8876dc312a

开发者 老哥 
这个字边框 调整的问题 可以优化下吗

**Comment by lhj5426** [comment]
就是 点击文字的时候文字 跑到边框的最上边了
然后 这个时候调整 边框的话 从翻译模式切换到日文模式再切换回翻译模式的时候
文字经常会自动向下位移 而这个位置的位置时间上是上次边框的顶部

**Comment by lhj5426** [comment]
还有就是能不能请老哥增加一个功能
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/90e12ca5-b10c-4345-bc33-7cbb766e9832)
在这里增加一个 查看翻译的时候可以显示原始日文图层 目的是为了 方便和日文对齐文字对齐
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1496e21d-21c3-44ff-bc94-e308fe2d1440)
目前这样设置可以 显示日文原文 但是 只有部分能显示 
所以恳请老哥能不能增加一个独立 的 在查看翻译的时候可以显示日文图层
或者说把文字可以显示在日文图层上？

**Comment by xulihang** [comment]
这是设置了垂直居中，修改翻译文本实时预览这个操作没考虑这个设置。

如果不启用右边的自动保存是没问题的。

**Comment by xulihang** [comment]
显示原图和与原文对齐我考虑一下怎么做比较好。

**Comment by lhj5426** [comment]
> 这是设置了垂直居中，修改翻译文本实时预览这个操作没考虑这个设置。
> 
> 如果不启用右边的自动保存是没问题的。

不启动自动保存 经常就白修改 翻译结果 因为实在是 记不住 保存

所以 就只能恳请 开发者老哥 给优化下了

 嗯 感谢 有原图对比图层 调整 字的位置也能舒服点

**Comment by xulihang** [comment]
2.1.0修复了垂直居中不生效的问题，然后添加了一个新的工具栏用于调整透明度和对齐原文和译文


https://github.com/xulihang/ImageTrans-docs/assets/5462205/cecb3fe6-2c84-4169-9ed7-c09288f6fff8

**Comment by lhj5426** [comment]
> 2.1.0修复了垂直居中不生效的问题，然后添加了一个新的工具栏用于调整透明度和对齐原文和译文
> 
>  ice_video_20230709-134105._mp4_

这个厉害 开发者老哥的这个设计 还有透明图层了 马上下去去体验

**Comment by lhj5426** [comment]
> 2.1.0修复了垂直居中不生效的问题，然后添加了一个新的工具栏用于调整透明度和对齐原文和译文
> 
>  ice_video_20230709-134105._mp4_

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d9d2feee-014c-45ad-8032-7f9b5dcb914e)
妥妥的好用 感谢 这样就不需要来回切换 翻译模式和原文模式来调整了

**Comment by lhj5426** [comment]
> 2.1.0修复了垂直居中不生效的问题，然后添加了一个新的工具栏用于调整透明度和对齐原文和译文
> 
>  ice_video_20230709-134105._mp4_

然后还有一个问题 老哥需要优化下
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/af4bfffe-3160-499f-9b02-39d166b934c0)
就是导出的时候 能不能自动关闭 排版模式 和图层模式呢？

**Comment by xulihang** [comment]
新的问题麻烦开个新的issue
