### ISSUE TITLE
在一个项目中无法删除某个图片

### ISSUE THREAD

**Issue by linkstree** [xulihang/ImageTrans-docs#46]
![image](https://user-images.githubusercontent.com/18115991/116978117-f6917b00-accb-11eb-848a-01243dcc66a1.png)

**Comment by xulihang** [comment]
图片上右键删除
![image](https://user-images.githubusercontent.com/5462205/116978752-b8f61780-acf6-11eb-88b4-53a468e7c049.png)

**Comment by linkstree** [comment]
ok

**Comment by linkstree** [comment]
在我从一个项目里面删除一些图片之后我想另存这个项目为另一个版本，麻烦实现一下这个功能吧

**Comment by xulihang** [comment]
可以直接复制项目文件做到这点

**Comment by linkstree** [comment]
建议下一个版本添加另存为，目前这个issue先挂在这里用于跟踪

**Comment by xulihang** [comment]
v1.4.0添加了另存为功能
