### ISSUE TITLE
在导出的时候 可以自动关闭 排版模式的边框 以及 最新增加的 透明图层模式么

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#461]
尊敬的开发者老哥
感谢您今天2.10版本增加的图层模式
该模式 对编辑图片译文的时候提供极大的便利
因为不需要摸瞎 来回切换 查看翻译 模式和原文模式 
也减少了大量的译文位置调整时间
但是在使用的时候遇到了一点瑕疵问题 
希望请您能优化下
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/805cd8b3-51fd-43d0-a764-c05bdf9958c0)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/fdbedab1-3208-4c2d-a67d-90c1b78da853)
就是在导出 成品图片的时候 不管是批量 还是 单张
因为有的用户 经常会忘记 关闭 排版模式 和 透明图层模式
导致导出的图片
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/58edef99-a01a-416f-89a4-35ff7110018a)
是这个样子 又带有编辑的边框 还带有 透明图层
所以 可不可以 恳请 老哥 优化下这方面
在导出的时候 不管是单张 还是批量的
都可以自动关闭 排版模式的边框 和透明图层 
这样就算 有的用户 一时间忘记了关闭 这个功能 
也不需要重新再导出图片了 这样对用户来说更友好也更方便
拜托了

**Comment by xulihang** [comment]
给批处理和导出单张都加上了

https://github.com/xulihang/ImageTrans-docs/assets/5462205/d0354610-a99f-4cfe-849c-539314f0ae3e

就不算新版了，我直接把2.1.0的文件更新了

**Comment by lhj5426** [comment]
> 给批处理和导出单张都加上了
> 
>  ice_video_20230709-145019.mp4 
> 就不算新版了，我直接把2.1.0的文件更新了

感谢 我这就更新文件看看

**Comment by lhj5426** [comment]
再次感谢 这样 脑子不好使的用户 在导出的时候就再也不担心总忘记关设置了 谢谢

**Comment by xulihang** [comment]
下了吗，我又更新了下文件。因为新增的透明度的功能，没有文字区域的图又显示空白了，我把这个修了下。

**Comment by lhj5426** [comment]
> 下了吗，我又更新了下文件。因为新增的透明度的功能，没有文字区域的图又显示空白了，我把这个修了下。

那我再下一遍

**Comment by lhj5426** [comment]
> 下了吗，我又更新了下文件。因为新增的透明度的功能，没有文字区域的图又显示空白了，我把这个修了下。

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/40180750-9922-4dd8-b83e-b869634fdddd)
是的这次修好了
对了 这个在2.0的时候 虽然可以显示无气泡的框选的图片 但是 切换的时候需要开关一下翻译模式然后才显示 不然还是不显示
这次您修好了 切换直接就显示了 而不需要再开关一下 查看翻译模式了

**Comment by lhj5426** [comment]
我去 
我只能说开发者老哥想的周到
我编辑图片的时候是58%
然后我痛鼠标输入标点的时候不小心按错了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/52ef8189-038c-4edf-b0ba-ccc02645b0c9)
按成了导出图片 然后 该页 就自动放到100% 并导出了  
这下导出的时候连缩放都不需要重新调整100%了 想的太全面了 大感谢！！！！！
