### ISSUE TITLE
更新说明在哪查看？

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#466]
发现更新了2.1.0，想知道更新了哪些内容，但找不到更新说明。。

**Comment by xulihang** [comment]
https://www.basiccat.org/zh/imagetrans/#%E5%8F%91%E5%B8%83%E6%97%A5%E5%BF%97

**Comment by sera1991** [comment]
> https://www.basiccat.org/zh/imagetrans/#%E5%8F%91%E5%B8%83%E6%97%A5%E5%BF%97

好的，感谢。
