### ISSUE TITLE
关于掩膜编辑的颜色能不能全项目固定

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#467]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2c94e35c-cfd5-4a2e-bc2a-102198a62887)
是这样的的尊敬的开发者老哥
我今天在做漫画字幕的时候
发现个小小的问题 如图您看到的
这个气泡里的心 是粉红色的 然后 有部分没有被掩码覆盖到
当我打开掩码编辑的时候 
说实话 虽然可以直接上去瞎涂抹一下
但是 还是想能够具体的看清楚
虽然掩膜编辑
 有颜色选择 但是并不能固定这个颜色
 您看当我在213换了一个颜色之后
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/56624371-4e59-4cf6-a261-b8361f373afa)

切换页面之后214页
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/9bb9ab52-e2a9-453a-a6fd-0af3b795e93c)
又变回红色了
我知道这是一个小概率事件 但是看着还不太舒服
所以您能不能在项目管理掩膜的界面
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/798e1f02-a6cf-435d-9155-f2ab6c77b434)
增加一个掩膜颜色选择的功能 ？这样就可以全局用撞色 来查看 清晰明了 
在项目设置里增加一个全局颜色选择
在掩膜编辑界面 增加颜色选择固定  就是切换页面在掩膜界面选择的涂抹功能的 颜色还是上一页的这样固定
这种的功能

**Comment by xulihang** [comment]
掩膜编辑器可以加一个记住上次设置的行为
然后项目设置里加个颜色设置

**Comment by lhj5426** [comment]
感谢 ~

**Comment by xulihang** [comment]
2.2.0加了一个记住之前颜色的功能

**Comment by lhj5426** [comment]
> 2.2.0加了一个记住之前颜色的功能


https://github.com/xulihang/ImageTrans-docs/assets/30548000/9ccfb4c4-39ba-4481-93dc-2ff9a71dba16

这样就很棒 
不过还有一个小小的愿望
就是能不能恳请开发者老哥默认启用半透明
而且在您开不是方块的涂抹 模式 而是大面积拉框 的时候 这个拉框可以不可以也是半透明的

**Comment by lhj5426** [comment]
感谢 这样就方便很多 了
