### ISSUE TITLE
如何不生成掩膜

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#468]
比如我有现成的去文字图，我想点查看翻译时不使用掩膜，该怎么做。。

**Comment by sera1991** [comment]
还想吐槽下lama图像修复，今天生成高分辨率去文字图才发现lama会严重降低图像质量，换成软件自带的telea就不会
![QQ图片20230716051224](https://github.com/xulihang/ImageTrans-docs/assets/30473573/13c6f7be-3353-48a8-b81c-434818c5185e)
telea修复
![QQ图片20230716051311](https://github.com/xulihang/ImageTrans-docs/assets/30473573/118c7a11-ac0b-43e4-b2b1-48c54863cc0a)
lama修复

不知道是不是我哪里没设置好，毕竟lama对背景文字去除效果我觉得是最好的。。

**Comment by xulihang** [comment]
lama支持的最高分辨率有限，参见这个issue：https://github.com/Sanster/lama-cleaner/issues/18

可以在项目设置里改成按文字区域去除文字。

**Comment by xulihang** [comment]
有去文字图，可以用无文字原图管理器使用，见这里：https://github.com/xulihang/ImageTrans-docs/issues/199#issuecomment-1133639931

**Comment by xulihang** [comment]
可以把去文字图保存为图片名+`-original.jpg`，就可以使用了
