### ISSUE TITLE
字体bug

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#469]
今天打开模板发现省略号往左靠，但之前用同一字体做的翻译省略号是居中的。然后我打开了之前汉化的文件，省略号确实是居中的。
再次打开模板，发现省略号这次能够正常居中了（但是不能调整粗细了），但重启软件后省略号又变回原样，得重新上一步才能居中。
——
新建项目设置一样的字体，发现也能正常居中显示。不知道是不是bug。。

https://github.com/xulihang/ImageTrans-docs/assets/30473573/c28ca20a-38e3-4cff-9439-c43942cb0b72

[新建文件夹 (2).zip](https://github.com/xulihang/ImageTrans-docs/files/12063627/2.zip)
这是显示正常的和出错的文件

**Comment by xulihang** [comment]
横排状态下省略号靠下的字体，竖排时会靠左。目前没有办法设置合适的偏移量让它居中。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/4561dc13-c48a-4496-b107-26475a8c55b7)
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/5e59c743-2ad3-4fd4-ab60-9f1793ad7d6c)

**Comment by xulihang** [comment]
至于为什么不同项目不一样，虽然不同的项目同一个字体名字，但其实对应的字体文件可能并没有对应同一个字体文件

**Comment by sera1991** [comment]
> 至于为什么不同项目不一样，虽然不同的项目同一个字体名字，但其实对应的字体文件可能并没有对应同一个字体文件

感谢，刚在设置那把字体重新安装了下确实正常显示了。
进一步尝试，我把字体文件移动到别的路径后发现省略号再次向左对齐。
那就能解释视频里的问题了——找不到字体文件的项目调用了汉化项目里对应字体文件路径，所以能够正常显示。那之前省略号向左的字体就是系统默认字体了。。

还想问下有办法像这里的数字一样两个并排吗
![QQ图片20230716181111](https://github.com/xulihang/ImageTrans-docs/assets/30473573/754e8cc6-cb7b-4824-a5f1-b09400c97cf1)

**Comment by xulihang** [comment]
不同的问题麻烦发个新issue。数字并排旧版本是支持的，效果不好我后来取消了
