### ISSUE TITLE
按钮切换的时候，引擎和语言都无法固定

### ISSUE THREAD

**Issue by linkstree** [xulihang/ImageTrans-docs#47]
![image](https://user-images.githubusercontent.com/18115991/116978439-64d63d80-accc-11eb-9676-67fc9a47123e.png)

**Comment by xulihang** [comment]
这个问题的确不是很方便，我研究下怎么处理比较合适

**Comment by xulihang** [comment]
1.3.7修复了这个问题

**Comment by linkstree** [comment]
fixed
