### ISSUE TITLE
Support of Image Translation API

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#470]
There are image translation APIs provided by companies like Yandex and Baidu, which sends the image to the server and gets the OCR result, machine translation and the translation injected image.

We can create OCR plugins for such services. ImageTrans has to be adapted so that OCR plugins can also set the translation of text boxes.

**Comment by xulihang** [comment]
I've implemented Baidu Fanyi's image translation plugin: https://github.com/xulihang/ImageTrans_plugins/tree/master/imgBaiduOCR

It requires APPID and KEY to be set. You can get it in Baidu Fanyi's webpage: https://fanyi-api.baidu.com/api/trans/product/desktop

Then fill them in the preferences:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/fd555f5c-e009-4699-adaa-466b42d896fb)

It has a fee quota which is 10000 times per month.

**Comment by lhj5426** [comment]
嗯 其实有道也有相关的相关的 图片翻译
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/051a7953-385f-4cf6-844f-3943a0f33a99)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8c48c7ad-d9e5-4d6d-8025-5aa0f9a7351f)
