### ISSUE TITLE
掩膜编辑 可不可以 默认启用半透明并且 拉框模式也启用半透明

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#472]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/b9789496-8fa9-4b97-a58f-d51745460747

感觉老哥今天更新了 掩膜颜色 固定 这样就不担心在出现撞色文字的时候 每次都需要调整了 
但是还有一个小愿望
就是 能不能恳请开发者老哥 在掩膜启动的时候**默认**激活**半透明**
并且在 不是小方块的涂抹模式 而是大面积的拉框模式的时候这个**拉框的过程中 也可以显示半透明** 视频的最后几秒钟这里

**Comment by xulihang** [comment]
我考虑下怎么实现

**Comment by xulihang** [comment]
默认半透明，拉框半透明和使用选择的颜色加在2.2.1里了。

不过如果修复模式是用颜色覆盖文字，默认不半透明。

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/80b8daf2-7852-49d4-ab77-4c1ddcb73a97)
嗯..... 切换到涂抹方式还得双击下 半透明 才可以实现半透明 其实不透明就是异端哈哈 
感觉应该是全部都半透明更舒服？方便

**Comment by xulihang** [comment]
涂抹模式时也是半透明的。

颜色覆盖文字指这个：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/e2efcf88-1821-49a0-b30a-407d58a01bd8)

我发现掩膜保存时没有成功恢复图像为不透明，我会再更新下百度网盘的文件。

**Comment by lhj5426** [comment]
> 涂抹模式时也是半透明的。
> 
> 颜色覆盖文字指这个：
> 
> ![image](https://user-images.githubusercontent.com/5462205/258621087-e2efcf88-1821-49a0-b30a-407d58a01bd8.png)
> 
> 我发现掩膜保存时没有成功恢复图像为不透明，我会再更新下百度网盘的文件。

我先去更新下文件看看

**Comment by lhj5426** [comment]
> 涂抹模式时也是半透明的。
> 
> 颜色覆盖文字指这个：
> 
> ![image](https://user-images.githubusercontent.com/5462205/258621087-e2efcf88-1821-49a0-b30a-407d58a01bd8.png)
> 
> 我发现掩膜保存时没有成功恢复图像为不透明，我会再更新下百度网盘的文件。


https://github.com/xulihang/ImageTrans-docs/assets/30548000/0230a3a9-25fc-423f-bf5e-b2733d774d1d

太棒了 全都半透明了
