### ISSUE TITLE
能不能的符号 “— ”进行一下间距的优化？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#473]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d8fe2a98-5375-4cf8-b241-f32d616c489b)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2ac62e44-ddd2-4437-ab57-8ce02796d82e)
如图 其实真的有点 小别扭的
这个竖线符号 ｜ 2个之后中间都会个缝隙
可不可以请老哥对这个
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/30407eb0-7d6a-4f41-b648-58ad16b804ea)

全角竖线 做一下优化 复数个数中间无间隔

**Comment by xulihang** [comment]
目前把间距设置成0的话是可以连在一起的，我考虑下怎么给破折号单独设置间距

**Comment by xulihang** [comment]
2.2.1的竖排引擎添加了一个零间距字符的设置功能，默认是破折号。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/07125549-0d4f-46fa-8f5d-f0b34d5cd105)

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5e8c6de6-6d75-46e6-b731-8259cb26bf6f)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/3a72f5a9-03fa-4944-b2fb-caf71bf74153)
牛逼 续 波浪号 修正之后破折好也修正了
不过 那个开发者老哥 可以 给这个符号也弄成破折好的样子吗 就是
这个 字符 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/27e5bc5f-50fa-4dda-ab55-b89a54a957a2)
搜狗输入法打 shu 这个拼音 出来的这个丨
因为很像破折号而且 有点粗并且看着 很对其
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d3d7b7b7-f679-482d-aa3a-a0760564de70)
破折号的话 有一点偏 哈哈
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/3bb7a40a-d9c4-454c-8061-be775da110c5)
 这个丨 字符 一般情况下 很少用到 就连在一起显示也不会对文字造成任何的问题
 能否考虑一下？

**Comment by xulihang** [comment]
这个实现还是有点复杂的，一时间搞不定

**Comment by xulihang** [comment]
这个竖线的间距会受到字体影响，可以用富文本把竖线的字体设置成System看看是不是连起来了。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/e91ff3f4-3b3b-494e-b6c2-1b9c9ed36389)

**Comment by lhj5426** [comment]
> 这个竖线的间距会受到字体影响，可以用富文本把竖线的字体设置成System看看是不是连起来了。
> 
> ![image](https://user-images.githubusercontent.com/5462205/258621521-e91ff3f4-3b3b-494e-b6c2-1b9c9ed36389.png)

嗯好的我试试

**Comment by lhj5426** [comment]
> 这个竖线的间距会受到字体影响，可以用富文本把竖线的字体设置成System看看是不是连起来了。
> 
> ![image](https://user-images.githubusercontent.com/5462205/258621521-e91ff3f4-3b3b-494e-b6c2-1b9c9ed36389.png)

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/91090f09-b3e7-470d-96a7-31acd815ae3e)

完美  用这个字体的破折 就是粗的 哈哈而且居中
