### ISSUE TITLE
美漫最好的ocr是不是baidu accurate？

### ISSUE THREAD

**Issue by yogimator** [xulihang/ImageTrans-docs#474]
每天用一会就不给用了，我要买哪个api才可以调用这个呢？
另，tesseract对美漫的ocr真的太糟糕了  似乎漫画里的加粗和斜体他都没办法处理

**Comment by xulihang** [comment]
百度文字识别：https://cloud.baidu.com/product/ocr.html 高精度版1000次21元。ImageTrans默认每天提供500次调用，但是全部用户共享的。

或者用百度翻译的图片翻译功能，每个月1万次免费额度：https://fanyi-api.baidu.com/

**Comment by yogimator** [comment]
> 百度文字识别：https://cloud.baidu.com/product/ocr.html 高精度版1000次21元。ImageTrans默认每天提供500次调用，但是全部用户共享的。
> 
> 或者用百度翻译的图片翻译功能，每个月1万次免费额度：https://fanyi-api.baidu.com/ 。百度翻译这个OCR插件叫imgbaidu是2.2.0新加的

原来如此 我说为什么经常零点之后十几分钟就null了

**Comment by yogimator** [comment]
> 

另有个便宜的 ydocr.com

**Comment by yogimator** [comment]
> 百度文字识别：https://cloud.baidu.com/product/ocr.html 高精度版1000次21元。ImageTrans默认每天提供500次调用，但是全部用户共享的。
> 
> 或者用百度翻译的图片翻译功能，每个月1万次免费额度：https://fanyi-api.baidu.com/ 。百度翻译这个OCR插件叫imgbaidu是2.2.0新加的

更新是直接把插件拷贝进去吗

**Comment by lhj5426** [comment]
> > 百度文字识别：https://cloud.baidu.com/product/ocr.html 高精度版1000次21元。ImageTrans默认每天提供500次调用，但是全部用户共享的。
> > 或者用百度翻译的图片翻译功能，每个月1万次免费额度：https://fanyi-api.baidu.com/ 。百度翻译这个OCR插件叫imgbaidu是2.2.0新加的
> 
> 更新是直接把插件拷贝进去吗

下载完整包默认已经带了可以直接选 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/cf83148c-9439-4d85-9cf5-3b70f6917a52)

**Comment by yogimator** [comment]
我只有买的时候从邮箱收到了地址   后面版本 的下载地址在哪里找呢

**Comment by yogimator** [comment]
> > > 百度文字识别：https://cloud.baidu.com/product/ocr.html 高精度版1000次21元。ImageTrans默认每天提供500次调用，但是全部用户共享的。
> > > 或者用百度翻译的图片翻译功能，每个月1万次免费额度：https://fanyi-api.baidu.com/ 。百度翻译这个OCR插件叫imgbaidu是2.2.0新加的
> > 
> > 
> > 更新是直接把插件拷贝进去吗
> 
> 下载完整包默认已经带了可以直接选 ![image](https://user-images.githubusercontent.com/30548000/258598481-cf83148c-9439-4d85-9cf5-3b70f6917a52.png)

我只有买的时候从邮箱收到了地址 后面版本 的下载地址在哪里找呢

**Comment by xulihang** [comment]
百度网盘里会更新文件
