### ISSUE TITLE
manga-image-translator 的OCR失效了，去字没问题

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#475]
在OCR完成以后会变成乱码返回到软件里？是我哪里有问题吗。。尝试重装了manga-image-translator 也不行
![QQ截图20220604000622](https://github.com/xulihang/ImageTrans-docs/assets/49093867/9ebb6ef9-27d6-4fd7-869e-a57d683a77d0)
![QQ截图20230803213248](https://github.com/xulihang/ImageTrans-docs/assets/49093867/d553baa4-ebb9-437c-ae15-26ff81530bf7)

**Comment by xulihang** [comment]
哪个版本的ImageTrans，是2.2.0吗

**Comment by haofan170** [comment]
> 

草解决了..是我选择错了OCR模式（）
