### ISSUE TITLE
lama问题

### ISSUE THREAD

**Issue by sera1991** [xulihang/ImageTrans-docs#477]
因为lama更新到1.2.3了,想着用新版的lama来处理图像试试。结果运行cm以及lama提供的Windows包没有反应，然后我把端口改成8087显示下面的错误（用其它端口没反应）
![1](https://github.com/xulihang/ImageTrans-docs/assets/30473573/820031b4-8db9-4d45-85f8-b5bab2ed8f75)

但用这儿给的Windows包就能正常运行
https://github.com/xulihang/ImageTrans_plugins/tree/master/LamaInpaint
![QQ图片20230805055551](https://github.com/xulihang/ImageTrans-docs/assets/30473573/716724d7-6fa4-4794-a3cf-d1d0e50f6417)

所以想问下用cmd启动的lama怎么正常在ImageTrans里运行。。

**Comment by xulihang** [comment]
LamaInpaint的说明在这里：https://github.com/xulihang/ImageTrans_plugins/tree/master/LamaInpaint

新版的http请求参数不一样了，目前的插件不适用。

**Comment by xulihang** [comment]
LamaInpaint的说明在这里：https://github.com/xulihang/ImageTrans_plugins/tree/master/LamaInpaint

新版的http请求参数不一样了，目前的插件不适用。

**Comment by sera1991** [comment]
感谢解答，也希望后续可以接入新版lama。

**Comment by xulihang** [comment]
插件更新了下，支持新版了
