### ISSUE TITLE
可以给【对齐】功能增加快捷键吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#479]
因为对文化的不自信
所以我有个强迫症 就是做润色的时候必须开很多个翻译对比查看
哪怕现在可以使用AI  我也会开多个传统翻译引擎和多个不同温度的AI来进行对比
然后找出一句 或者自己总结出来一句 比较像人话的话然后回填到漫画里
如果是气泡漫画还好说
但是遇到这种全部都是文字的漫画 没有气泡
对齐就是很重要的功能了 当然我们的工具是有这个功能的 可是
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/88d134a6-9ded-458b-9541-c6606d00c92f)
像图1这种情况下 悬浮的翻译框可以放在下方 这样操作对齐没有任何的问题
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b2f851f3-bfb3-4048-813b-f9ef57254785)

也可以正常使用鼠标宏来实现一键对齐........
但是.......等遇到图2的这个情况 文字分布复杂
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4f7f1ab8-2970-47de-a45c-3ac1f05a5a29)
文字位置存在多处 

这种时候 点击的部分被别窗口覆盖住了 想要点击上对齐的话就只能最小化翻译的窗口才能够点到对齐的按钮

所以....就是......能不能....再麻烦....开发者.....老哥一下.....

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1d825d64-8ecc-4f58-bcbf-eb133a38a075)
在快捷键的设置里增加一下 对齐的快捷键选项........ 其实常用的 用的最多的就是上对齐  这就不需要鼠标来回点了
 一键对齐 想想 就很方便 ~~~~
 
 或者
 全部展开弄到外面来
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/6991614e-708d-47d5-93f3-52d03f50e4f5)

像PS这样 也很方便
![tianruo_20230806030838](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b701751e-4e40-4224-ac2f-8c3d6e4713d5)

**Comment by xulihang** [comment]
我加个菜单，快捷键你自己定义吧

**Comment by lhj5426** [comment]
> 我加个菜单，快捷键你自己定义吧

嗯  感谢
能有快捷键设置就 够了

**Comment by xulihang** [comment]
加在2.2.2里了

**Comment by lhj5426** [comment]
> 加在2.2.2里了

收到这就去更新看看 辛苦了 老哥

**Comment by lhj5426** [comment]
> 加在2.2.2里了

好像登录验证有问题？ 无法登录呢？
Tjava.net.ConnectException:Failed to connect towww.xulihang.me/fd00:696e:974:6578:0:0:61:66b:5127

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/159b9797-513c-4478-ac41-73568aba773b)
全部都试过了 这下方便了感谢 这本还有70多页 明天弄的时候能省事点了
