### ISSUE TITLE
开一个跟快捷键有关的topic，所有跟快捷键有关的issue可以在这里跟踪

### ISSUE THREAD

**Issue by linkstree** [xulihang/ImageTrans-docs#48]
![image](https://user-images.githubusercontent.com/18115991/117011367-72082200-acf6-11eb-8f28-7fe2e0d80711.png)
![image](https://user-images.githubusercontent.com/18115991/117011649-b4c9fa00-acf6-11eb-9f9b-1bbdb347a410.png)

我平常一次性1000多张图片，没有快捷键确实很不方便，麻烦关注一下

**Comment by xulihang** [comment]
好的，我一直想做个快捷键设置，一个问题是这些右键菜单的快捷键我不知道怎么添加，需要研究一下

**Comment by xulihang** [comment]
提到的快捷键在v1.7.1里都添加了
