### ISSUE TITLE
替代 GPT

### ISSUE THREAD

**Issue by k9menor2022** [xulihang/ImageTrans-docs#481]
使用[lm Studio](https://lmstudio.ai/)的API，我们可以在本地运行一个免费的智能体来进行翻译。

![image](https://github.com/xulihang/ImageTrans-docs/assets/116160919/ff6e8751-d116-4118-b437-416ec0c216af)
![image](https://github.com/xulihang/ImageTrans-docs/assets/116160919/98ba9d3e-fbf0-4498-8c04-39638230d492)

请创建一个插件。

**Comment by xulihang** [comment]
它的接口和ChatGPT是一样的，直接用ChatGPT的插件，修改下endpoint就行

**Comment by lhj5426** [comment]
> 使用[lm Studio](https://lmstudio.ai/)的API，我们可以在本地运行一个免费的智能体来进行翻译。
> 
> ![image](https://user-images.githubusercontent.com/116160919/259481144-ff6e8751-d116-4118-b437-416ec0c216af.png) ![image](https://user-images.githubusercontent.com/116160919/259481709-98ba9d3e-fbf0-4498-8c04-39638230d492.png)
> 
> 请创建一个插件。

这东西 吃显存吗 ？
