### ISSUE TITLE
Embedded Web Browser

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#483]
BasicCAT can use WebView to utilize online dictionaries and machine translations:

* https://docs.basiccat.org/en/latest/advancedFeatures.html#section-5
* https://www.basiccat.org/new-plugin-machine-translation-via-web/

They can also be embedded in ImageTrans.

I've added a web tab in the operations pane.

Here are some examples:

Use google translate:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/0f4488c0-0c52-4eb6-bce7-ad52b252e10b)

Use an online Japanese analyser based on kuromoji:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/1d82f01a-6e3c-4eff-beed-11e40086e510)

**Comment by xulihang** [comment]
The preset dictionaries or machine translation urls can be set the Preferences.

The following in the URL will be replaced with the desired content.

* {source} will be replaced with the source text.
* {sourceLang} will be replaced with the project's source lang code.
* {targetLang} will be replaced with the project's target lang code.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/4dff39dd-9d1a-4d83-a74f-7ec78953575c)

**Comment by xulihang** [comment]
Added in v2.3.0

**Comment by lhj5426** [comment]
哈哈 在高级点 是不是可以直接内嵌个GPT网页
https://chatkit.app/
https://web.chatboxapp.xyz/

**Comment by lhj5426** [comment]
中文显示是乱码
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/95c8fdb9-5765-476b-80ac-2da92577ba43)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/44a3d48d-b79c-4697-be70-57fd11865acf)

**Comment by lhj5426** [comment]
内置的 百度 之类的也是
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5c71492d-eecb-4ad6-93c4-9347d45bcb55)

**Comment by xulihang** [comment]
不清楚原因，我测的几台没这个问题

**Comment by lhj5426** [comment]
> 不清楚原因，我测的几台没这个问题

这个问题和 BasicCAT 感觉很类似 BasicCAT 查看 属于的界面也是乱码 一直都是 今天 更新的IT新更新的部分也是乱码 头疼

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a688dad3-56e5-4929-a359-6920dd528faf)
第一次 是改系统
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2d279fef-64c0-4fd6-950c-7077b71cfb57)
结果重启完 还是乱码 
然后 换了个纯净版的新系统
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/de1b118e-b09f-4ea1-9888-3885bbe93183)
正常了  还是系统的锅  呜呜 还得找原因 哈哈

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/285f8c22-ceb9-4b10-8c19-334f6c549b4c)
系统都是一样的 就是用时间长了不知道 出了什么幺蛾子导致了乱码
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/cb6eca4c-df3a-4dfa-9a34-f7d522d5cd11)
也不能为了这个重装遍系统 哈哈 只能一点点排查 了 哎
