### ISSUE TITLE
I have a proplem withe validator in ImageTrans?

### ISSUE THREAD

**Issue by keba12** [xulihang/ImageTrans-docs#484]
Hello there is a problem that occurs to me when I log in to the application ImageTrans. It tells me that I did not purchase it, knowing that I bought it from the Fastspring store, and my mail is [okbbacom4@gmail.com](mailto:okbbacom4@gmail.com). Please solve the problem quickly.
This is proof that I purchased the software
![Uploading Screenshot_٢٠٢٣٠٩٠٤-١٢٥٧٢٦_Gmail.jpg…]()

Thank you

**Comment by keba12** [comment]
![Uploading Screenshot_٢٠٢٣٠٩٠٤-١٢٥٧٢٦_Gmail.jpg…]()

**Comment by xulihang** [comment]
Which version are you using?

Free updates are within 6 months. If you need to use the latest version, you have to purchase it again.

**Comment by keba12** [comment]
But I purchased the version for $10.99. Do I not have the right to download
the latest version?

في الاثنين، ٤ سبتمبر ٢٠٢٣ ١:٠١ م Lihang Xu ***@***.***> كتب:

**Comment by keba12** [comment]
This is not fair. Aren't the updates free for anyone who bought the $10.99
version?

في الاثنين، ٤ سبتمبر ٢٠٢٣ ١:٢٤ م Tick Gaming ***@***.***> كتب:

**Comment by xulihang** [comment]
You can find the release notes containing the date of versions here: https://www.basiccat.org/imagetrans/release-notes/
