### ISSUE TITLE
The problem is that I could not log into the program

### ISSUE THREAD

**Issue by keba12** [xulihang/ImageTrans-docs#486]
Hello my friend, I downloaded version 2.2.0, which I was working on before the updates were issued, and it was working without problems. I enter it and it does not show me a sign that I have not recovered it now, and after I re-downloaded it, whenever I enter it and ask if I can log in, it tells me that I did not purchase the program, even though I had purchased it.  The program has been around for a while, so what should I do?  Please help quickly
 Thank you

**Comment by xulihang** [comment]
What is your order ID? Please send it to my email: admin@basiccat.org instead of posting issues here.

**Comment by keba12** [comment]
BASICCAT220825-3322-45119

في الجمعة، ٨ سبتمبر ٢٠٢٣ ٤:٣٣ م Lihang Xu ***@***.***> كتب:

**Comment by xulihang** [comment]
The latest version (6 months within your purchase) you can use should be v1.9.1.
