### ISSUE TITLE
图片管理里能不能增加一个筛选临时隐藏的功能

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#488]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/6428de19-30ce-4ea3-8958-170fa8fd9572)
开发者老哥 这个图片管理里 能不能增加一个 反选 还有一个临时隐藏的功能
就是勾选上之后可以在操作界面上隐藏这些图片 
举个例子 

https://github.com/xulihang/ImageTrans-docs/assets/30548000/096d4e33-2738-41e0-b91b-487156848481

就像这样 开启之后 可以把选中的图片隐藏 这样修正的时候 就可以 专注修正这些没被隐藏的

**Comment by xulihang** [comment]
反选是用来做什么的？

隐藏的话我可以加一个选项：选中图片不再显示在主界面列表里

**Comment by xulihang** [comment]
已翻译图片选中的不就是翻译好了要隐藏的吗，反选的话就选中了没翻译好的，这些本来也不用隐藏

**Comment by lhj5426** [comment]
> 已翻译图片选中的不就是翻译好了要隐藏的吗，反选的话就选中了没翻译好的，这些本来也不用隐藏

哈哈 脑瓜子没转过个来 老哥你说的对 
就是只需要一个可以 在 编辑界面隐藏选中的图片功能

**Comment by xulihang** [comment]
添加在v2.5.1了

**Comment by xulihang** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/4242f8f6-e2b3-49fd-9f74-2fa2605a2cb3)

勾选右下角的设置后点保存，主界面已翻译的图片会从列表中去除

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4144ebf3-5b50-4d50-a25f-3ee6776b4a1a)
 隐藏之后 导出也只导出 显示的图片 太棒了 非常感谢
 这样就不需要 几百张图 上次翻译了 并导出了50张 然后 下次 又接着翻译了50张
 还要从第一张重新 导出了 
 现在可以直接隐藏之前的那些了然后导出 也节省时间了 太棒了！！！
