### ISSUE TITLE
translating issue

### ISSUE THREAD

**Issue by animanl00ver** [xulihang/ImageTrans-docs#49]
when im translating sometimes its erases the bubbles or if theres it skips some of the bubbles and dont translate it and alsothe programs have trouble translating when the website has a lot of water marks it tries to translating part of the drawing

**Comment by xulihang** [comment]
The heuristic text detection is not 100% accurate. See the [docs](https://imagetrans.readthedocs.io/en/latest/textarea_detection_and_text_reinjection.html#id3) for details.

Basically, it first get all possible text areas and then filter areas with low confidence. It may include non-text areas.

In addition, it needs the characters separate from other drawings as it uses a connected-componet labeling method to group words into paragraphs.

I'd recommend you to apply for Google Vision to use its OCR services if you need a higher accuracy.

**Comment by herrachamp** [comment]
I applied for the google vision api.
I pasted the api key.
But after clicking on ocr nothing happens.
Is there more settings to be done?

**Comment by xulihang** [comment]
Check if you've pasted it correctly. Remove trailing whitespaces if there are.

![image](https://user-images.githubusercontent.com/5462205/123354523-6cacb280-d596-11eb-82bd-45cd6e5a9079.png)

**Comment by herrachamp** [comment]
There are no white spaces
Check the screenshots
![Vision API](https://user-images.githubusercontent.com/85825674/123386176-ff0f7f00-d5b3-11eb-8aa1-eb77be91b761.png)
![Google](https://user-images.githubusercontent.com/85825674/123386182-0040ac00-d5b4-11eb-8342-b13cd85bfbf1.png)

**Comment by xulihang** [comment]
I think you've applied a wrong key. It should be an API key, not keys of a service account.

The following is a screenshot of my account page:

![image](https://user-images.githubusercontent.com/5462205/123391168-4f93d600-d5ce-11eb-9a5f-e6ea4ec9d9b3.png)

**Comment by xulihang** [comment]
The page's URL: https://console.cloud.google.com/apis/credentials

**Comment by herrachamp** [comment]
Oh! I was pasting the wrong key.
Please tell me how to create the key.
![credentials](https://user-images.githubusercontent.com/85825674/123393988-439f1880-d5bc-11eb-9926-8345e59c8d1e.png)

**Comment by herrachamp** [comment]
I clicked on Create Credentials and then on Create API key.
Then this key generated. Is this the right one?
![api key 1](https://user-images.githubusercontent.com/85825674/123394412-c031f700-d5bc-11eb-9536-0f92477bf0c7.png)

**Comment by xulihang** [comment]
This one is right.

**Comment by herrachamp** [comment]
I pasted this new one still nothing happens when I click on ocr.
![api setting](https://user-images.githubusercontent.com/85825674/123395719-279c7680-d5be-11eb-81bf-e27a4acf3655.png)

**Comment by xulihang** [comment]
Run ImageTrans from PowerShell to see the output to check what is wrong.

Google is good for document-level ocr, but not good for bubble-level ocr.

https://user-images.githubusercontent.com/5462205/123396509-f5960f00-d5d3-11eb-8c7b-58bd9ffb9b90.mp4

The command line:

```
./jre/bin/java -jar ImageTrans.jar
```

**Comment by xulihang** [comment]
If the API is not valid, then you can see an output like this:

```
ResponseError. Reason: , Response: {
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "vision.googleapis.com"
        }
      }
    ]
  }
}
```

**Comment by herrachamp** [comment]
PS C:\Users\soura> E:\ImageTrans\ImageTrans\jre\bin\java -jar ImageTrans.jar
Error: Unable to access jarfile ImageTrans.jar


There is no java folder in my imagetrans setup

**Comment by xulihang** [comment]
You should run this under the ImageTrans folder:  E:\ImageTrans\ImageTrans\

**Comment by xulihang** [comment]
Input: `cd E:\ImageTrans\ImageTrans\`

**Comment by herrachamp** [comment]
run(MyMap) {lang=en, img=javafx.scene.image.Image@2ab6b61f}
ResponseError. Reason: Forbidden, Response: {
  "error": {
    "code": 403,
    "message": "This API method requires billing to be enabled. Please enable billing on project #563413037439 by visiting https://console.developers.google.com/billing/enable?project=563413037439 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console billing",
            "url": "https://console.developers.google.com/billing/enable?project=563413037439"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "BILLING_DISABLED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "vision.googleapis.com",
          "consumer": "projects/563413037439"
        }
      }
    ]
  }
}

(ArrayList) []


This is the error in PowerShell.
And the reason I was struggling with google is because the other ocr's are not able to recognise the text. (check the below images
So I thought google may help.

![winrt](https://user-images.githubusercontent.com/85825674/123402226-23c02280-d5c5-11eb-90c7-0c3202e923d8.png)
![ocrspace](https://user-images.githubusercontent.com/85825674/123402230-24f14f80-d5c5-11eb-947a-dee402934678.png)
![tesseract](https://user-images.githubusercontent.com/85825674/123402235-2589e600-d5c5-11eb-9746-87efa0cbbb6b.png)

**Comment by xulihang** [comment]
You can use baidu:

![image](https://user-images.githubusercontent.com/5462205/123403081-faaa8c80-d5da-11eb-9199-0f3b1fb97251.png)

**Comment by xulihang** [comment]
Tesseract also works:

![image](https://user-images.githubusercontent.com/5462205/123403293-35142980-d5db-11eb-932a-185a3db17899.png)

You should OCR a single bubble instead of the entire image.

**Comment by herrachamp** [comment]
All other ocr's don't work
and baidu is giving this error:


error: java.lang.RuntimeException: Object should first be initialized (List).
StackTrace: java.lang.RuntimeException: Object should first be initialized (List).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.List.getSize(List.java:117)
	at org.xulihang.imagetrans.ocr$ResumableSub_GetTextWithLocation.resume(ocr.java:2407)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)


Tesseract works well only in few places rest all is like this:
![tesseract 1](https://user-images.githubusercontent.com/85825674/123405024-0ee48e80-d5c7-11eb-98b3-a03f6b777b25.png)

**Comment by xulihang** [comment]
Setting the display percentage to 100% will improve the result. And install the latest version of Tesseract: <https://github.com/UB-Mannheim/tesseract/wiki>

Can you visit www.baidu.com? If not, Baidu may be blocked in your country.

**Comment by herrachamp** [comment]
baidu.com is not opening

**Comment by herrachamp** [comment]
and I have installed the latest version only
tesseract-ocr-w64-setup-v5.0.0-alpha.20210506.exe (64 bit) resp.

**Comment by xulihang** [comment]
Baidu and other Chinese OCR engines work great. But sadly, you cannot use them. You can try enabling the billing of Google.

As for offline OCRs, I haven't found a very good English OCR engine for your images.

**Comment by herrachamp** [comment]
Can you add the option of exporting the chat bubbles only without any ocr.
All stacked in line. 
I will use it to work around with google ocr.

**Comment by xulihang** [comment]
Go to Export->Document for translation, save as docx. It will crop bubbles without text and save them to the docx file.

**Comment by herrachamp** [comment]
I selected Use image clips for areas without source text? Yes
for export the document for translation in docx file.
I got this error:

error: java.lang.IllegalArgumentException: Invalid crop bounds: x [1], y [1144], width [140] and height [-64] must all be >= 0
StackTrace: java.lang.IllegalArgumentException: Invalid crop bounds: x [1], y [1144], width [140] and height [-64] must all be >= 0
	at org.imgscalr.Scalr.crop(Scalr.java:850)
	at anywheresoftware.b4a.objects.B4XViewWrapper$B4XBitmapWrapper.Crop(B4XViewWrapper.java:868)
	at org.xulihang.imagetrans.main._croppedbox(main.java:3717)
	at org.xulihang.imagetrans.exporter._export(exporter.java:497)
	at org.xulihang.imagetrans.main$ResumableSub_MenuBar1_Action.resume(main.java:10260)
	at org.xulihang.imagetrans.main._menubar1_action(main.java:9559)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
	at anywheresoftware.b4a.BA$1.run(BA.java:216)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by herrachamp** [comment]
> Can you add the option of exporting the chat bubbles only without any ocr.
> All stacked in line.
> I will use it to work around with google ocr.

export chat bubbles only like this:
![bubbles](https://user-images.githubusercontent.com/85825674/123410778-4fdfa180-d5cd-11eb-86f1-cc83c187e8b1.png)

**Comment by xulihang** [comment]
How did you generate text areas? Make sure everyone is within the image.

**Comment by herrachamp** [comment]
This option is exporting the text in docx file.
I want to export only the bubbles of chat in one image file. 
Check the above image I have attached.


> Go to Export->Document for translation, save as docx. It will crop bubbles without text and save them to the docx file.

**Comment by xulihang** [comment]
Save the docx file to an html file and then you can get all the bubble images.

**Comment by herrachamp** [comment]
I got it now.
I first used 'Detect balloons' and then exported it to docx file and got the bubble images as I wanted.
Using 'Detect text areas and recognize text' was giving the text and not the image.
Thank once again very much for your support.
