### ISSUE TITLE
「」() 标点的间隔能 进行一下优化吗 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#490]
尊敬的老哥 如图
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1ec1f286-7d27-4b66-a06c-a56a8a11501a)
这是软件默认的 对齐
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b5b9aeea-b9b0-4a3e-95b8-9760e6b6703d)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d594b03c-7086-4e02-88ac-b8572d59615a)

这是通过屏幕辅助线手动优化过的对齐
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2cafdd91-5f49-41ad-9855-9e73314efe13)
标点符号 相对于纯文字
这里会高出来一块 
可以通过优化给它切齐吗

现在 
需要开个 屏幕辅助线 和 放大镜 按像素来对齐
有点难受 之前 制作的那部没有 这种括号标点 直接快捷键一键对齐调整就行了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c7d0f31b-9bd3-49eb-85a7-1a93b7e21f1b)
现在这种 有括号 又方括号的 还有没有括号标点的 
虽然可以有快捷键可以一键对齐 可页面上出现各种的话 还要进行像素对齐
所以 能不能麻烦开发者老哥 想想办法 把这个这种 竖向的方括号 和 括号给它们 和文字切齐了

**Comment by lhj5426** [comment]
特别是这种一行放不下 分开的时候 就更 不好看了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1cf81c61-3a09-4e12-a6ef-ab2dcb7789f4)

**Comment by xulihang** [comment]
ImageTrans的竖排引擎里每个标点和文字占的高度是一样的。
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/05ba6864-ec0e-42b5-a08e-634669ca7aa6)

我看了下浏览器和Photoshop也是这样的设计：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/11192ec2-8cb7-4abc-9b27-5d406e6af822)
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/d0f2a541-0e1e-42bf-b1ac-7a664dcea44d)


需要加一个选项让字符高度可以根据文字本身的高度来，但我估计效果不会很好

**Comment by lhj5426** [comment]
> ImageTrans的竖排引擎里每个标点和文字占的高度是一样的。 ![image](https://user-images.githubusercontent.com/5462205/269908008-05ba6864-ec0e-42b5-a08e-634669ca7aa6.png)
> 
> 我看了下浏览器和Photoshop也是这样的设计：
> 
> ![image](https://user-images.githubusercontent.com/5462205/269907905-11192ec2-8cb7-4abc-9b27-5d406e6af822.png) ![image](https://user-images.githubusercontent.com/5462205/269907998-d0f2a541-0e1e-42bf-b1ac-7a664dcea44d.png)
> 
> 需要加一个选项让字符高度可以根据文字本身的高度来，但我估计效果不会很好

是这样啊   好像是个很麻烦的事情呢

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/be38b03e-51d6-4720-be80-c02836df13de)
我以为是只要削切掉 这里 文字和 绿框中间 多出来的空余部分就行了 呢

看了  从用户角度来说还是想的太简单了

**Comment by xulihang** [comment]
日文原图是怎么排版的？我看看怎么让它和原来的排版接近

**Comment by lhj5426** [comment]
![0035](https://github.com/xulihang/ImageTrans-docs/assets/30548000/e9513100-70e0-4596-bd64-d1eb4b6e0a68)
![0038](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2f43a6b1-1def-4cb0-a384-5df80783595f)
![0014](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b7de1a27-2f6b-432c-a181-5bf11e3b062d)
日文原本的

**Comment by lhj5426** [comment]
![0015](https://github.com/xulihang/ImageTrans-docs/assets/30548000/eb83d215-4f81-48d7-98bd-35d55c7facee)
![0034](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7abf4794-45c2-414f-8b6c-3e4047b29880)
![0044](https://github.com/xulihang/ImageTrans-docs/assets/30548000/54e5f3d3-17c8-4fed-ac5d-1d548b1c306c)
方括号的

**Comment by lhj5426** [comment]
然后我发现 在PS里这种 括号分开的字 一个括号就对齐了
然后在IT里 这个一个括号= PS 里两个括号的距离

https://github.com/xulihang/ImageTrans-docs/assets/30548000/299af186-99e1-4326-8421-fbcc168615b2

**Comment by xulihang** [comment]
把上面空的部分截掉相对容易一点。我考虑加个需上移的行首字符的设置。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/7a8ee7fd-3ced-426e-bac2-2a70348f5b7b)

**Comment by lhj5426** [comment]
> 把上面空的部分截掉相对容易一点。我考虑加个需上移的行首字符的设置。
> 
> ![image](https://user-images.githubusercontent.com/5462205/269986034-4b87dda0-a3d1-40d1-b062-c7e5d857cb6a.png)

看着老哥 截图的效果不错耶 开始期待下次的更新下

**Comment by xulihang** [comment]
添加在v2.5.1了

**Comment by xulihang** [comment]
加了需上提首字符的的设置，需要设置后使用，比如输入`[︵﹃]`。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/f8af8c76-bd34-41a2-a392-72bda3febe83)

**Comment by lhj5426** [comment]
> 加了需上提首字符的的设置，需要设置后使用，比如输入`[︵﹃]`。
> 
> ![image](https://user-images.githubusercontent.com/5462205/270152575-f8af8c76-bd34-41a2-a392-72bda3febe83.png)

非常 感谢这就去更新体验

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7ffc2d11-dbe7-42da-9090-276640187ba1)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/302d053a-7cee-4f2b-9edb-15fa7caadaeb)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/73f0fd82-0052-4a35-afb2-ec6739ec5cc1)

简直太棒了！！！  处理的非常 不错  非常感谢老哥！！！
