### ISSUE TITLE
反复开关掩膜编辑窗口 掩膜编辑窗口会黑屏

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#494]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/f2718ea4-4b9c-4c33-a0ae-2e9ad63e1ffa

如视频所示这样  反复开关 掩膜窗口  多开几次 修 个几张图 就会随机 变成视频最后的打开掩膜窗口就全黑了
然后这个时候整个软件 自身都是一卡一卡的 反映很慢
这个情况 唯一的解决方法 就是关闭 整个IT 软件 然后重开 才行

然后 重开软件 这个问题是  修 几张 到十几张图 又会随机出现这个问题 好的时候20 多张 才出现
在掩膜窗口100%的时候 出现的概率是10多张 出现一次 
如果 把掩膜窗口的百分百调整大于100% 几次 就有可能出现

这个问题还请老哥优化下 
从上一个 issues
我想了下我为什么不敢用 倍率放大去修掩膜而是用放大镜 
突然想起来 这个掩膜 开关多次就会出这个问题 这个问题存在好多个版本了

还有一个
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7b92da3a-8fe9-4315-9019-83d7af3e51e0)

掩膜 100%没有调整的时候 掩膜的颜色是这样的

https://github.com/xulihang/ImageTrans-docs/assets/30548000/7c969482-cd5f-4dff-b19f-38b2b4263c06

然后放大之后 颜色就变得很淡薄了
但是呢 如果关闭了  半透明  掩膜的颜色又变得和100%大小的时候一样浓了 但是 涂抹的时候 不透明了
所以 可以不可以 请开发者老哥优化一下 放大倍数的时候掩膜的颜色 也保持一直的浓度

**Comment by xulihang** [comment]
这个问题我复现不了。

放大时的掩膜变更加透明的问题我会修一下。其实还有个偏移问题，一直没解决。

**Comment by xulihang** [comment]
透明度这个问题比较明显，我修了下把2.5.1的文件更新了

**Comment by lhj5426** [comment]
> 透明度这个问题比较明显，我修了下把2.5.1的文件更新了

还有这种 掩膜放大 黑屏

https://github.com/xulihang/ImageTrans-docs/assets/30548000/7c127622-07c1-4205-bc1c-b5aafe3ba620

这要复现不了 要怎么能够 提交 具体出了什么问题呢 
我去开 命令行模式 运行 出了问题查看命令行 那个黑窗口呢？

**Comment by xulihang** [comment]
这个应该是图片的分辨率或者是放大后分辨率比较大的原因，宽或者高大概超过8000时会有这个问题。

我看看怎么更新一下，把这个限制给解决

**Comment by lhj5426** [comment]
那就不太清楚了我目前反馈这个问题的时候在制作字幕的漫画图片的分辨率是这种的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/3b6f74c6-14af-4f60-8c9f-90edf7a61ae7)
不放大 的情况下 来回 打开 掩码 十几次 20几次 也会报错 辛苦老哥了

**Comment by xulihang** [comment]
可以试一下v2.5.2，应该修复了这个问题

**Comment by lhj5426** [comment]
> 可以试一下v2.5.2，应该修复了这个问题

嗯 连续打开 放到400% 然后关闭 了84次 才报错 相当稳定了 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4c2b9aff-246e-453a-ae84-7db0c9f550eb)
