### ISSUE TITLE
manga_ocr 怎么才能使用 CUDA GPU

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#495]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/97975d69-f5f7-4c2b-82e2-5c635d385b5e)
 首先 老哥 中秋节 好 
 其次是问题
 
 
 如图您看到的 蓝色的框是我自己 按照  manga_ocr 部署到电脑上的 可以使用 cuda 来识别的 速度是真比CPU快啊
 然后 我在运行 您打包的 manga_ocr 对比 发现 我自己部署的没有 HTTP 这种东西
 
 所以想问下 我要怎么修改 自己部署的才能像 您 放在网盘里的那样 可以有 
 
 Listening on http://0.0.0.0:19812/
Hit Ctrl-C to quit.

serving on 0.0.0.0:19812 view at http:127.0.0.1:19812

或者说我要怎么修改您 打包的 manga_ocr  才能调用我自己部署的 GPU版本 

这样 我就用it 来运行 我自己安装的 可以用 cuda GPU 版本的 manga_ocr 了
GPU 运行是真快 我这刚截完图  窗口上就显示结果了 cpu 还得寻思个 2 5 秒钟。。。

**Comment by xulihang** [comment]
1. 安装相关依赖：

   ```
   pip install bottle Paste
   ```

2. 执行服务器的脚本：

   ```
   python server_manga_ocr.py
   ```

**Comment by xulihang** [comment]
用我提供的打包的话，需要把pytorch更新为gpu版。还是用你自己的环境运行上面的命令方便

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/25afb5ed-b7cd-430a-8d5b-e13946e78be9)
十分感谢老哥 妥妥的可以用cuda  这速度简直了 起飞
