### ISSUE TITLE
OCR的执行效率可否提高一下？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#496]
老哥 国庆节 快乐
是这样的
前几天不跟您请教如何使用cuda么
今天我好奇在我的电脑上究竟能提升多少
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a751893a-e800-491c-a2b2-968cd2584e41)
用了一部70页的漫画
O:\BTQB\shengrouben\(同人誌) [もふまんじゅう (ぴろまゆ)] 僕の彼女は義理の父に何度も犯されていた (オリジナル)
进行了测试 
然后
用了另外一款开源软件
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/9dd05bdb-788f-4cf4-95c1-4cddf81a4ce7)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/faf55767-3393-460b-baaa-c2ee7c71f617)
使用了相同的
相同的环境下 使用了 mangaocr 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/6bd778ce-7b1f-430e-aea1-ef8f5f959451)
 所以问题来了 咱们可以提升一下 OCR的执行效率么 从单线程 改成多现成并发？
 或者 能不能恳求 您能不能像 
 https://github.com/xulihang/ImageTrans-docs/issues/439
 一样 做一个转换 这样 可以 IT来 识别气泡 然后转换 成BL 的格式去OCR 然后再转换成IT格式的去翻译和机翻润色嵌字什么的
 这样即兼顾了识别速度 也兼顾嵌字体验
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/f3b588bf-0085-4eae-8f70-789dbc1fc9ae)

我自己知道 这个要求好像很没有道理 但是想提升一下使用体验 所以还是提出来了
取长补短 应该不算毛病吧 哈哈哈哈。。。

虽然有GPT 这个AI 但是
首先得人得懂 怎么弄 GPT才能辅助出代码
我自己什么都不懂 所以问gpt也问不出来什么

**Comment by xulihang** [comment]
这个之前有用户提过的，不只是OCR，还要求OCR的同时进行机器翻译，我当时没有这方面的打算。默认的在线服务都有每秒请求次数的限制，数量多了请求会失败。离线OCR的话，我只给tesseract做过多进程的优化。

OCR所有区域这个操作是和UI绑定的，会慢一点，你可以试一下静默翻译助手，这个是不和UI绑定的，但也是一个一个区域去识别。

**Comment by lhj5426** [comment]
> 这个之前有用户提过的，不只是OCR，还要求OCR的同时进行_机器翻译_，我当时没有这方面的打算。默认的在线服务都有每秒请求次数的限制，数量多了请求会失败。离线OCR的话，我只给tesseract做过多进程的优化。
> 
> OCR所有区域这个操作是和UI绑定的，会慢一点，你可以试一下静默翻译助手，这个是不和UI绑定的，但也是一个一个区域去识别。

嗯 先我去试试

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c75f531b-2aa0-4732-a3d0-f325e42bc39a)
没研究明白怎么用。。。

**Comment by xulihang** [comment]
静默翻译器是执行检测、OCR、机器翻译和生成翻译的图片所有操作的。启动助手后调整下参数点翻译当前图片或者所有图片就行了。单纯OCR我试了下其实和正常操作差别不大。

**Comment by lhj5426** [comment]
> 静默翻译器是执行检测、OCR、_机器翻译_和生成翻译的图片所有操作的。启动助手后调整下参数点翻译当前图片或者所有图片就行了。单纯OCR我试了下其实和正常操作的耗时差别不大。

您都测试过 我就不试了

在未来期待老哥 以后能够 至少把 mangaocr 和win系统OCR 这2个离线的 OCR 进行一些速度上的优化
毕竟离线 没有 网络上的那个请求限制 完全看硬件 最好是有个 并发设置 可以自己根据电脑配置来调整
到一个合适的并发数 达到效率最大化的目的

**Comment by lhj5426** [comment]
不过 这个 mit48px_ctc 是真的快 我操 我都傻眼了  要能引进也不错哈哈 
嘛 作为一个用户仅隔着异想天开  哈哈

**Comment by xulihang** [comment]
mit48px_ctc是manga-image-translator用的OCR模型，之前https://github.com/xulihang/ImageTrans-docs/issues/411讨论的，集成起来比较麻烦。最好它能提供一个API接口，我传张图给它，给我返回文字坐标、文字、颜色等数据。

我看目前已经有一个了，但还不是很完善：https://github.com/zyddnys/manga-image-translator/blob/74670c985ad2224ec406dab8e9aa3a817672ed41/manga_translator/manga_translator.py#L975

只有等它比较完善了我再集成进去

**Comment by lhj5426** [comment]
> mit48px_ctc是manga-image-translator用的OCR模型，之前 #411 讨论的，集成起来比较麻烦。最好它能提供一个API接口，我传张图给它，给我返回文字坐标、文字、颜色等数据。
> 
> 我看目前已经有一个了，但还不是很完善：https://github.com/zyddnys/manga-image-translator/blob/74670c985ad2224ec406dab8e9aa3a817672ed41/manga_translator/manga_translator.py#L975
> 
> 只有等它比较完善了我再集成进去
嗯  哈哈 只能等 他完善了 现在的解决方法最好的还是转换JSON
实我找到了需要转换的地方的  具体位置 就是 GPT 在给我疯狂写bug 我同时用了 GPT3 4 还有克劳德2
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/599fb6cf-2bc6-45cc-b088-d213960d793f)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4e6c8593-ebe8-40d7-b172-fbcf5ad5fe61)

**Comment by lhj5426** [comment]
死磕AI 
搞出来个脚本
import json

with open('111.json', encoding='utf-8') as f1:
    data1 = json.load(f1)

with open('222.json', encoding='utf-8') as f2:
    data2 = json.load(f2)

data2['dirPath'] = data1['directory'] 

for page, boxes in data1['pages'].items():

    data2['images'][page] = {'boxes': []}

    for box in boxes:
      
        x, y, w, h = box['_bounding_rect']
            
        data2['images'][page]['boxes'].append({
            'geometry': {
                'X': x,
                'Y': y, 
                'width': w,
                'height': h
            },
            'text': box['text'],
            'target': box['translation'] 
        })
        
with open('new.json', 'w', encoding='utf-8') as f3:
    json.dump(data2, f3, indent=4)
    
    在老哥您还没更新之前的折中解决方案
    
    

https://github.com/xulihang/ImageTrans-docs/assets/30548000/088e8fea-c1a7-4c7e-b740-fe72d07c983a

首先这么做并不是对您表示不尊敬 和尊重 相反是非的尊敬以及尊重
但是只是作为一个用户  只是 追求效率最大化而已
当然还是满心期盼 未来 IT自身的发展和更新
这只是一个折中的方案 

无奈我技术0 AI还太白痴 只做了 从B转换到I的脚本
至少可以加速OCR 也算达到了一个小的目标

**Comment by xulihang** [comment]
```diff
- with open('222.json', encoding='utf-8') as f2:
+ with open('222.itp', encoding='utf-8') as f2:
```
上面这行读取ImageTrans的项目文件，其实不改扩展名也是可以读的。

**Comment by lhj5426** [comment]
嗯 十分感谢 原来还可以这样  GPT让我咋写 我咋写的

**Comment by lhj5426** [comment]
import json

with open('111.json', encoding='utf-8') as f1, open('222.json', encoding='utf-8') as f2:
    data1 = json.load(f1)
    data2 = json.load(f2)

data1['directory'] = data2['dirPath']

for img_name in data2['images']:
    if img_name not in data1['pages']:
        data1['pages'][img_name] = []

    boxes2 = data2['images'][img_name]['boxes']  # 获取当前图片的所有boxes
    for box2 in boxes2:
        box1 = {
            '_bounding_rect': [
                box2['geometry']['X'],
                box2['geometry']['Y'],
                box2['geometry']['width'],
                box2['geometry']['height']
            ],
            'text': [box2['text']]
        }
        data1['pages'][img_name].append(box1)

with open('out.json', 'w', encoding='utf-8') as f:
    json.dump(data1, f, ensure_ascii=False, indent=4)
    
ImageTrans转B的脚本  互相转换的都完事了 一点代码不懂 跟GPT 聊天花了10多刀额度 哈哈。。

**Comment by xulihang** [comment]
> 不过 这个 mit48px_ctc 是真的快 我操 我都傻眼了 要能引进也不错哈哈 嘛 作为一个用户仅隔着异想天开 哈哈

48px_ctc这个模型我加上了，可以看这个更新后的说明：https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaTranslatorOCR

**Comment by lhj5426** [comment]
> > 不过 这个 mit48px_ctc 是真的快 我操 我都傻眼了 要能引进也不错哈哈 嘛 作为一个用户仅隔着异想天开 哈哈
> 
> 48px_ctc这个模型我加上了，可以看这个更新后的说明：https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaTranslatorOCR

嗯 去瞅瞅捅咕捅咕 感谢

**Comment by lhj5426** [comment]
![Uploading image.png…]()
这个样子是成功了吗？

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/0df2b78f-8365-4330-aac8-0e0da3ddf901)
这回好像对了

**Comment by lhj5426** [comment]
首先 非常的感谢 开发者老哥 今天更新这个 manga-image-translator 的 OCR模型 不过
这么说不知道会不惹您生气

其实 ……最近…… 又更新了一个新模型 要是能直接跟进一下就更好了 哈哈哈哈…………
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/16e6df47-0816-4ed8-a4f5-6890a8a13c48)

**Comment by xulihang** [comment]
新的模型没发现有什么优点

**Comment by lhj5426** [comment]
> 新的模型没发现有什么优点

我看 网上 漫画网站上 是这么说新模型的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/834f8a7e-7c12-4c78-93d4-9a8a9ed8fcda)

**Comment by Kamikadashi** [comment]
> bandicam.2023-11-29.00-00-25-145-00.00.25.253-00.01.01.148.mp4 
> 这个新的OCR 模型 速度很快 拿来直接 截图玩游戏都可以 用在游戏上识别率还比原来的Manga OCR 高很多
> 
> 而且支持多语言 平时日常用来OCR个啥东西 都可以 妥妥的 不局限于漫画本身了哈哈

Which model is being used here? Is it the new 48px model or the old one?

**Comment by lhj5426** [comment]
> > bandicam.2023-11-29.00-00-25-145-00.00.25.253-00.01.01.148._mp4_
> > 这个新的OCR 模型 速度很快 拿来直接 截图玩游戏都可以 用在游戏上识别率还比原来的Manga OCR 高很多
> > 而且支持多_语言_ 平时日常用来OCR个啥东西 都可以 妥妥的 不局限于漫画本身了哈哈
> 
> Which model is being used here? Is it the new 48px model or the old one?

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/515bcf7a-da0a-4447-865f-8c29a1f370f2)

**Comment by Kamikadashi** [comment]
> > > bandicam.2023-11-29.00-00-25-145-00.00.25.253-00.01.01.148._mp4_
> > > 这个新的OCR 模型 速度很快 拿来直接 截图玩游戏都可以 用在游戏上识别率还比原来的Manga OCR 高很多
> > > 而且支持多_语言_ 平时日常用来OCR个啥东西 都可以 妥妥的 不局限于漫画本身了哈哈
> > 
> > 
> > Which model is being used here? Is it the new 48px model or the old one?
> 
> ![image](https://private-user-images.githubusercontent.com/30548000/286456298-515bcf7a-da0a-4447-865f-8c29a1f370f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDM2MjksIm5iZiI6MTcwMTI0MzMyOSwicGF0aCI6Ii8zMDU0ODAwMC8yODY0NTYyOTgtNTE1YmNmN2EtZGEwYS00NDQ3LTg2NWYtOGMyOWExZjM3MGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA3MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzODg1Y2Q5ZTc1MzEzMDQyYTFlOThlMWVmOWIyMjQ3ZDk1ZThlZmE4OTE0YTllODdhODM0YzA0NTMwMmRiYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BQtxtmMMtLHTkwbUk13JT7CdENeXXmXEdElT9zgxJs8)

In the console, it simply indicates that the 32px model is being used when I select db+OCR, and ‘use ctc’ when db+OCR-CTC is selected, without specifying the model. That’s why I’m asking. However, I noticed that the new model, which is 195 MB in size, is not being used. The individual who trained it claims it’s better than the 48pc_ctc model, which is now over a year old.

![chrome_XQKNW37Q3u](https://github.com/xulihang/ImageTrans-docs/assets/90068423/5ddc6918-d418-48df-9f70-439dac4b1445)

**Comment by lhj5426** [comment]
> > > > bandicam.2023-11-29.00-00-25-145-00.00.25.253-00.01.01.148.__mp4__
> > > > 这个新的OCR 模型 速度很快 拿来直接 截图玩游戏都可以 用在游戏上识别率还比原来的Manga OCR 高很多
> > > > 而且支持多__语言__ 平时日常用来OCR个啥东西 都可以 妥妥的 不局限于漫画本身了哈哈
> > > 
> > > 
> > > Which model is being used here? Is it the new 48px model or the old one?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/30548000/286456298-515bcf7a-da0a-4447-865f-8c29a1f370f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDM2MjksIm5iZiI6MTcwMTI0MzMyOSwicGF0aCI6Ii8zMDU0ODAwMC8yODY0NTYyOTgtNTE1YmNmN2EtZGEwYS00NDQ3LTg2NWYtOGMyOWExZjM3MGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA3MzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzODg1Y2Q5ZTc1MzEzMDQyYTFlOThlMWVmOWIyMjQ3ZDk1ZThlZmE4OTE0YTllODdhODM0YzA0NTMwMmRiYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BQtxtmMMtLHTkwbUk13JT7CdENeXXmXEdElT9zgxJs8)
> 
> In the console, it simply indicates that the 32px model is being used when I select db+OCR, and ‘use ctc’ when db+OCR-CTC is selected, without specifying the model. That’s why I’m asking. However, I noticed that the new model, which is 195 MB in size, is not being used. The individual who trained it claims it’s better than the 48px_ctc model, which is now over a year old.
> 
> ![chrome_XQKNW37Q3u](https://private-user-images.githubusercontent.com/90068423/286522183-5ddc6918-d418-48df-9f70-439dac4b1445.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDc2MDEsIm5iZiI6MTcwMTI0NzMwMSwicGF0aCI6Ii85MDA2ODQyMy8yODY1MjIxODMtNWRkYzY5MTgtZDQxOC00OGRmLTlmNzAtNDM5ZGFjNGIxNDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4NDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkN2ZhNTc4ZmQ1MDRlMjIxYThlMTJjMjcwY2UxYjcwNWI1YzhjMTkzYWZjODk0YmNiZTUwNDc2NGQxMWU3ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Lk-GVaqTlCruHR_d92DCmNRew4xRc9gkM6S7zNjPDA)

The speed of execution can be felt that CTC was updated yesterday 48xpctc 48XP's new model is indeed superior to 48CTC when used in another software. Similarly, we look forward to developers continuing to adapt the latest OCR models.

**Comment by Kamikadashi** [comment]
@xulihang 

> No advantages were found in the new model

Here is an example of an image that is OCR-ed flawlessly by the new mit48px model, but both the 32px and 48px-ctc models struggle with (they make mistakes in 膂力)

![capturedImage](https://github.com/xulihang/ImageTrans-docs/assets/90068423/df9b80b0-7569-47ea-b886-c037f4954776)

**Comment by xulihang** [comment]
48px的模型已经加进去了

**Comment by xulihang** [comment]
> @xulihang
> 
> > No advantages were found in the new model
> 
> Here is an example of an image that is OCR-ed flawlessly by the new mit48px model, but both the 32px and 48px-ctc models struggle with (they make mistakes in 膂力)
> 
> ![capturedImage](https://private-user-images.githubusercontent.com/90068423/286585440-df9b80b0-7569-47ea-b886-c037f4954776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjQ1MzMsIm5iZiI6MTcwMzQyNDIzMywicGF0aCI6Ii85MDA2ODQyMy8yODY1ODU0NDAtZGY5YjgwYjAtNzU2OS00N2VhLWI4ODYtYzAzN2Y0OTU0Nzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEzMjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MzI5YWM0ZmZkYzk0ODJkMGNhOWJkMDM0NTJlNTE2MGIwZjA2NGRmMjhiZjhlZTU2YzJhMjViNjFlZDk5YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ezry2t-WvUV7DzDXXXWldvkCKvCkbc6hSmf5vb8dEl8)
> 
> And another one:
> 
> ![Geminism_KgDzsnVwc6](https://private-user-images.githubusercontent.com/90068423/286605875-ab5bc8d4-6b24-4621-b5da-9c442f671078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjQ1MzMsIm5iZiI6MTcwMzQyNDIzMywicGF0aCI6Ii85MDA2ODQyMy8yODY2MDU4NzUtYWI1YmM4ZDQtNmIyNC00NjIxLWI1ZGEtOWM0NDJmNjcxMDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEzMjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMjM0OTM0ZWJlZWM1NDE0ZjI5MzAzOWM3OTQwMmZhN2I1MDJlODEzNTE2Y2RhYWVmMWY0YzNiN2JmOGRhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tMwQxbPsIpBWT-aEryHmSUYJKJ5ZruGw1FiEsDEvMuY)

By the way, what is the name of the game? I think the merging algorithm has to take the punctuations into consideration.

**Comment by lhj5426** [comment]
好耶 !
谢谢 老哥 平安夜快乐！！！
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/dfebed60-8191-437f-b1da-f1635a3ebd5d)

**Comment by Kamikadashi** [comment]
> The 48px model has been added

I followed the instructions and re-downloaded everything, yet I keep getting this error when trying to use 48px. 32px works fine, as it did before.

```.jpg
use 48px
Traceback (most recent call last):
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\Python\lib\site-packages\bottle.py", line 868, in _handle
    return route.call(**args)
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\Python\lib\site-packages\bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "server.py", line 160, in ocr
    textlines = t.ocr(img, img_bbox,textlines)
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\manga_translator.py", line 338, in ocr
    textlines = self.run_ocr_48px(img_bbox, list(generate_text_direction(textlines)), self.dictionary, self.model_ocr, 16)
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\manga_translator.py", line 260, in run_ocr_48px
    ret = self.ocr_infer_bacth(images, model, widths)
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\manga_translator.py", line 324, in ocr_infer_bacth
    return model.infer_beam_batch(img, widths, beams_k = 5, max_seq_length = 255)
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\model_ocr.py", line 390, in infer_beam_batch
    assert H == 32 and C == 3
AssertionError
127.0.0.1 - - [26/Dec/2023 02:19:27] "POST /ocr HTTP/1.1" 500 744
.jpg
Traceback (most recent call last):
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\Python\lib\site-packages\bottle.py", line 868, in _handle
    return route.call(**args)
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\Python\lib\site-packages\bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "server.py", line 160, in ocr
    textlines = t.ocr(img, img_bbox,textlines)
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\manga_translator.py", line 335, in ocr
    self.load_ocr_model()
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\manga_translator.py", line 46, in load_ocr_model
    model = OCR48PX(self.dictionary, 768)
  File "C:\Users\AL\Downloads\Compressed\manga-image-translator_2\manga-image-translator\model_ocr_48px.py", line 350, in __init__
    encoder = nn.TransformerEncoderLayer(embd_dim, nhead, dropout = 0, batch_first = True, norm_first = True)
TypeError: __init__() got an unexpected keyword argument 'norm_first'
127.0.0.1 - - [26/Dec/2023 02:19:38] "POST /ocr HTTP/1.1" 500 744```

P.S. The game is called Geminism.

**Comment by xulihang** [comment]
Somehow it uses the 32px model internally. I am not sure of the reason.

**Comment by xulihang** [comment]
Try to use the packaged version I provided for windows: https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaTranslatorOCR

**Comment by Kamikadashi** [comment]
That’s the one I was using. Somehow, it started working fine when I ran it with server.py instead of run.bat. I’ll let you know if it starts acting up again.

**Comment by Kamikadashi** [comment]
It keeps mixing up the line order, but other than that, it works great so far.

**Comment by xulihang** [comment]
I see. 48px requires GPU. If running with CPU, it will give an error.

**Comment by lhj5426** [comment]
Yes, the GPU displayed on my screenshot is 48XP. 
Because ever since I installed CUDA, I haven't used the CPU anymore. The acceleration provided by CUDA is truly irreplaceable once you experience it.

**Comment by Kamikadashi** [comment]
> I see. 48px requires GPU. If running with CPU, it will give an error.

I bet 48px is very slow on the CPU anyway, so it’s not a big problem. However, I hope something can be done about the line order when merging.

**Comment by xulihang** [comment]
Could you send an image with problematic line orders?

**Comment by Kamikadashi** [comment]
Without using any new examples, the merge works fine in this case:
![286605875-ab5bc8d4-6b24-4621-b5da-9c442f671078 (1)](https://github.com/xulihang/ImageTrans-docs/assets/90068423/260f0ad1-c731-4b04-b2a0-1e2914b13963)


However, it breaks in this case:
![286605875-ab5bc8d4-6b24-4621-b5da-9c442f671078 (fail)](https://github.com/xulihang/ImageTrans-docs/assets/90068423/6d5649c1-94dc-4227-8020-0d8fb1d8ae81)


This happens in many cases, and unfortunately, it’s not predictable. This means that sometimes it works better with the full window screenshot, and sometimes only with a part. In some cases, it always gets it wrong, no matter what.

**Comment by xulihang** [comment]
You have to adjust two settings:

1. Minimum growth height. Set it higher to merge lines.
2. Check separation. Uncheck it to merge lines with a complex background.


![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/3800edc2-87a5-45b0-babf-537c02119b40)

**Comment by xulihang** [comment]
> I see. 48px requires GPU. If running with CPU, it will give an error.

I just checked again. It should be related to using an old version of PyTorch, I will update it in the packaged version.

**Comment by Kamikadashi** [comment]
I'm using ScreenReader and this doesn't seem to do anything.



> You have to adjust two settings:
> 
> 1. Minimum growth height. Set it higher to merge lines.
> 2. Check separation. Uncheck it to merge lines with a complex background.
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/292868667-3800edc2-87a5-45b0-babf-537c02119b40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTUwMjMsIm5iZiI6MTcwMzU5NDcyMywicGF0aCI6Ii81NDYyMjA1LzI5Mjg2ODY2Ny0zODAwZWRjMi04N2E1LTQ1YjAtYmFiZi01MzdjMDIxMTliNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMTI0NTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M2MDhlZTQ1NGVmNWY3OTM4Y2RmNjc0ZWQwNjg0MjhiOTE0M2U1NGQ3NzIzZTU3MDFhNGQ5NTAyYTRkOGMxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Tg0It60E_mnN2ZEhAdJdbKfxjZIBVGimW8-w0YLcylo)

**Comment by lhj5426** [comment]
> The screenreader does not sort the text areas and directly use the text returned by manga-image-translator. I have to update ImageTrans and the plugin.



> The screenreader does not sort the text areas and directly use the text returned by manga-image-translator. I have to update ImageTrans and the plugin.

那顺便 把这个也解决了吧
https://github.com/xulihang/ImageTrans-docs/issues/237
屏幕读取器 这个OCR 增加一个全局快捷键 
谢谢老哥了

**Comment by Kamikadashi** [comment]
> The screenreader does not sort the text areas and directly use the text returned by manga-image-translator. I have to update ImageTrans and the plugin.

Here is another example of the problematic screenshot:
![WoH_P5Vw3sNsyV](https://github.com/xulihang/ImageTrans-docs/assets/90068423/a5b8db13-b4ac-46e9-9676-b2c2fc4ce027)

**Comment by xulihang** [comment]
> > I see. 48px requires GPU. If running with CPU, it will give an error.
> 
> I bet 48px is very slow on the CPU anyway, so it’s not a big problem. However, I hope something can be done about the line order when merging.

The order problem should be solved in v2.8.0.

You have to check "Correct text order" in Screen Reader.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/a66c94e4-2ca5-480b-a0a9-afd453c91f19)

**Comment by xulihang** [comment]
Details about the order problem for screen reader: https://github.com/xulihang/ImageTrans-docs/issues/553
