### ISSUE TITLE
诡异的背景颜色

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#497]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/0f41815b-ffa5-40a6-8b35-71176dce9921

尊敬的老哥 我拿咱的软件 来翻译 RPG游戏里的图
翻译到这张图片的时候？？
查看翻译的时候 这个背景颜色异常的诡异 
我的图片格式是PNG的 
![002SYS050](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ad8153b0-4ae5-4f29-8dae-d966e5401552)
原图 是这样的 为什么 会出现这种诡异的现象呢？

**Comment by lhj5426** [comment]
不开精确涂抹
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/925ebe3e-556a-4993-878a-27bf0678d1fe)
开了之后
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/848fc00c-a269-40a6-be44-278c3971f9fc)

**Comment by xulihang** [comment]
这张图片有透明信息，去文字图和原图叠加后导致颜色加深了。

**Comment by xulihang** [comment]
噢，不对，应该是去文字图忽视了RGBA通道中的透明信息，导致和原图不一样了

**Comment by lhj5426** [comment]
> 噢，不对，应该是去文字图忽视了RGBA通道中的透明信息，导致和原图不一样了

就是生成的这个图片很诡异
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/49fa26e9-06cb-4fd7-b3a0-bc5176b97fcf)
颜色 深了很多 虽然 自己玩游戏 用不精确的这样也行
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2edf9a55-714a-43cb-8f72-1a7a142f8753)
不过还是想知道为什么这样 哈哈

**Comment by xulihang** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/e22b7996-355d-45a8-b222-f4f33cb88c62)

用画图另存为一下，把透明度信息去掉后再处理就行了。

带透明信息的png的文字去除问题，这个issue有讨论，一直没解决：https://github.com/xulihang/ImageTrans-docs/issues/302

**Comment by lhj5426** [comment]
> ![image](https://user-images.githubusercontent.com/5462205/271870016-e22b7996-355d-45a8-b222-f4f33cb88c62.png)
> 
> 用画图另存为一下，把透明度信息去掉后再处理就行了。
> 
> 带透明信息的png的文字去除问题，这个issue有讨论，一直没解决：#302

能解决就行 嗯谢谢了

**Comment by xulihang** [comment]
v2.9.1加强了对这种PNG图片的支持。

在文字去除项目设置里，设置精确文字抹除方式为透明文字，并勾选按文字区域处理，可以较好地处理你发的图。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/8f431b40-4ccc-4156-88d3-a0d5060758ed)

**Comment by lhj5426** [comment]
> v2.9.1加强了对这种PNG图片的支持。
> 
> 在文字去除项目设置里，设置精确文字抹除方式为透明文字，并勾选按文字区域处理，可以较好地处理你发的图。
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/313476947-8f431b40-4ccc-4156-88d3-a0d5060758ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODQxNDksIm5iZiI6MTcxMDY4Mzg0OSwicGF0aCI6Ii81NDYyMjA1LzMxMzQ3Njk0Ny04ZjQzMWI0MC00Y2NjLTQxNTYtODhkMy1hMGQ1MDYwNzU4ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTdUMTM1NzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZjY2EwMWUwZjM4YzE0ZDgzMTNhMzhhYzA0MWQxZjFhZjI5MGZhYzI1NTQ2MDczMTMxZDlhMzAwZjcxNDY5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JCTtLccJ9Gx6DpCPNJwfvuaAun9hPrUlvoeszncKbjU)

嗯  下次再遇到的时候 试试  谢谢
