### ISSUE TITLE
查找替换里可以进行多选操作吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#498]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ebfb935a-cbff-498d-916f-8b1adc1a930c)

 如图 开发者老哥
 
 因为oCR嘛 存在不确定性
 有时候会识别乱码 或成英文字符
 这样的 页面多了的话会很多
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/909015f9-fd04-47d3-839e-c7d25927f336)

 所以用 正则 来快速筛选是删除是很方便的
 可是 有时候太多了 这个正则的界面 要是可以 按住 crl 加左键点击 可以一个一个加选
 然后 选中一条 然后按住shift点击单击然后  间隔几个 再点次点击单击 这些 中间跨度的能全部被选上就好了 
 会很方便  
 就像 系统的 多选那样。。  会更方便操作一些

**Comment by lhj5426** [comment]
还有
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/577faf75-b14d-411c-902e-05cc54a4b0c6)
您看嘛 这里 这么大的空白地方 能不能像旁边的 大小写转换那样 弄个菜单 弄一些常用的正则预设在里边比如  这种啊 .*? ^.$ 比较常用的  之列 的筛选预设

**Comment by xulihang** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/03d88a78-a289-49da-b0f0-712efe180cef)

多选功能加上了

有什么可以加的预设正则吗

**Comment by lhj5426** [comment]
帮助文档链接也是不错的  软件的正则说明

**Comment by xulihang** [comment]
多选操作加在v2.5.3里了。

正则写了个帮助博客在这里：https://www.basiccat.org/zh/useful-regular-expressions-in-translation/

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4e125e23-09d2-48dd-95ef-3a01a8283345)
 牛啊 这就太方便了  清理起来多选的拟声词 然后
 就可以
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ef088b35-dbf5-4d57-96be-6589b15995ab)
 一次性解决所有了
 然后 老哥 还有一个直觉上的操作
 您可以优化一下吗
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/04ffc157-738f-42ca-bffa-153d7bcd2e22)
就是这个跳转到对应的图片 不是再右键 而是直接双击 就跳转可以 调整成这种 
直觉形式的操作吗
