### ISSUE TITLE
关于图片导出的字体大小位置和编辑时不一致的问题(旋转导致的)

### ISSUE THREAD

**Issue by nortrom-neverafk** [xulihang/ImageTrans-docs#499]
首先,软件很好用,在这里表示感谢.
然后,有个bug最近一直在困扰我:
旋转文本框可能会导致里面的文字的大小和位置变更,而这只有在导出图片后才能看到,如图:
<img width="554" alt="QQ浏览器截图20231007154026" src="https://github.com/xulihang/ImageTrans-docs/assets/51827569/a4f7f26d-abb3-4d02-8cad-23ca0301d978">
编辑时:1.汉字"一"旋转180°后与白线垂直相交 2.两个汉字"标准"字体大小是一样的

============================================
但导出的图像如下:
![未命名](https://github.com/xulihang/ImageTrans-docs/assets/51827569/7434a322-a25c-40c0-ac4d-97618ddca0f3)
很明显:
1.汉字"一"远离了白线
2.旋转后的"标准"变大了很多.

======================================
我不清楚你是怎么处理文本框的旋转的,但我记得图像的导出好像就是通过截屏实现的.
如果是这样的话,那么我认为这是个bug,你可以测试一下.
再次表示感谢!

**Comment by nortrom-neverafk** [comment]
补充一点:
旋转之后改变文本框大小会改变字体大小;然而不旋转的话,无论怎么改变文本框大小,也不会改变字体的大小.
应该将旋转后的字体大小与不旋转时保持一致.

**Comment by xulihang** [comment]
我没遇到这个问题，可以把项目和图片发过来吗？

还有版本号是多少？

**Comment by xulihang** [comment]
我启用大图导出模式后的确有了这个问题，应该是计算的外接矩形比实际需要的矩形大了点。

如果图片比较小，默认用截屏的方式导出应该是没这个问题的

**Comment by xulihang** [comment]
大小的问题解决了，位置还有点偏移，这个暂时没搞定。我是用这个变换去计算坐标的：https://docs.oracle.com/javase/8/javafx/api/javafx/scene/transform/Rotate.html

https://github.com/xulihang/ImageTrans-docs/assets/5462205/0d131fd2-2356-4f4f-b4b2-a001e7903f2b

**Comment by nortrom-neverafk** [comment]
感谢回复,取消大图导出模式后就正常了.
请问这个大图导出模式有什么作用?我4000*4000大小的图像都可以通过正常模式导出且无异常

**Comment by xulihang** [comment]
分辨率太大，一般高度大于8000时，截屏的方式可能会报错。高度大于8000或者启用大图模式时会用这个大图导出模式

**Comment by xulihang** [comment]
大图导出模式的这个问题v2.5.3修复了
