### ISSUE TITLE
error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by LazyGitan** [xulihang/ImageTrans-docs#5]

**Comment by xulihang** [comment]
Please post the entire error message

**Comment by HeLan8** [comment]
I have the same issue, here is a link with the entire error message
https://imgur.com/P6znubk

**Comment by xulihang** [comment]
You should paste the error message instead of posting an image.

Are you trying to import images? You have to create a new project before doing so.

**Comment by HeLan8** [comment]
My bad, I just bought it and didn't know what was wrong. Works perfectly now. I can finally read 200 volumes of Golgo 13 and other stuff that wasn't translated. Good job, xie xie
