### ISSUE TITLE
when I Merge text , be mixed.

### ISSUE THREAD

**Issue by bravehon** [xulihang/ImageTrans-docs#50]
![1](https://user-images.githubusercontent.com/79227082/117541046-ff2bdd80-b04c-11eb-8d25-2738160036b0.jpg)

![2](https://user-images.githubusercontent.com/79227082/117541049-0226ce00-b04d-11eb-8afe-5b0c006cf7ba.jpg)

can you fix it?

**Comment by xulihang** [comment]
What do you mean by saying mixed?

If you need to merge boxes and make the text in the correct right-to-left order. You need to enable this in the project settings.

![image](https://user-images.githubusercontent.com/5462205/117544808-a57be100-b055-11eb-81d6-25b933c6cbc8.png)

**Comment by xulihang** [comment]
To automatically merge text lines into paragraphs:

Shrink the pixels to expand:
![image](https://user-images.githubusercontent.com/5462205/117544834-cd6b4480-b055-11eb-9981-0686cfa6d5b3.png)

And adjust text box merging parameters if needed.

![image](https://user-images.githubusercontent.com/5462205/117544881-073c4b00-b056-11eb-9c7d-40e0e51fc3ab.png)

**Comment by bravehon** [comment]
> What do you mean by saying mixed?
> 
> If you need to merge boxes and make the text in the correct right-to-left order. You need to enable this in the project settings.
> 
> ![image](https://user-images.githubusercontent.com/5462205/117544808-a57be100-b055-11eb-81d6-25b933c6cbc8.png)

it's not work...

![제목 없음](https://user-images.githubusercontent.com/79227082/117554775-c879b580-b094-11eb-85b3-cb74604dd364.jpg)

I setting right to left reading 
but use Merge text sequence is mix

**Comment by xulihang** [comment]
I just tested it and it works.

https://user-images.githubusercontent.com/5462205/117557399-11396a80-b0a5-11eb-995a-c4c0f952ba03.mp4

**Comment by bravehon** [comment]
https://user-images.githubusercontent.com/79227082/117558442-78144f00-b0b8-11eb-93b3-2d46362efd18.mp4

I don't know difference....

**Comment by bravehon** [comment]
https://user-images.githubusercontent.com/79227082/117558512-0dafde80-b0b9-11eb-9dfc-2d5bfb53cbe8.mp4

I think ther is some bug ...
how can I apply  right to left reading?

**Comment by xulihang** [comment]
Sort the text areas before merging.

**Comment by xulihang** [comment]
You can use the Horizontal Merge button in the right. It will run sort first,

**Comment by bravehon** [comment]
> You can use the Horizontal Merge button in the right. It will run sort first,

wow It works! 

I use cutom workflow
how can I all pictures Horizontal Merge?

**Comment by xulihang** [comment]
Set the boxes merging param:

![image](https://user-images.githubusercontent.com/5462205/117564665-c426ba00-b0df-11eb-813b-85c1c6e202a8.png)

**Comment by bravehon** [comment]
https://user-images.githubusercontent.com/79227082/118021848-a20a9180-b396-11eb-992c-e8ec325d1bcc.mp4

just error how to that?

**Comment by xulihang** [comment]
The background is not pure white. Uncheck the check separation checkbox.

![image](https://user-images.githubusercontent.com/5462205/118063319-70f88400-b3cb-11eb-8914-77c04ead0141.png)

About the second operation, close the project first then open another project.

**Comment by bravehon** [comment]
> The background is not pure white. Uncheck the check separation checkbox.
> 
> ![image](https://user-images.githubusercontent.com/5462205/118063319-70f88400-b3cb-11eb-8914-77c04ead0141.png)
> 
> About the second operation, close the project first then open another project.

ah... when background is not pure white but Recognize? Can't it be applied all at once?

**Comment by xulihang** [comment]
> when background is not pure white but Recognize? Can't it be applied all at once?
I don't quite understand.

**Comment by bravehon** [comment]
> > when background is not pure white but Recognize? Can't it be applied all at once?
> 
> I don't quite understand.

you say when I text be mix Horizontal Merge button? but... background color is not pure white it is not work
 I hope whatever the background works.

**Comment by xulihang** [comment]
Uncheck the check separation checkbox so it will ignore the background. But please note, it may merge text areas that should not be merged together.

**Comment by bravehon** [comment]
> Uncheck the check separation checkbox so it will ignore the background. But please note, it may merge text areas that should not be merged together.

Okay I see
