### ISSUE TITLE
要怎么样做才能让ImageTrans使用自己部署的GPU版 Lama Cleaner

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#505]
如图  老哥 
我下载了 这个一键安装版V2的 新  Lama Cleaner
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/333317eb-ee69-4f39-83fb-0dccedac135b)

 在 Lama Cleaner 的界面上使用GPU是没问题的
 然后 
 在 网盘里下的端口是
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c70472d3-2cc7-4a3b-9a12-8cc866912114)
8087
 我把 这个新v2
也直接修改成了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/3293968e-ff22-4900-921e-3c5788f4ffd2)
8087 在 ImageTrans 不会被调用
是不是像 OCR 使用GPU的时候 一样 我需要下载个什么库?

**Comment by xulihang** [comment]
lama-cleaner的版本需要是0.12.0，高版本的HTTP接口不一样，目前的插件不能用

**Comment by lhj5426** [comment]
> lama-cleaner的版本需要是0.12.0，高版本的HTTP接口不一样，目前的插件不能用

哦好吧 现在的 1.2.0 差了个 0

**Comment by xulihang** [comment]
我把插件更新了下，可以用1.2.x的lama cleaner：
[lamainpaint_plugins.zip](https://github.com/xulihang/ImageTrans-docs/files/13327436/lamainpaint_plugins.zip)

**Comment by lhj5426** [comment]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/ebb6eec8-a0aa-4018-b835-49b67c1c096a

这也太爽了   好使 非常感谢
