### ISSUE TITLE
能不能增加一个 固定 全局固定识别区域功能

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#506]
是这样的开发者老哥  在给RPG游戏里的图片做翻译的时候
图片大小都是一样的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2a768e8e-ca3f-462c-aad8-6c2a78adaa63)
但用 软件现有的任何识别方式都不能很好的识别
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7cd06395-8570-43d4-90c2-d0d6972b43c2)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/85987f42-7544-42be-b64e-a7dcdb077f1b)

如果可以增加一个全局固定区域框选识别的话 就可以很好的解决这个问题
就比如 截图上的固定位置截图那种功能
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ef969ef0-202a-421c-8c5e-ca9b5708a268)
我们可以不可以借鉴下 然后 在软件上手动拉一个框 然后之后所有的图片都在这个框里
然后执行识别 后续图片也都在这个位置进行识别？
能考虑增加一下这种固定识别的功能吗

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/96721f1c-34c5-418b-9f39-24dd09801638)
这样我只 拉一个框 拉一次  然后启动 全局固定识别功能 执行识别 就后续所有的图都在这个范围内进行识别了

**Comment by xulihang** [comment]
你这些图，用现有的识别方式，比如百度、有道应该都是能识别的吧。

目前有一个建立全图文本框的功能，会以整张图片为单位建立文本框，你看下是不是符合需求

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/f9cb0dd9-2b78-453a-9620-8176ce85d6f2)

**Comment by lhj5426** [comment]
> 你这些图，用现有的识别方式，比如百度、有道应该都是能识别的吧。
> 
> 目前有一个建立全图文本框的功能，会以整张图片为单位建立文本框，你看下是不是符合需求
> 
> ![image](https://user-images.githubusercontent.com/5462205/278683326-f9cb0dd9-2b78-453a-9620-8176ce85d6f2.png)

老哥说的在线方式我的额度我早就用超了  

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/0b89d1ef-e767-4543-ab3b-e826c91347b3)


![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d47d0ab7-355c-4a53-bf7f-cf756dba18b0)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1b71010c-aa94-4f04-939a-6edf1a67fec7)

好像也行 ？ 没有把 4边 的UI 给涂抹上

**Comment by lhj5426** [comment]
完全够用了   感谢！！
