### ISSUE TITLE
最近打开项目的跨屏bUG

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#509]
老哥 如图
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/6a85cd2c-f3be-4af7-8ea0-e3fec19cd4e1)
您看到的这样
我电脑连接了4块屏幕 分别是4 2K 2 和3 是1080 1是4K
2号屏幕我设置的是主屏幕分辨率是1080 1920
然后 我在主屏幕上打开ImageTrans
之后想要打开之前的历史记录
现在不知道为什么历史记录 最近打开打开的项目跑到 4号屏幕这边了
4号屏幕是 2K屏幕 分辨率是2560 1440 的 
这样很不方便 
前几天 不对  昨天还好好的呢
今天就突然这样了 我重启过电脑 也是还是这个样子。。  

您刚才更新了 文件 
https://github.com/xulihang/ImageTrans-docs/issues/502
我更新完想要试试 结果一打开 历史就跨屏了 

呃 是因为有的路径太长了？
![2023-11-01-14 00 43](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4bb4a509-aed2-4773-88ca-6bd55f31dcdd)

**Comment by xulihang** [comment]
这个路径有多长啊？过长的话，比如大于100，我可以把中间文本裁掉，用省略号表示

**Comment by lhj5426** [comment]
> 这个路径有多长啊？过长的话，比如大于100，我可以把中间文本裁掉，用省略号表示

确实  一般情况下不会这么长不知道为什么突然就这么长了 然后就触发了这个
确实 可以裁切一下 不需要完全显示 前 几十个字符已经能够知道是那个项目了

**Comment by xulihang** [comment]
v2.5.4会缩略长度超过50的路径

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7ec800c5-89a0-497c-8cd4-9e51af5bd2c3)
这样 就不会出跨屏问题了 非常感谢！！！！
