### ISSUE TITLE
Google_drive OCR problem

### ISSUE THREAD

**Issue by ByRoT91** [xulihang/ImageTrans-docs#511]
Hello!

I always use the google_drive OCR function, in my opinion, this is the best.
Today, it's not work, google_drive cannot OCR.
This messages after OCR:
![googledriveimagetrans](https://github.com/xulihang/ImageTrans-docs/assets/104424475/f1216947-89b6-46ef-8535-edaa753a3d5d)
Or : Server Error.

Can you fix it?  I use the last version of you ImageTrans, but older versions have same problem with google_drive OCR.

Thanks the answer!

**Comment by xulihang** [comment]
The token for google drive expires every 7 days. I have to update it manually, otherwise it will not work.

You can set it up using your own google drive following this guide: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/

**Comment by ByRoT91** [comment]
I see, so, you will update this manually, and it will work again as example tomorrow?
Because if this is true, i am waiting for this.

**Comment by xulihang** [comment]
I will update it.

**Comment by ByRoT91** [comment]
Okay thanks, I am waiting for the update :)

**Comment by xulihang** [comment]
updated.

**Comment by ByRoT91** [comment]
It's perfect, work again :)
And the next time, the google drive token expires, and you see it, will you update this manually again and again?
Just because the next time, I see that google drive don't work, I don't ask anything, just wait for your manually update to work again.

**Comment by xulihang** [comment]
I may not update it in time when I am lazy.
