### ISSUE TITLE
OCR识别问题 

### ISSUE THREAD

**Issue by Occ1996** [xulihang/ImageTrans-docs#512]
软件识别里面有个baidu_ntework  我用着好好的  突然不能使用了  识别都是null  还有有道 我申请了 资格 填进软件 始终用不了 原文都识别不到  我看了几遍 没有填错       另外我做的重嵌  咨询下 繁体中文 竖版  右读  用什么识别最好

**Comment by xulihang** [comment]
百度网络图片接口每天只能请求500次。需要自己申请API密钥去使用


有道需要充值，申请后照下面这样填：
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/6e26b177-b80a-47bc-81e9-31e3c328855d)

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/417acc2c-153b-4391-9345-3728134a5d02)

**Comment by xulihang** [comment]
重嵌见之前的issue：https://github.com/xulihang/ImageTrans-docs/issues/446

**Comment by Occ1996** [comment]
请问我看到有机器翻译 但是软件内 我好像只有某一两个 可以机翻  是需要自己申请离线的OCR吗？ 

还有就是下载的补充文件里面的依赖文件 我看不明白有什么作用 能不能在里面放个文档说明下     

另外 我百度买了一个1W的包  但是baidu_ntework  仍然是null  不能OCR 不能翻译   我分不清选项里的baidu和baidu_ntework 哪个是调用的网络视图  密钥什么的我是填在baidu 一栏 不是baiduMT
![Uploading QQ截图20231110175657.png…]()

**Comment by xulihang** [comment]
百度有两种API，一种是机器翻译，一种是文字识别。

机器翻译的API填到baiduMT里，文字识别的填在baidu里。

机器翻译的图片翻译功能也能用于文字识别，每月1万次调用量。

**Comment by xulihang** [comment]
依赖文件目前已经用不着了
