### ISSUE TITLE
Keep same settings in different projects

### ISSUE THREAD

**Issue by Flowfo** [xulihang/ImageTrans-docs#516]
Hey!
How to keep the same project's settings when opening a new project ?
(I'd like to keep the same fonts).
Thanks

**Comment by xulihang** [comment]
You can save the project as a new project to keep the settings.

**Comment by Flowfo** [comment]
Good idea but how to delete all former pictures from the navigation menu (at the bottom).

**Comment by xulihang** [comment]
Currently, ImageTrans does not have the function to delete all the images from the project. You need to manually edit the project file.

Change the following:

```
"images": {
        "filename.png": {
            "boxes": []
        }
    },
```

To the following:

```
"images": {
    },
```

**Comment by Flowfo** [comment]
Ok. Thanks :)

**Comment by xulihang** [comment]
I added a context menu item for the image combo box to remove all the images in v2.5.6: 
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/517f10d8-f515-448c-be1c-3680bfe7ad38)

**Comment by xulihang** [comment]
Files on onedrive will be updated. You can find the link in the email sent to you.
