### ISSUE TITLE
Former text is not totally removed

### ISSUE THREAD

**Issue by Flowfo** [xulihang/ImageTrans-docs#517]
Hi,
When displaying the translated page, the former text is still visible.
On which settings do I have to play with?
![buble](https://github.com/xulihang/ImageTrans-docs/assets/48133323/24804adc-15ca-42df-a760-62755a2536e1)

**Comment by xulihang** [comment]
You can try to increase the mask dilation kernel to fit your image:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/a04640c3-6057-4e7c-a6a3-2c147eee4dc2)

**Comment by Flowfo** [comment]
Perfect!
It did the job.
Thanks for your help!
