### ISSUE TITLE
ocr google_drive does not work

### ISSUE THREAD

**Issue by JhojanVC** [xulihang/ImageTrans-docs#518]
google_drive ocr gives server error how to fix it?
Please help
![Captura de pantalla 2023-11-17 231052](https://github.com/xulihang/ImageTrans-docs/assets/141593096/a7a86b37-9360-4f59-b014-765117002e3b)

**Comment by xulihang** [comment]
As discussed here: https://github.com/xulihang/ImageTrans-docs/issues/511

Wait for me to update the expired token or set up your own google drive.
