### ISSUE TITLE
请问如何更新？

### ISSUE THREAD

**Issue by Jookemyyy** [xulihang/ImageTrans-docs#519]
如何更新，超过免费更新时间后，后续想更新改如何操作？

**Comment by xulihang** [comment]
6个月后更新可以到这里购买更新版：https://mbd.pub/o/bread/YpmUmJps

**Comment by Jookemyyy** [comment]
> 6个月后更新可以到这里购买更新版：https://mbd.pub/o/bread/YpmUmJps

订阅一次相当于可以再免费更新6个月内的更新是吧？

**Comment by xulihang** [comment]
是的

**Comment by Jookemyyy** [comment]
> 是的

好的。
