### ISSUE TITLE
Add new images

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#52]
I don't know if this would be difficult to do, but it would be nice if you could add new images to your folder and when you open the project then imagetrans updates the folder and imports the new images without changing the information of other images.

**Comment by xulihang** [comment]
If you add new images to the same folder and then import the folder, it will add new images without changing other images.

**Comment by HeLan8** [comment]
Aah, you're right, I thought after you've opened a project with existing images that you can't use the import feature, but it works, thanks
