### ISSUE TITLE
自动更正可以支持正则吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#520]
https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaTranslatorOCR
按照 教程 设置完 最新的OCR 和识别模型之后
遇到了一个通病

https://github.com/xulihang/ImageTrans-docs/assets/30548000/433bea2f-87d8-4089-9bb2-d8e3ea98f897

 如视频上展示的这样 假如 自动更正有正则功能的话
 那么这种数字 直接在 自动更正里 输入 ^(\\d{2})$ 而替换 为空
 这种正则 
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5ee120fc-cb4e-426f-807b-939a4bf03bd9)

 在OCR的时候 就 会被自动替换成 空了 这样 在全部OCR识别完之后
 运行一个 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7675530f-b040-4df2-9ed5-55a48e354b4c)
就可以轻松的 删除 了 
当然这只是一个引子
还有拟声词 的识别问题 因为图片问题 就不方便发图了
以另外图像来说明
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1f2eda04-73e5-497d-aee0-26b0ec6241ac)
 因为现在使用但是 manga-image-translator 的识别和OCR引擎
 这个工具的引擎 会识别出超大量的 拟声词  一个个手动删 是很不现实的
 所以给自动更正增加 这种 正则替换
 只要数量够大 在下次OCR的时候 就会命中一部分拟声词 减少一部分 手动删除拟声词的工作量

 这样 双管齐下 配合 之前的 搜索添加的正则可以最大限度的减少 手动删除拟声词的工作量
 虽然现在GPT3.5比白菜还便宜了 但是  GPT变的更傻了 因为拟声词 导致的串行问题更严重了 
 所以 
  还请老哥可以考虑一下添加上

**Comment by xulihang** [comment]
加在v2.5.6里了

**Comment by lhj5426** [comment]
> 加在v2.5.6里了

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/89395317-15ef-40ed-a20a-9a227ea1aa2c)
哦 我尊敬的老哥  您好像忘记上传到 OD了 百度云 没有会员虽然只有100m 下载的也很痛苦
还请 补传一下 OD 感谢了!!!!!!!!!!!!!

**Comment by xulihang** [comment]
2.5.7做了下面的更新，可以配合这个功能使用。

> v2.5.7 (2023/12/03)
> 修复OCR大图时生成的掩膜被缩小的问题
> 掩膜编辑器新增去除文字区域外掩膜的操作
> 新的自定义工作流项目：去除所有图片的无原文区域、去除所有图片的框外掩膜

**Comment by lhj5426** [comment]
> 2.5.7做了下面的更新，可以配合这个功能使用。
> 
> > v2.5.7 (2023/12/03)
> > 修复OCR大图时生成的掩膜被缩小的问题
> > 掩膜编辑器新增去除文字区域外掩膜的操作
> > 新的自定义工作流项目：去除所有图片的无原文区域、去除所有图片的框外掩膜

https://github.com/xulihang/ImageTrans-docs/assets/30548000/54740c63-6bb5-4c27-89b0-2aabd34b0d55


恩 收到了 这个功能有点意思
