### ISSUE TITLE
ScreenReader improvement

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#521]
It would be great if the ScreenReader had the capability to adjust the opacity of the ‘fixed area capture’ window. Additionally, it would also be beneficial if it could monitor changes in the selected area and automatically perform OCR on the area if the changes exceed a specified threshold. This enhancement would broaden the potential use cases for the ScreenReader, making it a more versatile tool.

**Comment by lhj5426** [comment]
嘻嘻 希望可以联动下这个
https://github.com/xulihang/ImageTrans-docs/issues/237
都是在一个界面上的功能 要是能一起迭代 优化就好了

**Comment by Kamikadashi** [comment]
I've done some additional testing and it seems that for the mangaTranslator OCR to accurately detect text in old, low-resolution games, it needs to be upscaled first. I suppose that’s why mangaTranslator now has a 4x-UltraSharp upscaler. I’m not certain how good it is, but I’ve done some testing with realesrgan-ncnn-vulkan and it consistently helps in achieving good results. 

With new high-resolution games, the OCR works just fine right out of the box, with no need for upscaling. The only issue I’ve encountered with high-res so far is that when there’s a full screen of text with many lines stacked one below the other, they sometimes get scrambled. It would be beneficial to have an option to force them to be ordered by the x or y-axis.

For low-res, I've tested with: 魔人形 (Neko Project II emulator) and マテリアル・ガール
High-res: Geminism 〜げみにずむ〜

**Comment by xulihang** [comment]
These features are added in v2.8.0.

1. You can adjust the alpha of the window in fix area mode.
2. You can start an interval to OCR an area. Motion detection is enabled by default. You can adjust them in the preferences.

**Comment by xulihang** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/0e1d58e6-5253-4442-81f9-3e40787b1884)

**Comment by Kamikadashi** [comment]
For some reason, it takes a screenshot with the box on top of the selected area and doesn’t sort the lines correctly, even though I checked the ‘Correct Text Order’ option.
![chrome_jkC0mo4z5c](https://github.com/xulihang/ImageTrans-docs/assets/90068423/f98c2980-4938-4087-b592-f3ee611c057f)

**Comment by xulihang** [comment]
Which OCR are you using? The order should be correct using manga-image-translator.

If it is not the desired order, try to set the sorting criteria to vertical ordinate in the project settings. You can test the sorting in the main window first.

**Comment by xulihang** [comment]
Hiding the capture box in the interval mode is annoying, so I just keep it. You can set its alpha value to 0 so that the captured image will not have it.
