### ISSUE TITLE
想问下batch_prompt 是干什么的？

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#525]
rt,在设置prompt的时候没理解

**Comment by xulihang** [comment]
ChatGPT多句一起翻译时用到的提示语：https://www.basiccat.org/zh/ChatGPT-image-translator/#%E5%A4%9A%E5%8F%A5%E7%BF%BB%E8%AF%91

**Comment by haofan170** [comment]
> 没明白。对齐位置吗，这个切换工具栏可以找到

感谢==我找找看看
