### ISSUE TITLE
想问下在合并多个文本框的时候，合并的规则是怎么样的？

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#526]
rt，我在合并了以后顺序就会变乱了==  有点没搞懂他这个合并几个文本框的规则（哪个在前哪个在后）

**Comment by haofan170** [comment]
> 项目设置里设置从右到左阅读顺序，会改变排序和合并的行为

但是有个地方我不太理解==  打个比方：在这段文字里面。打开了从右往左阅读以后，前两句话的合并是正常的
![4](https://github.com/xulihang/ImageTrans-docs/assets/49093867/19fe0b7f-af71-4204-addc-5bcf26ac7ed4)
：
![Q2](https://github.com/xulihang/ImageTrans-docs/assets/49093867/0a1cfeac-491d-4ad1-aa9f-43b31ed43eb0)
![zc](https://github.com/xulihang/ImageTrans-docs/assets/49093867/8a560d1a-89db-4e20-ad64-ea2148a2d3b9)
但是当选择了第三句话的时候，理论上应该在后面的第三句话就跑到前头去了==：
![Q3](https://github.com/xulihang/ImageTrans-docs/assets/49093867/182714ea-b0d5-42d5-9c18-7b6dd49c0737)
![BUG](https://github.com/xulihang/ImageTrans-docs/assets/49093867/71f80d91-2cb2-4c19-ab03-a4c6d85cf14c)
这么个情况是我对于合并所选文本的理解有错误吗（）

**Comment by xulihang** [comment]
用的工具栏的合并所选吗，这个需要先排序一下，不然是按当前列表里的位置顺序合并的

**Comment by haofan170** [comment]
> 用的工具栏的合并所选吗，这个需要先排序一下，不然是按当前列表里的位置顺序合并的

呃呃想问下怎么排序呢？有教程啥的吗（）

**Comment by haofan170** [comment]
选择问题就是新的那个OCR好用是好用，但是每一行都得分开框== 然后合并又似乎很奇怪（）

**Comment by xulihang** [comment]
排序用右下角的排序按钮，或者自定义工作流里对整个项目进行操作。切换到排序工具栏还可以给文本框显示序号

**Comment by xulihang** [comment]
文字行有背景的话，在项目设置的文字定位里取消勾选检测分隔，然后生长宽度可以设大一点。之后可以使用合并左右区域操作进行合并

**Comment by haofan170** [comment]
> 文字行有背景的话，在项目设置的文字定位里取消勾选检测分隔，然后生长宽度可以设大一点。之后可以使用合并左右区域操作进行合并

好的~我试下，还有想问下右下角这个排序的逻辑是什么？有的时候在后面的文字也还是会被排到前面这样（

**Comment by xulihang** [comment]
项目设置里可以设置根据到原点距离还是纵坐标，设置从右到左的话会把坐标镜像后排序。另外也可以根据分镜排序：https://github.com/xulihang/ImageTrans-docs/issues/147

**Comment by haofan170** [comment]
> 项目设置里可以设置根据到原点距离还是纵坐标，设置从右到左的话会把坐标镜像后排序。另外也可以根据分镜排序：#147

感谢！ 基本搞定了==
