### ISSUE TITLE
How to save the level of the zoom

### ISSUE THREAD

**Issue by Flowfo** [xulihang/ImageTrans-docs#528]
Hello,
Always in love with your soft!!!
Is there any way to save the level of zoom which displays the page?
When I open my file or export a page, it's lost. 
Probably that the whole layout and translation parameters could be also saved.
Ro

**Comment by xulihang** [comment]
Added in v2.6.0. 

Things like the zoom percentage are saved when you perform a save action and be loaded when you reopen a project.

You can disable this behavior in the preferences.
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/063a0345-0866-46a6-bee8-add2dcff3979)

**Comment by Flowfo** [comment]
Great job, thanks !!
Would be cool to save the zoom level after manually generate a translated page too.

**Comment by xulihang** [comment]
What do you mean? The zoom level will be set to 100% when generating a translated page. Do you want to return to the original zoom level after the generation?

**Comment by Flowfo** [comment]
Absolutly, it's 'tiring' to have to re-set this zoom level after each generation of translated page (via batch or manually).

**Comment by lhj5426** [comment]
还有一点 是能记住 软件的窗口状态就好了 
比如 软件窗口化 关闭时候的尺寸是1600 900 打开的时候也是1600 900
如果是窗口化 打开的时候也是窗口化 
这样 软件自身的窗口状态 也能记录就好了 不过现在能记录 项目的各种设置已经很不错了

**Comment by xulihang** [comment]
The zoom level will be restored to the previous value after generation in v2.7.0.
