### ISSUE TITLE
可以给文字大小调节增加快捷键吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#529]
事情是这个样子 开发者老哥
我在做的漫画图片分辨率是
![2023-12-08-15 49 53](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ffeb9da6-c7a8-401e-b1f4-e63cc508be57)
如图 您所看到的 3200 X1800
如果在 正常屏幕上显示100%的话是这个样子的
![2023-12-08-15 49 09](https://github.com/xulihang/ImageTrans-docs/assets/30548000/23d7e0dc-a1b2-4782-8a4e-ef95b655d965)
在初翻完成后的校对调整阶段
如果缩小图片 不好调整文字大小和气泡的距离
如果用全图又无法进行快速的整体阅读
但是刚好我的显示器可以开到
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/36c18660-c1a3-48ee-8613-623ac326728c)
这个4096 2160 的分辨率 这样只要把 系统缩放比率 调整到100%

![2023-12-08-15 43 14](https://github.com/xulihang/ImageTrans-docs/assets/30548000/3f75ca63-cfff-46b4-8a36-f564202b65e2)
如图  如您看到的
这样 在4K 100% 缩放比例的 分辨率下 这个3200 1800 的图片可以以 100%的面貌完全的显示在屏幕上
整页文字可以完整的显示且和清晰
但是 这就导致了软件的界面ui 变得很小
这样我就选择用宏来定位操作
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a2afcfe7-4a6e-4edf-92db-b272fe71c4bd)
因为是校对和调整阶段 实际上用到最多的就是调整文字的摆放 上下对齐  字体大小
然后问题就出在 字体大小调节上
虽然我可以用宏
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/92590cee-8669-4111-b159-ae61aef9e16d)
先按键盘F5 切换到 字体工具栏 然后鼠标 点击 放大 或者缩小字体的剪头
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7ec676d4-0e6f-4d26-a14c-20eb6772cb47)
宏的工作流程如图
可实际操作下来 这样 调整字体会有一个卡顿感 不和谐 只能按一下 停顿一下再继续按 不流畅
使用起来很别扭
所以 基于这个 能不能恳请您 再增加一组 字体大小调整的快捷键功能 
我记得之前某个issues 有其他的用户也跟您 反馈过希望能够增加一组 字体大小的调节快捷键
但是那个帖子还有其他问题 您只解决了重点问题 给忽略了这个
所以 今天 基于这个 使用体验的不舒适感 我再次向您提出这个问题

**Comment by xulihang** [comment]
加在v2.6.0了

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b0ce24f3-6536-4c41-b2a7-5b5c2907aaeb)
太棒了 非常感谢
这样设置到旋钮上 调节 非常的 舒服和方便    字体大小 字体左右移动 字体上下移动  都有快捷键了完美
