### ISSUE TITLE
lama-cleaner 漏擦出的现象非常严重

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#530]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/68f0a5da-7904-4b3a-8c71-b27e5e006a23)
 举个例子 掩膜都涂完了 但是 lama-cleaner 跑完之后 只有部分的被擦除了  基本上每一页都有 漏的 重新执行 也不行 
 把 这种 0044.jpg-text-removed 生成 的删掉 重新 生成新的 还是一样漏擦
 还请 老哥 检查下 是不是 运行遇到BUG ? 
 
 我目前用的是这个版本
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7e961744-98d8-42de-9738-d93a0756c9b7)

**Comment by xulihang** [comment]
发个有问题的图和掩膜我测一下

**Comment by lhj5426** [comment]
> 发个有问题的图和掩膜我测一下

[新建文件夹 (3).zip](https://github.com/xulihang/ImageTrans-docs/files/13628194/3.zip)

**Comment by xulihang** [comment]
我试了下没有问题。图片过大时，lama会进行缩放，使用lama建议勾选按文字区域处理图像。然后保证每个掩膜都有对应的文本框

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/de4ce858-eccf-4946-af25-d255225f21bc)

**Comment by lhj5426** [comment]
> 我试了下没有问题。图片过大时，lama会进行缩放，使用lama建议勾选按文字区域处理图像。然后保证每个掩膜都有对应的文本框
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/289550545-de4ce858-eccf-4946-af25-d255225f21bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDMzODYsIm5iZiI6MTcwMjMwMzA4NiwicGF0aCI6Ii81NDYyMjA1LzI4OTU1MDU0NS1kZTRjZTg1OC1lY2NmLTQ5NDYtYWYyNS1kMjU1MjI1ZjIxYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTM1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjg2MzBmMDNhOWZkYzdhZDVmOWE3YzA4ODBjZmRiMzA1YWQ2MTBjYjMyZjdiODBhZjdmOWE3Mjc3NDVlZDU4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tByxD9wMwSzbFWDNfYOlYh7VCHEiim8tr7U6se3QfdY)

嗯 好的 我按照这个试试

**Comment by lhj5426** [comment]
经过研究
我发现 如果 有漏识别的
需要做2步操作才可以正确识别
1 删掉漏识别的识别框
2打开掩膜 全删该区域的掩膜 重新涂抹
3再次查看翻译 才会真正的重新生成 新的去字图
如果没有 12 这个操作
而是不删除气泡 只 重新涂抹掩膜 并查看翻译 生成的去字图还是会 漏擦除

**Comment by xulihang** [comment]
去文字图重新生成的逻辑是这样的：

1. 如果有新的文字区域或者文字区域调整过，且没有掩膜文件，会重新生成。
2. 如果有掩膜文件，且掩膜文件比现有的去文字图的修改日期新，会重新生成。

你看下是不是哪里操作的不对

**Comment by lhj5426** [comment]
> 去文字图重新生成的逻辑是这样的：
> 
> 1. 如果有新的文字区域或者文字区域调整过，且没有掩膜文件，会重新生成。
> 2. 如果有掩膜文件，且掩膜文件比现有的去文字图的修改日期新，会重新生成。
> 
> 你看下是不是哪里操作的不对

https://alumnialbany-my.sharepoint.com/:f:/g/personal/planetrav_alumni_albany_edu/EvZL-u0_1jRAlg6nbV9R-yQBfVZkchMEObWqbJsBv7lQlA?e=UyIqrb

老哥  我录了一个视频放在网盘了里 一个是视频体积超过了GITHUB限制的10 M 一个因为图片是内入是NSFW的也不适合上传GITHUB
还请麻烦您 点击OD 链接下载查看


内容是这样的 首先您说了掩膜问题

我发现我之前只删了去文字图没有删过掩膜图

在视频演示里我去字图演示图都删了

问题一样漏擦除
然后 我把单图 复制到一个新文件夹打开一个新项目
单独 文字区域识别 并查看翻译
可以看到 是可以正常完全擦除的
然后我又回到这边的项目 用昨天回复说的
12步骤 
也确实可以擦除
我想说的 就是 在项目里 如果不执行 这个1 2步骤 真的不会 生成擦除干净的图

还请您 看一下演示 指出是我哪里操作不对导致的
麻烦您了

**Comment by xulihang** [comment]
重新保存掩膜后，掩膜文件就比去文字图新了，就会重新生成去文字图。你之前生成的去文字图我不知道什么原因，只清除了部分。我自己没试出什么问题，可以再发一个你的项目文件过来。

这些气泡里面的文字其实不需要手动去涂，可以直接用自带的基于二值化的掩膜生成方法，就是要把膨胀大小设大一点。

**Comment by lhj5426** [comment]
> 重新保存掩膜后，掩膜文件就比去文字图新了，就会重新生成去文字图。你之前生成的去文字图我不知道什么原因，只清除了部分。我自己没试出什么问题，可以再发一个你的项目文件过来。
> 
> 这些气泡里面的文字其实不需要手动去涂，可以直接用自带的基于二值化的掩膜生成方法，就是要把膨胀大小设大一点。

我上面发的 就是我最新的项目文件 以及遇到问题的
您打开 000153 这个项目文件 应该可以看到 掩膜大小我设置的是20左右
因为这部本身就是厚描边 掩膜必须设置很大才行 
就是感觉卡到了BUG

**Comment by xulihang** [comment]
噢，项目文件我漏看了。

我看了下，没有抹除的文本框右边的建立覆盖图层选项都没有勾选，这样抹除时会自动跳过这些文本框。可能是你操作时不小心勾选中了。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/e320e1bc-dcba-4b70-ac0e-4e922b19749d)

**Comment by xulihang** [comment]
可以用文本编辑器批量修改，改成建立覆盖图层：

搜索：

```
"bgColor": "transparent",
```

替换为：

```
"bgColor": "255,255,255",
```

**Comment by lhj5426** [comment]
> 可以用文本编辑器批量修改，改成建立覆盖图层：
> 
> 搜索：
> 
> ```
> "bgColor": "transparent",
> ```
> 
> 替换为：
> 
> ```
> "bgColor": "255,255,255",
> ```

哈哈 好吧 真的很感谢 老哥
原来 是 这个问题导致的 非常感谢您 

按照您这个 说的操作后 确实 
我在操作的时候右侧的框只有这么点
然后确实是误操作点错了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/bcff8a2e-9f5f-4641-8d50-d900968ac653)
总而言之 非常感谢 您 麻烦您了
