### ISSUE TITLE
关于排序能不能增加这种排序方式 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#533]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1c6394cf-0c2e-4516-89c7-4a9b01d3b0db)
我排序完发现  纵坐标 是以 从右向左开始 每个气泡的位置高低来进行排序
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/de8d7d1d-f1ca-4058-83c2-2ea5d3b75d68)
这种排序对 这种全彩的CG漫画来说 十分不友好 
所以能不能请老哥增加一个 
就是 纯粹的 从右边到左边 不分 高低 一个接着一个的自动排序功能
我也不知道 应该要怎么描述 
应该怎么形容 叫做 从右到左 排序？ 
就是这样 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/fe6a49fd-8896-48f5-bbcf-801514ad858c)
从右向左 依次扫描气泡排序 这样 对于这种长篇的CG漫画来说就是 最好的排序方式 

从原点到距离 更离谱 了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/31061520-d781-4bf9-ae54-3f251f36df7e)

这样就是比较合理的 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4f8671a1-f826-4f3b-8c5f-642bcec20987)
虽然老哥之前增加了手动排序
不过 我喜欢看全彩 然后 我看的 都是至少200页 300页的 手动排序 哈哈不太现实 
所以 就只能 寄托希望与您了 谢谢

**Comment by xulihang** [comment]
我再加一个按横坐标排序，应该可以满足需求

**Comment by lhj5426** [comment]
抱歉我的语言比较匮乏 实在 是不知道该如何形容
一个横坐标 就概括了 厉害
仔细想想 还真是 期待ing

**Comment by xulihang** [comment]
加在v2.6.0里了

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c233e165-3f49-42b1-97ab-91abc12fd39a)
 牛 这样就对了 导出文本 也是按照这个 阅读顺序了 感谢！！！！！
