### ISSUE TITLE
Add a status label to show progress

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#535]
Add a status label in the lower-right corner to show the progress.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/1b9296e7-78a6-4765-81e8-0731f4b3c525)

**Comment by xulihang** [comment]
Added in v2.6.0.

**Comment by lhj5426** [comment]
一个不经意的小设置 确很贴心

**Comment by hal9174** [comment]
Hi Xulihang,

Thank you very much to have added this feature that I was expecting for a long time.
