### ISSUE TITLE
White zone when exporting page

### ISSUE THREAD

**Issue by Flowfo** [xulihang/ImageTrans-docs#537]
Hey,
Thankd for the regular updates, it's really cool to upgrade like that :)

When exporting translated pages via batch, some are then displayed with a white area on the left (or right, top, bottom). 
Is it about text area which are defined partially outside the page ?

Can we fix this behavior ?

Best regards.

**Comment by xulihang** [comment]
Could you send a test project?

This problem should be fixed in v2.1.0: https://github.com/xulihang/ImageTrans-docs/issues/452

**Comment by Flowfo** [comment]
[For test.zip](https://github.com/xulihang/ImageTrans-docs/files/13696132/For.test.zip)
After more tests, it happens when I move a text area partially outside from the page (via one pixel shift).

**Comment by xulihang** [comment]
How did you move the text area outside the image?

The program is preventing moving the box outside the image. But the vertical center alignment is causing an exception.

For now, please take care of not moving the text areas out of the image.

**Comment by xulihang** [comment]
Another solution is to use the large image output mode which does have this problem: 
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/79bc2b2c-6362-4017-b36c-9447a1b90877)

**Comment by Flowfo** [comment]
I move the text area via shortcuts (pixel after pixel)

**Comment by xulihang** [comment]
Enable this will automatically move text areas within the image:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/11b3e01f-02ec-41d9-8acb-70da1996a122)

But it is buggy with vertically aligned text areas. I will try to fix this.

**Comment by Flowfo** [comment]
We tried the first solution (export images using large image mode.)
Ok, no more white zones but some bubbles are no more in the position that we wanted.

**It is very important to have a 'what I see in IT is what I'll get in export'.** 
We lost so many hours to check the export files :(

We also discovered that the white zones are not only caused by text areas outside the image but ALSO by translated texts which are outside their own area (whatever the position on the page.)
![bug](https://github.com/xulihang/ImageTrans-docs/assets/48133323/1298ae35-4a7a-479a-b0f4-9f2bd4e6d489)
A nightmare to check.

**Comment by xulihang** [comment]
Do not enable vertical alignment for now as it causes problems if you do not make the red box cover the entire text in large image mode.

**Comment by xulihang** [comment]
I've fixed the inconsistent position of text areas aligned in vertical center in large image mode. The files of v2.6.0 have been updated and you can have a try.

The default mode uses snapshot. You have to make sure the text is not above the image or to the left of the image.

**Comment by Flowfo** [comment]
Once we know what (not) to do, it's not a problem any more.
Thanks for the answers.

**Comment by xulihang** [comment]
The white zone problem using the default output mode is fixed in v2.7.0.
