### ISSUE TITLE
可以添加谷歌 AI  Gemini  吗 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#538]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/cbce36b9-b0c6-4234-983f-6fd2358ea686)

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/718d0fca-8ee0-4c3b-9053-bcc3e240f71e)

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/0cf3292e-bafa-4315-b5f2-5620e46ee68b)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ab600aea-5ada-4645-b687-75c8f6ef0283)
 我觉得这种翻译 太解气了
 
GPT翻译的
 要是当时有心情的话，早就辞职离开这个公司了，该死的~

谷歌AI 翻译的
老子要是有这个心思早就不干了，狗娘养的~
 
 所以能不能请 老哥 把 谷歌的  Gemini api翻译 请进 ImageTrans 里来  
 https://makersuite.google.com/app/apikey
 好像还的越狱才行
 https://github.com/openai-translator/openai-translator/tree/main

**Comment by xulihang** [comment]
写了个插件，目前需要使用美国IP访问

[geminiMT.zip](https://github.com/xulihang/ImageTrans-docs/files/13727494/geminiMT.zip)

**Comment by lhj5426** [comment]
> 写了个插件，目前需要使用美国IP访问
> 
> [geminiMT.zip](https://github.com/xulihang/ImageTrans-docs/files/13727494/geminiMT.zip)

 666 感谢 去试试   昨天 把文档分成50行一个文档 41个文档  复制粘贴 老麻烦老累了 感谢

**Comment by lhj5426** [comment]
这个好想不是一次喂一页 的内容 而是一个一个？

**Comment by xulihang** [comment]
我还没有做到多句在一个请求里翻译

**Comment by lhj5426** [comment]
嗯 抱歉抱歉 对不起

**Comment by xulihang** [comment]
我试了下，可以用和ChatGPT一样的诱导方式，多句翻译加上了：
[geminiMT.zip](https://github.com/xulihang/ImageTrans-docs/files/13734973/geminiMT.zip)

**Comment by lhj5426** [comment]
> 我试了下，可以用和_ChatGPT_一样的诱导方式，多句翻译加上了： [geminiMT.zip](https://github.com/xulihang/ImageTrans-docs/files/13734973/geminiMT.zip)

嗯 感谢 辛苦 老哥了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/42d1ad97-aeee-456d-83d7-8e927fa1497c)
