### ISSUE TITLE
我不了解如何使用imagetrans，什么是API以及如何使用它们进行OCR

### ISSUE THREAD

**Issue by Surgehero100** [xulihang/ImageTrans-docs#54]
嗨，我在尝试使用Imagetrans时遇到了问题，就像每当我尝试使用OCR函数来翻译pdf的选定文本框时一样，都不会发生任何事情。 我去过徐立航的youtube，并观看了他的视频，了解如何入门，但是每当我尝试进行OCR时，什么都没发生。 我启动程序，创建一个新项目，导入我的pdf，然后选择一个文本，然后单击OCR，但是什么也没有发生。 如果有人知道我在做什么错，请发表评论，我正在尽最大努力尝试将此软件理解为图像翻译器和api的新手，但我仍然不太了解。

**Comment by xulihang** [comment]
不要分两个issue用不同语言提问，我会在https://github.com/xulihang/ImageTrans-docs/issues/53回答你

**Comment by bravehon** [comment]
I think OCR is error / What OCR do you use?
