### ISSUE TITLE
想问下左侧的工具栏在哪里打开啊

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#540]
如题。。。我2.6的左侧工具栏不见了。。找半天也没找到（）
![MISSING](https://github.com/xulihang/ImageTrans-docs/assets/49093867/c66a0d26-bcaf-4c2e-91e3-d188a8284ea0)
就这个

**Comment by xulihang** [comment]
2.6.0新增了记忆UI状态的功能，有时候工具栏的宽度会变成0，需要手动拉出来。拖拽最左边的那条就行

**Comment by haofan170** [comment]
> 2.6.0新增了记忆UI状态的功能，有时候工具条的宽度会变成0，需要手动拉出来。拖拽最左边的那条就行

原来如此，还有个小问题就是我用manga-image-translator的时候，2.4基本上一两秒钟一页 但是2.6会要十多秒一页..都是GPU运算（ 大佬有啥头绪吗

**Comment by xulihang** [comment]
项目设置-文字去除里把ocr时生成掩膜关闭，新版的这个操作会增加耗时

**Comment by haofan170** [comment]
> 项目设置-文字去除里把ocr时生成掩膜关闭，新版的这个操作会增加耗时

原来是这样...感谢,那我还是开着吧..一次把两个都跑完了..说起来海外续费的方式价格似乎不太对？ 我直接面包多了.. 我看新币续费要150RMB了合到

**Comment by xulihang** [comment]
FastSpring上涨价了

**Comment by haofan170** [comment]
> FastSpring上涨价了

了解捏 感谢

**Comment by xulihang** [comment]
v2.7.0更新了下，打开项目时，工具栏不会被隐藏了
