### ISSUE TITLE
How to NOT display the source text when target is empty.

### ISSUE THREAD

**Issue by Flowfo** [xulihang/ImageTrans-docs#541]
Hey,
I have very complicated bubbles to mask.
Most of the OCR techniques or text areas detections work well for me: they separate line per line which is PERFECT for this project.
Of course, each text area has its own source text after the detection process.
Then I ONLY use the first line of each bubble to write my target text.
BUT the translated page also displays the other lines with the source text (it's the default behavior when the target is empty, correct?).

My question: **is there a way to not display the source text when target is empty ?**
Thanks.

**Comment by xulihang** [comment]
I have to add a preference setting to disable this behavior.

**Comment by xulihang** [comment]
Added in v2.7.0.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/2875e33f-d1da-453c-b56d-b6929f75faf6)
