### ISSUE TITLE
关于 搜索以及 搜索排序的问题 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#545]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/6737fc62-c7c2-43eb-9ecd-43bc92d2146e

老哥 圣诞节好
あゆむは
あゆむ
这个是漫画女主的名字 第一次出现是在第8 页
因为GPT翻译 把人名翻译的乱七八糟的打算集体修正下
然后当我搜索的时候
我发现一个问题|
就是 搜索的排序 不是按页数来 的 随机排序的
并不是按照 单词出现的页数 由少的页数 往多的页数排序
而是无规则的 如视频那样 第一次搜索 最开始出现的这个词 不排在第一个
而我搜索第二个次 4个字符的时候 甚至排序到了 非常后面 》》
这个搜索排序可以 修改成按照页码 出现的顺序由低到高排序吗
如果能在搜索的结果前边加上出现的页码就更好了 
还有 在搜索的结果里 可不可以修改成 双击 就跳转到当前条目对应的页数 而不需再打开右键菜单然后点击 因为现在右键菜单就一个功能
如果这里没有别的功能 还是双击跳转比较符合直觉操作？ 
![2023-12-25-05 10 41](https://github.com/xulihang/ImageTrans-docs/assets/30548000/fef2fdfc-022e-4523-963b-22e2e345d98b)

**Comment by xulihang** [comment]
目前没有根据文件名排序，我会给它加上。

其它还有些可以优化的地方，比如是否只搜索当前图片、搜索结果里显示来自哪张图片等等。

**Comment by xulihang** [comment]
v2.7.1修正了排序的问题，然后加上了在当前文件搜索和双击跳转

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/45148e2c-7de2-482b-898d-e137005a1315)

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/17d441f1-1107-4465-a82e-a67afc41838a)
双击方便了很多哈哈 后续要是可以显示页数就更棒了
感谢老哥您不辞辛苦 跨年的更新 ！！

**Comment by xulihang** [comment]
结果里显示来自哪张图片加在v2.8.0了

**Comment by lhj5426** [comment]
感谢 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1b8bed21-7268-4dbb-8215-ee5d5097f1ac)
