### ISSUE TITLE
可以给AI翻译们设置一个特殊选项吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#546]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/10fc495b-a537-45ab-ad95-5c1d7d3c0365)
就是在自动更正的后边 增加一个 只针对AI们的一个提示词 GPT  以及 谷歌AI  还有之后可能会有的其他AI 给他们的一个专属提示词设置  也叫字典？
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/49dd0f02-af91-46b1-8066-858388e4976b)
 比如这样  
 这样 更方便帮助AI们来理解和通顺翻译结果
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c9a38b54-fce6-4132-9314-117a8795f9eb)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2f6be0b9-7449-4f4f-8899-2842dd0a2216)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/eb532779-5202-4c86-9c5f-8de6973d7404)
 鸣人 真没绷住 哈哈 
对比下 就读起来 舒服点

**Comment by xulihang** [comment]
这个是Open AI Translator的生词本吗？

可以利用ImageTrans现有的术语管理功能，加个选项，给ChatGPT使用

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/984646fe-990d-47f1-8152-5e45283b376d)

**Comment by lhj5426** [comment]
嗯 好像是吧 不太懂
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5ee75dc6-e927-4fd8-8741-2dd43953f880)
就是 独立的一个输入文本编辑的地方
每次跟在提示词之前 一起喂给AI们  

哈哈 放在术语管理里 真的更贴切
脑子里就想的是  AI自动更正 文本
所以 首先想到的就是  项目 - 自动更正

**Comment by xulihang** [comment]
添加在v2.7.1了。

需要先定义术语，然后在偏好设置里启用使用术语辅助翻译。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/b4ad7ff9-8a23-482c-bef1-45643b592237)

之后调用翻译时，会检测文本中是否包含定义的术语，有的话会把匹配的术语传给AI，让它使用这些术语进行翻译：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/ac1a94f1-39dd-46b9-968c-a3f9dc718868)

Gemini和ChatGPT的插件需要更新，我包含在v2.7.1里了

**Comment by lhj5426** [comment]
首先！元旦快乐 ！
老哥是2024年头一天就更新 感谢 辛苦您了！

**Comment by lhj5426** [comment]
> 添加在v2.7.1了。
> 
> 需要先定义术语，然后在偏好设置里启用使用术语辅助翻译。
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/293587846-b4ad7ff9-8a23-482c-bef1-45643b592237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjc2MTYsIm5iZiI6MTcwNDE2NzMxNiwicGF0aCI6Ii81NDYyMjA1LzI5MzU4Nzg0Ni1iNGFkN2ZmOS04YTIzLTQ4MmMtYmVmMS00NTY0M2I1OTIyMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMDM0ODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q1Zjc5NTQ5MTYxY2UyMTI4ZTM5MDMwYmZjYTdlZGM0ZDAzZjU2MmRiNzM3NzQ1ZDQ2OTRlYjg0ZjdjOTI5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tR4r97N0Zgt0NwrLaFop67PRwzP8XUMWonPku6wLkZU)
> 
> 之后调用翻译时，会检测文本中是否包含定义的术语，有的话会把匹配的术语传给AI，让它使用这些术语进行翻译。下图的例子里我定义了JENNY的翻译为詹尼，这样给出的结果就不再是珍妮了
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/293587851-ac1a94f1-39dd-46b9-968c-a3f9dc718868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjc2MTYsIm5iZiI6MTcwNDE2NzMxNiwicGF0aCI6Ii81NDYyMjA1LzI5MzU4Nzg1MS1hYzFhOTRmMS0zOWRkLTQ2YjktOTY4Yy1hM2Y5ZGM3MTg4NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMDM0ODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY3M2UxODczMjBkNTU5YjgwMGYwNTRlYzIyODUzYzJmYjVkMTM3Mjg1OTIzZjUwNWViZTMzYjVjZTRkYjJiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2m7npJ7DW09GMKl4L9yToh0fg82L03XhF5zKJNLHpNA)
> 
> Gemini和_ChatGPT_的插件需要更新，我包含在v2.7.1里了

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/664a93de-9a83-41f4-bdb9-a65d6971a260)
 刚 续费下载完新版 老哥 您 在属于里没有 设置删除是吗 
 如果写错了 属于要怎么删除现在？只能去编辑ipt文件吗

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/9970135b-40ee-4842-8867-2dc1dd64f981)
啊没事了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ac1b6305-ca13-487b-b048-64a7f3d8c3d3)
 需要精确的点击这里的空白全选 才能显示删除按钮

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/215ed449-c027-4f6e-b438-373b196ef3c9)
好用耶
