### ISSUE TITLE
说起来，现在最好的识别文字段落的方案是什么？

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#547]
manga-image-translator干啥都好，就是没办法准确分段，每次都是一行一行的要手动分== 几百页的图我真的要破防了（x）
我在想可以用MANGA OCR先分段，再用manga-image-translator来OCR可行吗？

**Comment by xulihang** [comment]
识别后左右合并一下不行吗？

mangaOCR不检测文字位置，只识别文字，可以搭配气泡检测或者manga image translator的检测功能

**Comment by haofan170** [comment]
> 识别后左右合并一下不行吗？
> 
> mangaOCR不检测文字位置，只识别文字，可以搭配气泡检测或者manga image translator的检测功能

但是我要翻译的东西没有气泡。。类似轻小说那种== 合并的话我测试下来很多都不会自己合并，还是一样要自己挨个翻一边（）

**Comment by xulihang** [comment]
可以在项目设置的文字检测里把生长宽度设大点。

新版会把里面的区域合并部分独立出来，并添加根据标点符号判断段落进行合并的设置。

**Comment by xulihang** [comment]
关于生长宽度可以看这个视频：【ImageTrans漫画翻译教程——文字区域检测与译文回填-哔哩哔哩】 https://b23.tv/3SRe0xS

**Comment by haofan170** [comment]
> 可以在项目设置的文字检测里把生长宽度设大点。
> 
> 新版会把里面的区域合并部分独立出来，并添加根据标点符号判断段落进行合并的设置。

现在可以设置按照标点符号判断了吗？没有找到哎？

**Comment by xulihang** [comment]
标点符号这个是计划中的功能

**Comment by haofan170** [comment]
> 标点符号这个是计划中的功能

sokka 期待捏~辛苦大佬一直更新了 我自己先研究研究吧

**Comment by haofan170** [comment]
测试了一下，目前来说这种情景最好用的是自动定位文字（自然场景检测） 大概能有一半左右的段落正确，剩下的只能手动画了。不过也还是缩短了不少小率了

**Comment by xulihang** [comment]
自动定位文字（自然场景检测）这个操作前会缩小图像到固定的分辨率，所以用默认设置合并段落会好一点

**Comment by haofan170** [comment]
> 自动定位文字（自然场景检测）这个操作前会缩小图像到固定的分辨率，所以用默认设置合并段落会好一点

原来是这样.. 这次吸取教训了，以后没事不翻译长篇了== 纯纯受罪

**Comment by xulihang** [comment]
上述改动添加在v2.8.0里了：https://github.com/xulihang/ImageTrans-docs/issues/547

**Comment by haofan170** [comment]
> 上述改动添加在v2.8.0里了：#547

好耶！这就更新2.8 刚好快假了

**Comment by xulihang** [comment]
新增的项目设置，应该对段落合并有帮助。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/1c083409-62c5-4492-a438-b00a87fc147e)
