### ISSUE TITLE
Generate translated pictures doesn't respect done pages. 

### ISSUE THREAD

**Issue by Flowfo** [xulihang/ImageTrans-docs#548]
Hello :)

Even if I 'manage my translated images', the BATCH 'Generated translated pictures for all' doesn't record my choice. 
Then it re-generates everything from the start which is time-consuming.
(and makes my laptop crash after 45 pictures, but that's probably another problem :D)
Other features of the batch menu work well.
A precision : I use Lamainpaint to remove the text.
Best regards.
Ro

**Comment by xulihang** [comment]
In translated images manager, check "Do not display translated in the editing interface".

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/8d1d1100-8383-4fb7-bdd4-243453da24f4)

Then you can skip generated pictures.

**Comment by xulihang** [comment]
Two things to improve:

1. Make the generation of translated images, mask images and text-removed images skip the translated ones.
2. Add a conditional selection in the translated images manager to select images which have generated results.

**Comment by xulihang** [comment]
> Two things to improve:
> 
> 1. Make the generation of translated images, mask images and text-removed images skip the translated ones.
> 2. Add a conditional selection in the translated images manager to select images which have generated results.

The above is implemented in v2.8.3.
