### ISSUE TITLE
在没有原文的情况下要怎么导入原文呢

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#557]
这个问题很奇葩是吧
老哥请坐 看我讲来
是这样的
我是在做硬字幕的提取和翻译
然后我像用用 樱花模型 可手里唯一能够使用樱花自动批量的只有IT
然后把 我 用 专门提取硬字幕的工具已经提前把文本提取出来了
图1
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/572096fa-d3c8-42fa-b046-b3e6d8e1ccd5)
然后2我把SRT变成了纯文本
图2
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/06e91eef-a8f1-406b-ba75-580036ca1545)
然后图片总数是 549张图
图3
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2e575ffc-cdc6-4664-b29d-ceff5c26c85e)
之后我打开 IT 导入图片 建立全图文本框
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4dd15896-6d93-4dbc-a851-9ccb7a039164)

然后我以为只要把文本做成 这个样子
图4
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/cc0f671f-9e2b-4e4c-a2c3-ada93b5f1320)
 就可以导入到IT的原文里
 结果我错了没报错也提示导入 但是什么都没有导入
 我又用表格
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/09e24b00-020c-47ab-b23f-170218830eee)
把TXT改成了这种格式导入
问题来了原文里没有文本
译文里被填充上了 
图5
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/49db86bd-d27c-44a6-a448-c964e1041ec2)

然后我还不死心我像是不是不能用TXT换了DOC
图6
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/3f73235d-b37a-4d7f-863c-4fc0c26a99c0)
还是一样 译文被填充 原文空白

我实在不会了
能不能请老哥您教教我
怎么对原文进行 无中生有式填充  谢谢了

**Comment by xulihang** [comment]
目前上述方法只能导回译文。

导入原文的话，有导出所有文字区域图片和导入文字区域图片的OCR结果这两个操作。文字需要存放在image-index.txt里，其中index表示文字区域的序号。

**Comment by xulihang** [comment]
我可以加一个选项，从docx文件导回时也导回原文

**Comment by xulihang** [comment]
我想起来BasicCAT也有ChatGPT插件的，直接支持SRT格式

**Comment by lhj5426** [comment]
> 相关的issue：#124*

哈哈这个方法不适用与我这个情况
我是把所有所有500张图片的文本OCR到了一个TXT里
而
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ee168c41-0ea1-42ad-8b78-d242df448db3)

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d858a8c5-4787-4169-b00a-9e1971cea605)

这个功能是导入一个一个图片
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5f7543a1-7edc-4d75-8c52-0088ab7ecd39)
一个图片对应一个TXT这种的
正好是 完全不同的两种用法 

如果 可以让TXT 或者DOC 也支持导入原文就 更好了

**Comment by xulihang** [comment]
导回翻译时同时导回原文的选项加在v2.8.2里了

**Comment by lhj5426** [comment]
> 导回翻译时同时导回原文的选项加在v2.8.2里了

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/01c0d876-4fad-402e-bf0c-2da46583d190)
今天做视频 刚好用到 非常感谢！！！！

检测有点严格必须 双侧都有才会导入 原文和译文
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ed1b8189-22b1-4867-a73d-f82fdfd48a56)
也不麻烦 用 EmEditor 以制表符分割然后 复制粘贴到第二格就行了 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/65e384ad-f333-4706-9339-f31691d8aba9)
总之很感谢 够用了
