### ISSUE TITLE
Can you add Papago paid version Translate?

### ISSUE THREAD

**Issue by bravehon** [xulihang/ImageTrans-docs#56]
when you add papago is free version
I want add like google paid version [it's machine running translate]

this website is paid version
https://console.ncloud.com/mc/solution/naverService/application

I will send naver Id and password

**Comment by xulihang** [comment]
Okay. I will make a new papago plugin for this.

**Comment by bravehon** [comment]
> Okay. I will make a new papago plugin for this.

thank you!

**Comment by xulihang** [comment]
![image](https://user-images.githubusercontent.com/5462205/120099355-8f9d9f80-c16d-11eb-819d-9784b664e502.png)

It is done.

The naver cloud platform's version is basically the same. I just need to modify the URL and auth header names,

[papagoMT.zip](https://github.com/xulihang/ImageTrans-docs/files/6565979/papagoMT.zip)

**Comment by xulihang** [comment]
The plugin's source code: https://github.com/xulihang/BasicCAT/tree/master/plugins/papagonvcloudMT

**Comment by bravehon** [comment]
> 플러그인의 소스 코드: https://github.com/xulihang/BasicCAT/tree/master/plugins/papagonvcloudMT

thank you !!
