### ISSUE TITLE
manga-ocr和manga-image-translator不能同时运行吗

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#560]
rtm有的时候manga-image-translator出bug会需要manga-ocr，但是manga-ocr要是和前者一起打开的话选择manga-ocr的识别项目会不识别，关闭前者就可以了

**Comment by haofan170** [comment]
发现了 两者都监控8080. 把server_manga_ocr改成8081就好了

**Comment by yahoozhu** [comment]
> 发现了 两者都监控8080. 把server_manga_ocr改成8081就好了

你就改那一个值就完事吗？我也碰到这问题，改什么端口都不行，只能8080    

![2024-04-05_22-51-53](https://github.com/xulihang/ImageTrans-docs/assets/24186777/69923581-a300-4ec5-93bd-65e20554d0ba)

server_manga_ocr改8081或者其他的都一样，点识别的话请求都发到在server那边去了


![2024-04-05_22-54-37](https://github.com/xulihang/ImageTrans-docs/assets/24186777/33353b84-bd3c-447f-9711-a01064c90ff6)

反之也一样

请问还需要改什么吗？ @xulihang

**Comment by xulihang** [comment]
看这里：https://github.com/xulihang/ImageTrans_plugins#notes-using-local-servers

**Comment by yahoozhu** [comment]
好了 感谢
