### ISSUE TITLE
排序的小问题？

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#561]
分镜以后排序正常的情况下：
![px](https://github.com/xulihang/ImageTrans-docs/assets/49093867/b964b968-c030-4781-b4c1-55d30e51c4ee)
在合并的时候应该是2-3-4，但是实际上却变成了
![px2](https://github.com/xulihang/ImageTrans-docs/assets/49093867/8c30d04a-4efc-4da6-9fc3-d776a1ae8afe)
3-2-4？这是为什么啊 版本2.81

**Comment by xulihang** [comment]
图片发我试一下

**Comment by haofan170** [comment]
> 图片发我试一下

郵件已發送

**Comment by xulihang** [comment]
我测试没什么问题，你哪里可能操作不对吧

**Comment by haofan170** [comment]
> 我测试没什么问题，你哪里可能操作不对吧

奇怪 我晚上再看看

**Comment by haofan170** [comment]
> 我测试没什么问题，你哪里可能操作不对吧

好奇怪，我这边用老的2.6就可以了，最新的就会有顺序错误

**Comment by xulihang** [comment]
把项目文件，具体操作步骤发过来。

**Comment by haofan170** [comment]
> 把项目文件，具体操作步骤发过来。

额好的...就是第八页在同样的顺序下选择那三个框，并且点击合并所选的结果就不同了，我录个视频吧

**Comment by haofan170** [comment]
> 把项目文件，具体操作步骤发过来。

已发送视频和文件

**Comment by xulihang** [comment]
2.8.1会对选中的区域重新排序。你项目设置里的排序依据设置的纵坐标，它按纵坐标排了

**Comment by haofan170** [comment]
> 2.8.1会对选中的区域重新排序。你项目设置里的排序依据设置的纵坐标，它按纵坐标排了

原来是这样 我说呢… 感谢捏

**Comment by xulihang** [comment]
v2.8.4添加了一个单独的合并文字的排序设置，具体见这个issue：https://github.com/xulihang/ImageTrans-docs/issues/576

**Comment by haofan170** [comment]
好的感谢
