### ISSUE TITLE
遇到一个bug

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#562]
就是 我是先用ps一张一张把图片 手动去字的
然后 0335.jpg
0335.jpg-original.jpg
放到 目录的
刚才在润色的时候 突然 查看翻译的时候 就变成了这样 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/6f204f2b-69cb-4cbc-b587-0610a52414b7)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/344906c8-9eb4-484f-b6d1-b76c366f9338)

这种情况 而且不是一张两张是整个项目都是这个情况
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/bef2c732-0950-45a9-b47e-96d278ed1098)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ea075879-f69e-4c34-8851-1970f107a5d5)

而且关闭项目重开 关闭 软件重开 这个 问题 依然存在
https://github.com/xulihang/ImageTrans-docs/assets/30548000/33314f36-3e79-4b24-8b70-06e3f668fc3c
录制了个视频 请老哥看下
顺便 随便提供了 2组 项目里的有字 和无字图 
[新建文件夹.zip](https://github.com/xulihang/ImageTrans-docs/files/14022029/default.zip)
还有出问题的项目文件
[项目.zip](https://github.com/xulihang/ImageTrans-docs/files/14022034/default.zip)
还请麻烦老哥看一下 是什么问题

https://github.com/xulihang/ImageTrans-docs/assets/30548000/b5e70bb6-2ed8-4419-9258-facd9bd6f44f

建框译文的整个框区域都被 文字的描边颜色包裹上了

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/6fbe18e7-977f-4ca1-a189-4d218f72e2dc)
如果导出的话
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/00056317-7067-4579-9c23-4cb45b2ac101)
直接就给上色加 框了

**Comment by xulihang** [comment]
应该是勾选了非精确模式，用背景颜色填充了

**Comment by lhj5426** [comment]
> 应该是取消勾选了精确抹除文字模式，用背景颜色填充了

操 原来是我蠢货了  抱歉打扰了 
对不起我是个蠢货 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7e44c251-3508-43a5-a38c-f6def4330129)
原来没注意这个 被勾去了 
我还纳闷呢怎么突然就这样了呢。。。 太二货了  抱歉
