### ISSUE TITLE
是否考虑加入框选区域对齐的功能

### ISSUE THREAD

**Issue by yougnut** [xulihang/ImageTrans-docs#564]
非常喜欢大佬开发的软件，但感觉能增加些更方便编辑的功能
比如我有在用的另一个软件，能选择居中或以左右对齐框选的区域
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/e2f7a754-4b1f-45d8-b095-6d409b094a01)
不知道Imagetrans有无此功能，或是有没有其他达成类似功能的作法，谢谢。

**Comment by xulihang** [comment]
通过左边工具栏按钮可以切换到多选模式，里面有调整对齐的功能

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/0e4a220e-2d50-4a4c-ad87-b023db988b6e)

**Comment by yougnut** [comment]
原来在那边，谢谢大佬!
