### ISSUE TITLE
粗体字无法正确显示

### ISSUE THREAD

**Issue by yougnut** [xulihang/ImageTrans-docs#565]
您好，在设置裡预设使用粗体，但选取查看翻译时並不会显示粗体字，只有调整字体大小或手动选择粗体才会显示出来，不知道有没有什么解决办法，谢谢
1. 预设字体有勾选粗体
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/902bdf79-b085-41c6-9c48-1258fb07da15)
2. 这是直接勾选查看翻译显示的字体，可以看到虽然工具列粗体是勾选状态但译文粗体没有套用
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/41dcc32d-0337-43a1-b48a-ddf37a0db21f)
3. 调整字体大小后才显示粗体
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/ce2c34ee-1a1b-40ca-a5b8-ebb5f8ac89f1)

**Comment by xulihang** [comment]
这里有个bug。目前可以通过在项目设置里启用富文本来解决
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/0fd3721e-23e3-4f1a-a24a-5681c074b37d)

**Comment by yougnut** [comment]
好的，谢谢您

**Comment by xulihang** [comment]
这个问题在v2.8.3里修复了
