### ISSUE TITLE
Is it posible to use my own model, like an yolo8 model when batch bubble detection.

### ISSUE THREAD

**Issue by WavaDev** [xulihang/ImageTrans-docs#566]
I have an Yolo8 model that is trained on 1300 images, and it is trained on text bubbles: 
![image](https://github.com/xulihang/ImageTrans-docs/assets/127393002/9f73f171-d2fc-4110-b85d-1ce28a6a6f1a)
and is it posible to use it in the software? I want to auto get all text boxes.

**Comment by xulihang** [comment]
1. Try to convert the model to an OpenCV-compatible format, like Darknet's .weights and ONNX.
2. Start a local server to make it work as a scene text detector like this one:  https://github.com/xulihang/ImageTrans_SceneText_Detection

**Comment by lhj5426** [comment]
> I have an Yolo8 model that is trained on 1300 images, and it is trained on text bubbles: ![image](https://private-user-images.githubusercontent.com/127393002/302130903-9f73f171-d2fc-4110-b85d-1ce28a6a6f1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTUyOTgsIm5iZiI6MTcwNzExNDk5OCwicGF0aCI6Ii8xMjczOTMwMDIvMzAyMTMwOTAzLTlmNzNmMTcxLWQyZmMtNDExMC1iODVkLTFjZTI4YTZhNmYxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNjM2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzYzNmVkM2Q4ZWY2MTA0YzQ1MzBhOTRiNzg1ODMzNDA1MTBkODJlZjlkZjU5YzNjZGY3ZDg2NDU3YTM5NzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VzCF8g6mbECMRb-atnysg__cF3WQl1jxXS3ONJ0e2HM) and is it posible to use it in the software? I want to auto get all text boxes.

Can you share it if it is useful?
To help the author and other users enhance the software usage experience.

**Comment by xulihang** [comment]
ImageTrans v2.10.0 added support for YOLOv8.

Check out this blog to learn more: https://www.basiccat.org/how-to-train-yolov8-object-detection-model/

**Comment by xulihang** [comment]
I've uploaded some models here: https://github.com/xulihang/balloon-dataset/
