### ISSUE TITLE
Preview Fonts in the Font Combo Box in the Toolbar

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#567]
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/7c7f4e72-4f3d-43df-8e77-c3ffe3ee137a)

We can preview the fonts in the font list to quickly get an idea of what a font looks like.

For performance concerns, it is disabled by default. We can enable it in the preferences.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/93a79646-299a-465f-b793-2f6fb4b95b51)

**Comment by xulihang** [comment]
Added in v2.8.3.

**Comment by lhj5426** [comment]
感谢更新 新年快乐
