### ISSUE TITLE
i have a problem dectect bubble so much 

### ISSUE THREAD

**Issue by NinjaScoutZ** [xulihang/ImageTrans-docs#568]
Whenever I use batch's main three options, it always has this problem no matter the option. What should I do?
![Screenshot 2024-02-08 155235](https://github.com/xulihang/BasicCAT/assets/132326611/0be31da8-a385-4ffd-b80b-b4f5ac171a6c)
![Screenshot 2024-02-08 155223](https://github.com/xulihang/BasicCAT/assets/132326611/28cf0d78-5ad3-466c-8714-9e508aa9d1a6)
![Screenshot 2024-02-08 155144](https://github.com/xulihang/BasicCAT/assets/132326611/7cb4d7be-88ba-44ab-b9f3-9f86703a3c6b)

![Screenshot 2024-02-08 155247](https://github.com/xulihang/BasicCAT/assets/132326611/cdd790cd-e10b-4679-ab99-9618fea2c208)

**Comment by xulihang** [comment]
You are using the heuristic method. The image's font size is reatively large. You have to increase the minimum growth height and width in the text area detection project settings until the text areas are merged correctly.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/ec1b417f-77da-493c-8fd7-05e9aea27cd7)
