### ISSUE TITLE
How was the itp file in the Gallery was created 

### ISSUE THREAD

**Issue by quanengineering** [xulihang/ImageTrans-docs#569]
Hi,

I saw the Gallery listing these .itp file, e.g. https://www.basiccat.org/viewer/?project=/gallery/projects/scrooge/scrooge.itp.

How was it exported in ImageTrans? I don't see the docs mentioned about it.

**Comment by xulihang** [comment]
Just put the project file with the images and use the viewer to open the project.

You can export the project as a web page to get webp images.

**Comment by quanengineering** [comment]
Sorry for bothering you, but how can I self-host an online viewer like you? I mean the https://www.basiccat.org/viewer?

**Comment by xulihang** [comment]
You can fork this project and upload your project files: https://github.com/xulihang/ImageTrans-Online
