### ISSUE TITLE
Photoshop script will not produce correct font sizes

### ISSUE THREAD

**Issue by jps1226** [xulihang/ImageTrans-docs#57]
When I use the "Generate Editable PSD files" option and run the relevant script, everything works except the font is set to zero.

I played around with the script and it knows what size to set it to, but after correctly changing the font, it just sets it to zero.

When I edited the script to make the text itself be what the font size is supposed to be, everything matched up, so it seems the font size just won't stick for some reason.

**Comment by xulihang** [comment]
What version of Photoshop are you using? Check out this one: https://github.com/xulihang/ImageTrans-docs/issues/22#issuecomment-808717368

**Comment by jps1226** [comment]
I think I'm using 2020, but the one you linked to me did the trick! This was a workaround for not getting Anime Ace to work in the software itself but now I think I prefer having the translations in PS, so disregard my other comment on the other issue.
