### ISSUE TITLE
google drive error

### ISSUE THREAD

**Issue by ztench** [xulihang/ImageTrans-docs#572]
I receive this error.
![Captura de pantalla 2024-02-14 140757](https://github.com/xulihang/ImageTrans-docs/assets/77814259/e8daf3e8-7c27-4c3d-b742-63ea88bcda59)

**Comment by EdShedisson** [comment]
Same

**Comment by xulihang** [comment]
The OAuth token I requested for the server was expired.

You can use your own google drive account following this blog:

https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#enable-ocr-via-google-drive

**Comment by EdShedisson** [comment]
"You need to create a Google Cloud Platform account first. You can get a $300 credits for the first year. With this amount, you can make OCR requests for 212,000 times." 

Google Cloud statement: 
"$300 credit for free
Put Google Cloud to work with $300 in credit to spend over the next 90 days."

**Comment by EdShedisson** [comment]
> The OAuth token I requested for the server was expired.
> 
> You can use your own google drive account following this blog:
> 
> https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#enable-ocr-via-google-drive

Maybe it's a problem on my side. But nor google/google_drive not workin, nor baidu.

**Comment by xulihang** [comment]
> > The OAuth token I requested for the server was expired.
> > You can use your own google drive account following this blog:
> > https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#enable-ocr-via-google-drive
> 
> Maybe it's a problem on my side. But nor google/google_drive not workin, nor baidu.

If you only need to process Japanese manga, then they are not needed as there are offline alternatives.

**Comment by EdShedisson** [comment]
> > > The OAuth token I requested for the server was expired.
> > > You can use your own google drive account following this blog:
> > > https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#enable-ocr-via-google-drive
> > 
> > 
> > Maybe it's a problem on my side. But nor google/google_drive not workin, nor baidu.
> 
> If you only need to process Japanese manga, then they are not needed as there are offline alternatives.

Mainly in English and French.

**Comment by xulihang** [comment]
> Mainly in English and French.

The OCRs I listed in the docs can work with English and French: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#ocr

Google and Baidu do work better and can recognize more fonts.

**Comment by EdShedisson** [comment]
> Google and Baidu do work better and can recognize more fonts.
That's what I'm talking about. A have connected both Google and G Drive and they aren't working just blank space instead of result. And from Baidu I'm getting "null". Yesterday everything was ok with both G Drive and Baidu.

**Comment by xulihang** [comment]
The accurate version of baidu has a daily usage limit. To continue to use it, I have to provide a paid online service, which is not on my plan.

**Comment by ztench** [comment]
I was able to solve the problem with the guide.

**Comment by xulihang** [comment]
Great.
