### ISSUE TITLE
文字显示的一个问题》？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#575]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/eb9e405d-4cf6-4458-a0f3-3ffa916ae889

如视频 所示 每一个的 气泡文字  都会有被压缩的情况
只有点击之后 才会舒展开？

**Comment by xulihang** [comment]
启用了居中对齐，然后文字区域过窄时会有这个问题

**Comment by xulihang** [comment]
调整大小时，不要让文字超出边框
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/abf425e7-69ce-4aad-a993-b6463c5c714c)

**Comment by lhj5426** [comment]
> 启用了居中对齐，然后文字区域过窄时会有这个问题

噢  之前好像没遇到过

嗯呢 正在做润色 默认超出边界的是 初次GPT机翻的文本 

手动润色的时候会调整 文字的边界的

**Comment by lhj5426** [comment]
改成了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/674c8d80-38f7-4f62-ae11-db61df7c4787)
左对齐之后 问题没了
