### ISSUE TITLE
The option to load custom masks and the order of bubbles

### ISSUE THREAD

**Issue by EdShedisson** [xulihang/ImageTrans-docs#577]
I'd like to use masks to detect bubbles/text from Panel Cleaner. It detects them faster and better.
Also, is it possible to set the order of scanning/distribution of textboxes from right to left from top to bottom? For me, they are ocr'ing randomly.

**Comment by xulihang** [comment]
The order for OCR does not matter. You can always sort them after OCR.

You can sort the text areas by several criteria. You can set it in the project settings and sort the text areas for all the images in custom workflow.

**Comment by xulihang** [comment]
Panel Cleaner uses comic text detector which is included in manga-image-translator.

You can use the plugin for manga-image-translator to generate the mask images: https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaTranslatorOCR

You can put mask images generated by other tools for ImageTrans to use according to the the following rule:

```
image.jpg // image file
image.jpg-mask.png // mask image file
```

As for generating text areas from mask images, it is not supported yet.

**Comment by EdShedisson** [comment]
> Panel Cleaner uses comic text detector which is included in manga-image-translator.
> 
> You can use the plugin for manga-image-translator to detect the text and generate the mask images: https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaTranslatorOCR
> 
> You can put mask images generated by other tools for ImageTrans to use according to the the following rule:
> 
> ```
> image.jpg // image file
> image.jpg-mask.png // mask image file
> ```
> 
> As for generating text areas from mask images, it is not supported yet.

Okay. Thanks, I'll give it a try.

**Comment by xulihang** [comment]
I've added an operation to generate text areas from masks in v2.8.5.

You can use it through the menu item or custom workflow.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/c4be54d8-d082-40d7-a7f7-bf8e5f2e1263)
