### ISSUE TITLE
Full package not launching [Windows]

### ISSUE THREAD

**Issue by jamwilljar** [xulihang/ImageTrans-docs#578]
downloaded full not getting anything when I run imagetrans.exe,.jar or .bat should I ask for money back???

**Comment by xulihang** [comment]
Which Windows version are you using? 

There is a similar issue here: https://github.com/xulihang/ImageTrans-docs/issues/558

You can use PowerShell to run `ImageTrans.bat` to see the error message.

**Comment by xulihang** [comment]
Which Windows version are you using? 

There is a similar issue here: https://github.com/xulihang/ImageTrans-docs/issues/558

You can use PowerShell to run `ImageTrans.bat` to see the error message.

**Comment by jamwilljar** [comment]
windows 10 pro
version 22H2
OS Build 19045.4046

**Comment by xulihang** [comment]
Is it an x64 version?

Use Powershell to start it to check out the error message.

**Comment by jamwilljar** [comment]
also basicCAT will only accept *.bcp files, no *.jpg or *.pdf files???

**Comment by xulihang** [comment]
BasicCAT is for translating documents like docx and txt files. You have to open a .bcp project and then import files.

**Comment by jamwilljar** [comment]
So how is it supposed to handle manga files? And what is the differance between Imagetrans and BasicCat, and the email I received takes me to a download page that will not let me download. I press the download button, but nothing downloads.

**Comment by xulihang** [comment]
You should be able to receive two emails. You csn download ImageTrans using the onedrive link.

**Comment by jamwilljar** [comment]
It's not downloading.

**Comment by jamwilljar** [comment]
can you send me a working link???
 https://1drv.ms/u/s!Akc_xu6OIXVY53znoo16PqCaJGsj?e=ZsQ41Q

**Comment by jamwilljar** [comment]
![ImageTran](https://github.com/xulihang/ImageTrans-docs/assets/64225278/c166f8d3-6f01-4e7f-9335-5096ec915f76)

**Comment by xulihang** [comment]
Onedrive works for me.

If you cannot download it, you can follow the crossplatform approach.

1. Download jre: https://github.com/bell-sw/Liberica/releases/download/11.0.19%2B7/bellsoft-jre11.0.19+7-windows-amd64-full.zip Unzip it and rename the folder as jre in ImageTrans's folder.
2. Download OpenCV and unzip it to ImageTrans's folder: https://github.com/xulihang/ImageTrans-docs/releases/download/opencv/windows_x64.opencv_java455.zip

**Comment by jamwilljar** [comment]
O.K. thank you for your time and consideration. Barring I don't run into any roadblocks :)
'

**Comment by jamwilljar** [comment]
!!!now what the HECK! is an *.itp file Please!!!!

**Comment by xulihang** [comment]
You need to create a project first and then import images. You can follow the documentation: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html
