### ISSUE TITLE
字体多选情况下 无法批量修改

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#583]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/1939b390-5a05-4959-bb90-bec649764952

老哥 如视频所示
2个 艺术字 气泡 被同时选上
然后 修改字体 只有其一 被修改
 并不能多选后一起修改
 还请 在这里优化一下
 让字体 支持【多选同时修改】
 感谢

**Comment by xulihang** [comment]
字体工具栏右边的“应用到所有”有勾上吗

**Comment by lhj5426** [comment]
> 字体工具栏右边的“应用到所有”有勾上吗

好把 我的锅
因为 我这里 放的是拟声词快速输入窗口 给档上了 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/633bfcc5-ef11-4e46-9c5b-84ce2418bb39)

就没看到过

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5b5965d1-733e-476a-b8c8-c9ea7426a825)

刚才 看到老哥的回复之后  我移开了拟声词输入窗口 看到了  抱歉啊 给您添麻烦了
