### ISSUE TITLE
【对齐】功能的快捷键失效 功能错乱

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#584]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/98bf5542-16d0-4985-9b6f-14e2f9bed8ac

如视频所示 左对齐 无效 
上对齐 实际上是左对齐
垂直居中 下对齐都无效

https://github.com/xulihang/ImageTrans-docs/assets/30548000/1226ce08-32e4-45b1-9c0b-4aa384df4f65

这6 项目对齐 在快捷键里 要么是乱的要么就根本不好使 请老哥 测试 并修正一下
使用的软件版本 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4f04057c-7163-41ec-b827-4534d1e4c9e5)

**Comment by xulihang** [comment]
我试了下没有问题，你鼠标通过菜单或者工具栏调用有问题吗

**Comment by lhj5426** [comment]
我是直接按键盘上的组合键 不是使用按键映射成一个按钮

**Comment by lhj5426** [comment]
视频2 通过 UI界面的菜单使用是没问题的 就快捷键使用有问题 要么不好使要么 功能和描述不对应

**Comment by xulihang** [comment]
通过菜单可以查看快捷键有没有绑定

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/008da30f-8d7b-4967-8ae7-c27a090748bc)

https://github.com/xulihang/ImageTrans-docs/assets/30548000/a9e21c38-8f24-45a6-b229-985560dc37c4

您看 快捷键都设置 了 以ctrl+shift+A 上对齐为例子
您看 我先在视频里 用 菜单执行 上对齐 文字进行正确的上对齐
但是当我使用 上对齐的快捷键时 并没有执行上对齐 文字块 都挤在了一起 应该是 左对齐？

**Comment by xulihang** [comment]
我绑定了同样的快捷键，没有问题。

是不是和你其它软件有冲突了

**Comment by lhj5426** [comment]
![111111111111111%pn_2024年03月07日22点34分20秒468](https://github.com/xulihang/ImageTrans-docs/assets/30548000/746e7cbb-7e63-4947-9375-c7420b5bc126)
排查了一圈 我也不知道问题出在那 因为我在做漫画的时候 一任务栏的辅助软件
但是老哥说您那边没问题
那肯定就是我这边的问题但我实在是不知道问题出在哪里了

在最后实在没办法 我试着把 咱们 的软件启用了 管理员权限 没问题了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ec596f29-042e-41a0-a021-0f5fa2e3fc67)
奇葩  无法理解
