### ISSUE TITLE
i cant detect ballons

### ISSUE THREAD

**Issue by NinjaScoutZ** [xulihang/ImageTrans-docs#585]
![第5话_1](https://github.com/xulihang/ImageTrans-docs/assets/132326611/d178d556-610b-4048-9d32-de03dc9f91e9)
![第5话_2](https://github.com/xulihang/ImageTrans-docs/assets/132326611/1dd53c06-e5ce-4bb5-a950-98148daf959e)

**Comment by xulihang** [comment]
The online balloon detection model has a daily usage limit.

Use heuristic text detection for this.

**Comment by NinjaScoutZ** [comment]
so no offline model can do it?

**Comment by xulihang** [comment]
The current models are not very suitable for Chinese comics.

I plan to release a tool to make it easy to train a custom model.

**Comment by xulihang** [comment]
Hi,

I've written a guide about training your own model using ImageTrans v2.10.0: https://www.basiccat.org/how-to-train-yolov8-object-detection-model/

We can build a balloon detection model to detect balloons in Chinese manhua following the above guide.

**Comment by xulihang** [comment]
You can try to use models here with ImageTrans 2.10.1: https://github.com/xulihang/balloon-dataset/

**Comment by NinjaScoutZ** [comment]
where is Release Notes for imagetrans? i wanna know about news update

ในวันที่ ส. 6 เม.ย. 2024 เวลา 07:33 Lihang Xu ***@***.***>
เขียนว่า:

**Comment by xulihang** [comment]
https://www.basiccat.org/imagetrans/release-notes/
