### ISSUE TITLE
“R”富文本编辑 A字体 可以记住上次的选择吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#587]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/06be2606-a189-4803-aa31-f70792631d6a

老 哥 如视频所示 右边的R 富文本这里
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c5fdc857-cc60-46ab-a86d-ce07c6064c64)
可以记住上次的选择吗
如果直接切换气泡 R上次字体选择是不会变的
但是当要复制原文的时候就必须先关闭R
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7620cb93-3e67-4ce1-a84a-5a75edd5bbc7)
然后 再次打开的时候 上次选择的字体 没有自动记住 还得重新选择
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/49371a0d-3e21-4272-94b6-6953a248b329)
 所以能麻烦您优化一下让R 富文本 自动记住上次的选择么 这样 直接点设 就可以快速设置 不需要每次再选择了
 还有同样的 左上角 A 字体这里 也是
 如视频那样 每次更换一个气泡都要重新 选择
 就是本页 一次性选设置完了
 但是换到下一页 还是要选择
 最近在做的一本漫画 用了大量的特效字体  还有 对话加粗
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2239e509-c85f-4436-ac9d-ea298d6a8ee5)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1bb76433-2f21-411e-b7ae-08b661eab4cd)

 所以最近大量的在使用 R 来设置粗字体 和用A字体 来设置 艺术字体
 就在想如果这2个功能 都是使用的固定一种字体 如果能够自动记住上次选择的话 每次点下设置 就完事 了
 可以节省不少的重新选择的时间 
 还请老哥可以对这2个地方做下优化
 嗯 还有就是 R 里设置的代码 如果 出现换行 就会还原成代码的问题
 还有一点 就是 恳请并希望您可以把 R富文本的 竖排 字体大小 能给安排上

**Comment by xulihang** [comment]
优先级不高，我有空了加上

**Comment by lhj5426** [comment]
嗯，先谢谢了…

**Comment by xulihang** [comment]
保留富文本编辑器里的字体选择状态和竖排引擎的富文本支持调节字体大小加在v2.9.0里了。

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/7c353a4f-3883-40cf-8475-85e1f7559bf0)
感谢老哥

**Comment by victor318** [comment]
又学一招，谢谢

**Comment by xulihang** [comment]
换行导致富文本标签失效的问题在v2.12.4里修复了

**Comment by lhj5426** [comment]
嗯 感谢
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a2e03fef-57f8-49a9-ba6c-a62d5a3fd2df)
现在包裹上富文本 可以随意换行了
