### ISSUE TITLE
An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting"

### ISSUE THREAD

**Issue by NinjaScoutZ** [xulihang/ImageTrans-docs#589]
Previously, it worked normally, but suddenly an error occurred: the translation did not appear.

![image](https://github.com/xulihang/ImageTrans-docs/assets/132326611/b56630f8-a658-43bf-a1c6-d989f8bec454)

**Comment by xulihang** [comment]
It works for me. Not sure about the reason.
