### ISSUE TITLE
Start ocr batch on current picture (suggestion)

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#59]
I find it with some projects where I have a lot of images that it might be more easy in some cases, if you can start the ocr batch on the current picture instead of doing it from the first picture

**Comment by xulihang** [comment]
Right. The batch operation should have an option to select which images need to process.

**Comment by xulihang** [comment]
A translated images manager is added in v1.4.0. If the image is marked as translated, then the batch operation will skip this image.

![image](https://user-images.githubusercontent.com/5462205/121832234-32245980-ccfc-11eb-9bd6-e6c5074099ff.png)

**Comment by HeLan8** [comment]
Thanks, it works fine

**Comment by xulihang** [comment]
There is a bug related to the new floating text editor. You may redownload it if you need this function.

**Comment by herrachamp** [comment]
from where can I download the latest version?

**Comment by xulihang** [comment]
The files on onedrive (links in the emails) are always the latest version.
