### ISSUE TITLE
manga-image-translator可以加上cuda的操作能加一个中文版的傻瓜式教程吗，弄了一晚上还是不行

### ISSUE THREAD

**Issue by JILUDEDIPINGXIAN** [xulihang/ImageTrans-docs#595]
如标题所说能不能出一个全面一点的从头开始的中文版教程，最好是能带图片的

**Comment by JILUDEDIPINGXIAN** [comment]
可能是我太笨了，看了已有的安装教程还是做成了菜逼样，有安装成功的大佬总结一下吗

**Comment by JILUDEDIPINGXIAN** [comment]
> 如标题所说能不能出一个全面一点的中文版教程，最好是能带图片的

**Comment by lhj5426** [comment]
安装cuda cudnn

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117



安装完后

https://pytorch.org/get-started/locally/
O:\dupan\N卡cuda
set cuda

环境变量
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\libnvvp

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp
import torch
torch.cuda.is_available()

安装manga-image-translatorrun
https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaTranslatorOCR
 不是已经简化到 下载 压缩包 解压就行了么

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8ee2c499-0560-4ef4-85fc-b67497ed1bed)
 这里的 全下载 并解压复制到一起 比如
 我的路径是 J:\Downloads\75yuan\manga-image-translator 所有文件复制到一起
 然后 跟着B站视频 安装 CUDA CUDNN 之后 
 
 在创建一个无后缀的文件 use_cuda
 
 执行 run.bat 就完事了

**Comment by lhj5426** [comment]
后边用 lama-cleaner 来修复图片 也需要用到cuda 肯定是要装一下的

**Comment by JILUDEDIPINGXIAN** [comment]
搞定了，谢谢大佬指导
