### ISSUE TITLE
Errors and things not working

### ISSUE THREAD

**Issue by FluoxSSRI** [xulihang/ImageTrans-docs#596]
I've been trying to use Imagetrans for several days now and I've been struggling with getting it working. I've followed the instructions on imagetrans.readthedocs and respectetive github pages on plugins with no luck getting imagetrans to work reliably. Maybe I missed something or I'm just not doing something properly I'm not sure. I have tesseract, mangaocr, mangaimagetransator, opuscat installed and been trying to get it to machine translate.

I've been trying to get it machine translating by right clicking and clicking one-click translation, selecting opus and heuristic then clicking machine translation, I don't know if I'm supposed to select an ocr before but I tried changing it to different ones before clicking machine translation. I also tired uninstalling everything and following the instructions again to install still with no luck. I'm no programmer and without an in depth guide on how to use imagetrans I'm really struggling understanding, again maybe I'm just stupid and ignorant or misunderstanding something. Any help would be appreciated and if I can get into contact with someone who as experince using imagetrans that would be great.

This is the error I get when clicking detect text areas (heuristic) and also the same as the error when tring to machine translate.
I'v also gotten a different error which I'm not sure what I did to trigger it

error: java.lang.RuntimeException: Object should first be initialized (Map).
StackTrace: java.lang.RuntimeException: Object should first be initialized (Map).
	at anywheresoftware.b4a.AbsObjectWrapper.getObject(AbsObjectWrapper.java:32)
	at anywheresoftware.b4a.objects.collections.Map.Get(Map.java:67)
	at org.xulihang.imagetrans.main._hasoverlappedbox(main.java:10417)
	at org.xulihang.imagetrans.main._loadtextareas(main.java:12576)
	at org.xulihang.imagetrans.main$ResumableSub_LocalizeTextHeuristically.resume(main.java:13675)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Some other occurances are 
When selecting ocr engines, selecting a text area, clicking ocr, nothing happens or it continues to the OCRing windows and stays like that for a long time or the OCRing windows will open but for a second then closes doing nothing
Things not translating properly for example some tranlated outputs I've gotten are "WeeTHEWebK<S" and "HURLNAPRV#SMSH"

**Comment by xulihang** [comment]
Hi, could you upload a sample image?

**Comment by FluoxSSRI** [comment]
I'm not too sure what you mean by sample image but this is me trying different things with tesseract, mangaocr, and machine traslating

https://github.com/xulihang/ImageTrans-docs/assets/163112693/63592c8c-3fa2-4138-a920-85e311250cc6

https://github.com/xulihang/ImageTrans-docs/assets/163112693/165a0f53-0f48-43f0-87da-f4c98f1c2cfa

https://github.com/xulihang/ImageTrans-docs/assets/163112693/140350f0-05c1-45b7-826e-85addac6ed46

https://github.com/xulihang/ImageTrans-docs/assets/163112693/d336b632-c8f3-4ef3-9c13-430520b6db68

https://github.com/xulihang/ImageTrans-docs/assets/163112693/919e07d3-c46e-4976-a12e-937b76e9bd62

**Comment by FluoxSSRI** [comment]
I restarted imagetrans and opened a new project I can't reproduced some of the errors I've encountered but it still continues to not work as expected

**Comment by FluoxSSRI** [comment]
This is me following along the video and the comment, it also gave the same outcome when I tried "detect text areas (heurisitic)" and "detect balloons"

https://github.com/xulihang/ImageTrans-docs/assets/163112693/8ddfd293-2b42-40fe-a47f-b1c0f4745021

**Comment by xulihang** [comment]
Just putting the files will not make it work.

1. Put the three model files directly under ImageTrans's folder and enable offline balloon detection in the preferences.
2. Start mangaOCR by executing `run.bat` and keep its window open.

**Comment by FluoxSSRI** [comment]
Oh I see, it did help although the tranlation doesn't seem correct

https://github.com/xulihang/ImageTrans-docs/assets/163112693/cfa1f820-a275-4934-9d14-281acc2ee70e

![image](https://github.com/xulihang/ImageTrans-docs/assets/163112693/c0df9b1e-c1cc-46f6-b758-97e5bfef4f19)

**Comment by xulihang** [comment]
This is machine translation. Its quality may not be very good. You can use different machine translation engines and choose the best result.

**Comment by FluoxSSRI** [comment]
I see, that would make sense. Does selecting a different ocr engine also effect the results? or just the machine translation engine?

**Comment by xulihang** [comment]
OCR engine only recognizes the source text. If there is misrecognition, it will also impact the translation.

**Comment by FluoxSSRI** [comment]
ah ok that makes more sense now, I probably misunderstood some information. There are some errors that occur I just don't know how to reproduce them. I'll post them if they do occur
