### ISSUE TITLE
When I chose to use Autocorret, this kind of bug occurred. But when I copy these languages It came back out in normal language. Not like in the picture CN-TH

### ISSUE THREAD

**Issue by NinjaScoutZ** [xulihang/ImageTrans-docs#597]
![image](https://github.com/xulihang/ImageTrans-docs/assets/132326611/d98a31cb-6a70-4c5d-92d2-df243a0e41b1)
![image](https://github.com/xulihang/ImageTrans-docs/assets/132326611/fb654367-5a8e-4126-b150-041e72109643)

**Comment by xulihang** [comment]
You enabled the autocorrect rule for OCR which will replace the source text. I think it is not correct.

**Comment by NinjaScoutZ** [comment]
so what should i do because if i disable that everything's will not useful

**Comment by xulihang** [comment]
You can just uncheck "Enable for OCR" for that rule.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/1ab203ef-c4e7-42be-8743-229c91c006ca)

**Comment by NinjaScoutZ** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/132326611/95f10c9c-70b8-4087-8547-93199158ca20)
actaully It's not just Autocorret, but if sometimes I let Gemini translate and Gemini leaves out the untranslatable words and sends them in the original. The program will show as The square word boxes are the same.

**Comment by xulihang** [comment]
This is Gemini's problem. I can't do much about this.

It seems that "Turn off your clothes" is regarded as SEXUALLY EXPLICIT.

**Comment by NinjaScoutZ** [comment]
so we can't disable safety filter?

**Comment by xulihang** [comment]
It seems that we can do some settings: https://github.com/google/generative-ai-python/issues/126
