### ISSUE TITLE
版本2.9.1  批量识别图片文字和 滑动建框问题

### ISSUE THREAD

**Issue by fly100f** [xulihang/ImageTrans-docs#598]
1.识别建框问题

https://github.com/xulihang/ImageTrans-docs/assets/155800529/b10bfabb-597c-49dc-b374-8354e08be174

  每次建框选择区域，出现会把原来已识别区域的最后一个置空。

2.批量识别图片文字

https://github.com/xulihang/ImageTrans-docs/assets/155800529/bcee4ce5-67ea-4569-86ea-51f5abbcb2e1

 第一页识别正常，第二页开始返回的是前一页的识别框位置和内容。

 大家使用这个版本时有碰到这个问题吗。

**Comment by xulihang** [comment]
是2.9.1引入的Bug，待会修一下

**Comment by xulihang** [comment]
2.9.2修复了，麻烦重新下载一下

**Comment by fly100f** [comment]
> 2.9.2修复了，麻烦重新下载一下

好的.

**Comment by fly100f** [comment]
测试了几次，目前问题
