### ISSUE TITLE
软件支持几台电脑安装，语言支持俄语吗

### ISSUE THREAD

**Issue by victor318** [xulihang/ImageTrans-docs#600]
我不是用作漫画翻译，想做电商图片翻译的，家里一台电脑，一台笔记本，办公室一台电脑，一共3台电脑，共用一个账号就行吗？

**Comment by xulihang** [comment]
可以的。一个账号可以在三台设备上用。可以翻译到俄语。

**Comment by victor318** [comment]
接口什么的，需要自己配置吗？还是说完整版，是已经配置完成的

**Comment by xulihang** [comment]
有默认配置好的，也有需要自己配置的。具体看文档：https://imagetrans.readthedocs.io/zh-cn/latest/gettingstarted.html#ocr

还有博客：https://www.basiccat.org/zh/how-to-use-youdao-in-imagetrans/

**Comment by victor318** [comment]
因为是用在电商上的，所以翻译的内容准确性还是有点要求的，配置的接口翻译的准确性如何。

**Comment by xulihang** [comment]
我不懂俄语，只能说目前最先进的机器翻译都已经集成了。软件本身也支持人工翻译，你觉得准确度不够可以请人翻译。

**Comment by victor318** [comment]
OK，购买了的

**Comment by victor318** [comment]
OK，购买，从0开始，怎么操作，因为看到好多文件

**Comment by xulihang** [comment]
先自己看文档和视频吧。这个issue我关了，有问题麻烦重新发一个
