### ISSUE TITLE
购买了，激活时候，提示未购买

### ISSUE THREAD

**Issue by victor318** [xulihang/ImageTrans-docs#601]
在面包多里购买了，用完整版的，激活时，提示未购买，
![Snipaste_2024-03-29_19-47-01](https://github.com/xulihang/ImageTrans-docs/assets/24997911/85a83f81-b186-4ee0-9534-56a8a8a008ca)
![Snipaste_2024-03-29_19-47-09](https://github.com/xulihang/ImageTrans-docs/assets/24997911/8ccf8ec7-7354-4436-a565-95f07de9bfc7)
![Snipaste_2024-03-29_19-48-32](https://github.com/xulihang/ImageTrans-docs/assets/24997911/19268d34-519f-4f21-a8d9-6fb544554b1d)

**Comment by xulihang** [comment]
服务器选ne
