### ISSUE TITLE
Hello, I've finished my 6 months of updating.

### ISSUE THREAD

**Issue by JhojanVC** [xulihang/ImageTrans-docs#602]
I wanted to ask once I finish the 6 months, will I be able to continue using the program and its tools? For example, "Google Drive OCR", since it is the best OCR that the program has and it is the one I use the most.

Will I still be able to use "Google Drive OCR" after the 6-month update ends?

**Comment by xulihang** [comment]
Google Drive OCR is not related to updating.

It does not work because I haven't refreshed it token.

Wait for me to refresh the token or set up your own following this guide: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#enable-ocr-via-google-drive

**Comment by JhojanVC** [comment]
entiendo, pense que ya no dejarian usarlo una vez acabara los 6 meses, gracias por el tiempo

**Comment by xulihang** [comment]
I've refreshed the token. The default Google Drive OCR can work for another 7 days.
