### ISSUE TITLE
请问能否实现选中文本时在图片气泡框同步高亮的效果

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#603]
如图这样，右边选中文本的时候，在图片气泡内的对应位置或者对应那一行也行，实现一个高亮标识的效果，有时候OCR识别错误，搞机翻本来就不认识原文，如果是一大段文字，只能一个个字符去找不同，就挺费事的

![2024-03-30_20-00-09](https://github.com/xulihang/ImageTrans-docs/assets/24186777/33c965b8-7ac9-466e-a94f-98b422faba0e)

**Comment by xulihang** [comment]
OCR结果没有保存单个字符的位置信息。想高亮只能通过文字引擎重新排版以估算位置。

目前导出为PDF是可以高亮位置的，效果见这篇博客：https://www.basiccat.org/how-to-create-searchable-pdf-from-scanned-documents/，但对竖排的支持不佳。

总之实现起来比较麻烦，也可能做不到非常精确。

**Comment by yahoozhu** [comment]
> OCR结果没有保存单个字符的位置信息。想高亮只能通过文字引擎重新排版以估算位置。
> 
> 目前导出为PDF是可以高亮位置的，效果见这篇博客：https://www.basiccat.org/zh/how-to-create-searchable-pdf-from-scanned-documents/，但对竖排的支持不佳。
> 
> 总之实现起来比较麻烦，也可能做不到非常精确。

明白了，大概就猜到会很难搞，就还是来问一下
