### ISSUE TITLE
目标检测数据 管理工具打不开？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#604]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c1410889-d6ad-4250-8850-ea877d7ff196)
如图 打开没有反映呢 是我的操作不对吗

通过菜单->工具打开对象检测注释数据管理器。

将数据导出到一个目录。数据将按照以下结构以 YOLO 格式存储

但是点击之后什么都没有发生？

https://github.com/xulihang/ImageTrans-docs/assets/30548000/e4ee24d1-7815-4669-b5e7-2afcecf454fd

**Comment by xulihang** [comment]
菜单名改过后我忘记改对应的代码了。

从onedrive上重新下过吧

**Comment by lhj5426** [comment]
> 菜单名改过后我忘记改对应的代码了。
> 
> 从_onedrive_上重新下过吧

嗯嗯 知道了 谢谢

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8a203f23-cf54-4a39-9b72-a49ff768c7c5)
谢谢老哥  这次可以正常导出了
