### ISSUE TITLE
有没有办法在一句话里面，加大部分字号或者加粗呢？

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#605]
rt,比如blood或者是加大一句话里面的部分文字？

**Comment by xulihang** [comment]
富文本功能，可以点击译文编辑区右边的R按钮进行设置

**Comment by xulihang** [comment]
竖排引擎目前不支持仿粗体和仿斜体，其它的字号、斜体、粗体和颜色都是可以设的。粗体和斜体需要字体本身支持

**Comment by haofan170** [comment]
> 富文本功能，可以点击译文编辑区右边的R按钮进行设置

sokka！ 我这就去看看 感谢大佬

**Comment by haofan170** [comment]
> 竖排引擎目前不支持仿粗体和仿斜体，其它的字号、斜体、粗体和颜色都是可以设的。粗体和斜体需要字体本身支持

大佬现在不支持指定字体字号吗？eg：[size=30]文字[/size] 似乎不行哎

**Comment by xulihang** [comment]
看文档：https://imagetrans.readthedocs.io/zh-cn/latest/gettingstarted.html#id26

是fontsize，不是size

**Comment by haofan170** [comment]
> 看文档：https://imagetrans.readthedocs.io/zh-cn/latest/gettingstarted.html#id26
> 
> 是fontsize，不是size

好的感谢~
