### ISSUE TITLE
文字识别后，背景处理干净，怎么弄

### ISSUE THREAD

**Issue by victor318** [xulihang/ImageTrans-docs#606]
![Snipaste_2024-04-01_10-46-18](https://github.com/xulihang/ImageTrans-docs/assets/24997911/d1b29577-3ca0-4614-bae0-a14acf8b7e79)
![Snipaste_2024-04-01_10-44-16](https://github.com/xulihang/ImageTrans-docs/assets/24997911/dd954655-b1eb-4948-a93f-74d15fecbc9d)

文字识别出来后，翻译后，再看，背景处理不干净，怎么整

**Comment by xulihang** [comment]
1. 文字没抹除：文字框需要完全包围文字
2. 有残留：在项目设置的文字去除设置里把掩膜膨胀大小调大一点

参考这篇博客：https://www.basiccat.org/zh/details-about-image-text-removal-using-imagetrans/

**Comment by victor318** [comment]
![Snipaste_2024-04-01_10-49-43](https://github.com/xulihang/ImageTrans-docs/assets/24997911/9fe1e8ce-bb56-4a11-87a6-372ba97ee36f)
还有这个问题

**Comment by xulihang** [comment]
需要选中一个文本框后再勾选

**Comment by victor318** [comment]
![Snipaste_2024-04-01_10-51-23](https://github.com/xulihang/ImageTrans-docs/assets/24997911/b59c4a73-f118-48c3-b6c6-a264c2f6efb7)

这样包裹，也不行？

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/e995a529-c66a-438e-ae7a-9d86146ee432)
 有时候 需要手动 这样操作
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5dd8b236-985a-4c78-9587-348bc22ba644)

不能100%全自动

**Comment by xulihang** [comment]
黑色和橙色混在一起会影响掩膜的生成。
然后背景和文字颜色接近，也会有影响。

这个时候只有手动编辑掩膜了

**Comment by victor318** [comment]
api接口怎么填写？就输入key就行了吗？

**Comment by lhj5426** [comment]
也就百度的麻烦点 3行 输入这2个 其他的都是1个坑  对应一个的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8b335cc5-be5b-45ec-8a37-03e352cc8e53)

**Comment by victor318** [comment]
![Snipaste_2024-04-01_11-16-47](https://github.com/xulihang/ImageTrans-docs/assets/24997911/41be520a-d37a-4658-8cac-04615b538e62)
gpt的api，怎么输入，我就填写了key

**Comment by lhj5426** [comment]
> ![Snipaste_2024-04-01_11-16-47](https://private-user-images.githubusercontent.com/24997911/318328019-41be520a-d37a-4658-8cac-04615b538e62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDIwOTYsIm5iZiI6MTcxMTk0MTc5NiwicGF0aCI6Ii8yNDk5NzkxMS8zMTgzMjgwMTktNDFiZTUyMGEtZDM3YS00NjU4LThjYWMtMDQ2MTViNTM4ZTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMjMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNjNlMzdmOTM0YmY1ZDNhYTE1OGZkY2JkYTdkZjE5MTQ3YjhkYTViNWU0MDE0MTMwNzI2ZDY0YTY0NGJjNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_3f2wvFsruOMsNU7BBLdYfA_k1a7OyLeh4G_KEEgVU) _gpt_的api，怎么输入，我就填写了key

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/3690e652-e60e-4dd7-940f-a17c63754549)
改成 第三方地址

**Comment by lhj5426** [comment]
比如我用的 https://api.xeduapi.com HOST这里就改成 这个 按照你买的API代理商页面写

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/987e57fe-b2c5-48ba-b31a-a912621b6e21)
有的代理 商支持以GPT api 的形式调用claude 3 的话 也可以写 claude 3的模型 这个看你买的代理商

**Comment by victor318** [comment]
好的，谢谢
