### ISSUE TITLE
排序的序号字体显示怪怪的，可以设置成在气泡框外显示吗？

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#609]
像这样，想让图片单张整个显示在窗口，从而快速校对序号是否正确，但是数字会显示不全，对话多的话看起来挺费劲的，这个序号似乎是以画布界面做参照的固定大小，能把它挪到气泡外面显示吗？或者改下字体大小

![2024-04-04_20-09-31](https://github.com/xulihang/ImageTrans-docs/assets/24186777/9b3331a1-069a-4a7a-88c5-924d6a98bbc0)

**Comment by xulihang** [comment]
这里其实只是一个显示图片的控件，我只能把内容画在它的范围里面。把显示比例调大一点应该能显示完整。

显示到外面的话需要做一些调整。

**Comment by xulihang** [comment]
显示不下的话，把字体调小。这个在高度不够的时候是会做的，但宽度不够的情况目前没有做

**Comment by xulihang** [comment]
是文本框高度不够时程序会自动缩小序号

https://github.com/xulihang/ImageTrans-docs/assets/5462205/ad78d8a3-e5af-4756-9059-d19d224d40bf

**Comment by yahoozhu** [comment]
> 是文本框高度不够时程序会自动缩小序号
> 
>  ice_video_20240405-091709.mp4

明白了，不过这样似乎比我多花几秒看序号更花时间

**Comment by xulihang** [comment]
高度宽度不够自动调整，应该不会多花时间。不过还是改变下序号显示方式比较好

**Comment by xulihang** [comment]
宽度不够时紧凑显示序号的改动加在v2.10.2里了
