### ISSUE TITLE
adding the missing target language & pasting the translated text in doc file

### ISSUE THREAD

**Issue by herrachamp** [xulihang/ImageTrans-docs#61]
Please look into these:
1. In Select Language Pair how to add the language Hindi which is not available now in the option.
2. When I am pasting the translated text in doc file, all text is pasted in one cell only. How to paste them all in their respective columns. I am using LibreOffice Writer program.

![target language](https://user-images.githubusercontent.com/85825674/122050935-a72d8700-ce01-11eb-9145-2ea2e52d3504.png)
![translation doc](https://user-images.githubusercontent.com/85825674/122050938-a7c61d80-ce01-11eb-90c7-02ac6626863d.png)

**Comment by HeLan8** [comment]
Do you translate the text seperately or do you translate the doc document? If you translate the doc document and copy the text from the translated doc decument, then there shouldn't be any problem with pasting the text in their respective columns

**Comment by herrachamp** [comment]
> Do you translate the text seperately or do you translate the doc document? If you translate the doc document and copy the text from the translated doc decument, then there shouldn't be any problem with pasting the text in their respective columns

I copy the text from left side of table in doc file and translate it on translate.google.com 
from there I get the translated text and want to paste it on right side of the table in doc file

**Comment by HeLan8** [comment]
Try translating your doc file here
https://www.onlinedoctranslator.com/en/translationform
then copy the translated text and paste it to the original document. I tried it out and it worked

**Comment by herrachamp** [comment]
> Try translating your doc file here
> https://www.onlinedoctranslator.com/en/translationform
> then copy the translated text and paste it next to the original document. I tried it out and it worked

Thank you very much HeLan8 it worked as you said .
Can you tell me how to adjust the font size of the translated text and is it possible to adjust the position of the desired text.

**Comment by HeLan8** [comment]
https://youtu.be/S_6FF-5zTns?t=185
This should work

**Comment by xulihang** [comment]
I will add a full language codes list including Hindi in the next version. 

> how to adjust the font size of the translated text and is it possible to adjust the position of the desired text.

You should start a new issue for further questions. But this is a basic operation question which you can find answers in the documetation and video tutorials.

**Comment by herrachamp** [comment]
thank you HeLan8 and Xulihang for your support

**Comment by xulihang** [comment]
Hindi is added in v1.4.1.

**Comment by herrachamp** [comment]
Thanks a lot
