### ISSUE TITLE
可以让分镜框也能进行双击更改序号吗

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#611]
![2024-04-06_09-29-08](https://github.com/xulihang/ImageTrans-docs/assets/24186777/e3dbc9f9-c33d-4f1a-8ec1-23799f30a874)

识别错了只能删掉重划或者拖动给他排序，还有中间漏了一个分镜后面乱序的，在中间漏的地方加一个分镜改序号就行了，但新增分镜序号只会递增不能改，那后面的就还是要手动调

**Comment by xulihang** [comment]
因为分镜数量比较少，我就没加这个。可以在右边的分镜列表调整顺序

**Comment by xulihang** [comment]
加在v2.10.2里了
