### ISSUE TITLE
能不能增加个放大输入框文字的功能

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#613]
就是 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1be94833-6436-43a9-aa16-37282f84520b)
文字 编辑输入框的这个部分 能不能设置成文字大小可以调节显示的

https://github.com/xulihang/ImageTrans-docs/assets/30548000/8be37a41-87da-43a1-9edb-c248a13a725c

做漫画字幕和做视频字幕都是个长时间盯着看的 操作
但是做视频字幕的时候 可以这样调节编辑框字体的大小
漫画 时间长了说实话文字太小 眼睛也有点干涩
所以 就 能不能请 老哥 在这个 文字编辑框的部分优化成可以调节文字大小显示的呢
这样大字体看着舒服 也不那么累眼睛 

还有这个 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/07650b4e-6f89-4891-a9d2-fc0f4cdc023a)
  独立输入框也 一起 改成能够调整文字显示大小的 就更棒了 感谢
   眼睛有点干酸 哈哈

**Comment by lhj5426** [comment]
这样文字大点看着会很舒服 不那么累
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/cdd59df1-c0d4-4154-8f41-a8aab1734d7f)

**Comment by xulihang** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/8c34d241-8431-474f-a677-05b206be7db1)

这个可以在项目设置里设置。

两个输入的地方的字体都可以改。

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5e025eed-974f-4cc5-8815-fb2b80fd09c0)
