### ISSUE TITLE
项目 界面设置 字体不生效

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#614]
这个 衔接 上一个
https://github.com/xulihang/ImageTrans-docs/issues/613

https://github.com/xulihang/ImageTrans-docs/assets/30548000/78293ae4-2f53-42fc-9fbc-3a98d553e033

昨天老哥 您告诉我了如何修改更大的字体
嗯 非常感谢 大字体长时间使用 眼睛的压力小了很多
不过 大是大了 但是文字有点太细了 
所以我就试着更换了 粗体字 然后就 发现 这个界面里 粗体字 不会生效 甚至很多字体
在设置里都是默认的字体样式 只有极少数的 是可以在界面里显示字体的
嗯 还得麻烦老哥您 能不能 让这个编辑框支持下粗体字 或者粗字体

如果可以话能不能 请您适配下这款
[新兰圆-B.zip](https://github.com/xulihang/ImageTrans-docs/files/14911001/-B.zip)

[新兰圆-M.zip](https://github.com/xulihang/ImageTrans-docs/files/14911010/-M.zip)

字体到界面显示
这个字体粗大 还圆润 看着很舒服 长时间阅读也不会很累 我个人是这么感觉的 
我自从用您的漫画软件制作漫画字幕以来 默认的字体也是这款 因为我觉得真的很舒服 
谢谢了

**Comment by xulihang** [comment]
这个中文字体的设置会有bug，我暂时搞不定


https://github.com/xulihang/ImageTrans-docs/assets/5462205/dfbf3d3d-3a2e-4ff4-869c-3e9732d16d08

**Comment by lhj5426** [comment]
> 这个_中文_字体的设置会有bug，我暂时搞不定
> 
>  ice_video_20240409-120005._mp4_

哈哈 好吧 抱歉给老哥您 出难题了
那能不能您找一款 稍微粗一点 看着得劲一点的 然后 所有系统都兼容的字体 来设置呢

**Comment by xulihang** [comment]
可以设置一个黑体，会粗一点

**Comment by lhj5426** [comment]
嗯 也可以 只要粗点 不那么累 就行 嗯 还请麻烦老哥您在后续的更新中给 这个安排上 谢谢您了

**Comment by xulihang** [comment]
这个修复不了
