### ISSUE TITLE
gemini申请了key，直接填软件api里面，无法使用

### ISSUE THREAD

**Issue by victor318** [xulihang/ImageTrans-docs#615]
gemini申请了ke有，直接填软件api里面，无法使用，是还需设置什么？

**Comment by xulihang** [comment]
1. 不能翻译成人内容
2. IP有一定要求

可以用ImageTrans.bat打开软件，看具体的错误信息。

**Comment by victor318** [comment]
![Snipaste_2024-04-09_17-14-53](https://github.com/xulihang/ImageTrans-docs/assets/24997911/71f86e1b-9890-493e-84b9-2c3ed7b5502d)
已经翻墙了，翻译内容不显示。
![Snipaste_2024-04-09_17-16-06](https://github.com/xulihang/ImageTrans-docs/assets/24997911/7b159388-e9ac-47ab-bdb9-3f0fe2c00fdf)
提示是位置不支持，我电脑开启翻墙了。

**Comment by xulihang** [comment]
需要美国IP

**Comment by victor318** [comment]
我有买美国ip，怎么去设置

**Comment by victor318** [comment]
![Snipaste_2024-04-09_18-10-53](https://github.com/xulihang/ImageTrans-docs/assets/24997911/a9f47184-9c8b-4f1f-a248-a119b119fcd3)
这里改美国ip，还是在fanqiang软件里使用美国ip即可
![Snipaste_2024-04-09_18-11-32](https://github.com/xulihang/ImageTrans-docs/assets/24997911/e5c23b9c-376e-4088-bb0a-44636d3d07a4)

**Comment by xulihang** [comment]
翻墙软件里

**Comment by yahoozhu** [comment]
![1](https://github.com/xulihang/ImageTrans-docs/assets/24186777/8b78117b-cddf-427a-822a-c78bd053b5d6)
![2](https://github.com/xulihang/ImageTrans-docs/assets/24186777/bd3bcc8e-edd5-431f-bfe0-4db6a5c4c4a7)
![3](https://github.com/xulihang/ImageTrans-docs/assets/24186777/bdebd3a9-39c6-42c8-8a80-e6f81cfe1a58)
 
请问这啥问题，我用了3个平台的的API给了3个不同的结果……用测试网站测的话都需要填入指定的模型名字才可以测试成功，像第一个只能是gemini-pro，第二个要求是api-gemini-1.5-pro，软件里没有设置的地方不能跟chatgpt一样   @xulihang 


> 翻墙软件里
