### ISSUE TITLE
不知能否将合并文字框加入右键快捷选项

### ISSUE THREAD

**Issue by yougnut** [xulihang/ImageTrans-docs#616]
大佬你好，主要是提供个感觉能增加效率的想法
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/a276263d-64a4-48a3-94ef-e5ec410c30e9)
不知有没有考虑将合并文字框加入右键快捷选项或是加入快捷键方便触发，否则要不断切换页面稍嫌麻烦，感谢大佬
![image](https://github.com/xulihang/ImageTrans-docs/assets/67062125/f64156e3-686d-4c15-be77-6eb43662ca79)

**Comment by yougnut** [comment]
感谢大佬！

**Comment by xulihang** [comment]
右键菜单和主菜单的合并项目已经加在2.10.2里了
