### ISSUE TITLE
气泡框突然变成这样了，好像是“建立覆盖图层”的功能失效了

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#617]
![2024-04-11_12-42-41](https://github.com/xulihang/ImageTrans-docs/assets/24186777/5bb26435-51f2-4bbc-973d-051c05ea5245)

这个本已经做完了，搞了好几个小时了，只剩封面大字没翻了，我刚调整完字体也没报错啥的，但是字体框都有白色背景，我手动勾选取消了下建立覆盖图层的，然后一翻页报了个错，我直接点了确定，后面的就全部变成这样了，重启软件也不行

**Comment by xulihang** [comment]
勾选下左下方的精确抹除文字

**Comment by yahoozhu** [comment]
> 勾选下左下方的精确抹除文字

人傻了  这么简单，我准备把文字全抹掉都搞了十几张了
