### ISSUE TITLE
Having Problem in Translating 100 pages comics

### ISSUE THREAD

**Issue by CoolGenius-123** [xulihang/ImageTrans-docs#618]
I have recently came across these tool ImageTrans and able to use it for translation using this methods.

1. Heuristic Text Detection 
2. Usint WinRT or MangaTranslator 
3. Using ChatGPT 

But Heuristic is not able to properly detect all text properly specially text which are colored and also I am seeing WinRT is performing better than MangaTranslator, but failed to OCR colored text could someone help me .

I need to learn How to use this 

1. Ballon detection or any other detection 
2. How to use mangaOCR or MangaTranslator 
 
Any guide for starting this two things

**Comment by xulihang** [comment]
Please post a sample image.
