### ISSUE TITLE
可以一次导回任意数量的翻译文档吗？多的填充到辅助翻译里面本地调用

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#619]
现在都是全文导出AI翻译，这几天试了各种模型，虽然贵的clauda-opus和chatgpt4整体效果是好一点，但是单句拆分了看，便宜的gpt3.5和hiku、gemini这几个有的句子读起来又通顺些，整篇下来不少这种地方

![2024-04-13_17-49-52](https://github.com/xulihang/ImageTrans-docs/assets/24186777/4a3672af-7f41-47ff-83ca-14728ec4c4f3)

所以比如我现在翻译出3份译文出来，能不能我就直接在后面加上就行  比如txt格式，每行就是：原文tab译文一tab译文二tab译文三……
然后导回的时候的，第一个译文填入翻译框，其他译文就本地调用的方式置顶显示在辅助翻译里，AI全文翻译的效果再拉也还是比单句翻译强的

**Comment by xulihang** [comment]
用辅助翻译，列出多个机器翻译时，直接调用API去翻译不也一样吗？

这个需求可以通过自己编写机器翻译与翻译记忆插件去做。不过，目前一个插件只能返回一条结果，这个尚待完善。

**Comment by lhj5426** [comment]
所以我都是全跑一遍然后 拿一个当底子导入
然后一边看一边润色 一边修改 在第二个屏幕上开多个全网翻译的文档 外加ai对话
一点点润 其实和放在辅助翻译框了其实意思差不多 不过我都是手敲
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/32ae4b91-68ce-4fb5-8b40-5b688ea55181)

**Comment by yahoozhu** [comment]
> 所以我都是全跑一遍然后 拿一个当底子导入 然后一边看一边润色 一边修改 在第二个屏幕上开多个全网翻译的文档 外加ai对话 一点点润 其实和放在辅助翻译框了其实意思差不多 不过我都是手敲 ![image](https://private-user-images.githubusercontent.com/30548000/322274465-6df827c7-f49e-40a5-9274-44acb74abbde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTE3OTAsIm5iZiI6MTcxMzExMTQ5MCwicGF0aCI6Ii8zMDU0ODAwMC8zMjIyNzQ0NjUtNmRmODI3YzctZjQ5ZS00MGE1LTkyNzQtNDRhY2I3NGFiYmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE2MTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzOTAyMzE5MGRhMzE1NjY2YjM1M2IzZjhlZWI3MTMxNWU2N2FiMmM1OWY1MTQ0NWU5YjM5NzM3ODlmNmYxYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DIvse6A3MjHeljrWMSX4MHx76qQBlfGB_qRbIa0VSu0)
> 
> ![image](https://private-user-images.githubusercontent.com/30548000/322274417-32ae4b91-68ce-4fb5-8b40-5b688ea55181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTE3OTAsIm5iZiI6MTcxMzExMTQ5MCwicGF0aCI6Ii8zMDU0ODAwMC8zMjIyNzQ0MTctMzJhZTRiOTEtNjhjZS00ZmI1LThiNDAtNWI2ODhlYTU1MTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE2MTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZDhkODAzOGVmN2Y4MzMxNzNlNzc5Mzg3YTNhNGI0MWU2ZDhlMDQ0NmVhMWRmNDJiODgzN2Y5ZWFlMDg0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BWfu2nrYvELmK3Mc7sQaxL7G33-AiaNzZSLETMHbdzU)

要是能导入辅助翻译就可以快速填入了，用你这个软件双屏操作感觉会很爽，就是成本有点高了……

**Comment by lhj5426** [comment]
> > 所以我都是全跑一遍然后 拿一个当底子导入 然后一边看一边_润色_ 一边修改 在第二个屏幕上开多个全网翻译的文档 外加ai对话 一点点润 其实和放在辅助翻译框了其实意思差不多 不过我都是手敲 ![image](https://private-user-images.githubusercontent.com/30548000/322274465-6df827c7-f49e-40a5-9274-44acb74abbde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTE3OTAsIm5iZiI6MTcxMzExMTQ5MCwicGF0aCI6Ii8zMDU0ODAwMC8zMjIyNzQ0NjUtNmRmODI3YzctZjQ5ZS00MGE1LTkyNzQtNDRhY2I3NGFiYmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE2MTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzOTAyMzE5MGRhMzE1NjY2YjM1M2IzZjhlZWI3MTMxNWU2N2FiMmM1OWY1MTQ0NWU5YjM5NzM3ODlmNmYxYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DIvse6A3MjHeljrWMSX4MHx76qQBlfGB_qRbIa0VSu0)
> > ![image](https://private-user-images.githubusercontent.com/30548000/322274417-32ae4b91-68ce-4fb5-8b40-5b688ea55181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTE3OTAsIm5iZiI6MTcxMzExMTQ5MCwicGF0aCI6Ii8zMDU0ODAwMC8zMjIyNzQ0MTctMzJhZTRiOTEtNjhjZS00ZmI1LThiNDAtNWI2ODhlYTU1MTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE2MTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZDhkODAzOGVmN2Y4MzMxNzNlNzc5Mzg3YTNhNGI0MWU2ZDhlMDQ0NmVhMWRmNDJiODgzN2Y5ZWFlMDg0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BWfu2nrYvELmK3Mc7sQaxL7G33-AiaNzZSLETMHbdzU)
> 
> 要是能导入辅助翻译就可以快速填入了，用你这个软件双屏操作感觉会很爽，就是成本有点高了……

其实你要真正用上你会发现 你要经常在 辅助翻译和 文本框2个选项卡来回切换
特别是很多时候软件自动识别字体颜色错误的时候 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/f67422ed-2354-4596-ade3-059a9fb61241)
会产生严重的 使用割裂感 看完翻译还得切换过来修改字体颜色 反正我觉得挺割裂的
不过我本身就是4屏 对我来说 这个不算成本

不过把话拉回来

要是 能按照 这个 扩展 这个思路 去装填其他的文本 
http://firefoxer.ru/informenter+.htm?ch

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/147ce846-12b9-4615-b1fd-438abf904503)
在 翻译这里增加一个小箭头
点开箭头就可以看到 相同气泡下的其他已状态的翻译内容

**Comment by yahoozhu** [comment]
额 好吧，我只翻黑白漫很少有需要换字体和颜色的操作，拟声词换字体都是最后一次搞，所以几乎都只看辅助翻译框

**Comment by lhj5426** [comment]
> 额 好吧，我只翻黑白漫很少有需要换字体和颜色的操作，拟声词换字体都是最后一次搞，所以几乎都只看辅助翻译框

软件还有很大的开发空间 慢慢来慢慢用 一步一步走反正已经可以逐步实现漫画自由看了 我在E站也发了快100本了

**Comment by xulihang** [comment]
2.11.0添加了一个插件显示多个候选机器翻译的功能。

下面是从txt读取机器翻译的插件：

[tsvMT.zip](https://github.com/xulihang/ImageTrans-docs/files/15050862/tsvMT.zip)

把翻译按以下格式存储：

```
source	普通话	上海话
I like you.	我喜欢你。	我欢喜侬。
```

然后在偏好设置里指定该文件路径。

之后可以在辅助翻译里查看：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/30da794c-9fc7-43e5-84e3-d16f566168fb)

**Comment by xulihang** [comment]
v5.18.0添加了外部翻译记忆的功能。

准备一个如下的xlsx文件：

<img width="882" height="158" alt="Image" src="https://github.com/user-attachments/assets/3cec30c8-e4c1-4d61-a8ba-278b2806cbcd" />

然后在项目设置里导入：

<img width="927" height="540" alt="Image" src="https://github.com/user-attachments/assets/4dfffec1-4090-4db5-8895-0993c1812c3b" />

之后就可以调用了：

<img width="1580" height="731" alt="Image" src="https://github.com/user-attachments/assets/61875d66-4c44-4460-a966-4ce2e3bb3a83" />

**Comment by xulihang** [comment]
新的翻译记忆功能性能比较好，支持上万条翻译的快速显示。

**Comment by lhj5426** [comment]
> v5.18.0添加了外部翻译记忆的功能。
> 
> 准备一个如下的xlsx文件：
> 
> <img alt="Image" width="882" height="158" src="https://private-user-images.githubusercontent.com/5462205/580393213-3cec30c8-e4c1-4d61-a8ba-278b2806cbcd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY1NzU4MDUsIm5iZiI6MTc3NjU3NTUwNSwicGF0aCI6Ii81NDYyMjA1LzU4MDM5MzIxMy0zY2VjMzBjOC1lNGMxLTRkNjEtYThiYS0yNzhiMjgwNmNiY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MTlUMDUxMTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODdlYWY2MTUwYWY5NGVmNWMyYmEzYjFkYWQ3NDQwMGFiNDExYmI5MDQ5MmNlYWRhM2I5OTc1ZDA0NDEyNzljNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.7f3EYslVQWKacQdXQ4PYId90IibdCit-W0CZcKgdb8c">
> 然后在项目设置里导入：
> 
> <img alt="Image" width="927" height="540" src="https://private-user-images.githubusercontent.com/5462205/580393243-4dfffec1-4090-4db5-8895-0993c1812c3b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY1NzU4MDUsIm5iZiI6MTc3NjU3NTUwNSwicGF0aCI6Ii81NDYyMjA1LzU4MDM5MzI0My00ZGZmZmVjMS00MDkwLTRkYjUtODg5NS0wOTkzYzE4MTJjM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MTlUMDUxMTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY2NzIxOGQxMTliMTZlMTc5NTY3ZTY2MWVlMWI5ZmY3ZjlkZWIyMjNiNDI4NjhjYWM3MThjNmY1Y2MwNTA5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.jnfO5e7JnarLnnRiNqS5EYpL4ZlAPCFqHGH8bYE5Ovs">
> 之后就可以调用了：
> 
> <img alt="Image" width="1580" height="731" src="https://private-user-images.githubusercontent.com/5462205/580393189-61875d66-4c44-4460-a966-4ce2e3bb3a83.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY1NzU4MDUsIm5iZiI6MTc3NjU3NTUwNSwicGF0aCI6Ii81NDYyMjA1LzU4MDM5MzE4OS02MTg3NWQ2Ni00YzQ0LTQ0NjAtYTk2Ni00Y2UyZTNiYjNhODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MTlUMDUxMTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzc1ZjFmMWExMGJlNjM0NzIwNzA4ZTM3M2I3ZDAxYWU0NjM2MDNmMDJmNzU2NGRlY2ExNTg4OGI4ZTRiMzYxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.wMacSOwEQ_nhAFVdb0qrqHy8u7uF-JR317ghFYZbjiI">

这个6啊 

我之前用AI 还开发了个这种东西

<img width="1010" height="677" alt="Image" src="https://github.com/user-attachments/assets/45fbeee8-7b98-4b09-ad6f-c62cfdc2f931" />
