### ISSUE TITLE
项目设置里文字方向

### ISSUE THREAD

**Issue by NinjaAquaKin** [xulihang/ImageTrans-docs#62]
想从横向改成竖向  点完应用再进去以后还是横向怎么办

**Comment by NinjaAquaKin** [comment]
浑身解数真的不知道咋把竖版日文翻译出来的中文也变成竖版的

**Comment by NinjaAquaKin** [comment]
看了视频大概懂了 但是为什么视频里有删除字体样式 ，我用的最新版单击只有“从项目导入   删不掉感觉很麻烦

**Comment by NinjaAquaKin** [comment]
或者说怎么把新添加的字体样式设置为默认

**Comment by xulihang** [comment]
需要在文字上方右键

**Comment by NinjaAquaKin** [comment]
我右键以后没有删除选项  只有一个《从项目导入

**Comment by NinjaAquaKin** [comment]
但是看你的演示视频好像直接右键就可以删了

**Comment by xulihang** [comment]
我给你录个视频吧：

1. 使用本地字体设置竖排

https://user-images.githubusercontent.com/5462205/122209824-8899bf80-ced7-11eb-8e50-7f482fc2152c.mp4


2. 使用全局字体样式设置竖排


https://user-images.githubusercontent.com/5462205/122209755-76b81c80-ced7-11eb-803d-af545bdba09d.mp4


全局样式记得保存，另外需要在文字上方右键，不能在空白处右键，不然只有从项目导入。

**Comment by NinjaAquaKin** [comment]
和你操作一摸一样   但是鼠标移到新建字体上面点击后右键点击真的只能出来《从项目导入

**Comment by NinjaAquaKin** [comment]
抱歉我解决了  耽误时间了非常抱歉

**Comment by NinjaAquaKin** [comment]
yysy'我随手打了个 1 ，以为是点那一行就行了 ，鼠标还一定要移到那么细的一个1 上才行==
