### ISSUE TITLE
能让复制粘贴功能直接作用在气泡上吗？

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#622]
包括气泡的大小 角度 内容

**Comment by xulihang** [comment]
啥意思，是右键创建副本这个操作吗

**Comment by yahoozhu** [comment]
![2024-04-18_17-05-44](https://github.com/xulihang/ImageTrans-docs/assets/24186777/6a5e151b-cf8d-4f46-abe2-c81d75764a15)

 这样的，这几个气泡都没识别，出来手动拉的，还有一些手写字体的拟声词，单个单个的很容易识别不出来，一页好几个，大小都差不多，我想手动拉一个气泡之后直接ctrl+c，在鼠标指定的位置ctrl+v一个大小、角度、原文、译文都一样的气泡出来

**Comment by xulihang** [comment]
可以用创建副本功能，再手动移下位置

**Comment by yahoozhu** [comment]
> 可以用创建副本功能，再手动移下位置

哦哦 看到了，可以给这个加进到快捷键列表里吗？最好给快捷键列表加个搜索，太多了，我检查三遍才确认没有这个功能

**Comment by xulihang** [comment]
快捷键项目是通过添加菜单项目来支持定义的。下个版本会在菜单里加上它

**Comment by xulihang** [comment]
加在v2.11.0里了
