### ISSUE TITLE
进行字体设置后，气泡就会取消选中状态了

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#623]
https://github.com/xulihang/ImageTrans-docs/assets/24186777/475813bf-08b3-4e07-96ca-41d6b28747b9

希望能维持选中状态，方便后续操作

**Comment by lhj5426** [comment]
使用样式来快速设置 不会取消选中 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/0fd947c8-7a6c-4c2c-8da0-d6e7e7216bcf)
而且可以批量设置 字体设置主要是还原 样式用的 平时设置字体请使用指定样式

**Comment by lhj5426** [comment]
比如你想要无描边就在这样样式里设置一个无描边 每次 设置的时候 选择 指定样式里的无描边就可以了 设置方便还不会取消选中
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4dd1d16b-aaae-481f-a957-8d8d03eb03ee)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b4173cbb-b072-46e8-a894-0ae661ee9d9e)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ac0b3793-c69b-47c2-9cc3-33429fbe0420)

**Comment by yahoozhu** [comment]
> 使用样式来快速设置 不会取消选中 ![image](https://private-user-images.githubusercontent.com/30548000/323811413-0fd947c8-7a6c-4c2c-8da0-d6e7e7216bcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTc1MjcsIm5iZiI6MTcxMzQ5NzIyNywicGF0aCI6Ii8zMDU0ODAwMC8zMjM4MTE0MTMtMGZkOTQ3YzgtN2E2Yy00YzJjLThkYTAtZDZlN2U3MjE2YmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAzMjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMGUyMjAwNjI4NjkxNDdlNTMzOWE2ZjM4MmI4ZTM1NTk4ZjkxMzZjZWFmMGI2ODA1MzI0MWE3MjA0YzBiNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79fU-HGPp0cHthKK2j3Gkh6_XVwhhXF1eqKlWdICyBw) 而且可以批量设置 字体设置主要是还原 样式用的 平时设置字体请使用指定样式

这是解决方案之一，不过保留选中状态还是更符合习惯吧，而且样式通用性也不太够，太小或者太大的字体，还是要单独调描边

**Comment by lhj5426** [comment]
> > 使用样式来快速设置 不会取消选中 ![image](https://private-user-images.githubusercontent.com/30548000/323811413-0fd947c8-7a6c-4c2c-8da0-d6e7e7216bcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTc1MjcsIm5iZiI6MTcxMzQ5NzIyNywicGF0aCI6Ii8zMDU0ODAwMC8zMjM4MTE0MTMtMGZkOTQ3YzgtN2E2Yy00YzJjLThkYTAtZDZlN2U3MjE2YmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAzMjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMGUyMjAwNjI4NjkxNDdlNTMzOWE2ZjM4MmI4ZTM1NTk4ZjkxMzZjZWFmMGI2ODA1MzI0MWE3MjA0YzBiNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79fU-HGPp0cHthKK2j3Gkh6_XVwhhXF1eqKlWdICyBw) 而且可以批量设置 字体设置主要是还原 样式用的 平时设置字体请使用指定样式
> 
> 这是解决方案之一，不过保留选中状态还是更符合习惯吧，而且样式通用性也不太够，太小或者太大的字体，还是要单独调描边

嗯 不过我做了一百多部 漫画 还真没怎么用这个功能 除了 删除旋转之外 几乎不用这个功能  等开发者后边优化

**Comment by xulihang** [comment]
2.11.0修改后不会取消选中了
