### ISSUE TITLE
确实需要一个全局可调整位置的固定文本框

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#626]
老哥 这个 issues 延伸自
https://github.com/xulihang/ImageTrans-docs/issues/506
之前 提过这个问题 
这种图的话使用全图文本框是没任何问题 的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/189e6bcd-fc05-4964-99dc-a1b6e8ab8f58)
正如 506所说那样 
 但是 现在遇到了这种
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/bf87fd21-4c43-42c9-83bc-9b97f0dc4663)
这种使用全图 文本框的 话 就不行了 

所以 还得 说 后续 请您 增加 一个 功能 就是全图 固定文本框
框选出来之后 整个项目的 图片位置都是固定
只要框选一次 后续的位置也固定不需要二次框选了
这样对于翻译 这种 非气泡 非漫画的 且单一 但是位置固定图 是非常有帮助的 
现在这种只能一张一张手动 去框选 很机械很重复 很累

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/02491605-011e-4106-bb09-8863a22de84c)
如果 有这种功能的话
这样 我只需要在一张图上 拉一个框 后续的图片也是这样位置 这样 我直接拉完框之后 点击OCR就可以开始识别了
而现在 是每一张图我都得去拉这个框 
翻译RPG游戏的图片。。  现在就很繁琐 很麻烦

**Comment by xulihang** [comment]
加在v2.11.0里了：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/0321566b-dd29-490e-8d3d-8fdc5a069bdc)

**Comment by lhj5426** [comment]
> 加在v2.11.0里了：
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/324227727-0321566b-dd29-490e-8d3d-8fdc5a069bdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTIzODksIm5iZiI6MTcxMzY5MjA4OSwicGF0aCI6Ii81NDYyMjA1LzMyNDIyNzcyNy0wMzIxNTY2Yi1kZDI5LTQ5MGUtOGQzZC04ZmRjNWEwNjliZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjFUMDkzNDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQzODUwMDQ3YmNiODNlYWZlZTk2YzRiNWFkM2YxZTI1Y2E0MmVkZDc5MzllMGZkZjFhYjQ3NTEzN2ZkYThmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UZX1YQI21aBdS56HZMAW6mzS_TS784_CPixU7-yQprM)

66666感谢 这就去试试 这样以后翻译RPG图片省事了

**Comment by lhj5426** [comment]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/b9772542-250c-4b20-bdbb-49111fc88884

太 棒了 非常感谢 这样 在遇到这种 框选一个 之后生成模版就行了 爱你
