### ISSUE TITLE
寻一位互相进行文本翻译润色的友人，自己翻的用不起来

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#627]
自己翻的怎么样都没办法用起来
之前加了一个机翻群找的人他们不用这个软件，尝试了下纯导出文本对着图片进行翻译润色的话效率太低太浪费时间了，要能在项目里直接操作效率高很多，不用费神的去找句子看得眼花

特此寻一位互翻友人，流程的话就是自己的本子先进行ocr自检——文本排序——导出文本——使用第三方AiNiee一次性翻译——导入文本（我会额外提供共4个AI翻译的表格给你）——交换项目——两人仅做文本校对润色工作——交换工程文件

就按30页的本一周的时间这样的节奏来就可以，本人偏爱熟女NTR题材，最好来个JK纯爱党，那种题材我是一概不看
本人翻译质量https://e-hentai.org/uploader/bgxyahoo
有兴趣的加q315892756

**Comment by xulihang** [comment]
这里访客不多，每天也就十来个。你这条挂一个星期我会给它关闭。

**Comment by lhj5426** [comment]
可惜都是熟女 无爱啊
我https://exhentai.org/?f_search=uploader%3Allflzy+uploader%3A%E6%B7%AB%E4%B9%A6%E9%A6%86+uploader%3AL%E6%B7%AB%E4%B9%A6%E9%A6%86L+uploader%3A%E6%B7%AB%E6%9B%B8%E9%A6%86
我喜欢 年轻的 JK  哈哈哈哈哈哈哈  本人的翻译质量

**Comment by yahoozhu** [comment]
> 可惜都是熟女 无爱啊 我https://exhentai.org/?f_search=uploader%3Allflzy+uploader%3A%E6%B7%AB%E4%B9%A6%E9%A6%86+uploader%3AL%E6%B7%AB%E4%B9%A6%E9%A6%86L+uploader%3A%E6%B7%AB%E6%9B%B8%E9%A6%86 我喜欢 年轻的 漂亮的 JK 哈哈哈哈哈哈哈 本人的翻译质量 不过我都是做长篇 2 3百页的这种 全彩

这不是正好吗，互翻就要对对方的题材不感兴趣的才好，不过你的翻译量确实大，我硬凑都凑不出这么多页想翻的本

**Comment by lhj5426** [comment]
> > 可惜都是熟女 无爱啊 我https://exhentai.org/?f_search=uploader%3Allflzy+uploader%3A%E6%B7%AB%E4%B9%A6%E9%A6%86+uploader%3AL%E6%B7%AB%E4%B9%A6%E9%A6%86L+uploader%3A%E6%B7%AB%E6%9B%B8%E9%A6%86*  我喜欢 年轻的 漂亮的 JK 哈哈哈哈哈哈哈 本人的翻译质量 不过我都是做长篇 2 3百页的这种 全彩
> 
> 这不是正好吗，互翻就要对对方的题材不感兴趣的才好，不过你的翻译量确实大，我硬凑都凑不出这么多页想翻的本

你从一开始就搞错了一件事情了
这东西是兴趣驱动的 
而不是 所谓的 使命感
我从发现 到使用 会用老哥的工具这句话过程
我就是以兴趣驱动的
熟女不在兴趣范围内  虽然我也是NTR党 但是我更是一个画风党 画风既正义
在没有兴趣的前提下也没有动力 去 搞
而且 我手里不光有漫画 我还有视频 哈哈 还会搞搞rpg游戏
我是一直期待我做的漫画会有视频版
然后再做成视频版的字幕 
所以我在坚持 做长篇全彩 哦对了 4.26 就有一部

**Comment by yahoozhu** [comment]
> > > 可惜都是熟女 无爱啊 我https://exhentai.org/?f_search=uploader%3Allflzy+uploader%3A%E6%B7%AB%E4%B9%A6%E9%A6%86+uploader%3AL%E6%B7%AB%E4%B9%A6%E9%A6%86L+uploader%3A%E6%B7%AB%E6%9B%B8%E9%A6%86*  我喜欢 年轻的 漂亮的 JK 哈哈哈哈哈哈哈 本人的翻译质量 不过我都是做长篇 2 3百页的这种 全彩
> > 
> > 
> > 这不是正好吗，互翻就要对对方的题材不感兴趣的才好，不过你的翻译量确实大，我硬凑都凑不出这么多页想翻的本
> 
> 你从一开始就搞错了一件事情了 这东西是兴趣驱动的 而不是 所谓的 使命感 我从发现 到使用 会用老哥的工具这个过程 我就是以兴趣驱动的 熟女不在兴趣范围内 虽然我也是NTR党 但是我更是一个画风党 画风既正义 在没有兴趣的前提下也没有动力 去 搞 而且 我手里不光有漫画 我还有视频 哈哈 还会搞搞rpg游戏 我是一直期待我做的漫画会有视频版 然后再做成视频版的字幕 所以我在坚持 做长篇全彩 哦对了 4.26 就有一部
> 
> 在享受了 制作的过程之后 用不用 那都无所谓了 我们想看这个故事 画风这么好 讲了个什么故事 而抛开低级趣味的用 虽然做的东西就是低级趣味的 但是 也是可以抛开的 享受过程才是乐趣

佩服你确实是兴趣使然，我还是性趣使然多点，好多本翻完一年多就算很喜欢的也不想再动手去修图嵌字了，看本翻本都是为了用，没什么见不得人，脱离了这个最底层的需求说啥都不好使，真要看故事，正常向的大师作品还有茫茫多的囤货放在收藏夹里吃灰没看的在
