### ISSUE TITLE
能把tsv的机器翻译移到最上面优先刷新吗？

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#628]
仅勾选tsv的话倒是可以瞬间显示，勾选其他机器翻译的话会按顺序展示，最后才是tsv，速度慢吞吞的，我有4个额外翻译倒是够用，但其他机器翻译也还是有点参考作用的

**Comment by xulihang** [comment]
目前获取机器翻译是一个一个获取的，需要改成同时获取

**Comment by xulihang** [comment]
并发获取机器翻译，应用在v2.11.1里了
