### ISSUE TITLE
滑动建框可以添加多个方向吗？

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#629]
![2024-04-22_08-57-14](https://github.com/xulihang/ImageTrans-docs/assets/24186777/7d4d927e-616c-421e-987f-47b9ff68d213)

目前滑动建框只能从左上往右下这一个方向
拉分镜框时，像这样左上角有贴边气泡，要小心翼翼点到左上最边缘的空隙处才行，不然容易选中气泡，如果从右下角大片空白处往左上角拉就好多了，这种情况还蛮多的

![2024-04-22_09-43-28](https://github.com/xulihang/ImageTrans-docs/assets/24186777/b3aa6e4a-e7ca-40f3-be57-dbe84a5a5274)

或者是这样密集的地方，左上角有气泡了，想在绿圈的位置拉个气泡出来会很容易激活左上角框的旋转条

**Comment by xulihang** [comment]
之前提过的issue：https://github.com/xulihang/ImageTrans-docs/issues/26

**Comment by xulihang** [comment]
加在v2.11.1里了
