### ISSUE TITLE
Cannot open the exe file

### ISSUE THREAD

**Issue by serycomplexee** [xulihang/ImageTrans-docs#63]
Hello,
I have issue opening the exefile i downloaded the version for personnal use (the cheapest). Even if I right click to execute as administrator or type ImageTrans.exe in a powershell nothing happens. Here is a screencaps of the folder:
![image](https://user-images.githubusercontent.com/86020526/122277910-b2a6ae00-cee6-11eb-9356-f3887b254479.png)

**Comment by xulihang** [comment]
Please read the documents before you ask: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#id2

You are using the cross-platform version. You need to set up jre and opencv manually
