### ISSUE TITLE
tvs的翻译导入显示问题有点多

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#633]
最频繁的是同一页里有的文本有的能刷出来，有的刷不出来，刷不出来的有时候怎么样都不行，有时候几个气泡间点来点去又有了

![2024-04-24_22-23-17](https://github.com/xulihang/ImageTrans-docs/assets/24186777/5c838082-e59a-4e8e-bed7-902fd3df79e0)
还有就是会重复显示，读取两遍显示出来，甚至会像这样把其他气泡的内容显示出来

**Comment by xulihang** [comment]
不启用其它机器翻译，显示速度快吗？

tsv这个要求软件里的原文和tsv里存的原文完全一致。

如果当前气泡的机器翻译没全部加载就切到另一个气泡了，没加载的之前气泡的机器翻译的确也会显示出来。

**Comment by yahoozhu** [comment]
> 不启用其它机器翻译，显示速度快吗？
> 
> tsv这个要求软件里的原文和tsv里存的原文完全一致。
> 
> 如果当前气泡的机器翻译没全部加载就切到另一个气泡了，没加载的之前气泡的机器翻译的确也会显示出来。

不勾可以全部瞬间显示，勾了很容易出现不显示和重复显示，不过不勾不太行，AI有的句子罗里吧嗦的，有些还是要机器翻译

**Comment by yahoozhu** [comment]
还一个问题切换项目的话必须关闭程序重新进才行，不然完全不读取了，是不是把tvs路径放到项目设置下面好点？

**Comment by xulihang** [comment]
这个需求最好是单独写一个机器翻译服务器程序，通过页面配置用哪个。不过我没时间，tsv是个临时的简单方案。

**Comment by xulihang** [comment]
切换到另一个气泡，显示之前气泡的翻译的问题在v2.11.1里修复了

**Comment by yahoozhu** [comment]
牛蛙牛蛙
