### ISSUE TITLE
省略号不居中怎么处理

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#634]
![image](https://github.com/xulihang/ImageTrans-docs/assets/26926749/1dbe9083-2417-44e6-b51a-f609b7f8df73)

**Comment by hyominli** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/26926749/c5842f4e-ffbf-4ac6-92af-1cc41a96fc22)

**Comment by xulihang** [comment]
不同的字体省略号的居中效果不一样。目前没有设置某些字符水平偏移的功能，可以使用富文本功能把省略号的字体换成一个省略号居中的字体。

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/4fa0b8f6-fa95-4752-8741-3cf9716cc3a6)

**Comment by xulihang** [comment]
相关的issue：https://github.com/xulihang/ImageTrans-docs/issues/271

**Comment by hyominli** [comment]
> 相关的issue：#271

我用的方正黑体简体为啥不能居中啊

**Comment by xulihang** [comment]
可能下的版本不一样，再换个试试吧

**Comment by hyominli** [comment]
> 可能下的版本不一样，再换个试试吧

能给下你的这个吗_(:з」∠)_

**Comment by hyominli** [comment]
> https://www.fonts.net.cn/font-31593102437.html

感谢大佬！
