### ISSUE TITLE
Problem with DeeplFree

### ISSUE THREAD

**Issue by CapMan47** [xulihang/ImageTrans-docs#635]
DeeplFree suddenly started giving “null”, although everything was fine earlier today. I tried to roll back to the old version of the program and create new projects - no help. mymemory works, but the quality there is worse. Could you please tell me what could be the problem?
Thanks in advance.
![Снимок экрана 2024-04-26 123759](https://github.com/xulihang/ImageTrans-docs/assets/119116019/2c84660a-5bb8-4436-a7b9-3d7e13035290)

**Comment by CapMan47** [comment]
Do you mean the paid Deepl Api or Deepl Api Free? I know there is Deepl Api free with a 500,000 character limit per month, will I be able to connect it? It's just that in ImageTrans the Deeplfree API window doesn't require a key and that confuses me. But you need to insert a url. Could you please clarify this point if not too much trouble.
![Снимок экрана 2024-04-26 133114](https://github.com/xulihang/ImageTrans-docs/assets/119116019/1bbe7e2b-8ca9-4829-9a19-058971c862e4)

**Comment by xulihang** [comment]
The DeepL plugin uses the official api and you can choose to use its free mode and fill in your key.

The DeepLFree plugin uses a hack to use DeepL without an API key.

**Comment by CapMan47** [comment]
Got it, I'll use Deepl Free Api, thanks for the help).
I'll check for the future - are there any plans to update the hack?

**Comment by xulihang** [comment]
There are alternatives like DeepLX: https://github.com/OwO-Network/DeepLX

Maybe I will use it instead.

**Comment by CapMan47** [comment]
Super, I'll be looking forward to it)

**Comment by xulihang** [comment]
I just tested it. The hack is still working.
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/e6297a1b-44b4-416e-9f18-8b0d74825f91)

**Comment by CapMan47** [comment]
Yes, it started working the same day, apparently there were problems on his side. But then a few more times there were problems and it didn't work temporarily.
