### ISSUE TITLE
右侧的选项卡能不能自定义位置？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#637]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/16dc0aab-14cf-4708-9f7d-422f9abd6b99)
 如图  开发者老哥
  您看 这个文字输入的地方可以飞出来独立放在任意位置
  那么 您看文字飞出来之后 上边空出来一大片
  那么 能不开发成这样
  

https://github.com/xulihang/ImageTrans-docs/assets/30548000/5b9451d0-d671-492a-aa2d-f41df400b41f

像PS 这样 的选项卡 可以自由组合拖拽的 
你您看啊 把文字框飞出来之后 这一片空白
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/13dac006-3608-4418-bee0-7a24b651883c)
闲着 也是占地方
为什么我们不能给他利用上呢？
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/31d6d989-3638-4183-a612-d0ab3816832f)
比如
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/33c8e7b5-147a-41a3-a212-b60dbfa32af5)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/555d7122-fdc0-49c6-96eb-a2d536f1d969)
 这样自由组合？ 
 甚至把文本框也合并到分镜后边 让整个右侧成为文字编辑区域？
 这样还可以显示更大文字
 当然下边是不是也可以设置成独立飞出来？
 这样的话 使用多屏的话 就可以 把一部分放在第二屏幕 第三屏幕然后 让一个屏幕只显示全图 
 这样一个屏幕只放IT图片编辑区域 一个屏幕放PS 然后一个屏幕放 IT的文字编辑区域 
 感觉好像也不错 如果是带鱼屏幕的话 空间利用率就更高了

**Comment by xulihang** [comment]
需要自定义控件，难度比较高

**Comment by lhj5426** [comment]
好叭 期待在未来的版本中能够加入吧

**Comment by xulihang** [comment]
这个不打算做
