### ISSUE TITLE
Problem with translation import.

### ISSUE THREAD

**Issue by CapMan47** [xulihang/ImageTrans-docs#639]
Hi. There is a problem with importing a translation. I export text to docx format and translate, then I replace the text in the same file with the translated text and launch the translation import. Nothing happens, but if I agree to import source text, it is replaced. But the window with the translation remains empty. 
I tried to export to txt or create a new file with translation, but nothing helps, I'm obviously doing something wrong, but I don't know what. 
Looked for a solution in the documentation, but there is very poorly described actions, so I turn here. 
Please give me a hint.

**Comment by xulihang** [comment]
You should put the translation in the second column instead of replacing the source text.

**Comment by CapMan47** [comment]
I'm not sure which column we're talking about. There are two columns in xlsx, but not in docx. 
![image](https://github.com/xulihang/ImageTrans-docs/assets/119116019/d83bbc25-5427-4539-afce-18f81f70d9c4)

**Comment by xulihang** [comment]
You have to adjust the width of the second column to reveal it.

**Comment by CapMan47** [comment]
Sorry for the dumb questions, but how do I do this? When I change the width, this happens....
![image](https://github.com/xulihang/ImageTrans-docs/assets/119116019/1e7b1feb-dc64-4c4b-8a71-8e14b2f4506d)

**Comment by CapMan47** [comment]
Got it figured out, thanks for the help. I never realized there was a second column hidden there. 
An additional question, if I import from txt, how will it look like? There are no columns there?

**Comment by xulihang** [comment]
I will set the target text column's width to 50% in the next version of ImageTrans.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/cf1cb148-b429-4817-acef-f0d8ce7f0c6b)

**Comment by xulihang** [comment]
> I will set the target text column's width to 50% in the next version of ImageTrans.
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/326376884-cf1cb148-b429-4817-acef-f0d8ce7f0c6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTUyMTMsIm5iZiI6MTcxNDY1NDkxMywicGF0aCI6Ii81NDYyMjA1LzMyNjM3Njg4NC1jZjFjYjE0OC1iNDI5LTQ4MTctYWNlZi1mMGQ4Y2U3ZjBjNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMTMwMTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA1OTFjMGU0MzUwMGI2M2MzNzk0MTUzNTE4MzJhYWNhMWM4OGFkMGRmZGVlMDRhYWZmZDM0MjI5ZDkyN2IwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NomunWgG52YIfq5sfdcmywJwxm8vdll11Cz0RnNzyNU)

Implemented in v2.11.2.
