### ISSUE TITLE
UI font size too small

### ISSUE THREAD

**Issue by jps1226** [xulihang/ImageTrans-docs#64]
I find myself having a very hard time editing text because the translation areas and editing areas have very small font size. Changing my windows scaling and/or font size changes nothing within the application, and neither do the high DPI settings (but that's probably because it only applies to the .exe and not the .jar, I assume). I use the app on a 1080 monitor as well as on a 4K laptop and the scaling seems consistent, which leads me to believe it's not a scaling issue.

Currently I've been using a 3rd party magnifying glass app to see the font as I type, but I really wish I could change the UI font size. Am I missing something or is there no way to do this currently? 13 pixels is just too small...

![unknown](https://user-images.githubusercontent.com/30449321/122577329-45933580-d018-11eb-8b02-2ce94cb8a195.png)

**Comment by xulihang** [comment]
![image](https://user-images.githubusercontent.com/5462205/122630407-f0c5ec80-d0f5-11eb-9b33-fc5d2bdbb34e.png)

You can use JavaFX's css to style any UI element.

1. Create a css file with the following content:

  ```css
  .text-area {
      -fx-font-size: 25 !important;
  }
  ```

2. Enable it in the Preference using external css:
  
  ![image](https://user-images.githubusercontent.com/5462205/122630434-2539a880-d0f6-11eb-937f-2b8654dd31e3.png)

**Comment by xulihang** [comment]
If you want to keep the dark theme, add the following css to your css file:

```css
.root {
  -fx-base: rgba(60, 63, 65, 255); // dark
}
```

![image](https://user-images.githubusercontent.com/5462205/122630487-bc066500-d0f6-11eb-8cff-8b37ca2c72fd.png)

**Comment by jps1226** [comment]
Thank you so much!!

**Comment by xulihang** [comment]
I've added a font project settings in v1.5.0 which is more convenient to set up the UI font.

![image](https://user-images.githubusercontent.com/5462205/141674873-880ff815-6c7f-440a-89c3-6749f020899c.png)
