### ISSUE TITLE
你好，请问像这种显示翻译后有白块的问题，有没有除了手工涂掩膜之外的方案

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#641]
![image](https://github.com/xulihang/ImageTrans-docs/assets/26926749/5951bb66-1918-495a-8fb5-e2a1c11246b6)

**Comment by xulihang** [comment]
带描边，项目设置里把掩膜膨胀大小设大一点

**Comment by xulihang** [comment]
参考issue：https://github.com/xulihang/ImageTrans-docs/issues/640
