### ISSUE TITLE
如果只存在一个字幕框话的话能不能默认选中呢

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#642]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/203dcc44-9a8b-4ef3-b527-36c041c6053c

尊敬的 老哥如视频所示
如果每张图片 只有一个字幕框？ 文本框？
的话能不能默认选中
 视频里我是在对OCR的字幕进行校对
 每次切换图片之后 还得手动点一下框框 才能看到字幕 并进行校对
 有点不太方便 
 所以 后边能不能弄一个 如果只存在一个框框的话 就每次切换图片的时候自动选中上
 这样每一页能节省一 到2个步骤 
 加起来 能节省很多劳动力
 还有一个就是
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/cffbfae4-092b-4c6e-9e3b-c588d764aa91)

这个东西在飞出来 出于 悬浮状态的时候 这个 中间的杠杠 ？ 分割UI？ 可以 左右滑动拖动大小么
现在想要让左边的原文完全以一行的形式显示出来 这个框要拖拽的很长 右边都快飞出屏幕了

**Comment by lhj5426** [comment]
啊 后边的是我蠢了 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8151415e-bd26-4e5b-8265-551d49195407)
 飞出来可以 上下这样就不会飞出屏幕了

**Comment by xulihang** [comment]
可以加个偏好设置，切换图片时默认选择第一条

**Comment by lhj5426** [comment]
> 可以加个偏好设置，切换图片时默认选择第一条

嗯  按需开启 好耶！！

**Comment by xulihang** [comment]
偏好设置添加在v2.12.0里了

**Comment by lhj5426** [comment]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/e6a32de7-07fc-4271-9a3a-779bda558d1a

感谢 老哥
