### ISSUE TITLE
导出所有文本的时候可以默认删除图片扩展名吗？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#643]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/8739c952-e301-4fc6-be37-606b62d4e3ce

哥 如视频所示
ImageTrans 的文件→导出 →所有文本
导出的
图片 的名字
ImageGrab_0.00.20.00.png
ImageGrab_0.00.23.00.png
ImageGrab_0.00.26.00.png
ImageGrab_0.00.28.00.png

ImageTrans 导出的所有文本的名字
ImageGrab_0.00.20.00.png.txt
ImageGrab_0.00.23.00.png.txt
ImageGrab_0.00.26.00.png.txt
ImageGrab_0.00.28.00.png.txt
可以把
.图片后缀删除变成

ImageGrab_0.00.20.00.txt
ImageGrab_0.00.23.00.txt
ImageGrab_0.00.26.00.txt
ImageGrab_0.00.28.00.txt

这样利于使用   感谢

**Comment by xulihang** [comment]
万一有同名的jpg和png不容易区分，我不想改程序。你可以自己写个重命名的脚本

**Comment by lhj5426** [comment]
> 万一有同名的jpg和png不容易区分，我不想改程序。你可以自己写个重命名的脚本

嗯  好的 感谢
