### ISSUE TITLE
没有检测到图片是什么情况

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#644]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b24c2608-6ad4-445a-8a88-5dd8021743ec)
事情是这样子的
今天在逛DMM的时候发现之前买的并且做完的漫画
也更新出2560的版本了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5b52dd79-61b8-4f16-8e1d-eb01c2c87ce2)

然后我用1920的 项目文件 打开 2560的图片就出现了 
帖子最开始的提示
然后就算我用
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c027e990-0f6b-42cc-999e-1d110eb00858)
转换工具 重新转换jpg 也 还是这个提示 但是新建立一个项目就没事

我之前也是用相同的方法
https://github.com/xulihang/ImageTrans-docs/issues/591
用1920的 项目打开 2560的图片 就没有这个弹窗提示
所以我想问一下老哥 这个弹窗提示是什么意思？ 为什么无法检测到图片？ 
图片明明就好好的在这里放着
新创建的项目文件就可以检测到图片
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b38f91aa-128c-4185-a7af-d5fe023e930a)
 用旧项目文件就无法检测到呢？

**Comment by lhj5426** [comment]
如图检测不到的话 我还有什么方法可以把已经做完的项目移植到新的 更大尺寸的图片上呢？

**Comment by lhj5426** [comment]
忘记说了 图片名字 和路径都是一样的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2e5d4767-5827-44fd-a0a2-a413d21bdaa7)
 关于整理图片 我一直是 使用第三方资源管理器
 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/fa07edea-0abb-48e0-9281-4101bdfee6ff)
专门做了一个整理的工具条 不管是图片的重命名排序
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/58c097e3-148d-4bd0-9909-467988662691)
还是路径 都是固定的
就是旧项目无法读取新图片

**Comment by xulihang** [comment]
如果没有检测到新的图片，就提示没有检测到图片。原来的图片还是在项目里的

**Comment by xulihang** [comment]
要用新的版本，不是直接替换原来的图片就行了吗

**Comment by lhj5426** [comment]
> 要用新的版本，不是直接替换原来的图片就行了吗

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/ad617189-04fb-4cb0-96d2-95aeb75cb202)
我也是 这么认为 以前也确实是这样的
您看 1920 本篇是之前项目  原来的项目文件夹就叫 本篇
但是现在有了更高分辨率的图 所以我把原来的本篇改名成1920 本篇

然后我又创建了一个和原来那个项目相同的名字的文件夹 【本篇】 然后 新的 大尺寸图片也放在了这个文件夹里
并且图片的重命名也是完全相同的 路径也是完全相同的
接着我打开 项目 是不显示图片的 我点 导入图片文件夹 就出现了这个提示

**Comment by lhj5426** [comment]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/1b972d59-1f16-40e0-bda8-3fd7d454b2ad

好吧  被这个 提示 给误导 忽悠了

您看 打开项目 之后  不显示图片 
点击导入之后 提示 这个提示 然后
我在发帖之前没有点击下一页去看 
刚才您说图片还在里面

那我就稍微点击了上一页 下一页

结果 图片出来了....... 这个提示 这个提示  给我误导 了
