### ISSUE TITLE
也许未来可以引入新的识别功能？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#645]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/9e81ce6e-2e40-4bcc-aa22-3d766b736fa0)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/743c2351-e369-42a0-a1ae-82367a24e0de)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/826f905e-f4af-4ea0-aaa8-e2e7f81f8ea7)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/b8b2aa43-77fd-4843-b556-9acb45b31c86)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/86c7c054-1208-4f06-a951-ff6f0f6db29f)

今天的GPT4O 哈哈 可以直接识别漫画

**Comment by xulihang** [comment]
还需要能返回坐标信息。可以的话可以做个类似这个的图片翻译插件：https://github.com/xulihang/ImageTrans-docs/issues/470

**Comment by lhj5426** [comment]
> 还需要能返回坐标信息。可以的话可以做个类似这个的图片翻译插件： [#470 ](https://github.com/xulihang/ImageTrans-docs/issues/470)*

![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d413b9ff-c12e-4bf3-815b-8d2cf180909d)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/bd44fa87-a1fe-4f55-aca2-844ec39764ba)

哈哈抱歉 老哥 有点太兴奋了 看来还有一段路要走
