### ISSUE TITLE
自定义工作流的合并和文本框的合并不一样？

### ISSUE THREAD

**Issue by haofan170** [xulihang/ImageTrans-docs#646]
rt，在自定义工作流中开启了【纵向合并】的情况下运行了一遍
![image](https://github.com/xulihang/ImageTrans-docs/assets/49093867/fd52e79d-0a0c-4a7d-af64-87f92448b8b9)
，但是我发现还是没合并很多，但是如果使用的是文本框区域里面的
![image](https://github.com/xulihang/ImageTrans-docs/assets/49093867/a8c91e75-ba6a-4c1a-8169-de9593c285a4)
合并左右区域，就可以合并，请问是哪里要设置吗

**Comment by xulihang** [comment]
合并左右区域是横向合并，不是纵向合并

**Comment by haofan170** [comment]
> 合并左右区域是横向合并，不是纵向合并

感谢== 原来是我搞反了啊
