### ISSUE TITLE
Can a new functionality be added?

### ISSUE THREAD

**Issue by ztench** [xulihang/ImageTrans-docs#647]
I want to explain in more detail what I want to do: when I translate directly from Korean to Spanish using ChatGPT or another translator, the translation quality is not very good. To improve the translation, I have to first translate from Korean to English and then from English to Spanish.

I wonder if it is possible to add a functionality that allows translation from Korean -> English -> Spanish.

**Comment by xulihang** [comment]
Yes. 

It is a good idea to have English as the intermediary language to improve the quality and support more language directions.

I will add an option to do this.

**Comment by ztench** [comment]
Thank you very much for considering my suggestion, and I look forward to the prompt implementation of this functionality.

**Comment by xulihang** [comment]
Added in v2.12.2. 

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/a90afdaf-ebf0-4189-8c90-52af0767826f)
