### ISSUE TITLE
Problem with the text areas

### ISSUE THREAD

**Issue by truki20** [xulihang/ImageTrans-docs#648]
When using the "detect text area (heuristic)" option, there is an issue because the order of each text area is incorrect. This creates a problem as I have to use "down" and "up" repeatedly to position them correctly. I am referring to the mawhas.
Additionally, I would appreciate knowing how to set the language configuration of ImageTrans to Spanish.

**Comment by xulihang** [comment]
You can sort text areas after detection: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#id17

You can set the sorting criteria in the project settings.
