### ISSUE TITLE
完全无法使用mangaOCR

### ISSUE THREAD

**Issue by changbaishanshan** [xulihang/ImageTrans-docs#649]
小白一枚，刚刚按照说明安装好了软件，觉得果然高大上。

但是在用的时候第一步就卡住了，漫画里的文字完全无法识别，气泡和坐标都正常，就是完全没有文字。

安装的版本是2.12.1，MangaOCR也单独安装了一遍，软件的安装目录都没有中文，不知道为什么这样，求大佬指点
<img width="795" alt="批注 2024-05-18 164011" src="https://github.com/xulihang/ImageTrans-docs/assets/170170640/8ae9256c-5577-4666-b587-39426eb88011">

**Comment by xulihang** [comment]
mangaocr要保持在后台运行，然后去调用
