### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#65]
I think a bookmark feature would be useful, like open project on the bookmarked page or with an already open project, go to bookmarked page

**Comment by xulihang** [comment]
I haven't added a bookmark feature. But in v1.6.0, it will record which image is opened lastly and it is possible to go the this image using a menu item.

![image](https://user-images.githubusercontent.com/5462205/152671333-d314b415-54d1-4ff7-af1c-47122754e116.png)

**Comment by xulihang** [comment]
The bookmark feature is added in v3.18.0.
