### ISSUE TITLE
problems with chatgpt

### ISSUE THREAD

**Issue by ztench** [xulihang/ImageTrans-docs#651]
when I translate with the gpt-4o model by checking the box :translate multiple sentences in one reques, it does not translate the texts. is there any way to make it compatible.

**Comment by xulihang** [comment]
I cannot test it since I don't have access to gpt4o. Please make sure you have access to it as well.

You can use ImageTrans.bat to start ImageTrans to check out the error message.

**Comment by ztench** [comment]
(MyMap) {role=user, content=Your task is to translate a text in JSON format into English and return the text in valid JSON format. You should not mix the values of different keys into one. Here is the JSON string to translate: {"11":"? ???? ??? ?? ??,","12":"???","13":"???? ??? ??? ???? ??? ????,","14":"??? ??? ?? ??.","0":"? ?? ??? ??? ??? ??? ?? ? ???,","1":"? ??? ???","2":"? ???? ?? ??? ?? ????.","3":"? '?? ??? ??...?'","4":"? ?? ???,","5":"? ??? ??? ?????..?","6":"? ??? ?? ??? ??? ???","7":"? ????? ?? ??? ??? ????? ???...,","8":"? ? ??? ? ?? ? ?? ???","9":"? ?? ?? ???? ?? ???? ???? ?? ????.","10":"? ???? ???."}}
{"messages":[{"role":"user","content":"Your task is to translate a text in JSON format into English and return the text in valid JSON format. You should not mix the values of different keys into one. Here is the JSON string to translate: {\"11\":\"? ???? ??? ?? ??,\",\"12\":\"???\",\"13\":\"???? ??? ??? ???? ??? ????,\",\"14\":\"??? ??? ?? ??.\",\"0\":\"? ?? ??? ??? ??? ??? ?? ? ???,\",\"1\":\"? ??? ???\",\"2\":\"? ???? ?? ??? ?? ????.\",\"3\":\"? '?? ??? ??...?'\",\"4\":\"? ?? ???,\",\"5\":\"? ??? ??? ?????..?\",\"6\":\"? ??? ?? ??? ??? ???\",\"7\":\"? ????? ?? ??? ??? ????? ???...,\",\"8\":\"? ? ??? ? ?? ? ?? ???\",\"9\":\"? ?? ?? ???? ?? ???? ???? ?? ????.\",\"10\":\"? ???? ???.\"}"}],"model":"gpt-4o"}
{
  "id": "chatcmpl-9RAoBPLDrKZYHO8l1YyloenvVHKfB",
  "object": "chat.completion",
  "created": 1716263431,
  "model": "gpt-4o-2024-05-13",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "```json\n{\n  \"11\": \"It's not a light that feels bright,\",\n  \"12\": \"But\",\n  \"13\": \"Jekyll, played by Shin Yoomyung, is someone who thoroughly pursues perfection,\",\n  \"14\": \"A man with moral impeccability.\",\n  \"0\": \"If human nature could be contained in separate entities,\",\n  \"1\": \"We would no longer\",\n  \"2\": \"Have to endure anything.\",\n  \"3\": \"'No need to endure...?'\",\n  \"4\": \"Henry Jekyll,\",\n  \"5\": \"What have you been enduring so much...?\",\n  \"6\": \"Jekyll's originally bright and warm nature\",\n  \"7\": \"Did catch one's eye due to the contrast with Hyde, but...\",\n  \"8\": \"Why someone who seems to have everything\",\n  \"9\": \"Would develop and personally consume such a drug was somewhat unconvincing.\",\n  \"10\": \"It was truly light.\"\n}\n```"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 266,
    "completion_tokens": 214,
    "total_tokens": 480
  },
  "system_fingerprint": "fp_729ea513f7"
}

(RuntimeException) java.lang.RuntimeException: JSON Object expected.
(MyMap) {role=user, content=Your task is to translate a text in JSON format into Spanish and return the text in valid JSON format. You should not mix the values of different keys into one. Here is the JSON string to translate: {"11":"","12":"","13":"","14":"","0":"","1":"","2":"","3":"","4":"","5":"","6":"","7":"","8":"","9":"","10":""}}
{"messages":[{"role":"user","content":"Your task is to translate a text in JSON format into Spanish and return the text in valid JSON format. You should not mix the values of different keys into one. Here is the JSON string to translate: {\"11\":\"\",\"12\":\"\",\"13\":\"\",\"14\":\"\",\"0\":\"\",\"1\":\"\",\"2\":\"\",\"3\":\"\",\"4\":\"\",\"5\":\"\",\"6\":\"\",\"7\":\"\",\"8\":\"\",\"9\":\"\",\"10\":\"\"}"}],"model":"gpt-4o"}
{
  "id": "chatcmpl-9RAoG8co42I92DWoprDWrdKbeOrKA",
  "object": "chat.completion",
  "created": 1716263436,
  "model": "gpt-4o-2024-05-13",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Here's the translated JSON string:\n\n```json\n{\n    \"11\": \"\",\n    \"12\": \"\",\n    \"13\": \"\",\n    \"14\": \"\",\n    \"0\": \"\",\n    \"1\": \"\",\n    \"2\": \"\",\n    \"3\": \"\",\n    \"4\": \"\",\n    \"5\": \"\",\n    \"6\": \"\",\n    \"7\": \"\",\n    \"8\": \"\",\n    \"9\": \"\",\n    \"10\": \"\"\n}\n```"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 81,
    "completion_tokens": 87,
    "total_tokens": 168
  },
  "system_fingerprint": "fp_729ea513f7"
}

(RuntimeException) java.lang.RuntimeException: JSON Object expected.

**Comment by xulihang** [comment]
It seems that it returns a malformed JSON. You can try to modify the batch prompt in the preferences to make it work.

**Comment by xulihang** [comment]
I just remembered that I had fixed this problem before. Try to use the updated plugin here: https://github.com/xulihang/ImageTrans-docs/issues/554#issuecomment-1974779290

**Comment by ztench** [comment]
this problem was solved, but when in translation assist the model changes to gpt-3.5-turbo-0125 and does not stay in gpt-4o-2024-05-13.
![Captura de pantalla 2024-05-21 001224](https://github.com/xulihang/ImageTrans-docs/assets/77814259/bc869e7e-5f61-47aa-94c0-8705fc95746d)
![Captura de pantalla 2024-05-21 001410](https://github.com/xulihang/ImageTrans-docs/assets/77814259/11133b89-def7-4c9b-8343-d4d59146d8b1)

**Comment by xulihang** [comment]
I forgot to set the model in the one-sentence translation mode. Please use the following plugin which has this fixed.

[chatGPTPlugin.zip](https://github.com/xulihang/ImageTrans-docs/files/15384886/chatGPTPlugin.zip)

**Comment by ztench** [comment]
now working, thank you

**Comment by xulihang** [comment]
The ChatGPT plugin bundled in ImageTrans has been updated as well.
