### ISSUE TITLE
关于几个气泡检测模型

### ISSUE THREAD

**Issue by whyiskey** [xulihang/ImageTrans-docs#654]
开发者大大你好，我有几个关于气泡检测的疑问：
1软件默认使用在线气泡检测，我是不是可以认为在线检测模型性能碾压离线啊，还是说在线的综合性能要好一些？
2我看到软件根目录自带model.cfg/json/weight三个文件，是自带日漫气泡检测模型吗
3韩语离线只有onnx和json两个文件，如果想要启用该模型需要将文件内的原json替换，并且model.cfg/weight文件删除吗？反之启用日语模型需要删除onnx吗？
4韩语离线表现会比在线识别性能出色吗？
谢谢

**Comment by xulihang** [comment]
在线的对中文漫画的效果好一点，我主要基于中文漫画训练的。

离线模型是针对不同漫画进行训练的，效果可以更好。

直接替换就行，不用删。模型参数和路径已经写在json文件里了。

可以把模型文件放在项目文件夹里，这样可以每个项目对应一种模型。

**Comment by xulihang** [comment]
想要最贴合自己要翻的漫画的效果的话，我建议自己去训练：https://www.basiccat.org/zh/how-to-train-yolov8-object-detection-model/

**Comment by whyiskey** [comment]
> 直接替换就行，不用删。模型参数和路径已经写在json文件里了。

那如果两个文件并存的话应该如何指定模型啊，比如当我项目是日漫的话我应该怎么做确保现在的模型不是韩漫的气泡？

> 可以把模型文件放在项目文件夹里，这样可以每个项目对应一种模型。

这个可以展开说下吗，是吧模型放到.itp文件同目录里面还是怎么样啊


如果可能的话以后可以在这个界面添加一个指定路径或者模型选取的bar吗？谢谢啦
![屏幕截图(69)](https://github.com/xulihang/ImageTrans-docs/assets/135958188/65e6deaf-b3b0-448a-9475-5870a71af520)

**Comment by xulihang** [comment]
model.json是哪个模型的就会用哪个模型。

放的话是放到项目的图片文件夹。

**Comment by whyiskey** [comment]
好的谢谢!
