### ISSUE TITLE
导出成品图错位问题

### ISSUE THREAD

**Issue by whyiskey** [xulihang/ImageTrans-docs#656]
开发者大大你好，发现了一个生成成品图片的bug，用30%大小编辑、修改、拖动文本和文本框，获得修正后的排版后，导出图片时会首先扩大缩放至100，这是会出现文本框的错位现象。比如在竖版排版中，第一列的句末省略号会被挤到下一列中，一些文字也会出现这种现象，
    ABCD...... ?
    XXXX.......      
变成了：
    ABCD...... 
    ?XXXX....
    ...
导致最后还需要重新校对一下，修正错误，主要是所见并非所得有点麻烦。
我推测是文本框大小和某一固定大小的文本块之间的空隙，被放大了，使得下一行的某些字可以挤进来导致错版
还有就是选项导出当前图片后在新版貌似自动变回之前的缩放大小了，可以让排版模式也自动勾选吗？也就是记忆选项
谢谢

**Comment by xulihang** [comment]
自动文字大小和竖排引擎会根据框的大小确定文字和在哪换行，图像素比较小可能比例切换影响比较大。

需要精细调整的话，可以启用本地样式和手动换行来确保排版结果。

**Comment by xulihang** [comment]
> 可以让排版模式也自动勾选

是导出图片后没勾选，想保持勾选状态吗

**Comment by whyiskey** [comment]
> 自动文字大小和竖排引擎会根据框的大小确定文字大小和在哪换行，图像素比较小可能比例切换影响比较大。
> 需要精细调整的话，可以启用本地样式和手动换行来确保排版结果。
主要是这样的，每一句手动换行的话会比较繁琐，一些结构明显的句子可以用标点符号（问号感叹号省略号这些）来分割，但是有些时候是需要对一个完整的句子分割的，软件自动生成的断句排版也是可用率很高的，完全取消多少有些浪费。可不可以添加一个选项使得100%显示完整的图片，需要放大就150%，200%这样？怎么做的话直接在100界面修改就不需要再缩放了，也就自然不会乱排版了

**Comment by whyiskey** [comment]
> 是导出图片后没勾选，想保持勾选状态吗
是的，不过需要这么做的主要原因是生成图错位，后期得反复进入排版界面纠错，如果一开始就输出正确的图片的话自然也就不需要记忆勾选了

**Comment by xulihang** [comment]
怎么能保证不改变换行，这个需要试验一下

**Comment by xulihang** [comment]
可以发个测试项目过来吗，这个问题还不是很好重现。

**Comment by whyiskey** [comment]
开发者大大你好这是打包文件，请查收，因为不知道那个压缩包全不全所有我就又打包了一次。内容请忽略

一个例子是7p的一个对话框“左X跑出来”，我的常用缩放是30，转变到100后就变得不是一列了
我的软件版本是2.12.3
谢谢！

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xulihang/ImageTrans-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月2日(星期天) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xulihang/ImageTrans-docs] 导出成品图错位问题 (Issue #656)





 
可以发个测试项目过来吗，这个问题还不是很好重现。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

22.zip (373.47M, 2024年07月02日 11:23 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5a373663dbbd99da3df65f084735031d19430355020500064c06555a5718530654011b555506521f550f0f5505500857590600516133310053194c0a11350c&code=a76ca512

**Comment by xulihang** [comment]
我看了下，是调整文字区域大小时给的区域有点大了，导致自动调整大小时字体变得大了，导致换行。

```json
"targetGeometry": {
    "X": 1139,
    "width": 93,
    "Y": 2024,
    "height": 299
},
```

右键清除译文位置后就表现一致了。

我建议关闭自动字体大小调整，改用统一的字体大小，就不会有这个问题了。

**Comment by whyiskey** [comment]
好的谢谢！以后我就固定字体大小啦
