### ISSUE TITLE
I get null using baidu_network for text detection.

### ISSUE THREAD

**Issue by truki20** [xulihang/ImageTrans-docs#657]
![Captura de pantalla 2024-05-31 204936](https://github.com/xulihang/ImageTrans-docs_en/assets/170079865/1957322a-02da-4b45-a94c-872252d46683)

**Comment by xulihang** [comment]
Baidu is a paid service. ImageTrans uses the free tier of baidu which has a 500/day usage limit using baidu_network.

**Comment by truki20** [comment]
could you recommend an alternative to use for English language instruction?

**Comment by xulihang** [comment]
You can use paddle ocr which is free: https://github.com/xulihang/ImageTrans_plugins/tree/master/paddleOCR

**Comment by truki20** [comment]
one more thing that has nothing to do with this but I wanted to know where I can download the spanish language pack for the program.

**Comment by xulihang** [comment]
The UI has not been translated to Spanish. But you can try to translate it by yourself: https://github.com/xulihang/ImageTrans-docs/issues/544
