### ISSUE TITLE
I can use the fonts

### ISSUE THREAD

**Issue by Suldand72** [xulihang/ImageTrans-docs#658]
I create the font style, but when I try to change it in the type mode it continues in the preset font. How can i change correctly

**Comment by xulihang** [comment]
If the text area already has a local style, then the global style will not be effective.

You can clear the styles like this:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/02389bf1-a6fd-4853-9421-d0dbe333971a)
