### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by FluoxSSRI** [xulihang/ImageTrans-docs#660]
Hi, where can I find or download updates for the program whenever they're released?
How do I find what version I am using? and what is the latest version?
Thanks in advanced

**Comment by FluoxSSRI** [comment]
How would I know what version I'm currently using and if I need to update it?

**Comment by xulihang** [comment]
Through the menu:
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/fcd8b5f7-fe01-4bc1-a4d8-b3cbacf5fe75)

**Comment by FluoxSSRI** [comment]
How would I download it? would I have to uninstall the current imagetrans and down the latest from the onedrive? or just download straight from the one drive?

**Comment by xulihang** [comment]
ImageTrans is portable. You just need to download and unzip it. If you need to keep the preferences, remember to copy `prefrences.conf` to the new folder.

**Comment by xulihang** [comment]
Plugins are bundled with ImageTrans. Generally, you don't need to update them manually.
