### ISSUE TITLE
macOS Sonoma - 14.3.1 Fails to start application

### ISSUE THREAD

**Issue by mattarainwater** [xulihang/ImageTrans-docs#661]
I had the application running successfully a few days ago, but when I tried today it just becomes unresponsive. I did a fresh install of ImageTrans-mac-x64.dmg from the OneDrive, ran the following command (after seeing the "damaged" error), but am still seeing the same issue.

`sudo xattr -rd com.apple.quarantine /Applications/ImageTrans.app`

Tried to run the .jar directly as well, but it just hangs in the terminal.
![Screenshot 2024-06-04 at 5 30 16 PM](https://github.com/xulihang/ImageTrans-docs/assets/2125151/fcbea07a-782c-45f5-ba7d-ed663e3b1ca3)

**Comment by xulihang** [comment]
Try to run this command as well:

```bash
sudo spctl --master-disable
```

In addition, if you need to run ImageTrans from Terminal, you can do this:

```bash
cd /Applications/ImageTrans.app/Contents/MacOS
./ImageTrans
```

**Comment by xulihang** [comment]
If it still does not solve the problem, install Liberia JDK and use it to start ImageTrans according to the docs's getting started part for cross-platform usage.

**Comment by mattarainwater** [comment]
Awesome, yeah - disabling gatekeeper via the following worked, thanks for the help!
`sudo spctl --master-disable`
