### ISSUE TITLE
Save Font Style

### ISSUE THREAD

**Issue by Suldand72** [xulihang/ImageTrans-docs#662]
Hi, I make the configuration of my  font style, there is a way that i can use all the fonts I make in a project to a new project?

**Comment by xulihang** [comment]
Right click on the blank area to import font styles from another project.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/33ab849b-fee6-4c00-b563-02e6756255c9)

You can also save a project as a template for future projects.

**Comment by Suldand72** [comment]
Where I can make that template?

**Comment by xulihang** [comment]
You just save the project and use it as a template.

**Comment by Suldand72** [comment]
Oh, okay. One more question. My friend is asking if there is a method where I can export all the typed images. Instead of one by one

**Comment by xulihang** [comment]
Use batch operations: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#id27
