### ISSUE TITLE
manga_ocr

### ISSUE THREAD

**Issue by Yosoroko** [xulihang/ImageTrans-docs#663]
when i want to use manga ocr, it doesn't work, how can i capture text with manga ocr? greetings

**Comment by xulihang** [comment]
You have to download mangaOCR and keep it running: https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR

**Comment by Yosoroko** [comment]
i followed all steps but i cant launch the server python3 server_manga_ocr.py, and still the ocr doesn't work, how can i fix this?

**Comment by xulihang** [comment]
What is your operating system? If you use windows, you can use the packed version.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/df418506-ead3-4f37-a0a0-a5956f7faf8f)

**Comment by Yosoroko** [comment]
thanks buddy, it worked fine, greetings
