### ISSUE TITLE
how to update my version of imagenTrans

### ISSUE THREAD

**Issue by truki20** [xulihang/ImageTrans-docs#664]
I realized that the version of imageTrans I have is old (2.10.1) and I would like to know how to update my version to the latest version which is v2.12.4.

![image](https://github.com/xulihang/ImageTrans-docs_en/assets/170079865/fdf196cb-f6e2-4c6b-ad0f-7e5640fb4532)
![image](https://github.com/xulihang/ImageTrans-docs_en/assets/170079865/21e8aa08-bde8-4727-b646-aff37fee5364)

**Comment by xulihang** [comment]
Check out this: https://github.com/xulihang/ImageTrans-docs/issues/660

**Comment by truki20** [comment]
where is the link to onedrive

**Comment by xulihang** [comment]
It is in the email sent to you after you purchased ImageTrans.

If you cannot find it, please send an email to admin@basiccat.org.
