### ISSUE TITLE
能不能把百度云的其他文件补充文件放到OD一份？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#665]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/0ba36cbd-4eb6-40c8-b097-6c77eafb528e)

老哥提前祝您端午安康

就是吧 最近有时候会租用远程主机 也就是云电脑
然后吧 百度云 您知道 的那个下载速度简直了
在云电脑下机了都未必能下完 那些文件
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c0e0324b-5277-4959-8e52-ba342284c848)

所以 能不能请您 把这些个补充文件 放到od一份

我在远程用OD下都比百度云快啊  拜托了啊

**Comment by xulihang** [comment]
这些文件github上都有对应的，可以直接下载的。onedrive我只有5gb的容量，放不下这些文件

**Comment by lhj5426** [comment]
> 这些文件github上都有对应的，可以直接下载的。_onedrive_我只有5gb的容量，放不下这些文件
呃
哈哈 谷歌云呢谷歌云有15G 应该沟了吧  

github 对 不过太分散了哈哈 嘛 行吧 
我去github的个个角落里收集下
