### ISSUE TITLE
deepl接口有问题？

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#668]
我购买了deepl API，如下设置后并未工作
![image](https://github.com/xulihang/ImageTrans-docs/assets/78189608/07681216-1c90-4b91-a54a-9c2c45116ad3)
![image](https://github.com/xulihang/ImageTrans-docs/assets/78189608/4b90a761-eac9-4f2a-ab68-2210a3738a14)
![image](https://github.com/xulihang/ImageTrans-docs/assets/78189608/a367eb8b-21d1-4f3a-8aa5-ca1d2ab439d8)

**Comment by xulihang** [comment]
我没有deepl的密钥，我记得插件前不久才更新的。可以把密钥发我邮箱admin@basiccat.org，给我测试一下吗

**Comment by hucurve** [comment]
当然可以
4802cfe2-7a86-40bb-ad2a-f827623483e6:fx






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xulihang/ImageTrans-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月9日(星期天) 晚上8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xulihang/ImageTrans-docs] deepl接口有问题？ (Issue #668)





 
***@***.***，给我测试一下吗

**Comment by xulihang** [comment]
我试了下是可以用的

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/b6b2eef0-0ca0-4a59-aae3-1c067d2cab7b)

**Comment by xulihang** [comment]
不能用的话，可以用ImageTrans.bat打开软件，显示命令行输出，看看有什么错误
