### ISSUE TITLE
买了个糟心的软件

### ISSUE THREAD

**Issue by qiyasw** [xulihang/ImageTrans-docs#669]
很麻烦，都不是不如BallonsTranslator，是差得非常多。文字识别翻译时灵时不灵，都是翻译软件，为什么BallonsTranslator就可以每次识别翻译都能成功。我以为能省事，结果事更多。想看看漫画一健就翻译的人，不要买，直接用BallonsTranslator。

**Comment by xulihang** [comment]
翻译日漫吗，这个需要自己额外配置的，网盘的补充文件里有说明，默认效果是不好。
