### ISSUE TITLE
按文档离线模型了，运行run.bat闪退，ocr和没安装时一样。

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#671]
D:\Program Files\ImageTrans\manga-ocr>. \Python3810\python. exe. \server_manga_ocr.py 2024-06-10 04:58:51. 586 | INFO manga_ocr. ocr:_init_:13 Loading OCR model from kha-white/manga-ocr-base 'HTTPSConnectionPool (host=' hugging face. co', port 443): Max retries exceeded with url: /kha-white/manga-ocr-base/resolve/ main/preprocessor_config.json (Caused by ConnectTimeoutError (<urllib3. connection. HTTPSConnection object at 0x0000017131C 5C490, Connection to huggingface. co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://hugging fa ce. co/kha-white/manga-ocr-base/resolve/main/preprocessor_config.json Traceback (most recent call last): 
File \server_manga_ocr.py"， line 34， in <module>mocr Manga0cr () 
File "D:\Program Files\ImageTrans\manga-ocr\Python3810\lib\site-packages\manga_ocr\ocr.py", line 14, in self. feature extractor = AutoFeatureExtractor. from pretrained (pretrained_model_name_or_path) 
_init_ 
File "D:\Program Files\ImageTrans\manga-ocr\Python3810\lib\site-packages\transformers\models\auto\feature_extraction_a uto. py", line 296, in from pretrained 
config_dict, = FeatureExtractionMixin. get_feature_extractor_dict (pretrained_model_name_or_path, **kwargs) 
File "D:\Program Files\ImageTrans\manga-ocr\Python3810\lib\site-packages\transformers\feature_extraction_utils.py", li ne 402, in get_feature_extractor_dict 
resolved_feature_extractor_file = cached_file( 
File "D:\Program Files\ImageTrans\manga-ocr\Python3810\lib\site-packages\transformers\utils\hub.py", line 409, in cach ed_file resolved_file = hf_hub_download ( 
File "D:\Program Files\ImageTrans\manga-ocr\Python3810\lib\site-packages\hugging face_hub\file_download.py", line 1136, in hf_hub_download 
with open (ref _path) as f: 
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Y/. cache\\hugging face\\hub\\models--kha-white--manga ocr-base\\refs\\main'

**Comment by xulihang** [comment]
目录结构是什么样的，下面这样的吗：

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/c79312fb-dca0-4a94-964d-2820466f5468)

下载的模型压缩包还有`server_manga_ocr.py`这个文件，需要替换原来的，才能把路径改成离线的模型。

还有软件最好不要放在`Program Files`目录里，可能有权限问题。

**Comment by xulihang** [comment]
下的是缓存文件还是说明第二步的模型文件？我把网盘里的说明改了，把那个下缓存的方式删掉了

**Comment by swswlg** [comment]
按更新以后也没识别
![image_3](https://github.com/xulihang/ImageTrans-docs/assets/172276973/b67d00c0-6c11-476e-8362-b29c32531419)
![image_4](https://github.com/xulihang/ImageTrans-docs/assets/172276973/4086773a-2532-4cdc-9e0d-ba3d62cec3e4)
![image_5](https://github.com/xulihang/ImageTrans-docs/assets/172276973/22e5769d-9297-4236-8afe-a7dfadf97aaf)

**Comment by swswlg** [comment]
气泡检测不全，8个会话框能检测3个

**Comment by xulihang** [comment]
漫画有图吗。离线模型要在偏好设置里启用

**Comment by swswlg** [comment]
![image_6](https://github.com/xulihang/ImageTrans-docs/assets/172276973/ad16f890-960d-4b69-a0c1-5d40a51494de)
 WinRT 不支持日语么？
![Uploading image_7.png…]()

**Comment by xulihang** [comment]
上图的气泡是可以识别的。注意放模型的时候，不要把几个模型放一起，用哪个放哪个。

WinRT需要系统在语言选项里添加日语。

这个issue主要是问mangaOCR的，这个能用了吗

其它问题建议开个新issue。

**Comment by swswlg** [comment]
用哪个放哪个怎么做？

**Comment by xulihang** [comment]
要用的气泡模型解压到软件目录

**Comment by swswlg** [comment]
用哪个模型就解压那个，能用了。
