### ISSUE TITLE
如何保存配置文件

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#672]
每次更换一个目录就需要重新创建一个临时文件。itp。里面包含了图片和所有的漫画参数设置。如果打开它在另外打开新图片文件夹，会报错没有jpg文件。但重新创建就不会出现报错。
有没有导入后可以一键删除原来的图片及识别文本框的功能呀
想问一下作者有没有什么好办法吗

**Comment by xulihang** [comment]
之前的相关issue: https://github.com/xulihang/ImageTrans-docs/issues/516

**Comment by hucurve** [comment]
ok虽然有点麻烦，但能解决问题

**Comment by xulihang** [comment]
v3.2.0加了个功能，支持配置模板：https://github.com/xulihang/ImageTrans-docs/issues/688
