### ISSUE TITLE
横向双排OCR识别可以优化一下吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#673]
老哥我使用的是 manga-image-translatorrun 这个OCR 来对正常横着的字幕进行OCR
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/c0eff8fc-473b-45ba-8de0-b8aab6155659)
 
就比如这种的  全都 是  把第二行 放在前面了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8d4780f2-8385-497f-a220-c3a676d2cba1)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/69a46dd4-18d8-4720-9708-95f67c41f739)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8550ecf7-caf6-4480-9d71-2beedf4cdadf)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/78c3b6de-d618-4807-bb25-b2b053e9b2ff)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/5ec44c14-f7ec-4c9d-b9dc-c800f42c9a12)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/2b7f0456-83a7-47ff-8aae-c80bac0390f3)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/dc130dd7-be20-4180-b299-59e496b879e5)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/3c324354-915c-41e7-b217-e1c5caf69d27)

然后 就很奇怪 有时候还正常
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/afa46742-9be4-4ecb-bafc-f57d2ba395c3)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a7dd4a68-cc0b-4192-92f3-9084f5530528)

所以  这种 情况 能够进行优化吗？

**Comment by xulihang** [comment]
我考虑在项目设置的文字合并设置里加个选项，勾选从右到左阅读的话，进行上下文字行合并时还是按照正常顺序合并文字。

**Comment by lhj5426** [comment]
> 我考虑在项目设置的文字合并设置里加个选项，勾选从右到左阅读的话，进行上下文字行合并时还是按照正常顺序合并文字。

这个现在是勾选不勾选 都会 后在在前

**Comment by xulihang** [comment]
噢，我记得之前版本已经改好了的，勾选不勾选从右到左，都可以按合并方向智能判断。我有空再具体看一下

**Comment by xulihang** [comment]
我看了下是因为你这里识别的单个区域，会直接按照默认返回的顺序合并文本，没有由软件二次排序。这个问题用屏幕阅读器时勾选左下方那个排序选项可以解决，但默认界面没这个选项。我会加个ocr的项目设置，默认进行排序

**Comment by lhj5426** [comment]
嗯 您在
https://github.com/xulihang/ImageTrans-docs/issues/553
这里 只给屏幕阅读器添加了
也就是只给了实时识别 添加了这个功能
而忘记了批量非实时性 OCR 也添加上
其他老哥 后续的迭代 哈哈

**Comment by xulihang** [comment]
加在v3.1.1里了。见项目设置的OCR设置

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/93239515-9bb6-45b8-b3a9-d5d5ccae5817)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/d0d3362c-0cdd-496f-bbd8-0073be20ef3d)
嗯 试了下  好耶 可以正确 显示了 感谢
