### ISSUE TITLE
无法新建、打开项目，会出现代码错误

### ISSUE THREAD

**Issue by qaz-000** [xulihang/ImageTrans-docs#674]
![image](https://github.com/xulihang/ImageTrans-docs/assets/172361087/86f094e4-901a-414e-a508-8d1eec3e5ddf)

**Comment by xulihang** [comment]
看起来是之前路径的记录有问题了。

把以下路径的文件清空一下：

```
C:\Users\你的用户名\AppData\Roaming\ImageTrans
```
