### ISSUE TITLE
可以增加 2个对置信度操作的功能么

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#676]
第一个就是 批量操作 的工作流里 希望老哥您 可以增加一个置信度的操作
因为直接使用 manga-image-translatorrun 识别之后是没有置信度操作的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/9644d566-aac0-454f-85fb-f81a6420ef4a)

还有一个就是能不能 置信度增加一个阈值的调整 和开关  
这个阈值 怎么理解呢 就像OCR的时候咱黑框里不是有个0.几的数值么
这个数值 在置信度里目前是不可见的 就能不能调整成可见的 低语多少 或者高于多少的才框选变黄这样的
开关就是有时候弄完了 但是 实际上  真垃圾 比 真气泡 要少 手动删了垃圾之后 。 可以关闭变黄的气泡 腰部 黄了吧唧一直挂着也不好看而要手动去 一个一个反转  反倒是不如 挂着黄框了 所以要是能有一个开关的话 就会好很多？ 

虽然老哥之前说了怎么去训练 这个 置信度的模型 并且 在最近非常贴心的增加了 可以自己训练的识别模型和调用的功能
但就算现在是有AI的辅助 有些事情 有些人 还是做不来  哈哈 所以还得拜托您

**Comment by xulihang** [comment]
加在v3.1.1了。设置加在项目设置的文字区域检测里

**Comment by lhj5426** [comment]
稍微能强那么一点 谢谢
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/65936591-c9e0-45a7-b293-3679ab88d200)
