### ISSUE TITLE
如何更改自动翻译所有区域、预翻译的网站来源？

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#677]
我希望将其调整至ChatGPT来源，但设置后依旧为deepl。难道是我设置错了？
![image](https://github.com/xulihang/ImageTrans-docs/assets/78189608/b5bc2bfb-0b59-4bd9-95e7-93d9997538c5)
![image](https://github.com/xulihang/ImageTrans-docs/assets/78189608/5eae12bc-70a8-4854-87e3-fd1585c19e27)

**Comment by xulihang** [comment]
是这样设的，我测试没问题

**Comment by xulihang** [comment]
是这样设的，我测试没问题

**Comment by hucurve** [comment]
会不会是因为gpt需要一定时间反应（我这里两秒钟以后才会返回结果）。我看即使选这一个翻译也不会正常显示，而是显示成原文的样子

**Comment by xulihang** [comment]
ChatGPT有时候的确会返回原文，没有机器翻译那么稳定。
