### ISSUE TITLE
change the gpt model to the 4th and now I get no response.

### ISSUE THREAD

**Issue by truki20** [xulihang/ImageTrans-docs#678]
![image](https://github.com/xulihang/ImageTrans-docs/assets/170079865/dd2c0115-b154-4fe3-b28d-ceef8db5bd01)
here is the evidence
![image](https://github.com/xulihang/ImageTrans-docs/assets/170079865/2c53a0ec-c3f0-4ec9-ad6f-fd4586eb01e7)

**Comment by xulihang** [comment]
I think it should be `gpt-4o`.

Related issue: https://github.com/xulihang/ImageTrans-docs/issues/651
