### ISSUE TITLE
在manga_ocr中打开server_manga_ocr.py用cuda，打开run.bat用cpu的原因？？？还需要按照https://github.com/xulihang/ImageTrans_plugins/blob/master/mangaOCR/GPU.启动gpu加速么？

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#679]
在manga_ocr中，打开server_manga_ocr.py用cuda，打开run.bat用cpu，还需要按照https://github.com/xulihang/ImageTrans_plugins/blob/master/mangaOCR/GPU.使用gpu加速么？

**Comment by xulihang** [comment]
你本地装了python了吗，那不用了。用run.bat会用打包的python，默认不支持cuda

**Comment by swswlg** [comment]
安装了，但是manga-image-translator没有用gpu。
