### ISSUE TITLE
Option 1: Install with the Prepacked Packages 是哪不对么，manga-image-translator没有用gpu。

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#680]
![image_19](https://github.com/xulihang/ImageTrans-docs/assets/172276973/4d9b301e-eac4-4fc3-abbb-58eefefaaa79)
![image_20](https://github.com/xulihang/ImageTrans-docs/assets/172276973/4a3cd4a4-db35-4349-980f-959d5fcccebf)

**Comment by xulihang** [comment]
目录里要建一个文件启用cuda，具体看说明

**Comment by swswlg** [comment]
![image_20](https://github.com/xulihang/ImageTrans-docs/assets/172276973/59a71ceb-a6ad-4641-aed1-657fd03cac6a)
建立了use_cuda，在site-packages，现在在manga-image-translator也建立，gpu没反应
![image_21](https://github.com/xulihang/ImageTrans-docs/assets/172276973/8a257fa2-2ff8-4ac5-867e-ea674861b757)

**Comment by swswlg** [comment]
按说明，日漫OCR(manga ocr)在run.bat也显示用gpu了
![image_22](https://github.com/xulihang/ImageTrans-docs/assets/172276973/2e6ab990-a981-4f1a-ab50-8621265bbcb2)
，但是同样按说明，manga-image-translator就没有。

**Comment by swswlg** [comment]
manga-image-translator加use_cuda，重新启动用gpu了
