### ISSUE TITLE
可以对单页增加快捷键工作流么

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#681]
什么意思呢

https://github.com/xulihang/ImageTrans-docs/assets/30548000/d51e850d-5616-4111-a464-6f5b4e68f7cf

老哥
视频里 第一次是使用了批量
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/542b31b0-01ee-421e-8879-6680cd776877)
识别的区域
然后因为软件不完美无法做到百分之百不漏 不丢 或者不多识别
所以人工检测这步骤目前少不了
然后 就来到了问题的主旨
我现在是通过
按键映射把 翻页什么的放在左手wasd的位置上 不动
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/47f2212b-aef0-4a31-8655-352a419cdf8e)

然后 把 这几个单页识别的快捷键做成悬浮按钮来用
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/36168043-33d9-486c-b005-e1205894045f)

但是 一次 两次行 这个 页面多了每次都得按个 2 3次行为  还是有点麻烦的
所以就在想 您能不能 给单页也做一个工作流 并且 免询问的 而且可以设置快捷键的
这样比如 可以拼2个快捷键 一个自然场景检测+OCR 一个 单页气泡识别+OCR
这样的
 这样 一键就搞定个动作 
 现在这样 遇到了一个一个点 有点小麻烦 
 要是有漏检测的功能 好像没有这种功能... 
 
 就是退而求其次  ocr的时候不弹出 那个 询问 时间的框一能强一点

**Comment by lhj5426** [comment]
其实我在想这个建立文本框后ocr
不适用于？ 单页自动识别上么
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/81af375b-bb99-4fb2-ba4d-44cf1e44a9d7)

**Comment by lhj5426** [comment]
其实主要难受的是 我无法得知 具体什么时候 气泡 或者自然场景识别完 每页内容不一样 识别结束的时间也不一样
不然用鼠标录个宏大概就解决了    就不需要麻烦 老哥您了

**Comment by xulihang** [comment]
总结下就是工作流可以自定义几个，然后提供快捷键直接调用来处理单张图，这个是可以加的，优先级不高

ocr时间间隔设置可以在项目设置的批量设置里设好，就不会再询问了。

建框后ocr只适用于手动建框

**Comment by lhj5426** [comment]
> 总结下就是工作流可以自定义几个，然后提供快捷键直接调用来处理单张图，这个是可以加的，优先级不高
> 
> ocr时间间隔设置可以在项目设置的批量设置里设好，就不会再询问了。
> 
> 建框后ocr只适用于手动建框

嗯  总结的到位  OCR间隔 放在设置里 其实就行 
不敢代表 所有用户 就说我自己 用了这么长时间 就没怎么调整过这个OCR的时间  几乎就是默认

**Comment by lhj5426** [comment]
因为已经自己跑训练模型了所以以后应该不会再出现经常遗漏这么多的情况了 所以 先关闭了 感谢老哥
