### ISSUE TITLE
I can't download the tesseract folder because baidu asks me for an account and I can't create it, could you put it in a drive to download it?

### ISSUE THREAD

**Issue by truki20** [xulihang/ImageTrans-docs#683]
![image](https://github.com/xulihang/ImageTrans-docs/assets/170079865/b3099118-04cb-42f2-9369-79eed4213a05)

**Comment by xulihang** [comment]
You can download tesseract-ocr using this link: https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-5.4.0.20240606.exe

Then set up the path to `tesseract.exe` in preferences.

**Comment by truki20** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/170079865/7de1dc00-441a-4777-b1a7-fdbaa3d2f4ed)
I have already done so but still no response from OCR or have I made a mistake?

**Comment by xulihang** [comment]
You have to run the exe to install.

**Comment by truki20** [comment]
I'm ready and it generated a folder with files, now I have to choose the one that says winpath?
![image](https://github.com/xulihang/ImageTrans-docs/assets/170079865/6f846b25-1471-4a70-8a7e-76c097f38ced)

**Comment by xulihang** [comment]
Choose `tesseract.exe`.
