### ISSUE TITLE
放在项目目录下的模型不支持复杂路径

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#685]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/aff38f79-92b1-46b1-b6cd-63bb19d9645e

老哥如视频演示 
分别在
O:\BTQB\shengrouben\(同人誌) [聖華快楽書店] 姫騎士アリシアの受難 ―淫乱サキュバスは姫騎士の身体を乗っ取りたい―\本篇\111
O:\BTQB\shengrouben\testmod
左右 2个路径 下放入 模

https://github.com/xulihang/ImageTrans-docs/assets/30548000/9a5584af-c52e-4a26-9736-9bcd6ba66886

型 然后 左边的在项目偏好里 启动离线模型会显示找不到模型
就是不去动 这里 直接识别也 识别不到内容的因为 确实找不到模型

右边的简单路径 和左边内容是完全相同的
但是因为 路径简单 所以 可以识别到 离线模型

这个路径问题可以优化么
因为。 国外漫画嘛 漫画文件夹 难免都是日文 啊 括号啊 方括号 这样的

**Comment by xulihang** [comment]
目前模型是直接根据路径读取的，但OpenCV不支持unicode路径。我看它有直接从字节读取的方法，应该可以解决这个问题：https://docs.opencv.org/4.9.0/javadoc/org/opencv/dnn/Dnn.html#readNetFromDarknet(org.opencv.core.MatOfByte)

**Comment by xiaobaiyigebudongjishu** [comment]
老哥我昨天说话是有什么冒犯到您了么
![image](https://github.com/xulihang/ImageTrans-docs/assets/132572152/72d2f7f0-e73d-42a0-b2d2-07ec685fae89)
为什么 在您的仓库无法发言了呢。。
如果冒犯到您了我跟你道歉能给我解封吗

**Comment by lhj5426** [comment]
> 目前模型是直接根据路径读取的，但OpenCV不支持unicode路径。我看它有直接从字节读取的方法，应该可以解决这个问题：https://docs.opencv.org/4.9.0/javadoc/org/opencv/dnn/Dnn.html#readNetFromDarknet(org.opencv.core.MatOfByte)*

希望能够可以解决现在 感觉放在软件目录下 不走这个模型呢
放在 图片和想目录下 到是真走 而且识别速度很快 就是现在得要么把图片复制到一个路径去识别
要么就把原始图片文件夹目录改名 反正都是不太方便
这两天跑模型测试就是来会折腾图片到另外一个文件夹里

换了个浏览器又能评论了？

**Comment by xulihang** [comment]
路径问题我已经解决了。

不能评论估计是因为网络问题

**Comment by lhj5426** [comment]
嗯嗯，好耶，
我还以为是昨天发言是不是有什么不太文明的地方冒犯到您了哈哈，原来是网络的锅 期待新版……

**Comment by xulihang** [comment]
v3.2.0修复了

**Comment by CarpeDiem1976** [comment]
很有帮助
