### ISSUE TITLE
可否增加clova api的链接数

### ISSUE THREAD

**Issue by whyiskey** [xulihang/ImageTrans-docs#686]
如题，我想要同时使用两个api和url地址，我尝试着复制一份plugin的插件但是貌似不行，能不能加一个类似于clova1，clova2这种

**Comment by xulihang** [comment]
韩语ocr的话，我明天会更新一个韩国公司发布的叫pororo的ocr，可以对比下效果

**Comment by xulihang** [comment]
韩语ocr的话，我明天会更新一个韩国公司发布的叫pororo的ocr，可以对比下效果

**Comment by xulihang** [comment]
Pororo OCR: https://github.com/xulihang/ImageTrans_plugins/tree/master/pororoOCR

**Comment by whyiskey** [comment]
> 为什么要用两个api，因为请求限制吗? 这个需要自己用b4j改代码，把名字改了然后编译个新的插件

主要是想要试一试clova的日语服务，但是好像每个domain下貌似只能勾选一个语言..可以简单说下怎么用b4j软件吗

**Comment by xulihang** [comment]
我好久不用clova了，之前是有个韩国用户给我提供的账号，现在没有办法测了。我记得是可以同时用多种语言的。

插件我编了一个：
[clova2.zip](https://github.com/user-attachments/files/16014989/clova2.zip)

**Comment by whyiskey** [comment]
> 插件我编了一个： [clova2.zip](https://github.com/user-attachments/files/16014989/clova2.zip)

感谢！插件很好用没有任何问题
