### ISSUE TITLE
关于模型读取的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#687]
哥 我昨天发现了个新的打标工具可以直接加载模型
验证读取 就像咱it 直接识别气泡一样
然后我按照
https://github.com/CVHub520/X-AnyLabeling/issues/469
这里设置加载了自定义模型
加载之后发现 咱it在读取模型上是不是有问题？

https://github.com/xulihang/ImageTrans-docs/assets/30548000/010d5d9f-2d64-4b81-b51d-1bc277865c44

https://github.com/xulihang/ImageTrans-docs/assets/30548000/9f3dc3b4-1339-4172-84a5-03d3fae620ab

https://github.com/xulihang/ImageTrans-docs/assets/30548000/4ba3eacf-6a86-458b-8440-ccf1a3c855ef

我用了500张纯文字图训练的 纯文字专精的模型
训练到250轮的时候提示我说没有提升了
然后我用IT跑 还是有各种问题
但是我换到这个 新找到的 
https://github.com/CVHub520/X-AnyLabeling
打标工具并加载模型 一对比发现 在打标工具上可以识别到的
但是在it上就无法识别到 或者识别错误

**Comment by xulihang** [comment]
别的模型参数可能不一样，要自己修改model.json进行适配。

```json
{
  "width":640,
  "height":640,
  "model":"model.onnx"
}
```

**Comment by lhj5426** [comment]
、

> 别的模型参数可能不一样，要自己修改model.json进行适配。
> 
> ```json
> {
>   "width":640,
>   "height":640,
>   "model":"model.onnx"
> }
> ```

是要按照 这种yaml 文件来修改吗？
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/77df077f-566b-4aba-8a78-cbe74b89cd47)

**Comment by xulihang** [comment]
ImageTrans是使用OpenCV的DNN模型去推理的，和其他工具的引擎不是完全一样的。

**Comment by lhj5426** [comment]
> ImageTrans是使用OpenCV的DNN模块去推理的，和其他工具的引擎不是完全一样的。

啊这抱歉 我就不太懂了
现在就是训练模型没有提升 但是 读取有缺陷
要不要我把模型发给您 看看？

**Comment by xulihang** [comment]
把图和模型发过来我看下

**Comment by lhj5426** [comment]
> 把图和模型发过来我看下
[best.zip](https://github.com/user-attachments/files/15935169/best.zip)


[0003.zip](https://github.com/user-attachments/files/15935170/0003.zip)


[0008.zip](https://github.com/user-attachments/files/15935171/0008.zip)

[0039.zip](https://github.com/user-attachments/files/15935175/0039.zip)
模型 还有 问题举例子的3张图片

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/35a3312d-27c9-4e57-81a0-a16a344524b9)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/112e69bf-0395-40f1-a68b-709e06dbf54a)
像这样虽然 有下次但是不会漏识别中间的一条 嗯麻烦 老哥给看看模型吧

**Comment by xulihang** [comment]
气泡存在重叠，软件自动过滤掉了

**Comment by xulihang** [comment]
置信度和图像预处理的也会影响结果。目前置信度是设死的，不能修改。

预处理的话，在项目设置的气泡检测设置里修改，可以对图片做缩放或者裁剪成一张张小图送去检测。

也可以通过模型配置文件指定裁剪方式，这种一般需要训练的时候就只用固定比例的图，我测试过条漫的效果还可以。

下面引用自博客：

对于条漫，我们可以使用以下配置文件，将图片裁剪为若干份宽度高度均为图片宽度的子图，高度的重叠比例是20%：

{
   "width":640,
   "height":640,
   "model":"model.onnx",
   "ratio":1,
   "width_overlap":"0",
   "height_overlap":"20"
}
对于很大的图片，也可以使用以下配置文件，使用滑动窗口，以固定的宽度高度去裁剪图片：

{
   "width":640,
   "height":640,
   "ratio":1,
   "model":"model.onnx",
   "slidingWindow":{
      "width":1600,
      "height":1600
   }
}

**Comment by lhj5426** [comment]
> 置信度和图像预处理的也会影响结果。目前置信度是设死的，不能修改。
> 
> 预处理的话，在项目设置的气泡检测设置里修改，可以对图片做缩放或者裁剪成一张张小图送去检测。
> 
> 也可以通过模型配置文件指定裁剪方式，这种一般需要训练的时候就只用固定比例的图，我测试过条漫的效果还可以。
> 
> 下面引用自博客：
> 
> 对于条漫，我们可以使用以下配置文件，将图片裁剪为若干份宽度高度均为图片宽度的子图，高度的重叠比例是20%：
> 
> ```json
> {
>    "width":640,
>    "height":640,
>    "model":"model.onnx",
>    "ratio":1,
>    "width_overlap":"0",
>    "height_overlap":"20"
> }
> ```
> 
> 对于很大的图片，也可以使用以下配置文件，使用滑动窗口，以固定的宽度高度去裁剪图片：
> 
> ```json
> {
>    "width":640,
>    "height":640,
>    "ratio":1,
>    "model":"model.onnx",
>    "slidingWindow":{
>       "width":1600,
>       "height":1600
>    }
> }
> ```

嗯 我去试试 修改一下看看

**Comment by lhj5426** [comment]
嘛 不过好像没什么帮助 还是一样无法识别
毕竟才训练了一个 diletta 会社的 接下来还得训练其他的

**Comment by xulihang** [comment]
这种长条的文字，我自己没有训练过，我给出的示例主要是气泡。所以你得自己实验了。

**Comment by lhj5426** [comment]
> 这种长条的文字，我自己没有训练过，我给出的示例主要是气泡。所以你得自己实验了。

好吧 我主要是喜欢看全彩CG 所以训练的都是用的CG图 在CG图里这种剧情全文字的过长非常的多
我自己研究研究吧   谢谢老哥
