### ISSUE TITLE
关于文字区域检测框

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#690]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/779bbc03-6a72-44da-8db9-7c7877fb4c94)
老哥 这个 检测框的创建和这个里面的数据有关系吗
我从昨天到现在训练了10个模型 上千轮
现在我发现这个检测框每次生成是越来越大
这个框 是根据什么生成的
咱们能控制这个框框生成的大小和宽度吗？

**Comment by lhj5426** [comment]
我是这样画的结果现在完全大的不可控了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/51cb4f87-2070-41e1-91a8-ec2f0d241102)

**Comment by lhj5426** [comment]
或者说能不能恳请您增加一个功能是 可以手动来批量调整这个框宽高的
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/29701a04-4bf1-44d1-92a9-f7f21766d512)
这太宽了 已经无语了 简直了这个模型识别的 对就是框的区域太大了

**Comment by lhj5426** [comment]
我以为是这里的关系把 
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/72c20c0c-9dfe-4044-950a-56902a6ad24f)
这里关了
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/a0854b5b-b7dd-44aa-b616-193cfe1e8c06)
这里删除 还是很大 好像跟这个没关系？

**Comment by xulihang** [comment]
应该是模型给出来的就是这么宽，和软件里的设置没什么关系

**Comment by lhj5426** [comment]
https://github.com/xulihang/ImageTrans-docs/assets/30548000/8ede7f5c-a3a9-429d-a1ca-520988d3f213

现在想到的 方法是 直接修改项目json的全部 宽度 然后手动位移 来达到批量缩小宽度的目的
要是可以以中心点向内缩小就好了

**Comment by lhj5426** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/1809fdbd-cd39-4773-926c-be09229082bb)
而且手动调整的 都是正数 而识别出来的都带有小数点。。而且后好几位

**Comment by xulihang** [comment]
小数点倒无所谓。增加调整功能我觉得也很难完美控制模型给出的结果

**Comment by lhj5426** [comment]
https://github.com/ultralytics/ultralytics/issues/13930 我在官方这边也是在问
