### ISSUE TITLE
检测分镜有时候会排序不准怎么办？

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#694]
就是这样
![Uploading image_15.png…]()

**Comment by swswlg** [comment]
![Uploading image_15.png…]()

**Comment by xulihang** [comment]
图看不见

**Comment by xulihang** [comment]
分镜检测目前就是很多图片不准的，算法限制

**Comment by swswlg** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/172276973/5107ca29-721d-46b0-8283-8363ff4cce75)

**Comment by swswlg** [comment]
服务器版会更准么？

**Comment by xulihang** [comment]
这张图分镜粘连的，服务器版也不行。可以用排序方式里的先纵后横进行排序

**Comment by swswlg** [comment]
先纵后横会好一些，手动建框会准。
