### ISSUE TITLE
翻译的字体有大有小有办法吗？  调整翻译字体的鼠标能在右边么？

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#695]
![image_17](https://github.com/xulihang/ImageTrans-docs/assets/172276973/c2842f94-dc8b-45fb-a8b7-47019784929c)

**Comment by xulihang** [comment]
因为从右到左排列，所以调整文本框大小我设在左边。如果从左到右，默认是右边。

这里是粗细不一，我估计是字体问题，有的字不支持加粗或者用的繁体字，不支持显示简体

**Comment by swswlg** [comment]
取消从右到左调整文本框也没变回来。
为了排序不得选从右到左，调整文本框可以都设置右边么？

**Comment by xulihang** [comment]
不是阅读顺序，是文字方向。改成竖排从左到右会在右边 从右到左的话，目前只能这样操作

**Comment by xulihang** [comment]
3.5.0修改了，现在可以用四个角去调整位置和大小
