### ISSUE TITLE
关于导出翻译

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#696]
我尝试使用导出供翻译的文档翻译，再倒入会txt。明明行数是一致的，不知道为什么还会报错
![微信截图_20240627212149](https://github.com/xulihang/ImageTrans-docs/assets/78189608/c13d59d1-c641-49e0-811e-79a418f4cdef)
![微信截图_20240627212330](https://github.com/xulihang/ImageTrans-docs/assets/78189608/252d98e9-18be-4b2c-b89b-496d9a373b41)

**Comment by xulihang** [comment]
不是直接替换文本。要把译文放在第二列。原文和译文用tab分隔。

**Comment by lhj5426** [comment]
为了 方便 查看 个人建议 把 TXT转成 EXCEL
 
 提供一个我一直在使用的python 脚本
 ```
 #  运行不了 安装 pip install openpyxl


import sys
import os
import openpyxl

# 检查是否拖放了文件到脚本上
if len(sys.argv) > 1:
    input_files = sys.argv[1:]
else:
    print("请拖放一个或多个文件到脚本上。")
    sys.exit(1)

# 遍历每个输入文件，生成相应的 Excel 文件
for input_file in input_files:
    # 检查输入文件是否存在
    if not os.path.isfile(input_file):
        print(f"文件 '{input_file}' 不存在。")
        continue

    # 设置输出文件名为输入文件名，扩展名改为 '.xlsx'
    output_file = os.path.splitext(input_file)[0] + '.xlsx'

    # 创建一个新的 Excel 工作簿
    workbook = openpyxl.Workbook()
    sheet = workbook.active

    # 写入表头
    header = ['Original Text', 'Initial', 'Machine translation', 'Better translation', 'Best translation']
    sheet.append(header)

    # 逐行读取输入文件，并将每一行的内容写入 Excel 文件的相应列
    with open(input_file, 'r', encoding='utf-8') as file:
        lines = file.readlines()
        for line in lines:
            line = line.strip().split('\t')
            sheet.append(line)

    # 保存 Excel 文件
    workbook.save(output_file)

    print(f"已生成 Excel 文件 '{output_file}'.")

print("所有文件处理完成。")
```
 直接把 TXT 用拖拽的方式 拖拽到PY文件上就行

然后弄完 再转回 TXT 也是有脚本
···
import pandas as pd
import os
import sys

# 通过命令行参数获取拖拽的文件路径列表
file_paths = sys.argv[1:]

for file_path in file_paths:
    # 读取 Excel 文件
    df = pd.read_excel(file_path, header=None, usecols='A:C')
    
    # 去除空行
    df.dropna(how='all', inplace=True)

    # 获取文件名(不包含扩展名)
    file_name = os.path.splitext(os.path.basename(file_path))[0]

    # 构造保存的文本文件名
    txt_file_name = f'{file_name}.txt'

    # 从第二行开始检查 B 列是否为空
    if df.iloc[1:, 1].isnull().all():
        # 如果 B 列从第二行开始全为空,则使用 A 列和 C 列
        df_selected = df.iloc[1:, [0, 2]]
    else:
        # 否则,使用 A 列和 B 列
        df_selected = df.iloc[1:, [0, 1]]

    # 将选择的数据保存为文本文件
    df_selected.to_csv(txt_file_name, sep='\t', index=False, header=False)
···
这样方便转换而且量大的话还可以使用
https://github.com/NEKOparapa/AiNiee 的t++ 格式来翻译
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/8fc57fb8-b8fc-4693-9e6d-84194eb849b2)

而且最近支持了  携带上下文和 思维链 自动总结

翻译效果 好了很多 用这个翻译 完再导入 到IT里去看 就很舒服
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/0b04b3a8-7e76-4718-a99d-dda12ac0c220)
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/bf50d888-437c-46c4-a210-04185210734f)
举个例子
![image](https://github.com/xulihang/ImageTrans-docs/assets/30548000/4594c1bb-bfa4-4771-8c40-c310cb06a980)
