### ISSUE TITLE
I need help getting the server for the extension to run.

### ISSUE THREAD

**Issue by Swerve1234** [xulihang/ImageTrans-docs#698]
Hey,
Im not sure what Im missing, but I cant connect to the server.when I type the server adress  in the browser im getting an error.
I think I have all the requirements installed but mabey Im missing smth.
So could you please tell me step by step what I am supposed to do to get the server for the extension running.
thank you!

**Comment by xulihang** [comment]
It is okay if you encounter an error about the certificate being expired, you just need to trust the website.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/4602387a-3389-4f15-b08c-b22b41314f7c)

<https://local.basiccat.org:51023/>

**Comment by Swerve1234** [comment]
thats not what im getting 
here:
![Screenshot 2024-06-29 100651](https://github.com/xulihang/ImageTrans-docs/assets/174135705/f3c3bba8-2c38-4719-9e7c-ab7447f6746b)

**Comment by Swerve1234** [comment]
unfortunatly

**Comment by xulihang** [comment]
Are you following the instruction here? https://github.com/xulihang/ImageTrans_chrome_extension

Please make sure you've followed the steps.

**Comment by Swerve1234** [comment]
yeah i think so.

**Comment by Swerve1234** [comment]
So I did buy image trans and installed it and also got the server.jar

**Comment by xulihang** [comment]
You have to start the server in ImageTrans.

**Comment by Swerve1234** [comment]
oh i also did that

**Comment by Swerve1234** [comment]
are there any other requirement for imagetrans apart from this jre thing?

**Comment by xulihang** [comment]
Please use powershell to start the server and check out the error message.

```
cd ImageTrans
./jre/bin/java -jar ImageTrans_wsServer.jar
```

**Comment by Swerve1234** [comment]
okay

**Comment by Swerve1234** [comment]
quick question cd imagetrans means i need to cd to the directory where imagetrans is right?

**Comment by xulihang** [comment]
Right.

**Comment by Swerve1234** [comment]
nice thank you

**Comment by Swerve1234** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/4e9dcd9b-a9b7-45f2-aaf2-a30f54e8df16)
thats weird so it says translated:
the system couldnt find the given path
or smth like that

**Comment by Swerve1234** [comment]
but i do have the server.jar
![Screenshot 2024-06-29 103547](https://github.com/xulihang/ImageTrans-docs/assets/174135705/c577fa56-eaed-4598-9d13-adedaf67e1d7)

**Comment by xulihang** [comment]
You missed the `.` in `./jre/bin/java`

**Comment by Swerve1234** [comment]
okay are these seperate commands?

**Comment by xulihang** [comment]
No. You've entered the single command wrong.

**Comment by Swerve1234** [comment]
okay

**Comment by Swerve1234** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/7e8ca45d-4f0a-4fd2-a507-2422a64c5f5f)
hope i got it right 
it says: the command . wasnt found

**Comment by xulihang** [comment]
Try this: 

```
.\jre\bin\java -jar ImageTrans_wsServer.jar
```

**Comment by Swerve1234** [comment]
ah okay now:
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/d4f82d75-c28b-4234-9b8d-3ab78be0eea0)

**Comment by xulihang** [comment]
I forgot to add arguments. Try this

.\jre\bin\java --add-opens java.base/sun.security.x509=ALL-UNNAMED -jar ImageTrans_wsServer.jar

**Comment by Swerve1234** [comment]
okay I now got a super long response:
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/9664fd3d-8b22-4f95-83fa-6e15104fae3f)

**Comment by Swerve1234** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/a2a80c44-8798-4f96-88b4-d1d731431ded)

**Comment by xulihang** [comment]
It seems that the port 51042 is used by another process so the server cannot start.

**Comment by Swerve1234** [comment]
oh i still had the server running maby thats why

**Comment by Swerve1234** [comment]
turned it off and now:
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/6a8ef3ba-8883-4d72-ab95-c43ff3e4849b)

**Comment by xulihang** [comment]
Can you visit https://local.basiccat.org:51043/ or https://127.0.0.1:51043/

**Comment by Swerve1234** [comment]
i can only visit this one 
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/abe13aeb-04e5-423c-8536-d37d321d4efd)

**Comment by xulihang** [comment]
This seems a dns issue.

You can change the URL in the extension's options to `https://127.0.0.1:51043`:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/676cee96-5721-45c6-80f2-37c1f49832c5)

Remember to visit https://127.0.0.1:51043/index to allow accessing it if it fails to connect to ImageTrans,

**Comment by Swerve1234** [comment]
so id changed the url but its sadly still not working
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/16f0db5a-54bc-4ed3-a254-ab62d9a68841)

**Comment by xulihang** [comment]
You can press F12 in the browser to check out the error message.

**Comment by xulihang** [comment]
I just tried mangadex. This site is supported.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/0b6e8eee-0387-40a0-ba66-e601010c865a)

**Comment by Swerve1234** [comment]
Im actually on that site aswell right now lol haha
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/16d6c69c-198e-4084-9eef-ca704cc18fb7)
thats what im getting

**Comment by xulihang** [comment]
Then follow the step 4 (Install and enable Allow CORS) in the instruction to bypass the CORS problem.

**Comment by Swerve1234** [comment]
okay

**Comment by Swerve1234** [comment]
i cant use it somehow 
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/afb71a27-ac33-4a04-af5b-a161e2b2618c)

**Comment by Swerve1234** [comment]
oh i got it now just had to turn it on

**Comment by xulihang** [comment]
Just turn it on.
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/6d512bc5-515c-4e13-9318-d5504647fa91)

**Comment by Swerve1234** [comment]
okay now im getting bad result is imagetrans running correctly

**Comment by Swerve1234** [comment]
maby that helps
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/1afa3151-e0e5-48b0-9892-8137179e1b69)

**Comment by xulihang** [comment]
Then it is about ImageTrans. Turn off other ImageTrans process and the server. Use `ImageTrans.bat` to start ImageTrans, start the server from ImageTrans and create a new project to get ready for translation.

Then use the extension to translate.

**Comment by Swerve1234** [comment]
nice so translating does seem to work now. Thank you so much for that.
But I would also like to know ho I can copy the text from a panel, is that even possible?

**Comment by Swerve1234** [comment]
Im getting this again when trying to translate
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/e5c9e289-f22e-4673-a243-8e2d5f3fc70e)

**Comment by Swerve1234** [comment]
Okay I think we dont need to solve all the issues at once and Ill just take a quick breake.
Im coming back to you later.
Thank you so much though for your time and great help!!

**Comment by xulihang** [comment]
You can copy the text in ImageTrans but it is not possible in the browser directly for now.

For other questions, please open a new issue.
