### ISSUE TITLE
How can I copy the text from a panel in imagetrans?

### ISSUE THREAD

**Issue by Swerve1234** [xulihang/ImageTrans-docs#699]
Hi,
I want to copy the text from a manga panel, so that I can put it in anothert document.

**Comment by xulihang** [comment]
Have you used OCR to get the text? You can export the text to a word file.

Please read the docs first.

**Comment by Swerve1234** [comment]
I did read the docs to install manga ocr, but I think its not working correctly

**Comment by Swerve1234** [comment]
![Screenshot 2024-06-29 151714](https://github.com/xulihang/ImageTrans-docs/assets/174135705/f0b93d61-ac11-4d0e-9c6b-fbc85b631af1)
It doesnt pickup the text I think

**Comment by xulihang** [comment]
mangaocr is for Japanese. Use other OCRs which are for English.

**Comment by Swerve1234** [comment]
ah okay ill try

**Comment by Swerve1234** [comment]
![Screenshot 2024-06-29 175606](https://github.com/xulihang/ImageTrans-docs/assets/174135705/49c44bbc-2617-4405-a4cd-84992782d02f)
when I try to ocr the text it only finds gibberish
