### ISSUE TITLE
Could you please add a delete key to the text area?

### ISSUE THREAD

**Issue by bravehon** [xulihang/ImageTrans-docs#7]
https://imgdb.in/igQU

when i find error area I delete that so... 
For more convenience, I suggest putting in Delete key.

and 

when use OCR they can't recognize like ... ♡ ♥ Special Characters
how can I recognize it?

PS. this screenshot is edit strings.db en > ko

**Comment by xulihang** [comment]
You can right-click on the error area to delete it:

![image](https://user-images.githubusercontent.com/5462205/108299359-4090b780-71d9-11eb-85ca-e87763d6f286.png)

What do you mean by "Delete key"? Do you need a shortcut?

As far as I know, there is not an existing OCR which can recognize special characters. You may need to train your own OCR to do this. Fine-tuning Tesseract may be a good choice: https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00---Finetune

By the way, nice translation. I am surprised that you figured out how to do this. I haven't written anything about how to localize ImageTrans.

**Comment by bravehon** [comment]
> 오류 영역을 마우스 오른쪽 버튼으로 눌러 삭제하십시오.
> 
> ![image](https://user-images.githubusercontent.com/5462205/108299359-4090b780-71d9-11eb-85ca-e87763d6f286.png)
> 
> "키 삭제"라니? 지름길이 필요하십니까?
> 
> 내가 아는 한, 특수 문자를 인식할 수 있는 기존 OCR은 없다. 당신은 이것을 하기 위해 당신의 OCR을 훈련해야 할지도 모른다. Tesseract의 미세 조정은 좋은 선택이 될 수 있다: https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00---Finetune
> 
> 그런데, 번역 잘했어. 나는 네가 이것을 어떻게 하는지 알아내서 놀랐어. 나는 ImageTrans를 현지화하는 방법에 대해서는 아무것도 쓰지 않았다.

I know how i suggest for convenience could you add key??

I got help from an acquaintance. 
He said this program make java... so I use mysql and open string.db and use excel change word...

**Comment by bravehon** [comment]
> You can right-click on the error area to delete it:
> 
> ![image](https://user-images.githubusercontent.com/5462205/108299359-4090b780-71d9-11eb-85ca-e87763d6f286.png)
> 
> What do you mean by "Delete key"? Do you need a shortcut?
> 
> As far as I know, there is not an existing OCR which can recognize special characters. You may need to train your own OCR to do this. Fine-tuning Tesseract may be a good choice: https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00---Finetune
> 
> By the way, nice translation. I am surprised that you figured out how to do this. I haven't written anything about how to localize ImageTrans.

yes I need fast way! short cut! 

I know how i suggest for convenience could you add key??

I got help from an acquaintance. 
He said this program make java... so I use mysql and open string.db and use excel change word...

**Comment by xulihang** [comment]
I think there is a better way to remove areas. I just implemented it. See the attached video.

https://user-images.githubusercontent.com/5462205/108348428-bec27d80-721c-11eb-9826-b088b6fe46c4.mp4

**Comment by bravehon** [comment]
> I think there is a better way to remove areas. I just implemented it. See the attached video.
> 
>  quick_remove.mp4

wow amazing Is useful ! better than my suggest!

**Comment by xulihang** [comment]
Starting from v1.5.2, it is possible to use delete key to delete selected text areas.
