### ISSUE TITLE
Bad result when ocring text

### ISSUE THREAD

**Issue by Swerve1234** [xulihang/ImageTrans-docs#700]
![Screenshot 2024-06-29 175606](https://github.com/xulihang/ImageTrans-docs/assets/174135705/a38fd7ca-8c11-4534-93d4-f8e89b72bbde)
how can I get a better esult

**Comment by xulihang** [comment]
Well, you'd better upload a sample image here.

You can use PaddleOCR or Google which have a better accuracy.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/f7bf13e7-405e-4244-b599-0954c0678373)

PaddleOCR is offline and free: https://github.com/xulihang/ImageTrans_plugins/tree/master/paddleOCR

**Comment by xulihang** [comment]
How to use google: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/

**Comment by Swerve1234** [comment]
thank you for your reply.
when Im trying it, it recognizes the text much better, but it leaves out the spaces. Is there a way to fix that?
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/40a2f55e-c638-4254-8474-2117c1b10b55)

**Comment by Swerve1234** [comment]
![image](https://github.com/xulihang/ImageTrans-docs/assets/174135705/75f2b40e-c262-4f76-bed6-77ea89142ff3)

**Comment by xulihang** [comment]
Which OCR are you using?
Are you using the template to create the project? What is the language pair settings? If the source language is Japanese, it will replace the line breaks with empty string instead of spaces.

**Comment by Swerve1234** [comment]
I used the jatoen template, en to en pair and yes, the source language is really japanese. what should I be using?

**Comment by xulihang** [comment]
Set the language pair to your desired language pair like English to Germany.

**Comment by Swerve1234** [comment]
okay I will try it

**Comment by Swerve1234** [comment]
It works!! heureka thank you
