### ISSUE TITLE
Is there a shortcut to play the tts text?

### ISSUE THREAD

**Issue by Swerve1234** [xulihang/ImageTrans-docs#702]

**Comment by xulihang** [comment]
What is your desired workflow? I can add a menu item for this and you can bind a shortcut to it.

**Comment by Swerve1234** [comment]
hey, so I would like to read the manga out loud in the program, so I just dont have to read the text.
It would be great if you could do that
thank you!

**Comment by Swerve1234** [comment]
so just for closure ,I dont want to push you to do this, do you think this is possible to make?

**Comment by Swerve1234** [comment]
hey, so so could you do this?

**Comment by xulihang** [comment]
Just leave this feature request. I will implement it when I think it is worth the effort.

**Comment by Swerve1234** [comment]
okay good
I would really love this to be implemented.

**Comment by Swerve1234** [comment]
do you think though it would be possible to make a shortcut for this in autohotky just for myself?

**Comment by Swerve1234** [comment]
but I dont have any programming skill at all

**Comment by xulihang** [comment]
It is possible. You can check out the previous issue: https://github.com/xulihang/ImageTrans-docs/issues/215

Simulating a mouse click or something.

**Comment by Swerve1234** [comment]
It works! great recommendation
