### ISSUE TITLE
can you change the TTS voice model?

### ISSUE THREAD

**Issue by Swerve1234** [xulihang/ImageTrans-docs#705]
The tts currently uses the pretty annoying sounding robot voice.
can I add a voice somewhere in the folder?

**Comment by xulihang** [comment]
Currently, only the system's built-in TTS are supported.

You can export the project as a web page and then use other TTS. Check out this demo: https://comics.basiccat.org/viewer.html?uniquename=allwashedup

**Comment by Swerve1234** [comment]
that looks cool, ill try that out.
thanks!!

**Comment by Swerve1234** [comment]
Im having trouble exporting the website. when I want to name it it says that the path couldnt be found and when I dont name it it seems to go through but doest give me anything

**Comment by Swerve1234** [comment]
but they are not like the demo.
do I smh need to open them with the viewer site in the folder

**Comment by xulihang** [comment]
After export, you can see files like this:

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/7f758d51-6d2e-43bf-beb4-422a55c3569b)

Then open server, set the work folder to the output folder.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/8c6fd417-eff9-4199-93f7-3680600f274b)

Then go to https://127.0.0.1:51043/viewer.html, and you will be able to view the comics.

**Comment by Swerve1234** [comment]
thanks thats working fine btw!
