### ISSUE TITLE
DeepL plugin wrong endpoint

### ISSUE THREAD

**Issue by livefrommin** [xulihang/ImageTrans-docs#708]
I'm using DeepL Pro with paid API key, but when I try to use it with freemode=no, it gives me error `ResponseError. Reason: , Response: {"message":"Wrong endpoint. Use https://api.deepl.com"}`

**Comment by xulihang** [comment]
There is a bug of reading the settings. I've fixed it with this commit: https://github.com/xulihang/ImageTrans_plugins/commit/49f1a21e825614ab89cff663e4556f52c79bdd6b

Please use the following plugin files to overwrite the existing ones.

[deeplMT.zip](https://github.com/user-attachments/files/16242156/deeplMT.zip)

**Comment by livefrommin** [comment]
It works now, thanks
