### ISSUE TITLE
[Suggestion] Add a shortcut for deleting selected area 

### ISSUE THREAD

**Issue by thoth42** [xulihang/ImageTrans-docs#71]
## Summary

- Add a delete selected area to the existing `Adjust Selected area` options with a shortcut. (example: `Crtl + Backspace`)
- It will improve the editing flow since it will be easier to remove invalid text areas.
- Currently you need to rigth click on the box and choose delete.

|          Preview           |
| :------------------------: |
| <img src="https://user-images.githubusercontent.com/10050862/125914831-d5ef1d6c-2ac9-48b6-8eed-49a2780450a6.png" width="100%" > |

**Comment by xulihang** [comment]
Okay, I will add a shortcut key in the next version.

**Comment by xulihang** [comment]
The shortcut is added in v1.4.1.

**Comment by noku** [comment]
Thank you

**Comment by thoth42** [comment]
Thank you
