### ISSUE TITLE
掩膜调用BUG？ 还是》？

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#710]
![image](https://github.com/user-attachments/assets/9a0ea13d-88e4-4dc6-8056-41beabf89684)

![image](https://github.com/user-attachments/assets/ab0100b8-745c-41d8-bc27-404ccc2efee6)

![image](https://github.com/user-attachments/assets/6daf08bd-96fd-4ec5-8921-ffb8774729e7)
我用yolo 生成的 mask.png 图 然后我发现只有部分 使用了 
很多 如图都 不会被擦除 这个是什么问题  呀 老哥

**Comment by lhj5426** [comment]
只有重新生成
![image](https://github.com/user-attachments/assets/0d6d36cc-114a-4689-9c75-d6a2518bae92)
才会被抹除
![image](https://github.com/user-attachments/assets/dbc1e0a5-4ee0-486b-ba96-1df5d39d2f23)
但是重新生成也存在遗漏 
就是因为 知道软件生成有遗漏
才用 YOLO的检测结果生成这种 mask.png 图的 
但是却没有被使用 是颜色问题吗？

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/02d25f56-d317-4334-bce5-f47288a448b8)
没事了 用最新 版本创建一个新的项目就没事了 用以前 NNN早还是2 可能甚至是1.几版本时候一直沿用至今的项目模版
就会有这个问题 用最新版本新建的就可以识别这个  mask.png  看来我的使用新功能
![image](https://github.com/user-attachments/assets/ec810b3a-552d-4af0-ad2a-5d9b4f859632)
 创建一个 新的模版了 把 自动替换的那些个东西都移动过来

**Comment by xulihang** [comment]
mask.png需要比text-removed.jpg新，不然是不会重新生成的

**Comment by xulihang** [comment]
这样点查看翻译会一直重新生成。重新生成去文字图后，去文字图比掩膜新，这样才不会一直重新生成。所以比去文字图新几秒就行

**Comment by xulihang** [comment]
更方便一点的话，需要基于你这个掩膜生成工具写一个服务器，用externalmaskgen这个掩膜生成插件调用

**Comment by xulihang** [comment]
噢，不写插件也行。基于现有时间晚几秒就已经确保掩膜比去文字图都新了

**Comment by xulihang** [comment]
它是判断的修改时间

**Comment by xulihang** [comment]
不行的话图发过来我看一下

**Comment by lhj5426** [comment]
> 不行的话图发过来我看一下
[0005.zip](https://github.com/user-attachments/files/16283878/0005.zip)

打包了 一张 图还有yolo生成的 掩码

**Comment by lhj5426** [comment]
这个是我用来 生成 掩膜图的 脚本 
```
import cv2
import numpy as np
import os
from ultralytics import YOLO

# 获取当前脚本目录
current_dir = os.path.dirname(os.path.abspath(__file__))

# 自动找到模型文件
model_files = [f for f in os.listdir(current_dir) if f.lower().endswith('.pt')]
if not model_files:
    raise FileNotFoundError("No model file found in the current directory.")
model_path = os.path.join(current_dir, model_files[0])

# 加载模型
model = YOLO(model_path, task='detect')

# 输入文件夹路径
input_folder_path = current_dir

# 自定义颜色（默认红色）
custom_color = (5, 0, 255, 255)  # BGRA 格式

# 获取文件夹中的所有图像文件
image_files = [f for f in os.listdir(input_folder_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

# 处理每个图像文件
for image_file in image_files:
    input_image_path = os.path.join(input_folder_path, image_file)
    input_image_name, input_image_ext = os.path.splitext(image_file)

    # 进行预测
    results = model.predict(source=input_image_path, save=True, show=False)

    # 处理预测结果
    result = results[0]  # 只处理第一个预测结果

    # 获取预测的框和标签
    boxes = result.boxes.xyxy.cpu().numpy()  # 预测框
    img = result.orig_img  # 原始图像

    # 创建一个透明背景的图像
    mask_color_map = np.zeros((img.shape[0], img.shape[1], 4), dtype=np.uint8)

    # 将每个预测框应用自定义颜色
    for box in boxes:
        x1, y1, x2, y2 = map(int, box)

        # 在掩膜图上绘制矩形
        cv2.rectangle(mask_color_map, (x1, y1), (x2, y2), custom_color, thickness=cv2.FILLED)

    # 生成文件名
    mask_filename = f'{input_image_name}{input_image_ext}-mask.png'
    mask_filepath = os.path.join(input_folder_path, mask_filename)

    # 保存掩膜图像
    cv2.imwrite(mask_filepath, mask_color_map)

    print(f"Mask saved at: {mask_filepath}")

print("All masks have been processed and saved.")
```

**Comment by xulihang** [comment]
应该还是时间问题，我用掩膜编辑器保存一下后就可以了

**Comment by xulihang** [comment]
其实这个脚本和insectmask这个做的差不多，是生成一个框大小的掩膜，只不过insectmask这个生成的掩膜，向内缩了10的像素

**Comment by lhj5426** [comment]
> 应该还是时间问题，我用掩膜编辑器保存一下后就可以了



> 应该还是时间问题，我用掩膜编辑器保存一下后就可以了

我用掩膜编辑器 划拉 两下保存也没用 
甚至都把那个 什么 无字图删掉了生成的还是有字的无字图
我也醉了 主要是这个快 一口气就完事了

**Comment by xulihang** [comment]
下版本我加个设置吧，可以调整10个像素这个值。

**Comment by lhj5426** [comment]
> 下版本我加个设置吧，可以调整10个像素这个值。

嗯 行吧  谢谢了

**Comment by lhj5426** [comment]
> 下版本我加个设置吧，可以调整10个像素这个值。

对了 老哥我忘记说了 我是用
![image](https://github.com/user-attachments/assets/9bd141d4-6e1a-45e9-b737-60504c902f76)
这个方法导入的边框 数据
因为  打标软件的预测是可以调用GPU 加速处理的
比IT直接跑气泡 整体速度上快了以量级
 这个导入之后 掩码不好使的

**Comment by lhj5426** [comment]
在这种导入 边框的情况下 就是打开掩膜编辑器 划拉几下 再保存也是不行的
![image](https://github.com/user-attachments/assets/f13e2b08-1bcd-43c3-9904-90a3d945bca5)

**Comment by lhj5426** [comment]
[3.0项目模板.zip](https://github.com/user-attachments/files/16284629/3.0.zip)
这是我的 项目文件 我用这个项目文件 就不好使
但是 只要全选创建一个项目文件 就一点问题没有 可以正常消除 我觉得是这个文件的锅
但是这个文件是我下午傍晚的时候 使用3.0最新的版本创建 并重新添加 设置的 问题出在哪呢

**Comment by lhj5426** [comment]
目前 已知  这个模版里 把这一串删掉之后 可以正常消除了
        "precisionMode": 0,
        "balloon_fixed_ratio": "1x1",
        "output_format": 0,
        "sourceLang": "ja",
        "maskRadius": 0,
        "checkParagraphPositionForMerging": false,
        "doNotCheckSeparationWithText": true,
        "use_balloon_detection_model_params_first": true,
        "maxFontSize": 100,
        "position_restraint": false,
        "richtext": false,
        "checkPunctuationForMerging": false,
        "readSubFolder": false,
        "char_center_align": "[\\!\\?！？⁉‼❗❓⁇⁉‼…—~⋮0-9a-zA-Z]",
        "showTTSButton": false,
        "getClassIDAsTextStyle": true,
        "char_rotate": "[…—~]",
        "byTextArea": true,
        "invert": false,
        "resize_before_OCR": true,
        "inferSeparation": true,
        "output_with_bitmapcreator": false,
        "balloon_divide_ratio": 4,
        "generateMaskDuringSceneTextDetection": false,
        "minimumHSpan": "10",
        "flipOutputImage": false,
        "sortCriteriaForText": 0,
        "resize_before_balloon_height": 1024,
        "expand": "6",
        "useBatchSettings": true,
        "output_folder": "out",
        "reorder_for_area_ocr": true,
        "resize_before_OCR_width": 2500,
        "enable_bridge_language": false,
        "expand_for_balloon": true,
        "use_fixed_ratio_for_balloon": false,
        "defaultMaskGen": 0,
        "inpaintRadius": 3,
        "offsetThresholdBetweenParagraphLines": 20,
        "blur": false,
        这里 哪个项目影响了 无字图和掩膜 导致不擦除的？

**Comment by lhj5426** [comment]
"byTextArea": true,
        这个的锅
        
![image](https://github.com/user-attachments/assets/f0baa1f7-b851-49d5-a04a-1f5eef952dd1)

![image](https://github.com/user-attachments/assets/bd96942d-4a42-48ec-8056-ae1d9c3af46d)
这句话 勾去掉就好了 果然还是 项目文件设置的锅

**Comment by xulihang** [comment]
> 下版本我加个设置吧，可以调整10个像素这个值。

v3.4.0添加了这个偏好设置

**Comment by lhj5426** [comment]
> > 下版本我加个设置吧，可以调整10个像素这个值。
> 
> v3.4.0添加了这个偏好设置

嗯 这就去试试 谢谢

**Comment by lhj5426** [comment]
> > 下版本我加个设置吧，可以调整10个像素这个值。
> 
> v3.4.0添加了这个偏好设置

偏好设置？
![image](https://github.com/user-attachments/assets/f81099d5-1da6-48ca-9009-ca2c5e772009)
是说这里的设置 对这个插件生效了吧？
![image](https://github.com/user-attachments/assets/4a80baf2-3701-4956-b355-2682e83d18c6)
其他地方没找到

**Comment by lhj5426** [comment]
从压缩包里解压出来一个纯净版 然后 新建一个纯净的项目 看到了
![image](https://github.com/user-attachments/assets/040b071e-0b17-4138-a53b-d821173ff0af)
