### ISSUE TITLE
long text(manga-ocr) 识别问题 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#712]
https://github.com/user-attachments/assets/13d4f028-1424-47d9-8a79-573d477d3cbd

老哥如视频所示
在有些情况下 会出现长条文字 合并的时候出现双眼皮的情况
就比如 这张图的 这2个位置
![image](https://github.com/user-attachments/assets/3f3dce14-01b2-4eab-b00a-240a44202dca)

**Comment by xulihang** [comment]
长条的识别我是切分成几个短的去处理的，有可能把一个文字切分了，结果识别出重复或者错误的文字
