### ISSUE TITLE
problems with gemini 

### ISSUE THREAD

**Issue by ztench** [xulihang/ImageTrans-docs#714]
i am using gemini 1.5 flash(endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent) but it does not translate and gives me this error:

(ObservableListWrapper) [Translation]
(RuntimeException) java.lang.RuntimeException: Object should first be initialized (Label).
{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "```json\n{\n\"0\": \"O (70?\",\n\"1\": \"Tales of a Shining Sword\",\n\"2\": \"\",\n\"3\": \"Advance Chapters Available on the Website.\"\n}\n```"
          }
        ],
        "role": "model"
      },
      "finishReason": "STOP",
      "index": 0,
      "safetyRatings": [
        {
          "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HATE_SPEECH",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HARASSMENT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
          "probability": "NEGLIGIBLE"
        }
      ]
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 109,
    "candidatesTokenCount": 57,
    "totalTokenCount": 166
  }
}

(RuntimeException) java.lang.RuntimeException: JSON Object expected.
{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "```json\n{\"0\": \"\", \"1\": \"\", \"2\": \"\", \"3\": \"\"}\n```\n\nPlease provide the actual text you want to translate. The provided JSON object only contains empty strings, so I cannot translate it.  \n\nOnce you provide the text, I will be able to translate it into Spanish while capturing the excitement and martial arts elements you requested. \n"
          }
        ],
        "role": "model"
      },
      "finishReason": "STOP",
      "index": 0,
      "safetyRatings": [
        {
          "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HATE_SPEECH",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HARASSMENT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
          "probability": "NEGLIGIBLE"
        }
      ]
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 75,
    "candidatesTokenCount": 75,
    "totalTokenCount": 150
  }
}

(RuntimeException) java.lang.RuntimeException: JSON Object expected.
????
auto save

**Comment by xulihang** [comment]
Try the new plugin which removes the markdown markups:

[geminiMT.zip](https://github.com/user-attachments/files/16356270/geminiMT.zip)
