### ISSUE TITLE
离线OCR模型替代求助

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#717]
我的api使用体验失效了，原本的日语文字识别非常好用，之前使用的是有道的。
目前我希望使用离线模型替代，使用了
https://github.com/xulihang/ImageTrans-docs/issues/24
里面的yolo_darknet，效果只能说差距不小，希望作者还能推荐一下其他方法或者能有相应的参数调整
或是有什么其他好的解决方案

另外希望作者出一个一键复制拷贝翻译api的功能，因为作者实在是比较勤劳更新迭代很快，每一次都需要重新黏贴

**Comment by xulihang** [comment]
这个模型是比较老的，也不是针对日漫的。

可以在这里找到更新的模型：https://github.com/xulihang/balloon-dataset

模型也可以自己训练


偏好设置的话，更新文件时保留原来的preferences.conf就可以保留。

**Comment by hucurve** [comment]
感谢作者，找到了和之前的一位模型训练作者的对话，他分享的最新训练集表现出令人惊讶的效果
https://alumnialbany-my.sharepoint.com/personal/planetrav_alumni_albany_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fplanetrav%5Falumni%5Falbany%5Fedu%2FDocuments%2F123455678&ga=1

我强烈推荐这个123456789ABCD这个包，这是的软件的自动化程度更高了

**Comment by xulihang** [comment]
其它人训练的模型也用在ImageTrans上了吗。不过我没权限查看这个文件
