### ISSUE TITLE
problem with model gpt-4o-mini

### ISSUE THREAD

**Issue by ztench** [xulihang/ImageTrans-docs#718]
many times it does not give me the result of the translations ID->EN-> ES or it translates like this : 

![Captura de pantalla 2024-08-08 120529](https://github.com/user-attachments/assets/a7896f88-e709-4c8f-841b-053605e6e0c4)

(RuntimeException) java.lang.RuntimeException: Object should first be initialized (Label).
(MyMap) {role=user, content=Translate the following into English: ADA SEDIKIT MASALAH.}
{
  "id": "chatcmpl-9u0kRORaL5F3nD2DqZKrNbwUeZM7X",
  "object": "chat.completion",
  "created": 1723136271,
  "model": "gpt-4o-mini-2024-07-18",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "The translation of \"ADA SEDIKIT MASALAH\" into English is \"There is a small problem.\"",
        "refusal": null
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 22,
    "completion_tokens": 23,
    "total_tokens": 45
  },
  "system_fingerprint": "fp_48196bc67a"
}

pluginMTThe translation of "ADA SEDIKIT MASALAH" into English is "There is a small problem."
(MyMap) {role=user, content=Translate the following into Spanish: The translation of "ADA SEDIKIT MASALAH" into English is "There is a small problem."}
{
  "id": "chatcmpl-9u0kS5YAtHQlbt0MtMol8gUj2muwE",
  "object": "chat.completion",
  "created": 1723136272,
  "model": "gpt-4o-mini-2024-07-18",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "La traducción de \"ADA SEDIKIT MASALAH\" al inglés es \"There is a small problem.\"",
        "refusal": null
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 36,
    "completion_tokens": 24,
    "total_tokens": 60
  },
  "system_fingerprint": "fp_48196bc67a"
}

pluginMTLa traducción de "ADA SEDIKIT MASALAH" al inglés es "There is a small problem."
La traducción de "ADA SEDIKIT MASALAH" al inglés es "There is a small problem."
auto save

**Comment by xulihang** [comment]
Maybe setting the role prompt will make it perform better. Need some time experimenting.

**Comment by xulihang** [comment]
You can try to modify the default prompt in the preferences.

I just tested with this one: 

```
You are a translator who gives the translation of text without any comments. Translate the following into {sourceLang}: {source}.
```

![image](https://github.com/user-attachments/assets/c473542f-3550-4bf4-9b90-382f15753d88)

**Comment by ztench** [comment]
with the prompt already solved.
