### ISSUE TITLE
使用OCR补漏识别的是时候会导致页面错位的

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#719]
https://github.com/user-attachments/assets/8b281499-7b4a-4e0b-a467-e78ee3f8bc25

老哥如所示  首先查看1-10页没有任何问题 
然后启动MANGAOCR对 manga-image-translatorrun OCR之后剩余漏识别进行补漏OCR的时候 就会导致画面错误 
[0A3.4项目模版.zip](https://github.com/user-attachments/files/16561721/0A3.4.zip)
这是我的项目文件

**Comment by lhj5426** [comment]
只要是OCR第一次之后 再次使用全部OCR识别就会产生随机页面的错位 不管是用manga 还是用 manga-image-translatorrun OCR

**Comment by lhj5426** [comment]
在导出的文本里发现了大量的空缺发现是
![image](https://github.com/user-attachments/assets/a265cfcf-d227-4a30-b47a-bb3ed08e619f)
 
manga-image-translatorrun OCR没有识别上 重新批量识别的时候就出这个问题了

**Comment by xulihang** [comment]
页面切换太快，导致有些文字区域的位置信息没保存，加载数据失败所以图片没显示。下个版本会修复

**Comment by lhj5426** [comment]
嗯 辛苦

**Comment by xulihang** [comment]
3.6.0修复了。然后批量操作的速度也有提升

**Comment by lhj5426** [comment]
我了个去  现在 重新 补漏OCR 的时候 全图已经ocr过 的 跳过的真快啊 简直就是开了加速器  
非常感谢

顺便在这里问老哥一下 
![image](https://github.com/user-attachments/assets/c30957e4-ef75-43cf-b284-01c5b8843ff2)
 这个功能。。 我没有找到在哪里呢？

**Comment by xulihang** [comment]
> 我了个去 现在 重新 补漏OCR 的时候 全图已经ocr过 的 跳过的真快啊 简直就是开了加速器 非常感谢
> 
> 顺便在这里问老哥一下 ![image](https://private-user-images.githubusercontent.com/30548000/356810128-c30957e4-ef75-43cf-b284-01c5b8843ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTkyMzMsIm5iZiI6MTcyMzI5ODkzMywicGF0aCI6Ii8zMDU0ODAwMC8zNTY4MTAxMjgtYzMwOTU3ZTQtZWY3NS00M2NmLWIyODQtMDFjNWI4ODQzZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE0MDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmM2FkNTYwNDQ5ZTcyMTkyNjhkMmI0NTUxZjVmNTVkYTJmY2NlOGQ2ODBkMTk3NzJkNTkwY2Q0NDc4ZjczZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L4lYi3iOtWHP_FbjEVnzx13nth1zEH_1hvPTXP7jKHA) 这个功能。。 我没有找到在哪里呢？

https://github.com/xulihang/ImageTrans-docs/issues/721

一个在编辑-文字区域操作里用于所选区域，一个在自定义工作流里用于所有图片
