### ISSUE TITLE
[Suggestion] Add an option to center the text vertically and to overflow the box

### ISSUE THREAD

**Issue by thoth42** [xulihang/ImageTrans-docs#72]
## Summary

- Add an option to center the text vertically
- Add an option for the text to overflow the box.

I think this option will improve greatly the text arangement process. 
It will not be necessary to mannually adjust each box and then center it in the bubble.

(I generated an image with text of how that would look like with vertical aligment)

|           Before           |           With vertical center and overflow            |
| :------------------------: | :------------------------: |
| <img src="https://user-images.githubusercontent.com/10050862/125917832-1f197cdc-05f1-4ec6-9d16-6991f662b576.png" width="100%" > | <img src="https://user-images.githubusercontent.com/10050862/125918085-79e3eea9-6bd7-483a-abb5-7af02e6dd61f.png" width="100%" > |

**Comment by xulihang** [comment]
I cannot set the text box control to vertically centered.  There is a workaround: select all the text boxes and move them down. I will try to add an automatic operation to do this.

As for the overflow problem, it is a bit difficult. I haven't found a good way to do this.

If I can automatically add line breaks, then this is possible, which is like how point text works in Photoshop.

For example:

Translation:

```
So is my father.
```

Text with line breaks:

```
So
is my
father.
```

**Comment by xulihang** [comment]
JavaFX's TextFlow control does not have a vertical center option: https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextAlignment.html. But I think having a vertical center option is better.

I will try to implement this.

**Comment by thoth42** [comment]
thank you for looking into this 

  if both improvements were to be implemented I think it will greatly improve the workflow, since it will not be necessary to manually adjust each text area on each page.

**Comment by xulihang** [comment]
Center vertically is added in v1.4.1.

**Comment by thoth42** [comment]
Thank you

**Comment by xulihang** [comment]
Overflow is improved in v1.6.5. Check this comment with a video: https://github.com/xulihang/ImageTrans-docs/issues/190#issuecomment-1107365256

**Comment by xulihang** [comment]
The work breaking has been improved in v2.12.0: https://github.com/xulihang/ImageTrans-docs/issues/190#issuecomment-2105636353
