### ISSUE TITLE
符號顯示亂碼

### ISSUE THREAD

**Issue by sauron951** [xulihang/ImageTrans-docs#726]
![1723470884985](https://github.com/user-attachments/assets/2421ab49-b56c-4ac4-b13d-6a4bca10d77d)
如圖，剛開始的版本沒有這個問題，從2.X版本後就開始出現了，目前是3.6，這個有辦法解決嗎?

**Comment by xulihang** [comment]
之前的issue：https://github.com/xulihang/ImageTrans-docs/issues/154

我测试旧版windows10需要把系统语言改成英文

**Comment by sauron951** [comment]
請問這種情況只有這種解決方式嗎?

**Comment by xulihang** [comment]
修改后有解决吗？我没找到其它方法

**Comment by sauron951** [comment]
![1723545004150](https://github.com/user-attachments/assets/2e9b5fda-73ee-4e1f-a89e-30d78a61f4dc)
不行呢，還是有部分無法顯示

**Comment by xulihang** [comment]
这些emoji复制一份文本到这里吧，我试一下。有些可能是javafx不支持。

**Comment by sauron951** [comment]
[01.txt](https://github.com/user-attachments/files/16599712/01.txt)

**Comment by xulihang** [comment]
我试了下我这里显示都是正常的
![image](https://github.com/user-attachments/assets/f0826756-f1d8-4e2a-8c36-8cc15d0d8be3)

你的系统版本是多少？

我的是（命令行输入winver）：
![image](https://github.com/user-attachments/assets/9c9a8865-cb61-44d5-b49f-68c316667748)

**Comment by xulihang** [comment]
一般是跟编码有关的，不是很好排查。

**Comment by sauron951** [comment]
![1723554827324](https://github.com/user-attachments/assets/b3ff4b32-c937-4454-847c-8e99a5dbb9d1)
這是我的

**Comment by xulihang** [comment]
不是无解。我没有你这个系统环境去找解决方法，只有你自己去解决了。

**Comment by sauron951** [comment]
好的，謝謝
