### ISSUE TITLE
可以支持yoloV8 OBB 吗 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#727]
哥 
 就是这个 
 https://docs.ultralytics.com/tasks/obb/#models
我今天第一次尝试使用0bb 支持旋转的模型 进行 这种图片上的对话的训练
![image](https://github.com/user-attachments/assets/25f7f422-fb7b-4ebe-bc06-61dc087f843a)
龙飞凤舞的
然后简单的训练之后是可以 以倾斜形式 被推理的
 这是直接用YOLOV8 推理代码 推理的图片
 
![image](https://github.com/user-attachments/assets/c3d3ee3b-b488-423d-9d4a-c1ba754e4656)
然后 我把模型放到 ImageTrans 下进行 气泡识别 
![image](https://github.com/user-attachments/assets/858c364d-0493-4a94-8129-bbedabdea3c8)
这如图 如您所见 气泡的位置没错 就是 没识别成倾斜的
所以 如果可以的话
可以麻烦您 支持下 OBB的模型的倾斜矩形吗 因为你你看 漫画  也有些个画师很个性 就喜欢这种龙飞凤舞 张牙舞爪 不规则的把 文字写在画面上
这个 还不是拟声词。 就很讨厌

**Comment by lhj5426** [comment]
这是我用于 测试 训练的 模型 和 图片文件
https://alumnialbany-my.sharepoint.com/:f:/g/personal/planetrav_alumni_albany_edu/ErkJqHrw4q9FtR33p5xn7JIBUy7lacWM1dX5PIQS4E-kGQ?e=fKEvXE 
因为GITHUB 只支持10M 而这个文件有80 多M 所用onedrive了

**Comment by xulihang** [comment]
我试了下，用你的模型是可以的。代码变动：https://github.com/xulihang/ObjectDetector/commit/80e251faab7bff380b64460a470e5ec8fdf0dcca

不过我用官方的obb模型转换得到的onnx没成功。

**Comment by lhj5426** [comment]
> 我试了下，用你的模型是可以的。代码变动：[xulihang/ObjectDetector@80e251f](https://github.com/xulihang/ObjectDetector/commit/80e251faab7bff380b64460a470e5ec8fdf0dcca)
> 
> 不过我用官方的obb模型转换得到的onnx没成功。

呃 我是用官方下载的  yolov8s-obb.pt 进行的测试训练

**Comment by lhj5426** [comment]
> 有些坐标转换问题还挺麻烦，等我优化好了再更新

嗯 辛苦了 我先重新用OBB的 做标注和训练模型 
这种的 还挺讨厌的 过规矩矩的多好

**Comment by xulihang** [comment]
3.6.1发布了。

支持调用OBB模型

支持导出和导入OBB格式的数据

**Comment by xulihang** [comment]
另外更新了下mangaTranslator的插件，支持检测旋转角度：https://github.com/xulihang/ImageTrans_plugins/releases/download/plugins/mangaTranslatorOCRPlugin.zip

**Comment by lhj5426** [comment]
> 另外更新了下mangaTranslator的插件，支持检测旋转角度：[https://github.com/xulihang/ImageTrans_plugins/_releases_/_download_/plugins/mangaTranslatorOCRPlugin.zip](https://github.com/xulihang/ImageTrans_plugins/releases/download/plugins/mangaTranslatorOCRPlugin.zip)

嗯收到 这就去更新看看

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/4aa6dec4-cd5b-4d62-b18b-1a0667d78cb4

哈哈 太棒了     感谢 辛苦了 我再去试试 新的插件

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/aec942f0-a211-415d-abb9-e255d0bfbe62)
 这省事了 我打 倾斜标签都省事了   manga-image-translatorrun 跑一边 把多余的删掉 然后导出就可以训练了
 这两天给我苦逼的 连续2天都在手动 框选倾斜矩形    太感谢了
