### ISSUE TITLE
这种有操作的空间吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#729]
https://github.com/user-attachments/assets/c66573c6-56cf-4c60-bafe-246cceaa9f06
 
 您看
我首先 手动框选出了 倾斜区域
然后 在上面 勾选了 保留当前标签的的选项
再然后 点击 推理
推理结束之后 1 并没有删除 原来框选 的 2 其他区域也被正确的识别出来了
3出现了重复区域 这个好解决用合并 就可以了
请您评估下这种 有没有可操作空间
什么意思呢
![image](https://github.com/user-attachments/assets/6fc13dda-51d3-42be-8471-5e0816f1b2e0)
![image](https://github.com/user-attachments/assets/f777ac70-4714-48d7-92aa-a9c8c0c8ce2c)

就是 如果 这个有操作可能性的话
是不是可以让多个模型联动
比如 有的模型专注于 标准文字的识别
而比如 倾斜这种 以 【清水庵】 这个画师为代表举例子
先用标准模型跑完所有的标准文字
然后再以插件的形式跑 这种不规则 天马行空出现的 倾斜文字？
出于什么考量呢
我怕 用一个模型学习多了 可能会造成 提升拟声词识别率的问题
假如 用一个模型全部训练 是担心很有可能 会 乱识别的概率
而将模型作为 插件 使用的话 我自己  不太确定 会不会 可以避免这个问题？
因为还在做倾斜的数据标注 还没有开始训练 但是有这个担心 

然后回看 这个 
https://github.com/xulihang/ImageTrans-docs/issues/447
这里先前提到过一个

【所以能不能在批量识别的时候增加一个选项 或者设置

假如入 图片有被气泡识别 就跳过这张图片 去识别下一张】

这个 【被识别 就跳过 】但是今时不同往日

比如视频里的图片 默认识别了基础文字 但有倾斜的文字 

这样就是切换模型的时候
不需要去跳过
而是重新识别在识别的时候
 插件模型会识别自己专精 的而首轮未被识别的区域

有点混乱 我让AI总结了一下  抱歉对不起
![image](https://github.com/user-attachments/assets/633c6456-6b46-4f62-abc2-cc718de5d498)

**Comment by xulihang** [comment]
现在可以啊，只要没有重叠，另一个模型的识别结果可以添加进去

**Comment by lhj5426** [comment]
原来如此 
另外 我使用ImageTrans 实现了
![%pn_2024年08月16日18点00分57秒043](https://github.com/user-attachments/assets/182a6281-b9ce-4cfd-8ebe-9f8714f946c7)
这3个软件的 
![%pn_2024年08月16日18点08分36秒889](https://github.com/user-attachments/assets/e2558e7a-e816-43b5-a704-d04fac2494ae)
数据 互通
但是因为 转换的桥是 咱的 ImageTrans 在换行过程当中丢失了倾斜矩形的数据 哈哈
BallonsTranslator ImageTrans X-AnyLabeling 的数据互通 互相转换

**Comment by lhj5426** [comment]
本来是想 
BallonsTranslator  这边可以识别 这些 倾斜 文字 然后我微调删除 就完事了
结果转完 全是正标准矩形了 哈哈

**Comment by lhj5426** [comment]
> 现在可以啊，只要没有重叠，另一个模型的识别结果可以添加进去


https://github.com/user-attachments/assets/0f997764-9a27-4f28-b6d7-166e326dd9b8

嗯 老哥 我试了 一下  确实可以  不过
有一个 问题
就是 换另外一个模型的时候  不会直接使用
必须关闭软件重开才可以加载才可以 使用 替换的模型

**Comment by xulihang** [comment]
为了减少加载所需的时间，模型会存在内存里，切换项目或者通过工具-释放内存时才会释放，之后调用时会重新加载模型

**Comment by lhj5426** [comment]
> 为了减少加载所需的时间，模型会存在内存里，切换项目或者通过工具-释放内存时才会释放，之后调用时会重新加载模型

噢~原来可以不用关闭软件重开 晓得了 谢谢

**Comment by xulihang** [comment]
这个issue需求不明确，关闭了。

**Comment by lhj5426** [comment]
哈哈 嗯 不是需求不明
 是老哥已经解释的很清楚了 我忘记关了
 
![image](https://github.com/user-attachments/assets/668b3a3d-a7e8-4ec4-97ec-e7bade902748)
经过 上次测试之后 我现在每天在收集才C104的图片的 2个种类的 数据
一个标准 数据 一个 旋转倾斜 数据
最后会训练2个模型 一个 通吃 漫画 和 全彩CG的 
一个是专门倾斜旋转 的 
这次数据图片量大概是5万张图 哈哈
