### ISSUE TITLE
Program works on only one device

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#73]
"Each email can be used for verification on at most three devices. If you want to use it on the fourth device, you have to reset with your email."
On your getting started page it says that you can use the program on three devices and for the fourth device you have to reset with your email. But I just tried validating the program on my second device and it doesn't work, I already get the notification that I have to reset with my email.

**Comment by xulihang** [comment]
Have you used VPN or changed your network adapter? ImageTrans use the network card's MAC address as the unique device ID. If you've used VPN, then it may record more than one devices.

Try reset and use ImageTrans on the other device again.

**Comment by HeLan8** [comment]
I haven't changed my network adapter, but I use a vpn all the time. I've used the program with more than 50 vpn ip adresses from nordvpn. If I reset my email on the second device, will it still work on my first device?

**Comment by xulihang** [comment]
It should work.

**Comment by HeLan8** [comment]
Works fine on my second device and I can also sign in on my first device. Thanks for the help. I don't know if I should close this issue, I'll leave that for you to decide.
