### ISSUE TITLE
有没有统一所有文字大小的功能

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#730]
最近用的时候发现有些作品里在很多页的字体大小都是一致的，因为不同的作品中都有一个最适合的字号使得气泡中的位置看起来舒服合适。我现在是勾起来更改所有字体然后全选文本框输入字体大小的，虽然比每个调起来方便不少。但是每一页都要重复操作。想问下能否在批量流里面加一个强制调整所有文本框的字号的功能嗷，感觉会让使用上方便很多。或者有已经存在的功能没有发掘还教一下

**Comment by xulihang** [comment]
关闭自动调整字体大小，然后设个字体样式就行了

**Comment by hucurve** [comment]
wow，没想到这么简单。感谢回复
