### ISSUE TITLE
有几个问题 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#731]
![image](https://github.com/user-attachments/assets/430e3651-760e-45a9-844c-710409eae9e4)
![image](https://github.com/user-attachments/assets/cdfb0b53-5eb4-4bf3-8a0b-d4d5f20a7abe)

然后导入 有点问题 ？
 位置会 偏移？ 
 
 我刚训练了 231张图 4小时 弄了一个初始化小模型在打标软件里跑完测试导出之后
 再导入IT 就会出现 如图的偏移 然后

[labels.zip](https://github.com/user-attachments/files/16645450/labels.zip)
然后老哥 我把 测试用的项目打包 麻烦您看下

还有 
自然场景检测 好像不支持旋转矩形  

https://github.com/user-attachments/assets/e2578e44-074a-4a13-8acb-c5f871427b70
目前好像只有
![image](https://github.com/user-attachments/assets/d5410c8e-5878-410e-8824-91fa23c47b93)
 这个  支持旋转矩形 且只能
 单图
 
![image](https://github.com/user-attachments/assets/ce20e14f-7269-4fa2-a923-29d1811fce1a)

 多图
![image](https://github.com/user-attachments/assets/2726a28b-e981-4f09-9f99-257928f9b85b)

 像自然场景 识别 (只定位框选区域 先不进行OCR) 的功能 无法 进行旋转识别

**Comment by lhj5426** [comment]
反向操作 IT 标注完导出然后 打标软件导入 就是正常的

**Comment by lhj5426** [comment]
这个是刚训练的小模型文件
https://alumnialbany-my.sharepoint.com/:f:/g/personal/planetrav_alumni_albany_edu/EsSUvGsN9MREowWla1BTftYBagf_6PJbSvQWltTmWoHQbw?e=ZPv8ie
![image](https://github.com/user-attachments/assets/a1e666ca-2166-4172-b47e-390514b61422)

![image](https://github.com/user-attachments/assets/e42f4cd8-3a5f-4f14-bb7b-a0be2402d1c4)

![image](https://github.com/user-attachments/assets/918347e6-80a0-4a72-b9ad-cce30c4447b1)
![image](https://github.com/user-attachments/assets/dd7b18f5-7233-4162-909f-30342ff6545b)
一个是 导入问题 一个 是 推理问题  虽然没怎么训练 但是 2个软件的 识别 就差了有点多
特别是第三张图 哈哈 在IT里有点太乱了   您给看下吧 老哥

**Comment by xulihang** [comment]
批量OCR和单张的OCR用的代码是一样的，是可以识别旋转的。

自然场景文字的旋转支持有待添加

导入的问题，应该是我宽度高度没有算对。

推理的不同原因又不一样，有待试验。

**Comment by lhj5426** [comment]
> 批量OCR和单张的OCR用的代码是一样的，是可以识别旋转的。
> 
> 自然场景文字的旋转支持有待添加
> 
> 导入的问题，应该是我宽度高度没有算对。
> 
> 推理的不同，原因又不一样，有待试验。

嗯  辛苦您了 
今天收到其他用户小伙伴对我训练的模型的评价 很开心哈哈
![image](https://github.com/user-attachments/assets/5a11ec8c-5962-4349-ac8f-ffbccb5d4706)

**Comment by lhj5426** [comment]
![WGestures_2024年08月17日22点45分59秒229](https://github.com/user-attachments/assets/6b685975-6c5f-4ca9-8aa6-a66a310dfe4a)
![WGestures_2024年08月17日22点46分24秒658](https://github.com/user-attachments/assets/105b354b-8470-4355-9004-a07f74e074ae)

然后因为老哥您 在配置文件里增加了角度
现在 可以和 BallonsTranslator  完美互转了

![%pn_2024年08月17日22点40分22秒368](https://github.com/user-attachments/assets/24ddc1be-cf1c-48e7-b608-45cf32124472)
包括角度 嘻嘻

**Comment by xulihang** [comment]
角度之前版本就有的

**Comment by xulihang** [comment]
> 批量OCR和单张的OCR用的代码是一样的，是可以识别旋转的。
> 
> 自然场景文字的旋转支持有待添加
> 
> 导入的问题，应该是我宽度高度没有算对。
> 
> 推理的不同，原因又不一样，有待试验。

3.7.0修复了这些问题。

但用OpenCV推理的结果还是可能和用Python原版的推理结果不一样，要完全一样可以自己写个python服务器脚本，当作自然场景文字检测器去调用。

**Comment by lhj5426** [comment]
> > 批量OCR和单张的OCR用的代码是一样的，是可以识别旋转的。
> > 自然场景文字的旋转支持有待添加
> > 导入的问题，应该是我宽度高度没有算对。
> > 推理的不同，原因又不一样，有待试验。
> 
> 3.7.0修复了这些问题。
> 
> 但用OpenCV推理的结果还是可能和用Python原版的推理结果不一样，要完全一样可以自己写个python服务器脚本，当作自然场景文字检测器去调用。

嗯 修复了 也可以使用 自然场景了  谢谢老哥辛苦了

![image](https://github.com/user-attachments/assets/514fcc97-4907-4f14-ad91-2b6808e6233d)
导入
![image](https://github.com/user-attachments/assets/4e42d2de-acb2-4305-ba90-bcb09e3d3d09)
导出
都没 问题
推理不一样导入一样就行 因为毕竟程序不一样执行逻辑应该也不一样 （我瞎猜的 错了莫怪）
然后应该您应该也看到了 我的说明视频里....
哈哈  我用我的电脑 运行ImageTrans 来跑我自己训练的模型
要好几秒才能出框  所以我习惯用了python 的 那个程序使用GPU加速推理
真的我这电脑 ImageTrans  跑我自己的模型 识别 一页 用GPU的那个能跑十几页
当然这个不是  ImageTrans  的问题 是我自己CPU硬件不行的锅 没毛病
我这里没有 要怪您 怪 ImageTrans   的意思 就是我电脑配置不行的问题  
反正用习惯 了也不差 多这么一个步骤哈哈
跑的快用起来爽 就完事了 
总之感谢 这次的更新修正了这些问题

**Comment by lhj5426** [comment]
然后 
![image](https://github.com/user-attachments/assets/2a677993-5511-4776-8826-a662910f8888)
![image](https://github.com/user-attachments/assets/d787fbf2-bafa-439c-98d4-5469f8d7cef3)
![image](https://github.com/user-attachments/assets/39c6f4e0-b38f-40ac-b62b-0b4c2d3ab397)
之前有这么个小插曲
老哥的这几次更新之后 我觉得 应该可以了 应该  对得起他吃的这口安利了 哈哈
