### ISSUE TITLE
能否优化一下名称排序？

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#732]
似乎图片名称的排序如果可以的话希望能优化一下，在一般情况下确实是这么排布的
但能Windows一样还能对这种批量命名的名称排序更友好一点就更好了
只是个UI上的小建议
![微信截图_20240816213829](https://github.com/user-attachments/assets/105cf220-69cf-4f43-a1bd-761dd113c7f5)

**Comment by xulihang** [comment]
这些图是哪里来的，本来就这么命名的吗？

需要参考这个：https://github.com/SethMMorton/natsort/wiki/How-Does-Natsort-Work%3F-(1-%E2%80%90-Basics) 根据多个数字进行排序

**Comment by lhj5426** [comment]
哈哈 我一直都是
![image](https://github.com/user-attachments/assets/cd63a1b5-5d9b-481e-869f-0b554d0d4eee)
 解压完 之后先给图片重新编号然后才开始其他的

**Comment by hucurve** [comment]
> 哈哈 我一直都是 ![image](https://private-user-images.githubusercontent.com/30548000/359314508-cd63a1b5-5d9b-481e-869f-0b554d0d4eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzYxNDIsIm5iZiI6MTcyNDIzNTg0MiwicGF0aCI6Ii8zMDU0ODAwMC8zNTkzMTQ1MDgtY2Q2M2ExYjUtNWQ5Yi00ODFlLTg2OWYtMGI1NTRkMGQ0ZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEwMjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMjlhYWM0NDY2MDY0NmY4MGZmNWJhNTM5YjU4ZjE2YzA5NDUyYjY4NTIyOWViNzlmMDdhMDY0NDU4NzY5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mFM6iy0LqY4wqhkHlgEBEGmidx7pNgWxx7Je-s3jrVI) 解压完 之后先给图片重新编号然后才开始其他的

老哥你这啥软件太高级了吧

**Comment by hucurve** [comment]
> 这些图是哪里来的，本来就这么命名的吗？
> 
> 需要参考这个：https://github.com/SethMMorton/natsort/wiki/How-Does-Natsort-Work%3F-(1-%E2%80%90-Basics) 根据多个数字进行排序

我是直接图方便windows多选图片右键重命名的

**Comment by lhj5426** [comment]
> > 哈哈 我一直都是 ![image](https://private-user-images.githubusercontent.com/30548000/359314508-cd63a1b5-5d9b-481e-869f-0b554d0d4eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzYxNDIsIm5iZiI6MTcyNDIzNTg0MiwicGF0aCI6Ii8zMDU0ODAwMC8zNTkzMTQ1MDgtY2Q2M2ExYjUtNWQ5Yi00ODFlLTg2OWYtMGI1NTRkMGQ0ZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEwMjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMjlhYWM0NDY2MDY0NmY4MGZmNWJhNTM5YjU4ZjE2YzA5NDUyYjY4NTIyOWViNzlmMDdhMDY0NDU4NzY5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mFM6iy0LqY4wqhkHlgEBEGmidx7pNgWxx7Je-s3jrVI) 解压完 之后先给图片重新编号然后才开始其他的
> 
> 
> 
> 老哥你这啥软件太高级了吧

我这个是Windows系统上的第三方资源管理器  Directory Opus 对于整理文件非常优秀帮助 一键自动重命名 都是最基本的功能连连全选都是自动的
