### ISSUE TITLE
Snap to Objects

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#733]
Like in Powerpoint and Photoshop. We can show a guide for alignment and snap the selected object to another object.

![image](https://github.com/user-attachments/assets/15c50654-cbbf-460d-957b-9535aae94d53)

https://support.microsoft.com/en-us/office/work-with-gridlines-and-use-snap-to-grid-in-powerpoint-84ed7394-5b37-4326-b13d-60fbc845e096

There are several objects to snap to.

1. Source text areas.
2. Target text areas.
3. Shapes in the image (table cell, etc.).

**Comment by xulihang** [comment]
Snap and guides are added in v3.9.0.

It works when the toolbar is switched to "select" or "source image"

![image](https://github.com/user-attachments/assets/9fc091b6-34d7-4138-9b3f-d2ad4cf0b5f3)

**Comment by lhj5426** [comment]
这个功能牛掰啊PS的辅助对齐 6666
