### ISSUE TITLE
French Rookie Help please 

### ISSUE THREAD

**Issue by Snake59ex** [xulihang/ImageTrans-docs#734]
Hello, I am French and I have just acquired your software.

The French are known for their lack of education in foreign languages, and I am the perfect example of a typical French person. 🤣

I do not know Chinese and I struggle a bit with English (I manage to get by), so tutorial videos with text in Chinese are incomprehensible for me, and few are in English...
I'm a "bleue bite", The term "bleue bite" (blue dick) is a French slang expression for novice, to say that I'm a klutz.

I aim to translate *He-Man and the Masters of the Universe* into the language of Molière (French).

Could you please guide me on how to proceed (software in English mode and explanation in English) to use your software?

I also see plenty of options, features, and batches; can you provide me with their description and functionality?

Is there a plugin to set the software in French?

Looking forward to hearing from you, I wish you a pleasant day.

**Comment by xulihang** [comment]
I will try to translate the comics and write some instructions here.

About translating the UI to French, it is possible to translate it by yourself. But it is a bit complex. I will write a detailed guide for this. The previous guide: https://github.com/xulihang/ImageTrans-docs/issues/544

**Comment by Snake59ex** [comment]
I'm sorry but you write "here" ....but no link for the instructions ? 
Where is here ? 🤣

**Comment by xulihang** [comment]
"I will" means the instruction is not ready yet.

**Comment by Snake59ex** [comment]
Ok, thanks you so much for your answer and your work

**Comment by xulihang** [comment]
Automatically translated sample:


![capture001](https://github.com/user-attachments/assets/b74e298e-7d1f-414c-9ace-6b95e8bfa7eb)

**Comment by xulihang** [comment]
Here is a guide you can follow to translate ImageTrans into French: https://www.basiccat.org/how-to-localize-a-b4j-desktop-app/

**Comment by Snake59ex** [comment]
Thanks you so much.

And when the page looks like this, what to do ?

https://photos.google.com/share/AF1QipNerIX0vSdeySUnYYRb-TDsTGJihCTa1hUyzzgn63HRMpwgdOkO3Fdm_0F3kKDlPw?pli=1&key=NEQ1Z28zR21wWU44RlR3Q2tKWnJhSDd0N2QxTmp3

**Comment by xulihang** [comment]
1. Use RapidOCR to detect and recognize the text areas.
2. Create the following mask and generate the text removed images by increasing the mask kernel dilation size to 25 in project settings and use lama inpaint to restore the background.

    ![capture001 jpg-mask](https://github.com/user-attachments/assets/2beeab8b-7451-4ebd-91c8-4ebc421490b6)

    ![capture001 jpg-text-removed](https://github.com/user-attachments/assets/88834ac0-9968-4f50-895e-319d9cd67356)

3. Create a font style and add stroke to the text and get the following translated image. The font has special styles. You may need to export the image to Photoshop for further editing.

    
    ![capture001](https://github.com/user-attachments/assets/d3002e34-ab0f-4656-aa50-87b4e312b5b0)

**Comment by Snake59ex** [comment]
You're FANTASTIC !!! Thanks a lot.
I'll be back for another questions 😅
