### ISSUE TITLE
有的情况下文本修改无法保存

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#736]
我是用工作流批量翻译以后，有的时候经常会触发这个bug。有的时候多按几次保存就可以了，现在他完全不工作了。我不知道为啥以及如何解决这个问题。因为我保存了很多预设的字体，每次都是删掉itp里的img文件重复使用的，会不是配置文件哪里坏掉了呢

https://github.com/user-attachments/assets/4e751e98-2ae7-49b3-bff8-592507a5800a
附上.itp文件，因为只支持上传.txt所以修改了下后缀
[moyaki.txt](https://github.com/user-attachments/files/16690291/moyaki.txt)

**Comment by xulihang** [comment]
没看出有什么问题

**Comment by hucurve** [comment]
哥看一下视频，文字不能修改嘞

**Comment by xulihang** [comment]
你这里字号比较大， 导致文字被切掉一部分。可以把上边距改大一点
![image](https://github.com/user-attachments/assets/8a99ba8e-5605-4a6c-a7cf-a4267d11be8a)

**Comment by xulihang** [comment]
不能重现。发完整的文件发过来

**Comment by hucurve** [comment]
真是无语我一重启又好了。我好像明白是为什么了。我感觉是有没有用管理员模式的原因不能正确写入文件里吧
看来下次要右键管理员运行了
