### ISSUE TITLE
issue when trying to translate

### ISSUE THREAD

**Issue by louisgriffis** [xulihang/ImageTrans-docs#737]
when i go to auto translate or machine translate this error comes up
![Capture1](https://github.com/user-attachments/assets/ce3962a8-526c-4dc5-946b-b4308097dcb4)

**Comment by lfgriffis** [comment]
Chat gpt

**Comment by lfgriffis** [comment]
Also how do I remove the text and replace it with the translated text?

**Comment by xulihang** [comment]
ChatGPT is not available by default. You have to fill in your API key. Check out this blog: https://www.basiccat.org/ChatGPT-image-translator/

**Comment by xulihang** [comment]
> Also how do I remove the text and replace it with the translated text?

Check the "Translated" checkbox on the lower-left. See the docs for details: https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#id22
