### ISSUE TITLE
掩膜编辑后出错！

### ISSUE THREAD

**Issue by didala083** [xulihang/ImageTrans-docs#738]
编辑掩膜后总是出现这样的报错，
error: java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
StackTrace: java.lang.OutOfMemoryError: Java heap space
貌似是提示内存不足，但是内存还有空闲啊

**Comment by xulihang** [comment]
图片多大？需要给java虚拟机分配大一点的内存，可以使用imagetrans.bat去打开软件，这种方式默认会使用2gb的内存

**Comment by didala083** [comment]
图片大约3-4M吧，好像是修改了几次掩膜就成这样了，我来把bat里面的内存限制改成4G试试
