### ISSUE TITLE
unsure how to update the program

### ISSUE THREAD

**Issue by jps1226** [xulihang/ImageTrans-docs#74]
on https://www.basiccat.org/imagetrans/ it says there was a new version last month, but I don't know where to find it to update from 1.3.7

**Comment by xulihang** [comment]
I haven't implemented a mechanism to notify users of a new version. You can download the latest version from the onedrive link. I will update them when there is a new version.

**Comment by ZeroSkman** [comment]
我也找不到最新版在哪下载

**Comment by xulihang** [comment]
> 我也找不到最新版在哪下载

百度网盘里有最新版的

**Comment by ZeroSkman** [comment]
我邮箱就一个订单邮件了下载链接我下完以为没用就删了

**Comment by xulihang** [comment]
随便发封邮件到admin@basiccat.org，我再给你发一个
