### ISSUE TITLE
如果存在多模型的话 每次可以选择 使用的模型？ 

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#743]
![image](https://github.com/user-attachments/assets/1b50f852-81d9-4058-a0d6-770ed1e45a6b)

![image](https://github.com/user-attachments/assets/4c1e8f28-68b6-49a9-b5f5-beffff8449e4)

![image](https://github.com/user-attachments/assets/327a5361-c982-4b56-88f9-4ea67133af69)

![image](https://github.com/user-attachments/assets/2fb2aa58-092d-4b86-bdbc-303002197e86)
老哥如果存在多模型的话
是不是可以 
像这样 出来个小箭头选择？  或者 像这样的 弹窗 选择本次使用哪个模型？ 
![image](https://github.com/user-attachments/assets/69a5de62-c60f-4d96-b0f0-0467b09e3a58)

**Comment by lhj5426** [comment]
现在好像 只是默认使用第一个？

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/2caa4232-19b6-42a3-9a59-3dc59cb9ba43)
![image](https://github.com/user-attachments/assets/74d0668b-a6d1-4ad7-9a89-0582c9bb6888)
![image](https://github.com/user-attachments/assets/25ee4171-d503-48ea-adbc-69a6fa4d65aa)
就像这个ocr 这个弹窗 如果不勾选的 话 就是每次都弹出选择模型 
如果勾选的话就默认不弹出弹窗了

**Comment by xulihang** [comment]
一般用户应该不会需要这样做。我可以加个选项开启要不要手动选择

**Comment by lhj5426** [comment]
这个好，默认是关闭状态…  就跟现在一样开启就是高级模式…可以选择

**Comment by xulihang** [comment]
加在3.9.0里了，需要在偏好设置里启用

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/fa990f98-a249-4a83-a9b1-fc0e9136c58f)
嗯 看到了
