### ISSUE TITLE
请推荐适用于韩语、中文和英语的优秀且免费的OCR和翻译方法。Please recommend good and free OCR and translation methods for Korean, Chinese, and English languages.

### ISSUE THREAD

**Issue by NANAREDFISH** [xulihang/ImageTrans-docs#745]
Please recommend good and free OCR and translation methods for Korean, Chinese, and English languages.

Currently, most of my work involves these languages, and I would like to know which methods have proven to be effective and reliable based on user feedback.

Additionally, please note that my system does not have a GPU and only includes a CPU with 8 GB of RAM.

----------------------

请推荐适用于韩语、中文和英语的优秀且免费的OCR和翻译方法。

目前，我的大部分工作涉及这些语言，我想知道哪种方法根据用户反馈已被证明是有效和可靠的。

另外，请注意，我的系统没有GPU，只有一个CPU和8GB的RAM。

**Comment by xulihang** [comment]
You can try RapidOCR which is free and runs on your own device with good speed.

For Korean, you can also try pororo.

You can learn about different OCRs here: https://github.com/xulihang/ImageTrans_plugins

You can send some images for me to have a test.

**Comment by xulihang** [comment]
You can also try online OCRs which may have a better accuracy. You can follow this guide to use Google: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#install-the-plugin-for-imagetrans
