### ISSUE TITLE
Google Drive OCR error

### ISSUE THREAD

**Issue by CapMan47** [xulihang/ImageTrans-docs#746]
Greetings, I would be glad to have a little help. 
I recently ran out of the 90 day free trial for google ocr cloud vision and decided to switch to google drive ocr, since this guide says it's free - https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/. 
I configured everything according to it, but I get this error instead of ocr result:
java.net.SocketException: A program on your host computer has broken the established connection
Or these: Server Error
I'm doing this from Russia, so could this be the problem?
I would be grateful for help.

**Comment by xulihang** [comment]
Have you done the following?

https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#install-the-plugin-for-imagetrans

**Comment by CapMan47** [comment]
Yes. Just in case, just repeated all the steps and it didn't work.

**Comment by CapMan47** [comment]
I remembered that I tried Google Drive OCR using this guide before and everything worked. But then I switched to Google Cloud and now three months are over and I need Drive again.

**Comment by xulihang** [comment]
Well, it works on my side. Maybe you can try to use a VPN. By the way, I've refreshed the default google drive OCR's token for another 7 days.

**Comment by CapMan47** [comment]
Well you must have done something, because it started working for me. Apparently updating the token solved the problem. But is there any way I can stop being dependent on a token update on your part?

**Comment by xulihang** [comment]
This one: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#install-the-plugin-for-imagetrans

You are still using the packed plugin. You need to replace the plugin files and restart ImageTrans.

**Comment by CapMan47** [comment]
After restarting and starting OCR I was redirected to the page with access confirmation. This has never happened before. After confirmation everything worked. 
Apparently during the tests, I never restarted the application, my fault. 
Thanks for your help and quick response. I'm always amazed at how quickly you solve user issues :)

**Comment by xulihang** [comment]
Well, I didn't write to restart ImageTrans in the guide. I will add this.

**Comment by CapMan47** [comment]
Clarification on Google Drive OCR
For some reason it recognises text with a space before it, regardless of the complexity of the text. That is, in source text there is always a space before the text. Other OCRs do not have this problem. 
Have you encountered this and how can this problem be solved?
Maybe it's a problem that can't be solved at the OCR level, but is it possible to remove these spaces when exporting text to .docx or .txt? 
In fact, I've long wanted to know about text editing when exporting, is there any way to customise it? So that Source text can be changed at the export stage.

**Comment by xulihang** [comment]
You can use find and replace to remove the spaces.

You can enable regular expression to remove the spaces at the head:  `^ `.

![image](https://github.com/user-attachments/assets/bb2d7a3a-48bd-43ec-9f5d-eef99bb6c096)

**Comment by CapMan47** [comment]
For some reason the space that appears after OCR Google Drive is not read in find and replase. When I put the space myself, it is visible and can be replaced, as in your example. 
But the space that appears as a result of OCR is not found in find and replace. 
In the first screenshot, the space that OCR set - it is not shown
On the second screenshot, the space that I typed myself - it can be seen using regular expression. 
![Снимок экрана 2024-08-28 200626](https://github.com/user-attachments/assets/570cc70c-e01d-444f-a713-8a58d7eea400)
![Снимок экрана 2024-08-28 200555](https://github.com/user-attachments/assets/7653b29b-7ba3-4e41-b156-863b8b225098)

**Comment by xulihang** [comment]
This is strange.

You can uncheck `auto remove line breaks` and then replace "\n" instead.

![image](https://github.com/user-attachments/assets/264d01a9-8488-47f6-8454-bc88bed63fba)

**Comment by CapMan47** [comment]
At first I thought this helped and solved the problem, but after working for a bit I noticed that in some bubbles the text is glued together where it is moved to a new line. And this happens often enough to break the work flow.
The first screenshot shows an example of the problem. 
The second one is an example of how the text is read initially. Before the operation with */n*
![image](https://github.com/user-attachments/assets/d9a36fc3-c6fa-4189-a1af-6b9f0ed3586d)
![image](https://github.com/user-attachments/assets/8ce6ce1c-1e37-4b00-a429-5c797552b9f4)

**Comment by CapMan47** [comment]
Apparently google drive ocr doesn't add a space at the beginning, but something else. Word reads this character not as a space.
![image](https://github.com/user-attachments/assets/85fcf070-b937-4491-b9f8-2a414ef649b0)

**Comment by xulihang** [comment]
This is BOM (https://www.b4x.com/android/forum/threads/b4x-reading-a-utf-8-file-that-might-have-bom.90943/#content). 

I've updated the files to fix this. Please redo this step: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/#install-the-plugin-for-imagetrans

**Comment by CapMan47** [comment]
Yeah, everything's working as it should. Thanks a lot for your help and patience)
