### ISSUE TITLE
Scale up a translated page.

### ISSUE THREAD

**Issue by Flowfo** [xulihang/ImageTrans-docs#747]
Hi!
I want to upgrade the definition of my source pictures.
Knowing these pages were already translated by ImageTrans, is there a way to upscale the detection areas, and text positions? 
(I know that I can make the fonts biggers via the project settings).
Thanks for your answer.

**Comment by xulihang** [comment]
Use "Scale" in custom workflow.

![image](https://github.com/user-attachments/assets/53b44fbb-5ba6-4189-af54-c8e28a9f5b02)


Related issue: https://github.com/xulihang/ImageTrans-docs/issues/591
