### ISSUE TITLE
最近出来了一个 调用微信离线OCR的东西

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#748]
老哥 最近出来一个 可以离线 不登录微信的情况下使用微信OCR的 
 东西 
 

![image](https://github.com/user-attachments/assets/eac74b75-d5b5-4f20-9554-1e5fa355254d)

 https://www.52pojie.cn/forum.php?mod=viewthread&tid=1958424&page=8#pid51191107
 
 链接：https://pan.baidu.com/s/1VjRjk2uH7XClwBpfr7UtOQ?pwd=vwev
提取码：vwev
--来自百度网盘超级会员V10的分享

![image](https://github.com/user-attachments/assets/cce070b8-3075-411d-a926-7be7e778ce9d)
![image](https://github.com/user-attachments/assets/72ea2b49-0933-4687-b608-e742fe8f35cc)

![image](https://github.com/user-attachments/assets/cf3a5fbe-7ac3-40d6-b85a-8a3f44749585)
![image](https://github.com/user-attachments/assets/44bb079c-4cf8-42c3-a627-2e265db3cc61)
这个 离线的微信ocr 对日文的识别效果还是可以的 
而且对这种长条文字可以直接识别 不需要像mangocr 那样切一下 然后合并的时候有可能出现双眼皮
英文
更没什么问题
可以做成插件吗？

**Comment by xulihang** [comment]
我就不写了，有需求可以自己去写个插件。

**Comment by lhj5426** [comment]
> 我就不写了，有需求可以自己去写个插件。

好吧 这个可以自己做插件的么
