### ISSUE TITLE
Remove unselected Bug

### ISSUE THREAD

**Issue by HeLan8** [xulihang/ImageTrans-docs#75]
There seems to be an issue with the "Remove unselected" button in your new version. When I press it, nothing happens, text areas are not being removed. It still works with the previous version.

**Comment by xulihang** [comment]
It works on my computer.


https://user-images.githubusercontent.com/5462205/126350639-913ab32b-b6c7-4e3e-a85e-cbb45ff621b6.mp4

**Comment by HeLan8** [comment]
Yes, the way you did it in the video, it works for me too. But when you don't any area at all and then click on Remove unselected, nothing happens. With the previous versions I could go to a new page, click the button and all areas would have been removed.

**Comment by xulihang** [comment]
I see. I rewrote the remove unselected method in the new version. I will make it work as the previous version.

**Comment by xulihang** [comment]
But removing all text areas is not what it is designed to do. The Clear button under the text areas list is designed to do this.

**Comment by HeLan8** [comment]
That works too, I never noticed it since I've been using the remove unselected button so far, but the clear button is fine as well

**Comment by xulihang** [comment]
1.4.2 is released and it can now remove unselected areas even if there is not any areas selected.

**Comment by HeLan8** [comment]
Thank you
