### ISSUE TITLE
请问富文本怎么用？

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#751]
![2024-09-04_003650](https://github.com/user-attachments/assets/ee60c0ef-2990-4baa-94de-12bb858e2ebe)
![2024-09-04_003657](https://github.com/user-attachments/assets/c02f10c2-6e8f-48b6-8c35-029202a78cf0)

**Comment by xulihang** [comment]
是这样用代码的，具体看文档：https://imagetrans.readthedocs.io/zh-cn/latest/gettingstarted.html#id26

**Comment by swswlg** [comment]
我是按照[b]文本[/b]，但是没变粗体啊，
![364067687-ee60c0ef-2990-4baa-94de-12bb858e2ebe](https://github.com/user-attachments/assets/c7c9f405-1206-4792-8e60-7e91d038cbec)
![2024-09-04_125150](https://github.com/user-attachments/assets/2d7ef89e-12bd-44cc-b266-494d52c22350)

![Uploading 2024-09-04_125142.png…]()

**Comment by xulihang** [comment]
需要字体本身支持粗体，比如微软雅黑。

**Comment by xulihang** [comment]
v3.10.0加了竖排内横排功能。如果字体本身不支持粗体，也可以改用横排引擎支持的仿粗体。就是用起来比较麻烦点

![image](https://github.com/user-attachments/assets/374dccbf-b52b-493c-9184-955f88c72df3)

**Comment by swswlg** [comment]
要是我没有用错，字体会比原来粗些，但是还是有差距。
![Uploading 屏幕截图 2024-09-09 005529.png…]()

**Comment by swswlg** [comment]
![Uploading 屏幕截图 2024-09-09 005529.png…]()

**Comment by swswlg** [comment]
![屏幕截图 2024-09-09 005529](https://github.com/user-attachments/assets/7444a19b-9204-4f0e-9369-0df2f45468e3)

**Comment by swswlg** [comment]
是我沒用對字體，富文本很好用。
