### ISSUE TITLE
Autofont not checked but always ON (V3.9)

### ISSUE THREAD

**Issue by Flowfo** [xulihang/ImageTrans-docs#753]
Hi!
I have switched from version 2.11 to 3.9 and now my area texts behave as if the autoFont was activated.
But it's not (and I don't want to use it).
Did I do something wrong?
Thanks for you asnwer.

**Comment by xulihang** [comment]
I don't have this problem.

It may be related to this option: 

![image](https://github.com/user-attachments/assets/e5e1ba21-dc68-44df-82a1-06bc6fa53a40)

It will shrink the size if the words will be broken.

**Comment by Flowfo** [comment]
**You're right!! Thank you :)**
Another totally different question: what does the 'Drag Mode' box exactly do?

**Comment by xulihang** [comment]
You can pan the image if it is checked.
