### ISSUE TITLE
您好，请问用Sakura翻译模型如何批量翻译气泡？

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#754]

**Comment by swswlg** [comment]
Uploading freecompress-屏幕录制 2024-09-09 164716.mp4…

**Comment by xulihang** [comment]
之前试过是可以一次翻译多个句子的：https://github.com/xulihang/ImageTrans-docs/issues/554

**Comment by swswlg** [comment]
我是看了Sakura这个问答才知道怎么用的，但是我真不知道是哪有问题才会出现这样的情况。
一是一条一条识别出来的，二是批量识别出来的。
![1](https://github.com/user-attachments/assets/3202467a-08cd-4666-99a4-a8ef4c57c4f8)
![2](https://github.com/user-attachments/assets/dd467ae6-3f44-4676-a4b1-ab4e4b7422fa)

**Comment by swswlg** [comment]
![7777](https://github.com/user-attachments/assets/1ceafbc6-5397-4db4-96e1-15883e356e89)
![777](https://github.com/user-attachments/assets/2adc426f-01b6-46cb-947b-92144459782c)

**Comment by xulihang** [comment]
怎么去调用的？编辑-自动翻译所有区域，这个是支持多个句子同时翻译的

**Comment by swswlg** [comment]
![2024-09-10_205934](https://github.com/user-attachments/assets/db10f7ae-4ce6-4384-ae4a-2a2144feae39)
自动翻译所有区域

**Comment by swswlg** [comment]
换过gpt插件https://github.com/xulihang/ImageTrans-docs/issues/554

**Comment by swswlg** [comment]
![1](https://github.com/user-attachments/assets/5ae4884f-8dfa-4953-9a51-ad7b6d2aaed2)
![2](https://github.com/user-attachments/assets/22666a38-4191-4eb2-91f1-8520080e8709)
自动翻译所有区域

**Comment by swswlg** [comment]
![0](https://github.com/user-attachments/assets/d2dd47b0-8a1e-4b55-9e93-10731da6c8b4)
已经单图全文翻译了，但是辅助翻译上不显示，按条辅助翻译就显示。

**Comment by swswlg** [comment]
![Uploading 0.png…]()

**Comment by swswlg** [comment]
![0](https://github.com/user-attachments/assets/b65ee915-7fbd-4858-b85b-6283e1c59f15)

**Comment by swswlg** [comment]
![0](https://github.com/user-attachments/assets/5a9530e3-ea62-4783-a1af-09d2aa754c22)
