### ISSUE TITLE
可否增加got api的链接数 第686章

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#756]

**Comment by swswlg** [comment]
用Sakura模型就用不了gpt了，能增加gpt api的链接数么？
或者其他办法？

**Comment by xulihang** [comment]
需要我实现这个克隆插件的功能：https://github.com/xulihang/ImageTrans-docs/issues/723

**Comment by swswlg** [comment]
…没看懂，没写怎么克隆啊。

**Comment by xulihang** [comment]
实现克隆太麻烦了，我重新编了一个叫sakura的插件：

[sakuraMTplugin.zip](https://github.com/user-attachments/files/17004534/sakuraMTplugin.zip)

要自己编的话，可以看这个教程：https://www.basiccat.org/zh/how-to-write-a-plugin-for-imagetrans/

**Comment by swswlg** [comment]
非常感謝！！
