### ISSUE TITLE
文字消除不干净啊，文字掩膜和颜色操作都没有反应呢

### ISSUE THREAD

**Issue by ka7474** [xulihang/ImageTrans-docs#758]
![Uploading image.jpg…]()
![Uploading image.jpg…]()

**Comment by ka7474** [comment]
![image](https://github.com/user-attachments/assets/37c3c10a-009b-4b8a-8993-c2720c68d1c1)
![Uploading image.jpg…]()

**Comment by ka7474** [comment]
![IMG_6776](https://github.com/user-attachments/assets/60c87600-7b66-4660-8bd2-91ea63316e60)
![Uploading IMG_6775.jpeg…]()

**Comment by xulihang** [comment]
项目设置-文字去除里把掩膜膨胀大小设大一点。参考这篇博客：https://www.basiccat.org/zh/details-about-image-text-removal-using-imagetrans/#%E5%B8%A6%E9%98%B4%E5%BD%B1%E6%88%96%E8%80%85%E6%8F%8F%E8%BE%B9%E7%9A%84%E6%96%87%E5%AD%97
