### ISSUE TITLE
Adding chatGPT

### ISSUE THREAD

**Issue by snoopgd** [xulihang/ImageTrans-docs#760]
I have a problem - I don't want to connect. I add it in API, API to gpt chat but I show that it is gpt-3.5-turbo. There is already a higher version and I have a premium account, can I connect it somehow? I created the API on platform.openai and I'm sure I pasted the right ones. API has all permissions

When I want to use chatgpt, it happens that even though I have added the API, nothing happens
By the way, in the guide: https://www.basiccat.org/ChatGPT-image-translator/ 
the window looks different than mine (screenshot)
![image](https://github.com/user-attachments/assets/3f2a48dd-1c6e-47fd-afb7-9349eb3bd7c4)

in preference>>> machine translation I have selected chatgpt

Chatgpt appears in translation assist but the fields are empty

**Comment by xulihang** [comment]
The params have been updated to add a few options but it does not matter.

You can use imagetrans.bat to open the program and see the error message when using ChatGPT.

**Comment by snoopgd** [comment]
where can I find this file?

**Comment by snoopgd** [comment]
I think I have it, and in it I have this:


`jre\bin\java -Xmx2048M --module-path jre\javafx\lib --add-modules javafx.base,javafx.controls,javafx.graphics,javafx.web,javafx.swing --add-opens javafx.controls/com.sun.javafx.scene.control.skin=ALL-UNNAMED --add-exports javafx.base/com.sun.javafx.collections=ALL-UNNAMED -jar --add-exports java.desktop/sun.awt=ALL-UNNAMED .\ImageTrans.jar`

**Comment by xulihang** [comment]
You have to double click it to run it.

**Comment by snoopgd** [comment]
I sent what I have in the bat file
chatgpt still doesn't work :(

**Comment by xulihang** [comment]
Use the bat file to open ImageTrans. You can see a black window. In the window, check the error message to find why it does not work.

**Comment by snoopgd** [comment]
Sorry, I'm not very technical, when I click imagetrans.bat a black window appears for a fraction of a second and then disappears
I can only view this file using notepad

**Comment by xulihang** [comment]
Are you using the zip file from onedrive? It should contain the jre folder which is used to run with the bat file. 

I think the problem is related to your api key and you have to check the error message to know the exact reason.

**Comment by xulihang** [comment]
If you cannot use the bat file, then hold shift and right click to open powershell. Then enter the command to run it: jre\bin\java -Xmx2048M --module-path jre\javafx\lib --add-modules javafx.base,javafx.controls,javafx.graphics,javafx.web,javafx.swing --add-opens javafx.controls/com.sun.javafx.scene.control.skin=ALL-UNNAMED --add-exports javafx.base/com.sun.javafx.collections=ALL-UNNAMED -jar --add-exports java.desktop/sun.awt=ALL-UNNAMED .\ImageTrans.jar

**Comment by snoopgd** [comment]
> Are you using the zip file from onedrive? It should contain the jre folder which is used to run with the bat file.


I just downloaded it from this link :) 

![image](https://github.com/user-attachments/assets/15c0288d-bb35-43d3-89ac-fac7ffcd7548)
this appears when I try to use chatgpt


Thank you very much for your help and patience :)

**Comment by snoopgd** [comment]
I use the premium version of chatagpt

**Comment by snoopgd** [comment]
Okay, I know, the chatgpt API is paid separately, I completed the account and now it works!!!! 


Sorry for all the confusion and thank you very much for your time 

By the way, if chatgpt is in translation assist, it won't translate the text :)

**Comment by xulihang** [comment]
If it does not translate, reopen the program and try again. You can also check out the error message.

![image](https://github.com/user-attachments/assets/b74669ad-b6d2-467c-820a-97018c6c3307)
