### ISSUE TITLE
关于分镜的问题

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#761]
老哥 
我昨天晚上 
发现个网站
https://universe.roboflow.com/search?q=like:muhamad-aditya-winaldo-w7csy%2Fskripsi-2-uhamg
![image](https://github.com/user-attachments/assets/858173af-573d-4321-a341-bdb96f060bf8)
上边有很多已经标注好的 漫画 和yolo 的数据
虽然漫画文字方面的数据 不太能拿来用 标注的太草率 粗糙了
但是 我看到有 分镜的数据
![image](https://github.com/user-attachments/assets/2df46846-7a80-4579-8dee-22cb9321f955)
咱IT支持yoloV 8的模型  我就在想 好奇想问下 假如用这个V8训练分镜模型 是不是咱也可以识别？

用的 OBB模型 也就是 之前您 支持的 倾斜矩形的那个 模型的类型
![image](https://github.com/user-attachments/assets/e5732be9-5a17-4462-9b33-bd897710e2a7)

**Comment by xulihang** [comment]
用目标检测做分镜检测是可以的，mantra的论文就是这么写的。

不过很多分镜都是多边形，用yolo识别只能给出一个长方形。ImageTrans目前也不支持用多边形表示分镜。

**Comment by xulihang** [comment]
也有人用YOLO做别的文档分析任务，比如360做的版面分析：https://github.com/xulihang/document-layout-analysis

**Comment by lhj5426** [comment]
嗯了解了 这个360 这个 厉害  数据看来不少
