### ISSUE TITLE
I think a tutorial is urgently needed showing the function of each thing and how to use it.

### ISSUE THREAD

**Issue by truki20** [xulihang/ImageTrans-docs#762]
With the implementation of many options, the recurring problem I have is that I do not use most of the options that the program has because I do not understand how it works apart from the basic ones that were explained to me in the documentation and I feel that I am not taking full advantage of it.

**Comment by xulihang** [comment]
I've already tried covering all the aspects of the program in the documentation.

You can list some use cases or images so that I can write a blog on how to handle them.
