### ISSUE TITLE
翻译排版问题，界面可以设置图片显示大小的但

### ISSUE THREAD

**Issue by dada609695** [xulihang/ImageTrans-docs#763]
翻译排版问题，界面可以设置图片显示大小的但能不能可以一张图显示在两个容器内 对着原图排版翻译的文字呢

**Comment by xulihang** [comment]
你的显示器很宽吗，我的显示器显示不下两张图。我可以提供一个弹出窗口，方便查看原图

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/21310f3e-c3f7-4226-89f8-ed10b8248c6a)
比如 DLsite  大家来翻译的这种界面？ 
https://mntr.notion.site/OCR-d51c8561c8404720af6a7b4f0561f1d5

![image](https://github.com/user-attachments/assets/93901f63-a1ef-4809-aa38-822accdd73d1)

**Comment by xulihang** [comment]
mantra的在线编辑器有个不好的地方就是原文和译文的文本框位置是一样的。

我打算只提供查看原图的功能，用弹出窗口，用户可以自由放置位置。

**Comment by lhj5426** [comment]
其实我觉得 之前弄那个 透明图层就可以 用做对比吧  排版也方便？ 
![image](https://github.com/user-attachments/assets/b512d943-a9a6-4164-9df3-0e95446b5af3)
翻译完排版的时候我之后一直都是差不多这么用 75 到85 左右的透明度然后开始对照位置

**Comment by xulihang** [comment]
3.10.3添加了原图查看器：

![image](https://github.com/user-attachments/assets/9a11728b-109b-48fd-908e-588eb9953787)

![image](https://github.com/user-attachments/assets/6566ed38-6157-4b0f-9788-dc8a4a90b12e)

**Comment by dada609695** [comment]
> mantra的在线编辑器有个不好的地方就是原文和译文的文本框位置是一样的。
> 
> 我打算只提供查看原图的功能，用弹出窗口，用户可以自由放置位置。

可是这样不能随翻译图一起滚动，这样对我们这些翻译长图高度过万的不好 对做宽图不长的图还好

**Comment by dada609695** [comment]
现在用这个原图查看器还得用个窗口同步器才能 两个图片同步显示一个图片片段

**Comment by xulihang** [comment]
目前只同步了百分比，同步进度条比较麻烦

**Comment by lhj5426** [comment]
我是多显示器 我把一个显示器竖过来处理竖着比例的图，横图和方图就放在横着的显示器来处理的😆 这样就不冲突了……现在显示器也比较便宜了… 不过我还在等lg的魔方屏等再掉掉价……这屏幕的比例绝对是处理漫画神器 就是2k 60刷新卖的比4k高刷都贵……还得等等
