### ISSUE TITLE
crashing on MAC

### ISSUE THREAD

**Issue by alverneball** [xulihang/ImageTrans-docs#764]
the program on my Mac continues to crash if I click out of it to use any other program

**Comment by xulihang** [comment]
Which Mac and macOS version are you using?

Based on my experience, it runs smoothly on an Apple CPU Mac. It may crash on an Intel CPU Mac occasionally. Could you also paste the error message?

**Comment by alverneball** [comment]
I'm running macOS Monetary with an Apple M1 Chip.  Here's a screen capture of what I'm seeing before it crashes
<img width="534" alt="Screen Shot 2024-09-26 at 10 34 53 PM" src="https://github.com/user-attachments/assets/f33fa0b7-ec2a-49cb-a613-509651005f6d">

**Comment by xulihang** [comment]
I remember that the system will also give a prompt to see the errors. Do you have it? 

I compiled the package under macOS Sonoma so it may not work very well in an old macOS.

**Comment by alverneball** [comment]
I don't get a prompt to see the errors.  I'll update the OS and hopefully that will fix the system.
