### ISSUE TITLE
V8和V11有区别吗 可以直接用吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#766]
是这样的老哥 我整个9月份 都在做数据标注
然后打算训练一个同时兼容气泡和纯文字以及硬字幕的模型
然后当我今天打算开始训练的时候 我看网站出来个11
![image](https://github.com/user-attachments/assets/59fed877-16ec-4cd7-b3c6-1a4e9bf08d49)
反正是新训练 那这个是不是直接训练最新的更好？
 还是 他这个就是在刷版本号

**Comment by xulihang** [comment]
可以转换一个它的模型为onnx，用ImageTrans去识别一张有猫猫狗狗的图，看能不能检测。但我估计是不太行

**Comment by lhj5426** [comment]
> 可以转换一个它的模型为onnx，用ImageTrans去识别一张有猫猫狗狗的图，看能不能检测。但我估计是不太行

它这个对于咱们这种简单的识别任务来说 会不会有提升
因为在B站还有CSDN上看的 都是超级复杂的工作比如什么焊接点 什么 医学还有 植物的叶子的病变
那图看着都复杂V8都可以胜任

**Comment by xulihang** [comment]
我试了下，可以直接用的

**Comment by lhj5426** [comment]
> 我试了下，可以直接用的

66666 那知道了 谢谢老哥
