### ISSUE TITLE
呃 导出的psd在哪？用everything也没搜到，有关ps的有教程么？

### ISSUE THREAD

**Issue by swswlg** [xulihang/ImageTrans-docs#768]

**Comment by lhj5426** [comment]
我在 E站倒是写过
https://e-hentai.org/s/691a357fac/2857507-94

**Comment by swswlg** [comment]
> 我在E站倒是写过 https://e-hentai.org/s/691a357fac/2857507-94

非常感谢你的帮助，这个教程简直太实用了！！！

**Comment by xulihang** [comment]
b站视频里也有演示操作

**Comment by ka7474** [comment]
导出PSD后只找到了这两个
![image](https://github.com/user-attachments/assets/06c58da0-58dd-4e5e-9bfc-577936767d3d)
