### ISSUE TITLE
add ability for models with more than one class

### ISSUE THREAD

**Issue by gandarufu** [xulihang/ImageTrans-docs#772]
I trained a model to detect soundwords AND balloon texts. However, using a custom model via balloon detect only seems to predict one class. Is there a way to have all classes from the model predicted, maybe with different font styles, the way you implemented it for the dataset assistant?

**Comment by xulihang** [comment]
Check out this: https://www.basiccat.org/how-to-train-yolov8-object-detection-model/#managing-classes

**Comment by gandarufu** [comment]
I added all classes to the font styles via the project settings and placed the "model.classes" with the corresponding labels in the directory of the model file, yet when I click detect balloons, it still only finds the soundwords, and no balloon text. Is this supposed to work for models with multiple classes?

Also, do you see any chance to add an offline model selection to the panel detection, vs. an online version? I have a custom model for that as well. Would be neat to just link that similarly as the balloon models.

**Comment by lhj5426** [comment]
> I added all classes to the font styles via the project settings and placed the "model.classes" with the corresponding labels in the directory of the model file, yet when I click detect balloons, it still only finds the soundwords, and no balloon text. Is this supposed to work for models with multiple classes?-----------谷歌翻译-----------我通过项目设置将所有类添加到字体样式，并将带有相应标签的“model.classes”放置在模型文件的目录中，但是当我单击“检测气球”时，它仍然只找到声音单词，而没有气球文本。这应该适用于具有多个类的模型吗？
> 
> Also, do you see any chance to add an offline model selection to the panel detection, vs. an online version? I have a custom model for that as well. Would be neat to just link that similarly as the balloon models.-----------谷歌翻译-----------另外，与在线版本相比，您是否认为有机会在面板检测中添加离线模型选择？我也有一个定制模型。将其与气球模型类似地链接起来就很不错了。

https://github.com/user-attachments/assets/2cb6e213-7257-4b1a-b08d-bf9f91ef3323

**Comment by xulihang** [comment]
I've added object detection as a panel detection method in v3.11.0.

![image](https://github.com/user-attachments/assets/5aa7c732-7c71-4fc5-82c1-173a6ea9ed9c)


It will use the model named `panel`.

You can put the model under the project's `panel` folder or the app's `models\panel` folder to use it.

**Comment by gandarufu** [comment]
Awesome, thank you so much! Can't wait to give it a try.

**Comment by gandarufu** [comment]
I still cannot get ImageTrans to detect multiple classes with my model, so I'm questioning if my model is the problem or my setup. Could you take a look at my model, if I send you the link for it? It's trained on 3 classes, I've set up the font styles, the model.classes and the model.json as you showed, it still only detects one out of three classes.

**Comment by gandarufu** [comment]
> I've added object detection as a panel detection method in v3.11.0.
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/380077948-5aa7c732-7c71-4fc5-82c1-173a6ea9ed9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDkxNjMsIm5iZiI6MTczMDY0ODg2MywicGF0aCI6Ii81NDYyMjA1LzM4MDA3Nzk0OC01YWE3YzczMi03YzcxLTRmYzUtODJjMS0xNzNhNmVhOWVkOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMTU0NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjliMDBkZTU4MmY4NTA0YjVhYzk2MDA2MjcxYzQ4NmE5M2Q5NDQ0YmM1YjU1NjkyNjUzZWI3YzQ4MWE1ZmYyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.j329iGiG6MDk0DzW4fNNbh07YL_wxhPcp8bU_s-_NQ4)
> 
> It will use the model named `panel`.
> 
> You can put the model under the project's `panel` folder or the app's `model\panel` folder to use it.

How do you make this work? My model detects the panels, the class is labeled "frame". I put the model under models\panel\model.onxx, with a model.json and a model.classes ("0":"frame"), but i don't get any results in ImageTrans.

I'd appreciate a bit more information on how to use the features.

**Comment by xulihang** [comment]
You can try this model with the following page: https://github.com/xulihang/document-layout-analysis


![image](https://github.com/user-attachments/assets/aca6a0f6-54ce-43a0-b3c8-3175d1cf12d1)

**Comment by xulihang** [comment]
Result: 

![capture001](https://github.com/user-attachments/assets/c933acf9-f6ff-4ee6-a550-8e8082bc9745)

**Comment by xulihang** [comment]
> I still cannot get ImageTrans to detect multiple classes with my model, so I'm questioning if my model is the problem or my setup. Could you take a look at my model, if I send you the link for it? It's trained on 3 classes, I've set up the font styles, the model.classes and the model.json as you showed, it still only detects one out of three classes.

The default YOLO model is multi-class. All the classes can be detected.

Please test your model with the official code: https://docs.ultralytics.com/tasks/detect/#predict

If it only contains one class, then it should be something wrong with your training.
