### ISSUE TITLE
导出PSD只能找到这个out和params.找不到演绎视频里的images啊

### ISSUE THREAD

**Issue by ka7474** [xulihang/ImageTrans-docs#773]
![Uploading image.jpg…]()

**Comment by xulihang** [comment]
按视频操作。导出out.txt这个数据后用addlayers.jsx这个脚本去生成PSD。

**Comment by ka7474** [comment]
![image](https://github.com/user-attachments/assets/706acecb-15bd-4307-b605-380d86800674)
![image](https://github.com/user-attachments/assets/226f19b9-02ef-4920-87f7-5b84b050302a)
已经设置好字体了，但字体跟image不一样呢，而且有些是歪歪的

**Comment by xulihang** [comment]
字体名字是从ps读取的话，可能是用了没有正确设置名字的本地样式。有问题的项目可以发我测试一下。
