### ISSUE TITLE
add shrink to batch custom workflow

### ISSUE THREAD

**Issue by gandarufu** [xulihang/ImageTrans-docs#774]
It would make sense to also add "shrink text areas" to the batch workflow, since sometimes you need to shrink all areas in a document.

**Comment by xulihang** [comment]
Noted. You can try the fit text areas to the text mask in custom workflow which also shrinks the text areas.

**Comment by lhj5426** [comment]
哈哈我之前弄了一个这个
![image](https://github.com/user-attachments/assets/bd5087d3-5655-4385-ac3a-b2469246b58f)
模型识别完有的时候太靠近字体就给某一个方向单独进行延伸

**Comment by xulihang** [comment]
Added in v3.11.1.
