### ISSUE TITLE
弱弱的问一下

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#775]
事情是这个样子的 开发者老哥
自从 好像是从6月份开始吧
开始研究YOLO 自己训练模型 到现在已经几个月了
在这几个月里呢
我几乎是每天都在用咱的ImageTrans和另外的一个X-AnyLabeling
然后呢 现在产生了一个问题 
这个问题是我自身的问题

这个问题是
因为几乎每天都在用 都在做标注
这边才用了
https://github.com/dmMaze/comic-text-detector
![image](https://github.com/user-attachments/assets/a5af3b06-9d44-4b08-8d7f-3d87b4276aa7)
这边才用了 一万3千张
而我这几个月已经 是这边的好几倍了 并且全部都是强监督数据
![image](https://github.com/user-attachments/assets/c32bf549-0768-4098-8280-73d3a2344138)
 并且今天还在搞
 
![image](https://github.com/user-attachments/assets/debd096f-4682-4d4c-8da1-f91793f2cd8b)

说了这么多 其实问题的核心是我已经习惯并且喜欢上了
这种 不同 标注类型  显示不同颜色
![image](https://github.com/user-attachments/assets/ddb5152c-8ed8-4f5a-96a7-424b640eec0b)
![image](https://github.com/user-attachments/assets/a67d06c0-3807-4beb-9964-2b59c699f4c8)
因为几乎天天在用 所以 真的看习惯了
现在看
![image](https://github.com/user-attachments/assets/4204d2c3-eb24-4b20-a285-345aede306bf)
这边的全部 纯色框
有点不太适应 哈哈
然后
我就想来问问老哥
既然可以自定义 样式
![image](https://github.com/user-attachments/assets/5625588c-7eba-4636-9828-d9a6df2d136e)
那个......能不能增加一个 那个标注标签颜色的样式呢？
其实这边 开始也不能修改
https://github.com/CVHub520/X-AnyLabeling/issues/470
也是在问了之后 开发者增加了类似 ImageTrans 这边可以修改矩形框 宽度的功能

所以 就是这样 

概括一下 就是  
可以不可以  增加一个自定义样式可以定义  目标检测到的 标签的边框的样式 拜托了

**Comment by xulihang** [comment]
我考虑下怎么实现比较这个设置比较方便

**Comment by xulihang** [comment]
添加在v3.11.1了。

在偏好设置-主题中勾选使用文字样式中的背景颜色作为文本框颜色，然后勾选显示样式名时会应用颜色。

**Comment by lhj5426** [comment]
https://github.com/user-attachments/assets/ebcb886b-4740-4d7c-bb4c-5fdeebcf615b

 哈哈  非常感谢老哥 这样颜色区分就很舒服了
