### ISSUE TITLE
Thai Support? 

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#777]
It supports translation to Thai and Thai typing?

**Comment by xulihang** [comment]
Yes.

**Comment by ZeroSum2000** [comment]
Thank you very much. I Will buy it now

**Comment by ZeroSum2000** [comment]
> Yes.

I downloaded it and it won't open.What should I do?

**Comment by ZeroSum2000** [comment]
> > Yes.
> 
> I downloaded it and it won't open.What should I do?


Uploading Messenger_creation_DD67F123-F64C-44BD-B62A-E4985F14ABB4.mp4…

**Comment by xulihang** [comment]
Use the package on onedrive. See the links in the email.

**Comment by ZeroSum2000** [comment]
> Use the package on onedrive. See the links in the email.

Click open and nothing happens.
![Screenshot_20241029_184358_com huawei himovie overseas](https://github.com/user-attachments/assets/726bdda5-f74f-4f2e-b405-6385d9a06dc2)

**Comment by xulihang** [comment]
Hold shift and right click. Open powershell and then run the following command:

.\ImageTrans.bat

**Comment by ZeroSum2000** [comment]
> Hold shift and right click. Open powershell and then run the following command:
> 
> .\ImageTrans.bat

Thank you I will try.

**Comment by ZeroSum2000** [comment]
> Hold shift and right click. Open powershell and then run the following command:
> 
> .\ImageTrans.bat

![IMG_20241029_201910](https://github.com/user-attachments/assets/e1977899-b88f-409b-a4a4-9d0ec2cb6120)
I hold shift and right click it don't have open powershell What should I do?

**Comment by ZeroSum2000** [comment]
> Hold shift and right click. Open powershell and then run the following command:
> 
> .\ImageTrans.bat

![Uploading IMG_20241029_202350.jpg…]()

**Comment by ZeroSum2000** [comment]
> Hold shift and right click. Open powershell and then run the following command:
> 
> .\ImageTrans.bat

![Uploading IMG_20241029_202350.jpg…]()

**Comment by xulihang** [comment]
Do not click the icon. Click on an empty area.

**Comment by ZeroSum2000** [comment]
> Do not click the icon. Click on an empty area.

![IMG_20241029_202517](https://github.com/user-attachments/assets/8c1467b9-df78-4422-978c-0d182c9308b6)

**Comment by xulihang** [comment]
It seems that some files are missing. Please make sure that you have unzipped the file correctly and have the jre folder.

You can try to download the zip again and unzip it to another place like D:\imagetrans

**Comment by ZeroSum2000** [comment]
> It seems that some files are missing. Please make sure that you have unzipped the file correctly and have the jre folder.
> 
> You can try to download the zip again and unzip it to another place like D:\imagetrans

Ok thank you I will try.

**Comment by ZeroSum2000** [comment]
> It seems that some files are missing. Please make sure that you have unzipped the file correctly and have the jre folder.
> 
> You can try to download the zip again and unzip it to another place like D:\imagetrans

Can you give me link download please

**Comment by xulihang** [comment]
The onedrive link. You should have seen it in the email.

**Comment by ZeroSum2000** [comment]
> The onedrive link. You should have seen it in the email.

![Uploading IMG_20241029_204918.jpg…]()

**Comment by ZeroSum2000** [comment]
> The onedrive link. You should have seen it in the email.

![IMG_20241029_204918](https://github.com/user-attachments/assets/8bb85bf9-0141-4412-8e3f-fc5cce2496c3)

**Comment by ZeroSum2000** [comment]
> > It seems that some files are missing. Please make sure that you have unzipped the file correctly and have the jre folder.
> > You can try to download the zip again and unzip it to another place like D:\imagetrans
> 
> Can you give me link download please

Oh I understood. I Will try again.

**Comment by ZeroSum2000** [comment]
> It seems that some files are missing. Please make sure that you have unzipped the file correctly and have the jre folder.
> 
> You can try to download the zip again and unzip it to another place like D:\imagetranI can open the file and thank you very much for helping.

**Comment by ZeroSum2000** [comment]
> It seems that some files are missing. Please make sure that you have unzipped the file correctly and have the jre folder.
> 
> You can try to download the zip again and unzip it to another place like D:\imagetrans

I can open the file and thank you very much for helping.
