### ISSUE TITLE
Please give me a link to teach me how to use it.

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#779]
When I pressed translate the image, some English letters were not deleted.
![IMG_20241101_163901](https://github.com/user-attachments/assets/328f0dee-0d0d-4753-ad88-45c2d3d03d45)
Can I clean some bubble by my self and how?
Thank you for helping me🙏🙏

**Comment by xulihang** [comment]
You need to make the text areas smaller to create the text mask correctly.

You can also use the mask editor to modify the text mask.

Check out the docs: https://imagetrans.readthedocs.io/en/latest/textarea_detection_and_text_reinjection.html
