### ISSUE TITLE
Image Trans as Cli without open gui 

### ISSUE THREAD

**Issue by apt42541** [xulihang/ImageTrans-docs#780]
{
    "auto_clean": true,
    "otsu_enabled": true,
    "horizontal_merge_for_OCR": true,
    "enable_panel_detection": false,
    "remove_space": false,
    "detection_method": "ballon",
    "reorder": false,
    "threshold": 200,
    "use_puretext": false,
    "source": "en",
    "mt_interval": 200,
    "right2left": false,
    "precision_mode": true,
    "ocr_interval": 200,
    "panel_detection_method": 0,
    "stripfurigana": false,
    "auto_capital": false,
    "autoThreshold": true,
    "vertical_merge_for_OCR": true,
    "mtengine": "tencent",
    "minimumHeight": 3,
    "addBorder": false,
    "minimumHSpan": 15,
    "target": "zh",
    "ocrlang": "eng",
    "maximumHeight": 100,
    "chinese_punctuation": false,
    "ocrengine": "tesseract",
    "minimumVSpan": 15
}

My purpose is batch ocr multi chapter like Naruto/15 /16/ /17 /18  and when ocr done got 4 txt file as ocr result

"jre\bin\java" --module-path jre\javafx\lib --add-modules javafx.base,javafx.controls,javafx.graphics,javafx.web,javafx.swing --add-opens javafx.controls/com.sun.javafx.scene.control.skin=ALL-UNNAMED --add-exports javafx.base/com.sun.javafx.collections=ALL-UNNAMED --add-exports java.desktop/sun.awt=ALL-UNNAMED -jar .\ImageTrans.jar "config.json" false true "./output" "filelist.txt"

run(Map) Not initialized
config.json
false
true
./output
filelist.txt
working dir:./output
null
(NullPointerException) java.lang.NullPointerException: Cannot invoke "anywheresoftware.b4a.BA$IterableList.getSize()" because "<local13>" is null

**Comment by xulihang** [comment]
The ui must be opened as this is a JavaFX program although it can be called using the command line.

You can use silent translator helper to customize the options.

By the way, I plan to make it also support using custom workflow to process files so that you can only run OCR.

**Comment by xulihang** [comment]
Check out this about running ImageTrans via CLI: https://github.com/xulihang/ImageTrans-docs/issues/785
