### ISSUE TITLE
Translation Problem

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#781]
Why ChatGPT Translated into other languages, not in Thai? I have set it to translate from English to Thai.
![IMG_20241102_175713](https://github.com/user-attachments/assets/7fd4948b-c556-4304-926b-e7597664d386)

**Comment by xulihang** [comment]
You can try to modify the prompt to specify Thai as the target: https://www.basiccat.org/ChatGPT-image-translator/#customize-the-prompt

**Comment by ZeroSum2000** [comment]
> You can try to modify the prompt to specify Thai as the target: https://www.basiccat.org/ChatGPT-image-translator/#customize-the-prompt

Thank you🙏🙏
