### ISSUE TITLE
Sickzil-Machine 

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#782]
How to install in the imageTrans program In the second step, what plugins should be loaded, and in the third step, which files should be loaded?
![IMG_20241102_192038](https://github.com/user-attachments/assets/f69e79f5-d5d7-49b1-bab4-fb64eba7655e)
![IMG_20241102_192125](https://github.com/user-attachments/assets/b74fdf00-1bc4-45b5-ae36-8e73d9960016)
![IMG_20241102_192339](https://github.com/user-attachments/assets/d26bf429-4732-4d41-b149-47967464d228)

**Comment by xulihang** [comment]
I've updated the readme: https://github.com/xulihang/ImageTrans_plugins/blob/master/README.md#how-to-use-sickzil-machine

**Comment by ZeroSum2000** [comment]
> ฉันได้อัปเดต readme แล้ว: https://github.com/xulihang/ImageTrans_plugins/blob/master/README.md#how-to-use-sickzil-machine

Thank you so much🙏🙏

**Comment by ZeroSum2000** [comment]
> I've updated the readme: https://github.com/xulihang/ImageTrans_plugins/blob/master/README.md#how-to-use-sickzil-machine

In the third point, call it right here, right?
![IMG_20241102_215608](https://github.com/user-attachments/assets/162b064e-33b0-4dfe-bdb7-a228e7f70013)

**Comment by xulihang** [comment]
Right.

Also in the mask editor and the text remover.
