### ISSUE TITLE
Lamainpaint

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#783]
Can Lamainpaint be erased smoothly?
![IMG_20241102_192609](https://github.com/user-attachments/assets/bd2440ef-3e33-4731-91c6-abc89d0fd8d3)
![IMG_20241102_192611_edit_171859072896692](https://github.com/user-attachments/assets/1879b2b8-8ee5-4cf4-989e-786c170284df)

**Comment by xulihang** [comment]
Yes.

Check out this blog: https://www.basiccat.org/details-about-image-text-removal-using-imagetrans/#lama-inpaint

**Comment by ZeroSum2000** [comment]
> Yes.
> 
> Check out this blog: https://www.basiccat.org/details-about-image-text-removal-using-imagetrans/#lama-inpaint

Thank you.
