### ISSUE TITLE
I can't change the page.

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#784]
I can't change pages very often.I have to re-issue the program to use it.

https://github.com/user-attachments/assets/5c9eb567-7ff2-4064-8383-82d7f9e0aa2e

**Comment by xulihang** [comment]
It takes time to generate the text-removed image.

You can generate them using Project->Batch->Generate text mask and text-removed images.

You can also disable precise text-removal to quickly navigate through pages.

Meanwhile, use the context menu to refresh the page if you encounter such a problem.

**Comment by ZeroSum2000** [comment]
> It takes time to generate the text-removed image.
> 
> You can generate them using Project->Batch->Generate text mask and text-removed images.
> 
> You can also disable precise text-removal to quickly navigate through pages.
> 
> Meanwhile, use the context menu to refresh the page if you encounter such a problem.

Thank you.
