### ISSUE TITLE
MangaTranslatorOCR

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#786]
Step 1 unzip it into folder 
Which folder
![IMG_20241104_120656](https://github.com/user-attachments/assets/5b4e8d35-2022-4593-8fb8-b98b79f60e69)
?

**Comment by xulihang** [comment]
Just create a new folder.

**Comment by ZeroSum2000** [comment]
> Just create a new folder.

Like this? 
![IMG_20241104_122123](https://github.com/user-attachments/assets/ed529989-f659-4f2a-8cff-6d01eab20539)

**Comment by xulihang** [comment]
Put all the files in one folder. Step 1's manga-image-translator in your case.

**Comment by ZeroSum2000** [comment]
After following the steps, it still doesn't work, nothing happens.

**Comment by ZeroSum2000** [comment]
> Put all the files in this folder. Step 1's manga-image-translator in your case.

![IMG_20241104_122826](https://github.com/user-attachments/assets/10072eeb-03a5-45fe-a23d-d9b340d29ec9)

**Comment by xulihang** [comment]
Same content. Just replace it.

**Comment by ZeroSum2000** [comment]
> Same content. Just replace it.


https://github.com/user-attachments/assets/0448794a-3939-4e68-87e8-8ab2c189b95a

**Comment by ZeroSum2000** [comment]
https://github.com/user-attachments/assets/61b4e645-a901-491c-8d56-56de17d1ffbf

**Comment by ZeroSum2000** [comment]
Nothing happened.

**Comment by xulihang** [comment]
Check the output in the console.

The server's:

![image](https://github.com/user-attachments/assets/6281986f-34db-465d-b9a4-82d39c3b4afa)

ImageTrans's:

![image](https://github.com/user-attachments/assets/c9256f8e-4b09-4566-9f09-dcda34c99807)


Make sure that your 8080 port is not occupied by other programs and you can visit http://127.0.0.1:8080/ in the browser.

![image](https://github.com/user-attachments/assets/c5551fb3-178e-43df-943d-5c6858dd5ef8)

**Comment by ZeroSum2000** [comment]
> Check the output in the console.
> 
> The server's:
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/382654823-6281986f-34db-465d-b9a4-82d39c3b4afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDA2ODEsIm5iZiI6MTczMDcwMDM4MSwicGF0aCI6Ii81NDYyMjA1LzM4MjY1NDgyMy02MjgxOTg2Zi0zNGRiLTQ2NWQtYjlhNC04MmQzOWMzYjRhZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDYwNjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZlZGI4NWZiY2ZiOGMwYjhjMDEzMTgxZGZmYzE4M2NiODhjMWY2Y2U0MGY3YjYwMGE2ZWUzMGZjNmZmOGQyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LAh0wY5WqRSikt7GtXto970eYKFwEz4yMnbxjooE7TQ)
> 
> ImageTrans's:
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/382654941-c9256f8e-4b09-4566-9f09-dcda34c99807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDA2ODEsIm5iZiI6MTczMDcwMDM4MSwicGF0aCI6Ii81NDYyMjA1LzM4MjY1NDk0MS1jOTI1NmY4ZS00YjA5LTQ1NjYtOWYwOS1kY2RhMzRjOTk4MDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDYwNjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY3NjU3NDg0MmNjY2I4OWY2MmJlMzk0ZDcyZGI2MDc0ZWI1MDM1NGMxMDJjMTRhNWNlOWU5MTJiMTRhYjdkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fqGgiyLR2k_ah9AEIywwoveWAgQM0trzNQywkAw28xU)
> 
> Make sure that your 8080 port is not occupied by other programs and you can visit http://127.0.0.1:8080/ in the browser.
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/382655012-c5551fb3-178e-43df-943d-5c6858dd5ef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDA2ODEsIm5iZiI6MTczMDcwMDM4MSwicGF0aCI6Ii81NDYyMjA1LzM4MjY1NTAxMi1jNTU1MWZiMy0xNzhlLTQzZGYtOTQzZC01YzY4NThkZDVlZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDYwNjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU5NTcwYzExOWZjMzNmMjZkNjFhMWY4NWQ3ODU5NWVlZDhmZTJiZWY4ODkzMjhlOTY2YjgxODg3MDQxMjEyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TpvBFhs6Qgt5dIGr4t9hsdugDHD8B_6eK4rQdWTzok0)

How to fix it? 
![IMG_20241104_130847](https://github.com/user-attachments/assets/09e62d7b-38f1-4a27-a8ce-7c525ce7f445)
![IMG_20241104_130853](https://github.com/user-attachments/assets/9ae69a81-196b-472d-ab14-a1fd8d38bc50)
![IMG_20241104_130857](https://github.com/user-attachments/assets/d5417dff-c91f-4d18-931a-5487db770b50)

**Comment by xulihang** [comment]
Close sickzil-machine as it conflicts with manga translator.

**Comment by ZeroSum2000** [comment]
> ปิดเครื่อง sickzil เนื่องจากขัดแย้งกับโปรแกรมแปลมังงะ

Thank you🙏🙏
