### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#787]
I can't use some OCR, such as: tesseract 
![IMG_20241104_131036](https://github.com/user-attachments/assets/c892243f-4926-437e-b8b2-03766783312e)
![IMG_20241104_131052](https://github.com/user-attachments/assets/0926c682-c3a3-4542-ad26-f3949c272ddd)

**Comment by xulihang** [comment]
Follow the docs to install it.

**Comment by ZeroSum2000** [comment]
> Follow the docs to install it.

Link please🙏🙏

**Comment by xulihang** [comment]
https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#ocr

**Comment by ZeroSum2000** [comment]
> https://imagetrans.readthedocs.io/en/latest/gettingstarted.html#ocr

Thank you🙏🙏
