### ISSUE TITLE
自动翻译又出错了，今天才五号，是又欠费了吗😭。我使用的次数不多，免费额度完全够用

### ISSUE THREAD

**Issue by ka7474** [xulihang/ImageTrans-docs#788]
![Uploading image.jpg…]()

**Comment by ka7474** [comment]
![Uploading image.jpg…]()

**Comment by xulihang** [comment]
可以自己申请一个账号：https://fanyi-api.baidu.com/api/trans/product/desktop

**Comment by xulihang** [comment]
这个月已经可以用了
