### ISSUE TITLE
OPUS

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#789]
I've downloaded it, what should I do next? I WANT TO USE IT IN IMAGETRANS.
![IMG_20241107_212420](https://github.com/user-attachments/assets/75246976-f526-43af-bf34-3b3cd9de9897)
![IMG_20241107_212427](https://github.com/user-attachments/assets/7a4669dc-2800-4982-b45d-5d68e94d0ead)

**Comment by xulihang** [comment]
Just use it in ImageTrans with the OPUS.

![image](https://github.com/user-attachments/assets/0b99d131-c86e-4ca3-96af-4d1bdeac9a15)

**Comment by xulihang** [comment]
I've updated the plugin for the latest version of OPUS-CAT:

https://helsinki-nlp.github.io/OPUS-CAT/opus-cat/update/2024/11/01/opus-cat-131b.html

You can use the updated one: 

[OPUSplugin.zip](https://github.com/user-attachments/files/17685987/OPUSplugin.zip)


Unzip it to replace the files in the plugins folder.

**Comment by ZeroSum2000** [comment]
> I've updated the plugin for the latest version of OPUS-CAT:
> 
> https://helsinki-nlp.github.io/OPUS-CAT/opus-cat/update/2024/11/01/opus-cat-131b.html
> 
> You can use the updated one:
> 
> [OPUSplugin.zip](https://github.com/user-attachments/files/17685987/OPUSplugin.zip)
> 
> Unzip it to replace the files in the plugins folder.

Thank you so much
