### ISSUE TITLE
不太會使用翻譯(日to中) 有詳細的說明步驟嗎?

### ISSUE THREAD

**Issue by trahur** [xulihang/ImageTrans-docs#79]
我是使用ImageTrans-windows-x64 從onedrive上的 但是用了一陣子發現還是部會翻譯 尤其是許多ocr engine 翻不出來. 有要安裝什麼其他的engine 嗎? 有詳細的步驟嗎? thanks!

**Comment by xulihang** [comment]
默认只有百度、ocrspace、azure我内置了API密钥，可以直接使用，其它引擎都是需要自己配置的。我在文档里有提到：https://imagetrans.readthedocs.io/zh_CN/latest/gettingstarted.html#ocr。

日语OCR效果比较好的有谷歌、搜狗、百度精确版 (baidu_accurate)、Windows 10自带OCR (WinRT)。其实最精确的还是自己定制OCR引擎，但一般电脑上处理速度很慢

**Comment by xulihang** [comment]
常见问题页面里也有提到竖排日语的问题：https://www.basiccat.org/zh/imagetrans/faq/
