### ISSUE TITLE
这个项目对提升去字 有帮助吗

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#794]
老哥 今天 探索github 时候在我的兴趣页面 github 推荐的
 https://github.com/VoxelCubes/PanelCleaner
 这个项目 对 去字 方面有没有提升的帮助？

**Comment by xulihang** [comment]
这个就是ImageTrans里的用文字掩膜直接进行覆盖，掩膜使用manga-image-translator用到的comic text detector生成。

如果背景复杂就用lama inpaint。

**Comment by lhj5426** [comment]
> 这个就是ImageTrans里的用文字掩膜直接进行覆盖，掩膜使用manga-image-translator用到的comic text detector生成。
> 
> 如果背景复杂就用lama inpaint。

哈哈 原来如此
现在就是掩膜问题  我用自己之前训练的模型 识别是没太大问题
很多时候就是掩膜涂不全哈哈 
我以为这个可以改善呢所以来问问 谢谢老哥解答
