### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#795]
![Screenshot_20241118_083620_com android chrome](https://github.com/user-attachments/assets/1cb027e1-b81a-4853-893f-8f8ffbae2d25)

**Comment by xulihang** [comment]
You can find the latest versions in the onedrive link.

**Comment by ZeroSum2000** [comment]
> You can find the latest versions in the onedrive link.

Ok thank you🙏🙏
