### ISSUE TITLE
关于3.12 更新的内容 的请教

### ISSUE THREAD

**Issue by lhj5426** [xulihang/ImageTrans-docs#798]
![image](https://github.com/user-attachments/assets/3d2d7cc1-8c66-45b5-ae32-7de4d84796ba)
如图 今天打开网页发现 更新了 遂马上去更新
但是更新之后 我找不到这几几个更新 菜单呢
所以不得已又得来发帖麻烦老哥了
能说明一下 这个图上的3个更新 菜单在哪里么
我找过右键菜单和设置项 确实是没找到

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/be5524f7-bdb2-4345-a933-e3f5bc0ad948)
统一 的逻辑 不是按照最先或者最后选中的宽度作为参照统一 而是 按照 最大的宽度统一？

**Comment by xulihang** [comment]
这次更新主要是为了翻译这种电商图片：https://www.basiccat.org/zh/e-commerce-image-translation/

统一高度和宽度都是用的最大的那个区域的值。这两个操作我还没加在菜单里

计算合适字号主要是方便关闭自动字号调整时能计算出一个合适的字号：

![image](https://github.com/user-attachments/assets/31a082c7-4d61-4f0f-9677-9511d7194e33)

**Comment by lhj5426** [comment]
> 这次更新主要是为了翻译这种电商图片：https://www.basiccat.org/zh/e-commerce-image-translation/*
> 
> 统一高度和宽度都是用的最大的那个区域的值。这两个操作我还没加在菜单里
> 
> 计算合适字号主要是方便关闭自动字号调整时能计算出一个合适的字号：
> 
> ![image](https://private-user-images.githubusercontent.com/5462205/389379647-31a082c7-4d61-4f0f-9677-9511d7194e33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTM4OTQsIm5iZiI6MTczMjUxMzU5NCwicGF0aCI6Ii81NDYyMjA1LzM4OTM3OTY0Ny0zMWEwODJjNy00ZDYxLTRmMGYtOTY3Ny05NTExZDcxOTRlMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMDU0NjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjgyZjBhYjcwOWI3NmViMjc0NjZiMzU5M2M1NTkxNTk3ODFkZGMzZTA2MWZhNWVmMTVkZWUwMTFiM2JlZGYxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FMQwMzPz-Xi3B76mpi3UAm2tZhpDF96c6NNFM_FvkQc)

嗯 嗯 谢谢 解答 我了解了 可以支持电商图片了 越来越厉害了  ！

**Comment by hucurve** [comment]
好好用的功能！不知道哪天能加到自定义工作流里面！
