### ISSUE TITLE
请问怎么和Sakura一起用

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#799]

**Comment by xulihang** [comment]
sakura兼容openapi的接口，可以用chatgpt的插件。在设置里把url改成sakura的url，应该是`http://localhost:5000/v1`

**Comment by hyominli** [comment]
> sakura兼容openapi的接口，可以用chatgpt的插件。在设置里把url改成sakura的url，应该是`http://localhost:5000/v1`

用不了，prompt这些都不一样

**Comment by hyominli** [comment]
> sakura兼容openapi的接口，可以用chatgpt的插件。在设置里把url改成sakura的url，应该是`http://localhost:5000/v1`

用其他方法可以了，但是因为prompt不一样导致翻译结果有挺大区别

**Comment by lhj5426** [comment]
我个人建议是想要更精细的话 最好是文本排序 然后导出TXT 然后去用
https://github.com/neavo/KeywordGacha
提取人名翻译 统一
然后去导入
https://github.com/NEKOparapa/AiNiee
并进行TXT翻译
最后再导入TXT回到ImageTrans
ImageTrans开发者给了 用户极大的自由度使用空间 
虽然这样很罗嗦 跨越了多个软件但是效果好很多
然后在进行 看 或者润色 精细嵌字

**Comment by xulihang** [comment]
我用LM studio加载sakura试了下，默认的批量翻译的prompt不行，需要在偏好设置里取消勾选一次请求翻译多个句子。

批量翻译可以用外部工具
