### ISSUE TITLE
when i use Batch translation OCR skip JP language [jp > ko]

### ISSUE THREAD

**Issue by bravehon** [xulihang/ImageTrans-docs#8]
[jp > ko]
I use batch but it has some error like this can check that?

https://imgdb.in/igRy
https://imgdb.in/igRz

I use PAPAGO  API

**Comment by xulihang** [comment]
ImageTrans's azure is a free version which has a usage limit. You cannot OCR too many areas within a short period of time. You can apply for a premium version of Azure on your own or choose other options. Google and Sogou have good Japanese OCR results.

Since you are from Korean, you can also check out Naver's OCR service: https://www.ncloud.com/product/aiService/ocr. But since I don't have a Korean phone number to apply for it, you may have to implement your own OCR plugin.

**Comment by xulihang** [comment]
I just tried papago. It works okay. Please note that the language code of Japanese is ja, not jp.

**Comment by bravehon** [comment]
> I just tried papago. It works okay. Please note that the language code of Japanese is ja, not jp.

how can use clover OCR? I don't know how to that 
and.. can I upload batch translate video?? 
when open program setting font ...

**Comment by xulihang** [comment]
> how can use clover OCR?

You can apply for an API key of Clover and share the key with me to allow me creating a Clover OCR plugin. You can reset the key afterwards.

> batch translate video; teamviewer

Send the video to admin@basiccat.org. You can also use google drive, onedrive, etc. If you need me to control your computer, I may use teamviewer.

> Sogou OCR

If any OCR engines produces an error, it means an api key is required. Sogou OCR is not available for application from non-Chinese users. I am thinking about providing a subscription to solve this. But not in the near future.

**Comment by bravehon** [comment]
thank you for answer /

1. I have already that 
2. okay... I will that
3. okay..
4. my telegram is t.me/mangazang

**Comment by xulihang** [comment]
I just implemented the clova ocr plugin. You can download it: 
[clova_ocr.zip](https://github.com/xulihang/ImageTrans-docs/files/6007902/clova_ocr.zip)

Demo video:
https://user-images.githubusercontent.com/5462205/108463268-05fe4c00-72b9-11eb-8a4b-4f7fc063287d.mp4

**Comment by xulihang** [comment]
> I just implemented the clova ocr plugin. You can download it:
> [clova_ocr.zip](https://github.com/xulihang/ImageTrans-docs/files/6007902/clova_ocr.zip)
> 
> Demo video:
> https://user-images.githubusercontent.com/5462205/108463268-05fe4c00-72b9-11eb-8a4b-4f7fc063287d.mp4
