### ISSUE TITLE
竖排字体设置问题

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#801]
久违的更新了下软件，感觉bug少了好多，不过感觉字体逻辑发生了变化
刚刚嵌入好的文字变了样子。按照之前的设置也没有办法
似乎有些字体就可以但大部分都是这样子。所以想问下怎么解决捏
![image](https://github.com/user-attachments/assets/781d8f83-9d6b-4f79-9012-4d8fdfee2e74)

**Comment by hucurve** [comment]
升级了java版本，重启之后问题自然解决了。如果有遇到相同问题的人建议也升级下环境哦~

**Comment by xulihang** [comment]
竖排引擎，3.10.0增加了竖排内横排以及偏移量的设置，其它应该没什么改动

**Comment by xulihang** [comment]
我试了下，不设上边距是没问题的，设了后字会被切掉，我看下

**Comment by xulihang** [comment]
更新了3.13.1，应该没这个问题了
