### ISSUE TITLE
ChatGPT无法使用？

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#802]
我从3.6版本，升级到了最新的3.13版本
打开全局代理后。在同一个工程文件和同一偏好文件下同时进行辅助翻译
3.13无法返回结果，运行提示
(MyMap) 
{role=user, content=Translate the following into Chinese: 
ああ、あそこで女と一緒に歩いてる男だ跡つけて追うぞ}
ResponseError. Reason: , Response: 404 page not found
然后3.6版本可以正常运行

随后我又更换了国内的gpt镜像节点（api.chatanywhere.tech），3.6依旧可用，但3.13依旧无法使用

以上的国内翻译均可正常运行，此环境下gpt网页都可正确打开

我认为这似乎与 https://github.com/xulihang/ImageTrans-docs/issues/796 一致，难道不是网络问题？

**Comment by xulihang** [comment]
新版插件的参数改了，以前只要填`https://api.openai.com`，现在需要带上版本号：`https://api.openai.com/v1`

主要是为了使用豆包api

**Comment by hucurve** [comment]
改完了就解决了
