### ISSUE TITLE
请问验证服务器是否正在更新？

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#803]
目前无法激活？CN服务器提示超时，NE服务器直接提示未购买？可我每次都是这么激活的诶
![image](https://github.com/user-attachments/assets/e33794f9-ec39-45e7-b366-75c1912390bd)

**Comment by xulihang** [comment]
可能正好这个版本超过半年，需要购买更新版了

**Comment by hucurve** [comment]
哦哦我刚刚购买了更新包，但还是提示一样的内容诶

**Comment by xulihang** [comment]
要用买更新版后得到的新的订单号

**Comment by hucurve** [comment]
是用的新号码，哦原来还有个20分钟的延迟，点了好多次终于进去嘞
