### ISSUE TITLE
Google drive OCR

### ISSUE THREAD

**Issue by ZeroSum2000** [xulihang/ImageTrans-docs#804]
I followed everything on the website, but it came up like this.

https://github.com/user-attachments/assets/01d1f811-209e-49a6-a744-403d20755dd6

**Comment by xulihang** [comment]
You are not doing it correctly as in this blog: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/

**Comment by ZeroSum2000** [comment]
> You are not doing it correctly as in this blog: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/

I have followed all the steps of google drive api

**Comment by ZeroSum2000** [comment]
> You are not doing it correctly as in this blog: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/

And restart imagetrans it's mean close and open program right?

**Comment by xulihang** [comment]
> > You are not doing it correctly as in this blog: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/
> 
> And restart imagetrans it's mean close and open program right?

That's right.

If you've used the command line plugin, it will open the browser to ask you to verify your google account.

**Comment by ZeroSum2000** [comment]
> > > You are not doing it correctly as in this blog: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/
> > 
> > 
> > And restart imagetrans it's mean close and open program right?
> 
> That's right.
> 
> If you've used the command line plugin, it will open the browser to ask you to verify your google account.

![IMG_20241210_182505](https://github.com/user-attachments/assets/4db7430e-e06d-4123-94fc-e4d3ff5b0124)
Verify This page?

**Comment by ZeroSum2000** [comment]
> > > You are not doing it correctly as in this blog: https://www.basiccat.org/how-to-use-google-cloud-in-imagetrans/
> > 
> > 
> > And restart imagetrans it's mean close and open program right?
> 
> That's right.
> 
> If you've used the command line plugin, it will open the browser to ask you to verify your google account.

Can you remote to my PC or How to do it in more detail?
