### ISSUE TITLE
returning user. need recommendation

### ISSUE THREAD

**Issue by kokonoa** [xulihang/ImageTrans-docs#806]
Greeting!
So I have use ImageTrans in 2022. and it's pretty good back then, but I stop using it a little after my half a year update end.
But I have seen some impressive translation update with the chatgpt so I'm thinking on getting the new version and trying it again.

Please rec me the best plugin to use now. I use mangaOCR and mix MTL back then.

I have read this blog post. but I don't know how up to date is this one.
https://www.basiccat.org/best-practice-manga-ocr-and-translation/

I mostly will use it to translate manga from japanese to english

**Comment by xulihang** [comment]
Actually, the best practice does not have many differences.

You can also use ChatGPT in the old versions of ImageTrans by downloading the plugin: https://github.com/xulihang/ImageTrans_plugins

The latest version has many new features and bug fixes. I would recommend updating it to the latest version.
