### ISSUE TITLE
export ocr then import it again with translation

### ISSUE THREAD

**Issue by kokonoa** [xulihang/ImageTrans-docs#807]
Hello,
I export it into xlsx format from imgTrans. 
Can I import it back in xlsx format? I just put the translation in the next column after the ocr text source

**Comment by xulihang** [comment]
You can export a docx file, copy the translation in the xlsx file into the second column of the docx file and then import the docx file.

**Comment by kokonoa** [comment]
was hoping for xlsx since I want to filter the text source. I'll try the docx for now. thanks!
