### ISSUE TITLE
ChatGPT工作流翻译脱漏内容

### ISSUE THREAD

**Issue by hucurve** [xulihang/ImageTrans-docs#808]
同题目，我使用工作流chatgpt进行批量翻译
原来基本每一页都能翻译出来，现在漏翻译的越来越多
目前10页只有2也能成功翻到
我开的全局模式。GPT网页也能秒开
请问可以有什么参数上的调整？
或是可以实现翻译等待结果再进行下一张？
![QQ截图20241219142530](https://github.com/user-attachments/assets/e35e9738-85f4-4c77-8f5c-618ed2f1f4b7)

**Comment by xulihang** [comment]
用ImageTrans.bat打开软件，看看输出内容，是什么原因。

**Comment by hucurve** [comment]
这是一页最终未能成功的日志
(MyMap) {role=user, content=你是一个专业的日本漫画翻译家，请直接回复我翻译内容到中文（可能包含拟声词），无需其他叙述。Translate the following into Chinese: {"0":"まだまだヤンチャ盛りなんじゃないですか?","1":"あ、チ●ール食べてる動画もあったかな…","2":"はい…家中しっちゃかめっちゅかですよ?","3":"寝てるときはほんとに天使みたいなんですけど…","4":"ははｗ","5":"ん"}}
{"messages":[{"role":"user","content":"你是一个专业的日本漫画翻译家，请直接回复我翻译内容到中文（可能包含拟声词），无需 其他叙述。Translate the following into Chinese: {\"0\":\"まだまだヤンチャ盛りなんじゃないですか?\",\"1\":\"あ、チ●ール 食べてる動画もあったかな…\",\"2\":\"はい…家中しっちゃかめっちゅかですよ?\",\"3\":\"寝てるときはほんとに天使みたいなん ですけど…\",\"4\":\"ははｗ\",\"5\":\"ん\"}"}],"model":"gpt-4o-2024-08-06"}
{"id":"chatcmpl-CYIon1Zhpwq4cTjU4t8l7TIPrkP0lb2g","object":"chat.completion","created":1734861436,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"finish_reason":"stop","message":{"content":"1. 还不还是很调皮吗？\n2. 啊，可能还有吃巧克力 的视频吧…\n3. 是的…家里乱得一团糟?\n4. 睡觉的时候真的是像天使一样呢…\n5. 哈哈ｗ\n6. 嗯","role":"assistant"},"logprobs":null}],"usage":{"prompt_tokens":122,"completion_tokens":65,"total_tokens":187}}
(RuntimeException) java.lang.RuntimeException: JSON Object expected.
(StringIndexOutOfBoundsException) java.lang.StringIndexOutOfBoundsException: Range [-1, 77) out of bounds for length 77
(MyMap) {role=user, content=你是一个专业的日本漫画翻译家，请直接回复我翻译内容到中文（可能包含拟声词），无需其他叙述。Translate the following into Chinese: {}}
{"messages":[{"role":"user","content":"你是一个专业的日本漫画翻译家，请直接回复我翻译内容到中文（可能包含拟声词），无需 其他叙述。Translate the following into Chinese: {}"}],"model":"gpt-4o-2024-08-06"}
{"id":"chatcmpl-DvK0p3f2HsHBcTJu4V4bDkl09kTS2ib0","object":"chat.completion","created":1734861439,"model":"gpt-4o-2024-08-06","choices":[{"index":0,"finish_reason":"stop","message":{"content":"请提供需要翻译的内容，我将为您进行翻译。","role":"assistant"},"logprobs":null}],"usage":{"prompt_tokens":39,"completion_tokens":15,"total_tokens":54}}
(RuntimeException) java.lang.RuntimeException: JSON Object expected.

**Comment by xulihang** [comment]
你这自己改了prompt，没返回json格式的内容

**Comment by hucurve** [comment]
哦哦我可能直接复制粘贴把后面的不小心删掉了

重新补充了原始的命令时候大部分的页面都存在翻译，我勾选了尽量合并进行上传翻译，发现还有小部分页面因为某一句处罚和谐导致整页文字缺失

请问有什么办法可以尽可能其余正常的文子嘛，比如未返回批量结果进行逐句翻译之类的。我是用api付费的，如果直接全改成逐句翻译可能费用一下子就上来了

**Comment by hucurve** [comment]
或者我直接在手动把勾取消掉再跑一遍嘛，不知道会不会覆写掉之前翻译的内容

**Comment by xulihang** [comment]
被禁的内容还是会被禁吧，我看可以改prompt来突破限制，不过我没试过。

重新翻译会跳过已经有翻译的内容。

**Comment by hucurve** [comment]
哦哦问题解决了，页脱漏页面取消合并多句翻译之后再翻译一遍就补上了
