### ISSUE TITLE
能不能添加一个按钮一键复制当前图片

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#809]

**Comment by xulihang** [comment]
想要什么效果。目前右键是有复制功能的

**Comment by hyominli** [comment]
> 想要什么效果。目前右键是有复制功能的

我知道有，但是得点击右键，然后得小心翼翼地选择当前图片，选中复制，一不小心还会点到删除，非常麻烦

**Comment by xulihang** [comment]
这个功能使用频率一般不高，你需要经常用到吗

**Comment by hyominli** [comment]
> 这个功能使用频率一般不高，你需要经常用到吗

确实需要，希望大大搞个按钮在下面
![072BE580](https://github.com/user-attachments/assets/7336968d-0ebf-4663-8c4a-b3e80d9d62d8)

**Comment by xulihang** [comment]
3.14.1添加了复制当前图片到剪贴板的菜单项，可以自己绑定一个快捷键
