### ISSUE TITLE
点击排版模式有bug,会导致将所有区域的字体统一格式

### ISSUE THREAD

**Issue by hyominli** [xulihang/ImageTrans-docs#811]

**Comment by xulihang** [comment]
哪个版本，具体步骤是什么？这么多用户，一直没人报过，应该是你哪里操作不对

**Comment by hyominli** [comment]
> 哪个版本，具体步骤是什么？这么多用户，一直没人报过，应该是你哪里操作不对

![image](https://github.com/user-attachments/assets/b5ec71f5-32c8-4882-864d-ee03069cbff4)
![image](https://github.com/user-attachments/assets/6b486926-6c97-421a-85f4-24a89a79122d)
3.14版本，总之，现在我复现不了了，想问下这个应用于全部有什么作用

**Comment by xulihang** [comment]
应用于全部勾选时，修改字体样式会修改所有选中的文本框的样式
