### ISSUE TITLE
无法使用自动识别气泡功能

### ISSUE THREAD

**Issue by Firedoudou** [xulihang/ImageTrans-docs#82]
无法使用自动识别气泡功能，自动识别文字可以用，软件重新下载安装也不行

**Comment by xulihang** [comment]
默认的基于百度EasyDL每天有500次的次数限制，Azure也有速率限制。可以改用离线版，下载模型文件，放在程序目录里再在偏好设置里启用。文件可以在FastSpring购买邮件的附件里下载

**Comment by xulihang** [comment]
之前的相关issue：https://github.com/xulihang/ImageTrans-docs/issues/24
