### ISSUE TITLE
Text and Balloon are not recognized in long images

### ISSUE THREAD

**Issue by herrachamp** [xulihang/ImageTrans-docs#84]
I have long image files.
The software is not recognizing its text or balloon.
How can I make it work.
I have attached one image.
![Kisai Ent - 41-1](https://user-images.githubusercontent.com/85825674/132962289-41e220b2-ea91-48c1-80ab-fbd5551e38ec.jpg)

**Comment by xulihang** [comment]
Use the heuristic text areas detection, which is based on traditional image processing. The balloon detection and OCR API's detection use neural network, which are not suitable for long images.

**Comment by herrachamp** [comment]
Thank you very much. 🤗

**Comment by xulihang** [comment]
Balloon detection has been improved to support long images in v1.5.5: https://github.com/xulihang/ImageTrans-docs/issues/138
