### ISSUE TITLE
Support of OpenCV's high-level text detection and recognition 

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#85]
OpenCV has high-level text detection and recognition APIs: https://docs.opencv.org/master/d4/d43/tutorial_dnn_text_spotting.html

It supports DB, EAST and CRNN. It may be a good offline OCR option.

**Comment by xulihang** [comment]
A plugin is made: [OpenCV_OCR_plugin.zip](https://github.com/xulihang/ImageTrans-docs/files/7229638/OpenCV_OCR_plugin.zip)


Models are places under the model dir:

![image](https://user-images.githubusercontent.com/5462205/134769312-64e72569-3571-49d5-9deb-84e39070816d.png)


Users can use detection+recognition together or separately: 
![image](https://user-images.githubusercontent.com/5462205/134769442-cc53d01b-53ea-41ee-aa86-afbfb6f74e85.png)

**Comment by herrachamp** [comment]
where do I have to unzip the plugin?

**Comment by xulihang** [comment]
Unzip to the plugins folder under ImageTrans's folder.

**Comment by herrachamp** [comment]
I unzipped in the plugins folder but I can't see the OpenCV options.

**Comment by xulihang** [comment]
Restart ImageTrans first. The recommended version of ImageTrans is 1.4.5.

**Comment by herrachamp** [comment]
I am using 1.4.5 and tried restarting the app multiple times.
Is there any other settings required after unzipping the plugins.

**Comment by xulihang** [comment]
You also have to download the OCR models and put them in the models folder as shown in the screenshot above. The download links are given in the OpenCV's tutorial.

**Comment by xulihang** [comment]
The provided models are not very accurate. The text recognition is good only if the detected areas perfectly match every word.
