### ISSUE TITLE
batch heuristic detection sometimes freezes the whole application

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#89]
While actively using the batch heuristic detection, I've encountered a problem where the detection would sometimes freeze the whole application for as long as 10 or even 20 minutes.
The task manager shows it climb up to about 4 GB and then drop down to 2 GB again, which repeats in a loop.
I have 16 GB of ram, so I don't think it's a ram problem.

![Taskmgr_mww0rTCBTI](https://user-images.githubusercontent.com/90068423/137594729-ca6ab107-af56-49dc-889b-31f4ad0cdcbd.png)

**Comment by xulihang** [comment]
The heuristic detection may need manual adjustment, or it will spend a long time processing, especially for an image which has screen tones.

1. You can adjust the maximum and minimum height of connected components to filter out small and big ones to increase the speed.
2. Use gaussian blur if the image is very clear
3. Adjust binary threshold.

![image](https://user-images.githubusercontent.com/5462205/137608782-c4e55c96-3f6d-417e-86a9-e74b8b392eb8.png)

![image](https://user-images.githubusercontent.com/5462205/137608877-c07b838f-c804-4ab9-8b96-3ce57a713172.png)

**Comment by xulihang** [comment]
I've released a new version. The program will not freeze during heuristic detection, though it may still take time for some images using the default settings.

**Comment by Kamikadashi** [comment]
This seems to fix it, thanks!
