### ISSUE TITLE
how can Auto Change spacing to indent ?

### ISSUE THREAD

**Issue by bravehon** [xulihang/ImageTrans-docs#9]
1. I have some trouble I want auto that...
export txt and use cirl+H change and import thing?
how to convience change spacing to indent?
like Mantra Engine https://youtu.be/X3gRg6pOXBw

2. I have some Photoshop script,tool for translator. Could you please review if it will be useful as an image transfer tool??

P.S I

**Comment by xulihang** [comment]
I don't quite understand.

**Comment by bravehon** [comment]
??? where is my you tube link?  https://youtu.be/X3gRg6pOXBw?t=53 like Mantra Engine

**Comment by xulihang** [comment]
Could you give a screenshot of the specific operation?

**Comment by bravehon** [comment]
> Could you give a screenshot of the specific operation?

telegram t.me/mangazang...

**Comment by bravehon** [comment]
https://ac.namu.la/20210221/086bdf169d6ea59baa4f9b8b4efca6a5e24fea7c3fc0e3e1141797744f26f4fe.jpg

when use it like that 

I hope the translated word comes out in a vertical oval.
like https://youtu.be/X3gRg6pOXBw?t=53 this link

**Comment by xulihang** [comment]
You have to manually adjust this using line breaks.

```
一二三
四五六
七八九
十
```

For CJK characters, it may look better when the text alignment is set to left-aligned.

**Comment by bravehon** [comment]
Okay can suggest middle is sillmar text??
