### ISSUE TITLE
[Suggestion] Google Drive OCR

### ISSUE THREAD

**Issue by Kamikadashi** [xulihang/ImageTrans-docs#91]
You may know this already, but apparently there is a way to get Google OCR to work via Google Drive API without resorting to Vision API. Like here: 
https://tanaikech.github.io/2017/05/02/ocr-using-google-drive-api/
https://github.com/ttop32/JMTrans

This looks like a good option for complex backgrounds and white text that all offline solutions seem to struggle with. It would be cool to see this feature implemented. 
_Originally posted by @Kamikadashi in https://github.com/xulihang/ImageTrans-docs/issues/83#issuecomment-944832687_

**Comment by xulihang** [comment]
The plugin is added in v1.4.8.

**Comment by Kamikadashi** [comment]
I think it's worth mentioning that after the latest updates, Google Drive OCR stopped working for me. I tried redownloading credentials - to no avail. The culprit, it seems, is the new plugin that's bundled with imagetrans by default. It doesn't work with the old 'google_drive_ocr.jar' (the link above is dead btw). Replacing the new plugin with the old one seems to fix this. Placing '[google_drive_ocr_server.jar](https://github.com/xulihang/Google-Drive-OCR-Java/releases/download/builds/google_drive_ocr_server.jar)' in the folder didn't. I didn't try the command line one; maybe it works as well.

**Comment by xulihang** [comment]
I've updated the comment.
