### ISSUE TITLE
easyocr and paddleocr python scripts

### ISSUE THREAD

**Issue by Desmo5574** [xulihang/ImageTrans-docs#93]
I've installed both of these via pip on my linux system. 
Where do I run the .py server scripts from? Do I need to drop them somewhere and run them?

**Comment by xulihang** [comment]
You can find the scripts here: https://github.com/xulihang/ImageTrans_plugins/tree/master/paddleOCR/server

How to use:

1. Install bottle

```
pip install bottle
```

2. Start the server

```
python3 server_paddleocr.py 
```
