### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by zyfbis** [xulihang/ImageTrans-docs#97]

**Comment by zyfbis** [comment]
我本来想到了一个idea，可以做漫画的ocr加上翻译，但是用搜索引擎一搜才发现已经有人做了😂，而且完成度还这么高，令人惊叹；
虽然软件没有开源略显遗憾，但是还是支持下作者👍~

**Comment by xulihang** [comment]
谢谢，我用一个小众语言写的，开源了意义也不大
